### ISSUE TITLE
NSLog output for loaded videos isn't useful

### ISSUE THREAD

**Issue by nheagy** [JohnCoates/Aerial#1]
Seems AerialVideo should have a better description? 

https://www.dropbox.com/s/3w1fkrefd57hiz7/Screenshot%202015-10-26%2022.19.16.png?dl=0

**Comment by JohnCoates** [comment]
Oops, this was purely for debugging and slipped past me before release.

**Comment by JohnCoates** [comment]
Fixed in https://github.com/JohnCoates/Aerial/commit/230d93d2fe135b5557080255f67c613ef7a9c61b

**Comment by nheagy** [comment]
Ha! I was going to submit a PR. You're faster than me :smile:
