### ISSUE TITLE
"Aerial.saver" Needs to Be Signed

### ISSUE THREAD

**Issue by philipamour** [JohnCoates/Aerial#10]
![screen shot 2015-10-27 at 1 01 42 pm](https://cloud.githubusercontent.com/assets/4676105/10758730/1d598086-7cab-11e5-8899-8d0a11e27ead.png)

**Comment by travislent** [comment]
This is gatekeeper in OS X stopping it. You have 2 options.  You can right click the .saver file and select "Open" then the dialog will appear again but this time with another button labeled "Open". Click open. This will allow the application to run. The other option is to disable gatekeeper. In System Preferences, Select "Security & Privacy", On the "General" tab, in the lower section "Allow apps downloaded from:" select "Anywhere". You may need to unlock this pane using your admin password if the settings are locked.

**Comment by alistairmcmillan** [comment]
@philipamour Did you get this working?

**Comment by philipamour** [comment]
@alistairmcmillan @travislent Nope. I refuse to install any unsigned apps. Asking users to disable protection against malware or install unverified apps is a horrendous thing to do. Had to go through the code and compile and sign it myself.

**Comment by alistairmcmillan** [comment]
Fair enough, but you don't need to disable Gatekeeper. Personally I hate when people recommend that.

You can just right-click and choose Open to allow it through.
