### ISSUE TITLE
which format for MacBook Pro 16

### ISSUE THREAD

**Issue by stevenrisman** [JohnCoates/Aerial#1000]
love the aerial screen saver. can you please help me with which format I should be using. I know the MacBook Pro doesn't have a 4k screen , I have the most upgraded model with 64ram . can you please advise. HDR,1080,4k?? no clue

**Comment by glouel** [comment]
Hi @stevenrisman 

With the latest, you can pick anyone you wish. 

4K HDR may have slightly wild colors, but many think it's the best looking. 4K HEVC has slightly tamer colors if that's your thing.
