### ISSUE TITLE
Video stops often after round 30 Sec.

### ISSUE THREAD

**Issue by megaholti** [JohnCoates/Aerial#1001]
On Catalina, the video stops to play after round 30-40 Sec. The PC dosn´t freeze. The clock run. All videos are streaming. Internet connection is 300MBit/Sek

**Comment by glouel** [comment]
Hi @megaholti 

Streaming is pretty unreliable. It's not just about your connexion but also the servers. I highly suggest you cache the videos you wish to see, it will avoid that issue.
