### ISSUE TITLE
Pro Display XDR screensaver

### ISSUE THREAD

**Issue by hirothreading** [JohnCoates/Aerial#1003]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 13-inch MacBook Pro (2019, four Thunderbolt 3 ports)
- [ ] macOS version: 10.15.5
- [ ] Monitor setup: LG Ultrafine 4K
#### Description of issue / Feature request

Great work on Aerial. It's absolutely fantastic. Do you have plans on including the Apple Pro Display XDR screensaver?
See, for example:
https://www.youtube.com/watch?v=VDW_91egGis

Thanks!

**Comment by glouel** [comment]
Hi @hirothreading 

Sorry for the late reply. 

Aerial focuses on those specific "Aerial" videos. But you can add your own pretty easily, including this one ! 

Download that one from apple (found the link in the video comments here : https://www.apple.com/105/media/us/pro-display-xdr/2019/1e439996-d014-462a-94d6-f67407717b60/overview/hero/large.mp4 ) and follow instructions here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/CustomVideos.md

If you are using Catalina, make sure you read the big **warning** section about paths !
