### ISSUE TITLE
Custom Video Repository

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1004]
It might be cool/fun/useful to have a place here on the 'hub to share or link to custom videos along the lines of the Aerial ones (maybe just links; hosting/sharing might create rights and storage problems).

Yes, the Internet itself is a video repository. But Aerial videos are distinguished by certain hard-to-define characteristics, and it'd be fantastic to be pointed to lots more such videos by fellow Aerial users who recognize/appreciate those characteristics.

Impetus: I'm getting sick of all the Hawaii and Dubai videos....

For anyone reading along who's curious about how to add custom videos, see [here](https://github.com/JohnCoates/Aerial/blob/master/Documentation/CustomVideos.md).

**Comment by glouel** [comment]
This is a topic that comes around often, but sadly there are many legalities around that.  

> Impetus: I'm getting sick of all the Hawaii and Dubai videos....

I feel obligated to remind everyone that if you don't like a video, you can unselect it in the main Video tab, and it will no longer appear in your rotation. The UI is not particularly obvious and I'm currently working on improving that for 2.0 ;)

**Comment by Jimmbo** [comment]
No legal issues if it's just a repository of outbound links, though. OTOH I completely understand if this isn't something you're into. Everything can't be everything!

**Comment by zeromhz** [comment]
I've built my own server instance to host custom Aerial's videos. I'll remark that the core problem for many people will be cost of hosting. At the moment, that's the only reason I haven't released mine publicly. We're really lucky Apple is paying for the download costs on everything else here.

**Comment by glouel** [comment]
I think that when it comes to hosting, there are a few hosting company that don't charge for bandwidth at all. OVH here in France does have some really cheap plans with pretty much unlimited bandwidth allowed.

If there's good content to be hosted, from authors that would like to see them in Aerial, I could definitely put up a host for some extra videos and have them available in Aerial, with some sort of manual approval process (so I don't get into legal troubles).

**Comment by Jimmbo** [comment]
Hosting is a problem with many solutions. The harder question is finding Aerial-type videos to supplement the "official" Aerial videos. There's no good search term to winnow such videos out. 

I bet some small number of Aerial users have found a bunch. If we could establish a page or Wiki with outbound links (eg to YouTube),  the rest of us could individually figure out hosting solutions. And there's no legal issue, as a nexus of outbound links does not constitute intellectual property theft.

**Comment by zeromhz** [comment]
There's hosting, and there's hosting from a service with good enough distribution that it will be fast and work in all markets internationally. The one option that I had considered is publishing the videos as a GitHub release. The problem is this could lead to them being misused for other uses that I don't approve of. I may be an exception here, because I am a person and a business. jetsoncreative.com.

**Comment by glouel** [comment]
@Jimmbo to be clear by all means, if you want to start a list of links, please go ahead, I'd suggest starting with an issue (feel free to open a new one as I may have been a bit off topic on that one, sorry). 

If there's good resources and it catches on I'll see about opening a wiki or a page somewhere to keep the list updated.

**Comment by wbing** [comment]
Custom video cannot be displayed in versions 1.8 and 1.9

**Comment by glouel** [comment]
> Custom video cannot be displayed in versions 1.8 and 1.9

Are you running Catalina or Big Sur ? Your files must be in a non protected location to work, I suggest trying to add custom videos from `/Users/Shared`, this is a new sandboxing restriction to protect sensitive paths (documents, downloads, desktop, etc).

**Comment by Jimmbo** [comment]
It should be noted that v.2 adds this....great tools for finding/loading/curating third party vids.

**Comment by itslifesaidhe** [comment]
Heya, I added a custom video to custom source, it loaded but it says 0 videos found. Is there a list of requirements for videos to show up in a custom location?

![Screen Shot 2020-10-03 at 9 06 26 PM](https://user-images.githubusercontent.com/69947031/95006752-6c115d80-05bc-11eb-844b-5c7d38ffbf25.png)
![Screen Shot 2020-10-03 at 9 07 11 PM](https://user-images.githubusercontent.com/69947031/95006754-6e73b780-05bc-11eb-8b77-2ed59c39e993.png)

**Comment by glouel** [comment]
Close system preferences and open it up again. It will force the reload of your video
