### ISSUE TITLE
Catalina Keeps Flagging Aeriel as malicious software

### ISSUE THREAD

**Issue by BuckSurdu** [JohnCoates/Aerial#1007]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:  MacBook Pro
- [x] macOS version:  Catalina
- [x] Monitor setup:  Built-in monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Every time the screen saver tries to run, I get the error that this is software downloaded from the Internet.  I go to System preferences and say open it anyway, but then the next time it tries to run, I get the same error.  Is there anyway to make this software that Mac OS won't flag as malicious?

**Comment by glouel** [comment]
Hi @BuckSurdu 

Which version of Aerial are you using ? It sounds like you might be using an old version. That warning appears on old versions of Aerial that are not notarized. Can you check which version you have installed in the preference panel ? Open it and look bottom right of the screen where I circled : 

![Capture d’écran 2020-06-03 à 22 41 28](https://user-images.githubusercontent.com/37544189/83687045-7f4ef500-a5eb-11ea-90f7-ad1182e15a45.jpg)

You can get the latest version here : https://github.com/JohnCoates/Aerial/releases/download/v1.9.0/Aerial.saver.zip

**Comment by BuckSurdu** [comment]
That’s odd.  I just downloaded the latest version, I thought, but mine says 1.6.2.


On Jun 3, 2020, at 4:43 PM, Guillaume Louel <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @BuckSurdu<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_BuckSurdu&d=DwMFaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=NeR0ex4vrSfxqqPK6N3AFS1xuZD4KSkQqNSofgV7wXk&s=V0ghQR7s3SRgh3_XYBzxIh7WFnp5KbtINB8tmM6AW4U&e=>

Which version of Aerial are you using ? It sounds like you might be using an old version. That warning appears on old versions of Aerial that are not notarized. Can you check which version you have installed in the preference panel ? Open it and look bottom right of the screen where I circled :

[Capture d’écran 2020-06-03 à 22 41 28]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_37544189_83687045-2D7f4ef500-2Da5eb-2D11ea-2D90f7-2Dad1182e15a45.jpg&d=DwMFaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=NeR0ex4vrSfxqqPK6N3AFS1xuZD4KSkQqNSofgV7wXk&s=9cYvSxK32zZzOO7rMVwxO8hYZb1qKINkeOW5wmBkDWU&e=>

You can get the latest version here : https://github.com/JohnCoates/Aerial/releases/download/v1.9.0/Aerial.saver.zip<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JohnCoates_Aerial_releases_download_v1.9.0_Aerial.saver.zip&d=DwMFaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=NeR0ex4vrSfxqqPK6N3AFS1xuZD4KSkQqNSofgV7wXk&s=Cx9f-3VuBtCM430ADQ_NTguyLHjtY94auUvjga82keM&e=>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JohnCoates_Aerial_issues_1007-23issuecomment-2D638450990&d=DwMFaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=NeR0ex4vrSfxqqPK6N3AFS1xuZD4KSkQqNSofgV7wXk&s=Z5wEpwYyvT8YuKcAre__JynGnyquSzVSvONkmTErDHo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGFA26ZDEIFRXXMKGJ4VMITRU2YXLANCNFSM4NSAHKIA&d=DwMFaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=NeR0ex4vrSfxqqPK6N3AFS1xuZD4KSkQqNSofgV7wXk&s=zfrOkT2KKjI_0Gaqj6J8Zur20I9hzsN8uw1PmD4fMsI&e=>.




CAUTION: This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
The Original Sender of this email is noreply@github.com<mailto:noreply@github.com>



----------------------------------------------------------------------
CONFIDENTIALITY NOTICE: The information transmitted (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521. This transmission is intended only for the person(s) or entity/entities to which it is addressed and may contain confidential and/or proprietary material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient or have received this transmission in error, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by glouel** [comment]
First, close System Preferences (the whole window with the red button in the top left corner).  

Then download the latest, then double click `Aerial.saver` to install it (make sure it's not named `Aerial 2.saver` or something else, which may happen when you have another downloaded version in your ). You'll see System Preferences opening again, saying something like "You have an older version installed, do you want to install this one", say yes, then you should be good to go.

**Comment by BuckSurdu** [comment]
I just downloaded and installed 1.9.0.  We'll see if the problem goes away.  Thanks.

**Comment by glouel** [comment]
Feel free to reopen if you see the issue but that should be it.

**Comment by BuckSurdu** [comment]
It seems to be working fine.  Thanks for the quick help.

I don’t know why Apple just doesn’t make this part of the OS.


On Jun 5, 2020, at 7:48 AM, Guillaume Louel <notifications@github.com<mailto:notifications@github.com>> wrote:



Feel free to reopen if you see the issue but that should be it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JohnCoates_Aerial_issues_1007-23issuecomment-2D639432773&d=DwMCaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=51ugm0Vflj0yc3E2_4wpbuW5pjOAVHJcNc9Pv0SgU3Q&s=eD5z-UDTZykhasNnVXhCdQWSnZKuWGC244tnQ9vARPo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGFA26Z2K2DRLX2KQGK447TRVDLSNANCNFSM4NSAHKIA&d=DwMCaQ&c=LNH3PIPmtGmTzul0rfrdcEeADmk7jEnuwziVNAPeopM&r=Omz8HM-ZvzpmXpvmX5GAcQhroelQtiVRrqfXgTOVtMs&m=51ugm0Vflj0yc3E2_4wpbuW5pjOAVHJcNc9Pv0SgU3Q&s=-R_9Qf6MEJ5ly65-O8hFswlGtQ0C_cytDKPfHXKbNpU&e=>.




CAUTION: This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
The Original Sender of this email is noreply@github.com<mailto:noreply@github.com>



----------------------------------------------------------------------
CONFIDENTIALITY NOTICE: The information transmitted (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521. This transmission is intended only for the person(s) or entity/entities to which it is addressed and may contain confidential and/or proprietary material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient or have received this transmission in error, please contact the sender by reply e-mail and destroy all copies of the original message.
