### ISSUE TITLE
Add option to remove the "powered by Yahoo" logo

### ISSUE THREAD

**Issue by kavehv** [JohnCoates/Aerial#1009]
Having weather is nice, but I'm not a fan of the constant Yahoo advertisement on my screen.  Would it be possible to leave this out?

**Comment by glouel** [comment]
Hi @kavehv 

Sorry, I have no choice in this, it's part of their attribution guidelines that I have to adhere to in order to use their API : https://developer.yahoo.com/attribution/

**Comment by kavehv** [comment]
Bummer.  Here's hoping.  It's honestly a little puzzling that Apple hasn't sherlocked this screensaver, but it would suck if they did because it's unlikely they'd make it so configurable as you have 😀.

**Comment by glouel** [comment]
I actually thought they would last year, but thinking more about it, they'd hit a lot of the same issues I'm hitting, namely, the very poor support for 10bit HEVC decoding Intel CPUs (and the lack of GPU support on anything that's not a iMac Pro/Mac Pro of GPU decoding), and the bandwidth/cache issue. Having a screensaver that may download hundreds of GB when tethered (when macOS has no API that let you know if you are) is probably a big can of worm they don't want to open, I don't blame them ;)
 
It's fairly unlikely they'd make it as configurable, I could always rename it Aerial Pro if they do 🤣

**Comment by kavehv** [comment]
😂

Regardless, thank you for doing it.  I can't tell you how popular this screensaver is in the workplace (back before we were all WFH).  Even as recently as January people were asking me what screensaver I was using.

**Comment by apocolipse** [comment]
@kavehv if you change `Contents/Resources/white_retina.png` out with a blank transparent png, that get you what you want 😉.  Yahoo's guidelines apply to Developers, not end users 😀 Just don't redistribute it like that.
