### ISSUE TITLE
HD to 4K Conversion

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#1010]
Request For HD to 4K Seamless Switch. The idea here is better file management so that there are no duplicated files. 

[EDIT 1] Though I am imagining this from 2K to 4K it should be noted that it would apply to all formats: 
<img width="175" alt="Screen Shot 2020-06-06 at 8 08 03 PM" src="https://user-images.githubusercontent.com/18543749/83956972-6e8fc080-a831-11ea-9919-5ecfe54fdfa1.png">
The setup is this: I currently have all the files I want used as a screen saver downloaded but in 2K (HD) format. I would like to upgrade those files to 4K content. 

**Current Behavior**
- If a user wants to switch from 2K to 4K videos, Aerial duplicates the files and does not overwrite when the 4K download occurs. 

**Suggested Behavior**
- Upon switching in settings from 2K to 4K, ask the user if they want to delete their current cached content to conserve space of duplicated items. 

This could either occur under the "Video Format" section:
<img width="383" alt="Screen Shot 2020-06-06 at 8 05 27 PM" src="https://user-images.githubusercontent.com/18543749/83956934-11940a80-a831-11ea-837e-b23fd7134a4a.png">

...Or it could occur when you choose to download a video that is already downloaded in another format:

<img width="277" alt="Screen Shot 2020-06-06 at 8 05 57 PM" src="https://user-images.githubusercontent.com/18543749/83956946-240e4400-a831-11ea-9ff3-e6636f7b127c.png"> (2K Content downloaded)
<img width="244" alt="Screen Shot 2020-06-06 at 8 05 52 PM" src="https://user-images.githubusercontent.com/18543749/83956954-2bcde880-a831-11ea-9a3e-78e9dea58c24.png"> (4K Content not downloaded)

The suggested behavior here still gives the opportunity for the user to keep both files if that is what they prefer, but I cannot imagine a situation where someone wants both (or in some cases up to 5) versions of the same video.

**Comment by glouel** [comment]
Hi @ZV00 

So, right now I'm currently working on a big rework of that UI and the cache system. I do have a pretty long post here describing what I'm up to : https://github.com/JohnCoates/Aerial/issues/1006

When it comes to this, a format switch, my goal is, assuming you have a rolling cache, purge everything that is not compliant with the new format and fill up the cache anew. I think that covers 99% of the use case.

People that don't want that can decide to disable the limit and Aerial will not touch their files. I think it's a good compromise that fits that issue, please have a look at that post and let me know.

**Comment by ZV00** [comment]
Hey @glouel,

I missed that post, but I will head over there and take a look! And yes, that does seem like an adequate fix to me for this!
