### ISSUE TITLE
1.91 Won't run on 10.15.5

### ISSUE THREAD

**Issue by DHKaplan** [JohnCoates/Aerial#1012]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: iMac (Retina 5K, 27-inch, Late 2014)
- [ ] macOS version: 10.15.5
- [ ] Monitor setup: iMac main display, 2nd display of Samsung Monitor
 - [ ] Version 1.9.1 Aerial
If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / 
2 errors:
1) screen saver doesn't run, instead shows a black screen saying I can't run the screen saver with this version of MacOS and to contact developer.
2) hitting options gets the error message : You can't open the applicant ScreenSaverEngine.app because it may be damaged or incomplete.

**Comment by DHKaplan** [comment]
Screensaver had been  working fine for months, and just this week I noticed it had problems.

**Comment by glouel** [comment]
Hi @DHKaplan 

Sorry about that, Catalina can be weird with screensavers although I'm not 100% sure I understand exactly what you get, so let me ask a few questions.
 
> 1. screen saver doesn't run, instead shows a black screen saying I can't run the screen saver with this version of MacOS and to contact developer.

So just to clarify, you have this message full screen instead of Aerial when your computer goes to sleep ? Could you possibly make a picture of it and attach it here ? I don't think I've seen that one. 

> 2. hitting options gets the error message : You can't open the applicant ScreenSaverEngine.app because it may be damaged or incomplete.

Do you mean you see this in the tiny preview above the button, or do you get an alert after clicking the button I circled ? 

Next question, do you have another 3rd party screen saver installed on your system, or recently installed one ? 

That should narrow it down a bit and I'll try to help you figure it out from here, thanks.

**Comment by DHKaplan** [comment]
Bonjour Guillaume,

I should have remembered the great fixer for macOS. I had to reboot my Mac for something else and now the screensaver works fine, so I can’t show you the error messages, but for future reference:

To try to explain more fully, 
1) The screensaver started, but showed a black screen with the white lettering moving around saying screensaver engine wouldn't run with my version of macOS and to contact the developer.

2) Hitting Options caused a popup message box saying " You can't open the application  ScreenSaverEngine.app because it may be damaged or incomplete."

3) I do have another 3rd party screensaver installed, but I haven't used it for years, and nothing new was installed. Aerial had been working fine for months until a day or so ago...

Thanks so much to the developers for a great program.

David

**Comment by glouel** [comment]
Hey @David

I'm a bit surprised by the `ScreenSaverEngine.app` error, since it's a system file. So it might just have been macOS having a hickup here... I can't remember having seen that message in a while or at all full screen. Please keep an eye on it and let me know if this comes back as this is definitely weird. 

10.15.5 and the beta seems to have some weird random issues (on top of all the classic ones) with screensavers, so that might be part of it. Hopefully in a week there will be good news at WWDC...

**Comment by jiaweihli** [comment]
I just installed Aerial after upgrading to 10.15.5 on a Mac Mini that's pretty minimal (haven't made any dirty symlinks/edits to any system files).  When I lock the screen via ctrl-option-q, the screensaver doesn't seem to activate.  I'm dropped instead into the lock screen.

**Comment by glouel** [comment]
> I just installed Aerial after upgrading to 10.15.5 on a Mac Mini that's pretty minimal (haven't made any dirty symlinks/edits to any system files). When I lock the screen via ctrl-option-q, the screensaver doesn't seem to activate. I'm dropped instead into the lock screen.

What happens if you go here in System Preferences, what do you see in the picture, and what about the button I circled ? 


![Capture d’écran 2020-06-14 à 13 39 16](https://user-images.githubusercontent.com/37544189/84592280-bf607400-ae44-11ea-93e8-483f84e219ba.jpg)

**Comment by r8ders2k** [comment]
FWIW, I have a Mac mini (Late 2012) running Catalina, connected to a Thunderbolt Display, with no problems.

**Comment by jiaweihli** [comment]
> What happens if you go here in System Preferences, what do you see in the picture, and what about the button I circled ?

I see the aerial screensaver and the button has its default text.
Weirdly enough, it looks like Aerial works if my screensaver naturally comes on via inactivity.  The issue is that jumping to lock screen doesn't work for Aerial.

**Comment by glouel** [comment]
> > What happens if you go here in System Preferences, what do you see in the picture, and what about the button I circled ?
> 
> I see the aerial screensaver and the button has its default text.
> Weirdly enough, it looks like Aerial works if my screensaver naturally comes on via inactivity. The issue is that jumping to lock screen doesn't work for Aerial.

@jiaweihli I can't say I've ever used the lock screen shortcut before, but a couple of thoughts : 

- I did set a 1st party screensaver from Apple, and Lock Screen doesn't start that screensaver either, I do get the lock screen
- The way I always done what I think you want, was to use the suspend command from the macOS menu, this one highlighted : 

<img width="338" alt="Capture d’écran 2020-06-17 à 12 50 04" src="https://user-images.githubusercontent.com/37544189/84889473-34c48280-b099-11ea-9d25-c67a258c36eb.png">

I have no idea if Catalina changed what happens in Lock Screen (they might have) but that doesn't seem to be an Aerial thing as Aerial doesn't act differently than a 1st party screen saver it seems.
