### ISSUE TITLE
Problem in Big Sur with Screen Saver Options hot corner

### ISSUE THREAD

**Issue by tomwolsky** [JohnCoates/Aerial#1014]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 2019 16" MacBook Pro
- [ ] macOS version: 11b1
- [ ] Monitor setup: MBP monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

When I select a video and go to the hot corner to preview the screen saver (one word or two), the screensaver works, though the clock doesn't, and I can't get out of it until the system goes to sleep. I know it's a beta OS but we have to start somewhere. Thanks,

**Comment by glouel** [comment]
Hi @tomwolsky !

Which version of Aerial are you using, 1.9.1 or an older version ? If you haven't, I'd suggest updating to 1.9.1 right away.

If I may, some questions to try and narrow it out and make sure I'm getting things right. Were you using Aerial in Catalina already and it's now misbehaving in Big Sur, or is it your first time installing?

You mention the clock, are you talking about the red thing I circled, or Aerial's own : 

![Capture d’écran 2020-06-24 à 15 25 12](https://user-images.githubusercontent.com/37544189/85565140-2a712e00-b62f-11ea-861a-3860cd74dc7a.jpg)

If you are talking about Aerial's own, do you see it in the tiny preview (the one I circled in green ?) or not there either ? 

You mention being unable to quit Aerial, I assume by pressing a key or trackpad right ? I do have to ask the mandatory, are you using Little Snitch (or another firewall) ?

If you are, in Aerial's "Updates" tab, 
![Capture d’écran 2020-06-24 à 15 30 53](https://user-images.githubusercontent.com/37544189/85565899-d450ba80-b62f-11ea-9b03-71e1a29772e0.jpg)
 
Usually that's the cause of most of the issues. If that fixes it, we'll see about fixing Little Snitch settings. 

Here so far, I've noticed that, Aerial or not, watch unlock pretty much never triggers (maybe 1 out of 10 times) but I always get the password prompt after it fails trying, so that's a bit different than your issue. 

Let me know and we'll go from here 

(and many many thanks !)

**Comment by tomwolsky** [comment]
> On Jun 24, 2020, at 08:36, Guillaume Louel <notifications@github.com> wrote:
> 
> 
> Hi @tomwolsky <https://github.com/tomwolsky> !
> 
> Which version of Aerial are you using, 1.9.1 or an older version ? If you haven't, I'd suggest updating to 1.9.1 right away.
> 
> 
I’m using 1.9.1. 
> If I may, some questions to try and narrow it out and make sure I'm getting things right. Were you using Aerial in Catalina already and it's now misbehaving in Big Sur, or is it your first time installing?
> 
> 

I have Aerial in Catalina. The problem seems to be in Big Sur. 
> You mention the clock, are you talking about the red thing I circled, or Aerial's own :
> 
>  <https://user-images.githubusercontent.com/37544189/85565140-2a712e00-b62f-11ea-861a-3860cd74dc7a.jpg>
> If you are talking about Aerial's own, do you see it in the tiny preview (the one I circled in green ?) or not there either ?
> 
> 
I see the on the screen, hours, minutes, seconds, but it doesn’t move. Time is frozen. 

> You mention being unable to quit Aerial, I assume by pressing a key or trackpad right ? I do have to ask the mandatory, are you using Little Snitch (or another firewall) ?
> 
> 
No Little Snitch or Firewall. I tried escape, tapping the trackpad, other keys, even Opt-Cmd-esc wouldn’t open. 

> If you are, in Aerial's "Updates" tab,
> 

Updates are set the check and show on screen.

The screensaver module in System Preferences seems a little wonky still. The sidebar is taking a really long time to load. 

Thanks very much.

All the best,

Tom

**Comment by glouel** [comment]
> I have Aerial in Catalina. The problem seems to be in Big Sur.

Ok !

> I see the on the screen, hours, minutes, seconds, but it doesn’t move. Time is frozen.

Are you saying it's stuck in both full screen mode and in the tiny preview from my screenshot ? If so, can you attach a screenshot of your Clock settings in Aerial, like this : 

![Capture d’écran 2020-06-24 à 16 44 27](https://user-images.githubusercontent.com/37544189/85578024-0830dd80-b63a-11ea-9920-e2a57bdc4326.jpg)

(you need to attach through Github's UI, you can't attach by email)

The clock being stuck usually happens on very old mac versions, so it's slightly puzzling. Big Sur is a bit inconsistent regarding version numbers too, it says both 11.0 and 10.16 (I think they went to 11 maybe a bit late in the cycle and may not have updated everything ?) here : 

![Capture d’écran 2020-06-24 à 16 56 13](https://user-images.githubusercontent.com/37544189/85580345-f0f2ef80-b63b-11ea-975a-85a46113c9d1.jpg)

I need to check what Aerial sees in it's macOS version checks to see if there isn't an issue here (although the clock somehow works for me, I need to check with 1.9.1).

> No Little Snitch or Firewall. I tried escape, tapping the trackpad, other keys, even Opt-Cmd-esc wouldn’t open.

Ok I didn't ask, does it happen 100% of the time by the way or some of the time ? 

Also could you try `Cmd-Opt-Shift-Esc` next time ? That's the force quit that usually works when a screensaver gets stuck ! 

> Updates are set the check and show on screen. 

Looks like you missed my edit, please uncheck all three that I had circled in red, and try again please. There were a few issues already in Catalina with the login thing unable to quit, for some just rebooting fixed it like here : https://github.com/JohnCoates/Aerial/issues/991 there's also this long thread but I never managed to truly get to the bottom of it as there seems to be many reasons : https://github.com/JohnCoates/Aerial/issues/828

One other I remember was issues with a thunderbolt dock, are you using one by any chance ?

> The screensaver module in System Preferences seems a little wonky still. The sidebar is taking a really long time to load. 

Yep it's really really slow here too ! Switching from Desktop to Screen saver is horrible right now here !

**Comment by tomwolsky** [comment]
> On Jun 24, 2020, at 09:59, Guillaume Louel <notifications@github.com> wrote:
> 
> 
> I have Aerial in Catalina. The problem seems to be in Big Sur.
> 
> Ok !
> 
> I see the on the screen, hours, minutes, seconds, but it doesn’t move. Time is frozen.
> 
> Are you saying it's stuck in both full screen mode and in the tiny preview from my screenshot ? If so, can you attach a screenshot of your Clock settings in Aerial, like this :
> 
> 
The time in the preview moves correctly. It’s when I go to the hot spot that it freezes.

>  <https://user-images.githubusercontent.com/37544189/85578024-0830dd80-b63a-11ea-9920-e2a57bdc4326.jpg>
> (you need to attach through Github's UI, you can't attach by email)
> 
> 

I really know very little about GitHub I’m afraid to say. I was wondering if you could point me to where to post the screenshot. (I’m back in Catalina at the moment.)
> The clock being stuck usually happens on very old mac versions, so it's slightly puzzling. Big Sur is a bit inconsistent regarding version numbers too, it says both 11.0 and 10.16 (I think they went to 11 maybe a bit late in the cycle and may not have updated everything ?) here :
> 
>  <https://user-images.githubusercontent.com/37544189/85580345-f0f2ef80-b63b-11ea-975a-85a46113c9d1.jpg>
> I need to check what Aerial sees in it's macOS version checks to see if there isn't an issue here (although the clock somehow works for me, I need to check with 1.9.1).
> 
> No Little Snitch or Firewall. I tried escape, tapping the trackpad, other keys, even Opt-Cmd-esc wouldn’t open.
> 
> Ok I didn't ask, does it happen 100% of the time by the way or some of the time ?
> 
> Also could you try Cmd-Opt-Shift-Esc next time ? That's the force quit that usually works when a screensaver gets stuck !
> 
> 
Thanks for that. 
> Updates are set the check and show on screen.
> 
> Looks like you missed my edit, please uncheck all three that I had circled in red, and try again please.
> 


Will do.

Thanks very much.

All the best,

Tom

**Comment by glouel** [comment]
> The time in the preview moves correctly. It’s when I go to the hot spot that it freezes.

This is intriguing. Next time you are in Big Sur, could you try pressing the "Preview" or "Test" button that's in this little preview, the one in green in that screenshot : 

![Capture d’écran 2020-06-23 à 17 01 24](https://user-images.githubusercontent.com/37544189/85420448-7eb6d800-b573-11ea-8103-a08bc91b6565.jpg)

I'm wondering if the clock is moving there too or not...

> I really know very little about GitHub I’m afraid to say. I was wondering if you could point me to where to post the screenshot. (I’m back in Catalina at the moment.)

No worries, just to be sure, to make a screenshot you probably know Cmd+Shift+5. To attach a screenshot on Github, when you post a comment, just drag the file to the text field and it will upload automatically, really easy ! You can also edit and drag the same way. 

> Thanks for that.

So far that shortcut worked 100% so let's hope !

I'll try 1.9.1 again here to see if I can replicate your issue in the meantime.

**Comment by glouel** [comment]
@tomwolsky I tried 1.9.1 and couldn't reproduce your issue, so just in case, I rebuilt the latest dev version with the Big Sur SDK, just to see if it helps. 

If you want to give it a shot, try this build : https://github.com/glouel/Aerial/releases/download/v1.9.5alpha3/Aerial.saver.zip

Be aware there's a new cache management feature in that one, so have a look at the Caches tab after installing as your cache settings will get reset.

**Comment by tomwolsky** [comment]
This works well at first look. Thanks very much Guillaume. 

All the best,

Tom
