### ISSUE TITLE
Some 4k videos are just black (macOS Catalina)

### ISSUE THREAD

**Issue by bondskin** [JohnCoates/Aerial#1015]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Air 13"
- [ ] macOS version: 10.15.5 
- [ ] Monitor setup: build-in display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I have selected only 4k videos and quality is 4k HEVC.
Some videos appear to be only black, others are played normally and as expected.
I don't cache videos, just streaming.
All other information (e.g. battery, weather, etc) are displayed correctly.

**Comment by glouel** [comment]
Hi @bondskin 

Streaming is really unreliable and may fail for a lot of reason, main one being the servers aren't configured to handle it, so it's really an unreliable hack and I really recommend not using streaming.

If you are concerned about cache size, next version of Aerial will revamp completely the cache options, you can now set a limit and (soon) will be able to periodically get your cache refreshed with new videos. 

You can find the latest builds here in this thread (it has the cache limit but not the refresh yet) : https://github.com/JohnCoates/Aerial/issues/1006

**Comment by bondskin** [comment]
thank you for your swift reply, the feature of the new version sounds promising and I will change my settings.

**Comment by zeromhz** [comment]
I believe this is actually fixable and not the servers fault. If downloads are limited to one stream at a time, this problem doesn't happen. From what I have observed it's not the server that is the cause here but something that goes wrong when multiple downloads are running at the same time. VideoDownload.swift 114 change streamCount = 4 to streamCount = 1. Alternatively, create an option to disable multi-downloads.

**Comment by glouel** [comment]
> I believe this is actually fixable and not the servers fault. If downloads are limited to one stream at a time, this problem doesn't happen. From what I have observed it's not the server that is the cause here but something that goes wrong when multiple downloads are running at the same time. VideoDownload.swift 114 change streamCount = 4 to streamCount = 1. Alternatively, create an option to disable multi-downloads.

@zeromhz this is quite possible, this is part of the old Aerial code I didn't write but from what I remember it splits the file in 4 chunks and "stream" all four simultaneously, increasing the chances of one failing and stalls on slow connections too. It's quite likely that a "pure" streaming approach (only using one thread) would be better. 

Downloads in Aerial no longer use this code path so it's less of an issue, I'll try to have a look at some point, but in general, streaming will very rarely occur in next version (maybe once at first launch if you don't go to settings, that's the plan per the other thread).

**Comment by zeromhz** [comment]
I should make it clear that I only experience this problem when selecting "Download All" or downloading multiple selected videos, not while streaming.

**Comment by glouel** [comment]
@zeromhz then it's probably a different issue. I'm not sure how you see a black screen while downloading though. Did you meant that your downloads get stuck in that case ?

**Comment by zeromhz** [comment]
Sorry, to be clear, random files end up partially downloaded. Once in this state, the app can't play the files, or re-download them, until they are deleted. The result is occasional black videos during playback.

**Comment by glouel** [comment]
This is super weird, I saw your other message, do you see this with your own server or Apple's ? I'm fairly sure I've never had a report of partially downloaded videos, or something like you describe. It's possible people didn't complain, but that would be surprising, I've had issues opened for far less. 

As far as I remember, things get persisted to disk only at the very end (that's how streaming work when you uncheck the old "cache video as they stream" that I ended up removing in 1.9.5alphas), so for example if you interrupt a streaming while the screen saver runs, the video won't get cached and won't be marked as downloaded. Things could be different with your own server though. 

The whole video download code is a lot messier than I remember, looks like I bolted a manager on top of the old VideoDownload class, that's definitely not how I remembered things 🙈 I may not have time to have a look before a couple of days but free free to open another issue so I can track this.

**Comment by zeromhz** [comment]
You know what, you are correct. I have only observed this with my own server and it may not be a problem with Apple's servers. I have a custom build I am using that references my server as an additional source. I fixed the problem in that build by changing streamCount to 1 as described above. I simply assumed this issue was describing the same problem.

**Comment by glouel** [comment]
No worries, the "streaming" (or downloads) in Aerial with Apple's server is just a very basic HTTP file download, done in one (in your case) or 4 chunks. I could see Aerial getting lost though depending on how you implemented yours. 

Here's the output from a single download : 

```
Starting download for content information

Starting 4 streams with 124250977 each, for content length of 497003909

last stream range: {372752931, 124250978}

Starting download for range bytes=0-124250977

Starting download for range bytes=124250977-248501954

Starting download for range bytes=248501954-372752931

Starting download for range bytes=372752931-497003909

connectionDidFinishLoading

connectionDidFinishLoading

connectionDidFinishLoading

connectionDidFinishLoading

Finished downloading!
```

Just curious, did you add your own manifest pointing to a basic http server too, or did something more intricate ? I could definitely see Aerial getting lost if your server doesn't give it the total content length at the beginning, for example.

**Comment by zeromhz** [comment]
I created an additional manifest and used the Custom Video format. It was remarkably straight forward to do with only minor modifications. There is no "server" in the code sense, it's just files hosted on a MaxCDN/StackPath instance.

The only real problem I had was the issue described in this bug which I assumed was either a server or encoding problem. I tried adjusting all sorts of parameters on the server, and also tried making all sorts of adjustments to the encoding. In the end I observed the behavior carefully and noticed that the stall/fail always happened right at the moment another download began. So I set streamCount to 1 and voila the problem was solved.

If you send me your e-mail address I can send you a build.

**Comment by glouel** [comment]
Awesome, I thought about adding some basic support for custom manifests in the future as this would solve this kind of user cases.

The Custom Video manifest could probably point to a http server as far as I remember, even though I don't think I explicitely allow it in the ui ;) I'll send you an email in a bit, thanks !

**Comment by zeromhz** [comment]
@glouel I just sent you an e-mail - it is long and from my non-public e-mail address, so check your spam folder if you do not see it shortly.
