### ISSUE TITLE
High CPU usage on 1440p resolution

### ISSUE THREAD

**Issue by erenesto** [JohnCoates/Aerial#1016]
Everythings normal if i usly on my mac. If i plug my secondary monitor which has 2560x1440 resolution , cpu going crazy. I tried 1920x1080 on my secondary monitor, there is no problem on that. But i am using it on 1440p. I tried all video formats. Any suggestion?

**Comment by glouel** [comment]
Hi @erenesto 

Which Mac model do you have ? 

And which format do you pick in Aerial ? 

Not every Mac can handle 2 videos simultaneously if you pick 4K in Aerial.

**Comment by erenesto** [comment]
hi @glouel 

My mac is 2017 model MacbookPro.

If i use only macbook ✅
If i use my macbook with my secondary monitor(1920x1080) ✅
If i use my macbook with my secondary monitor(2560x1440) ⛔️ cpu going crazy.

I am using 1080p H264 normally but i tried every format, still same issue.

**Comment by glouel** [comment]
> If i use my macbook with my secondary monitor(1920x1080) ✅
> If i use my macbook with my secondary monitor(2560x1440) ⛔️ cpu going crazy

From Aerial's standpoint there's no difference between those two. 

Just to be clear, in that case you run the video on both your internal monitor and the external screen, right ?

Also, does the video stall, do you see hiccups, or does it play correctly but it's just the CPU spinning ? And which version of macOS are you using ?

**Comment by erenesto** [comment]
It plays correctly. I have just cpu problem. I'm using Catalina 10.15.5

**Comment by TommyCardello** [comment]
Same, but with MBP 16 base. 

CPU temp goes to 80 C.

**Comment by glouel** [comment]
@TommyCardello do you mean 16 inch or 2016 ? If 2016, 4K videos will tax your CPU as it doesn't support hardware decoding. Aerial tells you what your Mac safely supports (click the ? next to the video format). 

To both please try to open an Aerial video with Quicktime (not another player). You can find the videos from the caches tab. Try opening one (or as many as you have screens) and load Activity Monitor, you should get an explanation what's happenning.

In @TommyCardello's case, probably CPU usage, it could well be a GPU usage issue for @erenesto though, I'm still not super clear about what's happening here for you.

**Comment by vdenisla** [comment]
I am experiencing the exact same issue. I have uninstalled aerial 2.0.4 and re-installed the older 1.9.2 and the problem went away.
There is definitely something wrong with v2.0.x.
My config is MacBook Pro 2017 running latest Catalina version and secondary display in extended mode with 1440p resolution.

**Comment by glouel** [comment]
@vdenisla there seems to be a specific issue with dual screens and 2.0.0s, I'm collecting information in this thread here which I suggest your check. I also posted a tentative build with a fix if you feel like trying it : https://github.com/JohnCoates/Aerial/issues/1077

So far this seems specific to some 2+ screens configurations. I'm trying to investigate but since I can't reproduce this here I need some help from people who are experiencing the bug to test my tentative fixes. Thanks!
