### ISSUE TITLE
Catalina 10.15.6 - Unable to exit screen saver

### ISSUE THREAD

**Issue by kvellano** [JohnCoates/Aerial#1024]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
- [x] macOS version: 
- [x] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

1) Installed latest version
2) Have hot corner configured (lower right) to enable screensaver
3) After enabling, unable to exit screensaver with mouse or keyboard. Tapping the power button (Touch ID) allows me to exit

2018 MBP 15" i7 2.6ghz 16GB RAM
Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB
macOS Catalina 10.15.6
OWC TB3 Dock
2x Dell 24" U2415H

**Comment by glouel** [comment]
Hi @kvellano 

This may be the auto update, could you go into the Updates tab and uncheck the 3 things circled here : 

![Capture d’écran 2020-06-24 à 15 30 53](https://user-images.githubusercontent.com/37544189/85565899-d450ba80-b62f-11ea-9b03-71e1a29772e0.jpg)
 
Let me know if that fixes your issue, the auto update thing is known to misbehave on some configurations.

**Comment by kvellano** [comment]
Issue occurs without dock attached

**Comment by kvellano** [comment]
That fixed it @glouel ! Thank you!

**Comment by glouel** [comment]
@kvellano awesome. FYI, with 2.0, I'll be removing the auto updates from the screen saver to definitely fix that issue and put it in a separate app.

**Comment by acitrano** [comment]
FWIW this happens in Big Sur Beta 2 and 3 as well, and appears to have the same solution.

1. Latest version installed (1.9.2)
2. Hot corner configured to enable screensaver
3. After enabling (with hot corner or through idle timing), unable to exit screensaver with mouse or keyboard. Tapping the power button (rear of iMac) allows me to exit

2014 iMac 27" i7 4ghz 32GB RAM
Radeon R9 M295X 4 GB
macOS Big Sur Beta 3 (20A5323l)

Disabling auto-update as suggested by @glouel seemed to remedy it. If issue reappears, I'll update.

**Comment by glouel** [comment]
@acitrano it seems to happen a lot more often in Big Sur. I ended up removing Sparkle for v2.0 to definitely fix that issue.

**Comment by glouel** [comment]
Closing this, with the release of the latest beta that fully removes Sparkle and fixes this bug : https://github.com/JohnCoates/Aerial/releases/download/v2.0.0beta1/Aerial.saver.zip
