### ISSUE TITLE
Why I cannot download the videos?

### ISSUE THREAD

**Issue by DavidMax2006** [JohnCoates/Aerial#1025]
I'm in `China`. When I tried to <kbd>Download All</kbd> , it downloaded a few videos and then, **no any progress**. I checked my internet speed - 0kb/s! I canceled it and started again, then still 0kb/s and no any progress. 
How can I fix that? Thanks a lot.

**Comment by glouel** [comment]
Hi @DavidMax2006 

It's my understanding that the servers hosting the videos are blocked in China. If you can use an alternate connection, I would suggest you do so. See here for more information : https://github.com/JohnCoates/Aerial/issues/933
