### ISSUE TITLE
1.9.2 still receive the message that is not compatible with Catalina

### ISSUE THREAD

**Issue by alex178ita** [JohnCoates/Aerial#1026]
Hi all,

Installed the latest version, but still see the message saying it is not compatible with Catalina when running.

Any idea ? Am I missing something ?

Thx

Alex

**Comment by glouel** [comment]
HI @alex178ita 

Do you mean this message : "You cannot use the Aerial screen saver with this version of macOS." in the preview ?

Please check here for how to fix that, it's a long standing macOS bug : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#very-common-issuesmacos-bugs

**Comment by alex178ita** [comment]
Thanks for pointing me there. It works now.

Alex

**Comment by glouel** [comment]
Awesome, enjoy Aerial !
