### ISSUE TITLE
Setting Pane Titlebar Not Long Enough

### ISSUE THREAD

**Issue by unbeatable-101** [JohnCoates/Aerial#1028]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Late 2013 iMac 21.5"
- [ ] macOS version: 10.15.5 (19F101)
- [ ] Monitor setup: Default Display

#### Description of issue / Feature request

![Screen Shot 2020-07-29 at 7 28 33 PM](https://user-images.githubusercontent.com/58151048/88864168-93ba0300-d1d2-11ea-98d1-0e1137e6a940.png)
The icon is not in the correct position

![Screen Shot 2020-07-29 at 7 27 42 PM](https://user-images.githubusercontent.com/58151048/88864172-94eb3000-d1d2-11ea-9636-86f3c470bdca.png)
I don not think that it looks good having the menu so far off to the side, it was better at the top.

**Comment by unbeatable-101** [comment]
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4998014/AerialLog.txt)


Here is the log if you need it.

**Comment by glouel** [comment]
> The icon is not in the correct position

Ha, forgot that one. Will fix for next build, that's part of the icons being handled differently on Big Sur than on other systems. 

> I don not think that it looks good having the menu so far off to the side, it was better at the top.

Noted, but I needed the sidebar for the videos so the tabs no longer made sense. It looks better/is more in its place in Big Sur with large controls : 

<img width="1152" alt="Capture d’écran 2020-07-30 à 01 56 54" src="https://user-images.githubusercontent.com/37544189/88865694-ce3e9280-d208-11ea-9f4f-eb9b3b09c93f.png">

**Comment by unbeatable-101** [comment]
I think what is making it look bad is that on older versions of MacOS the part that goes out of the settings pane does not have the rounded bar at the top. 
![Screen Shot 2020-07-29 at 8 10 48 PM](https://user-images.githubusercontent.com/58151048/88866135-c1557b00-d1d7-11ea-9a72-bbea336ab8ac.png)

**Comment by glouel** [comment]
So the corners are rounded in Big Sur, I'm not 100% sure why they aren't on older OSes. I'll have to check, I think this may be because I made the window resizable, I'll see if it's fixable.

**Comment by glouel** [comment]
Icon is fixed. As for corners, that's sadly how they look on modal sheets pre big sur, so nothing I can do here: https://github.com/JohnCoates/Aerial/releases/tag/v2.0.0beta2
