### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by unbeatable-101** [JohnCoates/Aerial#1029]
![Screen Shot 2020-07-29 at 7 49 56 PM](https://user-images.githubusercontent.com/58151048/88865020-b220fe00-d1d4-11ea-80ea-52a25cc807c7.png)

#### Description of issue / Feature request

Shouldn't the two 1.5 milestones be closed?

**Comment by glouel** [comment]
Yes, haven't used those in a while thanks.

**Comment by unbeatable-101** [comment]
No problem.

**Comment by unbeatable-101** [comment]
Related to this, there are some old branches as well

**Comment by glouel** [comment]
Ok I pruned those.
