### ISSUE TITLE
Second display is blank in 2.0.0beta1

### ISSUE THREAD

**Issue by vom513** [JohnCoates/Aerial#1030]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 2018 MBP 13 (Intel Iris Plus Graphics 655)
- [ ] macOS version: 10.15.6
- [ ] Monitor setup: 2 x LG Ultrafine 4k (TB3).  Lid closed on laptop.  2 active displays.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Congrats on getting to 2.0 - the UI looks nice !

Just installed 2.0.0beta1.  Was on 1.9.2 (?) before, both displays working as expected (I run with all displays, independent).  In 2.0.0beta1 - my secondary display stays black.  I have tried toggling the display setting as well to no avail.  Rebooted as well.  Will attach the AerialLog.txt file once I submit.  Thanks.

**Comment by vom513** [comment]
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4998106/AerialLog.txt)

**Comment by glouel** [comment]
Hi @vom513 

Looks like I broke that specific mode 🙈 I just checked here and replicated your issue, I'll track it down tomorrow, sorry about that. All the other modes work fine, which is even more weird, but I suggest you switch to one of those in the meantime. Thanks for the report !

**Comment by vom513** [comment]
Oh wow - thanks for the super quick reply !  No worries at all, glad you were able to confirm/replicate it at least.

**Comment by glouel** [comment]
FYI I found the bug, it was the same bug that caused the sidebar to not be expanded at startup in beta 1 !

I'll put up a beta 2 tonight with that fix amongst others.

**Comment by glouel** [comment]
@vom513 took a bit longer than I thought but build is here with the fix : https://github.com/JohnCoates/Aerial/releases/tag/v2.0.0beta2

**Comment by vom513** [comment]
Yep - looks good now.  Thanks much !
