### ISSUE TITLE
Info boxes don't work

### ISSUE THREAD

**Issue by unbeatable-101** [JohnCoates/Aerial#1032]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Late 2013 iMac
- [x] macOS version: 10.15.5 (19F101)
- [x] Monitor setup: Main Display

#### Description of issue / Feature request

None of the question marks work.
[Screen Recording 2020-07-30 at 6.04.31 PM.zip](https://github.com/JohnCoates/Aerial/files/5004005/Screen.Recording.2020-07-30.at.6.04.31.PM.zip)

**Comment by glouel** [comment]
Yep, I'll fix that in a subsequent beta, thanks !

**Comment by glouel** [comment]
This is fixed in the latest betas
