### ISSUE TITLE
Weather overlay not displaying

### ISSUE THREAD

**Issue by craigz** [JohnCoates/Aerial#1033]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Air (Retina, 13-inch, 2018)
- [ ] macOS version: MacOS Catalina 10.15.6
- [ ] Monitor setup: laptop display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

i've just manually deleted the older beta; installed Aerial Updater and with that installed 2.0.0beta3. after reviewing the new cache settings, etc i went back to other things. eventually when the screensaver activated i noticed the weather was no longer present. in overlays > weather i had 'use current' selected and clicked test.
my coordinates briefly flashed, followed by OAuthSwiftError.

so i changed location to 'Manually specify' and the location was already in place from a previous config i guess. clicking test (as well as the '?' button) does nothing. i also ran into the issue where i couldn't type in the text field, however reading issues in this repo i saw the clipboard suggestion, so i did the following:

- disabled weather overlay
- closed the pane and quit system preference
- activated aerial via the hot corner
- back to system prefs > aerial > overlays > weather

i confirmed my location was in place and clicked to enable weather and quit system preferences.

still, no weather, not in the small aerial preview window, nor when clicking preview, nor when activating via hot corner.

all i can see in AerialLog.txt is the error from 'use current':

```
2020-08-02 19:39:06.918 : === YW: Starting locationMode
2020-08-02 19:39:07.094 : The operation couldn’t be completed. (OAuthSwiftError error -11.)
```
and then periodically (i guess on relaunches, etc):

`2020-08-02 19:43:08.184 : === YW: Starting manual mode`

i've let it run for a while, went back to the desktop, let it activate on it's own, etc. however there's nothing further regarding yahoo weather in the log and it's just not showing on the saver.

nothing huge, but now you know!

best,

-c.

**Comment by glouel** [comment]
Hi @craigz !

And whoops ! I messed up, I made a new repository clone locally as I was having issues with the old one, but forgot to paste the secret API keys for yahoo... really sorry about that ! 

I'll put up a new beta tomorrow to fix that, in the meantime I suggest you disable weather to avoid the requests.

**Comment by craigz** [comment]
hey @glouel thanks for getting back to me so quickly! 

no worries, i've disabled weather for now and this will be a nice test (for me) of the updater alert & functionality as that is brand new to me. 
cheers!

**Comment by glouel** [comment]
HI again @craigz 

Beta4 is up with the fix, thanks again for the report. You'll let me know how the updater works for you ;)

**Comment by craigz** [comment]
worked as expected, thanks for the rapid fix! the updater did it's job and upgrading went without issue.

**Comment by glouel** [comment]
@craigz thanks a lot for confirming ! And glad to hear the updater works, FYI next version of the updater (later this week) will have a couple more options:
- Launch at startup
- Show in menubar (so you don't have to have one more icon up there)
