### ISSUE TITLE
Question: updates

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1034]
I'm confused about the updates options: 

1. Sparkle.
1. Homebrew
1. ArielUpdater

ArielUpdater seems nice, but kind of heavy weight. I personally would rather it happen automatically (thorough Sparkle?) or I will just update it through Homebrew. I don't understand what takes prescience and how to choose which thing is trying to do updates. If it matters, I'm running macOS High Sierra.

**Comment by glouel** [comment]
Hi @mbierman 

Sorry if this is confusing, 2.0 is still in beta and not officially released, so I haven't had a chance to cleanup the documentation to reflect the upcoming changes and everything.

Answering your question
- Sparkle : is gone from Aerial starting with 2.0 (including the betas), reason is, it simply can no longer auto update for Catalina and above and on top of not working, its causing issues where the you can't exit the screensaver on those OSes.

So from then on there will only be two options:
- Homebrew : that has been there for a while and will stay
- AerialUpdater : this is the alternative I made to replace Sparkle

It's still very early but it will be able to run a periodic background check (immediately quitting) in next build, so it will very much not be heavy weight. There's a long discussion in a pinned issue with the various issues that lead to writing AerialUpdater, I know running one more updater just for a screen saver is weird, but with the sandboxing restrictions imposed by Catalina and above, that's the best I can do. 

If you are bothered by it then go homebrew.

**Comment by mbierman** [comment]
Thank you so much! I didn’t mean to come off as a complaint. I love Ariel. Best screensaver I have ever had. 

Thanks for the explanation. This works for me!

**Comment by glouel** [comment]
No worries and thanks !

**Comment by mbierman** [comment]
@glouel sorry one more question... if I use homebrew to update, does that update the screensaver and videos? 

Many thanks.

**Comment by glouel** [comment]
Hey @mbierman 

So homebrew (or Aerialupdater for that matter) only updates the screen saver itself. 

For videos, it's the screen saver that periodically finds new videos when they come (sometimes I need to push an update, sometimes it will pick them on its own, depends). 

So whatever update method you use (including downloading manually), it has 0 impact on the videos you get.

The only difference between homebrew and the updater is that homebrew will not give you betas, whereas you can opt in to those in the updater.
