### ISSUE TITLE
Fresh install results in "You cannot use the Aerial screen saver with this version of macOS."

### ISSUE THREAD

**Issue by TXC** [JohnCoates/Aerial#1039]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MacBookPro16,2 (MacBook Pro 13" 2020 4 TB3)
- [X] macOS version: 10.15.5
- [X] Monitor setup: Lid closed, 1 Thunderbolt Display & 1 Dell U2715H

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Have tried to install the screen saver, both latest stable and beta release.
First through Firefox, then through Safari and through brew.
All results in this message.

I've CMD+Q the system preferences between all tries.

![image](https://user-images.githubusercontent.com/236697/90012666-1dbe9d00-dca4-11ea-9229-618a29c88ef1.png)

**Comment by glouel** [comment]
Hi @TXC 

Can you please close System Preferences (the whole window) and reopen it, leaving it selected ? It should then load. There's a bug with Swift screensavers that causes that message, see here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#very-common-issuesmacos-bugs

**Comment by TXC** [comment]
@glouel 

Done that.

**Comment by glouel** [comment]
Quick question, can you launch the screensaver if you use a hot corner ? Those are separate (system preferences and running as a screen saver) so it usually work, at least that's my understanding. That may narrow things a bit if it does/doesn't run. 

Could you try this : close System Preferences, open Console.app, then go to screen saver page again. Then look into the console, for warning/errors that may be relevant. You can filter by "Aerial", or more likely as you are running Catalina, by "legacyScreen". This might give me a clue of what's going on here. 

Thanks

**Comment by TXC** [comment]
I can't start the screen saver with a hot corner. It starts, but with the same message as the image.

In Console.app, i get no matches on: [ANY: Aerial], [ANY: aerial] or [ANY: legacyScreen]

**Comment by glouel** [comment]
And in Console.app, if you try to just show errors/warnings at that point in time (I mean when you click "Desktop & Screen Savers", is there anything showing ?

I'm wondering, can you go into `~/Library/Screen Saver/`(Aerial.Saver should be there, unless you installed for all users, in which case `/Library/Screen Saver/` but I would recommend trying installing for your user only). Then in Terminal try `xattr Aerial.saver`

I'm wondering if your file isn't quarantined for some reason, that may explain this.

**Comment by TXC** [comment]
Console.app doesn't show anything relevant, i think.

But when i click it in the preferences i get this:
![image](https://user-images.githubusercontent.com/236697/90023206-bdcff280-dcb3-11ea-8fdd-4a8d0abc19f1.png)


```
com.apple.lastuseddate#PS
com.apple.macl
com.apple.quarantine
```

**Comment by glouel** [comment]
Ha ! That's the weird moment where I ask how you *unzipped* your file. Basically, the .zip is notarized with Apple, but if you use a 3rd party extract tool, macOS may not check the notarization status and quarantine it. It's a bit weird, sorry about that. 

So running `xattrr -d com.apple.quarantine` should do the trick.

**Comment by TXC** [comment]
Since this is a new computer, unpacked today.

I just downloaded the file, double clicked the zip-file, and then double clicked in the saver-file and installed.

Can't see how it should be done otherwise.

---

```
$ xattr -d com.apple.quarantine Aerial.saver
$ xattr Aerial.saver
com.apple.lastuseddate#PS
com.apple.macl
```

Still the same error.
Shall look into this more when i get home.

**Comment by glouel** [comment]
This is super weird... I'll try to check if there's not an issue with the notarization of latest beta, but a few people downloaded it with no complaint. 

When you have time, my suggestion would be, first delete that file. Then use Safari, but first go into settings and make sure it has that setting I circled in blue checked below : 

![Capture d’écran 2020-08-12 à 16 07 53](https://user-images.githubusercontent.com/37544189/90025315-3df75780-dcb6-11ea-88dd-72bce6f5f873.png)

This way Safari does the unzip, and it will not quarantine the saver. Let me know how it goes when you have time and sorry for the bad experience.

**Comment by TXC** [comment]
@glouel a reboot resolved it all!

Thank you so much for your assistance and help!

**Comment by glouel** [comment]
Ha, sometimes macOS is really weird ! Glad to hear it's fixed and no problem, take care !
