### ISSUE TITLE
[Feature Request] Use secondary Displays only if one is connected

### ISSUE THREAD

**Issue by daletman** [JohnCoates/Aerial#1040]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 15" 2018
- [x] macOS version: 10.15.6
- [x] Monitor setup: 2x 4K LG USB-C

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I use the setting "Play Ariel on: Secondary display(s)" which does work fine. But it would be nice if it also falls back to "Main display" if there is no secondary display connected. Otherwise it doesn't play anything when I use my MacBook on it's own.

**Comment by glouel** [comment]
Hi @daletman 

I think that would be a pretty sensible default indeed to fallback in that case. 

I'll try to have a look when I have a sec and will let you know.

**Comment by DHKaplan** [comment]
Version 2.0beta12 has a typo in its "about" page. "Developped and maintained" should be "Developed and maintained"
<img width="655" alt="Screen Shot 2020-08-14 at 11 07 39 PM" src="https://user-images.githubusercontent.com/5953197/90304218-6e402100-de83-11ea-96bb-9e66a6344236.png">

**Comment by glouel** [comment]
>"Developped and maintained" should be "Developed and maintained"

Thanks, fixed for next beta !

**Comment by glouel** [comment]
@daletman sorry it took me so long, but I just released 2.1.1 with that fallback ! It's the default way that the secondary mode works now, so if you have that and no external display connected it will fallback to the main screen.
