### ISSUE TITLE
White dot in left bottom corner?

### ISSUE THREAD

**Issue by Eric-in-Hong-Kong** [JohnCoates/Aerial#1042]
Running Aerial on my Mac mini (2014) and my Macbook Pro (2012) and it's fantastic! Love the 4K videos and it's fairly smooth (I downloaded all videos).

However, I am wondering why there's a white dot in the left bottom corner in all the videos (regardless of chosen video format, fyi - I am currently using 4K HEVC, but I also noticed it in lower resolution formats). Not a big deal, but it's visible especially on my large 65" TV. Is there any way to fix this?

**Comment by glouel** [comment]
Hi @Eric-in-Hong-Kong 

Yep, sorry about that, basically it's a workaround for a video driver bug. See here for a discussion on the topic  : https://github.com/JohnCoates/Aerial/issues/1018#issuecomment-653026769

**Comment by Eric-in-Hong-Kong** [comment]
Many thanks for the quick response! Initially, I got worried that my relatively new TV already had dead pixels, but I read the other thread just now. Should be ok then ;)

**Comment by glouel** [comment]
I'll try to reinvestigate the issue at some point just in case, really don't want to give people a dead pixel fright ;)
