### ISSUE TITLE
YouTube gets broken after using screensaver

### ISSUE THREAD

**Issue by jnpatrick99** [JohnCoates/Aerial#1043]
Mac model: Mac Pro Late 2013
macOS 10.15.5
LG 4K

After a couple of sleep-wake cycles and some Aerial runs all YouTube videos in any browser on my Mac Pro stop playing - they display as still shots. It only happens with Aerial, if I switch to any other screensaver, no problems. I have to restart to make it work again. Is it a known issue?

**Comment by glouel** [comment]
Hi @jnpatrick99 

Can't say I've had such a report yet. It's very likely that this is a macOS bug with video playback on your specific configuration, those sometimes comes and go, you may want to give 10.15.6 a shot for example ?

**Comment by jnpatrick99** [comment]
Thanks, I'll try!

BTW new Aerial 2 freezes my Mac. I can see mouse cursor, but nothing else and the screen is black.

Also after restart Aerial 1 stopped working altogether. Black screen, but I can log back in. Probably now I'll need some time to restore it back. In any case thanks for the support!

**Comment by glouel** [comment]
Oh that's bad, sorry about that. Do you mean when the screensaver ran the first time in full screen mode, or when you clicked the settings ? 

To exit such a situation, you can press `Cmd+alt+shift+esc` should that happen in the future. Let me know if you have more information about what happenned.

**Comment by ZV00** [comment]
Hey @jnpatrick99, 

Depending on which 4K LG Monitor you have, this may be an issue specifically with your monitor. I have had similar issues with my LG monitor and have determined it is the monitor itself that causes this weird sleep/wake issue. If this is the case, can you restart your device, connect with either HDMI or USB-C, with HDR disabled, and *not* through an eGPU (if you have it) and see if it persists? If so, then it may be a separate issue, but i know for me those were the chains that caused a similar issue for me.
