### ISSUE TITLE
brew update not working

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1044]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini (Late 2012) 
- [ ] macOS version: 10.15.6 (19G2021)
- [ ] Monitor setup: 1

#### Description of issue / Feature request
`brew cask upgrade aerial` does not update from 1.9.2. to 2.0

**Comment by glouel** [comment]
I know sorry, having issues with homebrew on Big Sur right now, trying to fix !

**Comment by mbierman** [comment]
> I know sorry, having issues with homebrew on Big Sur right now, trying to fix !

No sweat! Thanks.

**Comment by glouel** [comment]
Been trying for an hour, it's just a mess on Big Sur and for some reason it no longer works in my Catalina machine either. If your homebrew work, you need `cask-repair` installed then its:
 `cask-repair aerial` 

when asked new version number: 2.0.0

and validate and hope it works :)

**Comment by mbierman** [comment]
If I have to install something to fix it (and it might not work) easier to just uninstall and reinstall. :) Thanks though!
