### ISSUE TITLE
Docs Should Offer More Guidance re: 4K HEVC vs 4K HDR

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1045]
Using (hallelujah) v2.0....

- [ ] Mac model: Mac Mini (2018)
- [ ] macOS version: 1.15.6
- [ ] Monitor setup: HP Z27

#### Description of issue / Feature request
Exploring the prefs, I was trying to figure out whether I should choose 4K HEVC or 4K HDR. The doc page ["About HEVC and hardware decoding, and HDR"](https://github.com/glouel/Aerial/blob/master/Documentation/HardwareDecoding.md) should be the right resource, but while it confirms that either format should work with my set-up, it doesn't offer guidance as to which is best. Since 4K HDR is the ultimate option, I assume it's the best quality, but that's just my speculation.

If you'd care to answer informally here, I can write up a polished version you may consider adding to that page.

**Comment by glouel** [comment]
Hey there!

You are definitely right, this part just covers compatibility. The problem with "what's best" is basically a matter of taste. Some people enjoy the HDR videos, some think the colors are crazy and unrealistic. I added a new setup thing where you can try both now and see what feels best which alleviates the issue a bit. 

But all this should be pointed out. If you want to write up something feel free and I'll add it, thanks for offering!

**Comment by Jimmbo** [comment]
I'm on it. Two things first:

1. How does user get back to the "setup thing"?

2. When I first set up Aerial, I set it to automatically download videos,  4K-only. I can't find that choice now. Can you help?

Unrelated: What the hell is global vibrance? There needs to be explanation of this stuff! Explain it informally to me here and I'll write copy.

**Comment by glouel** [comment]
> I'm on it. Two things first:
> 
> 1. How does user get back to the "setup thing"?

Right now you can't, but I should definitely add something

> 2. When I first set up Aerial, I set it to automatically download videos,  4K-only. I can't find that choice now. Can you help?

That's in Settings > Cache for auto download, Settings > Advance for format

> Unrelated: What the hell is global vibrance? There needs to be explanation of this stuff! Explain it informally to me here and I'll write copy.

Vibrance is a filter to make things pop , if you move the slider, you should see the effect on the images below, but yes it's a bit rough that one !

And take your time, I'm off to bed here, thanks for getting on this.

**Comment by Jimmbo** [comment]
[I'd put this on top of the page, since it's for newbies]

You have a choice of video formats, which you can set as a preference in System Preferences/Desktop&Screensaver/Aerial/Screen Saver Options/Advanced: 1080p H264; 1080p HEVC; 1080p HDR; 4K HEVC; or 4K HDR. 

They're listed in rough order of increasing quality, and you can check below about any constraints your set-up may present (just in general, if you see stuttering - non-smooth videos - choose a lower format). Some users dislike HDR, and find its colors unrealistic, so it's probably safer to choose HEVC, but, if you're curious, choose HDR  and see what you think!

**Comment by Jimmbo** [comment]
Re: global vibrance (can we rename it to "Color Pop"?), there are no "images below". [Here's a screenshot](http://i.imgur.com/Yjl9vtM.png).

**Comment by ZV00** [comment]
> Re: global vibrance (can we rename it to "Color Pop"?), there are no "images below". [Here's a screenshot](http://i.imgur.com/Yjl9vtM.png).

Hey @Jimmbo There should be images in that screenshot — Can you relaunch Aerial after the thumbnails cache (let Aerial sit open for a few minutes and then re-launch system preferences) and see if that persists?

**Comment by glouel** [comment]
One thing I reaaaaaaaaally need to add is that it only works on non HDR videos. I'm doing a quick update later today with some UI polish and various small fixes.

**Comment by Jimmbo** [comment]
I’ll add that note when I write it. Don’t sweat it for now

**Comment by Jimmbo** [comment]
Ok, that worked. 

Can you fix this, or do I need to explain all these contingencies in my copy for the "Filters" pane?

**Comment by glouel** [comment]
The documentation is updated and linked to in the setup page. I've heard you on vibrance.

But yes, the app is offering per video control. If you enable the Allow per video vibrance, there's a slider that lets you individually fix a video in the main UI.

<img width="419" alt="Capture d’écran 2020-08-21 à 00 28 20" src="https://user-images.githubusercontent.com/37544189/90832032-39314400-e345-11ea-91a3-d36f08edf39f.png">

**Comment by Jimmbo** [comment]
Sounds good, and docs look good.
