### ISSUE TITLE
New Set up

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1046]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini (Late 2012)
- [ ] macOS version:   10.15.6 (19G2021)
- [ ] Monitor setup: 1

I### Description of issue / Feature request
The new setup gives fewer choices for calculating location than the screen saver UI itself. I would suggest that they match or get rid of it in set up.

**Comment by glouel** [comment]
Yep, so my goal was to simplify things and remove some of the old options (like night shift detection which kinda works but only when it wants) but last minute I left them. I'll revisit this for next build and make them match cause the extra options make little sense today.

One thing I'll also add is the ability to pick how long the sunrise/sunset calculations are. Some of it was last minute (like really last minute) so just to give a bit of explanation, right now videos are categorized in 4 time segments :

- sunrise
- day
- sunset
- night

To make those calculations, I use the astronomical sunset/sunrise and add/substract 3 hours. So an example : 

04:49:20 <- astronomical sunrise
07:49:20 <- end of sunrise videos
20:15:12 <- start of sunset videos
23:15:12 <- astronomical sunset

So sunrise is between 4:49 and 7:49 here. I've been playing with the length for those sunrise/sunset and will give more options to adjust that in the future (4hr is nice too in summer, maybe not in winter).

So yeah, long story short, this need work :)

**Comment by mbierman** [comment]
Hmmm I like Night shift.

Since the mac already knows how I want to calculate day/night it is nice if the screen saver automatically follows suit. If I want to make an adjustment there is just one thing I need to change. 

Now maybe I'm not typical. My current mac is a desktop it doesn't travel about. If I traveled timezones I might feel differently.

**Comment by glouel** [comment]
The other option is basically the same, Aerial just asks macOS for your general location, which is how night shift calculates the sunset/sunrise times too (it's calculated every day based on location + date). It can then be used for weather too. 

Just to clarify (was rushing a bit yesterday), I'm talking about that specific option which is just another (pretty unreliable) way to get the sunset and sunrise times, so Aerial can then do its thing:

![Capture d’écran 2020-08-20 à 09 44 09](https://user-images.githubusercontent.com/37544189/90731480-085ff900-e2ca-11ea-8887-8472e345def3.jpg)

The first option on top is the "good one" and the one that I offer in the first time setup, just to go back full circle.

**Comment by mbierman** [comment]
I think I understand. But the first one requires giving Aerial for location permission. Using Night Shift does not. Given the option, I would use Night Shift.

**Comment by glouel** [comment]
@mbierman Ha I see ! I don't do anything with your location (Aerial has 0 data collection or anything of the sort) but I can respect that. I'll take that into account thanks.

**Comment by glouel** [comment]
@mbierman 

This is what I settled on. I removed manually entering coordinates but kept night shift for now : 

![Capture d’écran 2020-08-20 à 22 26 34](https://user-images.githubusercontent.com/37544189/90822270-77723780-e334-11ea-9c03-37e877c113da.png)

I've added a fancy bar at the bottom to give a visualisation of what plays when, which is going to make things a bit clearer. This will be in next build, maybe in an hour or tomorrow if I fall asleep on the keyboard ;)

**Comment by mbierman** [comment]
@glouel beautiful! 

Asthetic suggestion
![image](https://user-images.githubusercontent.com/1205471/90822694-add69500-e2e9-11ea-81ce-0e5cd92642f3.png)
Maybe a clock would be better?

**Comment by glouel** [comment]
That's a good idea, and I have the icon at hand too. So done :D

<img width="1107" alt="Capture d’écran 2020-08-20 à 22 36 40" src="https://user-images.githubusercontent.com/37544189/90823066-ab019180-e335-11ea-87c6-8439883cf115.png">

**Comment by mbierman** [comment]
AWESOME! Looking forward to it. :)

**Comment by glouel** [comment]
2.0.1 is out with the mentioned changes ;)

**Comment by mbierman** [comment]
`brew cask upgrade aerial` isn't working. :(

**Comment by glouel** [comment]
Yeah see the other thread, I still haven't managed to fix my homebrew on Big Sur (and with all the respect I have for the homebrew people, and complete understanding of their frustration by unexplained changes in a new macOS release, they could be a tiny bit more proactive on explaining the current status of things).
