### ISSUE TITLE
"Welcome to Aerial"

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1048]
Using (hallelujah) v2.0....

- [ ] Mac model: Mac Mini (2018)
- [ ] macOS version: 1.15.6
- [ ] Monitor setup: HP Z27

Aerial just randomly welcomed me a second time.

Problems:

1. No idea why it suddenly appeared.

2. The set-up area is great stuff. It should definitely be available on demand. 

3. Yes, now I see your "set up thing to compare image quality", but it's not practical for that purpose because when I choose a new video quality, I'm told it will delete all my downloaded videos. I don't want to do anything that extreme just to compare format qualities. I think you need a fooling-around experimentation pane (maybe including filters like vibrations) and THEN a pref-setting pane. It's confusing to do both in the same pane.

4. Copy change suggestion: "You can expand the video to full screen by passing your cursor over the video and choosing the arrow in the lower right corner". I hate that info icon, by the way. It's distracting (I keep clicking, figuring I'll get a definition pop-up or something), takes up screen space, and it's unnecessary. To offset guidance statements, I'd suggest simply italicizing them.

**Comment by glouel** [comment]
> Aerial just randomly welcomed me a second time.
> 1. No idea why it suddenly appeared.

That's a weird one.

> 2. The set-up area is great stuff. It should definitely be available on demand.

Yeah I'll add a button somewhere.

> 3. Yes, now I see your "set up thing to compare image quality", but it's not practical for that purpose because when I choose a new video quality, I'm told it will delete all my downloaded videos. I don't want to do anything that extreme just to compare format qualities. I think you need a fooling-around experimentation pane (maybe including filters like vibrations) and THEN a pref-setting pane. It's confusing to do both in the same pane.

Completely agreed, I shouldn't have added the alert in there, was just to workaround an issue I'll clean it up.

> 4. Copy change suggestion: "You can expand the video to full screen by passing your cursor over the video and choosing the arrow in the lower right corner". I hate that info icon, by the way. It's distracting (I keep clicking, figuring I'll get a definition pop-up or something), takes up screen space, and it's unnecessary. To offset guidance statements, I'd suggest simply italicizing them.

Good idea, it looks a bit dated too on Big Sur, I'll have a look. Thanks!

**Comment by Jimmbo** [comment]
"Welcome to Aerial" is still returning sometimes when I choose "Screen Saver Options" in the "Desktop & Screen Saver" pref panel.

**Comment by glouel** [comment]
I think I understand point 1 now, you probably closed the window using the button at the top left, and not the "Close" button that appear at the bottom of the window. In that cas it would pop again. This is fixed for next build.

Point 2 is implemented too, there's a button in advanced to launch setup again. 

3/4, on it. Depending on how long it takes me I'll post 2.0.1 with the changes tonight or tomorrow.

**Comment by glouel** [comment]
![Capture d’écran 2020-08-20 à 23 20 46](https://user-images.githubusercontent.com/37544189/90827057-d4252080-e33b-11ea-8c98-07376df3a262.jpg)

Fixing one last thing ;)

**Comment by Jimmbo** [comment]
If you add my new copy to the top of [this page](https://github.com/glouel/Aerial/blob/master/Documentation/HardwareDecoding.md), then I'd suggest adding this to the copy at left with a link to that page

(see **here** for more information on video formats)

**Comment by glouel** [comment]
Good idea, and yeah I will, trying to fix a ton of stuff right now so I'm having a hard time keeping track of everything.

**Comment by Jimmbo** [comment]
Maybe you should have a Trello rather than do this via Github?

**Comment by glouel** [comment]
I'm doing this on my spare time so I'd rather not get into Trello for this project. It's just a particularly busy day.

**Comment by Jimmbo** [comment]
It's good to feel anxiety. That perfectionism is the sign of a good dev. Just remember to take a breath so you don't get stressed. 

If you do get stressed anyway, then  something like Trello, even for a minor project, can help keep a minor project feeling minor.

Just my two francs, fwiw....

**Comment by glouel** [comment]
2.0.1 is out with the changes discussed.
