### ISSUE TITLE
Pane Closing Irregularity

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1049]
Small thing, but it's annoying.

Usually, you can hit Escape key to close "Screen Saver Options".  But if you choose "Screen Saver Options" and immediately hit Escape, you get a system beep and no closing.

If you select the "Community Videos" option and then hit escape, then it does close. If you go to another choice (like Brightness) and come back and hit escape, it does close.

**Comment by glouel** [comment]
Interesting, I'll have a look. There's a question of what is in focus, the beep implies that the panel may not have the keyboard focus so just clicking on it will bring it forward and then the Escape key will work, if you see what I mean ?

**Comment by Jimmbo** [comment]
Yes, of course that’s surely it. And it’s small, but these small things make a big difference. 

When I move into a new apartment, I make sure all the doors shut easily and the light switches work correctly.  If not, my entire life gets VERY slowly worse (if I were obsessive-compulsive, it would get QUICKY worse!)

**Comment by glouel** [comment]
It's not so much a question of small than it is of possibility. Basically the screen saver panel having focus or not is rarely something I can control, and depends on each version of macOS that has subtle bugs around this. I'll have a look, but this is not a small thing nor am I sure it can be fixed.

**Comment by Jimmbo** [comment]
Then not worth investing time. Unless there is some way  the focus can be on the other portion when the pane opens...

**Comment by glouel** [comment]
Escape key works fine here in Big Sur with latest version, on older OSes nothing more I can do.
