### ISSUE TITLE
"Downloading #%" in top right corner

### ISSUE THREAD

**Issue by zchjhnsn** [JohnCoates/Aerial#1051]
#### General troubleshooting tips

Before logging an issue please check that:
- [+] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [+] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [+] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [+] Mac model: MacBook Pro (13-inch, Mid 2012)
- [+] macOS version: 10.15.6 Catalina
- [+] Monitor setup: Laptop Monitor - Intel HD Graphics 4000 1536 MB

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Just got 2.0. Every time the screensaver loads is display "Downloading #%" in top right corner. I am assuming it's downloading the video but this is covering up the date and time I have in that corner. Is there a way to disable this? Sorry if this is already known. I tried looking for solutions.

**Comment by glouel** [comment]
Hi @zchjhnsn 

It wasn't reported yet but I'm adding an option to remove it later today ! Thanks for the report.

**Comment by glouel** [comment]
@zchjhnsn 2.0.1 is out with this indicator disabled by default :)
