### ISSUE TITLE
high cpu usage / fans active

### ISSUE THREAD

**Issue by craigz** [JohnCoates/Aerial#1054]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBookAir8,1
- [ ] macOS version: 10.15.6
- [ ] Monitor setup: built-in

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

running the 2.0 release (cheers!) and when i am either in the system preferences > desktop & screen saver > aerial settings window or when the screen saver itself is active, i can tell from the other side of the room because the fans are full-on screaming. this had happened in an earlier beta a while back and was resolved a release or 2 later. right now, i've sadly got it disabled on my air, because it's just too loud to do anything else when it's running :(

i've made no changes to any settings beyond marking a few videos as favorites, but i'm not constrained on disk space/cache size or anything like that.

**Comment by glouel** [comment]
@craigz can you go into Settings > Advanced and tell me which video format is picked at the top ?

According to my database your MacBook Air should be able to handle 4K HEVC, but maybe that was incredibly optimistic of me to think so (that's the format I suggested at first time install, very likely). 

So let me know which format you have and we'll go from there.

**Comment by craigz** [comment]
it says 4k HDR. i have not made any changes to that though so unless it was changed when i updated, i've been running the same format for months now.

**Comment by glouel** [comment]
It likely was yes at update. Pick 1080pH264 and you'll be good to go. Sorry for that one, I'll improve my detection/suggestion for next build !

**Comment by craigz** [comment]
ok, i've changed it and will let it be for a while. it went and downloaded a new video and for the minute or so i let it go there was no fan ramp up, so it seems that should do the trick. thanks.
