### ISSUE TITLE
Can't update with homebrew

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1058]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: macmini 
- [ ] macOS version: 10.15.6 (19G2021)
- [ ] Monitor setup: 1

`brew cask upgrade aerial`is failing to update to 2.0.1

`BigMac:bin michael$ brew cask reinstall aerial` 
also doesn't get 2.0.1
`Downloading https://github.com/JohnCoates/Aerial/releases/download/v2.0.0/Aerial.saver.zip`

I don't know if this is as it should be, but it seems odd to me. 

```
brew info aerial 
Error: No available formula with the name "aerial" 
Found a cask named "aerial" instead.

aerial: 2.0.0
https://github.com/JohnCoates/Aerial
/usr/local/Caskroom/aerial/2.0.0 (145B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/aerial.rb
==> Name
Aerial Screensaver
==> Description
None
==> Artifacts
Aerial.saver (Screen Saver)
```

2.0.0 is showing up and the name isn't a match?

**Comment by glouel** [comment]
So yeah, I still haven't fixed my issues with homebrew. Some gentle soul updated the cask to 2.0.0 yesterday, I don't know who, but they have my thanks. So right now until I fix my issues with homebrew I can't push the updates there at all. 

Regarding the misname with first command, it's because you used `brew info` instead of `brew cask info`:

```
$ brew cask info aerial
aerial: 2.0.0
https://github.com/JohnCoates/Aerial
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/aerial.rb
==> Name
Aerial Screensaver
==> Description
None
==> Artifacts
Aerial.saver (Screen Saver)
==> Analytics
install: 775 (30 days), 2,733 (90 days), 11,966 (365 days)
```

**Comment by netmute** [comment]
Just wanted to chime in and say that I do rolling upgrades with Homebrew every morning, and I have yet to encounter an issue.
