### ISSUE TITLE
Need an option to clear the cache

### ISSUE THREAD

**Issue by peterfou** [JohnCoates/Aerial#1062]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (16-inch, 2019)
- [x] macOS version: Catalina 10.15.6
- [x] Monitor setup: Display-port 1.4 to Dell U3419W 3440x1440
- [x] Aerial version: 2.0.1, just upgraded from 1.9.2 via `brew cask upgrade aerial`

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I can't find a way to clear the cache. When I installed 2.0, I got an error when I clicked on `Download Rotation` that I couldn't download new videos, because my cache is full. 
![image](https://user-images.githubusercontent.com/68914595/90910944-39156080-e3a6-11ea-8c4e-e705e6b78817.png)

I want to clear my cache to be below the 5GB mark, but I don't see a way to do that within the current version of the app.

**Comment by Amir-Hass** [comment]
My cache pane looks like this for some reason, and I cannot select an "On Rotation" to use.
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/5016531/92291107-ff377480-eee4-11ea-96ac-b39ff9c2d882.png">

**Comment by glouel** [comment]
@Amir-Hass you need to click "Automatically download videos"
