### ISSUE TITLE
Copy Edits for "Welcome" Screen

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1063]
_IMO you need to remember that users don't have .00001% of your familiarity with the app. When you say "settings", for example, they are lost...especially now that there are three places to configure Aerial (menubar, pref panel, and welcome screen). Until you can unify all into one single location (which I know is difficult and unlikely), you need to explain how to find a setting/parameter/feature whenever you mention it._

> A few tips, just in case...

Explaining Some Options  (in the sidebar of Aerial's "Screen Saver Options" within the Desktop & Screen Saver preference panel)

> You can quickly change which videos are playing using the new "On Rotation" feature.

Change video sequencing via the new "On Rotation" feature.

> Enjoying a video? Favorite it so it keeps playing.

Enjoying a video? "Favorite" it to make it play more frequently.
[I don't know if that's how it works; explain to me and I'll improve this]

> Not liking one? "Hide" it to keep Aerial from playing it (you can change your mind later).

Dislike a video? Tell Aerial not to play it (you can always change your mind).

> There's a whole new user interface by the way. You can even resize it!

Version 2 introduces a completely new user interface, by the way. You can even resize it!

> And yes, there are new videos! You can now enjoy some free videos provided by third party artists on top of the classical Aerials, check the Custom Sources in Settings for more details, and how to support them for their work.

And there are new videos! These are provided by third party artists, some free and some for a small payment which supports their work! You'll find them in "Custom Sources" in settings (go to "Desktop & Screen Saver" in System Preferences,  choose "Screen Saver Options", then hit the gear icon at upper left).

**Comment by Jimmbo** [comment]
>  I've never ever had someone being confused about where the screen saver settings were. 

Only a tiny fraction of users talk to you. And those are highly-filtered. Confused people often don't become users at all. And the users who find you are the  more competent ones. And users who find you and sign up for a GitHub account and make navigate its geeky UI to give feedback are filtered more still. 

Also, v2 increases complexity by an order of magnitude  by adding both a menubar config and the welcome screen config. There are now three different places to search around for any given portion of this app. I'm not attacking that choice, but your framing of user experience is very very very very off IMO.

**Comment by glouel** [comment]
I've improved a lot of copy in 2.0.3, including renaming "On rotation", which seemed obscure, to "Currently playing" which should be more clear.
