### ISSUE TITLE
"Download Rotation"

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1066]
It's not clear what this does. I expected it to download metadata, as backup in case of a preference problem.

Do I understand correctly that it downloads all active and non-hidden videos? If Aerial v2 already stores all videos on disk, what's the purpose of this? (I'm not questioning the function, just trying to figure out if it can be called something better or somehow explained).

**Comment by glouel** [comment]
So just as a heads up, I've renamed the "On rotation" to "Currently playing" which should help a bit in clarity, I have other UI changes coming to try and make the UI a little more obvious.

**Comment by ansonliao** [comment]
I also have the same confuse about this download option, I am migrating from version `1.9.x`, and now installed new version `2.0.5` in my new machine, but in the new version, I can't find the download option `download only 4K` and looks like `Download Rotation` download all valid videos includes 1080P and 4K.

**Comment by ZV00** [comment]
Hey @ansonliao, 

Each individual video states whether it is 4K or 1080P. The selection of the 4K HEVC in the quality will select those videos as well. You can also “hide” the tvOS 10 which does not have 4K content, and if any individual 1080p videos make it through you can always hide those videos as well. 

More information about hiding and selecting videos can be found here: https://aerialscreensaver.github.io/faq.html#VideosNotPlaying

**Comment by ansonliao** [comment]
@ZV00 
Thanks for your reply.
For the setting when start `Aerial`, the tutorial will ask me to select the video quality, then I choose for example `4K HDR`, then I click `Download Rotation` to download the video, then it means that will only the 4K videos only for me, right?

**Comment by glouel** [comment]
@ansonliao there are 9 videos (total) that are not in 4K out of 119 available. Everything but those 9 will be in 4K.

If you really really don't want them, scroll down the sidebar, find tvOS 10, right/option click, press Hide videos. Then Aerial 100% won't download them/show them to you. 

![Capture d’écran 2020-08-29 à 18 36 42](https://user-images.githubusercontent.com/37544189/91641728-c0a64380-ea26-11ea-82f5-bbfafe0fc310.jpg)

Makes sense ?

**Comment by ansonliao** [comment]
@ZV00 
it is clear, thanks for your reply.
