### ISSUE TITLE
Slow-Down

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1072]
Running Aerial v2.0.1 on a mid-2018 Mac Mini running macOS 10.15.6

When I launch screensaver post-crash (issue #1070), the image is frozen. 

When I try to stop screensaver, and am asked to enter password, typing, cancelling, etc.,  are all very slow, with spinning cursor.

**Comment by Jimmbo** [comment]
It's odd we both experienced the problem simultaneously, and both experienced spontaneous resolution of the problem simultaneously.

More data points are obviously needed.

**Comment by glouel** [comment]
Regarding stutter and slowdown, per this issue (https://github.com/JohnCoates/Aerial/issues/1077), I changed things in 2.0.5 and that seem to fix the issue (at least for some, still waiting on feedback). It looks like it was particularly flagrant on *some* systems particularly with more than one screen.

**Comment by Jimmbo** [comment]
I have never had an issue since that one day. 

However, oddly, having bought and installed the third-party expansion set of videos, I'm still only seeing the old classics. I'll go under the hood when I get a chance, and hopefully that will stir up any remaining bugs.

BTW, maybe that process can be smoothed, or at least better explained during the post-purchase download/installation process? In other words, if there's an "activation" step beyond the downloading/installing, it should be pointed to during/after the installation.

**Comment by glouel** [comment]
@Jimmbo so if you didn't outright download them (I'm not sure about the instructions they put in their materials, but I can check with them), they will appear slowly when your cache refresh itself, grabbing new videos. One improvement I'll add based on your feedback is  prompt you to download the videos after adding them. 

Short term for you, press the circled arrow down next to the packs:

![Capture d’écran 2020-08-27 à 19 00 42](https://user-images.githubusercontent.com/37544189/91472650-113b6680-e898-11ea-9754-deb79f488585.png)

One thing I improved in the last few builds is explain a bit more how many videos are downloaded already for that pack.

**Comment by Jimmbo** [comment]
Here, fwiw, is where I'm at with "Custom Sources", plus my latest cache situation:


<img width="739" alt="Screen Shot 2020-08-27 at 1 05 57 PM" src="https://user-images.githubusercontent.com/7252766/91472944-2eefd800-e866-11ea-8b45-68f7636dbc33.png">
<img width="765" alt="Screen Shot 2020-08-27 at 1 05 51 PM" src="https://user-images.githubusercontent.com/7252766/91472945-2f886e80-e866-11ea-8e77-7121816959dd.png">

**Comment by Jimmbo** [comment]
I'm at v2.0.4 btw, and am not seeing a notification in the menubar icon about the update, as I did with prior versions.

I hit "Check Now", and it found the upgrade and changed the menubar icon. 

Ah, but I'm configured to check daily...maybe this update is very new?

**Comment by glouel** [comment]
It's minutes old yes, I literally just posted it ;) 

It looks like it downloaded around 20 of each in your screenshots so you should see them in theory. In the main video panel, what do you have as "Current Rotation" ?

**Comment by Jimmbo** [comment]
Not sure how to answer that....I can't really explain via screenshots. It does say "269 videos, 526 minutes".

BTW, Le Bureau des Légendes is getting a bit popular here, and is great. Is any other French TV that good/subtle/intelligent?

**Comment by glouel** [comment]
> Not sure how to answer that....I can't really explain via screenshots. It does say "269 videos, 526 minutes".

So according to what you are saying, you have every video enabled. You can however quickly change to a selection by various filter. Like here, where I only enabled countryside videos :

<img width="868" alt="Capture d’écran 2020-08-27 à 20 19 38" src="https://user-images.githubusercontent.com/37544189/91480509-603ac900-e8a3-11ea-93fa-c9e012bbb374.png">

You can use that to restrict what will show up. 

> BTW, Le Bureau des Légendes is getting a bit popular here, and is great. Is any other French TV that good/subtle/intelligent?

A lot of it depends on taste/topics, but this list probably has a few good suggestions, I'd go with things that are both popular and highly user rated to narrow it down:  
https://www.imdb.com/search/title/?countries=fr&sort=moviemeter&title_type=tv_series 

Versailles and The new pope are two safe suggestions I'd say.

**Comment by Jimmbo** [comment]
But I have not seen a single non-classic video since I bought the package, soon after V2.0 came out. Is there a chance the randomization is not random?

The Young Pope is FANTASTIC, so I’ll check out Versailles ASAP, thanks. 

From America, Succession and Rick and Morty are the current can’t-misses. Also Atlanta.

**Comment by glouel** [comment]
It definitely should be. I suggest you try the thing from my screenshot to get them right now in the meantime, but it should be random over the whole 269 videos.

And thanks for the suggestions !
