### ISSUE TITLE
Add Local button grayed out

### ISSUE THREAD

**Issue by the-sweet** [JohnCoates/Aerial#1079]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MacBook Pro Retina early 2015
- [X] macOS version: 10.15.6
- [X] Monitor setup: Usually just the built-in, sometimes spanned with an external monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I used to have a custom video in a custom folder within my user account's Movies folder. Now I don't see a way to add that location back in the new Aerial. The Add Local button is grayed out, and I haven't been able to find any information about either why it's grayed out (a combination of settings) or whether it's a feature that's not yet available in the new version. Since this doesn't seem to be an "error" per se, I wasn't sure if I should still attach a log.

**Comment by ZV00** [comment]
Hey @the-sweet,

Local videos will be coming back in a soon-to-be-released update! Sorry about the delay in this!

**Comment by glouel** [comment]
Yeah sorry about that one, it's coming back soon. Probably by the end of the week or this week end.

**Comment by itslifesaidhe** [comment]
Cant wait for this to come back!

**Comment by glouel** [comment]
Yeah sorry I'm a bit (a lot) overworked right now I'm on it as soon as I have a second.

**Comment by PBK-B** [comment]
Look forward to the return of this function, thanks to the author of such a good program, hard

**Comment by SpiritSoul11** [comment]
Hoping this feature will return soon. Shows as still greyed out for me. Thank you.

**Comment by glouel** [comment]
@the-sweet @itslifesaidhe @PBK-B @SpiritSoul11 
That took a while but it's fixed in 2.1.0 finally ! Make sure if you are using Catalina or Big Sur to put your files in a folder like /Users/shared/ that's "safe" for the screensaver to use.
