### ISSUE TITLE
Unable to set location

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1080]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: macbook Air 13-inch early 2014
- [ ] macOS version: 10.13.6
- [ ] Monitor setup: built in

#### Description of issue / Feature request

I was trying to get my wife's computer set up and nightshift was disabled. O.K. I gave it location permission. Or so I thought. I keep getting this: 

![image](https://user-images.githubusercontent.com/1205471/91371647-68710680-e7c6-11ea-9d83-bdb00619b4e5.png)

No matter how many times I hit Allow it comes back each time the screen saver comes on.

**Comment by glouel** [comment]
Hi @mbierman this is a bug in 10.14 and earlier, check this for the fix : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#issues-on-macos-1014-and-earlier

**Comment by mbierman** [comment]
Your link sort of helped. But it turns out this vintage of Mac doesn’t support night shift. Luckily, you have provided, “use my location” so she can use that. ;) thanks doe all your hard work.

**Comment by glouel** [comment]
Well, great to hear it works with the use my location option, it's really the preferred option as it's more compatible in general.

Night shift should be supported on any mac >10.12.4 if I remember correctly, but it can be fairly unreliable. What I'm doing there is a trick mostly and it doesn't always work depending on some weird factors. I nearly removed it in 2.0.0 but didn't ;)
