### ISSUE TITLE
An error occured loading the file. Please check your network connection, firewall, and try again. 

### ISSUE THREAD

**Issue by lf-openthos** [JohnCoates/Aerial#1082]
MacMini 8,1
macOS 10.15.6 (Catalina) latest
Upgrade from 1.9.2 to latest version with every video cached before.

When I enter Aerial Screensaver Settings, it pops up a alert:An error occurred loading the file. Please check your network connection, firewall, and try again. 
If I press ok, everything will continue.

But when screensaver activates, only black-screen shows up and I guess there is a invisible message alert waiting for user confirm to close.

Sometimes, the system's screensaver preference panel is locked by aerial which do not allow user to go back.

**Comment by lf-openthos** [comment]
I'm trying to reinstall it to see if that happens again.

**Comment by glouel** [comment]
Hi @lf-openthos 

> When I enter Aerial Screensaver Settings, it pops up a alert:An error occurred loading the file. Please check your network connection, firewall, and try again.

So this sounds very much like you have a firewall blocking access to grab the github community videos manifest. Do you have little snitch installed, or another firewall like it ? You will need to manually configure a few rules, as little snitch doesn't prompt you for firewalls, see here for what to do : https://aerialscreensaver.github.io/troubleshooting.html

Let me know if that fixes your issue.

**Comment by lf-openthos** [comment]
No, I am using macOS default firewall and there is no way to add legacyScreensaver.appex to whitelist.

**Comment by glouel** [comment]
Are you in China by any chance? You may have issues with that *other* firewall for downloading some of the manifests.

Here's a suggestion, go into Aerial's Settings, then Advanced in the sidebar. At the bottom right press Show in Finder:

![Capture d’écran 2020-08-28 à 10 31 03](https://user-images.githubusercontent.com/37544189/91539925-5e601c80-e91a-11ea-88c6-68ae8bfc0e55.png)

You will get a finder window with hopefully inside a few folders: 
- tvOS10
- tvOS11
- tvOS12
- tvOS13
- Community Videos from Joshua Michaels & Hal Bergman

Do you see these, and do you see entries.json files inside ? Let me know what's missing and I'll try to help you through them. I used to have instructions about grabbing videos from behind *that* firewall but they are a bit outdated for 2.0.0, I can work on that though.

Thanks

**Comment by glouel** [comment]
Sorry took me a bit to wake up (not a morning person) and really understand your issue so, here's how things should look:

![Capture d’écran 2020-08-28 à 10 59 32](https://user-images.githubusercontent.com/37544189/91544238-bc433300-e91f-11ea-9bb9-72a8d0075694.png)

if you don't have them, create those 5 folders : 
- tvOS10
- tvOS11
- tvOS12
- tvOS13
- Community Videos from Joshua Michaels & Hal Bergman

You should have a few files called tvos10.json... to tvos13.json. Move them in the respective folder, and once there, rename them entries.json. You should also have one TVIdleScreenStrings.bundle, move it into tvOS13 (and rename it to that precise name if needed, this is for the translated location information).

Lastly, can you tell me if you have the files inside the community videos folder or not ? They are on github so hopefully those should work (you may need to fix the other things before Aerial downloads them for you). 

If you can't grab them, they are here:
https://raw.githubusercontent.com/glouel/AerialCommunity/master/manifest.json
https://raw.githubusercontent.com/glouel/AerialCommunity/master/entries.json

It was my understanding that those weren't blocked by the great firewall but I may be wrong on that. The videos are hosted on github to which should download normally for you. Let me know if that helps.

**Comment by lf-openthos** [comment]
Yes I am living in China. I just use another Mac to upgrade aerial from 1.9.2 to 2.0.5, everything works like a charm. 
Thanks for your great job.
