### ISSUE TITLE
Entire Screensaver window blank

### ISSUE THREAD

**Issue by cookswim** [JohnCoates/Aerial#1084]
Installed the Aerial Screensaver. Initially it worked OK, but then in the settings area of the screensaver I clicked the button for alternate cache location or something. Immediately the settings window disappeared and left the entire screen saver pane blank. Relaunching has no effect. 

<img width="674" alt="Screen Shot 2020-08-29 at 5 24 19 PM" src="https://user-images.githubusercontent.com/58910094/91646485-acaa1400-ea1d-11ea-8446-34d9cad4c4bb.png">

If I force quit the system preferences app then it resets the screensaver selection and I can choose something else. But re-selecting Aerial immediately brings back the blank pane. Tried to completely uninstall and reinstall following the instructions to remove all files and settings. After reinstall nothing has changed.

I am running Mojave 10.14.6 on a 2010 Mac Pro with a 28" 4k monitor over Displayport

Since I can't actually get back into Aerial anymore I can't set the debug info to log to disk. Normal log provided.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5146012/AerialLog.txt)

**Comment by glouel** [comment]
Ha sorry about that. That option is fairly dangerous and it looks like I may have messed up some cases on some OSes.

In a terminal, type this:

```
defaults write ~/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist hideFromTimeMachine 0
```

This should fix it by disabling the option.

**Comment by glouel** [comment]
Actually, now that I read what you said, maybe that wasn't timemachine, so just in case, extra command: 

```
defaults write ~/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist overrideCache 0
```

This is if you tried to change the location of Aerial's cache.

**Comment by cookswim** [comment]
Thanks, the first plist edit brought it back to life.
I saw the warning about warning about security restrictions past 10.14, so figured I'd give it a shot so that users could share the cache, but looks like that won't be possible.

Great screensaver even with this limitation.

**Comment by glouel** [comment]
I haven't tested it yet on 10.14 but will give it a shot to see if I can fix it. Thanks for reporting back !

**Comment by desilinguist** [comment]
I am having the exact same issue since I updated to 2.0.9 and neither of the `defaults` commands had any effect.

**Comment by glouel** [comment]
Could you share a log and time at which you see it happening ?

**Comment by desilinguist** [comment]
Sorry, I am not sure how to get to a log since I can't see the preferences at all. I am using the companion app.

**Comment by glouel** [comment]
@desilinguist sorry I misread which thread that was. So in that case could you please go into Console and look for a crash log in there ?
