### ISSUE TITLE
"BSD process name corresponding to current thread: legacyScreenSave"

### ISSUE THREAD

**Issue by thisLinda** [JohnCoates/Aerial#1086]
I installed the beta version of Aerial yesterday on my MacBook Air 2020, Catalina v 10.15.6. Prior to install my machine had no crashes, while installed it crashed a half dozen times. Today I uninstalled and installed the non-beta version. I've just had my first crash (after hours of install so it's better than beta but....). Google search shows the error is common except for the "legacyScreenSave" part which makes me think the error is related to Aerial.

This is my first Mac and I am not familiar with it enough yet to debug (but am willing and able to follow direction).

I did copy the report but as you know it's extensive and I do not see the advanced tab for attaching.

**Comment by glouel** [comment]
Hi @thisLinda 

Sorry about that, can you clarify exactly when does it crash? Is it in the preference panel, is it when the screen saver launches? What's happening exactly in those moments? From your description it doesn't seem to happen at a specific time which is a bit weird. 

As for the crash log you can just drag and drop the file in the github reply box, if you copied in a .txt that's fine, if not you may need to .zip the file. 

Thanks!

**Comment by thisLinda** [comment]
Hi glouel, I absolutely love your screensaver. I was looking at the issues and wish I could help but my skills aren't there yet. But I will donate. 

The crash occurs after the screensaver's been running for awhile. I set it to an hour because I just sit and watch it for so long. I'm not sure if it's when the hour's up or before because I do wander off to do something else and return to find it crashed. 

[crash.zip](https://github.com/JohnCoates/Aerial/files/5148178/crash.zip)

**Comment by glouel** [comment]
Thanks for your kind comments and please no worries. 

So I had a quick look at your log, and sorry to ask for confirmation but what you meant by crash is your mac reboots ?!? I think that's the first time I've seen that. 

I'm going to ask what you have connected to your mac, do you have a second screen, do you use a USB hub, something of the kind ?

That's why I was a bit confused, when a screen saver crashes, what happens is macOS launches another screen saver. Making your mac reboot, that usually takes some pretty serious efforts or elevated privileges... Usually only a video/usb driver or something like that can literally crash your Mac and make it reboot. 

Let's try something, can you grab your configuration file and send it to me ? It's a bit hidden so let me know if you need some assistance to get there via Finder (Library is a hidden folder by default) : 

```
~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist
```

Where UUID is a random series of letters/numbers (and don't miss the "ByHost" in the url, there may be an identical file one level down, that's no good).

Thanks and really sorry about that but it's really weird.

**Comment by thisLinda** [comment]
I have nothing connected to the laptop, no USB hub. To further clarify the issue the system does not reboot itself. The screen is black and when I wake it up I'm at the apple logo (I think) but wherever I am I need to re-enter my password and it boots back up.

Using Finder, I pressed command shift G, I entered the above ``~/Library...,`` "The folder can't be found" returned. Am I supposed to be entering the UUID random series of letters/numbers?

**Comment by thisLinda** [comment]
Just happened again. Maybe it's just the generic Mac issue?
[reboot.zip](https://github.com/JohnCoates/Aerial/files/5150937/reboot.zip)

**Comment by glouel** [comment]
> I have nothing connected to the laptop, no USB hub. To further clarify the issue the system does not reboot itself. The screen is black and when I wake it up I'm at the apple logo (I think) but wherever I am I need to re-enter my password and it boots back up.

Yeah I'm pretty sure it the whole system who crashed and booted up again. 

> Using Finder, I pressed command shift G, I entered the above `~/Library...,` "The folder can't be found" returned. Am I supposed to be entering the UUID random series of letters/numbers?

So try cmd+shift+G and paste this : 
```
~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/
```

You'll see the file there.

**Comment by thisLinda** [comment]
Got it this time, two files.

[com.JohnCoates.Aerial.9BAE75EF-7F28-5D84-BB78-F4C9E8F3CCB6.plist.zip](https://github.com/JohnCoates/Aerial/files/5151989/com.JohnCoates.Aerial.9BAE75EF-7F28-5D84-BB78-F4C9E8F3CCB6.plist.zip)
[WebViewScreenSaver.9BAE75EF-7F28-5D84-BB78-F4C9E8F3CCB6.plist.zip](https://github.com/JohnCoates/Aerial/files/5151991/WebViewScreenSaver.9BAE75EF-7F28-5D84-BB78-F4C9E8F3CCB6.plist.zip)

**Comment by glouel** [comment]
Thanks I'll get back to you tomorrow and sorry again you are experiencing this.

**Comment by thisLinda** [comment]
I'm closing the issue. The restarts continued without Aerial running, I contacted Apple, Catalina was reinstalled, it ran one day with no restarts, I started up Aerial again, another day without restarts. Seems it was definitely a Catalina problem. Thank you for being there and so helpful. The experience was informative to me as I continue to learn; thank you.

**Comment by glouel** [comment]
Hey @thisLinda 

Sorry I didn't get back to you been a crazy last few days. It seemed like this was either macOS or hardware related, glad to hear it's fixed for you !
