### ISSUE TITLE
`Remaining cache` is displayed although `Limit cache size to` is set to `unlimited`

### ISSUE THREAD

**Issue by kommtzeitkonrad** [JohnCoates/Aerial#1088]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBookPro8,1
- [x] macOS version: 10.15.6 (19G2021)
- [x] Monitor setup: Internal monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

![image](https://user-images.githubusercontent.com/42938101/91848869-68a45280-ec5b-11ea-8929-801b64f5cb91.png)

**Comment by glouel** [comment]
@kommtzeitkonrad this is fixed in 2.0.8, thanks for the report !
