### ISSUE TITLE
Can't add my own videos to Aerial 2.x

### ISSUE THREAD

**Issue by lastinglight** [JohnCoates/Aerial#1089]
In previous versions, it was possible to choose videos that I have saved local on my Mac and configure them as screensavers, but this appears to have been removed in the more recent 2.x release.

The FAQ on Github has the following instructions, which seem to be out-of-date:

https://github.com/JohnCoates/Aerial/blob/master/Documentation/CustomVideos.md

I need to be able to add my own videos, or Aerial doesn't do me any good...

**Comment by glouel** [comment]
Please see this issue, it's coming back soon. https://github.com/JohnCoates/Aerial/issues/1079
