### ISSUE TITLE
plug-in not installed

### ISSUE THREAD

**Issue by perfycheng** [JohnCoates/Aerial#1090]
通过AerialInstaller.dmg安装之后，显示plug-in not installed，点击install now报错，Error: No manifest

**Comment by glouel** [comment]
Hi @perfycheng 

Your computer needs to access this file : https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json

For it to work. Can you check if your computer can access it ?

**Comment by perfycheng** [comment]
yes，
[image: image.png]

Guillaume Louel <notifications@github.com> 于2020年9月3日周四 下午3:58写道：

**Comment by zengsl** [comment]
> Hi @perfycheng
> 
> Your computer needs to access this file : https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json
> 
> For it to work. Can you check if your computer can access it ?

I have the some problem “Error: No manifest”，and my computer can not access https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json

**Comment by glouel** [comment]
@zengsl can you check what I wrote here : https://github.com/JohnCoates/Aerial/issues/1091#issuecomment-687706611 and reply there ?

Hopefully I can find a workaround but I need someone to test this for me, thanks!

**Comment by glouel** [comment]
Closing this, let's fix this on the other thread I linked above thanks!
