### ISSUE TITLE
 Cannot be used after installation, issues specific to China

### ISSUE THREAD

**Issue by perfycheng** [JohnCoates/Aerial#1091]
After the installation
![image](https://user-images.githubusercontent.com/29480722/92102608-697ee500-ee11-11ea-9d5f-6b4c45667303.png)

Click the install now button
![image](https://user-images.githubusercontent.com/29480722/92102863-c11d5080-ee11-11ea-8e25-5177130f95c5.png)

I don’t know if this is a problem with my computer

**Comment by glouel** [comment]
Hi @perfycheng

Your computer needs to access this file : https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json

For it to work. Can you check if your computer can access it ?

**Comment by beyondskyway** [comment]
> Hi @perfycheng
> 
> Your computer needs to access this file : https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json
> 
> For it to work. Can you check if your computer can access it ?

same problem. Can not access to https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json

**Comment by glouel** [comment]
@beyondskyway you are in China too ? 

I know at least some of GitHub isn't blocked by the firewall, can you test these 3 urls in a browser, and tell me which ones works and which ones don't, so maybe I can find a solution:
- https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json <- This one you told me doesn't load in a web browser, correct ? 
- what about this one, does that load : https://aerialscreensaver.github.io
- and that one : https://github.com/glouel/AerialCommunity/releases/download/mw1-1080p-sdr/LICENSE.txt ?

Based on that maybe I can find a workaround. Thanks

**Comment by zengsl** [comment]
> @beyondskyway you are in China too ?
> 
> I know at least some of GitHub isn't blocked by the firewall, can you test these 3 urls in a browser, and tell me which ones works and which ones don't, so maybe I can find a solution:
> 
> * https://raw.githubusercontent.com/glouel/AerialUpdater/main/manifest.json <- This one you told me doesn't load in a web browser, correct ?
> * what about this one, does that load : https://aerialscreensaver.github.io
> * and that one : https://github.com/glouel/AerialCommunity/releases/download/mw1-1080p-sdr/LICENSE.txt ?
> 
> Based on that maybe I can find a workaround. Thanks

Hello,I can access the other two url except the first URL， and I'm in China.

**Comment by glouel** [comment]
@zengsl thanks a whole lot ! I'll try to make a fix tonight and will let you know here. 

Thanks a lot for your quick response !

**Comment by zengsl** [comment]
> @zengsl thanks a whole lot ! I'll try to make a fix tonight and will let you know here.
> 
> Thanks a lot for your quick response !

U r welcome, expect you find a workaround soon

**Comment by glouel** [comment]
To @zengsl @beyondskyway and @perfycheng 

Please try the latest installer from here : https://github.com/glouel/AerialCompanion/releases/latest/download/AerialInstaller.dmg

This version uses https://aerialscreensaver.github.io/manifest.json which should work.

I also released version 2.0.8 of Aerial which should let you download the community videos. Please note that Apple video servers are banned by the firewall and for those there's nothing I can do for you, you will need to find another connexion if you want these. Please let me know if that fixes your issues.

**Comment by zengsl** [comment]
> I also released version 2.0.8 of Aerial which should let you download the community videos. Please note that Apple video servers are banned by the firewall and for those there's nothing I can do for you, you will need to find another connexion if you want these. Please let me know if that fixes your issues.

OK，thx. I will try it now

**Comment by zengsl** [comment]
> [https://aerialscreensaver.github.io](https://aerialscreensaver.github.io/manifest.json)



> To @zengsl @beyondskyway and @perfycheng
> 
> Please try the latest installer from here : https://github.com/glouel/AerialCompanion/releases/latest/download/AerialInstaller.dmg
> 
> This version uses https://aerialscreensaver.github.io/manifest.json which should work.
> 
> I also released version 2.0.8 of Aerial which should let you download the community videos. Please note that Apple video servers are banned by the firewall and for those there's nothing I can do for you, you will need to find another connexion if you want these. Please let me know if that fixes your issues.

There are no errors when downloading Plugin-in,but it's too slow to download it.Maybe there's something wrong with my network

**Comment by glouel** [comment]
Do you mean the screensaver download is slow, or the video downloads afterwards ?

**Comment by zengsl** [comment]
> Do you mean the screensaver download is slow, or the video downloads afterwards ?

I mean the screensaver download is slow 
![image](https://user-images.githubusercontent.com/18246911/92359997-b5d26980-f11e-11ea-9c0d-cb87aae9a8e8.png)

**Comment by glouel** [comment]
When you clicked install now ? Did it work in the end ?

**Comment by zengsl** [comment]
> When you clicked install now ? Did it work in the end ?

Prompt timeout

**Comment by glouel** [comment]
So the installer does try to download this file which as far as I know works on the firewall : https://github.com/JohnCoates/Aerial/releases/download/v2.0.8/Aerial.saver.zip

If you can load it from your browser, open the zip, double click the .saver and it will finish the install

**Comment by zengsl** [comment]
> So the installer does try to download this file which as far as I know works on the firewall : https://github.com/JohnCoates/Aerial/releases/download/v2.0.8/Aerial.saver.zip
> 
> If you can load it from your browser, open the zip, double click the .saver and it will finish the install

The installation was successful,thank you so much!
![image](https://user-images.githubusercontent.com/18246911/92399551-0c5e9880-f15d-11ea-8fd8-3a76e5b69607.png)
![image](https://user-images.githubusercontent.com/18246911/92399570-17192d80-f15d-11ea-9738-4fd4057323b5.png)
