### ISSUE TITLE
Understanding Display Settings

### ISSUE THREAD

**Issue by heutger** [JohnCoates/Aerial#1094]
Hi,

I don't find in the instructions, what is the difference between Cloned and Mirrored mode? What's the difference between Fill screen and Fit to screen?

Regards
Christian

**Comment by glouel** [comment]
So those are multi display settings. 

Assuming you have two monitors, it shows you on top exactly what will happen:
<img width="1109" alt="Capture d’écran 2020-09-11 à 08 27 02" src="https://user-images.githubusercontent.com/37544189/92874726-94b49600-f408-11ea-86f2-23cb2b8ada3e.png">

In mirrored mode it looks like a mirror effect (one video is flipped), you can see the preview on top.

<img width="1109" alt="Capture d’écran 2020-09-11 à 08 27 56" src="https://user-images.githubusercontent.com/37544189/92874846-b4e45500-f408-11ea-8611-d23108913c39.png">

Spanned, one video accross multiple monitors, etc, etc. 

For fit/fill, this only matters if you display is not 16/9.
