### ISSUE TITLE
Ability to preview videos from companion app

### ISSUE THREAD

**Issue by tbartelsmeyer** [JohnCoates/Aerial#1095]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (15-inch, 2019)
- [ ] macOS version: 10.15.6
- [ ] Monitor setup: 4k HDR 27" LG UK600w + laptop screen

#### Description of issue / Feature request

Hi! I looked around and can't find anything in issues, FAQs, or the app itself - how can I preview the screensaver videos from within the companion app? Thanks for making an awesome app, and I'm sorry if I missed it somewhere!

**Comment by glouel** [comment]
Hmm, from companion ? 

Like, right now, you can launch the screensaver settings and access them from here. At some point soon (let's say end of the month), you'll be able to launch Aerial in a window too but I'm not sure that answers your question.

**Comment by tbartelsmeyer** [comment]
You're correct - what I mean is while browsing the currently downloaded screensaver videos in your library in the companion app, it would be great if you could hit a button or a key to view said video fullscreen in order to see what it will look like when in use. Right now all I can see is a screenshot and thumbnail, not even a small video preview. Would be especially helpful so that you can easily filter your favorite and least favorite videos.

**Comment by glouel** [comment]
Ok so what you mean is from here right :

<img width="1107" alt="Capture d’écran 2020-09-11 à 08 23 30" src="https://user-images.githubusercontent.com/37544189/92874188-1526c700-f408-11ea-973e-dcd658a19ee4.png">

Just to explain my confusion, this is what I call the Preference Panel (Aerial Companion is this : https://github.com/glouel/AerialCompanion

So I did have auto play videos in previous builds but removed that, it only played videos that were cached. Previewing video that you haven't downloaded yet is possible, I'll think about adding something at some point.

**Comment by tbartelsmeyer** [comment]
Yep that's what I meant, sorry about the incorrect terminology. 
Ok, great thanks! Does that mean that there is a way to preview already downloaded content? Because I can't figure out how to do that either.

**Comment by glouel** [comment]
I'll add something in next build so you can manually play already locally downloaded content somehow yep.

**Comment by glouel** [comment]
@tbartelsmeyer 

In 2.0.9 there's a new setting in Settings > Advanced that lets you auto play videos. I believe this fixes your issue.

**Comment by tbartelsmeyer** [comment]
Awesome, thanks so much for the rapid response, and again for making such a great app!
