### ISSUE TITLE
Is caching necessary?

### ISSUE THREAD

**Issue by amedeocalcio** [JohnCoates/Aerial#1098]
Hello I’m new to all this so excuse me if I’m no expert. I just switched from 1.9 version to the latest and now whenever I start the screensaver the screen just turns all black. I tried to fix it and I think is because with previous version I wouldn’t cache the videos. So my question is: is it possible to have the screensaver working without downloading or caching videos on the computer? (Obviously having an internet connection working)

**Comment by glouel** [comment]
Hi @amedeocalcio 

Users who had that particular mix of settings seem to be experiencing issues, yes. I would recommend deleting the settings and start fresh. Location of files here at the bottom, you need to reboot after deleting though (plist are cached by macOS) : https://aerialscreensaver.github.io/installation.html

Answering your question, is caching "necessary" ? Nothing per se is really necessary. But streaming is at the root of a lot of issues in Aerial that I want to get rid of. That's the reason why I've hidden it (although apparently you can still bend Aerial to stream, against my best efforts !). 

There are a few reasons I made that change, the first one is, Apple servers are not configured correctly for streaming. The Apple TV's screensaver uses the exact logic I implemented in 2.0, which is cache, and rotate the cache periodically. This avoids a lot of failed playback issues, inability to resume etc. There's also a question of being mindful of resources that aren't ours. Apple seems to tolerate Aerial. If everyone streamed all the time, they may take a different eye to it, either by obfuscating their servers or using some other level. 

So yes, I highly recommend that you use a rotating cache after resetting your settings and I will not bring back the streaming all the time option.

**Comment by amedeocalcio** [comment]
That makes sense, you know I just considered what was best for my Mac, but with all these things in play I can understand why you’re doing what you’re doing. Thanks for the quick and exhaustive answer man! Keep up the good work.

**Comment by glouel** [comment]
Thanks for your understanding !

**Comment by amedeocalcio** [comment]
Since you answered, will it be possible to have back the narrow button option, the one for changing video while playing?

**Comment by glouel** [comment]
> Since you answered, will it be possible to have back the narrow button option, the one for changing video while playing?

Hmm ? Which button are you referring to ?

**Comment by amedeocalcio** [comment]
My bad, I typed it wrongly. I'm referring to the right arrow key for skipping the video

**Comment by glouel** [comment]
> > Since you answered, will it be possible to have back the narrow button option, the one for changing video while playing?
> 
> Hmm ? Which button are you referring to ?

It's still there and enabled by default, but it no longer works on Catalina and Big Sur because of sandboxing restrictions. It still works on 10.14 and below, but I have 0 control over it, it's a restriction imposed by Apple.
