### ISSUE TITLE
4K HEVC HDR Videos on Big Sur are "dim"

### ISSUE THREAD

**Issue by cmfrazier** [JohnCoates/Aerial#1099]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (15-inch, 2018)
- [x] macOS version: 11.0 Beta (20A5364e)
- [x] Monitor setup: 2x 4K monitors via a Thunderbolt dock

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5228427/AerialLog.txt)

#### Description of issue / Feature request

When HDR 4K HEVC videos play, they are extremely faint or dim, to the point the can barely be seen.
They appear this way in Quicktime as well.

<img width="1070" alt="Screen Shot 2020-09-15 at 4 53 09 PM" src="https://user-images.githubusercontent.com/20451193/93269101-f6ac2d00-f773-11ea-9884-5342f934315c.png">
<img width="984" alt="Screen Shot 2020-09-15 at 4 53 45 PM" src="https://user-images.githubusercontent.com/20451193/93269151-104d7480-f774-11ea-9f76-8e93ef0471f1.png">

**Comment by glouel** [comment]
Hi @cmfrazier 

This looks like another graphical driver bug with Big Sur, since you have the same issue with QuickTime. Beta 6 certainly seems "worse" than others. I did have very dim colors too with beta 1, maybe not that dim though, but it ended up fixed later on (on a Late 2015 iMac). 

So far in Beta 6, I've had your report, one weird report of video previews just not showing up in Aerial's UI (but working in full screen mode), and intermittent flashing on eGPU.

So not much that I can say except wait for beta 7 (hopefully really soon).

**Comment by glouel** [comment]
@cmfrazier did that get fixed for you in beta8 ?

**Comment by cmfrazier** [comment]
> @cmfrazier did that get fixed for you in beta8 ?

Nope 😒

**Comment by glouel** [comment]
I would suggest if you haven't done so to file a feedback assistant report about what's happening in Quicktime, that may get Apple's attention to your bug.

**Comment by glouel** [comment]
@cmfrazier any progress on this by the way ?

**Comment by glouel** [comment]
@cmfrazier did they manage to fix that bug for you in 11.1 ?

**Comment by cmfrazier** [comment]
@glouel Seems to be fixed in 11.1. I moved to a Mac mini M1 and it seems to be running smooth. I have not updated my MacBook Pro (Intel) to 11.1 yet.

**Comment by glouel** [comment]
Great ! Aerial runs really smoothly on the DTK, and I'd expect the same on the M1 Macs ! Closing this, feel free to reopen if you still hit an issue.
