### ISSUE TITLE
Screensaver remains "black" after starting: Could not open manifest for source, issues specific to China.

### ISSUE THREAD

**Issue by linyifan96** [JohnCoates/Aerial#1100]
Mac model: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.15.6
Monitor setup: External 1080P monitor

Hello, I am a mainland China user. I have been using your screensaver for many years, many thanks for your contribution. I'm new here and not an expert.

Recently, I upgraded Aerial to 2.0.9. As you know, China's network firewall limits the external access of some websites. Only through VPN can we solve this problem. I found that if I shut down the VPN, the software would not work normally. After launching, it would be black, and only by pressing the power button could the lock screen interface be restored and the password could be entered. But if I turn on VPN, everything is OK. I've downloaded all the videos before, so it shouldn't be about caching. I checked the log and found out "Could not open manifest for source at https://aerialscreensaver.github.io/community/".

I would like to ask if there is any way to solve this problem, so that I can normally use the screen saver without opening the VPN. The 1.9.X I used earlier didn't have this problem.

I have attached the relevant log. 
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5232316/AerialLog.txt)

Thanks again.

**Comment by glouel** [comment]
Hey there,

Thanks for the report, it's pretty hard to test around the firewall so sometimes I miss things. I was told though from another Chinese user that this : https://aerialscreensaver.github.io/community/entries.json

worked behind the firewall. I guess it does not.

Regarding your specific issue, there's currently a bug in 2.0.9 that might be behind this, it tries to download that file at startup even if it's already cached. I'll release a fix tonight and will let you know.

**Comment by glouel** [comment]
@linyifan96 apologies it took me so long, I fixed the bug in 2.0.10, please check and let me know : https://github.com/JohnCoates/Aerial/releases/download/v2.0.10/Aerial.saver.zip
