### ISSUE TITLE
Current build on brew does not work

### ISSUE THREAD

**Issue by ReagentX** [JohnCoates/Aerial#1102]
Installed via `brew`, I only ever see a black screen. Videos stream fine in the UI, but not as the screensaver.

- Mac model: MacBook Pro (Retina, 15-inch, Mid 2015)
- macOS version: 10.15.6 (19G2021)
- Monitor setup: None

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5252884/AerialLog.txt)

**Comment by glouel** [comment]
Can you show me a screenshot of your cache settings ? According to your logs you have no video cached. Did you uncheck automatic downloads ? 

There's a bug where Aerial seems to fail to stream in "emergency" cases, that may be what you are encountering.

**Comment by ReagentX** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1920666/94073622-ca249080-fdc5-11ea-9b48-4244bf3e6fa2.png">

**Comment by glouel** [comment]
Well, you have unchecked automatic downloads, and haven't downloaded a video yourself it seems.

So either check that box, or download a few videos manually in the main UI a,d you should be good to go.
