### ISSUE TITLE
Right Arrow Key Not Working on Mojave

### ISSUE THREAD

**Issue by KingTbird** [JohnCoates/Aerial#1103]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:3,1
- [ ] macOS version: 10.14.6
- [ ] Monitor setup: 6 displays; (3) 1440p over (3) 4K
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5258894/AerialLog.txt)

#### Description of issue / Feature request

Right Arrow key isn't functioning with v2.0.9 on macOS 10.14.6; audible error sound plays with each attempt. I understand it's broken and closed in Catalina; should this still work on Mojave?

**Comment by glouel** [comment]
It still works in my 10.14.6 vm here, but people have been having weird issues with the latest security update for 10.14.6.

A couple of things to start : 
- Check in Settings Advanced that's the option is enabled 
- You mention having an error sound, that implies something else has focus. What about other keypresses, do they make the same noise ? Or do they quit ?

That may narrow it down a bit, thanks and sorry about that.

**Comment by glouel** [comment]
Please reopen if you still need assistance
