### ISSUE TITLE
Feature request: Play videos on secondary displays iff connected

### ISSUE THREAD

**Issue by jpaddison3** [JohnCoates/Aerial#1104]
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).
- [x] Mac model: MacBook Pro (16-inch, 2019)
- [x] macOS version: 10.15.6
- [x] Monitor setup: Have Dell U2715H on a stand above my laptop screen. My workflow requires that my laptop screen is the "main" one.

First of all, thanks so much for Aerial, it is a privilege to watch.

I would like to suggest that the "Play videos on" option, have an option to play videos on one's external monitor* only in the event that the external monitor is connected. Otherwise it should display on the remaining monitor.

The use case is:
 * Want to have only one screen playing (for example, to prevent over-burdening the CPU)
 * Want the screen to be the large external monitor when that monitor is attached
 * Want to still display on laptop when the external monitor is not attached
 * Do not want to make the external monitor the "main" one

This seems like a relatively frequent use-case, but I'd understand if it was frequent enough to build for. Thanks again for all the work.

*(And not on one's laptop)

**Comment by glouel** [comment]
Hi @jpaddison3 !

Sorry for the late answer, someone suggested the exact same thing a while back and it's still on my list (ok I kinda forgot about it :D). See the discussion below, what you describe should be the default and I really need to get on it when I get a second : https://github.com/JohnCoates/Aerial/issues/1040

**Comment by jpaddison3** [comment]
Ah, sorry for missing the issue. Feel free to close this one.

**Comment by glouel** [comment]
@jpaddison3 sorry for the delay, it took me a while but version 2.1.1 now does this by default. Let me know if that works for you

**Comment by jpaddison3** [comment]
Amazing! Thank you! 🙏

I just upgraded and it works great!
