### ISSUE TITLE
New version 2.0.10 says it's older than installed 2.0.9 while installation

### ISSUE THREAD

**Issue by robert-cody** [JohnCoates/Aerial#1106]
Actions:

1. Currently installed version is 2.0.9.
2. Download and install version 2.0.10.

Result:
macOS says that 2.0.10 is older than previous one 2.0.9.

Expected result:
macOS says that 2.0.10 is newer than previous one 2.0.9.

macOS 10.15.6 (19G2021)

**Comment by glouel** [comment]
@robert-cody that's... weird. I guess that part of macOS doesn't parse .10 > .9 ?

It shouldn't be a blocking issue though, but thanks for mentioning it!
