### ISSUE TITLE
How to completely remove Aerial from my mac?

### ISSUE THREAD

**Issue by Maks-Yaremenko** [JohnCoates/Aerial#1109]
I would like to completely remove Aerial from my mac cuz I don't use it anymore. I didn't found this option in docs. Thank you

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (15-inch, 2018)
- [ ] macOS version: 10.15.6 (19G73)
- [ ] Monitor setup: default screen + 34" samsung

**Comment by glouel** [comment]
@Maks-Yaremenko 

Check here near the bottom : https://aerialscreensaver.github.io/installation.html

**Comment by Maks-Yaremenko** [comment]
Thx a lot, sorry about this issue, didn't notice that page.
