### ISSUE TITLE
Support for live wallpapers

### ISSUE THREAD

**Issue by jophill6** [JohnCoates/Aerial#1112]
I was wondering if there are any plans to have Aerial support live wallpapers with these same videos instead of just using them as screensavers?

I’d love to be able to set my desktop wallpaper to these videos as well. 

Thanks!

**Comment by glouel** [comment]
Hey @jophill6 

So in Companion, I do plan to add a windowed mode that can go both fullscreen and desktop. It's not ready for primetime yet but it's half working, I posted some progress a while back on ko*fi with a screenshot here : https://ko-fi.com/i/IP5P824B68

Apart from a couple of bugs that I need to wrap my head around, Catalina and Big Sur - because they use containers - make things a lot harder to get it to work as intended, but this should come at some point. No target date though.

**Comment by jophill6** [comment]
Sounds good - thanks for the update. How would that support a live wallpaper though? I’d like the video to be the desktop wallpaper in the background, not just a window. :-)

**Comment by glouel** [comment]
Yep, basically, you make a window the screen size and give it a special attributes so it can show as a wallpaper behind the desktop icons. That's how live wallpapers works.

**Comment by glouel** [comment]
If you have companion installed, you can see the menu entries are already there because I like teasing 🤣

<img width="491" alt="Capture d’écran 2020-10-01 à 14 14 30" src="https://user-images.githubusercontent.com/37544189/94807851-839beb00-03f0-11eb-8278-b66ca5771673.png">

**Comment by jophill6** [comment]
Ah, nice!  Thanks for the update (and education). :-)

**Comment by glouel** [comment]
@jophill6 so it's not fully there yet, but there's now a full screen mode in Companion 1.2 that lets you run Aerial on a monitor while you work on the other. Desktop mode will be coming next there.

**Comment by jophill6** [comment]
Great news - thanks for the update... can’t wait!

-Brad

**Comment by glouel** [comment]
And it's here, finally. 

![Capture d’écran 2020-12-02 à 17 18 33](https://user-images.githubusercontent.com/37544189/100910790-aae56600-34ce-11eb-9404-f9f3d11e9427.jpg)

It's still *very* early so you may hit some issues. I'd suggest you read that post regarding windowed mode, the same caveats apply : https://ko-fi.com/post/Aerial-2-2-1-and-Companion-1-2-R6R42TINQ

Get the Companion beta here : https://github.com/glouel/AerialCompanion/releases/download/v1.2.1beta1/AerialCompanion.dmg

Also make sure you update Aerial to 2.2.2beta1 using Companion, if not you'll experience memory leaks.

**Comment by glouel** [comment]
I did publish a standalone app to change settings if you need, more info here : https://ko-fi.com/post/Desktop-mode-is-here-in-beta-O4O32U85N

**Comment by glouel** [comment]
@jophill6 Version 2.2.3 of Aerial contains an important fix to solve a black screen issue with Desktop mode and windowed mode.

**Comment by KAMIKAZEUA** [comment]
Hey @glouel !

I'm using 2.2.8beta4, is there a way to get this feature in this version? 

macOS Big Sur 11.2.3

<img width="515" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/110953529-22d5ee80-8350-11eb-9bcd-a87ad5cb98f7.png">

**Comment by glouel** [comment]
Hey @KAMIKAZEUA, you need the beta of Companion for it to work, install this version : https://github.com/glouel/AerialCompanion/releases/download/v1.2.1beta2/AerialCompanion.dmg

And you'll be good to go !

**Comment by KAMIKAZEUA** [comment]
I just wondering of it's too old version, only v1.2.1beta2. 

Now I understand, that this is version of app, but not screen-saver. 
Thanks!

**Comment by glouel** [comment]
Yep it's a bit complicated 🙈 

That feature is in the beta of companion (and requires a modern version of the screensaver ;). Things will get a lot simpler as soon as I release the final version of that soonish ;) so yep, keep your 2.2.8beta4, that's fine, just replace your old companion and you'll get the feature.
