### ISSUE TITLE
Aerial issues with eGPU

### ISSUE THREAD

**Issue by davidcorbin** [JohnCoates/Aerial#1113]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (15-inch, 2018)
- [ ] macOS version: 10.15.6
- [ ] Monitor setup: 2x 1080p external + internal 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Aerial stopping eGPU from being disconnected. When eGPU disconnect button is clicked, these processes are stopping the eGPU from being disconnected. This lasts forever until force disconnect is clicked.

![Screen Shot 2020-10-01 at 5 56 13 PM](https://user-images.githubusercontent.com/5752872/94980898-d57d6780-04fb-11eb-9f31-c03edbd08ae8.png)

**Comment by glouel** [comment]
Hmm, well, one thing that pops to my mind is the com.apple.preference.desktopscreeneffect.screeneffects....

That's the System Preferences panel. Basically, as long as it's open, it may (and my understanding is, always) keeps a copy of the screensaver panel if you had opened it. And by doing that it's keeping a copy of Aerial (or whatever screensaver you have) running (but paused, if that makes sense) in the tiny preview that you see here : 

<img width="893" alt="Capture d’écran 2020-10-03 à 13 17 55 1" src="https://user-images.githubusercontent.com/37544189/94990254-e28d6b80-057a-11eb-9550-579081b8a90c.png">

So my wild guess is, you still have System Preferences still running and that's what creates that chain of stuff hanging around. Try to quit System Preferences and it's likely Aerial will get killed, then legacy etc...

In general, Aerial doesn't decide when it starts and when it gets killed, all of that is up to the system.

**Comment by davidcorbin** [comment]
Gotcha I'll keep and eye on this over the next couple days and see if the issue persists. Thanks!

**Comment by glouel** [comment]
I'll be closing this, feel free to reopen if you still hit the issue but I think that's "fixed" :)
