### ISSUE TITLE
Black screen in 10.14 if HDR is selected

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#1114]
You’re pretty fast ;-)
My settings are « launch the screen saver after 5 minutes » and  "never turn display off ».
Btw, the screen save has quit unexpectedly when I wanted to verify the delay …
Here is the report I got .

**Comment by cdavid33** [comment]
Here is the report 
[Report.txt](https://github.com/JohnCoates/Aerial/files/5321920/Report.txt)

**Comment by glouel** [comment]
Report is intriguing. Can you go into Aerials's settings > advanced then enable debuglog there, and reproduce the black screen ? Try to note the time it happens. 

Functionally speaking, hot corner and launching by itself is 100% similar so there's something else going on here. One thing that always help is making sure you close System Preferences (completely) before launching the screensaver as this has, over the past, been a cause of issues (and make the debug log harder to read).

**Comment by cdavid33** [comment]
Done!
I tried it 3 times between 2020-10-03 18:44:55.941 and 2020-10-03 18:51:47.35 (see debug report).
The two first were black screen, the last one worked, but I noticed previously (before your answer) that sometimes it works and when changing video the black screen come again ....
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5322021/AerialLog.txt)

**Comment by cdavid33** [comment]
Done on GitHub

**Comment by glouel** [comment]
Great thanks I'll have a look and get back to you asap (and no need to reply by email it goes in the same place, you just can't attach files by email).

**Comment by cdavid33** [comment]
I think I found the origin of my problem (just by chance...) : I dowloaded all videos, but a lot of those were in in 4K HDR format (I selected 4K HDR in the panel Advanced-> Video format).
I changed that to 4K HEVC and it seems to work correctly now.
Is it OK for you?

**Comment by glouel** [comment]
Oh wow, I didn't even notice that. HDR is not officially supported (by Apple) until Catalina, and I'm supposed to disable it on older OSes. Can you actually pick HDR in Aerial in Settings > Advanced on 10.14 ???

I may have a bug here, cause those choices are supposed to be hidden from you to avoid just that!

**Comment by cdavid33** [comment]
Yes, I **was** able to pick HDR in the setting just after (re)installing Aerial, but now since I've changed it to 4K HEVC the option HDR is no more  available.
I'm re-downloading the videos and no problem up to now.

**Comment by glouel** [comment]
Oh wow. So yeah I think I know what happened. You picked HDR in what I call the first time setup: 

<img width="912" alt="Capture d’écran 2020-10-02 à 12 58 21" src="https://user-images.githubusercontent.com/37544189/94916438-f9668c00-04ae-11eb-8dbf-afc04258ab31.png">

I probably forgot to unallow HDR in there. Really sorry about that. 4K HEVC is the way to go for you and you should be fine, thanks a whole lot cause I completely missed that one.

**Comment by cdavid33** [comment]
Thats it!
Happy to help debugging even if I'm not a geek :-)

**Comment by glouel** [comment]
Well you definitely deserve your geek card for that one, thanks a whole lot for following up on this with me, I fixed the bug for the next version of Aerial. Cheers!

**Comment by glouel** [comment]
@cdavid33 again many thanks for this, I (finally) released the new version of Aerial with the fix for everyone.

**Comment by cdavid33** [comment]
I know: I subscribed to the Recent Commits to Aerial:master feed and it was announced ;-)

Happy to have helped!
