### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Tacobell84** [JohnCoates/Aerial#1115]
I have two small issues. 1st being I can't seem to upgrade the screensaver. I'm still on 1.6.1 and when I try to get to 2.0.10 nothing happens. The other thing that is going wrong is that the screensaver seems to turn on then after a few seconds turns off.

**Comment by glouel** [comment]
Hey @Tacobell84 

Which macOS version are you using ? 

Can you try using the companion for installation ? Download this : https://github.com/glouel/AerialCompanion/releases/latest/download/AerialInstaller.dmg

Usage instructions here (double click the dmg, drop in applications, really easy, and it will auto update you in the future) : https://aerialscreensaver.github.io/installation.html

**Comment by glouel** [comment]
Fell free to reopen if you need more assistance on this

**Comment by Tacobell84** [comment]
Seems to be working
