### ISSUE TITLE
Feature Request - Keyboard shortcut to cycle scene

### ISSUE THREAD

**Issue by hefronmedia** [JohnCoates/Aerial#1117]
Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

On the ATV, swiping left or right changes the current scene.

On Aerial screen saver, any user input dims the screen saver and prompts to unlock the machine.

It would be good to allow a swipe gesture on the mouse to cycle scenes for the monitor the cursor is over, and have screensaver interrupted only by the stroke of a spacebar or enter key, for instance.

**Comment by glouel** [comment]
Hey @hefronmedia 

So there's already exactly that, you can press the right arrow to skip scene... but that only works on Mojave (10.14) and earlier. 

Starting with Catalina screen savers are no longer allowed to access the keyboard (or mouse for that matter). This is a macOS sandboxing limitation and until Apple ships a new API for screen savers I can't do anything about it sadly.

**Comment by hefronmedia** [comment]
Thanks for the info @glouel - I am not familiar with screen saver development although I know how sandboxing generally works.

On this page https://developer.apple.com/forums/thread/117136 there is a detailed post which explains the restrictions and mentions that it can be worked around if SIP is disabled.

How would this be achieved ?  I mean with a normal app bundle we can simply remove the sandbox and re-sign, but this has nothing to do with SIP.  I presume that the interface to the screensaver is where the restriction occurs, so how then does one get around this by disabling SIP ?

Many thanks.

**Comment by glouel** [comment]
Yeah that's actually me answering in that post you link (C_Wiz) ;)

Screen savers are plugins that runs under a new System app extension (the one that's sandboxed) so there's really nothing to be done here, it's fully under the control of macOS. You can't resign macOS code. 

The only known "solution" is disabling SIP (System Integrity Protection), but that is a system wide thing that you should really NOT do. Disabling SIP will disable *all* sandboxing and thus Aerial will gets back its keyboard access. 

I really do not recommend you do this.

**Comment by hefronmedia** [comment]
> I really do not recommend you do this.

For various reasons, this particular development machine has SIP disabled.  I am in agreement that this is not a proper solution for anything.

> The only known "solution" is disabling SIP (System Integrity Protection), but that is a system wide thing that you should really NOT do. Disabling SIP will disable _all_ sandboxing and thus Aerial will gets back its keyboard access.

This is a negative in my case.  At least on Big Sur Beta 9 ... pressing absolutely anything just goes to unlock the screen.

legacyScreenSaver has been given full rights to everything...  Are you saying just by having SIP off it [should] work without any additional action ?

**Comment by glouel** [comment]
> > The only known "solution" is disabling SIP (System Integrity Protection), but that is a system wide thing that you should really NOT do. Disabling SIP will disable _all_ sandboxing and thus Aerial will gets back its keyboard access.
> 
> This is a negative in my case. At least on Big Sur Beta 9 ... pressing absolutely anything just goes to unlock the screen.
> 
> legacyScreenSaver has been given full rights to everything... Are you saying just by having SIP off it [should] work without any additional action ?

This is what has been reported by multiple users, yes, disabling SIP disables sandboxing restrictions, that's at least how it worked in Catalina. I can't seem to remember if anyone commented about anything being different with SIP on Big Sur yet so I'm not 100% confident it works there though I believe it likely should.

You may need to enable that feature in Settings > Advanced though I believe it's enabled by default ? It's here and while it will be greyed out, it should appear checked, can you confirm ? 

![Capture d’écran 2020-10-14 à 13 42 37](https://user-images.githubusercontent.com/37544189/95984456-8270b200-0e23-11eb-98c0-83acbb627988.jpg)

**Comment by hefronmedia** [comment]
> You may need to enable that feature in Settings > Advanced though I believe it's enabled by default ? It's here and while it will be greyed out, it should appear checked, can you confirm ?

It does appear checked and greyed out.  But there's no true/false key for this feature in the plist.  I guess if it works for you in the same configuration this is a non-issue.

>Edit : While I don't run SIP disabled here, I do "run" Aerial on Big Sur unsandboxed (in a window for debugging) and I can confirm that, in that unsandboxed setting, the right arrow key does skip videos as intended.

Is this from XCode ?  Admittedly I haven't loaded the project yet as I didn't think this feature existed.  Before logging this feature request I searched the settings high and low, but I missed that greyed setting probably 10 times.

**Comment by glouel** [comment]
> It does appear checked and greyed out. But there's no true/false key for this feature in the plist. I guess if it works for you in the same configuration this is a non-issue.

Assuming you have the latest version of Aerial (?) I believe it should work (though it's not exactly the same situation). The fact it's not in the plist is ok, that's because it's a default setting. 

> > Edit : While I don't run SIP disabled here, I do "run" Aerial on Big Sur unsandboxed (in a window for debugging) and I can confirm that, in that unsandboxed setting, the right arrow key does skip videos as intended.
> 
> Is this from XCode ? Admittedly I haven't loaded the project yet as I didn't think this feature existed. Before logging this feature request I searched the settings high and low, but I missed that greyed setting probably 10 times.

Yes. There's an "Aerial App" target in the project that lets you compile Aerial as an app and to run it in a window, though it's really just for debugging purposes right now. I'm working on implementing the ability to launch Aerial in a window from Aerial Companion (the auto update helper) but that's not ready yet.

**Comment by glouel** [comment]
I'll be closing this, feel free to reopen if you still have issues with it.
