### ISSUE TITLE
[Feature Request] Customize menu bar icon

### ISSUE THREAD

**Issue by arnsangra** [JohnCoates/Aerial#1119]
Before logging an issue please check that:

- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases

- [x] Your issue isn't already mentioned in our issues. You may find a workaround there or a similar request already made.

- [x] Your problem isn't mentioned in the troubleshooting page.

It would be good to provide with a customization option for the menu bar icon. Ideally by providing a monochrome version that matches the majority of system icons.

Thanks

**Comment by glouel** [comment]
Hey there ! Someone is working on a flat monochrome icon, but I haven't heard from them for a while. 

I will try and see if they managed to get something going yet.

**Comment by glouel** [comment]
This is coming later this week just to keep you updated @arnsangra.

**Comment by glouel** [comment]
A bit late but this is up now in Companion 1.2, check it out here : https://aerialscreensaver.github.io/index.html
