### ISSUE TITLE
After enabling the Aerial screensaver, display sleep no longer works in el capitan

### ISSUE THREAD

**Issue by ovaltinedinosaur** [JohnCoates/Aerial#112]
1. Enable Aerial screensaver to turn on after 1 min in display system preferences
2. then go to energy saver and set display sleep to 3 min
3.  wait 1 min to let the screensaver turn on
4.  wait 2 more min to see if display will sleep, however screensaver continues to play the aerial screensaver

**Comment by IamMirezNL** [comment]
I have the same issue, I tried to find the process in the Activity Monitor to see if it was preventing sleep, however I couldn't find it.

**Comment by armen52** [comment]
I had this issue in Yosemite on my MacBook Air, and still have it after upgrading to El Capitan yesterday.

**Comment by alistairmcmillan** [comment]
@ovaltinedinosaur @IamMirezNL @armen52 Which version are you running? Are you running the latest beta? https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by armen52** [comment]
@alistairmcmillan No, turns out I was not. Upgrading to 1.2beta5 appears to resolve the issue. Thanks!

**Comment by alistairmcmillan** [comment]
Glad to hear it's working @armen52 

No reply from others, after months, so closing.
