### ISSUE TITLE
You can't use Aerial in this version of macOS

### ISSUE THREAD

**Issue by macwkcom** [JohnCoates/Aerial#1121]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Air 2017
- [ ] macOS Version: 10.15.7

#### Description of issue / Feature request

You can't use Aerial in this version of macOS.

![image](https://user-images.githubusercontent.com/53843550/97101969-78309c80-16dc-11eb-878f-6b8b10251221.png)

**Comment by glouel** [comment]
Hi @macwkcom 

Please check this entry in the FAQ (first one below the link) it should help you fix the issue : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#very-common-issuesmacos-bugs
