### ISSUE TITLE
Magic Window Air?

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#1123]
Not an issue... just a question:

I am a Setapp subscriber and saw [Magic Window Air](https://www.jetsoncreative.com/airmac) on there today. Description says:

_"Magic Window Air for Mac was created through a collaboration between Joshua Michaels (Jetson Creative), Hal Bergman (Fotologistics), and **Guillaume Louel (Aerial.)** [...] For this project we teamed up with Guillaume Louel, the developer behind the **Aerial Screen Saver**. Aerial is an excellent open source Screen Saver for Mac based on the Apple TV Screen Saver. Until now its content was limited to videos provided by Apple, but through this collaboration we were able to add to Aerial’s collection, and ultimately collaborate to create a complete travel experience with Magic Window Air."_

Just wondering what this means for Aerial as a standalone product. Is it going to continue along the same track or will development be shifted over towards MWA? Thanks for any insight!

**Comment by glouel** [comment]
Hey @luckman212 

So for those who didn't see it, MWA is basically Aerial, but running with another non-Apple set of videos, and it's available on Setapp as a separate product : https://setapp.com/apps/magic-window-air 

Aerial's code is MIT licensed so they were free to do so on their own, but asked me for a collaboration. As part of this we did get the free community videos in Aerial (which will have new improved versions of those soon). 

Regarding what this means for Aerial as a standalone product, well, there's no change really, it's still open source, and in terms of my investment, I'll still be developing it as usual here on Github, following the exact same track as before of doing my thing and implementing feature requests from github that make sense.

**Comment by luckman212** [comment]
@glouel Great, thank you very much for the clarification! Since I have Setapp I may try MWA...
