### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by shapkarin** [JohnCoates/Aerial#1125]
Hello. Is that possible to hide menu bar icon?

**Comment by glouel** [comment]
@shapkarin yep, pick no menu here : 

<img width="473" alt="Capture d’écran 2020-11-11 à 15 18 51" src="https://user-images.githubusercontent.com/37544189/98822497-379d8680-2431-11eb-857e-7a3b6dc85d6b.png">

It will launch periodically in the background to check for updates and will let you know if there's one, without the icon staying in your menu bar.

**Comment by shapkarin** [comment]
Thanks!

**Comment by glouel** [comment]
@kg-currenxie can you try the latest beta, see here : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.4.0beta1/AerialCompanion.dmg

**Comment by kg-currenxie** [comment]
Hi. Is it supposed to have the (no menu) item here? Choosing 'background' does not hide the icon, nor ask me to restart.

![Screenshot 2022-07-14 at 21 42 07](https://user-images.githubusercontent.com/48229166/178996362-d766033b-af44-4802-a0a7-02f9b221a180.png)
