### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by the-saint** [JohnCoates/Aerial#1126]
Late 2015 iMac
Big Sur

9:53:16 AM : avInit1 (0.0, 0.0, 296.0, 184.0)
9:53:16 AM : <AerialView: 0x7f9a2af0c970> AerialView setup init (V1.6.4)
9:53:16 AM : Time Management initialized
9:53:16 AM : Display Detection initialized
9:53:16 AM : ***Display Detection***
9:53:16 AM : 1 display(s) detected
9:53:16 AM : 1cm = 42.71653607460887 points
9:53:16 AM : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {2560, 1440}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69964952]
9:53:16 AM :        bottomLeftFrame (0.0, 0.0, 2560.0, 1440.0)
9:53:16 AM : src orig : (0.0, 0.0)
9:53:16 AM : left 0.0 below 0.0
9:53:16 AM : [id=69964952, width=2560, height=1440, bottomLeftFrame=(0.0, 0.0, 2560.0, 1440.0), topRightCorner=(2560.0, 1440.0), isMain=true, backingScaleFactor=2.0]
9:53:16 AM : (0.0, 0.0, 2560.0, 1440.0)
9:53:16 AM : ***Display Detection Done***
9:53:16 AM : <AerialView: 0x7f9a2af0c970> isPreview : true
9:53:16 AM : Using : nil
9:53:16 AM : <AerialView: 0x7f9a2af0c970> no local player
9:53:16 AM : <AerialView: 0x7f9a2af0c970> setupPlayerLayer
9:53:16 AM : <AerialView: 0x7f9a2af0c970> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
9:53:16 AM : Using dot workaround for video driver corruption
9:53:16 AM : Manifest init
9:53:17 AM : app support exists
9:53:17 AM : No customvideos.json at : /Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json
9:53:17 AM : isManifestCached 10 true
9:53:17 AM : isManifestCached 11 true
9:53:17 AM : isManifestCached 12 true
9:53:17 AM : isManifestCached 13 true
9:53:17 AM : 2020-11-10
9:53:18 AM : Interval : Optional(-294798.0869859457)
9:53:18 AM : No need to check for new videos
9:53:18 AM : Manifests files were not loaded in class
9:53:18 AM : Files were not already loaded in memory
9:53:18 AM : Manifests are cached on disk, loading
9:53:18 AM : Poi Strings Provider initialized
9:53:19 AM : Defaulting to bundle
9:53:19 AM : path : /Users/marc/Library/Screen Savers/Aerial-2.saver/Contents/Resources/en.json
9:53:19 AM : Community JSON : 73 entries
9:53:19 AM : No local or user cache exists, using ~/Library/Application Support/Aerial
9:53:19 AM : cache to be used : Optional("/Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
9:53:27 AM : Could not determine duration, video is not cached in any format
9:53:57 AM : Could not determine duration, video is not cached in any format
9:53:58 AM : Could not determine duration, video is not cached in any format
9:54:14 AM : Could not determine duration, video is not cached in any format
9:54:23 AM : Could not determine duration, video is not cached in any format
9:54:26 AM : Could not determine duration, video is not cached in any format
9:54:29 AM : Could not determine duration, video is not cached in any format
9:54:34 AM : Could not determine duration, video is not cached in any format
9:54:46 AM : Could not determine duration, video is not cached in any format
9:54:49 AM : Could not determine duration, video is not cached in any format
9:54:52 AM : Could not determine duration, video is not cached in any format
9:54:58 AM : Total videos processed : 99 callbacks : 0
9:54:58 AM : <AerialView: 0x7f9a2af0c970> Setting player for all player layers in []
9:54:58 AM : initvideocache
9:55:00 AM : cached video file with length: 105827826
9:55:00 AM : <AerialView: 0x7f9a2af0c970> playing video (OFFLINE MODE) : file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_GMT110_112NC_364D_1054_AURORA_ANTARTICA__COMP_FINAL_v34_PS_SDR_20181107_SDR_2K_AVC.mov
9:55:00 AM : <AerialView: 0x7f9a2af0c970> observing current item <AVPlayerItem: 0x600002bf8cb0, asset = <AVURLAsset: 0x6000029c7780, URL = file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_GMT110_112NC_364D_1054_AURORA_ANTARTICA__COMP_FINAL_v34_PS_SDR_20181107_SDR_2K_AVC.mov>>
9:55:00 AM : <AerialView: 0x7f9a2af0c970> observeValue Optional("readyForDisplay")
9:55:00 AM : AssetLoaderDelegate deinit
9:55:00 AM : <AerialView: 0x7f9a2af0c970> backing change 2.0 isDisabled: false
9:55:00 AM : <AerialView: 0x7f9a2af0c970> stopAnimation
9:55:10 AM : <AerialView: 0x7f9a2af0c970> startAnimation
9:55:10 AM : avInit1 (0.0, 0.0, 296.0, 184.0)
9:55:10 AM : <AerialView: 0x7f9a2af17b30> AerialView setup init (V1.6.4)
9:55:10 AM : <AerialView: 0x7f9a2af17b30> isPreview : true
9:55:10 AM : Using : nil
9:55:10 AM : <AerialView: 0x7f9a2af17b30> no local player
9:55:10 AM : <AerialView: 0x7f9a2af17b30> setupPlayerLayer
9:55:10 AM : <AerialView: 0x7f9a2af17b30> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
9:55:10 AM : Using dot workaround for video driver corruption
9:55:10 AM : <AerialView: 0x7f9a2af17b30> Setting player for all player layers in []
9:55:10 AM : initvideocache
9:55:15 AM : cached video file with length: 144093633
9:55:15 AM : <AerialView: 0x7f9a2af17b30> playing video (OFFLINE MODE) : file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_GMT306_139NC_139J_3066_CALI_TO_VEGAS_v08_SDR_PS_20180824_SDR_2K_AVC.mov
9:55:15 AM : <AerialView: 0x7f9a2af17b30> observing current item <AVPlayerItem: 0x600002bfde00, asset = <AVURLAsset: 0x6000029c2ea0, URL = file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_GMT306_139NC_139J_3066_CALI_TO_VEGAS_v08_SDR_PS_20180824_SDR_2K_AVC.mov>>
9:55:15 AM : <AerialView: 0x7f9a2af17b30> observeValue Optional("readyForDisplay")
9:55:15 AM : AssetLoaderDelegate deinit
9:55:15 AM : <AerialView: 0x7f9a2af17b30> backing change 2.0 isDisabled: false
9:55:20 AM : <AerialView: 0x7f9a2af17b30> startAnimation
9:55:20 AM : <AerialView: 0x7f9a2af0c970> observeValue Optional("readyForDisplay")
9:55:21 AM : <AerialView: 0x7f9a2af17b30> observeValue Optional("readyForDisplay")
9:55:28 AM : <AerialView: 0x7f9a2af17b30> stopAnimation
9:55:28 AM : pwc init2
9:55:30 AM : Callback after manifest loading
9:55:30 AM : Looking for outdated files
9:55:30 AM : SE_A016_C009_SDR_20190717_SDR_2K_AVC.mov NOT FOUND in manifest
9:55:30 AM : 1 old files found
9:55:32 AM : Aerial control panel V1.6.4
9:56:28 AM : Cache size : 22.55 GB
9:56:29 AM : Location services may be disabled, Night Shift can't detect Sunrise and Sunset times without them
9:56:29 AM : cvcinit2
9:56:30 AM : cvcawake
9:56:30 AM : wdl
9:57:37 AM : <AerialView: 0x7f9a2af0c970> played did reach end
9:57:37 AM : <AerialView: 0x7f9a2af0c970> notification: name = AVPlayerItemDidPlayToEndTimeNotification, object = Optional(<AVPlayerItem: 0x600002bf8cb0, asset = <AVURLAsset: 0x6000029c7780, URL = file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_GMT110_112NC_364D_1054_AURORA_ANTARTICA__COMP_FINAL_v34_PS_SDR_20181107_SDR_2K_AVC.mov>>), userInfo = nil
9:57:37 AM : <AerialView: 0x7f9a2af0c970> observeValue Optional("readyForDisplay")
9:57:37 AM : <AerialView: 0x7f9a2af0c970> Setting player for all player layers in []
9:57:37 AM : initvideocache
9:57:41 AM : cached video file with length: 258355456
9:57:41 AM : <AerialView: 0x7f9a2af0c970> playing video (OFFLINE MODE) : file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_L004_C011_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov
9:57:41 AM : <AerialView: 0x7f9a2af0c970> observing current item <AVPlayerItem: 0x600002bccef0, asset = <AVURLAsset: 0x600002880380, URL = file:///Users/marc/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_L004_C011_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov>>
9:57:41 AM : AssetLoaderDelegate deinit
9:57:41 AM : <AerialView: 0x7f9a2af0c970> playing next video for player Optional(<AVPlayer: 0x600002bd2f20>)
9:57:41 AM : <AerialView: 0x7f9a2af0c970> observeValue Optional("readyForDisplay")
9:58:07 AM : Playing this preview id=3716DD4B-01C0-4F5B-8DD6-DB771EC472FB,
name=Gray Reef Sharks,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/FK_U009_C004_SDR_20191220_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/FK_U009_C004_SDR_20191220_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/FK_U009_C004_HDR_20191220_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/FK_U009_C004_SDR_20191220_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/FK_U009_C004_HDR_20191220_HDR_4K_HEVC.mov"
9:59:08 AM : UI newDisplayModeClick: 1
9:59:13 AM : UI newViewingModeClick: 0
9:59:13 AM : ***Display Detection***
9:59:13 AM : 1 display(s) detected
9:59:13 AM : 1cm = 42.71653607460887 points
9:59:13 AM : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69964952, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {2560, 1440}]
9:59:13 AM :        bottomLeftFrame (0.0, 0.0, 2560.0, 1440.0)
9:59:13 AM : src orig : (0.0, 0.0)
9:59:13 AM : left 0.0 below 0.0
9:59:13 AM : [id=69964952, width=2560, height=1440, bottomLeftFrame=(0.0, 0.0, 2560.0, 1440.0), topRightCorner=(2560.0, 1440.0), isMain=true, backingScaleFactor=2.0]
9:59:13 AM : (0.0, 0.0, 2560.0, 1440.0)
9:59:13 AM : ***Display Detection Done***

#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
> 9:53:16 AM : <AerialView: 0x7f9a2af0c970> AerialView setup init (V1.6.4)

@the-saint looks like you are running a very old version of Aerial, 1.6.4, current version is 2.1.1, I would suggest upgrading. Latest versions supports Big Sur.

**Comment by the-saint** [comment]
It worked when I changed the directory for the cache files and moved the files. Why isn’t the screensaver automatically updating the way it’s supposed to?

**Comment by glouel** [comment]
Apple introduced restrictions on screensavers, they can no longer update themselves starting with Catalina, and have restricted access to the filesystem too. 

There's a new auto update system using the companion that you can find here :  https://aerialscreensaver.github.io

**Comment by the-saint** [comment]
Thanks. I found this after I sent my last message. Will this automatically update to the latest version of the screensaver when I install it?

**Comment by glouel** [comment]
Yep it will automatically install latest version and keep you up to date.

**Comment by the-saint** [comment]
Now I have two Aerials in my screensaver list, and when I use a hot corner, the screen goes black and simulates a freeze.

**Comment by glouel** [comment]
Use right click on the screensaver list to delete both, then reinstall via companion.

**Comment by glouel** [comment]
You may also need to reset settings as some things won't work. A screensaver can only write in it's container now, so you can't just have any location for your files. Again Apple restriction. Go here to reset : 
<img width="1109" alt="Capture d’écran 2020-11-13 à 20 26 06" src="https://user-images.githubusercontent.com/37544189/99112779-7f1d4180-25ee-11eb-9406-ecc6789f8eab.png">

**Comment by the-saint** [comment]
I did this. I click on Aerial in Applications and nothing happens.

**Comment by glouel** [comment]
Look in your menu bar, the companion is here, you should get the option to reinstall in there :  
<img width="291" alt="Capture d’écran 2020-11-13 à 20 28 17" src="https://user-images.githubusercontent.com/37544189/99112965-c60b3700-25ee-11eb-8525-fdcd9871157d.png">

**Comment by the-saint** [comment]
I can’t even get here because when I click to open Aerial in my Applications folder, it doesn’t open.

**Comment by the-saint** [comment]
I see this. What am I supposed to do with it?

**Comment by glouel** [comment]
If it's already installed, it will say so, and tell you which version is installed. If it's not installed, there's an install button in there. 

If that doesn't work for you follow the instructions here to fully uninstall and reinstall : https://aerialscreensaver.github.io/installation.html

**Comment by the-saint** [comment]
I don’t know if you saw my last message, because it had an embedded image file. It said it timed out and couldn’t download the screensaver. I eventually managed to download it, it hosed my system when I looked at a sample, and I had to use the power button to restart. I uninstalled it. It’s not worth the trouble. I’ll check back in six months or so when you’ve worked out the issues.
