### ISSUE TITLE
Doesn't download anything

### ISSUE THREAD

**Issue by kenzaflow** [JohnCoates/Aerial#1127]
Hi!

I have the latest version 2.1.1

and i didn't find any solution

- Mac model: xD
- macOS version: Big Sur 11.0.1
- Monitor setup: Samsung F390

In the program configuration, above "Close" button is always kept on "Downloading 0 / 20"

the Cache folder is always empty

any solution?

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5540098/AerialLog.txt)

**Comment by glouel** [comment]
Hey there,

Couple of options : 
- Are you using a firewall like Little Snitch ? If so by default it silently blocks network connexions for screensavers, you have to remove those rules for Aerial to work. More info here : https://aerialscreensaver.github.io/troubleshooting.html
- If not, please try closing system preferences (the whole thing, not just Aerial's preference panel) and reopen it, sometimes things get stuck somehow and by restarting system preferences, you're reloading Aerial and usually stuck things get unstuck 

Let me know how that works for you

**Comment by glouel** [comment]
Please reopen if you need more assistance

**Comment by jfromaniello** [comment]
same, and same logs... not firewall either. Tried closing preferences, and also rebooting. It seems to download stuff when playing in the screen saver, eg with "Launch Now". But if I try to download the videos upfront from preferences then it hangs with 0/116.


![image](https://user-images.githubusercontent.com/178512/106626892-ed6f0180-6556-11eb-815b-1e405a375e11.png)

**Comment by glouel** [comment]
Hey @jfromaniello 

Can you leave it like that for like a few mins to see if it actually moves ? I know that some of the servers can be super slow sometimes. If you can paste a more complete log that may be helpful too, thanks ! I'll do a double check around here and let you know.

**Comment by jfromaniello** [comment]
sure, I will do that with only one video. Is there a URL I can manually try, for instance with wget/curl, to see how slow is to download the video from my connection?

**Comment by glouel** [comment]
@jfromaniello 

Here's one from Github : https://github.com/glouel/AerialCommunity/releases/download/mw2-4k-sdr/video_inspire_florida_miami_brickell_sunset_00036.4k-sdr.mov

One from Apple : https://sylvan.apple.com/Aerials/2x/Videos/SE_A016_C009_HDR_20190717_3m30s_HDR_4K_HEVC.mov

**Comment by jfromaniello** [comment]
that might be it then, github is 5x faster than apple in this case. Downloading the one from apple takes 1 hour with my connection 🤦🏽

**Comment by glouel** [comment]
Oh wow, just curious, is the Apple TV sold in your country ? Their CDN may not give a lot of bandwidth depending on regions where they don't sell it, maybe ? 

(I know it's not sold in China and completely blocked there, but that's the "great" firewall)

One thing you can do to make it a bit more manageable : 

![Capture d’écran 2021-02-02 à 17 28 31](https://user-images.githubusercontent.com/37544189/106630592-400ee480-657c-11eb-885e-02df517efed4.jpg)

Uncheck automatic downloads

![Capture d’écran 2021-02-02 à 17 28 05](https://user-images.githubusercontent.com/37544189/106630601-42713e80-657c-11eb-819f-c64a76ff05df.jpg)

Then next to each videos, you'll see a down arrow to individually download a file. Then you can scroll down the list, look for sources, from Josh, those are the GitHub hosted ones so those should go quickly, then for the rest you can do it bit by bit. 

Also you can do that do do it City by City for example, right/option click something on the right column to grab the missing ones for that filter : 
<img width="290" alt="Capture d’écran 2021-02-02 à 17 31 16" src="https://user-images.githubusercontent.com/37544189/106630837-78aebe00-657c-11eb-9ce8-c628e721a40a.png">

**Comment by jfromaniello** [comment]
It is according to this page:
https://support.apple.com/en-us/HT204411

and I actually own one, and I think it already downloaded all the videos.. works well. Maybe is something more specific with my ISP.

Thank you for the suggestion, I will try that

**Comment by glouel** [comment]
Apple TV downloads them overnight and doesn't stream them (unless that changed with tvOS14) and only downloads a few (the whole set is more than 32 GB), specifically to avoid any speed issues. Thanks for the confirmation, let me know how that works for you.

**Comment by jfromaniello** [comment]
Maybe what could help in this specific UI is to show the progress per video... otherwise it seems unresponsive

```
Downloading 0/116
Current file 50%..
```

or something like that

**Comment by glouel** [comment]
Yep I definitely need to improve that indicator because it's way too minimalist, I meant to improve it earlier but never did... I'll put that on my list thanks !
