### ISSUE TITLE
Request: Webpages as screensaver

### ISSUE THREAD

**Issue by BrunoAMSilva** [JohnCoates/Aerial#1129]
I like to do some html canvas animations. Is there any chance to incorporate webpages as screensavers?

**Comment by glouel** [comment]
Hey @BrunoAMSilva 

That's not something that's currently planned, it would be significantly different from what Aerial usually does. You may be better served by this project instead : https://github.com/liquidx/webviewscreensaver

**Comment by BrunoAMSilva** [comment]
Thank you. It does indeed work great. But it's a bit of a pain for end-users to install and manage. Aerial does all that really well and having an included library of content is a plus for users. Hope you can reconsider some day. Thank you and keep up the excellent work!

**Comment by glouel** [comment]
It's an interesting idea so I'll keep it in mind for a possible future release, thanks !
