### ISSUE TITLE
Crashes when attempting to set custom cache folder location

### ISSUE THREAD

**Issue by brian163** [JohnCoates/Aerial#1133]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed [**2.1.4b1**] (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Mac Pro 2012
- [x ] macOS version: 10.14.6
- [x] Monitor setup: Two displays

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

When I click "Pick Folder" the configuration window "rolls up", leaving me in a blank Desktop & Screen Saver preference pane that I have to quit to reload. One time, while trying a few things to potentially get around this, the Screen Saver panel simply would not load anymore at all (same blank panel on opening D&S) unless Desktop & Screen Saver/Screen Saver would open to a different Screen Saver (almost like the OS was resetting it's own preference file?). 

I'm not sure if a debug dump will help in this case, however, I would catch the following error in the system.log (the legacy file, not the Console) at the moment it would seem to "crash":

Nov 21 23:26:59 Erin com.apple.xpc.launchd[1] (com.apple.preference.desktopscreeneffect.desktop.remoteservice[3338]): Service exited due to SIGKILL | sent by com.apple.preference.desktopscre[3338]

I'd be glad to provide a short video or any other info required to diagnose this. For now, I'm just excluding the Cache directory from Time Machine but I'd really like to move it to my much larger external disk array.

**Comment by glouel** [comment]
Hey @brian163 

There's been a few reports of this that I haven't managed to investigate. Do you think you could send me a AerialLog.txt of a launch where it crashes (enable/find in Settings > Advanced in Aerial's panel) ? It may contains some path information for me to double check. 

Since that feature is no longer possible on Catalina/Big Sur it's not super easy for me to investigate but I'll try to have a look today and let you know.

**Comment by glouel** [comment]
@brian163 I managed to have a look and found two huge bugs, including the one you likely experienced when clicking "Pick Folder". 

I'm 95% confident it's now fixed in just released 2.1.5, can you give it a try ?

**Comment by brian163** [comment]
It fixed it for me! Thank you.

However, I'd also like to suggest that changing this setting either warn the user that their existing cache files will be deleted (so perhaps they can copy/move them first?) or change the behavior that it does not delete the existing cache files and provide the user the opportunity to copy/move them. (Or for it to just copy them to the new location when you click the button independent of the folder selection process?)

I had 100 some videos in cache that I would have preferred to simply copy and not re-download which is a ton of bandwidth  and time consuming (it ran for hours yesterday). :-/

**Comment by glouel** [comment]
Thanks a whole lot for the confirmation @brian163 !

But I don't believe I delete the videos from the old cache ! Right now I don't copy them, true, but I'm fairly positive they are still there. Look at `~/Library/Application Support/Aerial/Cache` I'm 99.9% confident they are still there ;) 

Just move them to your new folder and you should be set. Can you confirm that after setting the path (if you redid it) you were warned to restart System Preferences ? I could probably add a longer message here about moving your videos or something. 

I could also maybe change that box to ask if you want to ove the videos to the new folder or not, I'll keep it in mind.

**Comment by brian163** [comment]
Ah, I was confused by the existence of the directory ~/Library/Caches/Aerial/. I had been referring to "https://aerialscreensaver.github.io/faq.html#uninstallPreCatalina prior" which mentions:

"It is **reccomended** that you only take this step if you are familiar with Terminal. You can manually remove your Cache by **nagivating** to ~/Library/Caches/Aerial and deleting the "Cache" folder manually." 

(Minor FYI, if you might update that section based on my noting this, I noted two typos in that sentence in bold. :-) )

**Comment by glouel** [comment]
Good catch about the typo and yep definitely I wlll clarify that in the documentation and next build, thanks !

**Comment by glouel** [comment]
Fixed typos and path thanks, older versions of Aerial used to store in `Caches` instead of `Application Support`, it's very confusing...
