### ISSUE TITLE
How to remove a video that is already downloaded

### ISSUE THREAD

**Issue by thefuckingcode** [JohnCoates/Aerial#1134]
#### General troubleshooting tips

How to remove a video that is already downloaded

#### Description of issue / Feature request

How to remove a video that is already downloaded

**Comment by glouel** [comment]
Are you using manual or automatic downloads ? 

In automatic downloads, hiding the video will make sure it won't get downloaded again and delete it when reclaiming space for newer videos.

In manual I'm not exactly sure off the top of my head if I delete hidden videos too. I'll have another look if that's your setup.

**Comment by thefuckingcode** [comment]
> Are you using manual or automatic downloads ?
> 
> In automatic downloads, hiding the video will make sure it won't get downloaded again and delete it when reclaiming space for newer videos.
> 
> In manual I'm not exactly sure off the top of my head if I delete hidden videos too. I'll have another look if that's your setup.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/23526448/100033564-66eec300-2e35-11eb-9d18-20c4db0e7382.png">
i found the path. check the automatically download videos button, the click show in finder

**Comment by glouel** [comment]
Ideally I'll add back a right click to delete or something but that works in the meantime !
