### ISSUE TITLE
Aerial 2.2.4 won't work in latest Big Sur beta (11.1 - 20C69)

### ISSUE THREAD

**Issue by BymBam** [JohnCoates/Aerial#1139]
- [ ] Mac model: iMac 27 2019
- [ ] macOS version: Big Sur 11.1 - 20C69
- [ ] Monitor setup: Internal

#### Description of issue / Feature request

Aerial 2.2.4 won't install in latest Big Sur beta (11.1 - 20C69).
Says it is not compatible with this System version.
Oddly enough, Aerial 2.2.3  IS  compatible and working on this System

**Comment by glouel** [comment]
Hey @BymBam 

This is weird, I'm running the same Big Sur build and just tested 2.2.4 and it starts fine here. Did you try closing System Preferences with Aerial selected in the list ? There's a longstanding bug with Swift screensavers and System Preferences that can cause that issue. Usually closing (fully) System Preferences and reopening it will fix it. Let me know.

**Comment by BymBam** [comment]
Applied your suggestion.
Aerial 2.2.4 Works perfectly now.

Thanks Glouel !
