### ISSUE TITLE
Unable to select which vid to play in screen saver options

### ISSUE THREAD

**Issue by RoketteS** [JohnCoates/Aerial#114]
Ls,

After an update to beta 4 of release 1.2 of the aerial screensaver I am unable to  select which vid to play in screen saver options. The List is empty (see screenshot).

Globally installed for all users.

Regards,
Steve
![screen shot 2015-11-01 at 13 47 52](https://cloud.githubusercontent.com/assets/381721/10868968/8b931b00-809f-11e5-9112-840a9090d96f.png)

**Comment by alistairmcmillan** [comment]
Duplicate of #26

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #26
