### ISSUE TITLE
Request - Screensaver on Roku

### ISSUE THREAD

**Issue by Godis1coolguy** [JohnCoates/Aerial#1142]
I saw there were ports to Windows and Linux by other devs, so I'm guessing this project will stay focused on Mac. Could this project ever expand to get these videos as screensavers on a Roku device though?

**Comment by glouel** [comment]
Sorry, I don't have a Roku so 0 plan from me to port it.

**Comment by Godis1coolguy** [comment]
No worries, I figured it was a long shot. Thanks for the quick reply!
