### ISSUE TITLE
Feature Request: Control to turn on/off time display

### ISSUE THREAD

**Issue by RickyRiccardo** [JohnCoates/Aerial#1144]
Request to add a control to setting to control time display, eg, on/off, 12 vs 24 hr, display seconds.

**Comment by glouel** [comment]
Hey there,

check settings - overlays - time you should find pretty much everything there

**Comment by glouel** [comment]
<img width="1098" alt="Capture d’écran 2021-01-02 à 15 26 18" src="https://user-images.githubusercontent.com/37544189/103459328-de562300-4d0e-11eb-9e06-420a6d54a77e.png">

@RickyRiccardo here's a screenshot of those settings above.

**Comment by RickyRiccardo** [comment]
Very cool!  Thank you.  I knew it had to be there somewhere!

Cheers,

Rick
