### ISSUE TITLE
Stops playing video after 2-3 seconds

### ISSUE THREAD

**Issue by olganagorna** [JohnCoates/Aerial#115]
In settings menu video is working fine, but when i click preview or wait till it turns on video just plays first 2-3 seconds and then stops as image and never goes on after.

10.11 beta 3

**Comment by h092211** [comment]
Same issue found in my mac.

**Comment by yzsolo** [comment]
Same issue +1

**Comment by chrislowthian** [comment]
Same for me after 2 or 3 scenes being played.

**Comment by matbloom** [comment]
Same issue - 2 seconds then freezes.

**Comment by grantr1961** [comment]
Same issue - a few seconds then freezes, even in Preview.  Seemed to be working better a couple of days ago .. congestion on the server these videos are being streamed from???   (Retina 5K 27" late-2014 iMac, running Yosemite 10.10.5)

**Comment by testzugang** [comment]
Seems to happen with beta 4 when videos are cached but not downloaded completely. You can delete the partial file by hand to trigger the download again. The cached files are saved in /Users/USER/Library/Caches/Aerial

**Comment by bytehala** [comment]
<img width="729" alt="screenshot 2015-11-07 09 51 53" src="https://cloud.githubusercontent.com/assets/2638498/11012809/3a4bf7c2-8535-11e5-9460-e9412337db55.png">

I'm also experiencing this issue, but there's no Aerial in my Caches directory. I'm on El Capitan.

**Comment by h092211** [comment]
Im on El Capitan too, and the cache files appears, but empty.

**Comment by alistairmcmillan** [comment]
Issues likely resolved with complete implementation of caching in v1.2.
