### ISSUE TITLE
Allow for content to be "zoomed" instead of "stretched" for use on 21:9 or wider screens.

### ISSUE THREAD

**Issue by bmcd243** [JohnCoates/Aerial#1155]
With my ultrawide monitor, I currently have two options - either choose "fit screen" so that the content shows in 16:9 with black bars either side OR "stretch to fill" and you get a pretty bad looking stretched image.

I think it would be much better if there was an option to "zoom/crop" the screensaver instead so that it still fills the screen, but the video isn't stretched.

**Comment by glouel** [comment]
Hey @bmcd243 

Unless I'm mistaken, fill is exactly what you are asking for, it's "zooming" (aka stretching with a constant ratio). Precisely it's zooming so the width of the video is filling the screen, and it's cropping the bottom/top parts. I may be wrong (my screens happen to be 16/9 right now so can't double check). 

It may look pretty bad depending on your monitor resolution/ratio and the source (especially if not using 4K).

Can you give me more details on your screen, and a screenshot of that panel : 

<img width="1109" alt="Capture d’écran 2021-02-21 à 17 05 31" src="https://user-images.githubusercontent.com/37544189/108630825-1fdd9180-7467-11eb-96a7-f9ff8f10e107.png">

The preview should show what will happen (but there may be a bug in there so I'd rather check). Thanks

**Comment by bmcd243** [comment]
![Screenshot 2021-02-21 at 19 52 49](https://user-images.githubusercontent.com/64990696/108636623-625e9880-747e-11eb-9e02-f60ddc3b4d06.png)

Hey @glouel, thanks for your response :)

It doesn't look too bad TBH but what I think is currently happening is that the image is being stretched horizontally to fit the screen whereas I am asking if it could be zoomed from the centre point...that way the image will slightly lower res as you are losing some of the outer-part of the video BUT it doesn't appear distorted.

It's difficult to explain...I hope that makes sense.

**Comment by glouel** [comment]
Ok thanks for confirming, if you look at the screenshot, you can see that it crops bottom/top here on the left screen (compared to the right, look at the clouds etc), and that's what you should get in theory with fill mode, and I believe what you are asking. 

So maybe there's something wrong with my code and instead of filling with correct aspect ratio it does compress vertically (though that should look unmistakably VERY wrong), I'll try to have a look if I can simulate something tomorrow and let you know !

**Comment by bmcd243** [comment]
Ah, it looks like you are right there as the top and bottom of the image has definitely been cut-off so it definitely isn't being stretched just horizontally.

I'd be really grateful to know what exactly happens so keep me posted!

**Comment by glouel** [comment]
Any chance you could took a picture of one video playing maybe on your screen ? That may give me an insight on what goes on. Thanks !

**Comment by glouel** [comment]
Hey again @bmcd243 

So I did a triple check and I believe that everything is actually fine, here's an example with Aerial running on a simulated 21:9 screen (This is Los Angeles - Santa Monica Beach, in the fist few seconds of the video) : 

![Capture d’écran 2021-02-22 à 15 23 06](https://user-images.githubusercontent.com/37544189/108721390-3c8acf80-7522-11eb-87a9-87b13c9858e6.jpg)

Now look at the same one on a simulated 16:9 : 

![Capture d’écran 2021-02-22 à 15 23 42](https://user-images.githubusercontent.com/37544189/108721502-5a583480-7522-11eb-973e-767162e633fa.jpg)

What Aerial exactly does is it scales with a constant aspect ratio to the monitor width (in this case), so to take a simple example if you have a 1920x1080 video and a 2560x1080 screen : 

- Aerial upscales the video from 1920x1080 to 2560x1440 with a constant aspect ratio (scales as much horizontally than vertically). 
- It displays that video on screen, centering the center of the video with the center of the screen (complicated way to say, it crops (180px from both the top and bottom of the video)

You can see exactly that above, there's no one way stretching that would make it look weird (look at the square on the tower, it's square on both), it just try to "fill" your screen without deforming the video. So unless you are seeing something different (in that case, take a picture of your screen running the same video), I don't think there's anything wrong here ?

**Comment by glouel** [comment]
@bmcd243 

No worries. It may not be your monitor. There's a handful of old videos that are 1080p only, those may be the ones you think look weird. 

You can disable those if you want (look for the tvOS 10 source, then right click and hide) : 

<img width="359" alt="Capture d’écran 2021-02-22 à 16 42 15" src="https://user-images.githubusercontent.com/37544189/108731608-0272fb00-752d-11eb-8ce0-dd32a946a114.png">

Also some videos aren't sharp at all, it's just the way they are. You can hide anything you don't like the same way in the UI. 

HDR does look different even if  you don't have a "HDR" monitor, macOS does some massaging of the colors to make them pop more. The result may look wrong though depending on monitors and taste, so really up to you on this, it's really a question of personal preference. HDR does require a bit more resources to process though !

**Comment by bmcd243** [comment]
Cheers @glouel, I'll do that.

For the "pop" feature to make videos look more vibrant, am I right in saying that I would need to switch to 4K HEVC to be able to use this?

**Comment by glouel** [comment]
Yep you are right, or it will apply it to non HDR video.

For example if you set to 4K HDR, Aerial will play most videos (the recent ones from Apple) in HDR, but for the other ones (the ones from Joshua, or the tvOS 10, etc), the pop feature will be applied on those when they play. 

If you set to 4K HEVC, it will apply to everything (and depending on your monitor/mac, it may look more pleasing than HDR). 

It's both here for consistency (bring some pop for non hdr versions) or popping everything. 

I think I made my explanation way too complex, hopefully that still makes sense 😅

**Comment by bmcd243** [comment]
Yeah, that makes perfect sense...looks like I will have to re-download all videos as HEVC though :/

**Comment by glouel** [comment]
Yep I should have started with that, each resolution is a separate set of files. I think this is obvious to me but it's probably not in the UI. I should probably clarify that. 

Here are two links if you want to compare beforehand (you can open in Safari).

HDR : https://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A008_C004_ALTB_ED_FROM_FLAME_RETIME_v46_HDR_PS_20180917_HDR_4K_HEVC.mov

SDR : https://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A008_C004_ALTB_ED_FROM_FLAME_RETIME_v46_SDR_PS_20180917_SDR_4K_HEVC.mov

**Comment by bmcd243** [comment]
Such a massive difference...I never knew you could view mov files directly in Safari, very cool 👍 

I'll go ahead and close this issue - thanks for all your help :)

**Comment by glouel** [comment]
No problem ! Take care!
