### ISSUE TITLE
Feature request: Allow newlines in Message overlay.

### ISSUE THREAD

**Issue by Mayzie** [JohnCoates/Aerial#1159]
#### Required information

- [x] Mac model: MacBook Pro (15-inch, 2018)
- [x] macOS version: Big Sur, 11.2.2 (20D80)
- [x] Monitor setup: Single

#### Feature request

Would it be possible to please add support for newlines in the Message overlay? Allowing basic (HTML) styling would be cool, too 🙂 

I'm just thinking of having a message like:

```
<My Name>
<Phone Number>
<EMail>
```

Thank you!

**Comment by glouel** [comment]
Hey there @Mayzie !

That's a great idea (for the new line), I'll put it on my list for next version that should be pretty straightforward to do. 

HTML is a bit messier to do with how Aerial currently works, so I'll stick to new lines for the moment ;)

**Comment by Mayzie** [comment]
Thank you so much! 🥳 🤩

My memory is very hazy on this, but wasn't there a Swift text component that could parse and display very basic HTML? Might make things a bit easier if it's possible to just swap it out.

Also, also, another neat thing (if it's also easy), would be to have two messages. One that is shown when the user selector isn't visible, and one when it is? 🙂 (given my name is already my user account name, it'd show twice)

**Comment by glouel** [comment]
Hey @Mayzie 

So regarding HTML, I think one can use a WKWebKitView to do that, but those are higher level components (and this one is super heavy/comes with macOS versions restrictions, I remember using it for a while for auto updates, bit of a mess !). There was a lighter solution but I think it's deprecated. I would need to double check. In any case, for a lot of bad reasons (mostly, this was my first mac project !), Aerial's text drawing is done using low level APIs like `CoreAnimation` and `CATextLayer`. 

I only recently found out that I could have used higher level components like `NSTextField`, which would have saved me so many headaches 🙈 Anyway, that will probably come at some point but the current system is so complex that I just can bring in something higher level easily, though it's something I hope to work on at some point.

Multiple messages is something that's been on my list for a while, it's halfway ready, I still have some issues to solve around that, but it's coming at some point. 

In the meantime, I may have a beta out later this week with new line support, I'll keep you posted.

**Comment by Mayzie** [comment]
Thanks @glouel, you're amazing! 🤩

> Slightly unclear about that though ? Which user selector are you talking about ? 

I meant the two different states that's common on the screensaver page:

1) Just shows the screensaver, and nothing else.
2) You move the mouse a little, and it shows you your user account, profile picture, name, and prompts you for a password.

Is it possible to have two states of the text for the above? i.e. one text A that shows while not focused, and text B that shows instead while focused?

**Comment by glouel** [comment]
> I meant the two different states that's common on the screensaver page:
> 
> 1. Just shows the screensaver, and nothing else.
> 2. You move the mouse a little, and it shows you your user account, profile picture, name, and prompts you for a password.
> 
> Is it possible to have two states of the text for the above? i.e. one text string that shows while not focused, and another text string that shows instead while focused?

Ha got it now. So that's a bit outside of the running of the screensaver. The screensaver itself is not the one prompting you for your password and right now, I don't think I can detect that moment when you press a key or move your mouse to bring the password prompt (or, if you don't have the password requirement, bring you back directly to macOS, both can happen depending on your settings, there's also a min delay for password etc). 

All of this is handled by the OS, and not the screensaver. I can't even detect/intercept mouse moves or key presses anymore since Catalina, so for the time being, that's not possible I think to have a special state there. 

Multi line is done though, beta should be out tonight, trying to get shell support in too : 

![Capture d’écran 2021-03-03 à 12 05 25](https://user-images.githubusercontent.com/37544189/109797209-6fffe500-7c19-11eb-88e6-e00d5d211f7a.jpg)

**Comment by glouel** [comment]
Beta is up, if you are using companion, switch desired version to beta and update : 

<img width="394" alt="Capture d’écran 2021-03-03 à 16 55 24" src="https://user-images.githubusercontent.com/37544189/109833073-41960000-7c41-11eb-9054-cc739b866c69.png">

Direct link : https://github.com/JohnCoates/Aerial/releases/download/v2.2.8beta1/Aerial.saver.zip

**Comment by Mayzie** [comment]
Works amazingly! Thank you so much!
