### ISSUE TITLE
Aerial currently plays: Downloaded

### ISSUE THREAD

**Issue by KAMIKAZEUA** [JohnCoates/Aerial#1162]
- Mac model: mac Mini 2018
- macOS version: 11.2.3 (20D91)
- Monitor setup: USB-C DELL 

#### Description of issue / Feature request

I just need option to play only **Downloaded** videos.

At them moment this is not available: 

**2.2.8beta4**

<img width="553" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/111306608-178d0680-8661-11eb-93ff-1ee1e6eadfb6.png">

**Comment by glouel** [comment]
Hey @KAMIKAZEUA 

What did you pick for cache settings here : 

<img width="1098" alt="Capture d’écran 2021-03-16 à 13 14 15" src="https://user-images.githubusercontent.com/37544189/111307287-84040780-8659-11eb-8164-a781ed5933ad.png">

I know this is a bit complicated and I need to improve on it, but basically there are two ways to make Aerial work right now :

- If you check the "Automatically download videos" here, Aerial will periodically download videos on its own, and rotate them if you asked it to (a cache limit can be set). If that limit is reached, and for example you set a long rotation/no rotation, it will not download anything and only play what's been downloaded.

- If you don't check that box (like my screenshot), Aerial will not download anything on its own. So if you are using that mode, whatever option you pick in your screenshot will only play what's been downloaded, and nothing else. If you pick an option for which you have no video (say you have no Dubai video downloaded but picked Dubai), Aerial will revert to whatever is in your Cache. 

I believe what you want is the full manual mode, so I'd recommend unchecking that box. Does that make sense ?

I really need to rework the whole Currently playing panel so it shows explains exactly what is going to happen based on settings, it's a big project I've been thinking about a lot, hopefully it should make things a lot more self explanatory for everyone.

Let me know if that answers your question.

**Comment by KAMIKAZEUA** [comment]
I have disabled it before, so it's still like this: 

<img width="610" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/111308246-1e1c7d80-8663-11eb-8f38-4aa3bcd6f550.png">

Yes, that was my logic before I created this bug: I was thinking that it should only play what's been downloaded, and nothing else. But it's plays anyway, it's just not downloading, it's plays stream.

I just did a quick test: renamed **Cache** to **Cache_old** and wait 1 min, it's launched and showed me some video, from **Everything**. 

But I still have disabled "**Automatically download videos**".

**Comment by glouel** [comment]
> I have disabled it before, so it's still like this:
> 
> <img alt="Screenshot" width="610" src="https://user-images.githubusercontent.com/3391456/111308246-1e1c7d80-8663-11eb-8f38-4aa3bcd6f550.png">
> 
> Yes, that was my logic before I created this bug: I was thinking that it should only play what's been downloaded, and nothing else. But it's plays anyway, it's just not downloading, it's plays stream.

As long as you at least have **one** video downloaded in your cache, that how it operates yes. If you think it streams while you have videos, please attach your AerialLog.txt with the time you think it's happening, so I can have a look. 

> I just did a quick test: renamed **Cache** to **Cache_old** and wait 1 min, it's launched and showed me some video, from **Everything**.

So this is a special case. If you have **nothing** in your cache, it will stream one video in the background. Until you have at least one video in your cache, it will revert to streaming, that's really a special case and should not be confused with regular usage.  

Makes sense ?

**Comment by KAMIKAZEUA** [comment]
Perhaps I was mistaken, but I think I saw that the video was played, which was **not in the cache**. 
Thats why I was thinking about such option - to play only from Cache. Actually this could be helpful option anyway. 

Anyway, I will be watching this more, later I will inform about the results.

**Comment by glouel** [comment]
It's possible there's a bug I haven't caught, or a specific condition that was triggered, but the manual mode is pretty straightforward and rarely has issues. 

If you have your logs enabled, check your AerialLog.txt and look for the word stream, you should only find it regarding your test, or if you change resolution or something. If you see more occurences then send me that log so I can have a look, thanks.

**Comment by KAMIKAZEUA** [comment]
Yes, this was my mistake, it's playing only from cache. Thanks for your answers and help! I will close this now.

p.s. I think such option for currently plays "**Downloaded**", should be added. 
If so, if there is no videos in **Cache** - just show black screen with text: no videos in cache :), otherwise play only from cache.

**Comment by glouel** [comment]
> Yes, this was my mistake, it's playing only from cache. Thanks for your answers and help! I will close this now.
> 
> p.s. I think such option for currently plays "**Downloaded**", should be added.
> If so, if there is no videos in **Cache** - just show black screen with text: no videos in cache :), otherwise play only from cache.

No worries, thanks for following up !

<img width="560" alt="Capture d’écran 2021-03-19 à 15 06 23" src="https://user-images.githubusercontent.com/37544189/111792598-afd6f580-88c4-11eb-80e5-1cf63aff8332.png">

I think the big problem is that in manual mode, in "Currently playing", the list shows every video that fits the criteria, and not just those that are cached. That leads to a lot of confusion, because in manual mode only the cached videos can play. 

Short term I'll see if I can fix that for manual mode, showing only the cached videos here (it makes sense showing cached and uncached in automatic mode, but not here, but it's the same code which is I think the root of the confusion).

At some point what I want is if you select currently playing, I won't show a list of videos on the left as it is right now but a full screen panel that recaps everything and will show you exactly which video will play in which conditions (which depends on so many stuff like, cache mode, time adaptation, etc) and some buttons to quickly change settings. 

Thanks for your feedback !
