### ISSUE TITLE
Can I change the menu button on Apple TV?

### ISSUE THREAD

**Issue by baehongjun0212** [JohnCoates/Aerial#1164]
![스크린샷 2021-03-30 오후 3 38 40](https://user-images.githubusercontent.com/55692618/112947690-12a47880-9172-11eb-985b-2171e85a86ea.png)

This picture is my goal. The menu button is to the back. Can I develop a separate menu button instead of going backwards?

**Comment by glouel** [comment]
@baehongjun0212 sorry, this support is dedicated to a Mac application, not the Apple TV. 

With that said, I don't think you can configure that button for what you want, but you should ask on Apple's forum instead : https://discussions.apple.com/community/appletv/appletv_hardware
