### ISSUE TITLE
Controlling Aerial remotely

### ISSUE THREAD

**Issue by jazzbo51** [JohnCoates/Aerial#1165]
I’m currently on vacation and trying to access my iMac remotely using both Parallels Access & Splashtop Desktop from my iPad. I can’t find a way to quit Aerial. Do you have any tips or tricks that might help before next weekend?  Thanks!

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: iMac 27” 2020
- [ ] macOS version: macOS 11.3 beta 5
- [ ] Monitor setup: iMac

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
I'm unfamiliar with both those tools so I'm not sure why you are stuck. In any case, non remotely, you can always exit the screensaver with `Cmd + Opt + Shift + Esc`, so this should work too. 

But ! You may need to use some special shortcut feature from those tools (usually they may have some menu to send special commands so they are not interpreted locally).
