### ISSUE TITLE
Feature Request: Programmable Time Formats

### ISSUE THREAD

**Issue by hnlkaitan** [JohnCoates/Aerial#1166]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 13" (M1)
- [ ] macOS version:  Big Sur 11.2
- [ ] Monitor setup: Built-In + Dell U2913WM (21:9 1080p monitor)

#### Description of issue / Feature request

If possible, would it be possible to let us set the formatting to the one that Apple uses for (at least) the Shortcuts app on iOS? I believe its [UTS 35](https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns), where you put in things like `h:mm` and get single-digit hours if the hour is single-digit or double-digit if the hour is double-digit. Just thought it would be nice since for example, April 4th displays as `April 04` on Aerial, and other similar things.

**Comment by glouel** [comment]
@hnlkaitan 

I'm already using that format, so adding a custom string should be pretty easy to do. Currently this is the format you get if you pick textual (with year) : 

`EEEE, MMMM dd, yyyy`

And the basic format:

`MM/dd/yy`

Interestingly, those gets massaged by the locale, so for example in french locale the first string actually outputs `Dimanche 04 avril 2021` which doesn't look anything like the string above, while with an en_US locale it goes `Sunday, April 04, 2021` (notice how it reorders and actually removes the commas in french locale).  

So yep, I'll think about letting you type your own (my only slight concern is locale interpretation, but I think people who want to mess with dates should be able to understand that). 

I think that only matters for dates and not time though ? Seems pretty superflous there as I already allow with/without seconds...

**Comment by hnlkaitan** [comment]
I had a feeling, and I also should have mentioned this was a very minor thing.

I guess as a bit of context for myself, I'm jailbroken and my status bar looks [like this](https://i.imgur.com/G0e50Qd.jpg) and I have an AOD/heads-up display for my lockscreen that looks [like this](https://i.imgur.com/3D2iANq.jpg). I haven't been jailbroken long enough to see if the `EEEE MMMM d` format works for a very long day (like **Wednesday, September 30**, for example) and might later on change it to something shorter like the `EEE MMM d` format on my status bar, and would've liked to match Ariel to my devices. It's super extra I know 😅

**Comment by glouel** [comment]
Hey @hnlkaitan 

Looks like I had kinda forgot about your issue, I just released a new beta with custom date and clock format, please give it a go and let me know if things are working for you.

Fair warning : because of the locale massaging, what you get may not be the "exact" unicode string you typed. I'm not sure how to handle that I'll have to think about it, Apple's APIs are all about doing stuff "the right way" for locale but this is a bit of an edge case that I'm not sure they are handling.

Again sorry for the lag, I thought I had actually implemented it a while back 🙈

**Comment by glouel** [comment]
Fixed in 3.0
