### ISSUE TITLE
Aerial not operating on macOS 11.2.3

### ISSUE THREAD

**Issue by umpire274** [JohnCoates/Aerial#1167]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (16 inches, 2019)
- [x] macOS version: 11.2.3
- [x] Monitor setup: 16 inches (3072 × 1920)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Hi all. From today I see this message n the screen when I start scrensaver:

"Non puoi usare il salvaschermo Aerial con questa versione di macOS. Contatta il fornitore per ottenere una versione più recente del salvaschermo."
-
"You cannot use the Aerial screensaver with this version of macOS. Contact the vendor to get a newer version of the screensaver."

I can't operate into Aerial settings and then I can't attach the log.

I've delete the Aerial Cache and Aerial plugin and re-install it from scratch, but the result is the same.

Alex.

**Comment by glouel** [comment]
Hey @umpire274,

Did you happen to have installed another screensaver maybe ? That's usually what triggers this bug, assuming you are running a recentish version of Aerial (let's say 2.0+).

It's usually a very easy fix (quoting from the troubleshooting page here : https://aerialscreensaver.github.io/troubleshooting.html") : "You cannot use the Aerial screen saver with this version of macOS." error, or you don't see a preview and the prefererences button is greyed out: Select Aerial, close `System Preferences` with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screen savers in macOS/OS X reported (a long time ago...) to Apple as rdar://25569037."

Let me know if that fixes things for you, if not we'll try something else !

**Comment by ty003** [comment]
Hey! I got the same issue on macOS 11.2.3
<img width="663" alt="Screen Shot 2021-04-16 at 10 43 39" src="https://user-images.githubusercontent.com/82645090/114997868-9cf21980-9ea0-11eb-8fa3-a7f5d6387c7e.png">

Cant open settings and the preview stays black. I have tried completely reinstalling. Worked before 11.2.3

**Comment by glouel** [comment]
@ty003 I'm wondering, did you just update macOS to 11.2.3 or did you do it previously and all of a sudden it stopped working ? Do you remember if you were using 2.2.6 (stable) or the latest beta ? 

I think 11.2.3 was released last month so I'm wondering if the issue is specific to that version of macOS or not, it's a bit of a coincidence that you both have the issue so close to another (unfortunately I'm running 11.3 beta with no issue here, I reverted to 2.2.6 just to be sure too and didn't get the issue).

I would suggest if you can to close System Preferences( the whole thing), then launch Console.app, it will show you the live logs of macOS (you have to press start in the middle). Then launch system preferences and see if you can spot something (like an error, you can filter at the top left). Also you may filter (top right) with "saver" it may narrow down stuff. if you spot errors please let me know. 

Last thing, in the left most column, look for the reports and maybe something with legacyScreenSaver, System Preferences or Aerial in the name. If you see such a thing, paste the log please it may help narrow it down. 

In any case, sorry about the issue, hopefully we can fix that quickly.

**Comment by Pcar17** [comment]
Hello everyone,

I have also installed the latest macOS 11.3 beta and things seem to be working fine on an M1 Mac. I have the current beta versions of both Aerial and Aerial Companion installed (see the screen shot for specifics). 

The Mac journalist community is expecting that this macOS beta will go production very soon as it is working really well (it could be as soon as next week to be timed with the Apple Event?).

<img width="1267" alt="Screen Shot 2021-04-16 at 8 07 56 AM" src="https://user-images.githubusercontent.com/44177062/115030123-5eeafa80-9e8c-11eb-9f20-9e30d756766d.png">

**Comment by ty003** [comment]
Hmm, seems like it is a macOS 11.2.3 issue, perhaps the next update will solve this?

**Comment by glouel** [comment]
> Hmm, seems like it is a macOS 11.2.3 issue, perhaps the next update will solve this?

Check my answer above and let me know.

**Comment by ty003** [comment]
Seems like I got two things on "screensaver" the first one yellow and the second one red:

-[LegacyExtensionManager exceptionHandler:shouldHandleException:mask:] -- Module: (null) threw an uncaught exception: NSRangeException, reason: *** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array.

<NSXPCConnection: 0x6000012f8820> connection to service on pid 2664 created from an endpoint: Exception caught during invocation of reply block to message '___nsx_pingHost:'.

Ignored Exception: *** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
(
	0   CoreFoundation                      0x00007fff2049b6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201d33c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204c3a9a -[NSException raise] + 9
	3   ExceptionHandling                   0x00007fff3c4e8b7c NSExceptionHandlerExceptionRaiser + 140
	4   libobjc.A.dylib                     0x00007fff201d33c9 objc_exception_throw + 48
	5   CoreFoundation                      0x00007fff2054fa9a -[__NSCFString characterAtIndex:].cold.1 + 0
	6   CoreFoundation                      0x00007fff2040ee26 -[__NSArrayM objectAtIndexedSubscript:] + 142
	7   legacyScreenSaver                   0x00000001021e993a legacyScreenSaver + 22842
	8   ScreenSaver                         0x00007fff5625b42d -[ScreenSaverExtension beginRequestWithExtensionContext:] + 246
	9   ExtensionKit                        0x00007fff318caa25 __112-[EXConcreteExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke.126 + 142
	10  CoreFoundation                      0x00007fff2040456c __invoking___ + 140
	11  CoreFoundation                      0x00007fff20404410 -[NSInvocation invoke] + 303
	12  Foundation                          0x00007fff2116ea27 __NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__ + 17
	13  Foundation                          0x00007fff2116c66e -[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:] + 588
	14  Foundation                          0x00007fff2116c0b9 __88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_3 + 205
	15  libxpc.dylib                        0x00007fff2006dab8 _xpc_connection_reply_callout + 36
	16  libxpc.dylib                        0x00007fff2006da40 _xpc_connection_call_reply_async + 69
	17  libdispatch.dylib                   0x00007fff2017e831 _dispatch_client_callout3 + 8
	18  libdispatch.dylib                   0x00007fff20197010 _dispatch_mach_msg_async_reply_invoke + 375
	19  libdispatch.dylib                   0x00007fff201844a7 _dispatch_lane_serial_drain + 263
	20  libdispatch.dylib                   0x00007fff201850fe _dispatch_lane_invoke + 426
	21  libdispatch.dylib                   0x00007fff2018ec5d _dispatch_workloop_worker_thread + 819
	22  libsystem_pthread.dylib             0x00007fff20326499 _pthread_wqthread + 314
	23  libsystem_pthread.dylib             0x00007fff20325467 start_wqthread + 15
)

**Comment by glouel** [comment]
Seems like an issue with legacyScreenSaver maybe, hmm, very weird.

Two questions, one idea: 

- Did you just install 11.2.3 ? As I said above, it was released last month and it's a bit surprising to me that you two were the first one noticing it.
- Do you happen to have Safari Tech Preview installed ? (I've seen some weird issues in the past with Swift libraries and STP). 
- Can you try the latest beta ? It's compiled with the latest SDK, sometimes it helps if it's a Swift library issues : https://github.com/JohnCoates/Aerial/releases/download/v2.2.8beta4/Aerial.saver.zip
(if you are using Aerial Companion, just switch to beta in the menu instead and install from there)

**Comment by ty003** [comment]
> Seems like an issue with legacyScreenSaver maybe, hmm, very weird.
> 
> Two questions, one idea:
> 
> * Did you just install 11.2.3 ? As I said above, it was released last month and it's a bit surprising to me that you two were the first one noticing it.
> * Do you happen to have Safari Tech Preview installed ? (I've seen some weird issues in the past with Swift libraries and STP).
> * Can you try the latest beta ? It's compiled with the latest SDK, sometimes it helps if it's a Swift library issues : https://github.com/JohnCoates/Aerial/releases/download/v2.2.8beta4/Aerial.saver.zip
>   (if you are using Aerial Companion, just switch to beta in the menu instead and install from there)

I have been on 11.2.3 for a while now with this problem. However, I just ignored it in the belief of it just being a server issue or something, did never get resolved, however. I don't have any Safari preview, and trying the beta gives the same issue.

**Comment by glouel** [comment]
Ok thanks and sorry about that, it's a weird one. 

I'll try to have a further look and ask around if other people had a similar issue. I may try and put up a new build too if I find something, I'll let you know.

**Comment by ty003** [comment]
> Ok thanks and sorry about that, it's a weird one.
> 
> I'll try to have a further look and ask around if other people had a similar issue. I may try and put up a new build too if I find something, I'll let you know.

Thank you! I appreciate your help!

**Comment by glouel** [comment]
Sorry for the late reply @ty003, I did ask a couple of friends who were running 11.2.3 and they aren't experiencing the issue, which means it's probably not totally widespread, though that doesn't help understanding why you're having it.

Few ideas/questions:
- You pasted a crash log above, can you tell me which app crashed exactly ? Usually it's `legacyScreenSaver.appex` but I believe in that case, it might have happened somewhere else. You can find more information at the top of the crash report, that would be helpful. I'm trying to narrow it down a bit because it seems the issue is kicking in long before Aerial is even loaded. 
- I'm wondering if you can try running Arabesque, and if it works ? 
![Capture d’écran 2021-04-19 à 13 11 16](https://user-images.githubusercontent.com/37544189/115243465-3fb9ca80-a123-11eb-9a70-53b9b13dcf3c.jpg)
Arabesque is still using the "legacy" screen saver API so I believe it uses the same (or at least a similarly) convoluted loading system as Aerial. 
- One last thing to try, and I'm very much hesitating suggesting it, would be removing the entire content of the containers. This is those folders, you may have multiple of them. Don't delete the containers themselves but their content. Definitely make sure you have a time machine backup before attempting this though, there are symlinks to your desktop etc inside so be super careful. 
<img width="1129" alt="Capture d’écran 2021-04-19 à 15 27 13" src="https://user-images.githubusercontent.com/37544189/115244105-e736fd00-a123-11eb-84df-25e60c6871b4.png">

Again, don't attempt this unless you are confident in your backups (and be super careful if you do that from terminal, in which case the folders have a different name).

**Comment by umpire274** [comment]
> Hey @umpire274,
> 
> Did you happen to have installed another screensaver maybe ? That's usually what triggers this bug, assuming you are running a recentish version of Aerial (let's say 2.0+).
> 
> It's usually a very easy fix (quoting from the troubleshooting page here : https://aerialscreensaver.github.io/troubleshooting.html") : "You cannot use the Aerial screen saver with this version of macOS." error, or you don't see a preview and the prefererences button is greyed out: Select Aerial, close `System Preferences` with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screen savers in macOS/OS X reported (a long time ago...) to Apple as rdar://25569037."
> 
> Let me know if that fixes things for you, if not we'll try something else !

Hi Glouel.

Solved on my side. 

1.  I delete all caches, the plugin and the 'Aerial Companion'

[Uninstallation](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md#uninstallation)

2. Install from scartch Aerial Compenion, install Aerial screen saver using Aerial Companion

[Install latest AerialCompenion](https://github.com/glouel/AerialCompanion/releases/latest)

3. Restart the computer.

After that I can see the screen saver again, and I can update the screensaver options through the 'System Preference'.

**Comment by glouel** [comment]
Thanks Alex for the update, good to hear ! 

For @ty003 I would suggest trying what @umpire274 mentions above. I'd just add that you'll find a more complete version of the uninstallation instructions at the bottom of the page here : https://aerialscreensaver.github.io/installation.html

I'd suggest you try that prior to the container thing I mentioned above.

**Comment by ty003** [comment]
> Thanks Alex for the update, good to hear !
> 
> For @ty003 I would suggest trying what @umpire274 mentions above. I'd just add that you'll find a more complete version of the uninstallation instructions at the bottom of the page here : https://aerialscreensaver.github.io/installation.html
> 
> I'd suggest you try that prior to the container thing I mentioned above.

Hey! Thanks so much for the commitment to help me. I will definitely give this a shot and try ;)

**Comment by ty003** [comment]
Still does not seem to work sadly. Followed the steps from @umpire274

**Comment by glouel** [comment]
@ty003 I've opened a new issue here for you, as it seems to be a different one, check my messages there thanks !

https://github.com/JohnCoates/Aerial/issues/1168

**Comment by glouel** [comment]
@umpire274 if you are still around, can I ask you (roughly) your location ? I think I finally found the issue which seemed to affect people in locations where there was no strict astronomical sunrise/sunset. This is currently the case for example in Scandinavian countries. Version 2.3.2 fixes that (wiping the settings temporarily fixed things for you, but if you try to adapt videos to the time of day, you'd have crashed again).
