### ISSUE TITLE
Issue running Aerial on macOS 11.2.3

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#1168]
Still does not seem to work sadly. Followed the steps from @umpire274

_Originally posted by @ty003 in https://github.com/JohnCoates/Aerial/issues/1167#issuecomment-823168423_

**Comment by glouel** [comment]
I'll repost something I posted yesterday but you may have missed : 

Sorry for the late reply @ty003, I did ask a couple of friends who were running 11.2.3 and they aren't experiencing the issue, which means it's probably not totally widespread, though that doesn't help understanding why you're having it.

Few ideas/questions:
- You pasted a crash log above, can you tell me which app crashed exactly ? Usually it's `legacyScreenSaver.appex` but I believe in that case, it might have happened somewhere else. You can find more information at the top of the crash report, that would be helpful. I'm trying to narrow it down a bit because it seems the issue is kicking in long before Aerial is even loaded. 
- I'm wondering if you can try running Arabesque, and if it works ? 
![Capture d’écran 2021-04-19 à 13 11 16](https://user-images.githubusercontent.com/37544189/115243465-3fb9ca80-a123-11eb-9a70-53b9b13dcf3c.jpg)
Arabesque is still using the "legacy" screen saver API so I believe it uses the same (or at least a similarly) convoluted loading system as Aerial. 
- One last thing to try, and I'm very much hesitating suggesting it, would be removing the entire content of the containers. This is those folders, you may have multiple of them. Don't delete the containers themselves but their content. Definitely make sure you have a time machine backup before attempting this though, there are symlinks to your desktop etc inside so be super careful. 
<img width="1129" alt="Capture d’écran 2021-04-19 à 15 27 13" src="https://user-images.githubusercontent.com/37544189/115244105-e736fd00-a123-11eb-84df-25e60c6871b4.png">

Again, don't attempt this unless you are confident in your backups (and be super careful if you do that from terminal, in which case the folders have a different name).

**Comment by ty003** [comment]
Hey, I have tried the Arabesque screen saver and it works, however, I don't have a lot of experience with the crash log experience, so I have no idea. I think I will just wait it out and see if the next macOS fixes it.
Thank you so much for your help tho!

**Comment by glouel** [comment]
@ty003 no worries, hopefully it may happen late today. But just in case you are curious, here's how to find crash logs : 

![Capture d’écran 2021-04-20 à 13 28 03](https://user-images.githubusercontent.com/37544189/115388849-a6e78580-a1dc-11eb-9d5a-a3c8fa15abec.jpg)

Look in either one of the circled ones on the left then where the arrow points you get the various apps that crashed on your mac. 

In any case, crossing fingers on 11.3 and if you still have an issue I'll guide you more through it.

**Comment by ty003** [comment]
> @ty003 no worries, hopefully it may happen late today. But just in case you are curious, here's how to find crash logs :
> 
> ![Capture d’écran 2021-04-20 à 13 28 03](https://user-images.githubusercontent.com/37544189/115388849-a6e78580-a1dc-11eb-9d5a-a3c8fa15abec.jpg)
> 
> Look in either one of the circled ones on the left then where the arrow points you get the various apps that crashed on your mac.
> 
> In any case, crossing fingers on 11.3 and if you still have an issue I'll guide you more through it.

Thank you very much! I appreciate your time and help :) Will let you know after installing next weeks 11.3

**Comment by glouel** [comment]
@ty003 I got another report, very similar, which also happenned on 11.3. 

If you are familiar with Terminal, can you launch it and then run these commands: 

First, to make a backup of your settings, run those 2 commands : 

```
defaults read ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist > old.txt
```

This will make a readable backup. 

Then :

```
defaults export ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist oldbin.txt
```

This will create a binary backup I can import. 

Then attach those two files to a reply (you can drag and drop them in this reply box, they will be in your home folder (one level above Documents). 

This command will wipe your settings and should make Aerial work again: 

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
```

Opening settings and changing stuff may make it crash again afterwards though, until I figure out the issue. Thanks for your assistance on this.

**Comment by ty003** [comment]
> @ty003 I got another report, very similar, which also happenned on 11.3.
> 
> If you are familiar with Terminal, can you launch it and then run these commands:
> 
> First, to make a backup of your settings, run those 2 commands :
> 
> ```
> defaults read ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist > old.txt
> ```
> 
> This will make a readable backup.
> 
> Then :
> 
> ```
> defaults export ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist oldbin.txt
> ```
> 
> This will create a binary backup I can import.
> 
> Then attach those two files to a reply (you can drag and drop them in this reply box, they will be in your home folder (one level above Documents).
> 
> This command will wipe your settings and should make Aerial work again:
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
> ```
> 
> Opening settings and changing stuff may make it crash again afterwards though, until I figure out the issue. Thanks for your assistance on this.

Hey! Indeed I downloaded macOS 11.3 yesterday and the problems still persisted. However, the terminal commands fixed it! Thank you so much for your support! Finally I get to enjoy this great wallpaper engine again

**Comment by glouel** [comment]
Great to hear it's fixed for you ! Can you send me the two backups so I can investigate ? They hould be in your home directory, called "old.txt" and "oldbin.txt", this will help me find what happenned to you and others. You can drag and drop the files in github to attach them. Thanks !

**Comment by ty003** [comment]
Hey! Seems like I spoke to soon. The fix you provided me with only seemed to give me access to the screensaver settings, where I can tweak the settings for the Aerial Saver, however actually starting the saver does still not work. It also seems like I have to do the fix every now and then to get access to the settings. Seems very unstable. I have tried restarting my computer, but still no luck :(

Nevertheless, I will attach the files below :)

[old.txt](https://github.com/JohnCoates/Aerial/files/6392076/old.txt)
[oldbin.txt](https://github.com/JohnCoates/Aerial/files/6392078/oldbin.txt)

**Comment by glouel** [comment]
Thanks I'll have a look at the settings and try to reproduce. I think that there's probably one setting that if you change it, end up crashing the screensaver, I'll let you know. In the meantime you can unstuck it by:

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
```

and not changing too much/anything in settings.

**Comment by ty003** [comment]
> Thanks I'll have a look at the settings and try to reproduce. I think that there's probably one setting that if you change it, end up crashing the screensaver, I'll let you know. In the meantime you can unstuck it by:
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
> ```
> 
> and not changing too much/anything in settings.

Thanks, however I have to do all of the three-terminal commands to get access to the settings. Otherwise I am presented with this: (cant open settings either"
<img width="656" alt="Screen Shot 2021-04-28 at 15 28 20" src="https://user-images.githubusercontent.com/82645090/116411952-7b951400-a836-11eb-821f-fb17070f26d9.png">

**Comment by ty003** [comment]
<img width="656" alt="Screen Shot 2021-04-28 at 15 51 47" src="https://user-images.githubusercontent.com/82645090/116415439-b6e51200-a839-11eb-9a1d-d05cca3fbe02.png">
<img width="1127" alt="Screen Shot 2021-04-28 at 15 52 04" src="https://user-images.githubusercontent.com/82645090/116415451-b9476c00-a839-11eb-8ba0-27c5168c9d7d.png">

This shows up, but no preview. Also when I start the screensaver the clock from the preview does not show either. Very weird...

**Comment by glouel** [comment]
It may take a few seconds to cache some videos at first, that's probably why you are seeing a black screen. I'll get back to you later today with hopefully a definite fix for the crash, stay tuned and thanks for following up !

**Comment by ty003** [comment]
@glouel Thank you! I appreciate your time and effort to help me solve this.

**Comment by glouel** [comment]
> @glouel Thank you! I appreciate your time and effort to help me solve this.

No problem. I believe I have an issue with some regional settings and weather (probably setting English as primary language with a european locale). If you have a second, can you take a screenshot of your regional settings in macOS's System Preferences ? Something like this : 

![Screen Shot 2021-04-29 at 12 58 43](https://user-images.githubusercontent.com/37544189/116540769-e2740500-a8ea-11eb-8314-8158835c5164.png)

I have another user who has a very similar crash and I'm trying to definitely narrow it down. Avoid configuring weather in the meantime.

**Comment by glouel** [comment]
@ty003 scrap that, I think I finally found the issue. Aerial crashed because there are no astronomical sunrise/sunset this time of year up north. The other user having the issue was in Finland... 

I'll post a fix later today and let you know, sorry again for the issue !

**Comment by glouel** [comment]
@ty003 just posted the fix, which is available here or directly through Companion if you use it : 

https://github.com/JohnCoates/Aerial/releases/tag/v2.3.2

The issue happened with that setting (it's also something you can set during the first time setup) in cases where your coordinates retuned no astronomical sunrise/sunset for that day. 

![Screenshot 2021-04-29 at 14 55 53](https://user-images.githubusercontent.com/37544189/116554591-a8f7c580-a8fb-11eb-88e6-6768a63d34b9.png)

Thanks for your patience with me on this and the files you attached, wouldn't have found the issue without them !

**Comment by ty003** [comment]
> @ty003 just posted the fix, which is available here or directly through Companion if you use it :
> 
> https://github.com/JohnCoates/Aerial/releases/tag/v2.3.2
> 
> The issue happened with that setting (it's also something you can set during the first time setup) in cases where your coordinates retuned no astronomical sunrise/sunset for that day.
> 
> ![Screenshot 2021-04-29 at 14 55 53](https://user-images.githubusercontent.com/37544189/116554591-a8f7c580-a8fb-11eb-88e6-6768a63d34b9.png)
> 
> Thanks for your patience with me on this and the files you attached, wouldn't have found the issue without them !

Oh, yes! That did it! Can verify that everything works as expected now. Could definitely be it had something with us in the north to do indeed. Thank you so much! Really appreciate all of your time and dedication to help me!

**Comment by glouel** [comment]
Thanks for confirming that everything works now ! And thanks for sticking with me while I figured this out :)
