### ISSUE TITLE
Question about the new script feature

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1170]
More of a question than a bug. 

What locations are allowed to place the script for the new feature? I could not find anything mentioned in the feature highlight.

![image](https://user-images.githubusercontent.com/1205471/115827751-96443480-a3c1-11eb-860e-f1e1ba5eb3e1.png)

**Comment by glouel** [comment]
Not in Documents/Desktop/Downloads. I'd recommend `/Users/Shared/` as this is usually super safe.
