### ISSUE TITLE
Uninstall directions ineffective for Big Sur vers. 10.3

### ISSUE THREAD

**Issue by RwatsonEly** [JohnCoates/Aerial#1175]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by RwatsonEly** [comment]
iMac Pro with Big Sur version 10.3 all attempts to uninstall still leave something running as the reason Big Sur can not remove it. Have deleted all references indicated in Library as indicated by uninstall instructions

**Comment by glouel** [comment]
Can you clarify what you think is staying around ?

Uninstall instructions for the screensaver are here : https://aerialscreensaver.github.io/installation.html

As for AerialCompanion, just go to /Applications and put AerialCompanion.app in the trash, that's all there is to it ?

**Comment by RwatsonEly** [comment]
Thanks,

As in cannot be removed.

Attempt to move to trash (in finder) for follow these directions “If you installed using the Companion, or manually, the uninstallation process is straightforward, simply right-click on the Aerial screen saver in System Preferences, and select Delete "Aerial". This will uninstall the screen saver automatically.” Gets an error message that it can’t be removed because it is running.

I’ve removed, per instructions all findings of Aerial per the same instructions. Same error message when trying to remove from finder.

Richard Watson
Lutefisk Technologies, Inc. & ElyMinnesota.com & ElyBuzz.com
***@***.***
***@***.***
***@***.***




From: Guillaume Louel ***@***.***>
Reply-To: JohnCoates/Aerial ***@***.***>
Date: Saturday, May 1, 2021 at 3:49 PM
To: JohnCoates/Aerial ***@***.***>
Cc: Richard Watson ***@***.***>, Author ***@***.***>
Subject: Re: [JohnCoates/Aerial] Uninstall directions ineffective for Big Sur vers. 10.3 (#1175)


Can you clarify what you think is staying around ?

Uninstall instructions for the screensaver are here : https://aerialscreensaver.github.io/installation.html

As for AerialCompanion, just go to /Applications and put AerialCompanion.app in the trash, that's all there is to it ?

**Comment by glouel** [comment]
But what's the name of the file you can't remove ? Is it `Aerial.saver` or `AerialCompanion.app` ? Or something else ? 

In the meantime, two things you can check : 
- Make sure System Preferences is closed. Not just the Desktop & Screen Saver panel, the entire window must be closed. 
- Make sure you don't have AerialCompanion still running in  your menu bar (top right of the screen). If you do, quit it.

**Comment by RwatsonEly** [comment]
*   Thank you, your second step “Make sure you don't have AerialCompanion still running in your menu bar (top right of the screen). If you do, quit it.” Made the difference. Program now removed.
rw


From: Guillaume Louel ***@***.***>
Reply-To: JohnCoates/Aerial ***@***.***>
Date: Sunday, May 2, 2021 at 5:58 AM
To: JohnCoates/Aerial ***@***.***>
Cc: Richard Watson ***@***.***>, Author ***@***.***>
Subject: Re: [JohnCoates/Aerial] Uninstall directions ineffective for Big Sur vers. 10.3 (#1175)


But what's the name of the file you can't remove ? Is it Aerial.saver or AerialCompanion.app ? Or something else ?

In the meantime, two things you can check :

  *   Make sure System Preferences is closed. Not just the Desktop & Screen Saver panel, the entire window must be closed.
  *   Make sure you don't have AerialCompanion still running in your menu bar (top right of the screen). If you do, quit it.
