### ISSUE TITLE
Weather labels misplaced if wind and humidity hidden

### ISSUE THREAD

**Issue by honeywelluser** [JohnCoates/Aerial#1176]
- [iMac (Retina 5K, 27-inch, Late 2014)] Mac model:
- [11.3 (20E232)] macOS version: 
- [27-inch (5120 × 2880)] Monitor setup:
- Aerial 2.3.2

Cosmetic issue in that labels are moved down a line when neither humidity nor wind is enabled:
![IMG_5651](https://user-images.githubusercontent.com/76879734/117533156-2948b580-afe3-11eb-9e2c-b33694b4c308.jpeg)
![IMG_5650](https://user-images.githubusercontent.com/76879734/117533159-2b127900-afe3-11eb-8f9a-6f9c0447ea6a.jpeg)

**Comment by glouel** [comment]
Woops, I thought I had fixed that before release, guess I didn't ! 

Thanks for the heads up this should be fixed in next build later this week.

**Comment by honeywelluser** [comment]
Great! Hope ‘later this week’ comes soon... 😉

**Comment by glouel** [comment]
I guess it's late in the week 🙈 

Issue is fixed but I'm still working on adding current weather to forecasts. Depending on it goes I'll try to push a build with or without it by tomorrow.

**Comment by glouel** [comment]
![Capture d’écran 2021-05-15 à 19 12 19](https://user-images.githubusercontent.com/37544189/118372600-cb076e00-b5b2-11eb-8f79-98b22bcb9901.jpg)

Fixed in 2.3.3.

You also get current weather + the (optional) ability to add the city name.
