### ISSUE TITLE
Homebriew is not updating to 2.3.3

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1177]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini (Late 2012)
- [ ] macOS version: 10.15.7 (19H1030)
- [ ] Monitor setup: 1

#### Description of issue / Feature request
`brew upgrade --cask aerial` is not upgrading to 2.3.3

**Comment by glouel** [comment]
Ha I forgot yesterday. 

Just tried but the old `cask-repair` script no longer works and for some reason the new one is giving me issues right now, this is the command that should fix things but it says it can't create the branch (that I can't find on github) : 

`brew bump-cask-pr aerial --version 2.3.3 --url https://github.com/JohnCoates/Aerial/releases/download/v2.3.3/Aerial.saver.zip --sha256 no_check`

So right now I have no idea how to fix that... still looking !

**Comment by mbierman** [comment]
Hmm I tried and got this. I tried recreating the token and that didn't work either but I am not sure what permissions the token needs. 

```
bigmac:bin michael$ brew bump-cask-pr aerial --version 2.3.3 --url https://github.com/JohnCoates/Aerial/releases/download/v2.3.3/Aerial.saver.zip --sha256 no_check
==> replace /version\s+["']2\.3\.2["']/m with "version \"2.3.3\""
==> replace /https:\/\/github\.com\/JohnCoates\/Aerial\/releases\/download\/v\#\{version\}\/Aerial\.saver\.zip/ with "https://github.com/JohnCoates
==> replace /sha256\s+["']34fdbd5ec7ca087e3bea72c421947f38e43b0f62992caa532157c29b0f3e9ff1["']/m with "sha256 :no_check"
audit for aerial: warning
 - Cask should have a description. Please add a `desc` stanza.

1 file inspected, no offenses detected
Error: Unable to fork: GitHub API Error: You must be logged in to do that.
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Create a GitHub personal access token:
    https://github.com/settings/tokens/new?scopes=gist,public_repo,workflow&description=Homebrew
  echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> /Users/bierman/.bash_profile

!

```

**Comment by glouel** [comment]
Ok so apparently someone beat me to it already, although it doesn't reflect on their repo, I have no idea how that thing works seriously. 

glouel@iMac-de-Guillaume-2:~$ brew info aerial
aerial: 2.3.3

Let me know if it still doesn't work for you, but afaik, it should.

**Comment by mbierman** [comment]
Maybe me? I tried again and I don't know, maybe it worked. Now I'm upgraded. :)  ¯\_(ツ)_/¯

**Comment by glouel** [comment]
Ha great :) 

Sorry about that, I'm still incredibly confused about casks...
