### ISSUE TITLE
Preview/Forced view shows OSX screen saver, not Aerial.

### ISSUE THREAD

**Issue by cfjedimaster** [JohnCoates/Aerial#1178]
#### General troubleshooting tips

Before logging an issue please check that:
- [x ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Macbook Pro 
- [ ] macOS version: 11.3.1
- [ ] Monitor setup:

#### Description of issue / Feature request

When I preview, or force the screensaver with hot corners, I get another built in OSX screen saver, not this one. It could be a lock down setting or some such (this is a work computer), but every other aspect (selecting it, options) seems to work.

**Comment by glouel** [comment]
hey @cfjedimaster 

Just to clarify, do you see a black screen for a few seconds THEN the other screen saver launches, or does it just goes straight to a built in saver (if so which ?). 

Reason I'm asking is that in the event of a crash of a saver, macOS may launch another "safe" built in saver in its place. But it's usually pretty obvious that something was wrong (black screen hanging on for a few seconds etc). 

I would suggest double checking in `Console.app`, see if you have any crash of `legacyScreenSaver`, `ScreenSaverEngine`, or `Aerial`, just to be sure, but this may be your machine being locked down here (I'm unfamiliar with the various locking down mechanisms so unclear how they work).

Here's another suggestion, try this in Terminal (make sure you've selected Aerial first in System Preferences then closed it) : 

```
defaults -currentHost read com.apple.screensaver
```

Let me know what that says. You should see a section like this : 

```
moduleDict =     {
        moduleName = Aerial;
        path = "/Users/you/Library/Screen Savers/Aerial.saver";
        type = 0;
    };
```

System Preferences may not be able to change that files and thus you're not able to change saver, is a possibility.

**Comment by cfjedimaster** [comment]
Nope, don't see a black screen (well I do, but for like one second, if that). Running that check gives me:

```
{
    CleanExit = YES;
    PrefsVersion = 100;
    idleTime = 300;
    moduleDict =     {
        moduleName = Aerial;
        path = "/Users/raycamde/Library/Screen Savers/Aerial.saver";
        type = 0;
    };
    tokenRemovalAction = 0;
}
```

**Comment by glouel** [comment]
Ok so very likely not a crash, though please check `Console.app` as mentioned above. Other think I can think of is, in `Console.app` too, filter with `saver` top right and start monitoring, then launch the saver via a hot corner, and paste the log lines you see. There might be some relevant info there that could explain what's happening to you.

**Comment by cfjedimaster** [comment]
Couldn't find anything. I swear this feels like something related to IT locking stuff down, but locking the screensaver seems like a weird thing. I appreciate your help.

**Comment by glouel** [comment]
No problem, it kinda looks like it. You could double check with another one such as Fliqlo : https://fliqlo.com/screensaver/ and see if you hit the same locking down issue.
