### ISSUE TITLE
Black screen on 5k iMac

### ISSUE THREAD

**Issue by georgeiMac5k** [JohnCoates/Aerial#118]
Hello, thank you for Aerial project, but I have problem on my 5k iMac. When I install and set up the screensaver (and click on the Preview), everything works fine. But when screensaver automatically launches after the set time (1 minute), I can see only black screen, nothing more. I've also downloaded a beta version with offline caching, but results are same. Hope it will be fixed in the future :)

**Comment by heavyboots** [comment]
Same results on my Mac Pro 2009 2.93ghz quad core/ATI Radeon 4870 with 12gb RAM and Mac OS 10.11.1. Also, the Aerial cache only ever shows one movie.

I can preview it, but it only shows a black screen. Works perfectly on my rMBP though.

**Comment by alistairmcmillan** [comment]
Issues likely resolved with the addition of caching in v1.2.
