### ISSUE TITLE
Feature request: add wind speed in m/s for Weather Overlay similarly to ℃/℉ selector

### ISSUE THREAD

**Issue by shpokas** [JohnCoates/Aerial#1180]
#### Feature request

Please consider adding selectable m/s (meters per second) wind speed indicator similarly to ℃/℉ selector in Weatter Overlay. 
[Quoting Wikipedia](https://en.wikipedia.org/wiki/Wind_speed#Units):
Meters per second (m/s) is the SI unit for velocity and the unit recommended by the World Meteorological Organization for reporting wind speeds, and is amongst others used in weather forecasts in the Nordic countries.

Thanks!

**Comment by glouel** [comment]
Hey @shpokas 

I went back and forth on the wind unit that went with celsius, early builds even had m/s but I can't remember why I went to km/h. In any case, since it's used in nordic countries, I'll try to fix that for next build. 

Thanks !

**Comment by glouel** [comment]
Sorry for the delay, but the switch is available in 2.3.4beta1.

**Comment by glouel** [comment]
> Umm, just noticed that when forecast had been configured instead of current weather, then "m/s" in current weather is displayed along with km/h in the forecast.

Can confirm, from a quick look it's just the unit that is wrong, the values are I believe correct. Reopening and will fix for next version, thanks for the heads up!

**Comment by shpokas** [comment]
Really appreciate that super quick fix! Tested with 3.2.6 and all is fine.
Thank you!
