### ISSUE TITLE
Feature request: settings in additional app

### ISSUE THREAD

**Issue by ivabus** [JohnCoates/Aerial#1182]
Please make settings and downloads in additional app, because I can't change anything in settings while downloading.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/71599788/120891004-dfb5af80-c60e-11eb-9456-d9ab63ec3500.png">

**Comment by glouel** [comment]
@BushchikIvan this is a limitation of how Screen Savers work right now. This may change in the future but right now for manual downloads you are limited to this. 

You can though enable automatic downloads and Aerial will download files while the screensaver plays and cache it all.
