### ISSUE TITLE
can u add this ? it looks so nice for Mac Screen Saver

### ISSUE THREAD

**Issue by nonfxck** [JohnCoates/Aerial#1185]
Perfect Balance Circles
The circles will be perfectly synchronized after about 30 m.

The Program is made by Pezzza's Work and all credit goes to him.

His YT Channel: https://www.youtube.com/channel/UCFR-QlAx0qFHN9-QmcrpHnQ/

Pezzza's Work GitHub: https://github.com/johnBuffer/NoCol

wallpaper engine:https://steamcommunity.com/sharedfiles/filedetails/?id=2446231725

it looks so nice . it is perfected mac screen saver

**Comment by glouel** [comment]
@nonfxck 

This does look really good, but I'm not sure that would fit in Aerial, I don't see that looking good on top of a video for example.

It may be a good idea for an alternate, standalone, screensaver though ?

**Comment by nonfxck** [comment]
> @nonfxck
> 
> This does look really good, but I'm not sure that would fit in Aerial, I don't see that looking good on top of a video for example.
> 
> It may be a good idea for an alternate, standalone, screensaver though ?

ya, I don't think it will fit in aerial well too 

but as u say, it is a good standalone screensaver
