### ISSUE TITLE
Custom videos not playing

### ISSUE THREAD

**Issue by chemicalsam** [JohnCoates/Aerial#1193]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- iMac 2017
- Big Sur 11.6
- Dual Monitors

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/7314829/AerialLog.txt)

Custom screensavers will not play. They are located in Shared under Users but still they don't play.

**Comment by glouel** [comment]
Apologies as it looks like I completely missed your issue, really sorry about that. 

You are running Aerial 1.6.0 and that version is not compatible with Big Sur, please update to latest, you can get it here : https://github.com/glouel/AerialCompanion/releases/latest/download/AerialCompanion.dmg

Again, sorry I missed your issue
