### ISSUE TITLE
`Screen Saver Options...` option is greyed out

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#1194]
i tried that (typed ⌘-Q) but it doesnt work. And when i select Aerial, the `Screen Saver Options...` option is greyed out:

![image](https://user-images.githubusercontent.com/1039058/136971747-4355bb76-7318-4de5-88ef-6fc26d3af8e0.png)

_Originally posted by @mnbf9rca in https://github.com/JohnCoates/Aerial/issues/1190#issuecomment-941049034_

**Comment by mnbf9rca** [comment]
i've noticed that i cant select any other screen saver - only flurry!

**Comment by glouel** [comment]
Closing this, feel free to reopen if you have some news from your IT dep as I'd love to be sure it was that.
