### ISSUE TITLE
Error: No Manifest when trying to install plug-in on Big Sur

### ISSUE THREAD

**Issue by wptechnology** [JohnCoates/Aerial#1195]
Hello,

On my MBP Pro 16 (2019), running OSX Big Sur, I've installed Aerial using the DMG then double clicking the application.
On the icon in the menu bar I can see a red dot.
When I drop down the menu, it says : "Screen-Saver : Plug-in not installed! [INSTALL NOW]"
When I click on "INSTALL NOW", I get an error "No Manifest, please report"...
How can I fix that ?
Thanks a lot.

**Comment by glouel** [comment]
closing this, please feel free to reopen if you haven't fixed your issue
