### ISSUE TITLE
Hosting Video Files (not Cache) on External

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1198]
I know I can't move the Cache folder to an external drive due to MacOS limitations. 

But I have many gb of screensaver videos ( at ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial) that I'd love to offload onto external to save disk space. 

Is that forbidden, as well?

**Comment by glouel** [comment]
Hey

So that folder is restricted the same way currently, that’s the cache and other stuff.

But with Monterey that limit is lifted so the latest betas have some support for moving the cache folder, including on an external drive.

Sometime next month there should be full support for moving the whole thing.

**Comment by Jimmbo** [comment]
Wow, great. I could use another 44gb of disk space.

I'm guessing you'll want some testing on that. Will you be posting a notice somewhere?

**Comment by glouel** [comment]
Yep, I've been testing it with the cache only in the betas, and so far it's been working fine. If your drive isn't plugged, Aerial will just revert to the local folder that time, but will still try to reconnect to the drive on subsequent launches. That can leave some extra local files but I think it's a fair compromise. 

This should be in next beta (targetting mid november) so if you follow the beta releases you should be notified there, I also mention those kind of large changes on ko fi here : https://ko-fi.com/glouel/posts

3rd posts has more details about what's currently on the betas.

**Comment by tonywareck** [comment]
Is the external cache working in beta 8 or is it coming in a future beta? I'm on beta 8 and don't see an option to use external cache

**Comment by glouel** [comment]
> Is the external cache working in beta 8 or is it coming in a future beta? I'm on beta 8 and don't see an option to use external cache

Hey @tonywareck 

So it's there in latest builds, but with big caveats and I'm reworking it all for next beta. If you want to try it be aware of a few things: 
- First you can only see the button to change cache location by enabling automatic downloads. You can disable afterwards though, but you need to enable to see the button.

![Capture d’écran 2021-12-30 à 16 24 50](https://user-images.githubusercontent.com/37544189/147765033-41b5569e-3d2c-49f0-807c-a45b886e55ba.jpg)

- It will only change the location of the Cache folder that's inside Aerial's directory, not anything else in that directory (like extra packs of videos if you got some) 
- It won't move videos for you, you'll have to move files manually after changing it


What will change : 
- I'll no longer just move the Cache folder but the entire Aerial's directory (that contains video manifests, logs and video packs on top of the Cache). There were good reasons to separate this prior to Monterey but it's no longer an issue.
- You'll be able to change the location more easily.
- I *may* move stuff automatically too (probably will ask you if you want me to)

Also be aware, this requires Monterey, and will *never* work on Catalina/Big Sur.

**Comment by glouel** [comment]
@tonywareck and @Jimmbo this feature is now there in Aerial 3.0, check here for more details https://ko-fi.com/post/Aerial-3-is-out-G2G2801FZ  or let me know if you are running into an issue
