### ISSUE TITLE
Unable to download videos if previous attempted download failed.

### ISSUE THREAD

**Issue by Bohaska** [JohnCoates/Aerial#1199]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Macbook Pro 2017 
- [x] macOS version: 12.0.1
- [x] Monitor setup: Built-in screen. 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/7561495/AerialLog.txt)

#### Description of issue / Feature request
After trying to download the video "Alaskan Jellies" (number 1), I abruptly sent my laptop to sleep. When I checked the downloads, i found that they were gone, which is normal, but I also found out that I can't download Alaskan Jellies again. The app knows that the video exists, but it is not shown in the list of videos I can download, presumedly because it thinks I already downloaded it.
The logs for the download of the video start at 2021-11-18 16:19:26.001

{{Replace this}}

**Comment by glouel** [comment]
Hey

Aerial doesn't keep a list of videos downloaded, but it checks for files being in your cache at startup to know if you have a file or not. My guess is you may have multiple (according to your logs) 0 bytes videos in your cache.

So go to settings > advanced then click that button : 

<img width="1109" alt="Capture d’écran 2021-11-18 à 02 14 59" src="https://user-images.githubusercontent.com/37544189/142408407-96b513fa-c8dc-4dcd-aab5-b8e0f439a376.png">

It will open a finder window, alongside the log you'll find the `Cache` folder. Look for small/0 bytes files and get rid of them and you should be good to go.

**Comment by Bohaska** [comment]
> Hey
> 
> Aerial doesn't keep a list of videos downloaded, but it checks for files being in your cache at startup to know if you have a file or not. My guess is you may have multiple (according to your logs) 0 bytes videos in your cache.
> 
> So go to settings > advanced then click that button :
> 
> <img alt="Capture d’écran 2021-11-18 à 02 14 59" width="1109" src="https://user-images.githubusercontent.com/37544189/142408407-96b513fa-c8dc-4dcd-aab5-b8e0f439a376.png">
> 
> It will open a finder window, alongside the log you'll find the `Cache` folder. Look for small/0 bytes files and get rid of them and you should be good to go.

Thank you for promptly replying to my message. However, I have checked the cache folder multiple times before posting this bug and I haven't found any 0 bytes videos. I have enabled the option to view hidden files.

**Comment by glouel** [comment]
Hmm so couple of ideas : 

- First, make sure you close System Preferences (the entire window, not just Aerial's settings) and reopen it. It will force System Preferences to reload Aerial (screensavers are a bit weird in macOS) and that may just fix your issue as it will rescan your files and if they aren't there, you'll be able to download again.  
- Second, if that still doesn't work, can you look for this file in cache : `g201_AK_A003_C014_HDR_20191028_HDR_4K_HEVC.mov` (the end of the filename may differ a bit depending on your video format). This would be "Alaskan Jellies 1". The file may not be 0 byte but may be corrupted somehow. 

Let me know of that goes.

**Comment by Bohaska** [comment]
> Hmm so couple of ideas :
> 
> * First, make sure you close System Preferences (the entire window, not just Aerial's settings) and reopen it. It will force System Preferences to reload Aerial (screensavers are a bit weird in macOS) and that may just fix your issue as it will rescan your files and if they aren't there, you'll be able to download again.

Also did that several times before making this bug report, and again just now, didn't work

> * Second, if that still doesn't work, can you look for this file in cache : `g201_AK_A003_C014_HDR_20191028_HDR_4K_HEVC.mov` (the end of the filename may differ a bit depending on your video format). This would be "Alaskan Jellies 1". The file may not be 0 byte but may be corrupted somehow.

There are only 2 videos in the cache, all of them are not corrupt and are not related to the missing Alaskan Jellies

**Comment by glouel** [comment]
How did you configure your cache settings ? Is "Automatically download videos" checked or not ? 

If it is, let's try this : 

<img width="1107" alt="Capture d’écran 2021-11-18 à 13 20 43" src="https://user-images.githubusercontent.com/37544189/142414421-f72b47b6-6c0f-4ad2-83bd-42a2fea024c0.png">

Pick Sea on the left, does Alaskan Jellies 1 show up (may be first or not depending on if you use translations) ? If it's there, press the star, it should start the download. If you already starred that video, un-star then re-star.

If your cache management is on manual, on the same screen, what's shown here ? :

<img width="1098" alt="Capture d’écran 2021-11-18 à 13 22 53" src="https://user-images.githubusercontent.com/37544189/142414858-dbffa0cb-0338-4dcb-8946-184828494d57.png">
 
Files that are downloaded will not have the down arrow in a circle, while files that are will have it.  This should be an accurate view of what Aerial believes it has.

According to your logs there are only 2 files in your cache so I'm not sure I understand what's happening to you here...

**Comment by Bohaska** [comment]
AHH I WAS SOO STUPID.
Sorry for the inconvenience. I only recently found out that I have inadvertently hidden the video.

**Comment by glouel** [comment]
Hehe no problem, glad to hear it's fixed. Take care !

**Comment by Bohaska** [comment]
So the problem isn't that it Aerial was bugged, the problem was that it hid the video too well

**Comment by glouel** [comment]
I'm overhauling the UI now and will try to make hidden videos a bit more prominent. 

But 

>  I was trying to hide another video named Alaskan Jellies on my disk that was exactly the same video but with different quality

This is weird by itself. If a video is in the wrong format (say 1080p instead of 4K), Aerial will delete it at startup or when you change your video format in Advanced. Videos are identified by an ID so you ended up hiding that video yep. 

Hiding I believe does delete the video if it exists.
