### ISSUE TITLE
Duplicate videos need to be culled

### ISSUE THREAD

**Issue by staringispolite** [JohnCoates/Aerial#120]
At least in settings panel, they do. Hard to test which is which in the actual screensaver
http://cl.ly/image/2W002A1W281c
http://cl.ly/image/0o0q1k2m2N2q

**Comment by staringispolite** [comment]
Same with 1 and 6
http://cl.ly/image/3r3O2h0r1n2W
http://cl.ly/image/1y011n0l091r

**Comment by staringispolite** [comment]
Same with London night 2 and 3 
http://cl.ly/image/3Z0J192u2t1e
http://cl.ly/image/1N1V2Z1c3u0f

**Comment by staringispolite** [comment]
NY night 1 and 3
http://cl.ly/image/0K3b0g1g262J
http://cl.ly/image/1R1h2S0N1y0y

**Comment by staringispolite** [comment]
SF night 2 and 6
http://cl.ly/image/3n2P2f3G371Q
http://cl.ly/image/3n2P2f3G371Q

**Comment by JohnCoates** [comment]
Thanks for the heads up @staringispolite 
They're listed twice from the manifest file pulled from Apple themselves. Not sure why, but they have different filenames. I'll have to add a feature that checks for duplicates.

**Comment by QuChao** [comment]
```
ln -sf b1-1.mov b10-1.mov
ln -sf b2-3.mov b10-2.mov
ln -sf b2-4.mov b10-4.mov
ln -sf b2-2.mov b9-1.mov
ln -sf b3-1.mov b9-2.mov
```

We may create some symbolic links to free up some disk space for now.

**Comment by alistairmcmillan** [comment]
@QuChao John added some code back in 2015 (four days after his last comment) that should stop it downloading duplicated files. https://github.com/JohnCoates/Aerial/commit/93cb53ecef150fda7dfa4939244178b02a129d37

You can just delete the duplicates. No need for symbolic links. Aerial shouldn't download them again.

**Comment by alistairmcmillan** [comment]
Closing this issue as it was fixed in his commit back in 2015.

https://github.com/JohnCoates/Aerial/commit/93cb53ecef150fda7dfa4939244178b02a129d37
