### ISSUE TITLE
macOS 12.1 beta -- screen flickers and goes completely white

### ISSUE THREAD

**Issue by apfritts** [JohnCoates/Aerial#1200]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MacBook Pro M1
- [X] macOS version: macOS 12.1 beta 3
- [X] Monitor setup: Built-in display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I am running the beta macOS and realized that the stable version of Aerial was causing screen flickering when turning on and off. I think this eventually leads to the screen going white and becoming unreadable without rebooting. I've updated to Aerial beta and that doesn't seem to fix the problem.

The closest thing I've found to this problem online is here: https://piunikaweb.com/2021/11/18/macos-12-1-beta-3-update-breaks-custom-icc-color-profiles-for-some/

I don't have a custom ICC color profile but the symptoms listed match closely to what I'm experiencing.

*This really seems to be a macOS problem, but figured I'd post it here if anyone else is experiencing it.* I'll try to remember to post updates when new betas come out. I didn't have this problem with 12.1 beta 2.

**Comment by glouel** [comment]
Hey @apfritts

Thanks for the heads up ! FYI, someone reported something very similar on Discord, also with M1 + latest macOS beta, they saw some psychedelic colors at the start of the videos, for a few seconds then it went back to normal.

If I may, could you go to the cache folder (settings  > advanced > show log), check the cache folder inside and try opening the videos with Quicktime ? I believe the issue will be the same and it may be a better way to report that to Apple if so.

My rough guess from what I understand from the other person was that this may be specific to HDR videos.

Anyway, thanks for the report and let me know if you can reproduce in Quicktime !

**Comment by SRayCon** [comment]
I'm getting the flickering, then loss of the white outline around the MacOS cursor. I have a new M1 iMac running Monterey 12.1 beta. Updating to the latest Aerial beta did not fix it. The only fix is to reboot.

**Comment by glouel** [comment]
@SRayCon could you try this 

> could you go to the cache folder (settings > advanced > show log), check the cache folder inside and try opening the videos with Quicktime ? 

So far I've had a few reports that are all linked to the latest beta of macOS Monterey on M1s. There are also some reports of cursor displacement, etc 

HDR (which seems to be badly bugged right now in the beta, but is not without fault on 12.0.1) seems to be the common thread around all of these. 

Right now, every such bug on Aerial was reproduced in Quicktime using the same videos, so hopefully we'll get a new macOS beta tomorrow which fixes most of those.

**Comment by SRayCon** [comment]
I was able to view the first 3 videos I clicked on with no problem. Then, I clicked on the one below, and the screen went haywire.
<img width="988" alt="Screen Shot 2021-11-29 at 1 51 45 PM" src="https://user-images.githubusercontent.com/95199488/143943999-20ff2afe-9ddb-4ab2-a7e8-7c4383fb0e78.png">

**Comment by glouel** [comment]
Thanks a lot for checking @SRayCon ! I would suggest you report the issue to Apple if you can using feedback assistant. I was half expecting a new beta today but alas, nothing yet...

**Comment by apfritts** [comment]
macOS Beta 4 is out! Initial testing shows definite improvements in screen saver performance.

Aerial companion 1.2.2
Aerial 2.3.4beta8

If I don't notice any performance issues this weekend, I'll come back and close this if that works for you @glouel

**Comment by glouel** [comment]
Ha I hoped to get some good news about this ! Thanks a lot for checking in and letting me know !

And yep please do !

**Comment by apfritts** [comment]
It’s fixed! I haven’t seen any other weird behavior in the latest macOS Monterey beta. Thanks!
