### ISSUE TITLE
Flickering screen

### ISSUE THREAD

**Issue by Bumpyshot** [JohnCoates/Aerial#1201]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 13-inch, 2018
- [ ] macOS version: 11.6 Big Sur
- [ ] Monitor setup:Built In

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Hi, I was using aerial screen saver for a long time, this afternoon. i came back to my mac with a big glitch in the aerial screensaver, and a flickering screen when using my computer. I have try to restart my computer and delete aerialscreen but nothing work..

If you have any idea how to fix this issue...

**Comment by glouel** [comment]
Hey there

Which mac and macOS are you running ? Someone reported such an issue with M1 macs and latest macOS beta. 

But can you clarify what you mean by "nothing work" after trying to restart your computer, do you mean the mac itself or Aerial ?

**Comment by Bumpyshot** [comment]
Hey,
Mac model: MacBook Pro 13-inch, 2018 -> Intel chip
macOS version: 11.6 Big Sur -> No macOS beta

When I say nothing work, I mean nothing that I try seems to fix the problem. I'm gonna try to record my screen to show you the problem. It's like a remaining/residual image of the screensaver is constantly flickering with my screen.. it's really annoying. 

For now, the only thing that is working is rebooting on safe mode my mac, and the screen is all right

**Comment by glouel** [comment]
Hey again

So just to clarify, is this correct :
- if you reboot "normally" (not safe mode), you instantly come to the screensaver flickering after login ?
- if you reboot in safe mode there's nothing wrong
- this happens before running the screensaver after a reboot

Just trying to make sure I'm understanding the issue, if you can do a screen recording please do. Thanks and sorry about the issue, that's definitely a bit wild...

**Comment by Bumpyshot** [comment]
This is a video with my phone, i try screen recording but nothing is showing.
https://user-images.githubusercontent.com/68905158/142774789-ba68e5dc-1e03-4776-9465-d3e8e4eea5be.MOV

When I reboot normally I have this flickering on my desktop screen and on some safari tab also.
Safe mode no problem
This happen this afternoon when the screensaver was on, I came back and there was a big glitch on my screen, And when I exited the screensaver mode, there was this flickering.

**Comment by glouel** [comment]
Ok this makes a bit more sense, thanks for taking the time to make the video.

I'm not sure what happened here. Since this doesn't happen on safe mode, it's possibly not hardware related and this is probably a driver going haywire, but it's hard to fully rule hardware out. 

Flickering issues seem a bit common with macOS after making a quick search, a quick example here : https://recoverit.wondershare.com/mac-repair/macbook-pro-screen-flickering.html

Your mac doesn't have switchable graphics it seems, so maybe first try changing the resolution and see if the flickering disappears, reseting NVRAM/SMC may help.

I don't think this is particularly an Aerial issue at this point since it happens post reboot and Aerial is long gone from memory at this point, and really can't do anything to affect your mac that strongly. 

Anyway, let me know if any of those helps.

**Comment by glouel** [comment]
Hey @Bumpyshot I double checked this morning and found this thread which may be related : https://developer.apple.com/forums/thread/654876?page=8

A couple of things I've seen, changing the resolution tends to help (but that's not great), sometimes having some silly animation somewhere fixes it (there's literally some javascript in there to do that...), I'm not sure SMC/NVRAM reset is helpful but it's hard to filter. Most people who have this issue have external monitors though which is not your situation. Anyway, keep me posted, hopefully you've found a fix already.

**Comment by Bumpyshot** [comment]
Hello @glouel , first thank you for your reply ! Changing the resolution didn't fix the issue for me. But resetting the NVRAM seems to fix the problem. This morning I don't have any flickering screen !!

It's really strange that this problem appears at this time, I have been using the screensaver for a year now

**Comment by glouel** [comment]
Glad to hear it's fixed ! 

I think it's probably a general Big Sur issue that just happened to arise when Aerial was running, more than anything else. I will keep an eye on similar reports if any but I think it's likely more something that just randomly happened at that time. Apple moved a lot of things with graphics and rendering with the arrival of the M1 and there are definitely still a lot of rough edges everywhere. Closing your issue but feel free to reopen if something happens.
