### ISSUE TITLE
Feature Request: Addition of new iOS 15.2 Wallpapers.

### ISSUE THREAD

**Issue by tbraun1551** [JohnCoates/Aerial#1203]
If possible, I would like to see the addition of the new iOS 15.2 Wallpapers released this week. If someone can point me to instructions on how to do so, I can download them and take care of future updates to the wallpapers as well.

**Comment by glouel** [comment]
it's already here, check here for instructions on how to get them with the new beta : https://ko-fi.com/post/9-new-videos-available-C0C07GFG2

**Comment by glouel** [comment]
This is now available in 3.0 !
