### ISSUE TITLE
FAQs do not include supported macOS's

### ISSUE THREAD

**Issue by NaniteThunder** [JohnCoates/Aerial#1204]
Please add list of supported macOS's to the FAQ's.

Does Aerial work on Mojave or Monterey? The only info on Pre-Catalina is removing Aerial. 

The latest release does not work on macOS 10.14.6.  It installs. I can customize the appearance. But it never displays the Aerial Screen Saver. 

In order to help us sort your issue, we ask that you provide the following information:
- [2014 MacBook Pro ] Mac model:
- [ 10.14.6] macOS version: 
- [ Main MacBook Pro monitor and 2 external monitors.] Monitor setup:

**Comment by glouel** [comment]
Hey @NaniteThunder 

It definitely should work on 10.14.6, this is not normal, which version are you using of Aerial ? 

This is what I say on GitHub, it may not be on the other site. 10.12 has issues, but 10.14 should be perfectly fine, let me know so I can dig a bit more. 

Compatibility

OS X Sierra (10.12) and above, natively compiled for Apple Silicon

**Comment by NaniteThunder** [comment]
I just downloaded it today in response to a MacRumors.com article today. version 1.2.2. 

Clarification: If I enable a HotCorner, then the Aerial Screen Saver works, but not in automatic mode. I have it set to display the screen saver after 1 minute: to test the appearance of the screen saver. 

https://www.macrumors.com/2021/12/15/apple-tv-screen-savers-on-your-mac/

**Comment by NaniteThunder** [comment]
Also, I want to state that it is an incredibly thoroughly designed interface.

**Comment by NaniteThunder** [comment]
More info: When the screen saver comes on automatically, all three of my monitors are completely black.

**Comment by glouel** [comment]
Ha ok thanks for clarifying and the kind words !

Just to explain, macOS is responsible for starting/stopping the screensaver. So if hot corner works, it should be exactly the same as the "automatic" mode. 

The thing though is that there are two separate settings in macOS that gets easily confused (in french, this is monterey but you should have the same thing). The correct one is on this panel : 

![Capture d’écran 2021-12-15 à 17 28 44](https://user-images.githubusercontent.com/37544189/146225871-53c81e5e-059b-4a04-adb1-88763b9c7d40.jpg)

Make sure you don't confuse that setting with that one in power saving : 

![Capture d’écran 2021-12-15 à 17 34 27](https://user-images.githubusercontent.com/37544189/146226595-1594500d-1909-4314-8a73-73ba34378d49.jpg)

This one will turn your screen black. I guess this is the one you used ?

**Comment by NaniteThunder** [comment]
Sorry, but my settings are correct. 
<img width="671" alt="Aerial issue 1" src="https://user-images.githubusercontent.com/96195206/146228178-52ed8c54-38e1-4305-9125-333b00588d07.png">


<img width="670" alt="Aerial issue 2" src="https://user-images.githubusercontent.com/96195206/146228223-6226e105-9133-4b58-9a32-fce585b54db8.png">

**Comment by NaniteThunder** [comment]
Ok. I just brought up the Force Quit Applications dialog. I selected Finder and then the Relaunch button. 

The automatic Aerial Screen Saver started working. Thanks for spending time looking at this issue. Sorry, that was a just a Finder issue. 

Again, Aerial is an incredible app. I have been using a Mac since 1984 (yes that is correct). Aerial is one of the most complete apps that I have ever used. Congratulations!

I will be buying you a Cup of Coffee.
