### ISSUE TITLE
Screensaver counted as screen time.

### ISSUE THREAD

**Issue by Bohaska** [JohnCoates/Aerial#1207]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Macbook Pro late 2017
- [x] macOS version: 12.0.1
- [x] Monitor setup: Native display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Screensaver is counted as screen time, which can lead to some very odd results
<img width="433" alt="Screen Shot 2022-01-02 at 9 06 46 AM" src="https://user-images.githubusercontent.com/73286691/147863545-b31851fd-b756-44c1-a193-b13b33dde170.png">

**Comment by glouel** [comment]
Hey @Bohaska 

Thanks for the report but sadly this is a macOS bug. Your best hope would be to file a bug report to Apple via "Feedback Assistant".

Some context : 

`com.apple.ScreenSaver.engine.legacyScreenSaver` is an app extension (.appex) that's part of macOS. It's used by both System Preferences and ScreenSaverEngine to launch so called "legacy" screen savers (which are themselves simple plugins, the appex provide some needed memory isolation and some problematic [though less and less] sandboxing on top of it).

"legacy" screen savers includes all 3rd party screen savers and a good portion of 1st party screen savers too. The "new" API for making non legacy screen savers hasn't been released by Apple, and they themselves don't use it in their latest 1st party screen savers. 

Some 1st party screen savers are legacy but have another launcher (iTunessomething.appex) that has extra sandboxing entitlements, and a very minor number are using the "new" API.
