### ISSUE TITLE
Cursor jumps to and is temporarily locked in a corner

### ISSUE THREAD

**Issue by robpneu** [JohnCoates/Aerial#1208]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases - I'm running the newest non-beta and all of the betas don't mention anything that I think would be related to this.
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made. - I could not find anything similar mentioned
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md). - I don't think anything mentioned here relates

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 2021, 14-inch, 8-core (base model)
- [X] macOS version: 12.1
- [X] Monitor setup: I've tried this with only the built-in display, and with a number of combinations of external monitors. The behavior is the same.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/7851391/AerialLog.txt)

#### Description of issue / Feature request

Anytime Aerial is triggered, the mouse cursor is moved automatically to the bottom left corner of the display. When the screen saver exits, either by moving the cursor or by touching the keyboard, the cursor seems to be locked in the bottom left corner of the display for a few seconds (3-5). If you try to move it, it will sometimes move but will jump back to the corner until the 3-5 seconds have passed. This is especially problematic if you have set that corner to be a hot corner to trigger the screensaver; Aerial can  easily and unintentionally be triggered repeatedly.

I have noticed this happening in every circumstances where the screen saver video is triggered
- when manually triggering the screen saver using something like hot corners
- when the screen saver triggers automatically based on the inactivity time set
- when you open the macoS settings pane to the screen saver tab, as soon as the little preview window starts.
- clicking on "Screen Saver Options" from the above pane tiggers it again.

Here is a video clip demonstrating the issue: https://user-images.githubusercontent.com/67300265/149057977-e7511a1f-7715-4427-a4fc-f48299b8bf21.mov

**Comment by glouel** [comment]
Hey @robpneu 

Someone had the exact same issue, I'm trying to remember exact but I believe this was a macOS bug with HDR video playback.

If I remember correctly, they had the same bug when opening a HDR video (from Aerial's cache) in QuickTime. Could you try that and see if you can replicate ? 

I'll try to get back to you later today if I find the other issue. 

Thanks for the report !

**Comment by robpneu** [comment]
Huh, I would not have pinned that on the being an HDR playback issue but you're absolutely correct. Just playing an HDR video from Aerial's cache in Quicktime did the exact same thing. I then changed the video format used by Aerial to "4k HEVC" instead of "4K HDR" and am no longer seeing the cursor jump and get locked in a corner.

**Comment by glouel** [comment]
No problem, thanks for confirming ! I tried looking up the other person that had the issue but couldn't find it, maybe it was someone on discord.

It's one of those "weird" Monterey bug that popped up only on some configurations, which makes it even worse. I thought it was a 12.0 bug though, I'm fairly unhappy to hear it's still there in 12.1 :( 

Thanks for letting me know and yep, in the meantime, HEVC is safer until they fix it !
