### ISSUE TITLE
3.0.0 - when setting Cache size to Unlimited, Get New Videos menu disables itself

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#1209]
- [ ] Mac model: Mac Mini M1
- [ ] macOS version: 12.1
- [ ] Monitor setup: single 4k display 3840 × 2160

I'm not sure if this is somehow intentional, but when adjusting the Cache settings, I found that setting the slider to **Unlimited** causes the _**Get new videos**_ popup menu to become disabled:

![image](https://user-images.githubusercontent.com/1992842/149837515-e4b630a0-c72c-46a1-a338-48182b5fb568.png)

**Comment by glouel** [comment]
That was quick ! Definitely not normal, I'll have a look thanks !

**Comment by markusmiumueller** [comment]
... and on 'Now Playing' screen the app tells "xx.xx GB (your cache is full)" although 'Limit cache size to' is set to "Unlimited"
![image](https://user-images.githubusercontent.com/8100579/150088551-3d08e06f-89b4-42ea-a2d9-de80363b5ca6.png)
Thx. & Regs.

**Comment by glouel** [comment]
> * [ ]  Mac model: Mac Mini M1
> * [ ]  macOS version: 12.1
> * [ ]  Monitor setup: single 4k display 3840 × 2160
> 
> I'm not sure if this is somehow intentional, but when adjusting the Cache settings, I found that setting the slider to **Unlimited** causes the _**Get new videos**_ popup menu to become disabled:
> 
> ![image](https://user-images.githubusercontent.com/1992842/149837515-e4b630a0-c72c-46a1-a338-48182b5fb568.png)

Ok so, it kinda makes sense but because I renamed the label to make it "simpler", it makes zero sense now 🙈

"Get new videos" used to be called something like "Rotate videos", aka, when should Aerial delete some videos from your cache to make space for newer ones. 

So in that sense, if you have an unlimited cache, Aerial will download new videos as needed and will never delete anything. That's why it's disabled. I renamed it because "Rotate videos" was confusing everyone, because I used the word rotation in the other panel (I removed that too).  

I'll think of some better wording !

> ... and on 'Now Playing' screen the app tells "xx.xx GB (your cache is full)" although 'Limit cache size to' is set to "Unlimited"
> ![image](https://user-images.githubusercontent.com/8100579/150088551-3d08e06f-89b4-42ea-a2d9-de80363b5ca6.png)

Fixing that one in next build, thanks for the report !

**Comment by glouel** [comment]
@luckman212 here's what will be in 3.0.2

I've added some extra text and went with "Replace videos". Feedback on this more than welcome, I have a hard time explaining that feature succinctly.

<img width="1133" alt="Capture d’écran 2022-01-21 à 18 51 11" src="https://user-images.githubusercontent.com/37544189/150575958-596c782d-e55b-48eb-9cc5-9532a9a10fb9.png">

**Comment by luckman212** [comment]
Thanks @glouel 

Ah, I understand now. Thank you for the clarification.

I think I would word it like this:

Download videos: (weekly)
_**if**_ your cache is full, older videos will be replaced with newer ones

**Comment by glouel** [comment]
That's the thing, Aerial will always download videos until your cache is full 🙈

Here's how it works exactly : 

If your cache isn't full, if you have videos in your selection that aren't cached yet (let's say you picked Iceland and Scotland), **each time Aerial starts playing a new video**, it starts downloading a new video in the background  from your selection, so it can show it to you later.

If your cache is full, and you have videos in your selection that aren't cached yet, when you launch Aerial it looks for videos downloaded earlier than that period, delete the oldest one and grab a fresh one. 

I tried to make it "seemless" but this is overly complicated to explain 🤣

**Comment by glouel** [comment]
I went with replace + if for now in 3.0.2, to be improved in a future version. The other bug is also fixed, although you may need to move the slider again @markusmiumueller 

Unlimited was "61 GB" for very bad reasons, this should be better now.
