### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by iCandii** [JohnCoates/Aerial#121]
The Check boxes list is missing to select the cities. Below screen grab with my Systems info
![aerialsbug](https://cloud.githubusercontent.com/assets/15606394/10875993/2185c300-8141-11e5-856a-d14d1953f7e5.png)

**Comment by alistairmcmillan** [comment]
Duplicate of #26

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #26
