### ISSUE TITLE
Confusing Version Info

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1211]
Hi, Guillaume,

Prefs>ScreenSaver>Aerial>Info>About says I'm running Aerial v 2.3.4beta8
But the menubar icon for Aerial Companion says "3.0.0 is installed".

(also: I'd like to be running v3, but not sure what else to do. I thought running Aerial Companion would take care of it).

Also confusing: [the support page for Aerial Companion](https://aerialscreensaver.github.io/faq.html#AerialCompanion) says "After installing Aerial Companion, launch Aerial.app from your Applications folder". But in my Applications folder I see only Aerial Companion.

**Comment by glouel** [comment]
You should try closing System Preferences and reopening it. It should reload the correct version hopefully and show 3.0. If it doesn't, a restart usually fixes things though it's inconvenient. macOS sometimes keeps the old version in memory, it's a long standing bug :(

And yep I need to update the support page, I'll try to take care of it this week end, thanks for the heads up !

**Comment by Jimmbo** [comment]
Closing/reopening Prefs worked, thanks.

If you need help rewriting copy - anything that seems hard to clarify - feel free to hit me (I'm not just native English, I'm a professional writer).

**Comment by glouel** [comment]
Great to hear, enjoy v3 ! And thanks for the offer, I definitely will!
