### ISSUE TITLE
Duplication in Video List

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1212]
I'm [seeing two separate panes](http://i.imgur.com/lx3CB5h.png), with different video counts, for apparently the same content ("Countryside Air collection from Magic Window"). Is this ok?

Also, it will feel redundant to most users to have tvOS 15, tvOS 13, **_and_** tvOS 10 present and active. And tvOS 10 is empty and tvOS13 just has one video, so it's not worth the confusion! I'd default to purging the older ones. Less confusion = less support!

**Comment by glouel** [comment]
Those are two different packs actually, if you look carefully, Countryside and Cityscapes.

As for tvOS, I kept those for completion but new users only have tvOS 15 enabled, the older versions are disabled on new installations nowadays. Users upgrading such as yourself may still have the other ones.

**Comment by Jimmbo** [comment]
Very strange. Something in my brain sees both the same. Even after you pointed it out.

I understand that it's not real geeky, but for a consumer-facing app like this, I'd clean out redundancies like previous tvOS bundles even for upgrading users. But I understand why you won't do that (the two people who complain will complain LOUDLY).
