### ISSUE TITLE
medianalysis plist can no longer be deleted in OS X Monterey 

### ISSUE THREAD

**Issue by storkpkp** [JohnCoates/Aerial#1220]
I have the issue described in the troubleshooting section where everything works great for about 5 minutes, but then it freezes up to a slow stutter. 

The file system where the mediaanalysis plist is located is not read only and I cannot find any way to delete that.

**Comment by glouel** [comment]
Hey there

Can you tell me which mac you have, so I can narrow it down a bit ?

**Comment by storkpkp** [comment]
Sorry, yes. I have a mac mini 2012 i7 Quad Core running macOS 12.2 (Using OpenCore Lgacy Patcher) to allow it to install. I ran launchctl unload /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist just now and so far it is running smooth. However, I know I would have to do this every time I reboot. Not sure if anything else would reload that launchagent either.

**Comment by glouel** [comment]
Sadly there's not much you can do, it's just macOS trying to run stuff in the background and I have 0 control over it :(

Your best bet is launching photos once in a while so the import can go through. I believe that fixes things. 

Switching from 4K to 1080p H.264 would probably fix this too but it's not a great solution.

**Comment by glouel** [comment]
For more information, this is a longstanding bug. What you did MAY have fixed it for a while, but no guarantee. Some info here : https://forums.macrumors.com/threads/mac-mini-2014-screensaver-stuttering-mediaanalysisd-process.2267786/

**Comment by storkpkp** [comment]
Well that sucks. I knew it was not your fault. It has been running for 10 minutes or so flawlessly, so we will see and I can report back. 

I am running at 1080p h264.

**Comment by storkpkp** [comment]
Is there a way to run that command automatically on startup?

**Comment by glouel** [comment]
I'm not 100% sure you need to, but I think the easiest way to do it is via automator, see here : https://stackoverflow.com/questions/6442364/running-script-upon-login-mac/6445525#6445525

**Comment by storkpkp** [comment]
Just an update. It has run for several hours after unloading that agent with no issues. So it seems almost a certainty that the service was the issue. I guess we'll see if is starts back up.

**Comment by storkpkp** [comment]
Ok, after running all night it worked perfectly after unloading. I was even able to run them perfectly in 4K HEVC. 

 Of course, as suspected the issue did come back when I rebooted so I did the following. 

- File > New, type Application

- Add a Run Shell Script action, which adds an embedded bash script, and either paste 

launchctl unload /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist 

 
- Save the *.app bundle and add it to the Login Items list in System Preferences > User & Groups > Login Items.
- Select the "Hidden" check box if you don't want to see the app pop up on startup

Note:

This is a per user solution so if you have additional users, you would need to add the app to each user's login items. 
The embedded script runs with the default "C" locale.
$PATH is fixed to /usr/bin:/bin:/usr/sbin:/sbin, which notably does NOT include /usr/local/bin
The working dir. is the current user's home directory.

**Comment by glouel** [comment]
> Ok, after running all night it worked perfectly after unloading. I was even able to run them perfectly in 4K HEVC.
> 
> Of course, as suspected the issue did come back when I rebooted so I did the following.
> 
> * File > New, type Application
> * Add a Run Shell Script action, which adds an embedded bash script, and either paste
> 
> launchctl unload /System/Library/LaunchAgents/com.apple.mediaanalysisd.plist
> 
> * Save the *.app bundle and add it to the Login Items list in System Preferences > User & Groups > Login Items.
> * Select the "Hidden" check box if you don't want to see the app pop up on startup
> 
> Note:
> 
> This is a per user solution so if you have additional users, you would need to add the app to each user's login items. The embedded script runs with the default "C" locale. $PATH is fixed to /usr/bin:/bin:/usr/sbin:/sbin, which notably does NOT include /usr/local/bin The working dir. is the current user's home directory.

Thanks a whole lot for following up, though it's terrible it came back it's great to have a solution. I'll try to put a link tomorrow on the FAQ to this as this may help many people.

Take care!

**Comment by storkpkp** [comment]
No problem. Thanks for pointing me in the right direction. Have a great one!
