### ISSUE TITLE
Fan noise after upgrading to v3

### ISSUE THREAD

**Issue by Coquevas** [JohnCoates/Aerial#1221]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (16-inch, 2019) & MacBook Pro (Retina, 13-inch, Early 2015)
- [x] macOS version: macOS Monterey 12.1
- [x] Monitor setup: Both Macs are connected to external 4K monitors as their only display (lids closed)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Since Aerial updated to v3 a few days ago, I'm experiencing fan noise/high CPU usage every time the screen saver starts. I haven't changed the video preferences and this was not happening before. I'm experiencing this on two different Macs with different video settings: 1080p H264 on the Early 2015 and 4K HDR on the 2019 one.

Things I've tried:
1. Change to one of the default screen savers. No noise when screen saver is running.
2. Play the videos from the Cache folder using Quicktime. No noise and the VTDecoderXPCService process only uses 2-3% of CPU.
3. Disable the video downloading, in case it was an interaction between both actions, still CPU fan noise and downloading videos from settings doesn't impact the CPU/fan either.

**Comment by glouel** [comment]
Hey @Coquevas 

This is likely the retina text support I forced to default on everyone. Please try unchecking this : 

<img width="1142" alt="Capture d’écran 2022-02-02 à 14 23 07" src="https://user-images.githubusercontent.com/37544189/152162154-eaa235cf-0073-456b-8ef4-f2d161047815.png">

I think it will solve the issue, let me know if it does. Video will still be retina, it's the text shadows that make a mess on some Intel machines.

**Comment by Coquevas** [comment]
Thanks, @glouel. That was the problem. I disregarded that setting because I didn't know it was new and defaulted on, but also because I don't consider my 2019 laptop an "older Mac" :)

**Comment by glouel** [comment]
@Coquevas no problem, it's my fault I only meant to enable it on M1 macs only.

It's not so much that your 2019 Mac is old, but there's a bug in recentish macOS with Intel GPUs specifically that make the shadows take a huge amount of processing power. This wasn't an issue before. I hope to find a workaround someday but I definitely made things worse for people in 3.0.2, I'll try to release a new version that disable it by default this week end.

**Comment by glouel** [comment]
Bit of a late answer but this should be fixed in 3.0.4, by default I now "properly" detect M1 macs to avoid that issue.

**Comment by kvenden** [comment]
I've been struggling with this issue, as well and I know it never used to do this. I have a 2020 MacBook Air (Intel) which I'd think ought to be able to play these videos just fine as a screensaver? I play 4K video just fine without cpu fans in QuickTime or Plex or VLC player. I've got the latest up to 3.0.5 of Aerial. I've made sure I don't have the retina text checked. I have tried 4K HDR, 4K HEVC, 1080P HDR, 1080P HEVC. All produce the same results which seems puzzling as 4K should be more intense than 1080p I'd think. I removed the clock and location overlays. I've made sure all videos being played are fully downloaded/cached. Screensaver starts out quiet but then the fans kick in and get so loud and then slowly ramp down after I have unlocked my computer. I've even disabled Time Machine. Closed some of my apps. Nothing else seems to make my fans do this other than say Final Cut Pro when rendering a video. There's got to be something else that can fix this. Please, if anyone has any other ideas? I want to play these gorgeous screensavers and the ones I bought from Josh so bad, but keep going back to stock screensavers just to avoid the obnoxious noise here in our living room. Happy to provide any other info I can. Would just love to get this working better without the loud fans going crazy.
