### ISSUE TITLE
3.0.4 not loading on 10.14.6

### ISSUE THREAD

**Issue by brian163** [JohnCoates/Aerial#1222]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x ] Mac model: Mac Pro 2012
- [x ] macOS version: 10.14.6
- [x ] Monitor setup: Single display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

After upgrading to 3.0.4 it no longer loads. Clicking on Aerial in the screen saver tab of the control panel resulting in a blank window. I have to quit the System Preferences and re-load to get back to the list. I can't follow the instructions above to enable debug mode since nothing loads. 

Reverting to 3.0.2 resolves it.

I made a quick video:

https://user-images.githubusercontent.com/160223/152721169-e6590baf-624f-4725-9ac6-2e41a1ef3d08.mp4

**Comment by glouel** [comment]
Hey @brian163 

Hmm, this is definitely weird. Any chance you can try Console.app and look for a crash report ? I see you are running 10.14, it's possible the latest Xcode broke something on that OS. Or maybe it's my mac M1 detection that doesn't run here and somehow crashes older macOSes (that'a basically all that's new on top of the stuff for Companion).

Let me know if you need help looking for crash reports in Console.app, I'll try to double check some stuff here in the meantime.

**Comment by mvorl** [comment]
Having the same issue, here's the crash report from my system
[ScreenSaverEngine_2022-02-07-135229_Martin-Vorlanders-MacBook.crash.txt](https://github.com/JohnCoates/Aerial/files/8015547/ScreenSaverEngine_2022-02-07-135229_Martin-Vorlanders-MacBook.crash.txt)
.

**Comment by glouel** [comment]
Thanks for the crash log, it looks like this may be something with Xcode 13.3 beta that broke the build, I'll try to make a build with 13.2 asap to verify this.

**Comment by glouel** [comment]
@mvorl & @brian163 if you have a second can you try this build ? Please quit companion first, & close system preferences before installing. 

https://github.com/glouel/Aerial/releases/download/v3.0.5test1/Aerial.saver.zip

I don't have high hopes on this one, but just in case, thanks.

**Comment by glouel** [comment]
And this version, hopefully, will work, lot more confident, please let me know : 
https://github.com/glouel/Aerial/archive/refs/tags/v3.0.5test2.zip

**Comment by glouel** [comment]
@mvorl @brian163 I got confirmation that the second build works, so I released it to everyone as 3.0.5. 

Thanks for the report and take care !

**Comment by brian163** [comment]
Sorry, first chance I was back at my computer to check in on this today. I've downloaded 3.0.5 and all is well. Thanks for the quick turnaround!

Brian

**Comment by glouel** [comment]
@brian163 no prob, thanks for the initial report and for the confirmation !

**Comment by mvorl** [comment]
Yes, same with me as with @brian163 . Just returned to may office desk and a new and working Aerial is there to  install. Thanks a lot for the quick fix! I wouldn't want to miss these beatiful screen saver movies.
