### ISSUE TITLE
Message Overlay with shell script - does not always show up immediately

### ISSUE THREAD

**Issue by f-laurens** [JohnCoates/Aerial#1226]
#### Required information
- [x] Mac model: MacBook Pro (16", 2021) M1 Max
- [x] macOS version: Monterey 12.2
- [x] Monitor setup: Built-in display
- [x] Aerial version: 3.0.5
#### Description of issue
I use **Message** overlay with **Shell script** message type.
The shell script used is `/bin/hostname` (which should never fail and always return a value).

The observed behaviour is that the message does not always (this is non deterministic) show up immediately when the screen saver is started.
When message does not show at startup, it seems one has to wait for the **Refresh every** delay for it to show up.
A workaround is therefore to set the **Refresh every** delay to a low (10 or 30 seconds) value to force the message to show up 
(which is a bit of a hack for a shell script that always returns same value).

Is there a reason for the message not to show up immediately when screen saver is started, or is this a bug?

**Comment by glouel** [comment]
Hey @f-laurens 

This definitely looks like a bug, I'll try to have a look over the week end and let you know, thanks for the report.

**Comment by glouel** [comment]
- The test button should give feedback but maybe that's broken, I'll have a look
- Arguments are not supported, but since you can point to a script, you can put  your arguments in there

**Comment by glouel** [comment]
Hey @f-laurens 

Sorry for the late reply, I had a quick look so here are some thoughts. 

- First, regarding the Test button, the result may be hidden, I have a UI issue right now where stuff may be hidden with no way to scroll, this applies to the Test button : 

<img width="1205" alt="Capture d’écran 2022-02-14 à 13 21 05" src="https://user-images.githubusercontent.com/37544189/153863664-f41ca12b-ce8c-4b61-b428-38d2aebc1a2a.png">

If you enlarge the window a bit, (you may need to switch to another overlay and then back to Messages) you should be able to see the result of the Test happening. 

The test button is synchronous (unlike when ran in the screensaver) so here that test script will wait for 2 sec before giving me stuff. 

- Second, message not always showing immediately, I can confirm I replicated the issue, looking into it right now and will keep you posted, I may have a new build tonight or tomorrow.

**Comment by glouel** [comment]
Yes it's at the bottom, per my screenshot above, did you switch to another overlay after resizing and back ? Just resizing won't do. 

I tried here and the Test button works with `/bin/hostname`.

**Comment by glouel** [comment]
@f-laurens yeah sorry, I'm looking at fixing that UI bug today too, I've been having weird issues with Xcode on stuff that worked perfectly well before.

Anyway, the original bug is fixed for next build (predictably, I didn't update the overlay on the main thread which lead to what you experienced).

Hopefully I'll put out a fixed build tonight or tomorrow as I have other bugs to tacle (including the UI thing). Thanks for the detailed report !

**Comment by glouel** [comment]
@f-laurens 3.0.6 includes fixes for your issues, including the scrolling/test thing.

**Comment by f-laurens** [comment]
Indeed. All is fine now.
Thanks.
