### ISSUE TITLE
Aerial Companion menu English typo

### ISSUE THREAD

**Issue by nicacy** [JohnCoates/Aerial#1230]
The Aerial Companion 1.4.0beta1 menu states _Screen Saver settings are independant of..._. The word _independent_ contains no letter 'a' in English.

<img width="426" alt="Screenshot 2022-02-27 at 12 06 50" src="https://user-images.githubusercontent.com/37441096/155878286-c30a2dae-3615-4914-ab5e-e75b80f2d58c.png">

**Comment by glouel** [comment]
@nicacy thanks for the report, I always mess that word in english ! This is fixed for next beta which hopefully will be out the coming week.
