### ISSUE TITLE
How can I strictly forbid the download of those videos I don't like?

### ISSUE THREAD

**Issue by sgricky** [JohnCoates/Aerial#1231]
- [ ] Mac model: MacBook Pro 2019
- [ ] macOS version: 12.2.1 (21D62)
- [ ] Aerial version: 3.0.6

Hi,
In order to control the capacity, I want to stop downloading those videos I don't like, but so far I can't find where this function is.
Please advised.

**Comment by glouel** [comment]
Aerial will only download what is selected in "Now Playing". If you select locations on top and then only pick Dubai and New York, only those videos will get downloaded.

If you want to block an individual video from within a location, click the arrow top right, then in the list, press the hide button on those you don't like.

**Comment by glouel** [comment]
CLosing, feel free to repoen if you need more assistance
