### ISSUE TITLE
Aerial Companion issue

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1236]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini (M1, 2020)
- [ ] macOS version: 12.3 (21E230)
- [ ] Monitor setup: one monitor

#### Description of issue / Feature request

1. Installed Aerial Companion. 
2. Asked for betas. 
3. Chose Install now. 
4. No matter what it says **Install Now**. 

![image](https://user-images.githubusercontent.com/1205471/161009046-e498a431-9540-4bb6-98f2-ad6fd9cdec9f.png)

**Comment by glouel** [comment]
What happens when you press the Install now badge, you don' get an error ? Try restarting Companion possibly, and if not make sure the log is enabled and send it, it's in ~/Library/Application Support/AerialUpdater/

**Comment by mbierman** [comment]
It downloaded something and went back to Install beta1 now. 
[Aerial.saver.zip](https://github.com/JohnCoates/Aerial/files/8391702/Aerial.saver.zip)

**Comment by glouel** [comment]
Not sure I understand ?

**Comment by mbierman** [comment]
I had beta1 installed. yet it said to Install beta1 now. o.k. I run that. It still says to install beta1 now. It doesn't seem to know that it is already installed.

**Comment by mbierman** [comment]
B2 is now out but the updater doesn't see it. 
![image](https://user-images.githubusercontent.com/1205471/161307412-f3b3b667-e14a-4e82-a01c-b61d78e5ea2f.png)

**Comment by glouel** [comment]
Try to restart companion it should work now. I was fixing things in the background.

**Comment by mbierman** [comment]
I manually told Companion to check for updates and it found it. So that issue is solved! Thanks. I will leave it run for a while to see if b2 addresses the freezing issue. 🙏🏻

**Comment by glouel** [comment]
b2 is the same as b1 so there should be no improvement. If you can though, next time it hangs, note the time and send me your log, I'd like to reinvestigate this as I think there may be two separate issues and the logs I have don't seem to correspond to what people describe. Also an exact description of what's stuck (usually it's video looks paused and clock is stuck). Thanks !
