### ISSUE TITLE
Computer not sleeping after installing Aerial

### ISSUE THREAD

**Issue by thevoyager3** [JohnCoates/Aerial#1237]
Since installing Aerial the Mac can't go to sleep. Even pressing Apple > Sleep does not work. The screen goes dark and then wakes up again immediately. Have uninstalled and reinstalled the latest beta and the problem persists. Any idea? I have not installed other apps in the meantime.

**Comment by glouel** [comment]
Hey @thevoyager3 

Is this a M1 mac ? There are many issues with sleep and macOS in general that aren't linked to Aerial, this may be related. The screen waking up again is weird but I've seen here my external screen waking up periodically under sleep. 

Can you give more details about your setup and macOS versions  ? In any case, when you press Apple > Sleep, Aerial isn't involved at all.

Thanks

**Comment by thevoyager3** [comment]
Hi @glouel, thanks for the quick reply. Yeah, I agree that it may not be due to Aerial, just odd given the timing. Yes, it is an M1 Mac mini running the latest OS. maybe I need a reinstall as the issue seems to happen even in safe mode.

**Comment by Pcar17** [comment]
@glouel & @thevoyager3,

Not sure if this is related, but I am finding that if I have Universal Control enabled with another device that my corner screen settings on one side of my Mac (that I use to sleep the display) don't work and the cursor just ends up on my iPad (which I use as another device in Universal Control). And any use of my iPad wakes up my Mac or prevents it from going to sleep.

**Comment by Pcar17** [comment]
@glouel & @thevoyager3,

Not sure if this is related, but I am finding that if I have Universal Control enabled with another device that my corner screen settings on one side of my Mac (that I use to sleep the display) don't work and the cursor just ends up on my iPad (which I use as another device in Universal Control). And any use of my iPad wakes up my Mac or prevents it from going to sleep.

**Comment by thevoyager3** [comment]
Mmmm, that’s interesting, specially given the time this feature came out, and that for some reason doesn’t really work well for me anyway, let me check and make sure it’s disabled. Thanks.

**Comment by glouel** [comment]
I replied in the wrong thread while looking up stuff, see here : https://github.com/JohnCoates/Aerial/issues/1225#issuecomment-1094080023

**Comment by thevoyager3** [comment]
Disabling universal control did it. Bingo!

**Comment by Pcar17** [comment]
> Disabling universal control did it. Bingo!

Great news!
