### ISSUE TITLE
Stuck in System Preferences

### ISSUE THREAD

**Issue by Hukeqing** [JohnCoates/Aerial#1238]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 2020
- [x] macOS version: 12.3.1
- [x] Monitor setup: Built-in retina display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

I wanna to but I can't

#### Description of issue / Feature request

I just install the latest version from Homebrew, then I open the System Preferences to setting the aerial, and then, stuck

![stuck](https://user-images.githubusercontent.com/47495915/163150469-ef818365-9b63-4a25-87f6-50a42032648b.png)

At the same time, the CPU and memory went up like crazy, I tried to wait about 30 minutes until my memory was completely full

I tried restarting the computer etc.

**Comment by Hukeqing** [comment]
even I kill the process, the CPU and memory didn't stop increasing

**Comment by Hukeqing** [comment]
I successfully solved this problem
I found all Aerial files in ~ directory and deleted them

**Comment by glouel** [comment]
@Hukeqing sorry about that, for some reason the preferences sometimes get stuck, I had a couple of reports on discord about it but haven't been able to figure out yet the root issue :(

In any case if this happens again (or to someone else), open a terminal and paste this : 

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
```

This will reset your settings properly (on 10.15+), restart System Preferences and it will be good to go. If you manually delete the file, because of defaults caching, you'll need to restart your mac for it to work usually.

**Comment by Hukeqing** [comment]
> @Hukeqing sorry about that, for some reason the preferences sometimes get stuck, I had a couple of reports on discord about it but haven't been able to figure out yet the root issue :(
> 
> In any case if this happens again (or to someone else), open a terminal and paste this :
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
> ```
> 
> This will reset your settings properly (on 10.15+), restart System Preferences and it will be good to go. If you manually delete the file, because of defaults caching, you'll need to restart your mac for it to work usually.

maybe you can try to DESELECT "From Joshua Michaels & Hal Bergman", that means you deselect all in the following image

![](https://user-images.githubusercontent.com/47495915/163180047-1ed3989c-b326-47eb-a8c2-c0aa317ae86d.png)

then you may meet the stuck. And then, you can restart System Preferences to see the scene in my screenshot

because I reach the stuck again :-(

**Comment by glouel** [comment]
Oh that would make sense. in that case there would be no video source at all so I can understand the crash. 

Thanks a lot I'll dig into it tonight or tomorrow !
