### ISSUE TITLE
Stuttering with Monterey 12.3

### ISSUE THREAD

**Issue by lankox** [JohnCoates/Aerial#1239]
Before updating to Monterey 12.3, Aerial was buttery smooth on my Mac.  Now, the videos have a slight stuttering.  My setup is a 14" MBP M1 Max (24 core GPU) connected to a 5k LG Ultrafine monitor.  I have the screensaver displayed on both the external monitor and laptop screen.

**Comment by glouel** [comment]
Hi @lankox 

I'm running the betas right now so I haven't seen it personnally, but it wouldn't surprise me there's a specific bug with video decoding in 12.3.

Are you using HDR ? Usually this is the shakiest part of macOS video decoding and in Monterey in general it's been bad.

There's 0 reason it should lag on a M1 Max in any case so I think it's likely something they'll fix in 12.4.

**Comment by glouel** [comment]
@lankox are you still experiencing the issue ? I believe this was fixed in a subsequent Monterey build

**Comment by lankox** [comment]
Not sure.  I switched the video format to 4k HEVC from 4k HDR and that immediately solved the problem.  

On Aug 16, 2022, at 10:29 AM, Guillaume Louel ***@***.***> wrote:


@lankox <https://github.com/lankox> are you still experiencing the issue ? I believe this was fixed in a subsequent Monterey build

**Comment by glouel** [comment]
Thanks for taking the time to answer. I'm 99% sure this is fixed if you want to switch. It's definitely fixed in the Ventura betas I'm using right now. Take care !
