### ISSUE TITLE
won't auto start ? 

### ISSUE THREAD

**Issue by walkermurch** [JohnCoates/Aerial#124]
First - i appreciate the work you did thank you. When i hit PREVIEW its perfect...but doesnt last - when i set it to load in 1 min or any time...it never starts? 

Mac Pro 10.10.5   - On your beta 

Thanks again.

Art Bell

**Comment by IronCraftMan** [comment]
Do your other screen savers work fine? I'd recommend updating to OS X 10.11.

**Comment by walkermurch** [comment]
Yes - the others start…we can’t go up  - we are filmmakers and deadly bugs between Adobe and 10.11….maybe in a few months

Thanks,
