### ISSUE TITLE
Screensaver starts - plays one video and then stops

### ISSUE THREAD

**Issue by carolinecasella** [JohnCoates/Aerial#1240]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Macbook Pro (14 inch, 2021)
- [ ] macOS version: macOS Monterey version 12.2.1
- [ ] Monitor setup: Laptop

#### Description of issue / Feature request

Hi,
The screensaver works for the first video, and then it turns black and no more videos come back on. All the videos are downloaded and in my favorites (there are 64 in my favorites). I cannot figure out why it will not continue to play after the first 10 seconds. 

Thank you for your help!

**Comment by glouel** [comment]
Hi @carolinecasella 

So first thing to check would be your sleep settings in macOS, they are a bit weird, in battery you have this slider : 
 
<img width="893" alt="Capture d’écran 2022-04-22 à 15 20 36" src="https://user-images.githubusercontent.com/37544189/164722427-28c82b8e-b909-4fbd-b5b9-4453a7348463.png">

This decides when your screen/computer goes to sleep completely. This has to be higher than the time you set your screensaver to start. 

<img width="893" alt="Capture d’écran 2022-04-22 à 15 22 00" src="https://user-images.githubusercontent.com/37544189/164722684-f45cbf96-08d2-4bf2-a825-6733ef1cd55b.png">

If you have them set for the same duration, macOS will start your screensaver for a few seconds and then kill it. 

Can you check those settings first ? If you still have an issue, the log would be helpful to try and sort it out (go into advanced, scroll down a bit, there's a show log button and drop it here).

**Comment by glouel** [comment]
@carolinecasella Closing this as I didn't get a response, but please feel free to post again/reopen if you need more assistance.
