### ISSUE TITLE
Please allow to set the directory for videos

### ISSUE THREAD

**Issue by fbc** [JohnCoates/Aerial#1243]
I have a small MACOS boot disk(256gb) in my MAC MINI, but a large 2 TB SSD for data and my profile.

I don't want to fill my boot disk up with 4k video. How can I tell it where to put the video?

**Comment by fbc** [comment]
oops disregard, I just updated to the most recent version and saw the cache dir setting.. thanks.

**Comment by glouel** [comment]
Assuming you are running Monterey, you can, just use this button, a Aerial folder will be created wherever you select :
 
![Capture d’écran 2022-04-26 à 17 08 02](https://user-images.githubusercontent.com/37544189/165332421-e3c609a5-290a-4c8a-80dd-e676681c4b0e.jpeg)

**Comment by fbc** [comment]
> Assuming you are running Monterey, you can, just use this button, a Aerial folder will be created wherever you select :
> 
> ![Capture d’écran 2022-04-26 à 17 08 02](https://user-images.githubusercontent.com/37544189/165332421-e3c609a5-290a-4c8a-80dd-e676681c4b0e.jpeg)

Ahh thanks for your reply! I found it after upgrading to the latest. Thanks.
