### ISSUE TITLE
no love for windows users?

### ISSUE THREAD

**Issue by smoothnobody** [JohnCoates/Aerial#1244]
i know this can be converted for use on windows cause i have that version. but it has not been updated for a few years now. i see this version was updated a few days ago and seems to get alot more attention. would be awesome if we could get this version working on windows.

**Comment by glouel** [comment]
Hey @smoothnobody 

Sorry but I just take care of the macOS version. The Windows version, while sharing the name, shares pretty much nothing code wise as 99% of Aerial's code is platform specific.
