### ISSUE TITLE
Feature Request: System Mute on screensaver activating

### ISSUE THREAD

**Issue by itsrdm** [JohnCoates/Aerial#1245]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
 - #971 - Describes a new feature to 'mute videos' that are playing as a screensaver.  
 - I did not find any other feature requests that would apply.

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MacBook Pro M1 2020 & Mac Mini M1
- [X] macOS version: macOS Monterey (v. 12.3.1)
- [X] Monitor setup: Dual display. HDMI. (on both setups)

#### Feature Request: Enable system mute on screensaver activation

As an end-user, I would find it useful if the screensaver had the option to mute the system when the screensaver activates & unmute it when I return to my computer (the screensaver stops).

I would find it also useful if there was a sub-option for an "Apple Music" exclusion.
 
**Intent**: 
- My goal is to stop the iMessage dings and other synced notifications around my world.  For example, if I get a text message, it has the opportunity to ring out on my iPhone, iPad, MacBook Pro, and Mini.  
  - If my MacBook Pro or Mini is idle/screensaver active: I find the duplicate notifications distracting.  Personally, I'd just like to mute the entire machine while it is activated.
 - However, I could see for the larger user base, it may be even more useful if a sub-option would be included to allow an exclusion.  (Not sure if a 'mute exclusion' is possible, but I could see being useful).

**Comment by glouel** [comment]
Hey @itsrdm 

Sorry for the late reply. So I believe I already had a look but couldn't find an API to disable notifications altogether in macOS, as this is handled solely by the system. 

I haven't looked at the new stuff in Monterey regarding this, but if there's an API, it may make things worse as the closest thing I could (maybe) do is set do not disturb prior to launching the screensaver. But since that's now a shared state between your devices, that's definitely not a solution to this issue.

I'm afraid it's the kind of issue that you should probably relay to Apple via feedback assistant, as I don't think I can control this sadly. 

Now, if what you want is just muting the *sound* of those notifications, there may be a way, although I would need to check if I have the proper entitlements to do so (screensavers are limited).

**Comment by itsrdm** [comment]
Hello @glouel ! Thanks for the response.

I did not consider Apple's restrictions when making my request. Therefore, I can also send a feature request to them.

Following your train of thought, for my use case, triggering Do Not Disturb or invoking any of the newly added Focus profiles would not work for me, but perhaps it might work for others.  Since Focus is a shared status across all my devices, it would mean that my phone would go into Do Not Disturb (or some other set Focus status) on all of my devices when the screen saver kicks on.

But yes, just muting the notification sounds is what I would want.  No worries if this can't be accomplished, I know Apple has some fairly strict rules on what you can and can't do.

Appreciate your time!

Cheers,

-rdm

**Comment by glouel** [comment]
@itsrdm been a while but I finally added a global system mute when the screen saver is playing. Please test it in 3.1.0beta4 and let me know if that works for you, the setting is off by default, you can find it in Advanced, see below : 

<img width="1144" alt="Capture d’écran 2022-08-16 à 18 18 11" src="https://user-images.githubusercontent.com/37544189/184938761-5c12e476-6bed-4409-978a-2c32cab5de45.png">

**Comment by itsrdm** [comment]
Thank you!  I'll update this in a day or so.  I start my work week tomorrow (Friday) so, I'll be able to test this.  Thanks for your quick actions!! 

~rdm

**Comment by itsrdm** [comment]
Not even a full day of testing, but, it is exactly what I was looking for and is working as expected.  Now when one or both of my macs are in screensaver... I don't hear the notification across two idle computers and my phone/watch/iPad.  Thanks a ton!
