### ISSUE TITLE
Aerial stopped working / not compatible with this MacOS Version

### ISSUE THREAD

**Issue by 21Kingshill** [JohnCoates/Aerial#1251]
Hi,

I couldn't find a similar issue so far. I use aerial since it's very first release. Yesterday I noticed for the first time a black screen instead the screensaver. A moving text tells me, that this Aerial Screensaver is not compatible with this MacOS Version and the vendor should be asked for an updated version.

- [ ] Mac model: MacBook Pro 14" / M1
- [ ] macOS version: Monterey 12.4
- [ ] Monitor setup: Dell 4k

#### Description of issue / Feature request
- I haven't done any system update nor new software installation recently
- problem occurred "suddenly" for me
- I have uninstalled all parts of aerial and tried new installation of the companion and also the screensaver only. Always the same result.

Does anyone has the same issue or even better a solution?

Thanks,
21Kingshill

**Comment by glouel** [comment]
Hey there @21Kingshill 

Did you try restarting your Mac ? I think sometimes the `legacyScreenSaver.appex` (the thing from Apple that runs screensaver) just gets stuck. 

So first let me know if restarting helps

Second, do you see this in the full screen screensaver and in settings too ? 

Let me know, hopefully it either fixes or narrows it down a bit

**Comment by 21Kingshill** [comment]
It really helped to restart.

Sorry for such a stupid request and thanks for the quick help.....

**Comment by glouel** [comment]
Glad to hear it worked, and sorry that I have to resort to suggest *that* nowadays on macOS :(
