### ISSUE TITLE
Show hidden videos

### ISSUE THREAD

**Issue by AndreBrinkop** [JohnCoates/Aerial#1255]
#### Hidden videos can not be displayed again

I just freshly installed and configured Aerial. While selecting which videos I would like to include into the rotation I accidentally hid some of the videos. I am not sure if I was just too stupid but I could not find any way to unhide those videos again. Is there a feature to do so? And if yes, maybe it is not placed prominent enough. I would suggest that clicking the "X videos hidden" message will send you to a view that allows re-enabling of those videos.

Thank you very much for your great work!

**Comment by glouel** [comment]
No worries @AndreBrinkop thanks for reporting the issue. I'll have a look if I can fix that one quickly, I'll keep it open as a reminder.

**Comment by glouel** [comment]
Closing this, the bottom thing is now a button in 3.1.0beta4, thanks again @AndreBrinkop
