### ISSUE TITLE
Bug Report: 3.1.0 Advanced Display Offsets misbehave after upgrade to Mac OS Monterey 12.5.1

### ISSUE THREAD

**Issue by ravedon** [JohnCoates/Aerial#1260]
#### Required information

Mac Studio 2022 running macOS Monterey 12.5.1

Primary display is an LG38L950G, 3840x1600
Secondary display is an Apple Studio Display, in 1440x2560 aspect using SwitchResX 4.12.0 since current Firmware Version 15.5 (Build 19F80) doesn't support vertical display rotation natively. This is a known Apple issue.

#### Description of issue / Feature request

Spanned video worked seamlessly with this setup prior to OS upgrade with
Play videos on = All displays
Viewing mode = Spanned
Aspect = Fill screen
and Advanced mode configured via negatives values for ztop and zleft for the secondary display.

After upgrade to Monterey, 
 _Displays>Margins>Advanced Mode_ no longer respects "ztop" and "zleft" for the secondary display. Changing values makes no difference in the video offset.

I was able to almost recreate my previous offsets {"ztop" : -497, "zleft" : -1440} by setting {"offsettop" : 1,"offsetleft" : -1} and leaving my previous values in place. My current config under "Edit margins manually" is
{
  "displays" : [
    {
      "ztop" : 0,
      "zleft" : 0,
      "offsettop" : 0,
      "offsetleft" : 0
    },
    {
      "ztop" : -497,
      "zleft" : -1440,
      "offsettop" : 1,
      "offsetleft" : -1
    }
  ]
}

where again, the "ztop" and "zleft" values don't seem to be processed by the app anymore. 

The offsettop and offsetleft values are centimeters(?) versus pixels for ztop and zelft, so it is less precise and hence less useful.

**Comment by glouel** [comment]
Hey @ravedon 

Can you check and make sure that it says fill screen and not fit to screen ? For some reason that setting seem to have been reset, and it might just be what you are experiencing 

<img width="1135" alt="Capture_decran_2022-08-19_a_01 05 16" src="https://user-images.githubusercontent.com/37544189/185771711-5da92629-fa10-4707-90bd-096e12886cf5.png">

**Comment by ravedon** [comment]
Done. The same issue exists with either aspect setting.

**Comment by glouel** [comment]
Ok, I'll try to have a look and get back to you. 

However, just to clarify, he magins are cm but you can put a decimal in there (like 3.233) to get more precision. I have a hard time remembering what ztop/zleft does right now but I'll have a look ;)

**Comment by glouel** [comment]
@ravedon sorry I didn't get back yo you. I do believe this is fixed in 3.1.3. Could you confirm ?

**Comment by glouel** [comment]
Please reopen if it's not fixed
