### ISSUE TITLE
[feature request] 12 hr rather than 24 hr

### ISSUE THREAD

**Issue by BernSh19** [JohnCoates/Aerial#1261]
Title says it unless I missed the setting.

Thank you

**Comment by aidenmitchell** [comment]
![image](https://user-images.githubusercontent.com/30846409/186280019-56340131-6035-4bd5-82f5-94fe05477f44.png)

**Comment by glouel** [comment]
Sorry for the late reply @BernSh19 but yep, see above ! Closing, feel free to reopen if you still have issues

**Comment by BernSh19** [comment]
🙏 

Nice app. Wishing you much success!

Bern
