### ISSUE TITLE
Menu bar 'open settings' and location not working properly

### ISSUE THREAD

**Issue by liquidmetal2** [JohnCoates/Aerial#1266]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

From menu bar icon, Open Settings on the main dropdown does not work. have to go to experimental and 'launch aerial settings'.
also location does not seem to work. I had a screen recording, but not able to attach as GitHub says video is too big. Not able to compress the video to below 10MB
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/9691826/AerialLog.txt)
![Screenshot 2022-10-02 at 10 59 33](https://user-images.githubusercontent.com/2692241/193441450-111df4a5-6002-49e1-9479-fd810450bac1.jpg)
![Screenshot 2022-10-02 at 10 59 58](https://user-images.githubusercontent.com/2692241/193441456-1a6c3920-5503-4d60-997d-5071c4980c22.jpg)
![Screenshot 2022-10-02 at 11 00 08](https://user-images.githubusercontent.com/2692241/193441458-f2a368a1-35eb-475f-a5c8-6153b826f643.jpg)
![Screenshot 2022-10-02 at 11 00 17](https://user-images.githubusercontent.com/2692241/193441459-c0127dca-39ba-4aed-990d-e05b24b54add.jpg)
![Screenshot 2022-10-02 at 11 00 31](https://user-images.githubusercontent.com/2692241/193441461-ed528891-6218-4ca2-9fd0-288614ab8785.jpg)
![Screenshot 2022-10-02 at 11 01 25](https://user-images.githubusercontent.com/2692241/193441464-ac2d62ee-5308-4409-bd54-09cee77f3779.jpg)

**Comment by glouel** [comment]
Hey @liquidmetal2 

Apologies it's been a busy week and I wasn't able to answer you earlier. 

* Regarding the first issue, yes, it's an issue with the new System Settings from the macOS Ventura beta you are running. 

The experimental trick will work in the meantime, but you can also try the latest beta of Aerial Companion here from last july : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.4.0beta2/Aerial.Companion.app.zip

In beta2 you'll see it explicitly says that settings are not the same in screen saver mode and in desktop/fullscreen mode. 

<img width="406" alt="Capture d’écran 2022-10-08 à 16 54 26" src="https://user-images.githubusercontent.com/37544189/194713578-9905069a-4820-415e-83b2-128d961fbadb.png">

This is no longer true, despite what it says. Basically the 3 buttons will give you access to the same settings, except the top one opens macOS's System Settings, while the other two, Companion loads the settings in a window for easier access. I'm working on redesigning things so there's only one button in companion to make things simpler again, but it's not ready yet. Hopefully it will be for Ventura release.  

- Regarding location, it looks like it's not location but the weather fetch. Can you try opening System Settings > Screen Saver, then try the weather fetch from here ? I think there may be a weird network issue when Companion runs the screen saver, for some reason. It should not affect the screen saver when it runs, it should be able to fetch your data correctly. 

Let me know if that clears things up.

**Comment by glouel** [comment]
Quick update : the weather API uses HTTP and there's a security thing that blocks that nowadays by default, I'll try to see how to fix that. This is only an issue when running Aerial Settings from Companion, as far as I can tell.  The screen saver itself will run fine (but not the experimental stuff).

**Comment by liquidmetal2** [comment]
Hi
1. For the first item, will check out the beta later, as don’t really want to use beta at the moment on top of Ventura beta!
2. For the second item about weather location check, yes, doing it via System Settings > Screensaver > Aerial Options and selecting ‘current location’ worked and it shows the location correctly. Of course as you mentioned via the Companion app, it doesn’t work due to the http block; I expect mostly all are now required to be https.

Thanks for your reply and the nice work on Aerial screensaver

Thank you,

Ravindra Holalkere

A developed country is not where the poor have cars, it's where the rich use public transport 
												
															— (Unknown) Mayor of Bogota. 


The greatest tragedy in mankind's entire history may be the hijacking of morality by religion. 

															—Arthur C Clarke

**Comment by glouel** [comment]
@liquidmetal2 second bug is also fixed in this beta of Companion with more fixes for Ventura, I would encourage you to actually update because of the Ventura changes : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b2/Aerial.Companion.app.zip

**Comment by liquidmetal2** [comment]
Ok sure, thanks. Will try it out today.



Thank You,

Ravindra H


"Primitive life is very common and intelligent life is fairly rare. Some would say it has yet to occur on earth.”

																			—Stephen Hawking, Lecture at George Washington University, 2008


"We have, I fear, confused power with greatness"

                                                    													—Stewart Udall (he said this decades ago and it holds true for the millennia).
