### ISSUE TITLE
You cannot use this versio nof Aerial screen saver with this versiob of macOS

### ISSUE THREAD

**Issue by orenelim** [JohnCoates/Aerial#1270]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 14-inch, 2021, Apple M1 Max
- [ ] macOS version: Monterey 12.6
- [ ] Monitor setup: Built-in

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

After recent upgrade of Aerial I keep getting message that Aerial screen saver cannot start on my Monterey macOS

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/9844879/AerialLog.txt)
[AerialUnderCompanionLog.txt](https://github.com/JohnCoates/Aerial/files/9844880/AerialUnderCompanionLog.txt)

**Comment by glouel** [comment]
@orenelim where do you see the message exactly ?

**Comment by orenelim** [comment]
When the screen saver is starting

**Comment by glouel** [comment]
@orenelim are you still running Monterey or updated to Ventura ? Is the issue still here ?

You seem to be using companion, so I expect that running in a Window does work at least, can you confirm that ?
