### ISSUE TITLE
Weather Overlay test is broken

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1272]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: M1, 2020
- [ ] macOS version: 13.0 (22A380)
- [ ] Monitor setup: 1 monitor
- [ ] Aerial 3.2.1

#### Description of issue / Feature request
1. Testing the Weather overlay does nothing. 
2. Weather informatoin displayed is wrong. e.g. currently 
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1205471/199424770-b73f0a99-b4fd-4a86-966b-d20e8948eb99.png">
Shown in Aerial
<img src="https://user-images.githubusercontent.com/1205471/199425026-eabdd16b-0eb1-4855-8a72-8929b59c4412.jpg" >

**Comment by mbierman** [comment]
Ah, suddenly the test did work. Looks like the weather is for the wrong city.

**Comment by mbierman** [comment]
Also, the instructions are conflicting. It shows using a state abbreviation but also says not to abbreviate. Note, neither "santa clara, california, USA" nor "santa clara, ca, USA" work. 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1205471/199585325-8050218e-c0af-4d82-b0e6-a6e10609d1ce.png">

**Comment by glouel** [comment]
Hey @mbierman 

In general city lookup is powered by OpenWeather and what gets replied can depend from time to time, it seems like they are constantly tweaking their servers. 

I specifically modified the text yesterday because someone from the US said that doing City, State, USA was the way to go for the USA, but that may not have been correct. It looks like Open Weather's lookup can be weird at time specifically for the US, so I'm not sure what I should even put there. 

Regarding current location, be aware that if you open settings via Companion, location will not work unless you allow Companion to use location services in System Settings, on top of doing it for legacyScreenSaver for the regular panel. 

Hope that clears things up a bit.

**Comment by glouel** [comment]
Also, I just did some more testing : 

Santa Clara, CA <- says City doesn't exist (you may have to resize the panel a bit if you don't see the message)
Santa Clara, USA <- works
Santa Clara, CA, USA <- works

I had a 3rd party check those results with same results, so I think the current recommendation (always put , USA at the end, and add state if needed for disambiguation) is correct.

**Comment by mbierman** [comment]
> I specifically modified the text yesterday because someone from the US said that doing City, State, USA was the way to go for the USA, but that may not have been correct. It looks like Open Weather's lookup can be weird at time specifically for the US, so I'm not sure what I should even put there.

Here's the API 
https://openweathermap.org/api/geocoding-api

<img width="626" alt="image" src="https://user-images.githubusercontent.com/1205471/199640744-b9543a10-6639-4925-820d-012df0d5a201.png">

And note
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1205471/199640815-509e3443-84e7-4469-8219-11cb8db147e3.png">

> Regarding current location, be aware that if you open settings via Companion, location will not work unless you allow Companion to use location services in System Settings, on top of doing it for legacyScreenSaver for the regular panel.

I was only looking at Aerial itself, not Companion. 

* **Santa Clara, US** works correctly
* **Santa Clara, CA, US** works correctly.
* **Santa Clara, USA and Santa Clara, CA, USA**  Is the wrong city (in another country). 

USA is not the right country code and in the US states must be two letter abbreviations as best I can tell.

**Comment by glouel** [comment]
Thanks a whole lot for digging in @mbierman I'll fix a bit the documentation and put an example such as : 

"Cupertino, CA, US" which should tell everyone in the US how to handle their case.

**Comment by glouel** [comment]
@mbierman this is the new text : 

- Manually specify : Simply enter your location as the name of your city, followed by a country abbreviation. In the United States, to remove ambiguity, you can also add a state abbreviation  (e.g. Cupertino, CA, US).

I think this should solve this issue ? Same example is in placeholder for next build too.
