### ISSUE TITLE
Weather Overlay text 

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1273]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: M1, 2020
- [ ] macOS version: 13.0 (22A380)
- [ ] Monitor setup: 1 monitor
- [ ] Aerial 3.2.1

#### Description of issue / Feature request
![image](https://user-images.githubusercontent.com/1205471/199650310-43075b65-79b3-4c8f-98a1-603b0670448c.png)

**Comment by glouel** [comment]
Each Xcode upgrades messes my alignments and sizes, it's crazy... I'll fix it tonight thanks for the heads up !
