### ISSUE TITLE
Feature request: VLC playing status

### ISSUE THREAD

**Issue by Vinchethescript** [JohnCoates/Aerial#1274]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBookAir6,1 (MacBook Air mid-2013, 11-inch)
- [x] macOS version: Big Sur (11.6.7)
- [x] Monitor setup: MacBook Air integrated 11-inch monitor + external 1080p monitor

#### Description of issue / Feature request

In the current latest version (3.2.1) of Aerial, only Spotify and Apple Music are supported for the playing status in the screensaver, but I use VLC media player because it supports FLAC files. Also, FYI, VLC media player also has a HTTP interface you can use to interact with it, so you can get song information with that, if it can be useful. Thanks.

**Comment by glouel** [comment]
hey @Vinchethescript 

I'm looking for a universal way to do this but haven't found it yet. Right now I have to hard code if for everything and it will quickly become unmanageable if I add many. I'll keep you posted but I'd rather have a "full" solution for this than add support for every player.

**Comment by Vinchethescript** [comment]
Fair, a universal way is always better than a hard-coded way. I can only wait, since I don't really know Swift yet.

**Comment by glouel** [comment]
@Vinchethescript took a while but this is finally available in latest beta : https://github.com/JohnCoates/Aerial/releases/tag/v3.2.7beta2

It will show any app that playbacks audio in macOS now, including VLC !

**Comment by Vinchethescript** [comment]
Since the feature has been added, I'm closing this issue. Thank you!
