### ISSUE TITLE
Can't change speed

### ISSUE THREAD

**Issue by Explosion-Scratch** [JohnCoates/Aerial#1281]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/61319150/213761451-d615afce-f031-4514-a691-91fe8af8a49c.png">
I have per video vibrance on:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/61319150/213761540-544bf91f-869d-4eb4-a548-5e2dc5b1d967.png">
When viewing a video though there is no speed slider:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/61319150/213761622-4a956229-e663-4235-b00a-9f206030552e.png">

The slider appeared once but I can't find it now and now it's too fast and I get dizzy

**Comment by glouel** [comment]
Hey @Explosion-Scratch 

Are you running Ventura and using HDR ? I think I may have broken stuff while workarounding a bug in the new System Settings. Will try to dig a bit and get back to you !

**Comment by glouel** [comment]
@Explosion-Scratch 

Well, found the bug : https://github.com/JohnCoates/Aerial/releases/tag/v3.2.2beta2

You'll need to use Companion (as you seem to be doing from your screenshot) to set playback speed though if you are using Ventura ! Let me know if it fixes stuff for you.

**Comment by Explosion-Scratch** [comment]
Still can't find the slider for it but after uninstalling and re-installing both Aerial companion and the Aerial screensaver it seems to have a normal playback speed again

**Comment by Explosion-Scratch** [comment]
If you need me to debug in any way I'm happy to do so

**Comment by glouel** [comment]
@Explosion-Scratch 

Again, super sorry it took me so long, I think I really have it fixed this time, it will be in a build released later today : 

![Capture d’écran 2023-05-13 à 18 38 45](https://github.com/JohnCoates/Aerial/assets/37544189/16e9e7c7-8a10-47b5-889a-1eccae92b42f)

Will keep you posted, should be in a couple hours

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/tag/v3.2.5 should finally work, I'll let you confirm

**Comment by Explosion-Scratch** [comment]
Awesome, appreciate you guys working on this actively!

**Comment by Explosion-Scratch** [comment]
Lol sorry
