### ISSUE TITLE
Version Confusion

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1283]
When I check the “About” pane in the system pref pane, it says I’m running v3.0.1 (see attached screen shot)

But this file:
 ~/Library/Screen Savers/Aerial.saver
...shows v3.2.2beta1. 

...which I believe is the latest.

Is this the way it's supposed to work?

JIM
<img width="721" alt="Screen Shot 2023-01-28 at 3 35 49 PM" src="https://user-images.githubusercontent.com/7252766/215275337-4b57b38b-457a-4976-b087-e75f358ca289.png">

**Comment by glouel** [comment]
Unless you have two versions in you settings panel, this isn't right, no.

<img width="1144" alt="Capture d’écran 2023-01-28 à 16 41 55" src="https://user-images.githubusercontent.com/37544189/215275651-787e8cef-764d-4b0b-aed5-7694fdba22b4.png">

You may have another version in `/Library/Screen Savers/` too and that's the one you may be using. Double check you only have one and it's in your user's Library, not the global one as this is not working great in modern macOS.

**Comment by Jimmbo** [comment]
No, it's only in my user's library.

Good news: version now shows correctly. I suppose I was in update process when I posed that.

However, the question is why it's updating now, when I have Aerial Companion installed. Earlier, I re-downloaded Aerial Companion to replace the previous (just to be sure, though it wasn't too old), and also tweaked some Aerial prefs. This seems to have provoked an update.  Strange! I don't need further help on this, but I'm happy to test anything or supply logs if your'e curious.

Also, I was glad to see the option of "let Aerial determine settings for me but don't take all my disk space!". I selected this. However, Aerial is still using a huge 38gb of disk space.

**Comment by glouel** [comment]
No problem, few things to answer your questions :  

- If you had System Settings opened while it updated, the old version was loaded in memory until you close System Settings and reopened it again (the whole thing, not just the screen saver panel). 

- Did you update to the companion beta ? Some old version may have had bugs regarding detecting update, especially if you don't restart your mac often. That or it wasn't running in the background. Latest beta for ventura is here in any case : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

- Cache, what says this panel : 

<img width="1135" alt="Capture d’écran 2023-01-28 à 17 25 09" src="https://user-images.githubusercontent.com/37544189/215277595-b7de92e2-c720-4117-ac07-73ab6a38f0e7.png">

You can limit the size of the cache to something sensible to you (don't go below 5 GB). It won't clear immediately though. It will only clear on rotation, aka, "Replace videos" (I may change this at some point). Make sure you have "Replace videos" set to something other than Never, or video rotation (and cleanup) will never happen.

**Comment by Jimmbo** [comment]
Thanks! will update to beta Aerial Companion once I upgrade OS to Ventura. My cache was set to 36gb. Suggest that when you ask to have Aerial config this for the user, it offers a sanity-check cache setting, and ask "Does this look right?" I realize there's a fine line between this and manual config, but this strikes me as reasonable/helpful. Just an idea!
