### ISSUE TITLE
Unable to set as wallpaper on both displays

### ISSUE THREAD

**Issue by fd1911** [JohnCoates/Aerial#1284]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MBP 2022 M2
- [x] macOS version: 13.1
- [x] Monitor setup: Built in retina,  LC24RG50 Samsung Curved display.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I was unable to get logs, but it says that the screensaver is disabled and the wallpaper funcion works only in one monitor at the same time.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/50965810/215296915-b5c6d14a-cc4b-4f84-9764-24722b805e42.png">

Any advise, or even a guide into troubleshoot it at code level will be appreciated.

Thanks!!!

**Comment by glouel** [comment]
Hey @fd1911 

I can confirm, right now you can only set it on one display. I'm still working on this, hopefully in next beta soon.

**Comment by glouel** [comment]
@fd1911 it took a while but you can now launch on either all displays (the new default), or pick select displays : 

![Capture d’écran 2023-06-29 à 18 39 32](https://github.com/JohnCoates/Aerial/assets/37544189/d9904de4-1b33-47a4-a9b5-6b7da0c140fd)

Available in beta6 here : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b6/Aerial.Companion.app.zip
