### ISSUE TITLE
Custom Date Formatting Rules Ignored (ISO 8601)

### ISSUE THREAD

**Issue by alvintuo** [JohnCoates/Aerial#1288]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: Mac Mini (2023, M2 Pro 10c)
- [X] macOS version: Ventura 13.2.1
- [X] Monitor setup: Dual,, Dell U2415

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

The option to change the date formatting in overlay is broken. I wanted to use the ISO 8601 date format using Unicode, but the overlay ignores the custom formatting in preview. 
![Screenshot 2023-03-21 at 14 07 02](https://user-images.githubusercontent.com/52668092/226701965-1eb82577-b3d5-43db-ac77-d5563e97a58f.png)

In preview, the date shows up as "March 21, 2023".

**Comment by glouel** [comment]
Ok I finally figured it out : 

![Capture d’écran 2023-03-24 à 18 09 18](https://user-images.githubusercontent.com/37544189/227594212-e6df3546-e8bb-4d48-8256-91a502b048ed.jpg)

I'll post a beta later today or tomorrow !

**Comment by glouel** [comment]
Sorry @alvintuo  forgot to update but beta was posted with this fix.

**Comment by alvintuo** [comment]
Thank you for your help!
