### ISSUE TITLE
Not working on lockscreen and only working as a screensaver

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [JohnCoates/Aerial#1289]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 16-inch 2021
- [x] macOS version: 13.2.1 (22D68)
- [x] Monitor setup: builtin display

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request
Aerial only works as a screensaver, when I trigger lock screen by pressing power button, it doesn't work.
Is this natural? If it's not, what should I do to fix?

**Comment by glouel** [comment]
Hi @0xF4D3C0D3 

I'm not sure exactly what you mean by "trigger lock screen by pressing the power button" ? 

Are you saying, if your computer is asleep (black screen) and you press the power button to wake it up, you see a lock screen without a screen saver ? If so, I believe 0this is how it works with macOS, and as far as I know with all screen savers. Screen savers aren't relaunched for the lock screen as far as I know, you can probably double check with a built in screen saver (try Message from Apple). 

I'm not sure there's a way to change this either, as for security reasons Apple changed a lot of stuff around how screen saver works nowadays (they run under your user account, so you have to be logged in for it to start, if that makes any sense, and if you see a lock screen, well, you're not)

Did I get this right or are you asking something else ?

**Comment by 0xF4D3C0D3** [comment]
Hi! @glouel 

the power button I mentioned is the top rightmost button in following picture:
![image](https://user-images.githubusercontent.com/19762154/228111244-4f430380-db2d-4072-b6dc-e939b5a437e4.png)

when I press that button, my macbook is locked and then after wake it up the screen is inanimate and not from aerial screen but just normal wallpaper.

well I found similar things that this is a feature not a bug in terms of security and I confirm now with your answer. I'll close this issue. thanks for awesome opensource!

**Comment by glouel** [comment]
No problem, take care. And if you need to look up more details, Apple changed the whole security model in macOS Catalina.
