### ISSUE TITLE
Screen saver options button only works once on macOS 13 Ventura

### ISSUE THREAD

**Issue by dnicolson** [JohnCoates/Aerial#1291]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 16" 2021
- [x] macOS version: 13.3 (22E252)
- [x] Monitor setup: n/a

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

On macOS Ventura with Aerial 3.2.3, the "Options…" button works but after the Aerial "Close" button is used, System Settings needs to be restarted for it to work again.

The issue does not appear to affect macOS 12.5.

**Comment by glouel** [comment]
@dnicolson I can confirm the issue, it's been reported elsewhere and I thought I had answered you already, sorry about that.

At this point I have no idea why this is happening, whether it's a bug in System Settings or an undocumented change on how legacyScreenSaver operates. 

As a workaround in the meantime, if you use Aerial Companion for ventura (see here https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b3 ), you can launch settings directly hosted from it, and it works everytime this way.

**Comment by glouel** [comment]
Should be fixed in 3.2.6
