### ISSUE TITLE
Need uninstall instructions for Ventura 13.3

### ISSUE THREAD

**Issue by flidget** [JohnCoates/Aerial#1294]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 
- [ ] macOS version: 
- [ ] Monitor setup: 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

How do you uninstall in Ventura 13.3. Since installing this app, Apple Watch is not receiving authorisation requests.

**Comment by glouel** [comment]
@flidget I don't think the Apple Watch bug is linked to Aerial. 

In any case, follow the instructions here:  https://aerialscreensaver.github.io/faq.html#uninstall

The documentation is slightly outdated, after following the Big Sur instructions, open a terminal and do : 

```
rm "~/Library/Screen Savers/Aerial.saver"
```

This will remove the screensaver itself.

**Comment by glouel** [comment]
See this regarding Apple Watch : https://forums.macrumors.com/threads/apple-watch-no-longer-unlocking-mac-after-ventura-13-3-installation-merged.2385085/

Sadly this is a bug in 13.3.

**Comment by flidget** [comment]
Many apologies, I no longer want to uninstall.
