### ISSUE TITLE
[Feature Request] Hotkey to active Aerial

### ISSUE THREAD

**Issue by Beatzoid** [JohnCoates/Aerial#1298]
Could a hotkey please be added that triggers the `Launch Aerial` function?

**Comment by glouel** [comment]
@Beatzoid sorry looks like I didn't see your issue.

Have you tried using a hot corner in macOS Settings to launch the screensaver? This is usually the recommended way to do things. 

Lookup hot corner under Desktop & Dock in macOS Settings, there you can assigne one corner to launching the screensaver.

**Comment by Beatzoid** [comment]
Thank you so much, that works perfectly!
