### ISSUE TITLE
Not running full screen, just in bottom-left corner

### ISSUE THREAD

**Issue by steve-klein-Au** [JohnCoates/Aerial#1299]
Couldn't find this in the troubleshooting or other help pages

MacBook Pro (16-inch, 2019
macOS 13.3.1 (a) 
1 external 4K monitor + built-in display

#### Description of issue / Feature request

Built-in display was blank, and Aerial only ran in the bottom-left corner of my external 4K display.

<img width="2560" alt="Screenshot 2023-05-11 at 4 55 55 PM (2)" src="https://github.com/JohnCoates/Aerial/assets/73239985/d9ef61ad-bb2a-4f9a-a24f-27d6ef1c32ec">

**Comment by glouel** [comment]
Hi @steve-klein-Au 

Please see this pinned issue, this is a bug in macOS 13.3.X : https://github.com/JohnCoates/Aerial/issues/1286

Closing this as a duplicate.
