### ISSUE TITLE
USing this as a desktop background...

### ISSUE THREAD

**Issue by JimmyPco** [JohnCoates/Aerial#13]
what would it take to use this as a desktop background? i know it would be horrible on a laptop but i would love it on my macpro!

**Comment by iAlborz** [comment]
Wallsaver offers this option and it works on all screen savers.

http://wallsaver.en.softonic.com/mac

**Comment by agucova** [comment]
Or better, just open Terminal, and type the following:
   `/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background`

**Comment by joshnh** [comment]
#37

**Comment by MichaelDimmitt** [comment]
@JimmyPco, this application that I wrote uses a launch agent. 
https://github.com/MichaelDimmitt/Aerial_Desktop

It never opens more than one instance of Aerial. It loads from sleep or from startup. It automatically selects Aerial as the screensaver but that can be changed rather easily. It is meant to be incredibly simple click to install/enable click to uninstall/disable.

Want to switch to a new video after its already running? click uninstall and install and your desktop background will be different.

Meant to be super user friendly for my friends who are not programmers.

Does exactly what you are looking for and if you do not want it on all the time you can click uninstall and install it whenever you want. My laptop MacBook Pro (13-inch, Mid 2012) can run for 6 hours without needing a charge. So it does not consume a lot of resources. Chrome usually more expensive. Regards, Michael Dimmitt.

**Comment by NightRaider73** [comment]
@glouel Close this
