### ISSUE TITLE
New version results in duplicate "Aerial" object in screen saver menu

### ISSUE THREAD

**Issue by bham861** [JohnCoates/Aerial#130]
After downloading the new beta version I ended up with two icons (and instances apparently) of Aerial in the screen saver chooser menu. 

Although right clicking on either one presents a "delete" and move to trash option, neither one actually works, so there is no way to clean up the menu and leave only the most recent app version. 

Running Yosemite 10.10.5 on MacBook Air Core i7

**Comment by JohnCoates** [comment]
That's really weird. You should've been prompted to replace. Do you see two copies when you go to this folder: ~/Library/Screen Savers/
You can use Cmd+Shift+G to navigate there in a Finder window.

**Comment by bham861** [comment]
Two files. One is called Aerial and the other called Aerial 3 due to the duplicate download of the same title. I didn't override the default file title it created when I downloaded the beta version.

**Comment by JohnCoates** [comment]
Alright cool. I'm going to solve this issue by packaging releases in a DMG instead of a .zip to prevent extractors from renaming the screen saver

**Comment by bham861** [comment]
Awesome. Thanks. Killer job on this.

**Comment by chrislowthian** [comment]
I have the same issue but how can I remove them? If I right click and choose Delete Aerial and choose "Move to Trash" nothing happens?

I have tried restarting too.

**Comment by beornlake** [comment]
@chrislowthian If you chose to "Install for all users" when you first set up Aerial, then you'll need to manually remove the old version from `/Library/Screen Savers/` (note, that's the Library at the root level of your drive, not the one in your home folder). This appears to be a bug in the System Preferences app – it won't delete Screen Savers that are installed for all users.

**Comment by chrislowthian** [comment]
Thank you that worked perfect, much appreciated!
