### ISSUE TITLE
Screensaver on second display does not display correctly

### ISSUE THREAD

**Issue by bfg111** [JohnCoates/Aerial#1302]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: Apple M1 Pro
- [X] macOS version: macOS Ventura - Version 13.2.1
- [X] Monitor setup:
  - monitor 0: (lid closed on laptop) - not using built-in display
  - monitor 1: HP Z32 - (3840x2160)
  - monitor 2: Dell U2720Q - (2160x3840 - vertical arrangement)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I have two displays, and initially, everything seems to work. But after maybe 1 or 2 seconds, the secondary screen (vertical alignment) shifts to a horizontal frame (based on horizontal arrangement - even though it is vertical) and only fills part of the window.  Otherwise (other than the weird rendering on the second screen), everything seems operational. It is not the end of the world, but it is certainly annoying.

I have tried both the regular (3.2.5 and beta 3.2.5 versions of the software)

Below I have included what I think is the relevant part of the debug log

```2023-05-26 06:28:08.915 : PrefsTime : manual
2023-05-26 06:28:08.915 : night
2023-05-26 06:28:08.916 : Manual : night
2023-05-26 06:28:08.916 : night
2023-05-26 06:28:08.916 : Brightness before Aerial was launched : Optional(0.0)
2023-05-26 06:28:08.916 : Real screen count : 2
2023-05-26 06:28:08.917 : Using : Optional([id=3, width=2160, height=3840, bottomLeftFrame=(3840.0, -883.0, 2160.0, 3840.0), topRightCorner=(6000.0, 2957.0), isMain=false, backingScaleFactor=1.0])
2023-05-26 06:28:08.917 : <AerialView: 0x147699920> setting up player layer with bounds/frame: (0.0, 0.0, 2160.0, 3840.0) / (0.0, 0.0, 2160.0, 3840.0)
2023-05-26 06:28:08.917 : The data couldn’t be read because it isn’t in the correct format.
2023-05-26 06:28:08.918 : The data couldn’t be read because it isn’t in the correct format.
2023-05-26 06:28:08.918 : Using dot workaround for video driver corruption
2023-05-26 06:28:08.918 : <AerialView: 0x147699920> backing change 1.0 isDisabled: false frame: (0.0, 0.0, 2160.0, 3840.0) preview: false
2023-05-26 06:28:08.919 : <AerialView: 0x15666f3a0> startAnimation frame (0.0, 0.0, 3840.0, 2160.0) bounds (0.0, 0.0, 3840.0, 2160.0)
2023-05-26 06:28:09.022 : <AerialView: 0x15666f3a0> observeValue Optional("readyForDisplay") true
2023-05-26 06:28:09.022 : start playback: (0.0, 0.0, 3840.0, 2160.0) (0.0, 0.0, 3840.0, 2160.0) rate: 1.0
2023-05-26 06:28:09.402 : <AerialView: 0x147699920> startAnimation frame (0.0, 0.0, 2160.0, 3840.0) bounds (0.0, 0.0, 2160.0, 3840.0)
2023-05-26 06:28:12.117 : ############ willStop
2023-05-26 06:28:12.118 : <AerialView: 0x15666f3a0> stopAnimation
2023-05-26 06:28:12.119 : <AerialView: 0x15666f3a0> observeValue Optional("readyForDisplay") false

**Comment by glouel** [comment]
Hi @bfg111 

Are you 100% sure you are running Ventura 13.2.1 and *not* 13.3.1 ? 

Because this looks an awful lot like a variation of the huge multimonitor bug that we're discussing here : https://github.com/JohnCoates/Aerial/issues/1286 , but as far as I remember, it started with 13.3betas (though to be honest because I'm on the beta cycle I could have missed the point update). 

Also, does the bug happen 100% of the time ? Last thing, a log from an entire run would be more helpful, I can't see any of your settings/videos here.

**Comment by bfg111** [comment]
This bug happens *every* time without fail. I will include an image.
![IMG_4705](https://github.com/JohnCoates/Aerial/assets/15930421/22bfb25a-eb9c-45a0-a9ca-497380a9f3e2)
```sw_vers
ProductName:             macOS
ProductVersion:         13.2.1
BuildVersion:           22D68

**Comment by glouel** [comment]
Thanks for the picture. This is a bit weird and likely different. The margin at the bottom is also a bit weird and uncharacteristic. 

I think you are running Viewing mode : Independant in Aerial's Settings > Display, correct ? or is this a Spanned mode ? 

I'll try to dig a bit, I think some people complained of issues with vertical screens with one particular macOS build, will keep  you posted.

**Comment by glouel** [comment]
Ok I found some more info digging into discord, they had this bug during the beta and reintroduced multiple times depending on the configurations, last report I have is in November, this one has a nice video that seems to exactly mimic your issue : https://discord.com/channels/736331643723317248/742308387903242270/1044762078520557599

I believe that's the same issue you have. 

What I remember from that time is that playback also failed similarly with Quicktime, you may want to try and play one of Aerial's videos from the Cache folder in quicktime on your vertical screen and activate full screen, if I remember correctly it had the same issue. 

Assuming it's the same macOS issue, this is something you'll need to update.

However it's a bit of a mess, 13.3.x should be avoided per the other link I gave you earlier. 13.4 is "okayish" regarding that core bug. 

I do have multiple people who reported that 13.4 works correctly with a setup similar to yours (one vertical + one horizontal), including in the link above, but as best as I can recall, the rotation bug that affected Quicktime was probably a graphic driver bug that could be specific to some GPU, so no guarantee.

**Comment by bfg111** [comment]
I can confirm that QuickTime player has the exact same issue trying to display in full-screen mode on the second (vertical) monitor. Oddly, with QuickTime player if I move my mouse on the secondary (vertical) display it switches to full-screen mode (working) for about a second and then back to the weird behavior of only using part of the screen. Thanks for pointing me in the right direction.

**Comment by glouel** [comment]
No problem, thanks for confirming! Should you update to 13.4, let me know how it goes.
