### ISSUE TITLE
Aerial Saver [Both Versions] Java Error [a different one]

### ISSUE THREAD

**Issue by Hebetudinous** [JohnCoates/Aerial#1303]
[Java Error.pdf](https://github.com/JohnCoates/Aerial/files/11578644/Java.Error.pdf)

Any advice, please?  Have tried uninstalling/reinstalling both Aerial and Java; no luck.

Thanks.

**Comment by glouel** [comment]
@Hebetudinous this looks like a Windows version of Aerial ? You should check their, as this repository is only for the Mac version, I have no idea about that other one sorry :(
