### ISSUE TITLE
Feature request: Bring back play next video with arrow keys in preview

### ISSUE THREAD

**Issue by craftey** [JohnCoates/Aerial#1306]
I remember a very nice feature of an older version running on an older macOS where hitting arrow keys would change the currently playing video. I understand that this feature is gone because of security in newer macOS versions.

However, I would love to see this feature when the screensaver is started via preview from 
System Settings -> Screensaver -> Preview.
If that is not possible a dedicated button from within the screensaver settings to start such a fullscreen preview with working arrow keys would be my next suggestion.

My kids would love that feature, they once enjoyed to hit the next button from time to time to see next video. This mode should be possible, if the computer is unlocked.

Thanks in advance,
Craftey

**Comment by craftey** [comment]
If I hit in preview mode two times space, the preview stops and starts again with a new video. This is currently the closest I can get to simulate the desired behavior of "play next video on key stroke".

**Comment by glouel** [comment]
Hey @craftey 

So this is an issue with restrictions in modern macOS. 

Basically, 3rd party screen savers aren't allowed nowadays to intercept keyboard keys. If you use a very old macOS (10.14 or earlier), pressing the right arrow will skip video.I cannot fix that sadly. 

But yep, there's a workaround ! If you use Aerial Companion (the app), there's a "fullscreen mode" where you can use arrow key again to your heart content again !

This is this button : 

![Capture d’écran 2023-06-08 à 23 18 31](https://github.com/JohnCoates/Aerial/assets/37544189/3bbb20d9-9592-4fa9-a132-72d11a64bab1)

This will launch Aerial in a fullscreen mode. Again, right arrow key to skip.

To get the latest beta of Aerial Companion, download here : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

**Comment by craftey** [comment]
@glouel Thank you very much for this wonderful reply. My kids will love Aerial Companion Fullscreen.
