### ISSUE TITLE
macOS Sonoma Beta 2, always show sharing screen icon on menubar

### ISSUE THREAD

**Issue by termaulmaul** [JohnCoates/Aerial#1309]
- [ ] Mac model: MacBook Air M1
- [ ] macOS version: 14.0 (beta 2)
- [ ] Monitor setup: 1 ext monitor

#### Description of issue / Feature request
every time I open Microsoft Edge, the Sharing Screen icon always appears in the menubar. Even though I'm not doing a share screen on the Microsoft Edge application or other applications. "Microsoft Edge is sharing your screen" Even though I closed the application, the icon still appears.

<img width="348" alt="image" src="https://github.com/JohnCoates/Aerial/assets/109366541/cb76d1f7-5e40-4b79-bc11-daf742dc99be">
<img width="874" alt="image" src="https://github.com/JohnCoates/Aerial/assets/109366541/123920d6-d39a-401b-9b46-bc7db7c92987">

**Comment by glouel** [comment]
Hi @termaulmaul 

Did you mean to post this somewhere else ? This is for issues with Aerial screen saver only.
