### ISSUE TITLE
Aerial doesn't respect the Energy Saver settings

### ISSUE THREAD

**Issue by IndigoHomme** [JohnCoates/Aerial#131]
Energy Saver settings on screen sleep and computer sleep are ignored.

**Comment by dcoeurjo** [comment]
dup #129

**Comment by dcoeurjo** [comment]
see #23

**Comment by alistairmcmillan** [comment]
@IndigoHomme Which version are you running? Beta 4 should fix this issue.

https://github.com/JohnCoates/Aerial/releases

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #23
