### ISSUE TITLE
CPU usage in iMac 2020

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#1310]
Something I noticed: 

I have found when Aerial tries to run, and it did this also under Ventura BTW

when Aerial starts my system fan and processor spin up, it sounds as if my I-Mac is going to take off like Air Force One or something, the fan speed maxes out, and it does this for 20 to 30 minutes. 

I reported this but was given the canned response of "Rest The SMC" La Di Da by Apple

So before doing all of that I just turn Aerial and the other "Magic Window" off and uninstalled, does not work anyway for now.

Wow, I have not heard this much quite from my Imac in months, RPM is in the 1200 - 1500 range Normal
before it would spin at 2800+

Did anyone else notice? Just curious?
I have been using Macs Fans Control as a monitor for a long time.

_Originally posted by @DSBlackHeart in https://github.com/JohnCoates/Aerial/issues/1305#issuecomment-1610301876_

**Comment by glouel** [comment]
Assuming you are interested in fixing this, there are two known cause of CPU usage in Aerial, video decoding and text rendering.  

1) According to your posts you have a 2020 iMac with 3 monitors, which means an Intel CPU, and that video decoding happens through your CPU's Intel QuickSync unit (Apple never uses your GPU to decode videos on Intel macs) if possible, and if not it will failover to pure CPU decoding (which will make your fans spin). 

Aerial supports multiple video formats but not every one will work great : 

![Capture d’écran 2023-06-28 à 15 12 18](https://github.com/JohnCoates/Aerial/assets/37544189/45703ccf-8e7e-4e06-baa8-723d2a367f96)

- HDR decoding is not supported by your QuickSync version and will result in a pretty high CPU usage (and fan spinning). So those modes are out. 
- 4K HEVC *should* be fine from reports I had from other users, though I'm not 100% sure having 3 decodes simultaneously is supported. 1080p HEVC may be better. 
- 1080p H264 should never make your fans spin.

I would suggest you check your settings in Advanced panel, and check what you have picked there at the top for video format.

From this same panel, you can open a Finder window to Aerial's directory by pressing "Show log in finder" at the bottom. In there, there's a Cache folder. To check for video decoding performance, and see if this is a general issue or not, play one video in Apple's QuickTime (not any other video player), and repeat to play 3 fullscreen videos from the cache simultaneously. If you hear your fans spinning and it bothers you, you need to lower your video format. 

In general, what you have in Quicktime with those precise videos should be exactly what you get with Aerial. If not see point 2 below. 

2) Text rendering can cause slowdowns on some Intel macs, not all of them. There's a graphics driver bug that can cause that issue. There is a workaround in the settings, just below where you pick your video format : 

![Capture d’écran 2023-06-28 à 15 20 44](https://github.com/JohnCoates/Aerial/assets/37544189/5c172934-ccbc-4d7b-9396-c73e00c17801)

Uncheck this box, and see if it improves your fan situation.

**Comment by DSBlackHeart** [comment]
Thank You for posting this, However since installing Sonoma I cant even open the Aerial Prefs to get to this. I will keep it though for when a fix is finally up and running.

**Comment by glouel** [comment]
You can workaround that with Aerial Companion beta, pressing this button : 

![Capture d’écran 2023-06-28 à 16 28 01](https://github.com/JohnCoates/Aerial/assets/37544189/68fe46cf-0e41-4be3-9267-a9e366193c83)

Latest beta here : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b5/Aerial.Companion.app.zip
