### ISSUE TITLE
Any way to disable when connected via VNC?

### ISSUE THREAD

**Issue by stevehoek** [JohnCoates/Aerial#1312]
I connect via VNC using the Screens app to a remote Mac with Aerial installed.  Is there any way to prevent the screensaver from running in this context?

**Comment by glouel** [comment]
@stevehoek this looks like VNC doing non standard things, but this is not related to Aerial. 

You may want to ask in a more appropriate place around VNC users of macOS, but have a look at this for starter : https://brian-d-pemberton.medium.com/how-to-turn-off-screensaver-for-remote-desktop-sessions-in-macos-catalina-f5d3735b1aa5
