### ISSUE TITLE
Support for Pandora as Music Provider

### ISSUE THREAD

**Issue by McTTRS** [JohnCoates/Aerial#1314]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: 
- [x] macOS version: 
- [x] Monitor setup: 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Mac Studio Ultra, MacOS 13.5, 2-27" LG monitors via Lightning - Please provide Support for Pandora Mac desktop app (Safari/web kit based) as Music Provider.}}

**Comment by McTTRS** [comment]
Works like a champ. Thank you.

**Comment by McTTRS** [comment]
I spoke too soon.  It works fine if the Mac is receiving Airplay from my the iPhone but when trying the Pandora desktop app (based on Safari/webkit) or either Spotify or Pandora web streaming via Safari, no joy.

**Comment by McTTRS** [comment]
Do you see them in the "Now playing" thing in your menu bar or not ?

Yes there is a static message, see screenshot.
<img width="297" alt="Screen Shot 2023-08-09 at 14 05 39 PM" src="https://github.com/JohnCoates/Aerial/assets/125928335/9a955582-9b57-4822-9d2e-97e8954965ab">
This same static message is displayed in the menu bar when using Pandora in either Safari or their Safari based 'desktop app' but is only displayed in Aerial when Safari web streaming is used - go figure.  In any case it is clear that Pandora is not playing as well by the Mac rules as they do by the iPhone/Airplay rules.  

I have several other Pandora clients on my Mac.  Both Pantunes and Hermes clients display the song title with fixed musical note only for artwork and Milkshake does not display anything.

**Comment by glouel** [comment]
I see the static thing, it's really on them to fix that (they can even provide artwork via safari, Youtube for example does it). 

The static note is what I put when there's no artwork so yeah, maybe you can ask those other clients to add the artwork ? It's something audio apps can provide fairly easily in macOS via the remote *something* API (can not quite remember the name right now but I can look it up, they should be able to find it though).

**Comment by McTTRS** [comment]
I think I will abandon the Mac as a Pandora client for the time being using the iPhone for Pandora and Airplay to the Mac which work great.  In addition, perhaps contact Pandora support and give them a rash about not having proper Apple 'compliant' Mac desktop and Safari web clients like Spotify does.😁. Thanks for you help - Aerial is kicking butt and it looks like I need to buy you yet another cup of Joe.
