### ISSUE TITLE
Use Current Location(Weather) is not working even if I enable the setting in Privacy

### ISSUE THREAD

**Issue by neptunewong1998** [JohnCoates/Aerial#1316]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MBP 14' M1Pro
- [ ] macOS version: Sonoma beta 5
- [ ] Monitor setup: MBP 14' M1Pro

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Use Current Location(Weather) is not working even if I enable the setting for LegacyScreenSaver in Privacy. It said I need to enable for the companion however, I am not able to find in the location setting.

**Comment by neptunewong1998** [comment]
Thank you for your help. When I tried to choose 'Use current location'. It returns and message that I need to enable location for both the legacy screensaver and aerial companion. However, I am not able to see aerial companions in the location setting. After I follow your instruction. I open the aerial companions and go to the location setting, I found the aerial companions toggle appears suddenly

**Comment by glouel** [comment]
No problem, they don't show most apps now unless you very very recently tried to access location, that's why the test button is useful. Sonoma is still and beta and this may change.

Anyway, glad it's fixed, let me know if you have another issue.

**Comment by neptunewong1998** [comment]
Thank you for your help and I hope this conversation can help others too.
