### ISSUE TITLE
Unable to Uninstall from MacOS 14

### ISSUE THREAD

**Issue by andrewbcoyle** [JohnCoates/Aerial#1317]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:   Mac Mini M1 2020
- [x] macOS version:  Sonoma 14
- [x] Monitor setup:  1 monitor

#### Description of issue / Feature request

Cannot uninstall screen saver.   Moving Aerial Companion to trash does not uninstall, nor does manually removing files here:  https://github.com/JohnCoates/Aerial/issues/1036

Screen saver options still appear in system preferences, and a background process called "Legacy Screen Saver (Wallpaper)" runs in the background nonstop requiring a force quit to temporarily stop.

**Comment by glouel** [comment]
@andrewbcoyle the way macOS applications work, trashing the app doesn't delete the support files, yes.

To fully cleanup, under Sonoma, you have to manually remove those files you pointed at, and delete the screen saver itself, which is again a separate macOS file, you can do that by right clicking where the red arrow is here : 

![Capture d’écran 2023-08-22 à 03 57 13](https://github.com/JohnCoates/Aerial/assets/37544189/e09afd56-00a2-4520-8bdb-799e386aaaf3)

Note however that the part where I put a large green mark is part of macOS 14 and *not* Aerial.
