### ISSUE TITLE
Favorites don't save and hide video selection also don't saved

### ISSUE THREAD

**Issue by sdugoten** [JohnCoates/Aerial#1318]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:  Mac Studio M1
- [ ] macOS version: 13.4.1
- [ ] Monitor setup:  Studio Display
- [ ] Latest version of Aerial saver from this website as of Aug 26, 2023

#### Description of issue / Feature request

After you select the favorites from the local video list, the favorite will back to zero after you close and reopen the settings panel.  Sames goes for the Browse video section, you can hide video in the source folder, but after you close the setting , it will forget

Something like this after you reopen the Setting window, it goes back to zero

![2023-08-26_01-03](https://github.com/JohnCoates/Aerial/assets/7108552/b23fe462-a952-419f-98ff-2d7a5affe5d5)

**Comment by glouel** [comment]
Is this with all videos, or just videos you have added yourself ?

**Comment by sdugoten** [comment]
> Is this with all videos, or just videos you have added yourself ?

I haven't tried other video, I just use my own local video for such testing.

**Comment by glouel** [comment]
Are you using the beta or the release version. I believe this is fixed in the latest betas : https://github.com/JohnCoates/Aerial/releases/download/v3.2.7beta5/Aerial.saver.zip
