### ISSUE TITLE
Installation instructions not clear/incorrect 

### ISSUE THREAD

**Issue by Den-Rimus** [JohnCoates/Aerial#1319]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 14" 2023, Apple M2 Pro, 32GB
- [x] macOS version: Ventura 13.5 (22G74)
- [x] Monitor setup: MacBook screen.

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Installation steps on website not clear or incorrect (not applicable):

> 1. Navigate to the [latest release](https://github.com/glouel/AerialCompanion/releases/latest)

Currently leads to [v1.5.0b9 version](https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b9)

> 2. Select AerialCompanion.dmg Disregard the remaining files/assets

There is no dmg among this release assets. Only `Aerial.Companion.zip` (and source code archives).

Let's assume we download `Aerial.Companion.zip`.

> 3. Navigate to your Downloads folder (or wherever you chose to save AerialCompanion.dmg)
> 4. Double click on AerialCompanion.dmg

Double-clicked on `*.zip`, unzipped.

> 5. It will momentarily pause to open the DMG file.

This one I don't understand at all, sorry.

> 6. You will then see a window that prompts you to drag Aerial Companion.app to the Applications folder. Plese drag and drop as shown below

Typo in word `plese` (please) but ok. Since there is no dmg file there is no prompt to drag anything anywhere, but I'll drag `Aerial Companion.app to the Applications folder` as it says by myself.

> 7. Now double click on the Applications folder that you just dragged the icon to.
> 8. Find and double click on Aerial.app

There is no such app there. Only Aerial Companion from before.

It is the app that user needs - it can be used and installed. But these and further install/use instructions are out of order.

Thanks for a great app! This coffee is on me 😎

**Comment by glouel** [comment]
Ok I made a mess with that 1.5.0b9... I thought I was doing a good thing 😅

I'll update the instructions, I ditched the DMG because it's overly complicated.

Now it's just unzip and move to your `/Applications` folder. 

Thanks for the heads up I'll do it right now !

**Comment by Den-Rimus** [comment]
That must've been the quickest reply on github issue 😅

**Comment by glouel** [comment]
Yeah, it might be 😅 

Thanks for the heads up as the download links were also broken... I really should have waited to push that new version. 

Anyway, updated instructions are here : https://aerialscreensaver.github.io/installation.html

There's also (long awaited) instructions on how to setup for multiple users.
