### ISSUE TITLE
Auto replay when end of video is reached

### ISSUE THREAD

**Issue by JaNd3r** [JohnCoates/Aerial#132]
Currently the video stops playing after some time. So when I leave my desk for a coffee and come back, this awesome screen saver shows a freeze frame, which is a bit sad. It would be super-duper, if the video is started over in a loop (or if it starts playing another video).

**Comment by alistairmcmillan** [comment]
If the videos stop playing it is most likely due to a network glitch as the videos are initially downloaded direct from Apple's servers.

Which version are you running? With the latest versions the videos are cached, so once they've all played once they'll be playing directly from your machine, until Apple update their source files with new videos.

**Comment by JaNd3r** [comment]
I'm already using the version including cache. As far as I can see, videos are only cached, if they could be downloaded completely. After about a minute or two all these videos come to a "natural end". :) The screen saver then freezes. I mean, it shows the last frame. My suggestion is to restart the video or play another one. That would be great.

**Comment by chrislowthian** [comment]
Having the same issue, the beta seems to play around 2 or 3 different scenes then freezes a couple of seconds after starting the next scene.

**Comment by chrislowthian** [comment]
From what I have seen (I am not a dev) if a network error occurs scenes will freeze and not restart.

Could this be because Aerial is not trying to reconnect after a dropout?

**Comment by JaNd3r** [comment]
So what happens normally, if the end of a video is reached? Or what SHOULD happen? :)

Can you confirm, that the video normally starts over again or another video is started automatically? As far as I can see, I have no network issue, that occurs DURING the playback of a video (since I cached almost all videos when I was not behind a proxy).

**Comment by chrislowthian** [comment]
It should keep playing different scenes continuously.

**Comment by mohataj** [comment]
plays here 2 sec, then freezes (10.11).
downloading the videofiles and placing in ~/Library/Caches/Aerial helps.
see #136

**Comment by glouel** [comment]
I know this is years old, but AFAIK this is fixed, if not please reopen :)
