### ISSUE TITLE
Custom Video Loop Flicker

### ISSUE THREAD

**Issue by Jasmer** [JohnCoates/Aerial#1321]
- [x] Mac model: MacBook Pro M1 15" 2021
- [x] macOS version: Ventura 13.5.2 (22G91)
- [x] Monitor setup: Built In

I am using an mp4 video animation I downloaded from this site https://www.apple.com/in/apple-events/ It is a 10-second video that loops in Quicktime perfectly, but when adding it to Aerial it flickers at the end of the loop. Any ideas? Thank you

**Comment by glouel** [comment]
@Jasmer go to Advanced and disable video fades, that might be what you see.
