### ISSUE TITLE
URL for new tvOS 17 videos

### ISSUE THREAD

**Issue by jacobwhite** [JohnCoates/Aerial#1324]
Can we get the url for the new tar file with urls of the new videos?

**Comment by BingoKingo** [comment]
tvOS 17 or macOS Sonoma maybe this https://configuration.apple.com/configurations/internetservices/aerials/resources-config.plist

**Comment by glouel** [comment]
Can confirm this is the new url for both tvOS and macOS as far as I know. I'm still importing those manually each time in Aerial right now as they kept changing the format during the beta but I'll likely add the check to this url soon. 

Closing this for now.

**Comment by jacobwhite** [comment]
Hey, thanks! I'm specifically looking for the video, "Following the Temblor Range in southern California"
I did find one in there that I haven't seen in the screensaver yet though, "California State Route 58, Carrizo Plain, California"

Any help finding that one would be greatly appreciated. These are the hills behind my house :)

**Comment by glouel** [comment]
![Capture d’écran 2023-09-25 à 14 54 09](https://github.com/JohnCoates/Aerial/assets/37544189/4d4af038-3b6a-4fc6-a12b-4403e01b9d30)

Make sure you have the latest version, it's part of "Superblooms". If you don't see it, go to more videos and press "refresh now" on the macOS source.
