### ISSUE TITLE
New 240 FPS format and HDR confusion

### ISSUE THREAD

**Issue by cryptochrome** [JohnCoates/Aerial#1325]
Hi,

I just noticed there is a new video format, "4K 240FPS". When I select that, none of the videos appear to be HDR. When I go back to the "4K HDR" format, the video browser shows a "1080p" tag on all videos, suggesting that none of them are available in 4K.

This is pretty confusing and I can't find anything in the docs. The help inside the screensaver setting does not mention the new 240 FPS format either. 

Thanks

**Comment by glouel** [comment]
Hi @cryptochrome 

4K 240 FPS is a new format that is used by apple, those are 4K videos with 240 frames per second that are indeed not HDR. As of right now, all the new videos that are available are only available in this format. 

However the old HDR videos should still be available as long as you keep enabled the tvOS 16 source. You may want to try unchecking macOS 14 in sources, see if it helps? If it does let me know, maybe I missed somethign when adding the 240FPS format.

**Comment by cryptochrome** [comment]
Thanks. So I have the tvOS source enabled, but it has zero videos available:

<img width="794" alt="Screenshot 2023-09-24 at 22 55 31@2x" src="https://github.com/JohnCoates/Aerial/assets/4440762/4067e56c-619a-4147-8921-5f268d1d0601">

The old videos seem to be available, though, but they all show as "1080p" in the browser:

![Screenshot 2023-09-24 at 22 57 14@2x](https://github.com/JohnCoates/Aerial/assets/4440762/7f8382e8-27e5-42c9-ade3-1a6875535704)

What you are seeing in these screens is what I see when I have 4K HDR videos selected. So right now, it appears to be either 1080p with some of them in HDR or the new 4K 240FPS with no HDR at all. Something is not right.

**Comment by cryptochrome** [comment]
Update: When I disable the macOS 14 source, the tvOS 16 source suddenly shows videos. All in 4K HDR. So I'll just keep that enabled. 

It's kind of an odd UX that when you enable macOS 14 source the tvOS source basically goes to 0 videos...

**Comment by glouel** [comment]
@cryptochrome thanks again for the heads up, there was a bug that disabled all other video formats, it's fixed in upcoming 3.3.1 later today.

**Comment by glouel** [comment]
Closing with 3.3.1 released. You can safely reenable the macOS source if you want the new videos (those are not available in HDR yet, but Aerial will use the non HDR ones for now, until they become available and will replace them then. This is the part I had broken in 3.3.0 ;))

**Comment by cryptochrome** [comment]
Awesome, thank you!
