### ISSUE TITLE
v3.2.5 Won't Update

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#1327]
Aerial v3.2.5 won't update

When I launch latest Aerial Companion (v1.5.0b9), nothing happens (though I do see its process in Activity Monitor)

iMac (Retina 5K, 27-inch, 2020) running MacOS  v12.7

**Comment by Jimmbo** [comment]
Ha. Just before sleeping the computer, I thought I'd re-check version, and it's indeed updated to 3.3.1. I guess it just needed time to download. Some sort of thermometer (or other feedback upon launching Aerial Companion) might be helpful.

**Comment by r8ders2k** [comment]
FWIW, I re-install the Aerial Companion app (beta 9) and the 3.3.1 update was immediately available to download/update.On Sep 25, 2023, at 11:14 PM, Jimmbo ***@***.***> wrote:﻿
Ha. Just before sleeping the computer, I thought I'd re-check version, and it's indeed updated to 3.3.1. I guess it just needed time to download. Some sort of thermometer (or other feedback upon launching Aerial Companion) might be helpful.
