### ISSUE TITLE
Overlays not appearing after Sonoma update

### ISSUE THREAD

**Issue by sslalani** [JohnCoates/Aerial#1334]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: 
- [x] macOS version: 
- [x] Monitor setup: 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by sslalani** [comment]
I am not a techie, but I can give you access to my screen if you want to check anything.
1. There is no option to enable Aerial only screensavers in System Preferences
2. Layovers are not appearing any further after the Sonoma update

**Comment by glouel** [comment]
Hey @sslalani 

When you installed Sonoma, you probably tried some of the new "wallpapers" that Apple was providing I guess? They silently disable (my) Aerial when you do that and replace it with their "wallpapers". This is very confusing and not your fault.

Here's the instructions I display now on how to set it up : 

![Capture d’écran 2023-10-03 à 21 55 24](https://github.com/JohnCoates/Aerial/assets/37544189/78acdfb3-10e4-4573-9b38-44df4c4809ce)

Let me know but I'm pretty sure that will fix it for you. 

Also, this is optional, but you may want to install the latest version of the auto updater (called Aerial Companion) here, as it has some important fixes for Sonoma (it's where I display the instructions above now) : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.1

(unzip and replace the one in your `/Applications/` folder)

**Comment by sslalani** [comment]
Thanks a lot!
You are a lifesaver!

**Comment by glouel** [comment]
No problem, this is bound to be a very common issue so I'll pin it so other people can see the solution. Take care!
