### ISSUE TITLE
Overlays for main display are duplicated on 2-monitor setups on Sonoma

### ISSUE THREAD

**Issue by indorock** [JohnCoates/Aerial#1337]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:  Mac Studio M1 Max
- [x] macOS version: Sonoma 14.0
- [x] Monitor setup: 2 x Asus ProArt

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I have the screensaver spanning both screens, with clock overlay on the left (main) screen, and location overlay on the right (secondary) screen. This worked absolutely fine until upgrading to Sonoma.  Now, only the overlay defined for the main display is shown, but on both displays. The overlay for the secondary display is ignored. So, apparently it somehow regards *both* displays as main, however the actual video does properly span across both displays as it always has before.

**Comment by glouel** [comment]
Hey @indorock 

Apple broke screen detection (again) in Sonoma, and while I have a workaround, it's quite possible it's not properly applied to overlays.

I'll have a look tomorrow and will keep you posted!

**Comment by glouel** [comment]
I'll let you confirm but this is fixed in 3.3.3.

**Comment by indorock** [comment]
Works like a charm, thank you @glouel !
