### ISSUE TITLE
No Locations

### ISSUE THREAD

**Issue by mrmagic416** [JohnCoates/Aerial#1343]
Hello - I have tried everything & since the new Mac OS, the location of the videos no longer shows!

**Comment by glouel** [comment]
Hey @mrmagic416 

It's very very likely macOS replaced your default screen saver when you upgraded to their own clone of Aerial. And they hide mine pretty well too 😩

Try this : 
- Go into System Settings > Screen Savers 
- Scroll all the way down to the "Others" section (last one)
- Scroll to the right until you find one called "Aerial" like my screenshot
- Select it and it should say "Aerial" on top of the window. 
![Capture d’écran 2023-11-06 à 00 55 01](https://github.com/JohnCoates/Aerial/assets/37544189/476bf5f5-6f8f-4d18-9f32-98e0ba855786)

Then you'll get back the locations and everything else.

**Comment by glouel** [comment]
Closing this, reopen if it didn't fix for you.
