### ISSUE TITLE
Overlays on main screen only

### ISSUE THREAD

**Issue by Sandor-olah** [JohnCoates/Aerial#1344]
#### Description of issue / Feature request

I'm using Aerial 3.3.1 on Mac Sonoma 14.2 with two monitors, main screen is an LG Ultrafine, secondary monitor is an LG HDR 4K in vertical orientation. I will show a message only on the main screen. It seems to be not possible. The message shows on both screens. All overlays shows on both monitors. But I can choose the secondary monitor only and this setting working well.

**Comment by glouel** [comment]
@Sandor-olah please update to latest version, there's a fix for this issue : https://github.com/JohnCoates/Aerial/releases/tag/v3.3.4

**Comment by Sandor-olah** [comment]
Thank you, problem solved.
