### ISSUE TITLE
Videos not spanned across screens

### ISSUE THREAD

**Issue by WetTiger** [JohnCoates/Aerial#1345]
#### General troubleshooting tips

Before logging an issue please check that:
- [**Check**] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [**Check**] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- **[Check]** Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Air M1
- [x] macOS version: 14
- [x] Monitor setup: 1 external, USB-C

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

**The videos are not shown as spanned across the screens, although the settings are correct in the Aerial settings.
Any way to fix this?**

**Comment by glouel** [comment]
Please make sure : 
- you are running Aerial 3.3.4 (latest)
- you actually have Aerial selected as your screen saver for all screens, and not Apple's own implementation that doesn't support spanning : 
![Capture d’écran 2023-11-06 à 00 55 01](https://github.com/JohnCoates/Aerial/assets/37544189/2ad130ec-831e-434a-807a-10c3e361c567)
- On that same screen, make sure that "show on all spaces/screens" is checked top right too

Apple does silently disable your selected screen saver on upgrade to Sonoma, so it's very likely you are not running mine.

**Comment by glouel** [comment]
Thanks for your quick follow up !

Can you go into System Settings, displays, and make a screenshot of how you have aligned your screens ? 

The only thing I can think of is you have a less than 50% vertical overlap between displays, there's a discussion here that you may be interested in, it might be what you are experiencing ? 

https://github.com/JohnCoates/Aerial/issues/1305#issuecomment-1759995980

macOS Sonoma completely broke multi monitor support, we do have a "decent" workaround but as we found out recently, there are some edge cases where it still fails. Apple did ping me about that bug - somehow - so maybe they'll ultimately fix the root issue. 

In any case, let me know about your alignment, there might be something I can glean from it, there also could be another edge case we haven't encountered yet for our workaround.

**Comment by WetTiger** [comment]
<img width="572" alt="image" src="https://github.com/JohnCoates/Aerial/assets/76124896/9831bf21-cc99-4dbd-a049-9fb9cf366e12">

**Comment by WetTiger** [comment]
Since they are on top of each other, I guess the vertical alignment is 0 :D
This setup did work with previous versions though.

**Comment by glouel** [comment]
I'll try to test it and let you know ! 

This was a fine setup under macOS 13 but macOS 14 broke everything again, so, yeah, annoying. I'll try to get back to you asap.

**Comment by WetTiger** [comment]
Thank you! And no rush, I'll use "cloned" for now.

**Comment by glouel** [comment]
Can confirm your configuration trips up whatever mess they made in legacyScreenSaver. I reported it to Apple again...

I may have a workaround for "simple" cases like yours when both screens have a different resolution in the meantime, I'll get back to you!

**Comment by glouel** [comment]
@anthonybaldaccini follow the steps here : https://github.com/JohnCoates/Aerial/issues/1334#issuecomment-1745634041

This should fix it, it's probably not enabled and you're using the sonoma thing.
