### ISSUE TITLE
Videos from a local folder are not being shuffled 

### ISSUE THREAD

**Issue by Piipperi** [JohnCoates/Aerial#1347]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Mac mini 2018
- [x] macOS version: 14.1.1 (23B81)
- [x] Monitor setup: Two monitors, one 1920x1080 and one 2560x1440

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Videos from a local folder don't get shuffled/randomized. The video the screensaver starts with is always the same one.

**Comment by glouel** [comment]
Hi @Piipperi 

Can you 
- go into Aerial's Settings, Advanced tab, scroll down, enable logs
- launch the screen saver 3 or 4 times (launch, wait for say 10 seconds, exit, wait a bit, relaunch etc)
- go back to same place in Aerial's settings and attach the AerialLog.txt here 

Thanks, this will let me have a look at what's happening precisely

**Comment by Piipperi** [comment]
For some reason it works now, I had to switch a few times between the locations and now it's randomized like it should.

**Comment by glouel** [comment]
No worries, let me know if it happens again, sometimes it's just random luck. Take care.
