### ISSUE TITLE
Can't delete

### ISSUE THREAD

**Issue by dazidnet** [JohnCoates/Aerial#135]
I right click on the screensaver in System Preferences and click "delete" but nothing happens. (I'm trying to do this to be able to install a newer version.)

**Comment by chrislowthian** [comment]
@dazidnet On your desktop press [CMD] + [SHIFT] + [G] and enter the following:

<pre>/Library/Screen Savers/</pre>

You should be able to manually delete the Aerial Screensaver from there.

**Comment by dazidnet** [comment]
This worked, thanks!

-David
