### ISSUE TITLE
com.glouel.AerialUpdater running 24/7 as per screentime even after uninstalling.

### ISSUE THREAD

**Issue by anirudhgray** [JohnCoates/Aerial#1351]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MBP M1 Pro
- [x] macOS version: Sonoma 14.1.1
- [x] Monitor setup: 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I uninstalled Aerial a couple days ago after installing to check it out. However, for some reason, "com.glouel.AerialUpdater" seems to be running 24/7 as per my ScreenTime. This is really concerning as I cannot find this process in Activity Monitor.

<img width="489" alt="image" src="https://github.com/JohnCoates/Aerial/assets/91245420/916867b0-0a5f-4829-915f-7581038752bd">

**Comment by glouel** [comment]
@anirudhgray sorry I missed your thread this week end, can you check in /Applications for AerialCompanion.app ? This is what you need to remove. It's the background updater and depending how you configured it, it's running all the time in your menu bar. 

![Capture d’écran 2023-12-04 à 17 09 47](https://github.com/JohnCoates/Aerial/assets/37544189/eedcff37-61fa-4a11-8bf2-2ae09b044bf2)

It looks like this in your menu bar too : 

![Capture d’écran 2023-12-04 à 17 10 35](https://github.com/JohnCoates/Aerial/assets/37544189/8e3d7f21-9d25-485f-a190-abda80e416cd)

Remove AerialCompanion.app and that will fix it.
