### ISSUE TITLE
Lean Version

### ISSUE THREAD

**Issue by paulmoons** [JohnCoates/Aerial#1356]
This software used to be great when it did one job. 

Unfortunately it is now trying to do so many things, using so many resources that it's just a bloated mess. Is it possible to create a slimmed down version of Aerial which just plays back videos. No background "companion" apps. No downloading or promoting other people's videos.

Just select a folder of videos and play it as a screen saver. No more. No less.

**Comment by glouel** [comment]
> Just select a folder of videos and play it as a screen saver. No more. No less.

This has never been what Aerial is about. You're thinking of "Save Hollywood".

All the other features are optional, including the companion app. You may not like them, other people do.

**Comment by paulmoons** [comment]
Aerial used to be so good but now its bloatware. 🤷‍♂️

And yes but "Save Hollywood" is dead and is no longer functional in Sonoma. Some people suggest installing Aerial to do its job but the bloat precludes it, hence my suggestion for a _lighter_ version.

**Comment by glouel** [comment]
You've already insulted my work on christmas day. 

You've wasted enough of my time. Don't post here again.

**Comment by paulmoons** [comment]
Sorry mate.. was just making a suggestion and expressing an opinion.. didn't mean to offend. 🤷‍♂️
