### ISSUE TITLE
Can I pre-download video files?

### ISSUE THREAD

**Issue by RYOHOI** [JohnCoates/Aerial#136]
I have a very slow bandwidth, can I pre-download video files?

**Comment by pritpalspall** [comment]
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-2.mov
            "accessibilityLabel" : "London",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-3.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-4.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-1.mov
            "accessibilityLabel" : "China",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-2.mov
            "accessibilityLabel" : "Hawaii"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-3.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-4.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b3-1.mov
            "accessibilityLabel" : "London",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b3-2.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b3-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"
    
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-2.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b5-1.mov
            "accessibilityLabel" : "China",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b5-2.mov
            "accessibilityLabel" : "London",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b5-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-1.mov
            "accessibilityLabel" : "China",
            "timeOfDay" : "day"
    
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-2.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-3.mov
            "accessibilityLabel" : "London",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-4.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b7-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b7-2.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "day"
 
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b7-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b10-4.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b8-2.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b8-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b9-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b9-2.mov
            "accessibilityLabel" : "London",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b9-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b10-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b10-2.mov
            "accessibilityLabel" : "New York City",
            "timeOfDay" : "night"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b10-3.mov
            "accessibilityLabel" : "San Francisco",
            "timeOfDay" : "day"

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b8-1.mov
            "accessibilityLabel" : "Hawaii",
            "timeOfDay" : "night"

**Comment by RYOHOI** [comment]
٩( ºдº)و   many thx !!

**Comment by utack** [comment]
Seems like this issue should be closed?
Download is working now
