### ISSUE TITLE
Sonoma OCLP Green video thumbnails.

### ISSUE THREAD

**Issue by InDoubt** [JohnCoates/Aerial#1362]
iMac
Retina 5K, 27-inch, Late 2015
3.2 GHz Quad-Core Intel Core i5
AMD Radeon R9 M380 2 GB
32 GB 1867 MHz DDR3
Sonoma 14.3 (23D56)
27-inch (5120 × 2880) Built in
OCLP 1.3.0

Ever since installed Sonoma, videos thumbnails are green.
They show up in Finder and Photos.
Gifs thumbnails are also rendered green in Finder, Photos and some apps like WhatsApp.

Any work around this issue?
Thank you!

**Comment by InDoubt** [comment]
added pics:
![Screenshot 2024-02-16 at 10 51 27 AM](https://github.com/JohnCoates/Aerial/assets/17437998/b82447a7-b8e9-4217-9f71-bbe7e6520322)
![Screenshot 2024-02-16 at 10 53 19 AM](https://github.com/JohnCoates/Aerial/assets/17437998/648e66b5-d8fa-4a0c-a309-9620428afed4)
![Screenshot 2024-02-16 at 10 54 59 AM](https://github.com/JohnCoates/Aerial/assets/17437998/6b80dcd5-8344-4f9f-89e6-8f9d302ab268)
![Screenshot 2024-02-16 at 11 32 03 AM](https://github.com/JohnCoates/Aerial/assets/17437998/569d7b95-e9f9-4549-a012-b1b1e97d9512)
![Screenshot 2024-02-16 at 11 33 19 AM](https://github.com/JohnCoates/Aerial/assets/17437998/41b6f302-c113-4ade-9e37-eaa64971f761)

**Comment by glouel** [comment]
@InDoubt you are in the wrong repository, you need to ask the OLCP people : https://github.com/dortania/OpenCore-Legacy-Patcher/issues 

I have no idea about this, sorry !

**Comment by InDoubt** [comment]
Nothing to be sorry about
It was my complete fault.
Didn't pay attention to where I was posting.
Sometimes this place seems to my complicated.
If you could please delete the whole thing I wilL appreciate it.
Thank you!
I'm sorry!

**Comment by InDoubt** [comment]
![Screenshot 2024-02-16 at 11 58 03 AM](https://github.com/JohnCoates/Aerial/assets/17437998/f683cc85-567d-49de-bc48-ca35a66ff7ac)

Whatever!

**Comment by glouel** [comment]
Can't delete but it's closed, no worries. You'll have to go to their discord for support, see here  : https://github.com/dortania/OpenCore-Legacy-Patcher/issues/985

**Comment by glouel** [comment]
Use this link to go to their discord, it's from the link I posted above : https://discord.gg/rqdPgH8xSN

**Comment by InDoubt** [comment]
Thank you again!
Unfortunately I don't think on discord for this business
My experience there it's been negative
People is rude, dismissive, incoherent, don't know how to write and change the subject frequently!
I looked anyway and there are several people with the issue but no answer to the problem since last post on Oct 2023.
Thank you, again for sympathizing with my issue.
Cheers!
