### ISSUE TITLE
Black screens continued.

### ISSUE THREAD

**Issue by RGM1956** [JohnCoates/Aerial#1364]
After all of these many months why is this, HOW is this, still an issue?
2021 24" iMac
macOS 14.4
Aerial 3.3.7
Aerial companion 1.5.2

![IMG_0120](https://github.com/JohnCoates/Aerial/assets/145586318/3d0496b6-4a91-41da-b487-888ada2c9b11)

**Comment by RGM1956** [comment]
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/14895130/AerialLog.txt)


This problem is sporadic.  I suspect a bad video in the collection.

**Comment by RGM1956** [comment]
I can’t do it any other way. If I touch the keyboard or mouse in any way the system responds and the screensaver stops. There is no way around that.  That means I can’t take screenshots etc. without waking the system and ending the screensaver. I can try what you suggest as time permits, but that is likely to take weeks since I normally have a very full plate.As far as the videos. I bought all the Jetson packs as well as the other one’s available on the aerial site.  Can you not test all the videos on your site,I cannot buy the corrupted download theory since (for completely different reasons) I have scrubbed the SSD and laid down a fresh configuration with all freshly downloaded software including all the videos available for Aerial.The issue, from my perspective, is coming from your end, especially since it appears that I am far from the only person reporting the issue. On Apr 7, 2024, at 5:52 AM, Guillaume Louel ***@***.***> wrote:﻿
@RGM1956
Looks like your log was enabled after you took that picture. The times start after the 15:11 from your screenshot, and your log starts a couple minutes after, so that's not going to tell us much, sadly.
That said, this definitely looks like a corrupted video yes. This is not the "classic" Sonoma bug at all. From that screenshot you posted, it's clearly something else.
Couple of things from your log :
2024-04-06 15:34:03.384 : 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨 Could not open manifest for source at file:///Users/ricmelton/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/Catalina%20Air/

Looks like you have something weird in your Catalina Air pack. Might be a missing manifest (each folder should have an entries.json and a manifest.json file). I'm not sure that's the core issue though, it's more likely those video if there are any aren't shown at all, but who knows.
First, open Aerial Settings then "More videos". If you can make a screenshot after resizing the window, so all the entries are shown on the list, then I can have a look.
Second, go to "Cache" and press show in Finder (you'll have to open Aerial's settings from System Settings). This will open the regular Cache.
In general Aerial will not save incomplete downloads, but there might be some weird case where the file was corrupted on server, or some server was down somewhere, and it saved a 0/few bytes file.
So what you are looking for is 0 bytes, suspiciously small files (< 1MB). In the Cache folder you opened in Finder, sort by size, and look at the smallest ones. Let me know their size, if they are suspiciously small, move them away (don't delete them, and post their name/size here).
Then go up a level in Finder, and for each of your downloaded pack, do the same thing. If you find any suspiciously small file, put them aside and let me know which ones they are. In general the packs videos are much smaller as they are better compressed, you're looking for anything < 1MB, or anything where Finder doesn't show the preview correctly.
Lastly, let me know what's in your Catalina Air folder, because something is wrong here too.

**Comment by RGM1956** [comment]
One other thing.

If you look at the photo I included in my latest post, you will see that the lower right-hand corner is blank.  The video location is displayed there WHEN a video is playing.  No video, no description.  
The selected video is simply not playing or something else (code-wise) is happening.


￼

**Comment by RGM1956** [comment]
This is normal…

￼

This is not…

￼

**Comment by glouel** [comment]
> I can’t do it any other way. If I touch the keyboard or mouse in any way the system responds and the screensaver stops. There is no way around that.  

Where did I ask you do take a screenshot of the screensaver ? I only asked you for screenshots of your settings. Your log starts two minutes after your picture, which means you either trimmed it manually, or you enabled the logging afterwards. 

> Can you not test all the videos on your site, I cannot buy the corrupted download theory 

The videos don't "come from me". Some come from Apple, some from Jetson. Those are their servers, not mine. I have no control on them. I just make the client. Server issues happen for many reasons. Feel free to believe what you want. 

> I am far from the only person reporting the issue. 

That precise issue ? You are the first as far as I know. The common Sonoma black screen issue is about the screensaver not starting at all because of a macOS bug. 

>If you look at the photo I included in my latest post, you will see that the lower right-hand corner is blank.  The video location is displayed there WHEN a video is playing.  No video, no description. The selected video is simply not playing or something else (code-wise) is happening.

Please give me the log with the time it happens, or follow the instructions I gave you. 

(and you can't post pictures by email, use github).

**Comment by RGM1956** [comment]
I cannot get the log or do anything on the system without deactivating the screensaver (to get logs or anything else, like take a screenshot). 

My screenshot verbiage was just an example.  That is why the date of the photo and log files don’t match.  

That was my point. And there is no way around it.

I have seen many, postings about black/blank screens on your site with regards to Aerial screensavers after the release of Sonoma.

And if you partner with other people or companies then perhaps you should be dealing with them to find the issue.  Why Are consumers always left holding the bag?

I have a simple solution, uninstall Aeria; screensavers and file it under “hopeless”.  I have far more important things to do with my time.

**Comment by RGM1956** [comment]
By the way, Github complains about the size of of my screenshots and will not post them hence the e-mailed photos.

This has become a rat’s nest and major pain in the ass.

**Comment by glouel** [comment]
> I cannot get the log or do anything on the system without deactivating the screensaver (to get logs or anything else, like take a screenshot).

You don't need a screenshot. If you enable the logs, they will contain the last few launches. What I'm asking for is when you see a black screen as you describe, note the exact time it happens, get the log afterwards and give me both (time + log). Otherwise I can't infer what is happening from a random log.

> I have seen many, postings about black/blank screens on your site with regards to Aerial screensavers after the release of Sonoma.

As I've tried to explain a few times, the issue you are experiencing is pretty specific, and not the same. 

> Why Are consumers always left holding the bag? I have a simple solution, uninstall Aeria; screensavers and file it under “hopeless”. I have far more important things to do with my time.

Ok this is an open source project, available for free. I'm doing this on my free time. I'm trying to give you assistance, on a sunday, and you are being needlessly rude to me while I'm trying to help. 

If you want my help, either work with me and look for the small files as I asked, or feel free to uninstall and close this issue. 

> By the way, Github complains about the size of of my screenshots and will not post them hence the e-mailed photos.

As I said, that doesn't work, nothing shows up. 

> This has become a rat’s nest and major pain in the ass.

See above.

**Comment by RGM1956** [comment]
Then recreate the problem on one of your systems, talk to Josh at Jetson labs or whoever else provides videos for Aerial and work with them to fix the problem and…

 ...Just FIX IT!

I was done as soon as you started showing a snippy attitude.  “…When did I…”.  I am done with your and your software (a once good software turned to crap.

Goodbye.
