### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by igor9silva** [JohnCoates/Aerial#137]
Any chance we're having Linux support?

**Comment by iberianpig** [comment]
:+1:

**Comment by passcod** [comment]
Aerial can already be done in Linux with standard software and a tiny bit of configuration. See this for example: https://gist.github.com/Dhertz/9dd69eaad092d0c0fe96

**Comment by alistairmcmillan** [comment]
And there is a pull request to point to someone else's implementation... #191

**Comment by tsteuwer** [comment]
:+1:
