### ISSUE TITLE
Ignore Energy Saver Display Sleep

### ISSUE THREAD

**Issue by cucocreative** [JohnCoates/Aerial#138]
When I am running the screen saver it seems to ignore the Energy Saver Display Sleep setting, I have the screen saver turn on after 5min and the display to go to sleep after 15min, but the display never goes to sleep.

**Comment by scsskid** [comment]
I can confirm this

**Comment by vinceangeloni** [comment]
Same here, have had it go for hours not realizing it.

**Comment by alistairmcmillan** [comment]
@cucocreative @scsskid @vinceangeloni Which versions are you running?

**Comment by cucocreative** [comment]
@alistairmcmillan  v1.1 on Yosemite

**Comment by alistairmcmillan** [comment]
@cucocreative Try the latest beta. John made a change in one of the betas to resolve this issue.

**Comment by cucocreative** [comment]
Yes, that has fixed it

**Comment by leo** [comment]
Can confirm that this has been fixed! => Close this issue.

**Comment by alistairmcmillan** [comment]
@cucocreative You can close this issue if you are happy that the problem is resolved.

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by Markyt1977** [comment]
mark tegeda
