### ISSUE TITLE
No videos available

### ISSUE THREAD

**Issue by ianrobertdouglas** [JohnCoates/Aerial#1381]
MBP M3 Max
Macos Sequoia 15.0.1
3 connected monitors (1x HDMI, and 2x Thunderbolt Displays)
All connections for Aerial allowed under Little Snitch

I have lost all access to videos within the Aerials preferences. Nothing downloaded appears there. Doesn't matter if I cycle through Everything, Favorites, Time, Scene, etc. I basically cannot choose any video, because nothing appears.

I tried Reset All Settings. Made no difference. I re-downloaded the latest Aerial and reinstalled, and it made no difference.

Secondarily, how can Aerial be removed entirely from my machine, including any cruft? Is it as simple as System Settings / Screensaver and right click Delete on Aerial? Will that also remove other components?

**Comment by ianrobertdouglas** [comment]
Despite all connections being open in Little Snitch, my Little Snitch config appears to have been corrupted. Re-installing eventually triggered a notification of an outgoing connection, which I always allowed, and the videos have reappeared.

**Comment by Kikangh** [comment]
Did you update little snitch after upgrading to Sequoia ? Little Snitch will often (I not always) require to be updated after an OS upgrade to function properly.

Cordialement,

Gilles Hemard
