### ISSUE TITLE
Screen saver preview not working

### ISSUE THREAD

**Issue by camdendevelopers** [JohnCoates/Aerial#14]
Hello Aerial team,

I have noticed that the screen saver preview and the actual screen saver does not load. Both of them start up on my screen with the initial frame of a city but won't start even after a couple of minutes. I am running El Capitan. I hope this helps!

**Comment by alistairmcmillan** [comment]
@camdendevelopers Did you get this working?

**Comment by alistairmcmillan** [comment]
No reply for months, closing.
