### ISSUE TITLE
Display won't goto sleep if aerial screensaver is in use

### ISSUE THREAD

**Issue by qsub** [JohnCoates/Aerial#140]
It appears it doesn't allow the display to go into sleep\standby if the aerial screensaver is active.

Example: In Energy Saver, I have Computer Sleep set to Never and Display Sleep set to 15mins. After 15mins, the screen should go into standby\black but instead it stays active with the aerial screensaver.

**Comment by qsub** [comment]
duplicate.

**Comment by JohnCoates** [comment]
Try the latest beta release https://github.com/JohnCoates/Aerial/releases
