### ISSUE TITLE
Just For that who couldnt play screensaver 

### ISSUE THREAD

**Issue by bao3** [JohnCoates/Aerial#141]
ONLY Support version 1.2 beta4 ( https://github.com/JohnCoates/Aerial/releases ) ,please install beta version and read bellow.

I installed this screensaver but it show black screen ,and I found it could not download the necessary .MOV files .So I just manually download and put in  ~/Library/Caches/Aerial/ . If you wanna do the same thing, review the url bellow:

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

download all the .mov files to ~/Library/Caches/Aerial/ , but keep the files' name DO NOT rename them.

good luck

**Comment by BrysovVadik** [comment]
In this place there's no Aerial folder. I created it myself. Put there two video.In settings chose these two videos. Still only a black screen.

**Comment by bao3** [comment]
@BrysovVadik  install beta version ( v1.2 beta4 ) , look here https://github.com/JohnCoates/Aerial/releases

**Comment by BrysovVadik** [comment]
Very much thankful to you. Works perfectly!

**Comment by suclogger** [comment]
@BrysovVadik Thanks for the links.
@bao3 There are still connection problems from China.By pre-downloading the video file above,the cache function helps a lot! Thanks.
