### ISSUE TITLE
Didn't see 1.2 features in latest beta release

### ISSUE THREAD

**Issue by siyuanchu** [JohnCoates/Aerial#142]
I downloaded the latest beta 4 version of 1.2 Aerial and installed in my retina Macbook pro with 10.11.1 OS X. But I still have black screen problem, and no continuous playing, no offline mode, no cached file after playing and more. Did I install the right version? I cannot attach the saver file in this issue, please check the compatibility with 10.11.1 or check the version release seed! I really love this set of screensaver and really appreciate the work you have done. I will keep my ones on your project and try my best to help you test the features and suggest new features.

Since I'm not a coding guy so maybe i cannot help you with the coding part, I just want to suggest some features, like one-click caching, sync play along time period, etc..

Thank you for bringing the great piece of applet!

**Comment by JohnCoates** [comment]
I'm on 10.11.1 and it's working for me. It sounds like there's some firewall issue.

Try the latest release (1.2 beta 5 as of writing) https://github.com/JohnCoates/Aerial/releases
In preferences, go to the cache tab and hit Download Now and see if you get any errors

**Comment by siyuanchu** [comment]
I have cached them manually by the methods from another thread. Thanks for the help and the new release!

Btw how can I install the latest version of the screensaver if you release new features? I just downloaded the new saver file and install it but it appears as a new saver not a replacement in the system preferences.

**Comment by alistairmcmillan** [comment]
@siyuanchu If this is still an issue, there are two locations that you can install the screensaver. `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers`. Perhaps you have a copy installed in each.
