### ISSUE TITLE
Not offline loading

### ISSUE THREAD

**Issue by vol85** [JohnCoates/Aerial#143]
I can't loading the screensaver without internet connection.

I have installed 1.2 beta 4.

no problem with or without little snitch active or not.

**Comment by JohnCoates** [comment]
You might not have had any videos cached?

Try the latest release (1.2 beta 5 as of writing) https://github.com/JohnCoates/Aerial/releases
In preferences, go to the cache tab and hit Download Now

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by vol85** [comment]
perfect!!!

**Comment by alistairmcmillan** [comment]
Closing as resolved for @vol85
