### ISSUE TITLE
How about an "Open Cache Location" button?

### ISSUE THREAD

**Issue by Fofer** [JohnCoates/Aerial#145]
You know, like a shortcut to get there.  Or just make the displayed path clickable...

**Comment by Markyt1977** [comment]
Mt

mark tegeda
On Nov 6, 2015 4:42 PM, "Fofer" <notifications@github.com> wrote:
>
> You know, like a shortcut to get there. Or just make the displayed path
clickable...

**Comment by mommel** [comment]
Pull request https://github.com/JohnCoates/Aerial/pull/153 could give you that function

**Comment by glouel** [comment]
A Show in Finder button is now available in V1.4.
