### ISSUE TITLE
Can't change Cache Location (version 1.2 Beta 5)

### ISSUE THREAD

**Issue by kerstin** [JohnCoates/Aerial#146]
I just discovered there are Beta versions that let us cache the videos, so I downloaded the Beta 5 to my machine running Yosemite (10.10.5). Unfortunately, clicking "Change Cache Location" doesn't do anything, nor does clicking the displayed path to the cache location (the icons/folder names right above the buttons).

Clicking the 'Change Cache Location' button works fine in Beta 4 on another (older) machine, btw.

My issue might be related to #145 though the user who opened that one wasn't very clear about what their actual issue was.

**Comment by kerstin** [comment]
Related: the default cache location with this version seems to be ```HD/Applications```, which I don't think is suited for downloads like these.

In the Beta 4 it's ```User/Library/Caches/Aerial```, which I find much better (though ```User/Library/Application Support/Aerial``` might also make sense).

**Comment by alistairmcmillan** [comment]
Hi @kerstin , were you able to get the screensaver working?

**Comment by kerstin** [comment]
It was always working for me, I just couldn't change the cache location. I haven't updated the software since, so the situation should be unchanged. Are you asking me to update?

**Comment by alistairmcmillan** [comment]
If it's working for you then no need to change. :) Are you able to change the cache location now?

BTW I'm not sure how it ended up with `/Applications` as the cache location. The default has always been `/Users/YOURUSERNAME/Library/Caches/Aerial`. You can see the code [here](https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Models/Cache/VideoCache.swift#L23).

**Comment by kerstin** [comment]
I had a look, and changing the cache location seems to work now. (:

Dunno what went wrong previously, but also don't know which version I currently have installed (there doesn't seem to be a way to check from within the Screensaver? I don't remember where I put the original files). If it's the same version I have no idea how this problem could have changed without me doing anything about it. :P

The only thing "off" I noticed is that the last letter in "Cache Aerials As They Play" is cut off, as if there were something wrong with some of the elements in that window.

![screen shot 2016-01-29 at 14 04 11](https://cloud.githubusercontent.com/assets/559572/12676436/8cd57a9c-c692-11e5-9d7a-4c3e71da1d9d.png)

**Comment by alistairmcmillan** [comment]
The way screensavers work in OS X has always been a bit weird to me. Cause they just run as plugins. A couple of times when I've updated a screensaver on one of my own Macs it seemed like it was using the UI from the new version but still running the old code. Or vice versa. Very weird. But it might explain some of the strange behaviour people randomly get sometimes.

There is a pull request to [add version numbering to the UI](https://github.com/JohnCoates/Aerial/pull/128). :)

I'll check that NSLabel in the most recent beta when I get home and annoy @JohnCoates with another pull request if it needs extended a little. :)
