### ISSUE TITLE
Wallpaper [feature request]

### ISSUE THREAD

**Issue by Alexey1100** [JohnCoates/Aerial#147]
Hello. Sorry, it may be a stupid question, because I don't know how this thing is work.
But how about such feature which automatically takes the last frame before you exit from the screensaver and sets it as wallpaper? Could it be implemented?

**Comment by The1andONLYdave** [comment]
+1 would really like that too, best with support for https://github.com/JohnCoates/Aerial/issues/256 (choose which and maybe how many screens to run on)

**Comment by NightRaider73** [comment]
@glouel Time to be closed
