### ISSUE TITLE
can't  work

### ISSUE THREAD

**Issue by Andy0731** [JohnCoates/Aerial#148]
i've download all the versions but none can run...my Mac is 10.10.4 Yosemite...what can i do?

**Comment by Andy0731** [comment]
<img width="665" alt="2015-11-07 7 20 24" src="https://cloud.githubusercontent.com/assets/13774935/11014963/1152c3c2-8586-11e5-9d07-d259b653799a.png">
what can i do ?

**Comment by alistairmcmillan** [comment]
@Andy0731 Try the latest beta version.

If you are behind a corporate firewall or proxy they might be blocking you; if it's possible to connect your machine to another network you can cache the videos there with the latest betas.

If you have Little Snitch installed, it might be blocking too.

**Comment by sd4324530** [comment]
@Andy0731 这个屏保的内容是要下载的，而下载地址在天朝是访问不了的，我的解决办法是下载1.2beta5，翻墙后使用这个屏保支持的Cache，把屏保视频缓存到本机，然后就可以用了，不过偶尔还是会出现黑屏，大部分情况是可以使用了
