### ISSUE TITLE
Higher Resolution?

### ISSUE THREAD

**Issue by lllMPower** [JohnCoates/Aerial#15]
Is this available in a crisp 5120x2880 resolution for the iMac 5k? Screen saver looks great, but would be absolutely jaw-dropping in 5k. Thanks!

**Comment by iAlborz** [comment]
These are loaded directly from apple servers. since apple tv only supports 1080p, that's the resolution they provide. there won't be 4k until apple decides tv supports 4k. I doubt about 5k anytime soon.

**Comment by CristianMoisei** [comment]
Kind of sucks that they are only available in 1080p.

**Comment by omar-jalalzada** [comment]
*shakes fist @ apple*

**Comment by simplenotezy** [comment]
+1 I would love this. At least for MBP retina. It does not look as sharp as on apple tv, which is even a bigger screen.

Maybe Apple are now also streaming 4k or retina versions of the screensavers through their API? Worth investigation.

**Comment by mgguinne** [comment]
+1

**Comment by alistairmcmillan** [comment]
Apple create the videos. When they release higher resolutions videos, Aerial will automatically support them.

**Comment by alokdhir** [comment]
This is probably why they haven't added the screensaver to macOS themselves; the videos don't look great on a Mac.
