### ISSUE TITLE
Screensaver is black

### ISSUE THREAD

**Issue by etodac** [JohnCoates/Aerial#151]
Hi there,

I installed Version 1.1 and when I selected Aerial from my Desktop and Screensavers, the preview is black and there were no screensaver options available. I also tried the Beta 5 and it was the same issue. I run OS X El Capitan. Thanks.

Eric

**Comment by chrislowthian** [comment]
Have you been into the Screensaver settings on beta 5 and Cached all the videos?

**Comment by yuanhaoliang** [comment]
you need to wait for a minute.

**Comment by etodac** [comment]
@chrislowthian How do I cache the videos?

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by naffan2014** [comment]
@etodac 他的程序有bug，有时候好有时候坏。他的beta版有cache。我刚装了试了，可以。但是运行的不是很顺利。很多情况是黑屏。如果你cache视频的话，不是全部cache。那么你需要在设置里勾选那些已经下好的视屏。然后才能正常运作。如果你不勾选，他会读到并不存在的视频，因为他每个视频都已经做好了名字，例如b4-2.mov.这是他原先已经自定义的视频名称。 if you don;t understand ,plz translate it into english by google translator

**Comment by alistairmcmillan** [comment]
@etodac Download and install the most recent beta available [here](https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5). Select Aerial and click "Screen Saver Options...". Then select the Cache tab and click the Download button,

If your Mac can connect to Apple's servers it should be able to download and cache the videos.

However if you are behind a proxy or firewall, it may not be able to download them.
