### ISSUE TITLE
El Capitan - OS Crash

### ISSUE THREAD

**Issue by Shagans982** [JohnCoates/Aerial#157]
Just a heads up, this was working fine for me however, I began experiencing some heavy (8-12 a day) OS crashes after installation. While I don't know for sure if this was the culprit, It was the only application I had installed in awhile so I am assuming this is the cause. In addition, I uninstalled and restored the installation and the crashes seems to be fixed. Love the app... just providing my feedback.

**Comment by Jonathan-Rosewood** [comment]
I tried all of Aerial versions on all my machines (mbp, imac, hackintosh) with different OS X versions - all works perfect.
What machine u use?

**Comment by Shagans982** [comment]
Hey Jonathan, I'm using a 2013 Macbook Pro Retina.

**Comment by Shagans982** [comment]
Feel free to close out this issue. I am experiencing the crashes again and Aerial is not installed. My apologies.

**Comment by alistairmcmillan** [comment]
@Shagans982 Hi Stephen, There should be a button below that lets you close this issue.
