### ISSUE TITLE
Screensaver not working

### ISSUE THREAD

**Issue by lars06** [JohnCoates/Aerial#158]
Hi there,

I am running the latest beta. Unfortunately I haven't been able to get the screensaver to work. Everything is fine in settings. I turned on the screensaver and cached all the videos. But if I leave my computer without touching it, the screen just goes black and no screensaver comes up. I am not running Little Snitch (your recommendation from the troubleshooting section). Any thoughts?

Thanks

**Comment by michaelshobbs** [comment]
What was the solution?
