### ISSUE TITLE
Stalls when multiple displays are connected

### ISSUE THREAD

**Issue by mattmischuk** [JohnCoates/Aerial#159]
This can reproduced on a MacBook Pro and a Thunderbolt Display.

OS: 10.11.1
Hardware: Macbook Pro (Retina, 15-inch, Mid 2014)

**Comment by grabber24** [comment]
Are the displays separate pictures or the same showing? Have you checked pixel count on both screens being used if not the same manufacturer on both.

**Comment by mattmischuk** [comment]
@grabber24 It's the same manufacturer they are both Apple products. It plays on both screens the same picture and it freezes after 1s or so.

**Comment by alistairmcmillan** [comment]
Which version are you using? The latest beta allows you to download and cache the videos so they play off your hard drive. Otherwise they are streaming from Apple's servers and the performance of the playback is dependent on your network connection and any proxies/etc sitting between you and Apple.

**Comment by mommel** [comment]
Your guess isn't right, I drive the screensaver on rMBP and 2 Full HD, at home same setup like you. For testing I added a 4k Screen but even then there was no difference. I play on all devices different spaces and it shows most times different videos.
Please check your cached files. Try to play them in a video player.

**Comment by mattmischuk** [comment]
That's the point, the user shouldn't have to mess with cache for the .saver to work.

**Comment by mommel** [comment]
Do the videos from your cache play in a video player? Does it work without your TB Display?

**Comment by alistairmcmillan** [comment]
@mattmischuk Does it play okay if you just try on the Macbook Pro on its own? Just curious cause I'm pretty sure your Macbook should have no issue drawing to both screens. If it still stalls when it is only playing on your Macbook screen alone then there is something else at play here.

**Comment by mattmischuk** [comment]
Yeah, if my second display is not connected it works fine.


Matt Mischuk

**Comment by TomCarey** [comment]
I noticed this issue too, assumed it was a network problem, but all of the videos are now cached and still seeing it stall on a MBP (late 2013) + 2TB. Usually one screen will keep playing while the other two stall or are black (no consistency on which screens though). The videos play just fine when played from Finder.

Also just tried it with screens disconnected and it stalled once out of a few tries. So I'm guessing this may not be to do with the extra displays, except that they make it easier to see the issue.

**Comment by mommel** [comment]
Start it in X-/AppCode and lookup the error message, there should be some errors in the log.

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by NightRaider73** [comment]
@glouel Close this it is fixed in 1.4.2

**Comment by glouel** [comment]
Indeed thanks !
