### ISSUE TITLE
Does't work on 15inch macbook pro

### ISSUE THREAD

**Issue by troy351** [JohnCoates/Aerial#16]
I'm using a 15inch macbook pro(mid 2015) with OS X 10.11.  And when I launch the screen saver, I just saw a black screen with nothing.  Hope to fix it :)

**Comment by rubenverboon** [comment]
I have the same issue, only this issue is only present when I do not have a scaled resolution.

I prefer to use a more space resolution, and then the screensaver does not work.

It does work when I put the screen on default resolution.

**Comment by troy351** [comment]
I just use the default resolution, still not work

**Comment by troy351** [comment]
I use the hot corner to launch the screen saver. When I launch it, the screen seems to be pure black.  After a short period of time, when I need password to return to the desktop. I clicked 'X' to cancel it and back to the screen saver. Strange thing happened, it just works! And I don't know why. ( poor English :( )

**Comment by morismoris** [comment]
Error on console:
<<<< AVPlayer >>>> -[AVPlayer outputContext]: No figPlayer found, cannot set picker id
 <<<< AVPlayer >>>> -[AVPlayer setOutputContext:]: No figPlayer found, cannot set picker id

**Comment by mrapplegate** [comment]
I have the same issue. I get a black screen when I try to run on a 15 inch MacBook Pro
Here is the error I'm seeing in the system log
Oct 27 12:37:02 selma5 ScreenSaverEngine[17116]: [12:37:02.674] <<<< AVPlayer >>>> -[AVPlayer setOutputContext:]: No figPlayer found, cannot set picker id

**Comment by coreyallen** [comment]
I too have a 15 inch MBP and while the preview works, I get a circle with a line though it when the actual screensaver starts.

**Comment by mrapplegate** [comment]
Mine is working now. I noticed in another thread about Little Snitch blocking it, so I checked and it was blocked. I made a rule to allow it and now it works fine.

**Comment by joshnh** [comment]
I have a mid 2015 15" MacBook Pro running 10.11.1 and am not having any issues at all.

**Comment by troy351** [comment]
Maybe the network problem cause the issue

**Comment by alistairmcmillan** [comment]
If any of you are still having issues, make sure you are running the latest version, try caching the videos and make sure the screen saver isn't being blocked by a firewall or proxy (like Little Snitch for example).
