### ISSUE TITLE
How to delete

### ISSUE THREAD

**Issue by hellonearth9** [JohnCoates/Aerial#160]
I apologize for the stupid question but right-clicking and selecting "Delete Aerial" inside the screensaver preferences does not work. The only reason I want to delete it is because I have two versions,one being the latest beta and I can't tell which is which. Thanks for your help and thanks so much for creating this.
-Running Yosemite 10.10.5, 2012 Mac Mini

Ryan

**Comment by alistairmcmillan** [comment]
The screensaver will either be in `/Users/YOURUSERNAME/Library/Screen Savers` or `/Library/Screen Savers`. You can just delete it from there and it'll disappear from System Preferences.

**Comment by tnViking** [comment]
Please close this issue if you've solved your problem.

**Comment by alistairmcmillan** [comment]
Hi @hellonearth9,

Did you manage to uninstall the screensaver?

**Comment by alistairmcmillan** [comment]
Waited months, no reply, so closing.
