### ISSUE TITLE
Live Wallpaper for Mac not running.

### ISSUE THREAD

**Issue by walda23** [JohnCoates/Aerial#163]
Installed this in Macbook Pro 13” i5 w/8GB ram and El Capitan, 2012 model. When opening the screensaver, it won’t move on the screen. Any suggestions?

Minimum Reqs?

Something not enabled maybe?

David Walker

**Comment by alistairmcmillan** [comment]
Which version did you install? Did you try the latest beta? Are you behind a firewall or proxy?

**Comment by alistairmcmillan** [comment]
@walda23 Did you get the screensaver running on your Macbook?

**Comment by alistairmcmillan** [comment]
Waited months, no reply, so closing.
