### ISSUE TITLE
Works great in preview, black screen as a screensaver

### ISSUE THREAD

**Issue by seajay1221** [JohnCoates/Aerial#165]
Not sure what else to say. This seems to work and is just fine in preview mode, but when starting the screen saver via hot corners and with the timer it just shows a black screen. Tried all of the different options for the screensaver independently, so it's definitely not just one city's day or night mode messing it up.

This is on a 13" 2013 rMBP.

**Comment by alistairmcmillan** [comment]
Which version are you running? And if you're not running the latest beta could you try it and see if caching the videos helps? :)

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by nonissue** [comment]
I had the same issue, but installing the latest beta and enabling caching resolved it!

**Comment by alistairmcmillan** [comment]
@seajay1221 Did you get the screensaver running?

**Comment by michaelshobbs** [comment]
Same issue for me. Tried the v1.2beta5 with caching on and even downloaded all the videos. Works in preview but black screen otherwise.

**Comment by michaelshobbs** [comment]
Scratch that. I'm a moron. My hot corner was set to put my display to sleep. Works after I pulled my head out of my backside ;P

**Comment by alistairmcmillan** [comment]
Glad it's working for you @michaelshobbs 

Waited months but no reply from OP, so closing.
