### ISSUE TITLE
Not working on a closed network

### ISSUE THREAD

**Issue by aymanaltounji** [JohnCoates/Aerial#169]
Hi,

I installed Aerial on my MAC El Capitan and I love it. 
I have a weird issue, where it does not work on a restricted network at work, it take timer to get an image and then not video just an image. I don't know what the network has to do with screen saver, and I tried reinstalling and manual placing the file in the screen saver library with no luck. When I go back home, it works normal

Any thoughts?

Thanks

Ayman

**Comment by fletch247** [comment]
hi,
the screensaver streams the videos through the web from apple servers.
it has a cache function in the latest version that downloads the videos to your computer so the saver will also work offline.
take care, the download of the videos is more than 5gb.
all this is also written in the documentation.
cheers.

**Comment by aymanaltounji** [comment]
Thanks,

I download the latest version, but how does it download the videos, do I let it run, do I need to trigger anything, or is it in the background.

Thanks again, 

Ayman

**Comment by fletch247** [comment]
hi, it's easy, just check out the settings of the screen saver, it's kind of self explaining.
implemented since 1.2beta4, latest is 1.2beta5.
also it's all written in the readme file.
best regards.

**Comment by alistairmcmillan** [comment]
@aymanaltounji Did you get the screensaver working?

**Comment by aymanaltounji** [comment]
Yes

Ayman

**Comment by alistairmcmillan** [comment]
Cool. Glad to hear it. :)
