### ISSUE TITLE
Other platforms?

### ISSUE THREAD

**Issue by RuggedBrother** [JohnCoates/Aerial#17]
Can someone alter these files and maybe make them available for the iPhone/iPad ? 
Maybe a jailbreak developer could package it as a tweak? 

Battery drainer or not. I'm surely not the only one praying for this?

**Comment by dubstrike** [comment]
@RuggedBrother Seeing as the iPhone 6s has received Live Wallpapers in iOS 9, something could be made out of these videos.

**Comment by RuggedBrother** [comment]
I just hope they're not copywritten. 
I've posted the idea on Reddit in the form of a request. 
I also reached out to avfew developers via Cydia. 
I honestly don't think there's much else I can do, just hope word of mouth spreads.

**Comment by alistairmcmillan** [comment]
As mentioned in #134 @sharpguy101 would like a version for Amazon Fire TV.
