### ISSUE TITLE
Prevents display from turning off?

### ISSUE THREAD

**Issue by dutton242** [JohnCoates/Aerial#170]
Hi there, awesome project it's just beautiful! Though I've noticed it seems my display won't turn off at the normal time when I've got this running? Have others had this issue too? I'll continue to test, but is this a bug? Thanks!

Marc
OS X 10.11.1

**Comment by ashchristopher** [comment]
@dutton242 Try using the latest beta release - it is fixed there for me.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by dutton242** [comment]
@ashchristopher that seemed to have fixed it, thanks!

**Comment by alistairmcmillan** [comment]
@dutton242 If you're happy you can close this issue.
