### ISSUE TITLE
Video on screensaver plays for a second and then stops

### ISSUE THREAD

**Issue by rmarkiv** [JohnCoates/Aerial#172]

**Comment by raghvendra-iiita-work** [comment]
I experienced the same issue and this happens even in preview mode

**Comment by alistairmcmillan** [comment]
@markiv @raghvendra-iiita-work Which versions are you running? Are you running the latest beta?

**Comment by 123marvin123** [comment]
I got the same issue, I'm using 1.2 Beta 5 (but it was already in 1.2 Beta 1)

**Comment by carlosefonseca** [comment]
Was happening on the version i had installed, updated to the beta 5 and still happens… :( I have the cache disabled but i'm gonna try set it on an external drive and download the files and see if it still freezes…

**Comment by angeloski** [comment]
I'm also having this issue. Tried 1.2 Beta 5, but it is there also.

**Comment by carlosefonseca** [comment]
I "fixed" it by manually caching all videos.

**Comment by raghvendra-iiita-work** [comment]
I am using latest stable. I tried using beta version also, faced the same issue.

**Comment by alistairmcmillan** [comment]
@raghvendra-iiita-work Did you try caching the videos?

**Comment by Colir** [comment]
Same issue here.
@alistairmcmillan how ?

**Comment by alistairmcmillan** [comment]
* Download and install the [latest version](https://github.com/JohnCoates/Aerial/releases).
* Open System Preferences
* Click Desktop & Screensaver
* Select Aerial and click "Screen Saver Options..."
* Select the Cache pane and tick the "Cache Aerials As They Play" box.
* Finally click "Download Now"

<img width="780" alt="screenshot 2015-12-14 21 25 07" src="https://cloud.githubusercontent.com/assets/125896/12042393/9acc51e4-ae72-11e5-8f0f-ab0bc099e1c9.png">

**Comment by alistairmcmillan** [comment]
@Colir @raghvendra-iiita-work @carlosefonseca @angeloski @123marvin123 @rmarkiv Did you get the screensaver running?

**Comment by alexcurtin** [comment]
I am experiencing this issue with the latest release and even after caching all the videos. I am on OSX 10.11.3 using latest build.

**Comment by grahamj** [comment]
I believe I'm seeing the same problem with beta5 on 10.11.6 with all files cached.

I have a hot corner set up and when I activate it the screensaver exits most of the time. When it does play it's usually not for very long.

**Comment by glouel** [comment]
There's better caching option in 1.4 now. Also, you may experience slowdowns because of iCloud Photos activity, please reopen if you still have issues with 1.4
