### ISSUE TITLE
Retina MacBook Pro 15" 2014 running hot under 10.11.

### ISSUE THREAD

**Issue by ahenker** [JohnCoates/Aerial#173]
Retina MacBook Pro 15" 2014 running hot under 10.11. 

Is there a possibility to reduce quality ?

**Comment by 0xadada** [comment]
:-1:

**Comment by ccharlton** [comment]
Same issue on MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by glouel** [comment]
Can you try version 1.4 and check the hardware acceleration section in the readme on the project page ?
