### ISSUE TITLE
Have an option to turn off keyboard controls

### ISSUE THREAD

**Issue by tkessler45** [JohnCoates/Aerial#176]
This is a great project, but please include an option to just use default speed settings and not have keyboard input (i.e., J/K/L, Space, and arrow keys). I and others use space bar and arrows among other keys to wake our Macs from sleep or screensaver, and having these reserved by the screensaver prevents them from being used to authenticate and resume a session. A simple system preference setting to enable or disable these would be fantastic. Thanks!

**Comment by connormlewis** [comment]
I absolutely agree. I use the spacebar to wake my mac usually and i keep getting flustered and confused when the screensaver just stops instead of waking up my mac

**Comment by alistairmcmillan** [comment]
Hi @tkessler45 and @connormlewis,

I forget when but I'm pretty sure @JohnCoates fixed this in one of the betas. Try the most recent beta and let us know if it's working for you.

**Comment by alistairmcmillan** [comment]
Waited months, no reply, so closing.
