### ISSUE TITLE
OS X El Capitan Version 10.11.2 Beta (15C48a)

### ISSUE THREAD

**Issue by afivos** [JohnCoates/Aerial#177]
I'm on OS X El Capitan Version 10.11.2 Beta (15C48a). I installed it but I get the following message in the preview area:

"You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver."

**Comment by alistairmcmillan** [comment]
Duplicate of #168

**Comment by afivos** [comment]
Oops. I searched for "El Capitan" but didn't think of searching for "10.11.2". Sorry for the duplicate issue.

**Comment by afivos** [comment]
I left my computer and came back only to see the screen saver working just fine!
