### ISSUE TITLE
Screensaver is laggy on my older Mac

### ISSUE THREAD

**Issue by MaticConradi** [JohnCoates/Aerial#178]
I'm using 2011 iMac. Usually screensaver starts normally. But after a while the screensaver starts to lag or it completely stops.

**Comment by alistairmcmillan** [comment]
Which version are you using? Have you tried running the latest beta and caching the videos?

**Comment by MaticConradi** [comment]
No I probably didn't. I'll download it and try it out. How can I cache the videos? Is it done automatically by the latest beta?

**Comment by alistairmcmillan** [comment]
Just install the latest beta. Click Screensaver Options. Then choose the Cache tab. It's all fairly self explanatory.

<img width="780" alt="screenshot 2015-12-14 21 25 07" src="https://cloud.githubusercontent.com/assets/125896/11794467/7f7a3cc8-a2a9-11e5-8b9c-b72ebbbc6259.png">

**Comment by MaticConradi** [comment]
Ok, thanks! I'll try it out.

**Comment by alistairmcmillan** [comment]
@MaticConradi Did you get the screensaver working?

**Comment by MaticConradi** [comment]
Yes. Thanks for asking. It is just awesome.

**Comment by alistairmcmillan** [comment]
Cool. :)
