### ISSUE TITLE
Error states its not compatible with OSX

### ISSUE THREAD

**Issue by ODogg** [JohnCoates/Aerial#18]
Error states its not compatible with OSX. I'm currently running el capitan 10.11.1.

Thanks for making this awesome project open source!

**Comment by ODogg** [comment]
Here's a screenshot

<img width="412" alt="screen shot 2015-10-27 at 10 03 35 am" src="https://cloud.githubusercontent.com/assets/1015885/10764051/030b2f40-7c92-11e5-97d3-14fc6eac4a4c.png">

**Comment by macbookandrew** [comment]
Try this suggestion: https://github.com/JohnCoates/Aerial/issues/4#issuecomment-151557047

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #4
