### ISSUE TITLE
Spacebar causes video playback to pause instead of "stopping" screensaver

### ISSUE THREAD

**Issue by Kuipo** [JohnCoates/Aerial#180]
The screensaver can usually be woken up by pressing the spacebar, however if an Aerial video is playing, pressing spacebar causes the "active" desktop video to pause instead of bringing the user to their desktop or login screen.

Steps to repro:
1) Begin screensaver (can be done using a hot corner)
2) Once the video is playing, press the spacebar

Actual Results:
The video will pause.

Expected Result:
The screensaver should "stop" and return the user to their desktop/login screen.

Additional information:
OS: 10.11.1 (El Capitan)
Machine: MacBook Air 13-inch Mid 2013
Dual monitor setup (laptop screen + 22" 1080p monitor attached)

**Comment by jtnicandro** [comment]
I believe it is a feature. If you don't want it, use the beta version. The beta version removes the feature

**Comment by Kuipo** [comment]
Are you refering to the 1.2 beta builds or the pre 1.0 beta builds?

**Comment by jtnicandro** [comment]
1.2 Beta builds. Beta 5 feels stable on my Mac

**Comment by Kuipo** [comment]
Confirmed, 1.2 Beta 5 build doesn't have this behavior. I don't know that I would call it a feature though.
