### ISSUE TITLE
Images are static

### ISSUE THREAD

**Issue by bostick23** [JohnCoates/Aerial#181]
I've a Macbook pro retina 13" 2015 with OS X el Captain and the screensaver is always static. It doesn't play animations

**Comment by alistairmcmillan** [comment]
[Download the latest beta](https://github.com/JohnCoates/Aerial/releases). Try caching the videos. See if it plays any better that way.

**Comment by alistairmcmillan** [comment]
@bostick23 Did you get the screensaver working?

**Comment by bostick23** [comment]
Yes I did. Thank you for jour work

Il giorno gio 28 gen 2016, 22:57 Alistair McMillan <notifications@github.com>
ha scritto:
