### ISSUE TITLE
 enable offline mode

### ISSUE THREAD

**Issue by BJTHEIS** [JohnCoates/Aerial#182]
I can't figure out how to enable this feature. I cruise a lot and internet isn't active most of the time so I need the offline mode enabled.  Thank You

**Comment by alistairmcmillan** [comment]
Just go into the screensaver's preferences, enable the caching feature and click "Download Now".  This will allow you to run the screensaver when you are offline.

<img width="780" alt="7f7a3cc8-a2a9-11e5-8b9c-b72ebbbc6259" src="https://cloud.githubusercontent.com/assets/125896/12291796/4ed38058-b9e1-11e5-9d00-452771fab7b2.png">

**Comment by alistairmcmillan** [comment]
@BJTHEIS Did you get the videos cached?

**Comment by BJTHEIS** [comment]
Thank you very much
I believe it did:)

**Comment by alistairmcmillan** [comment]
Glad to hear it. :)
