### ISSUE TITLE
Screen Saver overrides Energy settings

### ISSUE THREAD

**Issue by mxt920** [JohnCoates/Aerial#183]
This screen saver works great, but it seems to override my setting in Energy Saver to turn off the monitor after 15 minutes - the screen never turns off.

Late 2012 Mac Mini running 10.11.2 here.

Thanks.

**Comment by alistairmcmillan** [comment]
Which version are you using? Try the latest beta version. This issue was fixed a wee while ago.

https://github.com/JohnCoates/Aerial/releases

**Comment by alistairmcmillan** [comment]
Duplicate of #23

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #23
