### ISSUE TITLE
Aerial Screensaver Updates

### ISSUE THREAD

**Issue by tvwillie** [JohnCoates/Aerial#184]
How might I be assured that I will receive notifications of updates for Aerial Screen?

**Comment by shaungrady** [comment]
Atom RSS feed: https://github.com/JohnCoates/Aerial/releases.atom

**Comment by alistairmcmillan** [comment]
Hi @tvwillie,

Has @shaungrady answered your question?

**Comment by alistairmcmillan** [comment]
No answer for six months, closing issue.
