### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by asoksevil** [JohnCoates/Aerial#187]

**Comment by crazytaxii** [comment]
Delete directly in system preference setting.

**Comment by Jonathan-Rosewood** [comment]
+ cache folder

**Comment by alistairmcmillan** [comment]
To uninstall the screensaver you will find the screensaver itself in either `/Library/Screen Savers` or `/Users/YOURUSERNAME/Library/Screen Savers`. Just locate the file and delete it.

If you have cached the videos they will be in `/Users/YOURUSERNAME/Library/Caches/Aerial`. You can just delete that folder.

**Comment by alistairmcmillan** [comment]
Updated README.

**Comment by gregarios** [comment]
I've been trying to uninstall Aerial completely and start fresh since I seem to have broken it. I delete the "Aerial.saver" and the folder with all the settings and downloaded videos. I've even restarted after deleting screensaver preverences and emptying the trash of all Aerial data I can find. Somehow, when I reinstall the Aerial.saver it already knows my previous preferences and crashes when I try to hit the "cache" settings in the screensaver settings. Please, give me a list of all locations any data relating to Aerial is stored on my iMac running macOS Catalina 10.15.6.

**Comment by glouel** [comment]
@gregarios 

All the locations are here at the bottom : https://aerialscreensaver.github.io/installation.html

For the plist in Catalina, it's : ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist 

(pay note to the ByHost folder, there's a similar file one level up).

I would ask however if you could zip that plist and attach it here before deleting it, so I can try and replicate your issue ? Thanks!

**Comment by gregarios** [comment]
> I would ask however if you could zip that plist and attach it here before deleting it, so I can try and replicate your issue ? Thanks!

Oops I had already deleted everything. I found the instructions you have on the website before I read this.

I did figure out that if you delete the Aerial folder with all the videos and such in it, you cannot click on the "cache" settings without freezing the entire "System Preferences" app requiring a force-quit to get out. This behavior persists, even if you delete all Aerial data and preferences and reinstall, until you get at least one full movie (re)downloaded.

**Comment by glouel** [comment]
Ok thanks a lot for that feedback, this is super useful.

> Oops I had already deleted everything. I found the instructions you have on the website before I read this.

No worries.

> I did figure out that if you delete the Aerial folder with all the videos and such in it, you cannot click on the "cache" settings without freezing the entire "System Preferences" app requiring a force-quit to get out. This behavior persists, even if you delete all Aerial data and preferences and reinstall, until you get at least one full movie (re)downloaded.

Ha, this is interesting, I may not create the Caches sub directory if you haven't downloaded a video, and that might crash the whole thing, testing this right now. 
 
> At no point did I try the "hide from Time Machine" option.

Great ! I mean, that was severely bugged so glad you didn't ;)

**Comment by glouel** [comment]
Found the bug, I had a division by 0 with an empty cache. This is fixed in next build coming out later today, really sorry about that one!
