### ISSUE TITLE
Pressing spacebar pauses only 1 screen

### ISSUE THREAD

**Issue by Topener** [JohnCoates/Aerial#19]
I have a Macbook Pro, with an external monitor on OSX 10.10. All works, however, when pressing spacebar it pauses the video, but for only 1 screen, (the main screen) and not the secondary screen.

In my case, my main screen is the external monitor.

**Comment by alistairmcmillan** [comment]
Hi @Topener have you tried a recent beta? The way the spacebar works has been changed so this should no longer be an issue.

**Comment by alistairmcmillan** [comment]
No reply for months, closing.
