### ISSUE TITLE
Videos no longer found

### ISSUE THREAD

**Issue by no2pixel** [JohnCoates/Aerial#192]
Starting today (at least that's as soon as I've noticed) the videos all fail to load when the screensaver activates. Results in a plain black screen or the usual video not found play button with a line through it.

![novideo](https://cloud.githubusercontent.com/assets/26990/12025253/e7b6a50e-ad69-11e5-945e-956cc824806d.png)

**Comment by alistairmcmillan** [comment]
Works okay here.

If you have cached the videos they load from "/Users/YOURUSERNAME/Library/Caches/Aerial" (unless you chose another location).

If you haven't cached the videos the screensaver opens the text file at http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json and then loads the files from locations like http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov.

Can you find the files in the cache or successfully access them on Apple's servers at the above link?

Some firewalls/proxies block access to the files on Apple's servers. Are you behind one?

**Comment by no2pixel** [comment]
Odd, not behind any firewall, and the cache appears to be empty now. Downloading manually and adding to the cache directory listed in the screen saver settings doesn't seem to resolve it either. All videos are playable on their own directly in Safari, and all were accessible to be downloaded manually into the cache directory.

**Comment by no2pixel** [comment]
Appears it may have been a local thing here after all. Reset cache location, moved files, and re-installed Aerial and it appears to be working correctly now.
