### ISSUE TITLE
Caching Options not working, 1.2b5

### ISSUE THREAD

**Issue by TotalNube** [JohnCoates/Aerial#193]
I'm using v1.2b5 in El Cap 10.10.1.

Installed Ariel, opened Screen Saver Options  and Cache was the default. After several clicks, got Main to open, but no buttons worked. They dimmed for a fraction of a second, but I couldn't do anything with any them, especially Change Cache Location. Then I couldn't get back to Cache, button didn't work.

Quit System Prefs, reopened and Cache was the default. Couldn't get back to Main, tried quitting System Prefs, no joy this time or several times after. A Restart didn't help.

I'll  run Ariel to see if it starts downloading the videos.

**Comment by TotalNube** [comment]
After running Ariel for 4 hours, it doesn't look like it's cached any video. There aren't any in the Applications folder.

**Comment by IronValkyrie** [comment]
I was getting connection errors when I tried to "Download Now" and the "Current Video" progress bar would glitch. Each time I pressed the download button again, but then I un-ticked "Cache Aerials As They Play" and pressed the download button. It said connection error again, but I left it with the glitching progress bar, and they're now downloading.

**Comment by alistairmcmillan** [comment]
Did this start working for you @TotalNube

**Comment by alistairmcmillan** [comment]
No reply for months, closing.
