### ISSUE TITLE
screen saver preferences not working 

### ISSUE THREAD

**Issue by ElliottTrester** [JohnCoates/Aerial#196]
letting you know that screen saver presences is not working inside of system preferences and hope this is resolved.

**Comment by alistairmcmillan** [comment]
In what way are they not working?

**Comment by sbres** [comment]
Try deleting the old versions and reinstall aerial, it worked for me.

**Comment by alistairmcmillan** [comment]
@ElliottTrester are you still having a problem with this? Did you get it working?

**Comment by ElliottTrester** [comment]
No problem seemed to be solved 

Thanks 

Elliott trester

**Comment by alistairmcmillan** [comment]
Cool. Thanks @ElliottTrester .
