### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by hayleyselby** [JohnCoates/Aerial#198]
Hi, my screensaver was playing perfectly until this morning. Is there a reason why?
I have tried downloading latest version and it shows with the icon in the system screensaver but doesn't play.
I did uncheck a couple of things in my system startup stuff have I don't something there?
Hayley

**Comment by alistairmcmillan** [comment]
If you have the latest version installed try going into the settings and enabling the cache setting. This will allow you to download the videos to your hard drive and play them from there.

**Comment by hayleyselby** [comment]
Hi there, it seems to have resolved itself. Was very strange.
I am all sorted and enjoying my screensaver again.
Is it possible to set these up with own content?
H

Hayley Selby
Product Creative Manager : Marketing
Virgin Holidays | Aeronautics House | Manor Royal | Crawley | West Sussex | RH10 9HQ
Tel: Mob 07931 722649<tel:07931%20722649> | Dir 020 3668 4741<tel:020%203668%204741> |Int 64741
Email: hayley.selby@virginholidays.com<mailto:phil.bloomfield@virginholidays.com>
Web: www.virginholidays.com<http://www.virginholidays.com/>

[cid:image001.jpg@01D0D37F.EBD979F0]

On 18 Jan 2016, at 12:24, Alistair McMillan <notifications@github.com<mailto:notifications@github.com>> wrote:


If you have the latest version installed try going into the settings and enabling the cache setting. This will allow you to download the videos to your hard drive and play them from there.

—
Reply to this email directly or view it on GitHub<https://github.com/JohnCoates/Aerial/issues/198#issuecomment-172514279>.

Virgin Holidays Limited. Registered Office: Company Secretariat, The Office, Manor Royal, Crawley, West Sussex, RH10 9NU. Registered in England, No. 1873815.

**Comment by alistairmcmillan** [comment]
Glad to hear it's working. You can close this issue if you're happy.

It's not possible to add your own content at the moment, but someone has requested that John add that feature under Issue #41 .

**Comment by hayleyselby** [comment]
thanks, I’d love to keep up to date with developments.
H

Hayley Selby
Product Creative Manager : Marketing
Virgin Holidays | Aeronautics House | Manor Royal | Crawley | West Sussex | RH10 9HQ
Tel: Mob 07931 722649 | Dir 020 3668 4741 | Int 64741
Email: hayley.selby@virginholidays.com<mailto:phil.bloomfield@virginholidays.com>
Web: www.virginholidays.com<http://www.virginholidays.com/>

[cid:image001.jpg@01D0D37F.EBD979F0]

On 18 Jan 2016, at 12:51, Alistair McMillan <notifications@github.com<mailto:notifications@github.com>> wrote:


Glad to hear it's working. You can close this issue if you're happy.

It's not possible to add your own content at the moment, but someone has requested that John add that feature under Issue #41<https://github.com/JohnCoates/Aerial/issues/41> .

—
Reply to this email directly or view it on GitHub<https://github.com/JohnCoates/Aerial/issues/198#issuecomment-172519638>.


Virgin Holidays Limited. Registered Office: Company Secretariat, The Office, Manor Royal, Crawley, West Sussex, RH10 9NU. Registered in England, No. 1873815.

**Comment by rsalek** [comment]
I still get black screen, preview does work but hot corners just gives a black screen. Any suggestion?

**Comment by rsalek** [comment]
Got it as you said "Black screen: Try disabling Little Snitch, or try the latest beta release from"

**Comment by alistairmcmillan** [comment]
Closing as screensaver is now working for @hayleyselby .
