### ISSUE TITLE
Aerial hangs when activated from Hot Corner

### ISSUE THREAD

**Issue by chandaraprakash** [JohnCoates/Aerial#20]
Set one of the Hot Corner to activate Screen Saver. Change Screen Saver to Aerial and activate the screen saver. It starts loading but immediately hangs. I also have the lock enabled after sleep or screen saver begins.

**Comment by elliottregan** [comment]
That doesn't happen for me on 11.1. What version of OS X are you using?

**Comment by chandaraprakash** [comment]
OS X Yosemite 10.10.5

**Comment by elliottregan** [comment]
Scanning through other bug reports, it looks like this was only tested on 10.11.x. I know this isn't a solution, but you should definitely upgrade to 10.11.1. It's faster than 10.10 in every respect, and there aren't any breaking bugs that I've come across (had to reinstall Java 6 for CS6, but that's nothing new).

**Comment by JohnCoates** [comment]
Looking into it. I have a computer on Yosemite so I'll be seeing if I can figure something out

**Comment by mac1user** [comment]
John, i have the exact issue. I'm running 10.12.3

**Comment by alistairmcmillan** [comment]
@mac1user @chandaraprakash Which version of the screensaver are you running? If it's not 1.2 please download 1.2 from [here](https://github.com/JohnCoates/Aerial/releases/tag/v1.2) and try again.

Do you have the videos cached? If not, please cache the videos from the Cache tab in "Screen Saver Options..." and try again.

How long are you leaving to start? Depending on the performance of your Mac it can take a while for the first video to start playing. Please leave for 60 seconds and see if anything happens.

If you set the screensaver to "Start after" a certain amount of time, does it launch itself okay? Is the issue only with the hot corner start?

**Comment by mac1user** [comment]
I'm running 1.2 and didn't bother unloading again
cache aerials as they play is selected already
start after <never> 
I do wait until it launches, it runs for a while then hangs.

**Comment by mac1user** [comment]
I'm running 1.2 and didn't bother unloading again
cache aerials as they play is selected already
start after 
I do wait until it launches, it runs for a while then hangs.

**Comment by glouel** [comment]
This is semi old but it looks like slow network, downloading the files would solve. Closing this as 1.4.1 should solve this by caching videos first.
