### ISSUE TITLE
Allow changing the Manifest URL

### ISSUE THREAD

**Issue by passcod** [JohnCoates/Aerial#200]
I am currently working on creating my own Manifest and videos for Aerial-like screensavers. Currently to use a custom URL in this, one needs to patch the source and recompile, but it would be tremendous if it simply had a preference for it.

**Comment by ragmondo** [comment]
I would also find this very useful.

**Comment by glouel** [comment]
Starting with version 1.4, we now load 3 different JSONs, they do need their own tweaks though as they aren't in the same format, or won't use the same tags for urls. 

For your specific need, with 1.4, you can edit one of the jsons in the Cache folder (see the Offline mode explaination in the readme), and add your videos there. You'll need to delete the preferences, you'll find them in 

~/Library/Preferences/ByHost/com.JohnCoates.Aerial.(something).plist

delete said file and it will reload your modified JSON.
