### ISSUE TITLE
10.11.3 not supported.

### ISSUE THREAD

**Issue by TheWojtek** [JohnCoates/Aerial#202]
The screensaver reports it's not compatible with 10.11.3 update.

**Comment by alistairmcmillan** [comment]
Working for me on 10.11.3 here. Could you try again please?

**Comment by Royedc4** [comment]
What version are you using alistairmcmillan?
I'm using a thunderbolt display as only screen. i've:
1. Downloaded all videos and put them in /Library/Caches/Aerial/
2. installed 1.2 latest beta = getting just black screen.
2. installed 1.1 latest release = getting just black screen also...

**Comment by alistairmcmillan** [comment]
`/Library/Caches/Aerial` is the wrong location. The cache location is that folder but within your own account, for example `/Users/royedc4/Library/Caches/Aerial`.

Try putting them in that folder and installing 1.2b5.

**Comment by Royedc4** [comment]
Working now(in both versions actually), thanks @alistairmcmillan

BTW i see some outgoing connection to: akamai.net, can i block it?
It will not try to download the videos anymore right? Because i notice some delay at the beginning of the screensaver.

**Comment by alistairmcmillan** [comment]
Apple could update the JSON file to include new videos. If they do, John decided the screensaver to download the new videos.

Personally I'd leave that outgoing connection unblocked.

**Comment by TheWojtek** [comment]
Unfortunately - still no: (
![screen shot 2016-01-30 at 1 20 10 pm](https://cloud.githubusercontent.com/assets/10579189/12695608/3e2b33a6-c754-11e5-9ca1-91f77b547e4e.png)

**Comment by alistairmcmillan** [comment]
Have you tried the latest release?

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by TheWojtek** [comment]
Yes, I am using this. However, I've found a solution:
- if the screensaver reports "please contact the vendor", leave the screesaver selected and close System Preferences,
- reboot,
- check back to Dekstop & Screesaver to see if Aerial works. In my case it took 3 reboots.

**Comment by alistairmcmillan** [comment]
That is very weird. I've seen that message randomly before when switching between screensavers but never worked out why. If you leave Aerial selected, close System Preferences and let the screensaver start naturally after the 5 minute delay does it just show the same error full screen?

Is there any chance you have two copies installed? One in `/Library/Screen Savers` and another in `/Users/YOURUSERNAME/Library/Screen Savers`?

**Comment by TheWojtek** [comment]
No, just a single copy for sure.
If I used a hot corner, the effect was just as expected - error message across the screen. Same thing after timeout. However, both methods are working now after reboots.

**Comment by alistairmcmillan** [comment]
That is so weird. I could understand why it might need one reboot. There does seem to be a bug in OS X where it holds on to old versions of plugins (which OS X screensavers basically are) but that should have been solved by one reboot.

Is it all working for you now though?

**Comment by msheaver** [comment]
The latest iteration of Mac OS X (10.11 El Capitan) sets different permissions on applications based upon whether they are signed my a valid developer and the user has the opportunity to override those permissions in System Preferences -> Security & Privacy -> General -> Allow apps downloaded from. I wonder if something inside of that may be causing the erratic behavior being discussed here;

Just a random thought.

**Comment by TheWojtek** [comment]
> Is it all working for you now though? Are you happy to close this issue?

Yepp, feel free to close it. It's great!

**Comment by alistairmcmillan** [comment]
@msheaver That can cause issues but if it was a Gatekeeper permission blocking it from running I don't think rebooting would have solved the issue that TheWojtek was having.

@TheWojtek Anyway glad to hear it's working now. Closing the issue.
