### ISSUE TITLE
Black screen, and a connection error

### ISSUE THREAD

**Issue by itsdaffa** [JohnCoates/Aerial#203]
Hi! I am on the latest beta (1.2 Beta 5), and the screen saver only shows black screen. I dont use Little Snitch or similar application. I've tried to download the video directly from the 'Cache' tab, but got an error saying 'Connection fail: Error domain=NSUrlErrorDomain Code=-1004 "Could...' 
Any help will be very appreciated :)

**Comment by alistairmcmillan** [comment]
Try this link in Safari or another browser on your Mac.. Does it work for you?

http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

**Comment by itsdaffa** [comment]
@alistairmcmillan nope :( I got a refused connection error.

**Comment by alistairmcmillan** [comment]
Someone is blocking you then. Are you behind a corporate firewall perhaps? Or is your Internet being filtered by your ISP?

**Comment by itsdaffa** [comment]
Nope. I am on a home internet connection. And hmm.. Blocking? Does that website contains porn? Because my government blocks porn. But usually when it is blocked by ISP, it directs me to a spalsh page by the ISP telling that this web is blocked. But not for this. It only shows me error refused connection. Maybe any workaround? :)

**Comment by alistairmcmillan** [comment]
Sorry. Try this... http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

**Comment by itsdaffa** [comment]
@alistairmcmillan Yep, I can open that one. But it still shows a black screen :(

**Comment by alistairmcmillan** [comment]
Okay, last one. Can you open this? http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

**Comment by itsdaffa** [comment]
Yep. Succesfully opened.

**Comment by alistairmcmillan** [comment]
So you can get to the JSON file, which means apple.com isn't being blocked. But Apple use Akamai's content delivery network to host the files (the edgesuite urls) and Akamai seems to be being blocked.

The workaround I guess would be to turn on caching in the screensaver while connected to a different network, so you can download the files to your Mac. Then the screensaver will work for you at home.

**Comment by Royedc4** [comment]
He could just download all the videos and put them in the cache folder right?

**Comment by alistairmcmillan** [comment]
Yup, that would work, but for some reason @itsdaffa is unable to get to the videos on the content delivery network (CDN) servers used by Apple.

**Comment by Royedc4** [comment]
Great @alistairmcmillan, well @itsdaffa i recommend you to use a VPN or something simpler like TOR browser to download the videos passing your ISP/FW restrictions

**Comment by itsdaffa** [comment]
@alistairmcmillan @Royedc4 I am sorry for the very late reply, I was very busy at school back then. Thanks for your very kind assistant y'all :) Have a nice day!

**Comment by alistairmcmillan** [comment]
@itsdaffa Did you get the screensaver working? If you're happy you can close the call. :)
