### ISSUE TITLE
When VLC is @ full screen and paused the screensaver comes up also paused. Plus more.

### ISSUE THREAD

**Issue by f-bone** [JohnCoates/Aerial#204]
As per title.

If I press Spacebar the screensaver resumes.

Also when at login screen for a long time (after booting) Apple default screensaver comes on...but when I finally give the password to continue to desktop a black screen comes up (with clock as I use it with the screensaver). Pressing any key then shows the desktop.

Yosemite final version.

Regards,
George

**Comment by alistairmcmillan** [comment]
About the space bar pausing the videos, download and try the latest release. John fixed that.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

Not sure about the VLC thing. Tried replicating that strange behaviour on my Macs and couldn't.

And the Aerial screensaver won't have started if one of Apple's default screensavers is running, so not sure what you're seeing when you log in and get a black screen with the clock.

**Comment by f-bone** [comment]
thank you for the info! maybe this specific machine being a hackintosh home-theater could affect the behavior somehow - although it works flawlessly ..my macbook and imac were not tested since I do not watch movies on them.

Ill install the update asap and provide feedback incase I encounter other small bugs.

**Comment by highvoltag3** [comment]
It's not specific to VLC, I'm having the same issue on my DEV machine no VLC or video apps open only dev tools and itunes.. plus a couple of browsers.

**Comment by alistairmcmillan** [comment]
@highvoltag3 Which issue are you having? The screensaver coming up but appearing paused? Which version are you running? Have you tried caching the videos with the latest beta? The videos stream from Apple's servers by default so network issues can make it look like the videos have paused.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by highvoltag3** [comment]
@alistairmcmillan Yes I was having the video coming up paused, I read your previous comment and was just downloading the videos to cache with the nice UI that was made for this. 

I'll report back if after the update it keeps being an issue.

**Comment by highvoltag3** [comment]
@alistairmcmillan I can confirm the beta fixes the issue.

**Comment by alistairmcmillan** [comment]
No reply from OP for months, so closing.
