### ISSUE TITLE
High internet usage

### ISSUE THREAD

**Issue by kalanaw** [JohnCoates/Aerial#206]
If I'm not very much mistaken, my internet data usage went really high after installing the screensaver. Does this screensaver one time download or are you downloading different sceneries while the screensaver is running?
Great looking job on porting this for mac btw.

**Comment by JohnCoates** [comment]
You're right, the main release doesn't save videos.
Try the beta, it caches videos:
https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by Bielousov** [comment]
Holy… I've had to update my ISP plan thinking it was all Apple TV, but it wasn't it was THIS!

**Comment by JohnCoates** [comment]
Sorry to hear that.
