### ISSUE TITLE
Remove the time?

### ISSUE THREAD

**Issue by magetron** [JohnCoates/Aerial#207]
Adding an option of removing the time would be very much useful.

**Comment by JohnCoates** [comment]
Just curious, did you close this because Aerial doesn't show the time?

**Comment by magetron** [comment]
Nope. I closed it 'cuz i realized that there is a option of showing the time at the bottom of the screen saver menu and i just enabled it.
I wanted to remove the time, i thought it was the screensaver's problem

**Comment by JohnCoates** [comment]
Okay cool, I've never even noticed that option. Thanks for replying back.

**Comment by magetron** [comment]
tbh, thank u for noticing my issue
