### ISSUE TITLE
Black screen when waking display after latest El Capitan update?

### ISSUE THREAD

**Issue by qsub** [JohnCoates/Aerial#209]
After I updated El Capitan with the recent security update a couple days ago, I've noticed my mac waking up to a black screen with movable cursor.

Has anyone experienced this lately? Essentially, my computer stays on all the time but the display goes to sleep after 15mins.

I am using the most recent beta with all the screensavers downloaded.

**Comment by alistairmcmillan** [comment]
The screensaver can't wake your screen up.

Check for something disturbing your mouse/keyboard or other applications that are waking it.

**Comment by alistairmcmillan** [comment]
No reply for months, so closing.
