### ISSUE TITLE
change the video with arrow keys.

### ISSUE THREAD

**Issue by iAlborz** [JohnCoates/Aerial#21]
hitting the arrow keys right now pauses the video and lets you move one frame at a time. if you hit space, it continues playing. This isn't really a needed functionality. if the arrow keys shuffled the screens, or just cycled through them, that'd be awesome.

**Comment by PhilippAuch** [comment]
+1

**Comment by beornlake** [comment]
This seems related to Issue #67 – I imagine it’s the QuickTime player intercepting user input.

**Comment by glouel** [comment]
Fixed for a while, also fixed in the preview panel now in 1.4.1 ;)
