### ISSUE TITLE
Use and delete bug

### ISSUE THREAD

**Issue by dandelucca** [JohnCoates/Aerial#210]
Hi,

I installed the Aerial screensaver and found a really annoying bug.

If I select it to be my screensaver it didn't work. When I play it start a black screen. If I try to remove it, the Mac send a file to the Trash and the Aerial stays in the options for screensaver. If I try again it send another file, the names are like this:
Aerial 09-25-05-617.saver
Aerial 09-25-08-138.saver

What should I do?

**Comment by alistairmcmillan** [comment]
Those dates are only being added when you put multiple copies in the Trash.

Empty the Trash. If there is still a copy in System Preferences then you've missed one. Check the folders `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers`.

**Comment by alistairmcmillan** [comment]
Also make sure you are running the latest version, and enable the caching feature. If the videos still don't play try on another network. The videos are initially streamed from Apple's servers, so they can be blocked by proxies and network filters.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by alistairmcmillan** [comment]
Let us know how you get on.

**Comment by alistairmcmillan** [comment]
Waited months, no reply, so closing.
