### ISSUE TITLE
Duplicate Videos on Multiple Displays

### ISSUE THREAD

**Issue by pvanb** [JohnCoates/Aerial#212]
I'm running the screensaver with 3 displays (laptop + 2 external displays) and I'll often see two of the screens playing the same video. I don't recall seeing the same on all 3.

Anyway, it'd be nice to always have each screen show a unique video.

**Comment by mgguinne** [comment]
I have the same issue. Be great to have this fixed.

**Comment by hani-ibrahim** [comment]
I have the same issue too, would be great if fixed and even better if each screen display a completely  different city

**Comment by glouel** [comment]
This is now fixed in 1.4 !
