### ISSUE TITLE
No black screen

### ISSUE THREAD

**Issue by auino** [JohnCoates/Aerial#213]
I've configured the Aerial screensaver, running, e.g., after 1 minute of inactivity.
I would also need to trigger the black screen/disk disabling features of OS X (e.g., after 1 hour of inactivity), but I realized that with the last version, the black screen is never triggered, not even after a whole night.
How to trigger it, maintaining the Aerial screensaver?

**Comment by alistairmcmillan** [comment]
Are you on the latest beta? If not, give it a try and let us know how you get on.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by roens** [comment]
I was also experiencing this behavior: screensaver starts… but then terminally does not power off the display when Energy Saver is set to: 1h. Rather, it kept the display on all night long.

But after installing 1.2 Beta 5, the display now turns off after an hour of inactivity.

**Comment by alistairmcmillan** [comment]
Glad to hear it's working for you now @roens 

No reply from OP, so closing.
