### ISSUE TITLE
Display never turns off

### ISSUE THREAD

**Issue by idokleinman** [JohnCoates/Aerial#214]
Aerial screensaver starts but display never turns off even though it is configured to turn off after ~10 mins both in power adapter AND battery mode. Macbook pro mid 2015, OSX 10.11.3. Disconnecting all USB peripherals did not help

ideas?

**Comment by alistairmcmillan** [comment]
Which release are you using? Try the latest beta release.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by idokleinman** [comment]
ok will try

**Comment by alistairmcmillan** [comment]
Let us know if that works for you, or feel free to close the call if your happy.

**Comment by idokleinman** [comment]
It wasn't the screen saver fault, I had processes preventing sleep, thanks!
