### ISSUE TITLE
Terminates OS

### ISSUE THREAD

**Issue by PhilippAuch** [JohnCoates/Aerial#215]
Does the following log entry mean Aerial terminated the OS? It happens relatively often and results in a logout... (Jakku is the hostname.)

`Feb 20 21:59:32 Jakku ScreenSaverEngine[918]: Window Server is not available.
Feb 20 21:59:32 --- last message repeated 1 time ---
Feb 20 21:59:32 Jakku ScreenSaverEngine[918]: *** CGEventTapCreate returned NULL
Feb 20 21:59:32 Jakku ScreenSaverEngine[918]: CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
Feb 20 21:59:33 --- last message repeated 3 times ---
Feb 20 21:59:33 Jakku syslogd[46]: ASL Sender Statistics
Feb 20 21:59:33 Jakku ScreenSaverEngine[918]: CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
Feb 20 22:00:03 --- last message repeated 1 time ---
Feb 20 22:04:33 Jakku com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000008.ScreenSaverEngine[918]): Service exited due to signal: Terminated: 15
Feb 20 22:04:36 Jakku loginwindow[867]: ERROR | -[Application hardKill:] | Application hardKill returned -600`

**Comment by JohnCoates** [comment]
That's a new one!
`Window Server is not available.` That just means ScreenSaverEngine detected that it can't display anything because there's no `Window Server` to display on. 

I don't know what's causing your Window Server to shut down. It wasn't happening before Aerial and it doesn't happen after you disable Aerial? Might be a firewall issue.

**Comment by PhilippAuch** [comment]
I've never seen it with an Apple screensaver, but it doesn't always happen with Aerial either.

**Comment by JohnCoates** [comment]
It's probably conflicting with something, probably due to the fact it accesses the internet. Have you downloaded all the aerials? This might stop it from happening. You can do this in the settings with the latest beta  https://github.com/JohnCoates/Aerial/releases

**Comment by PhilippAuch** [comment]
I downloaded them all, but when it starts there is a short moment of black screen (sometimes up to like 3 seconds). I figured it looks for new aerials. That could be the conflicting internet access.

**Comment by JohnCoates** [comment]
Yeah it does check for new Aerials and that causes the black screen. I'll see about making that check optional.

**Comment by PhilippAuch** [comment]
Thank you! :)

**Comment by PhilippAuch** [comment]
I just found a relatively hidden function that logs the user out after some idle time. I believe this was the root of the evil since deactivating it solved the issue :) This really should be more clear in the OS X log files... Thank you for the support though! :)
