### ISSUE TITLE
Better error handling / User friendlier errors

### ISSUE THREAD

**Issue by highvoltag3** [JohnCoates/Aerial#216]
I was caching the videos using the new Cache feature in `/release/1.5.beta` went to lunch which eventually let the computer to go to sleep and came back to find an error message which for us devs is ok, but I can see a user going like "what?"

Here it is:
<img width="596" alt="screenshot_2_22_16__1_30_pm" src="https://cloud.githubusercontent.com/assets/694585/13228150/64266208-d968-11e5-9b2e-4b9769392267.png">

**Comment by JohnCoates** [comment]
Totally agree! Thanks for making this issue

**Comment by glouel** [comment]
Implemented in 1.4.2 beta2, there's now a handy button that pops at the bottom of the preferences panel when something is wrong. + all the new logging stuff in advanced.
