### ISSUE TITLE
Aerial installation and config docuentation

### ISSUE THREAD

**Issue by hturner24** [JohnCoates/Aerial#217]
Hi John. Thanks for developing this awesome screen saver. I tried following the docs and don't seem to have a "screensaver options" choice. Any idea how I can get these to display as videos and not static images?
https://www.dropbox.com/s/a28l1astwup7bjq/Screenshot%202016-03-04%2014.49.07.png?dl=0

I'm running El Capitan

Thanks!
Hal

**Comment by alistairmcmillan** [comment]
That's not John's Aerial screensaver that you've got selected there. It's the "Classic" screensaver that comes with OS X.

Scroll down the list on the left hand side and if you've installed John's screensaver you should see "Aerial" further down the list. See below.

<img width="780" alt="screenshot 2016-03-04 23 24 41" src="https://cloud.githubusercontent.com/assets/125896/13543139/6315b264-e260-11e5-92a0-774b24d3186e.png">

**Comment by hturner24** [comment]
You're awesome. I didn't notice they were different. Thanks for the tip!

**Comment by alistairmcmillan** [comment]
Did you get the Aerial screensaver working now? If so, please feel free to close this issue. :)

**Comment by hturner24** [comment]
I did, thanks. And I tried to close the issue but didn't find the "Close and comment" button until your message prompted me to check again.

Thanks for your help and your followup!
