### ISSUE TITLE
Using the downloaded videos

### ISSUE THREAD

**Issue by joelcipriano** [JohnCoates/Aerial#22]
It would be great to have the option of using the downloaded videos and save bandwidth.

**Comment by tepRuslan** [comment]
+ 1

**Comment by elliottregan** [comment]
Sorry, I skipped over this issue because the title wasn't descriptive. 

I have a few more details in my issue right here: https://github.com/JohnCoates/Aerial/issues/24

**Comment by Jerome-lara** [comment]
I represent the majority of Chinese users
Really want to join the cache version, the Chinese network is too bad.

**Comment by yourtion** [comment]
@Jerome-lara +1

**Comment by yourtion** [comment]
@JohnCoates I will try to add cache function

**Comment by JohnCoates** [comment]
I just uploaded a version that supports automatically caching videos https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta

I'll be adding a button in preferences to cache everything at once soon

**Comment by Jerome-lara** [comment]
@JohnCoates Nice!

**Comment by joelcipriano** [comment]
Awesome! Thank you @JohnCoates!
