### ISSUE TITLE
Screen saver is pausing

### ISSUE THREAD

**Issue by amrinderquikr** [JohnCoates/Aerial#220]
Screen saver is pausing when Mac connected to secondary monitor.
One of screen just shows paused video and other keep running normally.

**Comment by alistairmcmillan** [comment]
By default the screensaver streams the videos from Apple's servers. So the videos can be affected by network conditions. With the latest beta you can cache all the videos on your computer and the screensaver will play them from there. Try the latest beta, enable the caching options and see if it plays any better for you. Let us know how you get on.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by brettrann** [comment]
I get the same issue. It's really actually paused.  If you click on the screen (escaping out of the password prompt) then press the space bar it resumes.  Maybe it pauses when it reaches the streaming limit.  I'll try out the latest beta thanks!

**Comment by iCHAIT** [comment]
Hi, so I downloaded the beta but I am still facing this issue :(

Can you guys confirm if it was resolved for you after downloading the beta?

**Comment by iCHAIT** [comment]
It pauses for me even in the preview.

**Comment by alistairmcmillan** [comment]
@brettrann If the screensaver pauses when you hit the spacebar then you're running an older version. Try the latest beta, it will let you cache the videos and should resolve any problems when streaming the videos. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

@iCHAIT Please try the latest beta and try caching the videos. That should stop the pausing you get when the videos are streaming. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by iCHAIT** [comment]
Hey @alistairmcmillan, I downloaded the latest beta only

From your comment on #172.

> Select the Cache pane and tick the "Cache Aerials As They Play" box.

This was checked by default.

> Finally click "Download Now"

This is currently in progress for me, lets hope this will fix it :)

**Comment by alistairmcmillan** [comment]
@amrinderquikr @iCHAIT Any progress?

**Comment by iCHAIT** [comment]
Hey @alistairmcmillan 

Yeah, so it worked for me after I cached all the videos.

Thanks a lot for the help :smile:

**Comment by glouel** [comment]
Please check version 1.4 for this.
