### ISSUE TITLE
Cache Options Not Displayed in .Saver file

### ISSUE THREAD

**Issue by gamemasta0** [JohnCoates/Aerial#221]
When running the test app from the source, I noticed there's a tab for caching options that I hadn't seen before. Looking back at the installed .saver screensaver in System Preferences, it isn't in those options for me. There isn't even a tab bar! The bar remains in the test app so I tried building the latest version of the .saver for myself but the issue remains. I would like to be able to have all these downloaded so I'm not using so much data, but I need to be able to access the options to do that! I've tried to look in the source to find the issue, but since it shows the tab when the test app is running it's hard to find out why it doesn't when it's in System Preferences. My solution is to cache all the videos through the test app and then hope the .saver will locate them, but this is certainly something worth noting.

**Comment by alistairmcmillan** [comment]
The latest beta included the caching options and a number of other improvements.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by gamemasta0** [comment]
Sorry I missed that it was in beta, thanks for the heads up! One issue I noticed while caching in the Test App: the list of videos to download appears to get truncated while viewing the preview. It missed several videos on the first pass but then downloaded the rest on a second attempt.
