### ISSUE TITLE
10.11.5 Beta (15F24b)

### ISSUE THREAD

**Issue by zackhsi** [JohnCoates/Aerial#227]
Doesn't work with this version of OSX.

**Comment by alistairmcmillan** [comment]
Could you try something for me? Open System Prefernces and select Aerial. Either it'll work or you'll get an error. If you do get the error leave it selected and close System Preferences. Then open System Preferences and see if it works now. Let us know what happens.

**Comment by zackhsi** [comment]
It works -__- thanks!
