### ISSUE TITLE
it doesn't work on iMac

### ISSUE THREAD

**Issue by meigesir** [JohnCoates/Aerial#229]
iMac info:
![image](https://cloud.githubusercontent.com/assets/1229786/15170599/c371073c-1779-11e6-86fb-828e3070b7b7.png)

**Comment by alistairmcmillan** [comment]
Do you get an error message saying "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver."?

**Comment by meigesir** [comment]
@alistairmcmillan  No，show below:
![image](https://cloud.githubusercontent.com/assets/1229786/15174340/bb56051a-1793-11e6-9bc7-5b17ec181322.png)

**Comment by alistairmcmillan** [comment]
Are you behind a proxy or firewall?

Do either of these links work for you?

This should just load a text file... http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

This should load one of the movies...
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

**Comment by meigesir** [comment]
@alistairmcmillan Thanks, I just click the button below，it works:
![image](https://cloud.githubusercontent.com/assets/1229786/15183709/dc0e6ab4-17c4-11e6-8a3c-010a79c083a6.png)

**Comment by alistairmcmillan** [comment]
Cool. You can close this issue if it's all working for you now.

**Comment by meigesir** [comment]
@alistairmcmillan Oh no, only a few can and others are download failed.
![image](https://cloud.githubusercontent.com/assets/1229786/15183949/e2c630de-17c5-11e6-87f0-e2d709bd1f2a.png)

**Comment by alistairmcmillan** [comment]
@meigesir So, are you behind a proxy or firewall?

**Comment by alistairmcmillan** [comment]
A month with no reply. Closing issue.
