### ISSUE TITLE
Aerial Inhibits Sleep

### ISSUE THREAD

**Issue by kolpanic** [JohnCoates/Aerial#23]
I just set my system sleep time to 1 minute and activated the screen saver. It ran for 5 minutes without sleeping.

I had the same problem in a screen saver I built. It may be because AVPlayerView creates some power management assertions to inhiibit sleep when it starts playing. My solution was to use AVPlayerLayer instead.

**Comment by jbeker** [comment]
:+1: Happens to me too

**Comment by fantattitude** [comment]
+1

**Comment by alby128** [comment]
This happens also to me on 10.11.1

**Comment by devinbrown7** [comment]
+1
Mac OS X 10.11.1

**Comment by eyesee1** [comment]
Yup, no sleeping here either. I woke up this morning and found it had been on all night, and running kinda hot, too. Mid-2014 MBP. 10.11.1.

**Comment by pierrevdk** [comment]
Same here on 10.11.1 with a Mid-2012 MacBook Air

**Comment by sterpe** [comment]
+1

**Comment by briantully** [comment]
+1

**Comment by Caf** [comment]
+1 (and it's not working anyway. ;) )

**Comment by joshlewis** [comment]
+1

**Comment by JohnCoates** [comment]
I'm working on this issue. I found an undocumented function in AVKit called AVEnableUserIdleDisplaySleep but I am not able to call it because dlsym can't get a reference to it for some reason I can't figure out. It will take some work to implement a fix, but I'm on it.

**Comment by kolpanic** [comment]
@JohnCoates As I mentioned, we had the same problem in our screen saver, and dug into the undocumented APIs for a solution. In the end, the easiest thing was to drop `AVPlayerView` and use an `AVPlayerLayer`.

**Comment by chrissanderson** [comment]
+1 for a fix. Great screensaver otherwise.

**Comment by MihaxXx** [comment]
+1

**Comment by nipuns11** [comment]
Great screensaver . just waiting for the sleep fix

**Comment by kevin1** [comment]
Hey guys, it looks like @JohnCoates is already working this bug. Can we stop +1-ing the thread? Some of us are subscribed to get notified when the bug is fixed

**Comment by JohnCoates** [comment]
Awesome suggestion @kolpanic, sorry I just briefly glanced over the thread and missed your initial post. I've switched over to AVPlayerLayer. Anyone having this issue, it should be fixed in the latest beta release found here https://github.com/JohnCoates/Aerial/releases

**Comment by kolpanic** [comment]
@JohnCoates Glad to help.

**Comment by bobbyo12** [comment]
works like a charm, thanks for the quick resolution!

**Comment by Markyt1977** [comment]
mark tegeda

**Comment by tiagratim** [comment]
I have beta 4 but still get the issue. Any suggestions?
