### ISSUE TITLE
1.2 Beta 4. Inconsistent loading of videos and screensaver options menu

### ISSUE THREAD

**Issue by Dlskier** [JohnCoates/Aerial#230]
First off, great work. This is the best screensaver I've ever seen.

I've cached all videos and sometimes it works fine and the menu is visible. Other times the "Main" options menu is missing the list of videos and the preview is black as well as the screensaver failing to display, just black.

![screen shot 2016-05-20 at 10 50 39 am](https://cloud.githubusercontent.com/assets/5822866/15437014/834cddf0-1e79-11e6-9a61-56789dc9c2fb.png)

OSX El Cap 10.11.4

I'm happy to do any debugging you need me to to isolate the issue.

**Comment by alistairmcmillan** [comment]
Do you get the same issue with beta5?

**Comment by Dlskier** [comment]
Sorry yes, same issue with beta 5, I've updated the title.

One bit of additional detail. It appears the 3 pieces of functionality can fail independently, which is making narrowing down a pattern for you more difficult. Just now I had the preview displaying correctly but the settings window was blank, while the screensaver was also black. Early I had the preview and settings blank with a functioning screensaver.

**Comment by alistairmcmillan** [comment]
Are you behind a proxy or firewall by any chance?

**Comment by Dlskier** [comment]
Sorry just updated the other comment before seeing your question. I am behind a proxy, and suspected that might be the issue but I can hit the json fine. Is there another url I need access to? Is it possible to force offline mode?

**Comment by Dlskier** [comment]
Ok, I've checked the logs and I do get an error when viewing preview.
>
Jun  8 12:38:39 WMac System Preferences[3804]: Aerial: Error retrieving content listing.
>

Then when opening settings I get
>
Jun  8 12:38:59 WMac System Preferences[3804]: [12:38:59.881] <<<< AVPlayer >>>> -[AVPlayer outputContext]: No figPlayer found, cannot set picker id
Jun  8 12:39:00 WMac System Preferences[3804]: [12:39:00.287] <<<< AVPlayer >>>> -[AVPlayer outputContext]: No figPlayer found, cannot set picker id
Jun  8 12:39:00 WMac System Preferences[3804]: [12:39:00.287] <<<< AVPlayer >>>> -[AVPlayer setOutputContext:]: No figPlayer found, cannot set picker id
>

Finally, while attempting to play screensaver and getting a black screen
>
Jun  8 12:41:44 WMac ScreenSaverEngine[3812]: Aerial: Error retrieving content listing.
>

I'm still able to browse directly to http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json and receive the json

**Comment by alistairmcmillan** [comment]
@Dlskier If you are able to access those urls okay in a browser but Aerial is unable to access them, do you have something on your Mac that blocks individual applications like Little Snitch perhaps?

**Comment by Dlskier** [comment]
I think it must be something in my work network that sometimes doesn't allow it or something. Sometimes it works, sometimes it doesn't. It would be amazing to be able to download everything once, and then have it never try to make any network connections so it would consistently work, but I realize I very well may be the only person with this need. I can live with it working sometimes.

**Comment by alistairmcmillan** [comment]
If you've cached all the videos, then it should work whether your network is blocking access or not. The JSON file gets cached as well.

I'm pretty sure the way John wrote the screensaver it tries to connect and if it fails, it loads the JSON from the stored copy in the preferences plist file.

So if you've enabled the cached option it should work if you even have no network connection at all. I'll confirm tonight that but I'm pretty sure that's the way it's supposed to work.

**Comment by alistairmcmillan** [comment]
@Dlskier If you're still having an issue could you try deleting the screensaver (just the actual saver file, not the cache) and downloading/installing a new copy. I've talked to a couple of people now who had corrupted installs that displayed similar weird behaviour.
