### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bonz027** [JohnCoates/Aerial#232]
Hey, 

First of all, awesome freakin app you have going here! I am just getting into programming (javascript) and I can't wait until I have the knowledge to design something like this in the future. 

Question to you, I want to add this Aerial app to the background of my landing page for my final project, any tips or pointers on how to go about doing something like that? My page is bootstrap btw. 

A million thanks in advance for your help! 

</Cheers!>

**Comment by alistairmcmillan** [comment]
Sorry but you can't really run an OS X executable (which screensavers are) as part of a web page.

The movies though are just MOV files listed in a JSON file. It shouldn't be difficult to grab the JSON file, parse it for the MOV files and load them sequentially in a web page.

Here's the link to the JSON file.
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json
