### ISSUE TITLE
screensaver freezes

### ISSUE THREAD

**Issue by npoilly** [JohnCoates/Aerial#233]
Screensaver freezes after few seconds.

Os X El Capitan V 10.11.6 beta

**Comment by alistairmcmillan** [comment]
Which version of Aerial are you using? Are you using the latest beta? Have you tried caching the videos?

https://github.com/JohnCoates/Aerial/releases

**Comment by npoilly** [comment]
Hey John,

thanks for your quick reply. 

I’m using the 1.2 beta 5, and i’ve cached all the videos.

Might be because I’m using Os X beta 10.11.6

**Comment by GroenteLepel** [comment]
I have the same issue, and I'm using 10.11.4

**Comment by clintharris** [comment]
Ditto. OSX 10.11.5, Aerial 1.2 Beta 5.

**Comment by alistairmcmillan** [comment]
@GroenteLepel @clintharris Do you have the videos cached? Is `/Users/YOURUSERNAME/Library/Cache/Aerial` populated with about 30 mov files?

**Comment by clintharris** [comment]
Yes, have all 34 videos cached. Also, when attempting to preview the screen saver I usually just get a black screen instead of the videos.

**Comment by alistairmcmillan** [comment]
@clintharris That is really weird. Which type of Mac do you have? And you definitely only have 1.2b5 installed? Forgive me if this is a silly question but you don't perhaps have one copy in `/Library/Screen Savers` and another in `/Users/YOURUSERNAME/Library/Screen Savers`?

**Comment by clintharris** [comment]
@alistairmcmillan I'm using a 2015 MBP. Confirmed that there's only one copy (`/Users/c/Library/Screen Savers/Aerial.saver`).

Strangely, the issue has resolved itself (wish I could tell you what changed). I won't close the ticket since I'm not the OP, but you can consider my ticket resolved. ;) Thanks for the quick response and the work on this project.

**Comment by winsmith** [comment]
+1

Environment: iMac (Retina 5K, 27-inch, Late 2014), macOS 10.11.5

Play Different Aerial on each display is enabled.

When the screen saver starts, the movies are animated for about 20 seconds, then they freeze. Tapping the space bar starts the video on my main screen again (and tapping it again pauses the video once more). Any other key or mouse click exits the screen saver.

**Comment by alistairmcmillan** [comment]
@winsmith You're using an old version. Download the latest beta from the link below, cache the videos and let us know if they still freeze after 20 seconds.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by alistairmcmillan** [comment]
@npoilly Are you still having issues?

@GroenteLepel Which version are you using?

**Comment by SuperGitty** [comment]
Hi. The screensaver still freezes, whether doing mirroring or separate videos for separate displays. It will start the video and then just freeze the video image. *Sometimes* the middle display will show the full video for *some* of the videos but never on either extended displays (which I have 2 other running).

Running:
iMac (27-inch, Mid 2011)
OS X El Capitan 10.11.6
3.1 GHz Intel Core i5
4 GB 1333 MHz DDR3 RAM
AMD Radeon HD 6970M 1024MB

**Comment by SuperGitty** [comment]
And yes, running the v1.2beta5

**Comment by alistairmcmillan** [comment]
@SuperGitty Have you tried caching the videos?

**Comment by moooooooo** [comment]
worse case scenario is manually delete the folder

xxxx@xxxxMBP /Library/Screen Savers/Default Collections

$ ll

total 0

drwxr-xr-x  19 root  wheel  646  2 Aug  2015 1-National Geographic

drwxr-xr-x  11 root  wheel  374  2 Aug  2015 2-Aerial

drwxr-xr-x  11 root  wheel  374  2 Aug  2015 3-Cosmos

drwxr-xr-x  10 root  wheel  340  2 Aug  2015 4-Nature Patterns


So in there (insert your user name where xxxx is) and remove 2-Aerial and
try again.

To be honest, apart from the blank black screen ages ago, it;s been solid
on both normal OSX and beta OSX on my Mac Mini.

Happy to take questions.

**Comment by alistairmcmillan** [comment]
@moooooooo Are you certain that folder has anything to do with this Aerial screensaver? I think that's photos that are bundled with the operating system.

**Comment by moooooooo** [comment]
you're right - it's where the photos are. hmmm. ok i'll keep checking

**Comment by alistairmcmillan** [comment]
@moooooooo Keep checking for what? :) The screen saver is either in `/Library/Screen Savers` or `/Users/YOURUSERNAME/Library/Screen Savers`. That the only two locations that the OS will recognise screensavers.

**Comment by SuperGitty** [comment]
@alistairmcmillan Yup, cached all videos. It seems to run "sometimes" but often not, freezing occurs. I have plenty of RAM and HD space so.... I guess this is supposed to work for El Capitan?

**Comment by timgonzales** [comment]
This is happening to me on 10.12 — I have all videos cached and it works for a little while, but after the screensaver cycles through several videos it freezes.

**Comment by alistairmcmillan** [comment]
@timgonzales What model of Mac do you have? And how many screens is the screensaver running on when it freezes?

**Comment by timgonzales** [comment]
@alistairmcmillan It's a mid 2012 13" MacBook Air (MacBookAir5,2). Running a single, external display with the laptop closed.

**Comment by zuidwijk** [comment]
Here a MBP late 2011, 10.12.2, all video's cached, latest version (1.2). Same issue as @timgonzales 
First video works fine, once it cycles to the 2nd video, it freezes.

**Comment by tjkohli** [comment]
My screen saver freezes every so often too. They're all cached, latest version (1.2), macOS 10.12.2.

**Comment by icfantv** [comment]
So far, I've noticed it's the same screensavers freezing (at least for me).  The two I've noticed so far are:

* comp_LA_A008_C004_ALT_v33_6Mbps.mov
* comp_HK_H004_C008_v10_6Mbps.mov

**Comment by zuidwijk** [comment]
comp_DB_D001_C005_t9_6M_HB_tag0 freezes here to...

I've noticed that screensaver on a 2nd screen doesn't freeze, only on my laptop screen.

**Comment by gregorylarsen** [comment]
Freezing on transition here as well. As a stop-gap, I have switched over to using Save Hollywood to play the cached movie files as it doesn't freeze and progresses through the various files without issue.

**Comment by srivaths** [comment]
I see many commenters reporting the _version_ of Aerial they have installed.  How can I determine the version?
...and yeah I'm having the freezing issue too.  Sometimes only on the secondary display.

**Comment by timgonzales** [comment]
Just wanted to note that I seemed to have circumvented this bug by deleting all the cached screensavers, and opting to NOT use that option to cache the videos ahead of time. For several weeks now, I have not experienced a screensaver freezing.

**Comment by glouel** [comment]
Version 1.4 should fix all this now.
