### ISSUE TITLE
Adjust speed of video

### ISSUE THREAD

**Issue by GroenteLepel** [JohnCoates/Aerial#234]
Hi,

I just installed the newest beta and I think the speed of the video is a bit too high. Is there a way to adjust it so it moves a bit slower?

**Comment by alistairmcmillan** [comment]
The speed of the movies is basically whatever Apple set when they created them.

If someone was sufficiently motivated they could write and submit a patch to allow users to change the playback speed of the movies in the screensaver preferences. AVPlayer allows you to change the rate of playback. https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/#//apple_ref/occ/instp/AVPlayer/rate

**Comment by fredleblanc** [comment]
It seems like J, K, and L (on your keyboard) controls the speed? For me it looks like L will speed it up, K will… freeze it? And J makes it go backwards? Try playing with those keys when the video is playing.

**Comment by alistairmcmillan** [comment]
@fredleblanc I think if those keys work it means you're using an older version.

I think they were a feature of AVPlayerView which, if I remember correctly, was preventing monitors from going to sleep. So John replaced it with AVPlayerLayer, which as a side-effect doesn't respond to the J, K and L keys.

The keys only work up to version 1.2 beta 2.

**Comment by fredleblanc** [comment]
Interesting, thanks!
