### ISSUE TITLE
Energy Saver

### ISSUE THREAD

**Issue by klauslovgreen** [JohnCoates/Aerial#238]
It seems that this screensaver overwrites the "Turn display off after:..." - please can you look into that? At night it is convenient if the display turns off.

Thanks for a great product!

**Comment by alistairmcmillan** [comment]
@klauslovgreen If the display doesn't turn off you are likely using an older version. That was a bug which John resolved a while ago. Please try the latest version and let us know how you get on.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by klauslovgreen** [comment]
Thanks - yes that did the trick.
