### ISSUE TITLE
Does not seem to work on the 15" “Early 2011” MacBook Pro

### ISSUE THREAD

**Issue by JackOnGitHubDotCom** [JohnCoates/Aerial#241]
Hi,

I installed Aerial on my 15" early-2011 MacBook Pro, and, while it shows an animated preview in the Screen Saver Control Panel, the screen saver itself doesn't actually show on the screen when the screen saver is invoked.

This is on a 2GHz i7 with 16 GB of RAM and an AMD Radeon HD 6490M 256 MB

Any ideas?

**Comment by alistairmcmillan** [comment]
Which version of the screensaver do you have installed?

**Comment by JackOnGitHubDotCom** [comment]
I think I installed the current version--the one from the download link on
https://github.com/JohnCoates/Aerial

- Jack

**Comment by alistairmcmillan** [comment]
Hi @JackOnGitHubDotCom 

The newest version is available here. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

It lets you cache the videos on your Mac. Which should eliminate any network issues.

Give that a try and let me know how you get on. 

- A

**Comment by JackOnGitHubDotCom** [comment]
Alistair,

Thank you—that worked... but also, I think it popped up my Little Snitch
Configuration app with the Screen Saver Engine highlighted, and shown as
blocking any connections. I ALLOWED the connections, and that fixed it!

Thanks again!

- Jack

On Wed, Jul 6, 2016 at 11:57 AM, Alistair McMillan <notifications@github.com

**Comment by alistairmcmillan** [comment]
@JackOnGitHubDotCom Glad it's working for you now. :)
