### ISSUE TITLE
Is it also freezing for you guys?

### ISSUE THREAD

**Issue by uxmariano** [JohnCoates/Aerial#242]
Last week, I started noticing that sometimes the screensaver will freeze on the first frame, and the video never starts playing. Is that also happening to you? I'm using 2 monitors, by the way.

**Comment by alistairmcmillan** [comment]
Hi @uxmariano, which version are you running? The last version 1.2b5 is available here. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5 You can cache the videos on your Mac and that should eliminate any network streaming problems.

Give it a try and let me know how you get on.

- A

**Comment by uxmariano** [comment]
Thanks!!
