### ISSUE TITLE
Not working on the last version of El Capitan

### ISSUE THREAD

**Issue by uxmariano** [JohnCoates/Aerial#243]
Getting this error message on El Cap 10.11.5 (15F34)

https://www.evernote.com/l/APq9E1sPP1dFEqw3JCU3WBOhsH49VNZg3Lw

**Comment by alistairmcmillan** [comment]
Long story short it's a bug in OS X. The screensaver will still actually work though. If you select Aerial, then close and reopen System Preferences you won't get the error.

More here if you are curious.
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by uxmariano** [comment]
Hey @alistairmcmillan - thanks for you quick reply!

So I downloaded the beta, installed it and now I see two versions of Aerial: https://www.evernote.com/l/APr9JfUoNY9G37bZNQj6T-Ga-Nq58mtpZVU

I don't have the error message, but the videos are not playing... I just get a blank screen all in the thumbnail, the preview and in the actual screen saver. I tried downloading from the Cache tab, but it doesn't seem to work. Even after restarting and quitting and re-opening preferences.

**Comment by Fitrepreneur** [comment]
El Capitan 10.11 

I do not see the options

Screen Saver is not running.

<img width="667" alt="screen shot 2016-07-07 at 5 04 43 pm" src="https://cloud.githubusercontent.com/assets/19987052/16648119/10d9c9b0-4465-11e6-8b41-fc0806a7dcf3.png">

**Comment by alistairmcmillan** [comment]
@uxmariano There are two locations you can install the screensaver. `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers`. If you are seeing two in System Preferences it likely means you have one in each location.

If the videos don't want to stream or download, are you perhaps behind a personal firewall, a corporate firewall or a proxy maybe?

**Comment by uxmariano** [comment]
Hey guys,

Thanks for your help - just wanted to post and update and let you know I was able to download the videos using a different connection and now the screensaver works like a charm. It's more than 3 gb of videos, so I would advise caution on where and when to download them (tethering is a baaad idea).

The UX for the Cache tab could definitely use a little love @JohnCoates - let me know if you want to see some suggestions.


Thanks again!
