### ISSUE TITLE
Aerial launches in frozen state and won't exit cleanly *sometimes* in macOS Sierra Public Beta

### ISSUE THREAD

**Issue by leeeoooooo** [JohnCoates/Aerial#244]
This screensaver's behavior seems twitchy under the new Public Beta. It often launches but won't move. When this happens, the screensaver clears only small parts of the screen at a time.

**Comment by alistairmcmillan** [comment]
Please report this to Apple using the Feedback Assistant.

http://www.macworld.com/article/3092985/ios/how-to-use-feedback-assistant-to-report-bugs-in-apple-betas.html

**Comment by alistairmcmillan** [comment]
Over a month with no reply. Closing this issue.
