### ISSUE TITLE
El Capitan 10.11.5 won't run Aerial

### ISSUE THREAD

**Issue by JuanCab** [JohnCoates/Aerial#245]
When I activate Aerial I get a displayed message that "You cannot use the Aerial screen saver with this version of OS X.  Please contact the vendor to get a newer version of this screen saver."  Odd since I see other people running it with Sierra in the issues list. :(

**Comment by alistairmcmillan** [comment]
It will run. It's just a bug in OS X System Preferences with Swift screensavers.

The screensaver will actually kick in fine.

And if you select Aerial, then close and reopen System Preferences, the preview will work okay too.

You can read more about it here.
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by JuanCab** [comment]
Just found it, thanks!

**Comment by alistairmcmillan** [comment]
@JuanCab Cool. Feel free to close the issue if it's working for you now.
