### ISSUE TITLE
Just shows a crossed out play button

### ISSUE THREAD

**Issue by dontangg** [JohnCoates/Aerial#246]
The screen saver was working fine for me for a few weeks.  I didn't change anything, and now it just shows a crossed out play button.  I tried installing it again and it is still not working.  I have a Macbook Pro running 10.11.5.

![image](https://cloud.githubusercontent.com/assets/319091/16969082/db01abae-4dcf-11e6-86b8-53441b0b2785.png)

**Comment by alistairmcmillan** [comment]
@dontangg Are you behind a firewall or proxy? That's the most likely cause.

Easy fix though. Download the [latest version here](https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5). Connect to a network that doesn't block you. Cache the videos.

Let us know how you get on.

**Comment by dontangg** [comment]
I downloaded the latest version from your link and it is working now.  The weird thing is that it is I downloaded and cached all the videos using the wifi where it wasn't working before.  Either way, it's working now.  Thanks for the help!
