### ISSUE TITLE
Screensaver not working on  the OS X EL Capitan 10.11.6

### ISSUE THREAD

**Issue by ChrisBada** [JohnCoates/Aerial#247]
Hi  guys,

I installed the new OS X EL Capitan 10.11.6  today and noticed that the screensaver have stopped working. I deleted the old installation re-install  but still  not working. All  am  getting is a black screen as seen  below. 

Could it be that  the screensaver is not compatible this new OS?

Can anyone please help.

Thanks
![screen shot 2016-07-20 at 5 02 37 pm](https://cloud.githubusercontent.com/assets/20560643/16991581/4c59d296-4e9c-11e6-8fd3-c8486592ee2a.png)

**Comment by alistairmcmillan** [comment]
@ChrisBada Which version are you using? The latest beta? https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

Did you have the videos cached?

**Comment by ChrisBada** [comment]
Hi there,

I tried these version and it's not working 

If caching , how do I decache?  I have deleted all downloaded versions off my Pc as they are now working .

**Comment by alistairmcmillan** [comment]
Tested the screen saver in 10.11.6 on two machines over night and it works fine for me. So it is compatible with 10.11.6.

How do you de-cache? Just delete the folder `/Users/YOURUSERNAME/Library/Caches/Aerial`. That's where Aerial stores the videos it downloads.

So you downloaded the latest beta, cached the videos, but you still got that black screen in the preview? And the screen saver wouldn't launch after the regular timeout?

**Comment by ChrisBada** [comment]
It is now working for me.

Thank  you  so  much for your help.

When  there are new videos available , will  they  be added automatically?

**Comment by alistairmcmillan** [comment]
@ChrisBada Glad it's working now. :)

Yes each time the screen saver launches it checks Apple's servers for the manifest file that lists the videos. So it will include new videos in the rotation whenever they're added (caching them if you've told it to do that).

**Comment by ChrisBada** [comment]
Thanks buddy.

**Comment by ChrisBada** [comment]
Thank you.
