### ISSUE TITLE
how to replace video which i have made

### ISSUE THREAD

**Issue by naffan2014** [JohnCoates/Aerial#248]
i have a lot of videos myself. i want change your videos. is there any solution i can do that?

**Comment by alistairmcmillan** [comment]
@naffan2014 At the moment Aerials only plays the movies from the Apple TV screensaver. Other people have requested the ability to play other videos and I think John was considering that, but so far no-one has written the code to make that happen.

Closing and linking to #41 .

**Comment by naffan2014** [comment]
i wanna do that  if you allow me to do
