### ISSUE TITLE
Aerial not compatible with macOS Sierra

### ISSUE THREAD

**Issue by Saphiria** [JohnCoates/Aerial#250]
Hi,

I upgraded to the beta of macOS Sierra and got this black message on my screen; **"You can not use Aerial screen saver with this version of OS X. Please contact the vender to get a never version of the screen saver."** I would appreciate a fix.

<img width="324" alt="screen shot 2016-08-01 at 10 47 59 am" src="https://cloud.githubusercontent.com/assets/12604271/17299899/bc120cec-57d5-11e6-99df-50469b93fe07.png">

Thanks,
Noah

**Comment by alistairmcmillan** [comment]
It's a bug in OS X (and now in macOS).

The screensaver itself will work okay.

To get the preview to work in System Preferences, just select Aerial, close System Preferences, and reopen the window.

For more information:
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by Saphiria** [comment]
Thanks so much! I hope a fix comes out soon.

**Comment by alistairmcmillan** [comment]
@Saphiria Glad to hear it's working for you. Please report this bug to Apple using the Feedback Assistant in macOS Sierra. Mentioning the blog post above and/or rdar://25569037 might help get this fixed.
