### ISSUE TITLE
Not working and cannot be deleted

### ISSUE THREAD

**Issue by songchunlin** [JohnCoates/Aerial#251]
Have tried place Aerial.saver in ~/Library/Screen Savers, used latest beta release, reboot, still not working on my Mac (OS X EI Capitan 10.11.4). And I can't delete it. See screenshots below.
![screen shot 2016-08-02 at 21 02 56](https://cloud.githubusercontent.com/assets/6443195/17329392/0c81d9bc-58f5-11e6-967f-a9e1914404e2.png)
![screen shot 2016-08-02 at 21 03 08](https://cloud.githubusercontent.com/assets/6443195/17329396/0edf8c04-58f5-11e6-9c3c-6695d3bdfff5.png)
![screen shot 2016-08-02 at 21 03 16](https://cloud.githubusercontent.com/assets/6443195/17329401/114367a4-58f5-11e6-882b-85566e2be705.png)

**Comment by alistairmcmillan** [comment]
Are you behind a firewall or proxy perhaps? If you're being blocked from reaching the servers that host the files this is what it'll look like.

To delete the file, just close System Preferences and delete the file from the ~/Library/Screen Savers folder.

**Comment by jeffdeville** [comment]
Not working for me either, with the same symptoms. No proxy. Any chance the downloads are unavailable?

**Comment by jeffdeville** [comment]
It looks like the urls from the manifest are 302ing to the eventual destination. Is your download following those redirects?

**Comment by jeffdeville** [comment]
Both of those downloads work in a browser.  

I can't cache the videos from the screensaver though. It gets stuck on "Loading JSON".  

I tried dropping the entries.json and all of the videos directly into the cache folder. No luck. May not have the file names / paths correct.

**Comment by alistairmcmillan** [comment]
@jeffdeville The JSON file gets saved as data into the screensaver's plist. Downloading the JSON file and dropping it into the cache folder won't have any effect.

If you can reach the JSON file in a web browser I'm really not sure what is happening here. You said you aren't behind a proxy. Do you perhaps have a firewall installed like Little Snitch?

**Comment by jeffdeville** [comment]
Oh man.  Face palm. I have an app that disables certain network traffic if I'm tethered to a phone. For some reason it didn't turn off even though I'm on wifi.  My apologies!  Sweet sweet screensaver action is now mine!  Thanks!

**Comment by alistairmcmillan** [comment]
@jeffdeville Glad to hear it's working now.

@songchunlin How about yourself? Are you behind a firewall or proxy?

**Comment by alistairmcmillan** [comment]
Two weeks. No reply from @songchunlin . Closing the issue.
