### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by MHWbaltimore** [JohnCoates/Aerial#252]
Hi...love the screensaver but I have noticed that when I am using it as my screensaver, my Mac will not sleep the screen or the computer as it seems to prevent it.

**Comment by alistairmcmillan** [comment]
I think you might be running an old version. The developer, John, fixed this issue a few releases ago.

Try the latest beta and let us know how you get on.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by jandersonpos** [comment]
I have the same issue even after installing the latest beta.

**Comment by alistairmcmillan** [comment]
@jandersonpos You really shouldn't be getting that if you have the recent version. The bug was definitely fixed in an older version.

Can you check to make sure you don't have more than one copy installed? Please check `/Library/Screen Savers` and `/User/YOURUSERNAME/Library/Screen Savers`. It's possible to have a copy in both locations.

**Comment by jandersonpos** [comment]
That was the issue.  There was a version 1.1 in /Library/Screen Savers and version 1.2 in ~/Library/Screen Savers.

**Comment by alistairmcmillan** [comment]
@jandersonpos Cool glad to hear it's working now.

@MHWbaltimore Are you still having issues with the screen saver?

**Comment by MHWbaltimore** [comment]
I am traveling at the moment but will check when I am back tomorrow. Thanks for the help. 






On Thu, Aug 18, 2016 at 8:34 AM -0400, "Alistair McMillan" <notifications@github.com> wrote:












@jandersonpos Cool glad to hear it's working now.



@MHWbaltimore Are you still having issues with the screen saver?

**Comment by alistairmcmillan** [comment]
@MHWbaltimore Hi, did you get a chance to test it?

**Comment by MHWbaltimore** [comment]
I will this evening...just been a bit crazed.






On Sun, Aug 21, 2016 at 5:47 PM -0400, "Alistair McMillan" <notifications@github.com> wrote:












@MHWbaltimore Hi, did you get a chance to test it?

**Comment by MHWbaltimore** [comment]
I think that corrected it…thank you for the help.

M

**Comment by alistairmcmillan** [comment]
Glad to hear it. :D
