### ISSUE TITLE
Please update for macOS Sierra beta 5/6/future?

### ISSUE THREAD

**Issue by ferrarifreak101** [JohnCoates/Aerial#253]
I can't use this amazing screensaver for macOS Sierra Public Beta :(

**Comment by alistairmcmillan** [comment]
It does work in Sierra. There is a bug in OS X and now macOS.

The screen saver itself works fine, but you get an error with the preview.

So select the Aerial screen saver, close System Preferences, re-open System Preferences and now the preview should work. Let me know if it doesn't.

It's a bug in macOS. Please report to Apple using the feedback app.

More here if you are curious. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by ferrarifreak101** [comment]
It absolutely does work! You're right (not that you wouldn't be, you're the expert). After receiving this email, I simply opened system preferences and boom, it works. Thanks so much! I'll be sure to report the bug thru Feedback

**Comment by alistairmcmillan** [comment]
Glad to hear it's working for you. :)

Please do report it to Apple. I logged a bug in their bug reporting system but it hasn't been touched yet. If you could log a bug with the feedback app and mention radar number 25569037 that might help draw attention to it. Thanks.
