### ISSUE TITLE
it's not working on 10.11.6

### ISSUE THREAD

**Issue by andy-sheng** [JohnCoates/Aerial#254]

**Comment by alistairmcmillan** [comment]
LOL. You need to give us a wee bit more information than that.

Do you get a "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver." error message?

If so then yes it is working. There is a bug in OS X.

The screen saver itself works fine. You just get that error with the preview.

So select the Aerial screen saver, close System Preferences, re-open System Preferences and now the preview should work. Let me know if it doesn't.

It's a bug in OSX.

More here if you are curious. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by andy-sheng** [comment]
Sorry, my fault. It's working fine now.
