### ISSUE TITLE
Cannot play the video

### ISSUE THREAD

**Issue by 5dmarkii** [JohnCoates/Aerial#255]
I have a same problem like Issue #251. The interface has nothing but a black windows or just like this:
<img width="780" alt="screen shot 2016-08-24 at 11 52 45 pm" src="https://cloud.githubusercontent.com/assets/3367751/17938355/2ffb1a7e-6a58-11e6-856c-16a38351eaa7.png">

How can i fix this? Did I miss something to download?

**Comment by alistairmcmillan** [comment]
So are you behind a firewall or proxy? If you get that, it typically means that you are being blocked from accessing the videos on Apple's CDN servers.

**Comment by 5dmarkii** [comment]
Fixed, thanks!

**Comment by alistairmcmillan** [comment]
Cool. Glad to hear it. :)
