### ISSUE TITLE
[enhancement] Disable additional Monitors

### ISSUE THREAD

**Issue by The1andONLYdave** [JohnCoates/Aerial#256]
I'd like to have it play on only 1 Monitor.
Sometimes i've connected 2 Monitors on my Mac Mini, sometimes i use it on my Macbook with internal + 2 Monitors.

Don't care if the other ones go to Blank/Standby, turn only black or display a chossable solid color, but the last would be the best.

Is this possible?

**Comment by ccharlton** [comment]
+1

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
