### ISSUE TITLE
Sharper videos (attached below)

### ISSUE THREAD

**Issue by CristianMoisei** [JohnCoates/Aerial#257]
Now that the screensaver is using cached versions of each video, those can be replaced with sharper versions. I have applied a sharpen filter to each video in AE and re-rendered them, which should make these a little better looking on retina displays.

This is by no means a resolution increase and they still look blurry, but the improvements are noticeable. If anyone wants the videos, download them here: goo.gl/q8lTBN (will take a while to upload)

To replace the files, just drop these into /Library/Caches/Aerial/
File size is almost double, but if you think it's worth it, you are welcome to use these.

Here are two screenshots comparing before and after:
![01-old](https://cloud.githubusercontent.com/assets/7927870/18022984/eb6ad328-6beb-11e6-8b5e-1af807b424f7.jpg)
![01-sharp](https://cloud.githubusercontent.com/assets/7927870/18022987/ebc4da1c-6beb-11e6-8a4a-0e691660416f.jpg)
![02-old](https://cloud.githubusercontent.com/assets/7927870/18022985/ebbe5a16-6beb-11e6-9ea1-de15bc0e444e.jpg)
![02-sharp](https://cloud.githubusercontent.com/assets/7927870/18022986/ebc49ebc-6beb-11e6-8ba6-05374c0f3ba3.jpg)

**Comment by jaknudsen** [comment]
Thanks for your effort!

**Comment by jstheoriginal** [comment]
Thanks for this!

**Comment by sagz** [comment]
Thank you!

**Comment by Misophistful** [comment]
Thanks, these are great!

**Comment by Sasha-Rose** [comment]
I have converted 6 people to use this, it is awesome.

**Comment by CristianMoisei** [comment]
Happy to hear you guys are enjoying these. It's a shame Apple couldn't be bothered to film these at a higher resolution, but in the meantime we have to make do with solutions like these.

**Comment by JohnCoates** [comment]
Great work! I wonder if it would be trivial to add a sharpen filter using something like https://github.com/BradLarson/GPUImage2

**Comment by CristianMoisei** [comment]
I made these in AE and I tried to tailor the level of sharpness for each video so that it looks good, but not over the top (these still are low res and there's only so much you can squeeze out of them). So no point in adding the filter on top of the new videos.

If you meant doing this programatically for all users, instead of using pre-rendered videos, what you'd have to consider are performance issues. Is that processing framework not going to overload most computers and drain the battery if it has to constantly apply sharpening filters to 1080p videos for half an hour straight?

**Comment by JohnCoates** [comment]
I was proposing doing it programmatically for all users.

You pose a good question. As far as battery draining, I believe that users who run Aerial off of battery are in the minority. Even so, I don't think that a sharpening filter written as a GPU shader would actually add any negligible performance issues. If it was written as a CPU routine, I believe your point would be very valid. Either way it would definitely be an optional feature. Just throwing the idea out there since your results look very nice.

**Comment by CristianMoisei** [comment]
It can't hurt to have it as a toggle. If you do decide to try it out, I'd be happy to look at what values each video needs (since it's just a number in AE and I cannot translate it to whatever GPUImage2 uses).

**Comment by JohnCoates** [comment]
Okay I'll definitely pass it by you if I end up coding it. I've been
restructuring and cleaning up the code the last few days, it might not hurt
to add a new feature!

**Comment by CristianMoisei** [comment]
Sounds good. You can reach me at cristian@hyperion.co

**Comment by xianglifei** [comment]
Thank you

**Comment by deckikwok** [comment]
thanks man. gonna try. esp since i have download issues (even without behind proxy of my own)

**Comment by ccharlton** [comment]
Cool.

**Comment by psaniko** [comment]
Link to videos is broken, anyone care to re-upload?

**Comment by djELITE** [comment]
Getting a "404" when clicking on the link.

**Comment by glouel** [comment]
Since link is broken and we have 4K videos now, closing this.
