### ISSUE TITLE
Include a clock.

### ISSUE THREAD

**Issue by CristianMoisei** [JohnCoates/Aerial#258]
It would be awesome if this could also display the time, and while I know OSX offers the option to overlay a clock on top of the screensaver, I always hated how it is placed on a random location over it.

Would you consider including a proper clock on top of this? If so, I'd be happy to help figure out the design.

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/tag/v1.4.1beta2 now has a clock ;)

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
