### ISSUE TITLE
Cannot select options for the Screensaver

### ISSUE THREAD

**Issue by manosbar** [JohnCoates/Aerial#26]
![2015-10-27 7 38 22](https://cloud.githubusercontent.com/assets/7253164/10767071/164d8a52-7ce3-11e5-8362-622961a40396.png)

I use MacOS X 10.11.1 in a MacBook Pro (15-inch, Early 2011). Although the screensaver runs smoothly, I cannot select any options in the Screen Saver Options window (see attached screenshot, sorry for Greek letters!)

**Comment by manosbar** [comment]
For no apparent reason, I am now able to select from the list of the available locations. I changed nothing.

I just went off the WiFi, saw that it doesn't stream videos when my Mac is offline, and then it worked properly.
![2015-10-27 8 10 45](https://cloud.githubusercontent.com/assets/7253164/10767829/d3ca9716-7ce6-11e5-99c2-c8f7309b9961.png)

**Comment by tm1000** [comment]
This is happening for me as well. Seems to randomly glitch out

**Comment by alistairmcmillan** [comment]
If anyone is still struggling with this issue please try the newest release that amongst other things offering caching.

https://github.com/JohnCoates/Aerial/releases
