### ISSUE TITLE
Black Screen on MacOS Sierra 

### ISSUE THREAD

**Issue by Duckyz** [JohnCoates/Aerial#261]
Both in the preview window and the actual screen saver just shows a black screen

**Comment by alistairmcmillan** [comment]
Are you behind a firewall or proxy of some sort?

Also which version are you running? The latest beta which allows you to cache the videos might help you. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by Duckyz** [comment]
I'm using a VPN which seems to be causing the problem. Installing the beta and downloading the videos seem to have fixed it. Thanks

**Comment by alistairmcmillan** [comment]
Cool.Happy to help.  If you're happy then please close this issue.
