### ISSUE TITLE
Aerial and Sierra

### ISSUE THREAD

**Issue by ArthurGooding** [JohnCoates/Aerial#262]
I have really enjoyed the Aerial screen saver.  I hope you update it so it can be used with Sierra.

Arthur Gooding

**Comment by ons-mart** [comment]
Aerial on Sierra works fine for me.

**Comment by alistairmcmillan** [comment]
@ArthurGooding The screen saver works fine in Sierra. However there is a bug in Sierra that prevents the preview view working in System Preferences.

If you select Aerial in System Preferences you might be seeing an error message that says `You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` But just leave Aerial selected, close System Preferences and reopen it. The preview will then work.

You can read more about it here if you are curious...
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by f-bone** [comment]
it works eventually but produces crash error during installation.

**Comment by alistairmcmillan** [comment]
@f-bone Is the crash error on your Hackintosh or one of your Apple Macs?

Can you show us a screenshot of the crash error you get on installation?

**Comment by f-bone** [comment]
its on the hackintosh. I installed Sierra yesterday using clover and looks good and stable - it used to run Yosemite flawlessly for the past two years+. (240GB SSD, Core2Duo E7600, 460GTX, nvidia web drivers, 8GB ram). 

on topic:
I just tried installing Aerial again on top of the existing installation and provide you with the requested screenshot - no errors this time. Maybe the crash-error-message was a hackintosh glitch---

**Comment by alistairmcmillan** [comment]
@f-bone I do think this might be a Hackintosh related glitch. The bug you reported before is unlike anything else that other users have reported. So what actually crashed this time? Was it the screen saver, System Preferences, the operating system itself?

@ArthurGooding Did you have any luck getting it to work under Sierra?

**Comment by f-bone** [comment]
I think it was maybe System Preferences related due to unrecognised developer or smt. Cant be sure of course just guessing.. Seems nice and stable now.

**Comment by JimmyPastel** [comment]
I can't make it work, correct install and I see preview, but when the screensaver starts only black screen.

Imac 12.1, Sierra clean install

**Comment by alistairmcmillan** [comment]
@JimmyPastel Are you behind a proxy or firewall by any chance?

Which version of the screensaver did you try? Could you try the latest beta version and see if it'll let you cache the videos? https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by RVenture** [comment]
Just got really excited to use this. Downloaded latest and it just displays an image. The images rotate but the video doesn't seem to play. Sierra 10.12, MacBook Pro.

**Comment by alistairmcmillan** [comment]
@RVenture What do you have selected in the list at the left of the Screen Saver panel?

<img width="233" alt="screen shot 2016-09-30 at 20 36 15" src="https://cloud.githubusercontent.com/assets/125896/19004391/ae6b2b4e-874d-11e6-84ad-dd1a7f530107.png">

**Comment by RVenture** [comment]
Never mind! Just needed time to load. Really excited to use this. Any chance of doing a Space on like the Apple TV space app?

**Comment by MatsCarvalho** [comment]
Mine isn't working at all. It stays about 30 seconds in a black screen then when the video starts it freezes almost immediately. Same thing happens in the preview.

**Comment by alistairmcmillan** [comment]
@MatsCarvalho Which version do you have installed? Do you have the latest beta? https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

If so, have you tried caching the videos?

**Comment by MatsCarvalho** [comment]
@alistairmcmillan 1.2 Beta 5, I deleted the version I was running and installed the lasted yesterday, still doesn't work. Yes, I have tried caching it, but it says "Connection fail: Error Domain=NSURLErrorDomain Code=-1001" and some other word I can't read.

<img width="1440" alt="captura de tela 2016-10-06 as 12 07 24" src="https://cloud.githubusercontent.com/assets/22651557/19157980/76870c24-8bbd-11e6-84dc-7c2be2235e26.png">

**Comment by alistairmcmillan** [comment]
@MatsCarvalho Looks like you are behind a firewall or proxy then that is blocking your access to the videos. Do you have anything like LittleSnitch installed? Or if its a laptop, can you try another wifi network?

**Comment by MatsCarvalho** [comment]
@alistairmcmillan Oh I see, I'm actually in my university and here there's a few things blocked, I didn't know this would be blocked. Anyway, I'll have to try caching at home then, see if it works. Thank you for helping.
