### ISSUE TITLE
Screensaver Creates Excessive Downloading

### ISSUE THREAD

**Issue by AfricanTechie** [JohnCoates/Aerial#267]
Awesome screensaver.  I just have the issue of noticing excessive downloading of content or something when the screensaver is running.  It runs into the 100's of MB each time it runs.  I've had to disable it just to save my data plan.  Isn't it possible to download all content and keep it locally rather than downloading something at each time the screensaver runs?

Please advise,

AfricanTechie

**Comment by alistairmcmillan** [comment]
If you try the latest beta you'll be able to cache the videos on your Mac.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by AfricanTechie** [comment]
Thanks, let me give it a shot ASAP.

**Comment by AfricanTechie** [comment]
Superb - all done and working like a charm without additional downloads while running...  Thank you very much for the prompt response and solution.
