### ISSUE TITLE
You cannot use the Aerial screen saver with this version of OS X...

### ISSUE THREAD

**Issue by tomlube** [JohnCoates/Aerial#269]
Just says it doesn't work with this version of macOS and to check with you to get a new one :(

**Comment by guylepage3** [comment]
seems to be working for me fine.

**Comment by alistairmcmillan** [comment]
It's a bug in macOS (it's been there for a versions). It only affects the preview. The screensaver itself will launch and work okay. Just select Aerial, close System Preferences and reopen it. Aerial will be working.

You can read more here if you want. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by tomlube** [comment]
It's definitely not only affecting the preview. It doesn't work when the screensaver comes up. I reinstalled it and it's still not working.

**Comment by alistairmcmillan** [comment]
@tomlube You get that error when the screensaver launches full screen after however many minutes of inactivity? Or do you get just a blank screen?

**Comment by tomlube** [comment]
That error message pops up on the full screen, with system clock after inactivity and/or by using a hot corner.

**Comment by alistairmcmillan** [comment]
@tomlube That's strange. Do you have something installed that is cycling through multiple screensavers? Perhaps do you have something that is loading and drawing a screensaver as your desktop?

The reason for this error is that there are multiple versions of the Swift libraries, and you can get a situation where macOS (and OSX before it) loads a specific version of the Swift libraries for something and then tries to run software written in Swift with those libraries even if they aren't the correct version.

So if you're getting this error in full screen then something must have loaded a version of the Swift libraries into the process that draws the screensaver full screen.

**Comment by tomlube** [comment]
No, I don't have anything of the sort. In fact I never used screen savers at all before I found out about this project. I just restored my hard drive through Migration assistant though.

**Comment by tomlube** [comment]
https://i.imgur.com/HooNUOp.jpg

**Comment by alistairmcmillan** [comment]
If you open Activity Monitor is there a ScreenSaverEngine process? If so kill that and try again.

**Comment by satpalsharma** [comment]
I'm facing the same issue. Did you manage to resolve it?

**Comment by alistairmcmillan** [comment]
@satpalsharma Select Aerial, close System Preferences, then reopen System Preferences. Let us know if you're still getting the same error.

**Comment by satpalsharma** [comment]
@alistairmcmillan Cool.. that resolved it. thanks.

**Comment by alistairmcmillan** [comment]
@tomlube Still having this problem?

**Comment by ccharlton** [comment]
Yep, the fix was to close and reopen the System Preferences window. :) Lovely screensaver, thank you!

**Comment by sashcraft** [comment]
Have tried closing and reopening SysPrefs, rebooting, deleting and reinstalling. Still get the message.

OSX 10.12.2 (was happening on 10.12.1 as well), XCode 8.2.1. Happy to provide any further debug information you might need.

**Comment by alistairmcmillan** [comment]
@sashcraft Did you select Aerial before closing System Preferences?

**Comment by sashcraft** [comment]
Yes.

**Comment by alistairmcmillan** [comment]
@sashcraft If you don't mind, with Aerial selected in System Preferences and with the error message in the preview window, could you launch Activity Monitor, select the System Preferences process, click the Info icon, select "Open Files and Ports", select all the files listed and send me a copy (alistairmcmillan75@gmail.com) or post it in a comment here (whichever you're most comfortable with). That should help work out why this isn't working for you.

![screenshot 2016-12-28 17 20 31](https://cloud.githubusercontent.com/assets/125896/21527281/01aeea42-cd22-11e6-8bfc-0d019f075152.png)

@tomlube If you wouldn't mind doing the same if you're still having the problem.

**Comment by alistairmcmillan** [comment]
@sashcraft @tomlube If you don't want to share the full list, I think we only really need the lines that mention "swift".

**Comment by pquodling** [comment]
I am seeing this as well, on a mid 2011 imac, running SIerra 10.12.2
Per above instructions.

cwd
/
txt
/Applications/System Preferences.app/Contents/MacOS/System Preferences
txt
/usr/share/icu/icudt57l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAppearance.car
txt
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
txt
/Applications/System Preferences.app/Contents/Resources/ToolbarTopSites.pdf
txt
/System/Library/PreferencePanes/Keyboard.prefPane/Contents/Resources/SystemPrefs_Keyboard@2x.png
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/System/Library/Fonts/SFNSText.ttf
txt
/System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
txt
/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
txt
/System/Library/Extensions/AMDRadeonX3000GLDriver.bundle/Contents/MacOS/AMDRadeonX3000GLDriver
txt
/System/Library/Extensions/AMDRadeonX3000GLDriver.bundle/Contents/MacOS/ATIRadeonX3000SCLib.dylib
txt
/System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
txt
/System/Library/PreferencePanes/Appearance.prefPane/Contents/Resources/Assets.car
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/Desktop_ScreenSaver.png
txt
/System/Library/PreferencePanes/Dock.prefPane/Contents/Resources/Dock@2x.png
txt
/System/Library/PreferencePanes/Dock.prefPane/Contents/Resources/Dock.png
txt
/System/Library/PreferencePanes/Keyboard.prefPane/Contents/Resources/SystemPrefs_Keyboard.png
txt
/System/Library/PreferencePanes/Spotlight.prefPane/Contents/Resources/Assets.car
txt
/System/Library/PreferencePanes/Expose.prefPane/Contents/Resources/MissionControl@2x.png
txt
/System/Library/PreferencePanes/Trackpad.prefPane/Contents/Resources/SystemPrefs_Trackpad@2x.png
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/System/Library/PreferencePanes/InternetAccounts.prefPane/Contents/Resources/Assets.car
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/Desktop_ScreenSaver@2x.png
txt
/System/Library/PreferencePanes/Dock.prefPane/Contents/Resources/Dock.icns
txt
/System/Library/PreferencePanes/Expose.prefPane/Contents/Resources/MissionControl.png
txt
/System/Library/PreferencePanes/Localization.prefPane/Contents/Resources/SystemPrefs_Localization.tiff
txt
/System/Library/PreferencePanes/Security.prefPane/Contents/Resources/SystemPreferences_Security.tiff
txt
/System/Library/PreferencePanes/Notifications.prefPane/Contents/Resources/NotificationsPref.tiff
txt
/System/Library/PreferencePanes/DigiHubDiscs.prefPane/Contents/Resources/CDs.tiff
txt
/System/Library/PreferencePanes/Displays.prefPane/Contents/Resources/DisplaysPrefIcon.tiff
txt
/System/Library/PreferencePanes/EnergySaver.prefPane/Contents/Resources/EnergySaverIcon.tiff
txt
/System/Library/PreferencePanes/Mouse.prefPane/Contents/Resources/SystemPrefs_Mouse@2x.png
txt
/System/Library/PreferencePanes/Mouse.prefPane/Contents/Resources/SystemPrefs_Mouse.png
txt
/System/Library/PreferencePanes/Trackpad.prefPane/Contents/Resources/SystemPrefs_Trackpad.png
txt
/System/Library/PreferencePanes/PrintAndScan.prefPane/Contents/Resources/PrintScanPrefIcon.tiff
txt
/System/Library/PreferencePanes/Sound.prefPane/Contents/Resources/SoundPrefIcon.tiff
txt
/System/Library/PreferencePanes/StartupDisk.prefPane/Contents/Resources/SystemPrefs_StartupDisk.tiff
txt
/System/Library/PreferencePanes/iCloudPref.prefPane/Contents/Resources/iCloud_Pref.tiff
txt
/System/Library/PreferencePanes/AppStore.prefPane/Contents/Resources/SystemPrefs_AppStore.tiff
txt
/System/Library/PreferencePanes/Network.prefPane/Contents/Resources/Network.tiff
txt
/System/Library/PreferencePanes/Network.prefPane/Contents/Resources/Network.icns
txt
/System/Library/PreferencePanes/Bluetooth.prefPane/Contents/Resources/BluetoothAqua.tiff
txt
/System/Library/PreferencePanes/Extensions.prefPane/Contents/Resources/ExtensionsPref.tiff
txt
/System/Library/PreferencePanes/SharingPref.prefPane/Contents/Resources/SystemPrefs_Sharing@2x.png
txt
/System/Library/PreferencePanes/SharingPref.prefPane/Contents/Resources/SystemPrefs_Sharing.png
txt
/System/Library/PreferencePanes/Accounts.prefPane/Contents/Resources/SystemPreferences_Accounts.tiff
txt
/System/Library/PreferencePanes/ParentalControls.prefPane/Contents/Resources/ParentalControls.tiff
txt
/System/Library/PreferencePanes/Speech.prefPane/Contents/Resources/Siri.icns
txt
/System/Library/PreferencePanes/DateAndTime.prefPane/Contents/Resources/DateTime@2x.png
txt
/System/Library/PreferencePanes/DateAndTime.prefPane/Contents/Resources/DateTime.png
txt
/System/Library/PreferencePanes/TimeMachine.prefPane/Contents/Resources/SystemPrefs_Backup@2x.png
txt
/System/Library/PreferencePanes/TimeMachine.prefPane/Contents/Resources/SystemPrefs_Backup.png
txt
/System/Library/PreferencePanes/UniversalAccessPref.prefPane/Contents/Resources/UniversalAccessPrefIcon.tiff
txt
/Library/PreferencePanes/Flash Player.prefPane/Contents/Resources/FlashPlayerSettings.icns
txt
/Library/PreferencePanes/OSXFUSE.prefPane/Contents/Resources/OSXFUSE.icns
txt
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/deploy/JavaControlPanel.prefPane/Contents/Resources/Java7VM.icns
txt
/System/Library/Fonts/Helvetica.dfont
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FunctionRowAppearance.car
txt
/System/Library/Screen Savers/FloatingMessage.saver/Contents/MacOS/FloatingMessage
txt
/System/Library/PreferencePanes/Keyboard.prefPane/Contents/Resources/Keyboard.icns
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/MacOS/DesktopScreenEffectsPref
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBAppDefPlugin.ilmbplugin/Contents/MacOS/iLMBAppDefPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBFolderPlugin.ilmbplugin/Contents/MacOS/iLMBFolderPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBAperturePlugin.ilmbplugin/Contents/MacOS/iLMBAperturePlugin
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/screen-preview-shadow@2x.png
txt
/System/Library/PreferencePanes/UniversalAccessPref.prefPane/Contents/Resources/UniversalAccessPref.icns
txt
/System/Library/PreferencePanes/AppStore.prefPane/Contents/Resources/appStore.icns
txt
/System/Library/PreferencePanes/DigiHubDiscs.prefPane/Contents/Resources/cd.icns
txt
/System/Library/PreferencePanes/DateAndTime.prefPane/Contents/Resources/DateAndTime.icns
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/DesktopScreenEffectsPref.icns
txt
/System/Library/PreferencePanes/Displays.prefPane/Contents/Resources/Displays.icns
txt
/System/Library/PreferencePanes/EnergySaver.prefPane/Contents/Resources/EnergySaver.icns
txt
/System/Library/PreferencePanes/Extensions.prefPane/Contents/Resources/Extensions.icns
txt
/System/Library/PreferencePanes/Appearance.prefPane/Contents/Resources/GeneralPrefsIcons.icns
txt
/System/Library/PreferencePanes/iCloudPref.prefPane/Contents/Resources/iCloud.icns
txt
/System/Library/PreferencePanes/InternetAccounts.prefPane/Contents/Resources/InternetAccountsIcons.icns
txt
/System/Library/PreferencePanes/Localization.prefPane/Contents/Resources/Localization.icns
txt
/System/Library/PreferencePanes/Expose.prefPane/Contents/Resources/Expose.icns
txt
/System/Library/PreferencePanes/Mouse.prefPane/Contents/Resources/Mouse.icns
txt
/System/Library/PreferencePanes/Notifications.prefPane/Contents/Resources/Notifications.icns
txt
/System/Library/PreferencePanes/ParentalControls.prefPane/Contents/Resources/Family.icns
txt
/System/Library/PreferencePanes/PrintAndScan.prefPane/Contents/Resources/PrintScanPref.icns
txt
/System/Library/PreferencePanes/Security.prefPane/Contents/Resources/FileVault.icns
txt
/System/Library/PreferencePanes/SharingPref.prefPane/Contents/Resources/SharingPref.icns
txt
/System/Library/PreferencePanes/Sound.prefPane/Contents/Resources/SoundPref.icns
txt
/System/Library/PreferencePanes/Spotlight.prefPane/Contents/Resources/SpotlightPrefIcons.icns
txt
/System/Library/PreferencePanes/StartupDisk.prefPane/Contents/Resources/StartupDiskPref.icns
txt
/System/Library/PreferencePanes/TimeMachine.prefPane/Contents/Resources/TimeMachine.icns
txt
/System/Library/PreferencePanes/Trackpad.prefPane/Contents/Resources/Trackpad.icns
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/MacOS/ScreenEffects
txt
/System/Library/PrivateFrameworks/Slideshows.framework/Versions/A/Slideshows
txt
/System/Library/Frameworks/ScreenSaver.framework/Versions/A/ScreenSaver
txt
/System/Library/Frameworks/PubSub.framework/Versions/A/PubSub
txt
/System/Library/PrivateFrameworks/Slideshows.framework/Versions/A/Frameworks/OpusFoundation.framework/Versions/A/OpusFoundation
txt
/System/Library/PrivateFrameworks/Slideshows.framework/Versions/A/Frameworks/OpusKit.framework/Versions/A/OpusKit
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBAperture31Plugin.ilmbplugin/Contents/MacOS/iLMBAperture31Plugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBFinalCutPlugin.ilmbplugin/Contents/MacOS/iLMBFinalCutPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBGarageBandPlugin.ilmbplugin/Contents/MacOS/iLMBGarageBandPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiMoviePlugin.ilmbplugin/Contents/MacOS/iLMBiMoviePlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiPhoto8Plugin.ilmbplugin/Contents/MacOS/iLMBiPhoto8Plugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiPhotoPlugin.ilmbplugin/Contents/MacOS/iLMBiPhotoPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiTunesPlugin.ilmbplugin/Contents/MacOS/iLMBiTunesPlugin
txt
/Library/Frameworks/iTunesLibrary.framework/Versions/A/iTunesLibrary
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBLogicPlugin.ilmbplugin/Contents/MacOS/iLMBLogicPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBMoviesFolderPlugin.ilmbplugin/Contents/MacOS/iLMBMoviesFolderPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBPhotoBooth2Plugin.ilmbplugin/Contents/MacOS/iLMBPhotoBooth2Plugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBPhotoBoothPlugin.ilmbplugin/Contents/MacOS/iLMBPhotoBoothPlugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBPhotosPlugin.ilmbplugin/Contents/MacOS/iLMBPhotosPlugin
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/screen-preview-shadow.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Floating@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Floating.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Flipup@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Flipup.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Reflections@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Reflections.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Origami@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/Origami.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/ShiftingTiles.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/corners@2x.png
txt
/usr/lib/dyld
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBAperturePlugin2012.ilmbplugin/Contents/MacOS/iLMBAperturePlugin2012
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiPhoto9Plugin.ilmbplugin/Contents/MacOS/iLMBiPhoto9Plugin
txt
/Library/Application Support/iLifeMediaBrowser/Plug-Ins/iLMBiPhotoPlugin2012.ilmbplugin/Contents/MacOS/iLMBiPhotoPlugin2012
txt
/System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
txt
/System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/Resources/tokruleLE.data
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/ShiftingTiles@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/SlidingPanels@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/SlidingPanels.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/PhotoMobile@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/PhotoMobile.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/HolidayMobile@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/HolidayMobile.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/PhotoWall@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/PhotoWall.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/VintagePrints@2x.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/VintagePrints.png
txt
/System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane/Contents/Resources/ScreenEffects.prefPane/Contents/Resources/corners.png
txt
/System/Library/Fonts/LucidaGrande.ttc
txt
/private/var/db/dyld/dyld_shared_cache_x86_64
0
/dev/null
1
/dev/null
2
/dev/null
3
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
4
/Users/peter/Library/Saved Application State/com.apple.systempreferences.savedState/data.data
5
/Users/peter/Library/Saved Application State/com.apple.systempreferences.savedState/windows.plist
6
/Users/peter/Library/Saved Application State/com.apple.systempreferences.savedState/window_1.data

**Comment by alistairmcmillan** [comment]
@pquodling Did you have Aerial selected when you grabbed that list? Cause the screensaver that actually seems to be loaded is FloatingMessage.saver. Neither Aerial or the Swift libraries required by Aerial are loaded at all.

If you did have Aerial selected, I'd suggest deleting it (check `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers` just in case you have multiple copies), downloading a fresh copy.

@sashcraft had an issue where the permissions were corrupted within the saver file on his Mac. A fresh copy fixed it.

**Comment by pquodling** [comment]
I checked and I had an aerial.saver in both /Library/Screen Savers, and in /Users/peter/Library/Screen Savers/ - deleted both, and reinstalled with homebrew - seems to work OK now.

**Comment by jsm296** [comment]
in case it helps, for me, I had to overlay the brew-installed version with the downloaded version in ~/Library/Screen Savers, then in the Preferences pane switch from Aerial to another, and then back.  Not sure what of all that actually made things work, but it works now...

**Comment by alistairmcmillan** [comment]
@jsm296 People are having this problem because there are multiple versions of the Swift libraries and System Preferences loads the Swift libraries once. It doesn't unload them and reload them for different plugins (it treats screen savers as plugins). So if you load a screen saver first that uses a version of the plugins that Swift doesn't use, then when you select Aerial it fails to run because System Preferences still has that wrong version loaded.

That's why selecting Aerial, closing and reopening System Preferences enables Aerial to run. Cause you're making sure System Preferences loads the right Swift libraries first.

The bug was reported to Apple months ago.

For now the way to fix it is simply select Aerial, close and reopen System Preferences.

**Comment by jonathanmorgan** [comment]
That did not work for me.  I uninstalled, restarted, installed using brew, went to preferences, selected aerial, closed preferences, reopened preferences, it still did not work.  i restarted computer, opened preferences, still not working.  Then I installed from download over top of brew install in ~/Library/Screen Savers.  No dice.  I switched to some other screen saver, then back, no restarting preferences, and it started working.  So, just stopping and restarting preferences did not work for me.  I am not sure if it was that the brew version was corrupted and the downloaded one was not, or the switch to another and back, but either one or both of those steps in addition were needed to get it working for me (10.12.2 on 2013 Mac mini).

**Comment by hairarrow** [comment]
I was having this issue and it went away after launching the screen saver a couple times (with Alfred). 

These are the steps I went through:
1. Select Aerial Screensaver
2. Close settings
3. Launch screen saver (with something life alfred, hot corners, or set your screen saver timer to a minute...)
4. Repeat step 3 a couple of times
5. Go back to settings and check if your computer is on fire (screen saver options and preview should work...?)

**Comment by alistairmcmillan** [comment]
I hate Apple. I'm tired of explaining this bug. Last time. Never again.

There are multiple versions of the Swift libraries. Version 1.0, 1.1, 1.2, 2.0 and 3.0.

System Preferences will only load one version of the Swift libraries. Once it has loaded one version it will not load another. Whichever version of the Swift libraries it loads first, that's it until you close System Preferences, the process dies and start again from scratch.

So if you open System Preferences and load a screensaver that uses version 1.0 of the Swift libraries, System Preferences loads version 1.0 of the Swift libraries. And then any screensaver that uses 1.1 or 1.2 or 2.0 or 3.0 of the Swift libraries will show that "You cannot use the XXX screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver." error.

Similarly if you open System Preferences to a screensaver that uses version 2.0 of the Swift libraries, System Preferences loads version 2.0 of the libraries and then any screensaver that uses 1.0, 1.1, 1.2 or 3.0 will display the "You cannot use the XXX screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver." error.

And so on and so forth for every combination.

If you would like to help please log a bug with Apple [here](https://bugreport.apple.com) or [here](http://www.apple.com/feedback/) or bug an Apple employee on Twitter or phone your Senator or send smoke signals or whatever. I reported this to them back in March through every avenue I could think of. They have done a grand total of diddly-squat to fix it.
