### ISSUE TITLE
Doesn't play - get "play button" crossed out even in Prefs pane.

### ISSUE THREAD

**Issue by alienmeatsack** [JohnCoates/Aerial#27]
Note that this same screensaver works perfectly on my identical iMac using identical Mac OS version at home. Not sure what the problem is. Screen shots attached.
![img_2819](https://cloud.githubusercontent.com/assets/8703414/10769429/0d281200-7cb4-11e5-89a0-f4485a4c75d8.JPG)
![img_2820](https://cloud.githubusercontent.com/assets/8703414/10769431/0e5b3ddc-7cb4-11e5-8d78-f5c265469fb5.JPG)

**Comment by alienmeatsack** [comment]
"Current" iMac 27" purchased a few months back.
![about this mac 2015-10-27 14-07-58](https://cloud.githubusercontent.com/assets/8703414/10769451/23b27fba-7cb4-11e5-9e48-026fd8af29ef.jpg)

**Comment by JaNd3r** [comment]
It seems, that the videos cannot be downloaded if you Mac is behind a proxy.

**Comment by alienmeatsack** [comment]
I'm not behind a proxy on either Mac. I've got AT&T uVverse here at home and COX cable at work. And my Mac has been freed from most all the office's usual rules since I'm the IT guy so I have unfettered access.

Is there some way for me to troubleshoot what is blocking or being blocked, maybe a direct link to one of the videos so I can test it, or something I can look up in our firewall to see if it's being stopped?

**Comment by JaNd3r** [comment]
The following URL is called to retrieve a list of video URLs:
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

**Comment by alienmeatsack** [comment]
Hmm... I just tried 2 of those video direct links from here, where the screen saver is failing, and got the prompt to download each no problem.

I see nothing in my firewall logs that says it's being blocked or stopped either. Any suggestions on how I might troubleshoot it further? Or help you in any way?

**Comment by alistairmcmillan** [comment]
Hi @alienmeatsack have you tried a recent beta? Is it working for you now?

**Comment by alienmeatsack** [comment]
Sorry for the delay, this notification came in while I was sick last week. I am downloading the latest beta and will report back my results!

**Comment by alienmeatsack** [comment]
![desktop screen saver 2016-02-11 08-19-28](https://cloud.githubusercontent.com/assets/8703414/12978697/3e6d491a-d098-11e5-9b00-f5dac589ded0.jpg)
Appears to work now in 1.2 B5 for me. I will let it run for a few days and report back but it appears to be fixed now. Thank you!

**Comment by alistairmcmillan** [comment]
Glad to hear it's work @alienmeatsack
