### ISSUE TITLE
Uses GB upon GB of data while in screen saver mode

### ISSUE THREAD

**Issue by CRiva** [JohnCoates/Aerial#271]
I have noticed over the past couple of months that my Mac, which I don't touch often but leave on, showed tens to hundred of times more "Data Received" than Data Sent in Activity monitor. 

I could not figure out what it was until I used the little snitch app, which showed a large amount of data usage from my screen-saver after sleeping for a few hours. 

I open this issue to ask that you please make it more known that this application **Streams** the screen savers, and doesn't store them locally.

I've been hunting the issue for months and am disappointed to see that this beautiful app here is the problem.

Thank you.

**Comment by alistairmcmillan** [comment]
@CRiva Which version of the screen saver are you running? I know this doesn't really help you now but the [current beta](https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5) (which is now over a year old) includes the ability to cache the MOV files and as far as I can tell it's set to cache by default.

https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Controllers/Preferences.swift#L45

**Comment by blackxored** [comment]
This started happening for me as well. Thing goes crazy to 7GB and more.

**Comment by joshlewis** [comment]
The beta needs to become the main version ASAP. They've just released a whole new set of videos.

**Comment by JohnCoates** [comment]
It's been linked as the main version for a while from the Readme https://github.com/JohnCoates/Aerial
