### ISSUE TITLE
Screen Saver Options freezes

### ISSUE THREAD

**Issue by elstgav** [JohnCoates/Aerial#272]
I noticed over the past few days the screensaver has been freezing, so I updated to 1.2 Beta 5 and now it works. Except when I try to open the screensaver options, System Preferences freezes. Happens every time I try to open the options panel.
![image](https://cloud.githubusercontent.com/assets/674092/20985224/6aab2340-bc78-11e6-8045-f735a77c9683.png)

**Comment by alistairmcmillan** [comment]
Do you have some kind of firewall/proxy software installed on your Mac (for example Little Snitch)? Or are you perhaps on a network behind a firewall/proxy?

**Comment by elstgav** [comment]
No I don’t, and I’ve tried it on multiple networks; still crashing consistently.

**Comment by JacobHuschilt** [comment]
I have the same issue.

**Comment by alistairmcmillan** [comment]
@elstgav @JacobHuschilt Can you get to http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json in a browser?

You should see a bunch of text like...

```
[
   {
      "id" : "73F3F654-9EC5-4876-8BF6-474E22029A49",
      "assets" : [
         {
            "url" : "http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov",
            "accessibilityLabel" : "Greenland",
            "type" : "video",
            "id" : "D388F00A-5A32-4431-A95C-38BF7FF7268D",
            "timeOfDay" : "day"
         },
         {
            "url" : "http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D011_D009_SIGNCMP_v15_6Mbps.mov",
            "accessibilityLabel" : "Dubai",
            "type" : "video",
            "id" : "2F11E857-4F77-4476-8033-4A1E4610AFCC",
            "timeOfDay" : "night"
         },
```

**Comment by elstgav** [comment]
Yeah I'm able to view that

**Comment by elstgav** [comment]
Strange, I'm no longer getting the freezing issue. Not sure when it resolved though

**Comment by JacobHuschilt** [comment]
I am also able to view that. 
I am also no longer getting this issue, though I'm not sure when it was resolved?

**Comment by alistairmcmillan** [comment]
I'm not sure how you can get into a situation where you have at least one of the videos (preview window populated) but you don't have the JSON source file (listbox empty).

Some sort of network glitch or Apple's CDN servers not responding correctly.

It's strange.

But if it's working for both of you now, are you okay with this issue being closed?

**Comment by elstgav** [comment]
Yeah, I think it can close. One of those annoying self-resolving mystery bugs…
