### ISSUE TITLE
Clock is not aligned by center

### ISSUE THREAD

**Issue by devlato** [JohnCoates/Aerial#273]
Hey, 

the clock is not aligned by center on 15' MacBook, it is shifted to the left a bit. Seems like currently the clock position is calculated based on the resolution of 13' MacBook (maybe there is some hardcode here instead of fair calculations?).

**Comment by alistairmcmillan** [comment]
@devlato The clock is not part of John's screen saver. It's part of macOS.

I think it's always shown off centre. Apple designed it that way.
