### ISSUE TITLE
Cached video files are deleted

### ISSUE THREAD

**Issue by sulifluffy** [JohnCoates/Aerial#274]
hey, 

About every 10 days the cached videos folder gets reset and I have to download all the videos again.  Is this due to the autoload by Apple?

-S

**Comment by alistairmcmillan** [comment]
Apple aren't involved. The screen saver won'5 be doing this either.

Is your Mac perhaps short of space? macOS is designed to sacrifice things in the Cache folder first if it is running out of space.

**Comment by sulifluffy** [comment]
I completely forgot that I have cleanmymac scheduled to run once a week. It clears all the cache files which includes the videos.

Thanks for your help
