### ISSUE TITLE
Low resolution video

### ISSUE THREAD

**Issue by AndrewMoehrkeXamarin** [JohnCoates/Aerial#275]
The videos appear to be low res and don't look nearly as good as they do on my AppleTV/TV combo at home

**Comment by sulifluffy** [comment]
https://drive.google.com/drive/folders/0B50igKAfYyPCcDdQV25yc21sQzQ

These are the hi-res versions of the videos. Download them and place them in the Aerial cache folder

**Comment by alistairmcmillan** [comment]
The videos that John's screensaver plays on your Mac are exactly the same videos from Apple's servers that play on your Apple TV.

The videos linked above aren't higher resolution. Someone just took Apple's videos and ran a sharpness filter over them. As Cristian, the guy who created them, says "This is by no means a resolution increase and they still look blurry, but the improvements are noticeable."

**Comment by juandesant** [comment]
Also, see that the result of the discussion on Issue #257 (the one where Cristian provides the link to the enhanced videos) is that the improvement will be done programatically via OpenGL/Metal filtering, so that battery impact is small, and no additional downloads are required.
