### ISSUE TITLE
Some videos freeze... 

### ISSUE THREAD

**Issue by Lapsusone** [JohnCoates/Aerial#278]
Only the first image of the video is shown on the screensaver, but there's no playback at all for new videos. Old videos do play correctly. All videos are correctly cached. 

When previewing using the button in the setting panel, new videos play normally.

**Comment by 4np** [comment]
No issues here, there work fine for me. Are you running the latest version?

![pasted_image_20_12_16_08_57](https://cloud.githubusercontent.com/assets/1049693/21342479/6dd9971c-c692-11e6-9a03-1f6096a5cd56.jpg)

You could try resetting your cache settings and/or Download and cache all videos?

**Comment by Lapsusone** [comment]
I've done all that. Running latest version. Now it seems t only halt playback with one video from Dubai day, though I've tried to clear cache multiple times.

**Comment by Syden10** [comment]
To share some light on what has done the trick for me. 

- Cache everything first.

- When you catch one of those vids which will just get stuck at the start image, do the following:

  1. Go to screensaver settings, deselect aerial for any other screensaver and re-select it back.

  2. Test if it worked by turning the screensaver on/off until you reach that same video, it should now play fine. **(optional)**

**Comment by jayrosen1576** [comment]
Most likely a bandwidth issue. On one network (work) I had less than 5Mbps bandwidth and experienced the same thing you did on all videos that were not cached. However, at Starbucks all videos played fine, even those not cached. So it seems that the playback needs a higher bandwidth to keep the videos going.

**Comment by alistairmcmillan** [comment]
@jayrosen1576 Thanks, but people are getting this even with all the videos cached. Very confusing.

@Lapsusone I'm randomly getting this with one Dubai video. The one titled comp_DB_D008_C010_v04_6Mbps.mov. Is that the one that sticks for you? Strangely sometimes it does play.

**Comment by Syden10** [comment]
I have the same issue, I thought it was fixed but vids seem to freeze randomly. Currently re-installed latest version and re-chaching vids as we speak. Will try with different bandwidths and see if anything changes as well (before the latest vid addition I had no issues). Thank you all.

**Comment by Lapsusone** [comment]
@alistairmcmillan That one among others. 

As @Syden10 says, it seems to freeze randomly. (I also have the last version, and videos are all cached and play fine when played from the Finder).

**Comment by alistairmcmillan** [comment]
Just looking into this just now. My theory is that it's something to do with the size of the video files. I only seem to get stuck video with the larger 450+ MB videos.

Funnily enough though right now on a Mac with two screens attached I have comp_HK_H004_C008_v10_6Mbps.mov frozen on one screen and playing on the second perfectly okay.

**Comment by richardfive** [comment]
Same here, it's random but indeed with the newer files. Using latest version and everything cached. Sometins it freezes at the start and sometimes in the middle.

**Comment by 4np** [comment]
So that would mean the following 450Mb+ videos would be problematic:

```
~/Library/Caches/Aerial $ find . -type f -size +450M
./comp_HK_H004_C008_v10_6Mbps.mov
./comp_HK_H004_C013_t9_6M_HB_tag0.mov
./comp_LA_A008_C004_ALT_v33_6Mbps.mov
~/Library/Caches/Aerial $ 
```

Have you tried playing those cached video files in quicktime? Do they play fine in there or do they stutter as well?

```
$ open ~/Library/Caches/Aerial/comp_HK_H004_C008_v10_6Mbps.mov
``` 

Might it be hardware related? What kind of machine do you have?

**Comment by alistairmcmillan** [comment]
@4np Who are you asking? Me?

**Comment by 4np** [comment]
To anybody who is experiencing issues ;)

**Comment by Syden10** [comment]
Here they all seem to play fine through quicktime, although I do recognize some of them for being frozen previously, even though a second try seems to play them fine as well until some other gets stuck. Machine is late 2011 13" MBP (crappy intel HD 3000 - topped to 512), freezes happen both with external or native screen only. Thanks for your time.

**Comment by the-saint** [comment]
Same issue here. Old videos work fine. New ones are frozen. Late 27-inch iMac, 3.2 GHz Intel Core i5, 24 GB Ram, running the videos cached.

**Comment by DasBlatz** [comment]
have also this freezing issue of the new videos on my mid 2012 macbook, and on my Mac mini too

**Comment by LtlKing** [comment]
Videos are freezing for me as well. I'm using a 2015 15'' MacBook Pro. I appreciate the OP bring up this issue... really hoping for a solution.

**Comment by vit0rg** [comment]
Same here, freezing sometimes @ MacBook Pro (Retina, 15-inch, Mid 2014) / 2,5 GHz Intel Core i7 / 16 GB 1600 MHz DDR3 / NVIDIA GeForce GT 750M 2048 MB Intel Iris Pro 1536 MB.

**Comment by timmartinez** [comment]
I have the same problem. Certain videos will always hang. One that is consistent is comp_DB_D008_C010_v04_6Mbps.mov. I believe it's all of the newer ones.

I'm running macOS Sierra 10.12.3 on a MacBook Pro (Retina, 15-inch, Mid 2014) / 2.8 GHz Intel Core i7, 16 GB 1600 MHz DD3, NVIDIA GeForce GT 750M 2048 MB

**Comment by Yasser** [comment]
Same problem with all of the new videos.

iMac 5K, 27-inch, Late 2014 / 4 GHz Intel Core i7 / 16 GB DDR3 / AMD Radeon R9 M295X 4096 MB

**Comment by bigheadjer** [comment]
Videos freezing for me on 15" Mid 2014 MacBook Pro / 2.5GHz Intel Core i7 / 16GB DDR3 / Intel Iris Pro 1536MB.

These are the videos are that have freezen on me (so far):

comp_C007_C004_0824AJ_001_v01_6M_HB_tag0.mov
comp_DB_D008_C010_v04_6Mbps.mov
comp_LA_A006_C008_t9_6M_HB_tag0.mov
plate_G002_C002_BG_t9_6M_HB_tag0.mov

Not all of them are bigger than 450MB.

**Comment by mjgold** [comment]
The videos are freezing me for as well. First time installation, videos are cached. I hope this can be resolved. Would be great to use the program.

**Comment by 4np** [comment]
I wonder if this could be related to _macOS Sierra_? I am running on _El Capitan_ without any issues...

**Comment by nixis** [comment]
Same problem with all of the new videos.
They stuck after few frames.

![bildschirmfoto 2017-02-09 um 07 45 14](https://cloud.githubusercontent.com/assets/950581/22772225/c168054a-ee9b-11e6-95db-eb1a3114ad42.png)

I use the latest version of Aerial

**Comment by pminardo** [comment]
Love the screensaver but experiencing this same problem with Los Angeles - Day - Three. All videos have been pre-downloaded using the Cache settings screen. Thanks!

**Comment by michsch** [comment]
I have the same issue for all videos. Using the latest version (1.2) and every video freezes at the beginning. I just see the first frame.

<img width="581" alt="about_this_mac" src="https://cloud.githubusercontent.com/assets/357387/23309802/6ad1f5bc-fab0-11e6-92f7-1f2fa42217ff.png">

**Comment by jdavidbakr** [comment]
I'm having the same issue, videos randomly freezing.  I have 2 monitors and usually it's just one video. I don't think it's the video because the same video has played earlier and/or will play later.

**Comment by Syden10** [comment]
Great news! seems fixed after 10.12.4 update, at least on my end. Thanks to all, regards.

**Comment by Lapsusone** [comment]
So far so good for me to. 😊

**Comment by bigheadjer** [comment]
Just updated to 10.12.4 and reenabled all the videos in the Screen Saver options and haven't had a freeze since.  👍

**Comment by the-saint** [comment]
Still freezing here. Los Angeles Day 3 froze after I re-enabled it. I had previously disabled everything except Iceland to keep it from freezing.

**Comment by frumbert** [comment]
Sierra 10.12.4, dual monitors on 2015MBP, display different on each monitor option.

ALL videos are only every showing the first frame only. Resetting caches not a fix. Resetting in a fast-internet area not a fix.

Seems to be worse SINCE upgrading to 10.12.4, in opposition to previous comments...

**Comment by yogthos** [comment]
I noticed that this only happens when enabling local caching for videos. When I turn cache off, I don't see the freezing. I'm updated to the latest version.

**Comment by the-saint** [comment]
I run my iMac overnight for backup. Morning is when I find frozen screen savers. I disabled each one that froze and found them to be: Hong Kong Day one and three, and Los Angeles Day three. I also disabled all of Dubai and Liwa, because I couldn't care less about those places. Works fine now.

**Comment by bigheadjer** [comment]
Yeah, spoke too soon.  I noticed a couple of freezes over the past week.  I'd rather not to have to turn the cache off though as downloading each video repeatedly doesn't seem to be very efficient.

**Comment by MajicMac** [comment]
Having the same issues as others in this thread but i have noticed one thing.
I have a Macbook Pro and if i unplug the power and run it on battery the screensaver has not frozen.
I have tested twice with about 50 min screenssaver run.
Once i plug in power it will freeze randomly after 10 min or so.
Anyone seen this?

On my iMac it never freeze.

**Comment by the-saint** [comment]
I had uninstalled the screensaver because using it conflicted with my VNC software and made it difficult to get to my desktop. This was the vault of the VNC vendor, as I found that most every screensaver created a conflict. So I changed to another remote app. When I reinstalled the screensaver and enabled caching, I could see the screensavers downloading individually, each with a progress bar. This isn’t something I remember seeing in my initial install. All the videos are working now.

**Comment by MajicMac** [comment]
Upgraded today to macOS 10.12.6 and screen saver been running without freeze for several hours.

**Comment by alistairmcmillan** [comment]
I think this issue was fixed by a point release of macOS. Is anyone still having this problem or can this issue be closed?

**Comment by the-saint** [comment]
I thought the problem was gone until I noticed that one of my videos was frozen yesterday.

**Comment by frumbert** [comment]
10.12.6 seems to be much better for me too, haven't seen the freeze (particularly multi monitor) for a while now.

**Comment by glouel** [comment]
I'll be closing this one, please reopen if you still see it in either Mojave or our version 1.4
