### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by carlosmunguia30** [JohnCoates/Aerial#28]
Hello,

I just downloaded the file and clicked it and installed it. But once it starts running it looks like it get stuck. I restarted my computer and tried again and nothing. I am running OS X 10.11 in a Retina MacBook Pro 2013 i7 8gb. If you need more info feel free to contact me: carlosmunguia30@outlook.com  You have made a wonderful job with this screensavers, I hope you could help!

Best Regards,

Carlos Munguía

**Comment by agucova** [comment]
Same here, again (Look my latest issue)... 3 and counting.

**Comment by alistairmcmillan** [comment]
If you are still having this issue please try the latest release and let us know if you have any issues.

https://github.com/JohnCoates/Aerial/releases
