### ISSUE TITLE
Directory of screensavers 

### ISSUE THREAD

**Issue by erikcoolen** [JohnCoates/Aerial#280]
Hi,
Is it possible to choose the directory where the screensavers are placed? I'd rather have them reside on an SD card in the SD slot than have them sit on my SSD drive. Thanks for your help.
regards,
Erik Coolen

**Comment by alistairmcmillan** [comment]
Latest version lets you pick the cache location.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by erikcoolen** [comment]
Hi Alistair,

Works like a charm, thanks for the advice!

groet,
Erik Coolen

**Comment by alistairmcmillan** [comment]
No problem. Happy it's working for you.
