### ISSUE TITLE
You cannot use the Aerial screen saver with this version of OS X...

### ISSUE THREAD

**Issue by mathisonrichard** [JohnCoates/Aerial#281]
Greetings,

I am running El Capitan. I there a version of Arieal screen saver for this version of OS X ?? What versions of OS X does Areial screen saver support ??

[Aerial.saver.zip](https://github.com/JohnCoates/Aerial/files/659469/Aerial.saver.zip)

http://qz.com/866027/how-to-get-the-apple-aapl-tv-aerial-flyover-screensavers-on-your-mac-laptop-or-desktop/

I am looking forward to hearing from you soon. Thank you.

Cordially,

Richard
612.741.5224

**Comment by alistairmcmillan** [comment]
First, please download the latest version. It says beta but it's been out for over a year now and includes a number of features including caching. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

Second, all versions work okay in El Capitan. The error message you are seeing is a bug in OS X (and it's still there in macOS). If you see the error message just select Aerial, close System Preferences and re-open it. The preview will then work okay. You can read more about the OS X/macOS bug here if you want. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html
