### ISSUE TITLE
New Screensavers from Apple TV

### ISSUE THREAD

**Issue by googlercolin** [JohnCoates/Aerial#282]
Hi John,
May I know if the new screen savers from the Apple TV which debuted a fews days ago will be included in Aerial real soon? 😄
Thanks!

**Comment by alistairmcmillan** [comment]
John designed the screen saver to pick up new aerials as Apple add them. If they're not appearing for you make sure you're on the latest version.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #276
