### ISSUE TITLE
Ariel Screen Saver not loading or playing any videos

### ISSUE THREAD

**Issue by adri430** [JohnCoates/Aerial#284]
When I've tried loading the Ariel screensaver on my iMac and MacBook, no images load as screen saver or in preview. They had worked previously, but will no longer load.

**Comment by alistairmcmillan** [comment]
@adri430 First thing, please make sure you're running the latest version. https://github.com/JohnCoates/Aerial/releases/tag/v1.2

Second, please make sure the screen saver isn't being blocked by a firewall or proxy.

Let us know how you get on.

**Comment by brandonedling** [comment]
Same issue here; presenting first frame of the video, like it's a static image instead of a video.

**Comment by alistairmcmillan** [comment]
@brandonedling Are you using the latest version? https://github.com/JohnCoates/Aerial/releases/tag/v1.2

Have you tried caching the videos?

**Comment by brandonedling** [comment]
Yep, confirmed that I'm using 1.2 and all videos are cached. I deleted them and re-downloaded them a couple days ago just to make sure cache wasn't corrupt, to no avail.

**Comment by mcgrealife** [comment]
Yes, same issue on MacOS Sierra 10.12.

**Comment by hairarrow** [comment]
I'm having this issue on macOS Sierra 10.12.2

I tried download `v1.2` and `v1.2 beta 5`

**Comment by alistairmcmillan** [comment]
I hate Apple. I'm tired of explaining this bug. Last time. Never again.

There are multiple versions of the Swift libraries. Version 1.0, 1.1, 1.2, 2.0 and 3.0.

System Preferences will only load one version of the Swift libraries. Once it has loaded one version it will not load another. Whichever version of the Swift libraries it loads first, that's it until you close System Preferences, the process dies and start again from scratch.

So if you open System Preferences and load a screensaver that uses version 1.0 of the Swift libraries, System Preferences loads version 1.0 of the Swift libraries. And then any screensaver that uses 1.1 or 1.2 or 2.0 or 3.0 of the Swift libraries will show that "You cannot use the XXX screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver." error.

Similarly if you open System Preferences to a screensaver that uses version 2.0 of the Swift libraries, System Preferences loads version 2.0 of the libraries and then any screensaver that uses 1.0, 1.1, 1.2 or 3.0 will display the "You cannot use the XXX screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver." error.

And so on and so forth for every combination.

If you would like to help please log a bug with Apple [here](https://bugreport.apple.com) or [here](http://www.apple.com/feedback/) or bug an Apple employee on Twitter or phone your Senator or send smoke signals or whatever. I reported this to them back in March through every avenue I could think of. They have done a grand total of diddly-squat to fix it.
