### ISSUE TITLE
Not compatible with 10.11.1

### ISSUE THREAD

**Issue by Scirocco3** [JohnCoates/Aerial#29]
Won't work for me withe the error above

**Comment by FerCL1** [comment]
Same here
I was available to install, but not to play them

**Comment by Scirocco3** [comment]
after a reboot and a second install as single user, it works

**Comment by phungleson** [comment]
It works for me, installed for all users, 10.11.1 (15B42)

**Comment by joshnh** [comment]
Works for me too on 10.11.1.

**Comment by jamieatadobe** [comment]
I ran re-installed, and it worked on the 2nd try

**Comment by alistairmcmillan** [comment]
Closing as working for @Scirocco3
