### ISSUE TITLE
Install through brew cask fails (404)

### ISSUE THREAD

**Issue by KlustoR** [JohnCoates/Aerial#290]
brew cask install aerial
==> Downloading https://github.com/JohnCoates/Aerial/releases/download/v1.2beta5

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'aerial' with message: Download failed: https://github.com/JohnCoates/Aerial/releases/download/v1.2beta5/Aerial.zip
The incomplete download is cached at /Users/klustor/Library/Caches/Homebrew/Cask/aerial--1.2beta5.zip.incomplete

can you re-upload please ?

**Comment by JohnCoates** [comment]
Done. thanks for the heads up!
