### ISSUE TITLE
Screensaver not compatible with  macOs 10.12 Sierra

### ISSUE THREAD

**Issue by hintzsche** [JohnCoates/Aerial#292]
Screensaver not compatible with macOs 10.12 Sierra

**Comment by alistairmcmillan** [comment]
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Comment by hintzsche** [comment]
Thank you very much solved
