### ISSUE TITLE
2016 iMac 5k Hung

### ISSUE THREAD

**Issue by stevetarara** [JohnCoates/Aerial#293]
Put iMac into Screensaver mode using Hot Corners. When I came back to my machine a few hours later it was a sleep with the display blacked out, as I expected. When I attempted to wake the machine I saw the Aerial screensaver start, and it never stopped or would be interrupted by the keyboard or trackpad.

**Comment by alistairmcmillan** [comment]
That's not really a glitch with the screensaver. The operating system handles starting the screensaver, stopping it, listening for user generated events (key presses), etc.

All I can say is to check the console log for that point in time to see if the operating system recorded anything relevant that might help diagnose the problem.

**Comment by stevetarara** [comment]
I've been using the stock screen savers for 8 months and never had an issue.  Started using the Aerial screensaver today and it locked the first time I used it.   With all due respect, the fact that caching occurs via the screen saver I am skeptical that the ONLY way this  can hang is the OS.

**Comment by alistairmcmillan** [comment]
I'm happy to help you trouble-shoot this but I'd need more information.

Is the hang repeatable? Does your iMac stop responding every time you leave Aerial running?

**Comment by stevetarara** [comment]
I'm sorry I removed the screensaver from my machine. I looked before removing it and the operating system didn't seem to record anything.  Sorry to leave you hanging, I just don't have the time to go through troubleshooting it with you.

**Comment by alistairmcmillan** [comment]
Sorry, there isn't much to do here then. Closing.
