### ISSUE TITLE
ScreenSaver does not comply with Energy Saver presets

### ISSUE THREAD

**Issue by jake-meister** [JohnCoates/Aerial#296]
Hi, amazing ScreenSaver, but I have noticed that the screenSaver does not comply with the Energy Saver presets. If the ScreenSaver is running and a preset to put the display to sleep is set for a given period of time, the display will never go to sleep. Hope you can fix this...

**Comment by alistairmcmillan** [comment]
There was a bug with this a while ago, but John fixed it.

Are you running the current version? https://github.com/JohnCoates/Aerial/releases

**Comment by jake-meister** [comment]
Evidently not.. ;-) 
Thanks. just downloaded the latest version, I was running a Beta. 
The download locations in GitHub are a little convoluted.
JC

**Comment by alistairmcmillan** [comment]
Cool. If you're happy feel free to close this issue. :)

**Comment by jake-meister** [comment]
Everything working OK now...
