### ISSUE TITLE
Package is not from an 'Identified Developer'

### ISSUE THREAD

**Issue by SullMcIntyre** [JohnCoates/Aerial#297]
The Aerial.saver package is not from an 'Identified Developer'. 

Users often use machines from employers that only allow the installation of apps from Identified Developers. 

Can the package be updated with an Identified Developer easily without issues or lots of work?

**Comment by ChristianMMacy** [comment]
@SullMcIntyre Info on the general process is [here](https://developer.apple.com/programs/how-it-works/).

I found this information on [code-signing for teams](https://codesigning.guide/) but it's entirely up to the core team if this is a direction they want to go in.

> TL;DR : You can fork and use your own license but be respectful of the core team's wishes.

Personally I would imagine that this would be a pretty big headache for relatively low return. With that said you could always fork the project, get your own developer ID through Apple, and add your key to your fork. But of course in that scenario I would hope that you would make a very clear distinction between your fork and the original and not make any claims or representations about the original material that would go against @JohnCoates ' license or the entire team's work. You could always maintain it as a private repo.

Also please note that I'm not on the team and I have no legal training so if you are interested in the suggestion above you'll be responsible for your own due diligence.

**Comment by alistairmcmillan** [comment]
I've got a copy of the screensaver signed using my own certificate. Is there much demand for this though? If Gatekeeper on your Mac is set to "App Store and identified developers" (which I believe is now the default in Sierra) then all you need to do is right-click and choose Open from the menu to get past that warning.

@JohnCoates If you want I can create a new release identical to 1.2 but signed so people don't get this warning message.

**Comment by glouel** [comment]
Version 1.4 is now signed to make it easier for everyone.

**Comment by thewatts** [comment]
@glouel while the release notes say signed - I'm still prompted with with the unidentified developer warning (build is 1.4.6)

![](https://thewatts.s3-us-west-1.amazonaws.com/Screen-Shot-2019-03-08-13-17-06.18.png)

**Comment by glouel** [comment]
@thewatts can you check the latest beta ? It's possible I forgot to sign this one but I try to sign them all. Thanks !

**Comment by thewatts** [comment]
@glouel latest beta is also not signed 😅

**Comment by glouel** [comment]
@thewatts can you try this in console : 

```
codesign -dv --verbose=4 Aerial.saver
```

You should see something with:
```
Authority=Mac Developer: Guillaume Louel (L6VPHQ7AB3)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=21 Feb 2019 at 19:52:35
```

The .saver is signed, but the .zip is not which may be why you see that prompt, depending on what you use to unzip ? I think Safari with it's default unzip safe content won't generate a warning, but some other tools may ? Can you clarify what you use to unzip ?

The zip is actually signed, but just for Sparkle (the new auto updater stuff in 1.4.7).

**Comment by thewatts** [comment]
```Executable=/Users/watts/Downloads/Aerial.saver/Contents/MacOS/Aerial
Identifier=com.JohnCoates.Aerial
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=12245 flags=0x0(none) hashes=377+3 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=021a96e72283804205a7e6f89063483d6aeac626
CandidateCDHash sha256=f45215fb5ed33d7cc8681c378062308b81461bbd
Hash choices=sha1,sha256
Page size=4096
CDHash=f45215fb5ed33d7cc8681c378062308b81461bbd
Signature size=4782
Authority=Mac Developer: Guillaume Louel (L6VPHQ7AB3)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Feb 21, 2019 at 12:52:35 PM
Info.plist entries=26
TeamIdentifier=3L54M5L5KK
Sealed Resources version=2 rules=13 files=33
Internal requirements count=1 size=184
```

**Comment by JohnCoates** [comment]
Looks fine to me

**Comment by thewatts** [comment]
Hmm, I'm not sure. I've tried on two different computers outside of my own. Both gave the security warning.

Any thoughts on what this could be?

**Comment by JohnCoates** [comment]
The warning happens when you unzip or when you run the .saver file?
could I see the output for ```codesign -vvvv -R="anchor apple generic" Aerial.saver```

**Comment by JohnCoates** [comment]
Under in System Preferences -> Security & Privacy do you have checked App Store, or "App store and identified developers" under "Allow apps downloaded from:"

**Comment by thewatts** [comment]
```
codesign -vvvv -R="anchor apple generic" Aerial.saver
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreImage.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftAppKit.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreImage.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftAppKit.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftXPC.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftXPC.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftObjectiveC.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCore.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCore.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftMetal.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftMetal.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreGraphics.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreGraphics.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreData.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreData.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftos.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreFoundation.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftos.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreFoundation.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftDispatch.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftDispatch.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftQuartzCore.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftQuartzCore.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftDarwin.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftDarwin.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreAudio.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftIOKit.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreAudio.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftIOKit.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftAVFoundation.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftAVFoundation.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftFoundation.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftFoundation.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreMedia.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreMedia.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreLocation.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftCoreLocation.dylib
--prepared:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftsimd.dylib
--validated:/Users/louclarizio/Downloads/Aerial.saver/Contents/Frameworks/libswiftsimd.dylib
Aerial.saver: valid on disk
Aerial.saver: satisfies its Designated Requirement
Aerial.saver: explicit requirement satisfied```

![Screen Shot 2019-03-08 at 3 52 19 PM](https://user-images.githubusercontent.com/1141717/54058060-5bb7b780-41ba-11e9-9a6a-d4268483ce5a.png)

**Comment by glouel** [comment]
@thewatts you didn't answer, how do you unzip ?

**Comment by thewatts** [comment]
@glouel sorry 😅

If I remember correctly, one instance was Safari’s - the other was using Mac’s default (double click to unzip)

**Comment by glouel** [comment]
No worries. Can you try:

```
xattr Aerial.saver
```

My guess is you'll see `com.apple.quarantine` because it's a downloaded file. According to this post here https://stackoverflow.com/a/31395999 , removing that metadata (-d) will fix your issue. 

What I don't get is why only some people have this issue. There may be some answer in this post https://stackoverflow.com/questions/31709087/failure-digitally-signing-a-mac-app-outside-xcode/32025478#32025478 , I'll have to do a more thourough check, could be some rpath thing too.

**Comment by JohnCoates** [comment]
I was able to replicate this on a stock installation of Mojave, and can confirm `xattr -d com.apple.quarantine Aerial.saver` fixed the issue. Would signing the .zip file solve this?

**Comment by glouel** [comment]
I thought so but the links above seem to imply that it may not. Can you check into console why it's rejected ? See here : 
https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG207

**Comment by JohnCoates** [comment]
Console's messages are not very helpful. I feel that the best past forward is to sign the zip or release via signed dmg. What do you think?

```
default	13:11:56.487222 -0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (syspolicyd[164]/0#-1 LF=0)
default	13:11:56.487424 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	13:11:56.524285 -0800	syspolicyd	MacOS error: 3
default	13:11:56.533845 -0800	syspolicyd	Error checking with notarization daemon: 3
default	13:11:56.692604 -0800	syspolicyd	rejecting due to lack of matching active rule
```

**Comment by glouel** [comment]
Guess it's likely it's the unsigned zip then. I'll check how to sign the zip (.xip I guess) for the next build (or go dmg route, this might break sparkle though will have to check)!

**Comment by glouel** [comment]
Ok this took me a long while to figure out BUT I finally got it. The .saver is now correctly signed AND notarized (and stapled for offline install). Still in zip format. Proper signing AND notarization are not mandatory in upcoming 10.15. 

I put the file here as a test, this is signed with my developper ID certificates : https://github.com/glouel/Aerial/releases/download/v1.5.1beta1/Aerial.zip

From now on I'll sign/notarize every release.

**Comment by thewatts** [comment]
Thanks, @glouel! I'll try that release on a computer that doesn't already have it installed - and keep you posted :)

---

As funny as it may sound - this project promotes joy. It genuinely makes my life better (and I'm not alone).

Thanks for all your hard work, @JohnCoates, @glouel, & everyone else!

**Comment by glouel** [comment]
@thewatts FYI I posted more recent betas directly here, they are now all signed and notarized : https://github.com/JohnCoates/Aerial/releases

It's always nice to hear people appreciating it. Really glad to hear this and I kinda have to agree, it's really a joyful project and that's why I keep working on it.
