### ISSUE TITLE
[Feature Request] Display cache size information

### ISSUE THREAD

**Issue by mrleblanc101** [JohnCoates/Aerial#298]
Hi,
1) Cache size information: It would be a nice addition if the the cache size was displayed somewhere in the setting pane as it can become quite large.
2) Purge cache: A purge cache button is **essential** as more and more video are added and apple still use very small for their entry level machine.
3) Limit cache option: In the same order of idea, it would be interesting to have an option to limit the cache size. As older video get deleted from the cache, it would make the app display the newer video that are not cached yet.

**Comment by janekszynal** [comment]
lack of those things also makes it really frustrating for me to use Aerial. maybe for #3 you could alternatively have it compress the videos when it gets closer to the limit.

**Comment by glouel** [comment]
I'm bumping this one as there are some good ideas for next version. 

Just so you know, in 1.4 there's a warning telling you how large the full download will be, and options to download just a few videos. 
1) we should definitely add
2) maybe, we have now a "Show in Finder" that will point you to that folder so you can manage it. 
3) this one is not quite realistic with how Aerial work. You're supposed to pick which videos you want and either cache them or they'll get streamed and cached (unless you don't want them cached at all). Managing a rolling cache won't help with much I think.

**Comment by glouel** [comment]
2) was implemented in 1.4.1, 1) will be in 1.4.2 beta 2

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta2/Aerial.saver.zip
