### ISSUE TITLE
Label video request

### ISSUE THREAD

**Issue by myaffee** [JohnCoates/Aerial#299]
I love this screensaver, thanks for putting it together! Since so many of the locations are places I haven't seen and don't recognize, it would be cool if, overlayed on the video somewhere, text would display the location of that video. It could be small and out of the way, like lower left corner or something, so as not to take away from the awesomeness of the videos. Thanks for considering!

**Comment by alistairmcmillan** [comment]
Already suggested under #58 and there is a depending implementation under #285. :)
