### ISSUE TITLE
Aerial for Windows

### ISSUE THREAD

**Issue by A1fus** [JohnCoates/Aerial#3]
Aerial is a great program that runs exceptionally on my Mac, but I also have a Windows laptop and would love to have a similar system run on that. I understand that Aerial is written in Swift so porting would be difficult but I thought I'd just leave this here in case anyone wants to work towards it 🙂.

**Comment by JohnCoates** [comment]
Thanks for the kind words. I don't own a Windows computer, but I'll leave this up in case anyone wants to  take on the challenge.

**Comment by llahnoraa** [comment]
@A1fus what version of Windows are you running on?

**Comment by elliottregan** [comment]
Might be worth waiting for when they open source Swift? Might be easy to port then.

**Comment by fantattitude** [comment]
@elliottregan Not really, most frameworks used here (and they are quite powerful) won't be available to other platforms so it won't mean an easier port (the pure Swift part here is pretty tiny).

**Comment by A1fus** [comment]
@llahnoraa I'm running the latest Windows 10 build.

**Comment by GitZenin** [comment]
In a moment, display screen saver when there will be caton black screen, and video playback.My system is EI Capitan.

**Comment by alistairmcmillan** [comment]
One of the problems of developing an equivalent on Windows is that Windows doesn't support QuickTime films natively and Apple stopped supporting their QuickTime for Windows SDK a wee while ago (2006?).

**Comment by A1fus** [comment]
Okay so @cDima has made [his own version](https://github.com/cDima/Aerial) of Aerial specifically for Windows.

**Comment by cDima** [comment]
@A1fus indeed, it works on my Windows 10 latest build machine and leverages Windows support for MP4.

**Comment by JohnCoates** [comment]
I've linked to the Windows version in the readme. Thanks @cDima, great work!

**Comment by cDima** [comment]
Thanks, John, for the link.

On Sun, Nov 1, 2015 at 7:14 AM, John Coates <notifications@github.com>
wrote:

> I've linked to the Windows version in the readme. Thanks @cDima
> <https://github.com/cDima>, great work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnCoates/Aerial/issues/3#issuecomment-152822204>.
>



-- 
*Dmitry Sadakov *
Consultant – Web Technology  | Gemini Systems | A&M | 600 Madison Ave| New
York, NY | Mobile +16468531955
sadakov.com | linkedin <http://linkedin.com/in/sadakov> | stackoverflow
<http://stackoverflow.com/users/82054/cdima> | github
<https://github.com/cDima> | g+ <http://www.google.com/profiles/sadakov> |
facebook <https://www.facebook.com/sadakov> | vk <http://vk.com/sadakov> |
skype:dmitry.sadakov
