### ISSUE TITLE
Flexible cache location required

### ISSUE THREAD

**Issue by karthikmangipudi** [JohnCoates/Aerial#300]
The cache goes and sites in C drive which is already cramped. I want to place the videos some other partition and route the videos to the screensaver. Is this possible?

**Comment by alistairmcmillan** [comment]
Are you using a Windows machine or a Mac?

If you are using a Mac, make sure you have the [latest version of Aerial](https://github.com/JohnCoates/Aerial/releases) and you can change the cache location in the Screen Saver Options.

<img width="780" alt="screenshot 2017-01-03 10 15 28" src="https://cloud.githubusercontent.com/assets/125896/21605059/86bf5dea-d19e-11e6-8e2e-641042650aef.png">

If you are using a Windows machine, then unfortunately that version of the screensaver (which is hosted over here https://github.com/cDima/Aerial/) hasn't been updated to allow that yet.

**Comment by alistairmcmillan** [comment]
This was about the Windows version. Closing.
