### ISSUE TITLE
Credits and Version number

### ISSUE THREAD

**Issue by WebVeteran** [JohnCoates/Aerial#301]
Perhaps in the Options panel, add come credits and also the version number.

**Comment by jomnius** [comment]
Need version number to verify which version I'm running or if it's even a beta version (see some bug reports asking for version number)

**Comment by ccharlton** [comment]
+1

**Comment by glouel** [comment]
We now have version number on the bottom right corner with 1.4 !

**Comment by WebVeteran** [comment]
I downloaded v 1.4 and I can tell it is with the new features. But it says 1.2 in the bottom right.
![screen shot 2018-10-11 at 12 40 11 pm](https://user-images.githubusercontent.com/40175/46819880-d6d38980-cd52-11e8-95a7-0fc2272c4765.png)

**Comment by glouel** [comment]
Can you close System Preferences and open it again ? It doesn't reload the new version correctly if you don't usually.

**Comment by WebVeteran** [comment]
Yep you're right. I went back to look just now, since closing Prefs earlier. I see "1.4".
