### ISSUE TITLE
Aeriel got stuck on-screen

### ISSUE THREAD

**Issue by jomnius** [JohnCoates/Aerial#305]
Running Aeriel 1.2 in MacBook Pro (Retina, 13-inch, Early 2015) with two external monitors (Dell). Using macOS 10.12.2. There is only one Aerial and it's in home/Library/Screen Savers folder. All videos are cached (unless there was new ones since last time).

Rebooted laptop and waited for existing apps and windows to relaunch, didn't really pay attention to what was going on. Saw that Aerial screensaver was running and thought everything is ready and laptop is ready to be used. However Aeriel would not go away.

I pressed and swiped trackpad, I tapped laptop keyboard randomly, moved (visible) mouse cursor to everywhere and especially to all monitor corners. Nothing helped, Aerial would not close and let me see the "real" desktops. Finally rebooted again via Power button and made sure I didn't let Aerial to start.

Now tested that Aeriel will start from hot corner and go away as it should. Never seen this before, no ideas what would have changed since last install. Just reporting as random non-reproducable bug.

**Comment by alistairmcmillan** [comment]
Someone else reported a similar issue recently.

#293 

But without the issue being reproducible I'm not really sure what anyone can do.
