### ISSUE TITLE
New videos not showing up

### ISSUE THREAD

**Issue by letibo** [JohnCoates/Aerial#307]
Hey, on my work laptop, the new videos (e.g. Antartica) are not showing up. I tried to uninstall and reinstall the screensaver, to no avail. On my private laptop, the screensaver updated itself automatically.

Any idea what can cause this?

Thanks!!

**Comment by alistairmcmillan** [comment]
@letibo Did you install the latest version from [here](https://github.com/JohnCoates/Aerial/releases)?

If you go to the Cache tab in "Screen Saver Options..." what happens when you click "Download Now"?

**Comment by letibo** [comment]
Hi, I was downloading it from [here](https://github.com/JohnCoates/Aerial) but the link to the actual file is the same.

In any case I've downloaded it again, and this time it worked. Strange. But thanks for the help!
