### ISSUE TITLE
Incompatible with macOS version 10.12.3 Beta

### ISSUE THREAD

**Issue by fintanstevens** [JohnCoates/Aerial#308]
<img width="349" alt="screen shot 2017-01-13 at 3 11 35 am" src="https://cloud.githubusercontent.com/assets/25081397/21892970/06f952ee-d93e-11e6-8bbe-bd0e171585ef.png">

I'm getting this error, I'm not sure why it wouldn't be compatible.

**Comment by alistairmcmillan** [comment]
@fintanstevens Please select Aerial, close System Preferences, re-open System Preferences, the screen saver preview should now work.

Let us know how you get on.

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #4
