### ISSUE TITLE
New version of Screensaver with imessage animation ?

### ISSUE THREAD

**Issue by Benexplorer** [JohnCoates/Aerial#309]
![img_6728](https://cloud.githubusercontent.com/assets/25125160/21958294/703b0914-daab-11e6-81f4-8dbd0b504030.JPG)
Hi everyone, 

I'm sorry to bother you with that but I can't sleep since I saw that :)
I went to an apple store (an official reseller to be honest in Bonn Germany) and I see on all the macbook this famous sceensaver "aerial" but with plenty of imessage animation on it inlayed perfectly in the cities. 
Where I can found it actually please ? 
(I took a picture if you want)

Thank you very much.

**Comment by Benexplorer** [comment]
Yeah I already did that ahah ! 
It's not in the screen saver by the way :(
It's something (like a video) project to the Macbook/iMac screen directly from "somewhere". 
The Apple reseller are connect to the system "Tune&Play" and it's thanks to this "connection" that they have this screen on their mac. 
For now it's not a screensaver, but I guess someone code it and could ba a screensaver ahaha :)
So...who did tthat ahaah ?

**Comment by Dimatellis** [comment]
Saw the exact same and was hoping also to get this Screensaver somehow, this was the closest I could get to it, after playing around on the Mac I also discovered that it could only come from Tune&Play

**Comment by alistairmcmillan** [comment]
@Benexplorer @Dimatellis Interesting. If someone could get a movie capture of this in operation myself, and I'm sure others too, would be curious to see it.

**Comment by Rafikki** [comment]
Yea, cool one.
