### ISSUE TITLE
Aerial doesn't work 

### ISSUE THREAD

**Issue by VictorPenkovsky** [JohnCoates/Aerial#31]
Unfortunately Aerial doesn't work correctly!

**Comment by alistairmcmillan** [comment]
John might need a little more information on the problem to fix it for you. In what way is Aerial not working for you? Do you get an error message? Does it not launch at all? Do the videos hang?

**Comment by VictorPenkovsky** [comment]
It doesn't launch partly. It looks like someone pushes pause when video is streaming. That's all

Отправлено с iPhone

**Comment by agucova** [comment]
Same problem here? Maybe? (Look my latest issue)

**Comment by alistairmcmillan** [comment]
Hi @VictorPenkovsky @agucova have you tried one of the recent betas that allows you to cache the videos? Do they work okay for you?

**Comment by alistairmcmillan** [comment]
Waited months, no reply, so closing.
