### ISSUE TITLE
Screensaver freezes

### ISSUE THREAD

**Issue by andygoldberg94** [JohnCoates/Aerial#310]
I have loaded the aerial screensaver on 2 systems running 10.11.6 (15G1212). The screensaver starts, but then the movement "freezes" after 2 secs.

**Comment by alistairmcmillan** [comment]
@andygoldberg94 Are you using the latest version? https://github.com/JohnCoates/Aerial/releases

Have you cached the videos?

**Comment by andygoldberg94** [comment]
I am using the latest version. I think it is a caching issue. Some seem to be working just fine while others aren't. I will download the rest of the cache.
