### ISSUE TITLE
Single video spanning multiple monitors

### ISSUE THREAD

**Issue by anorth2** [JohnCoates/Aerial#314]
How difficult would it be to implement multi monitor support?  My workstation is 2 vertically oriented displays, which causes the video to be super zoomed in.  What's needed to support displaying a single video over multiple displays rather than duplicating?

**Comment by mbroo** [comment]
Is this a duplicate of https://github.com/JohnCoates/Aerial/issues/194

**Comment by anorth2** [comment]
Yup it is, apologies.
