### ISSUE TITLE
Videos went missing...

### ISSUE THREAD

**Issue by robhuska** [JohnCoates/Aerial#315]
All of a sudden about a week or 2 ago the videos stopped showing and I got a broken play icon. I thought it was just an auto update issue, so I thought I would try and wait it out. Well then never came back, so today I went to the settings and at first it showed all the checkboxes of the videos, but none of them showed the preview. So I tried toggling to a different screen saver and go back. Now all of the video checkboxes are gone. This is what I see in the settings.

<img width="671" alt="screen shot 2017-01-31 at 1 23 54 pm" src="https://cloud.githubusercontent.com/assets/2412155/22478718/11329408-e7b9-11e6-9c10-d2bd5b2dc7df.png">

**Comment by robhuska** [comment]
I have also tried installing the latest version, and it still does the same thing.

**Comment by gomflo** [comment]
Same here…

**Comment by alistairmcmillan** [comment]
@robhuska That's a very old copy you have installed in that screenshot above. Download the latest version, delete all the old copies (check `/Users/YOURUSERNAME/Library/Screen Savers` AND `/Library/Screen Savers`), and try install just the latest version. It's possible to have multiple copies installed which just confuses things.

If it still comes up with no list like that then most likely either (a) you are being blocked from talking to Apple's servers by a firewall or corporate proxy or something like that, or (b) something is corrupting the screen saver install.

**Comment by alistairmcmillan** [comment]
@gomflo Do you have the latest version installed? Have you tried caching the files?

**Comment by robhuska** [comment]
@alistairmcmillan Yes, I have removed the old version and installed the latest. Still have the same issue. It is my work computer that I noticed the issue, so the firewall is possible... I just tried installing it on my laptop for the first time. I have the same issue. I will check to see if they work once I get home to my personal WiFi.

**Comment by robhuska** [comment]
Ok, my issue does appear to be some sort of firewall block at the office. I have now installed the latest on my laptop, it is broken on my works network, but works fine from home.

Well that sucks... I don't think I can go to my IT guy and be like "Hey can you lessen our security so I can get my cool screen savers back?"

**Comment by alistairmcmillan** [comment]
@robhuska If you let all the videos cache on your home network, then the screensaver should play fine at work. John designed it to essentially automatically work offline if the videos are cached and it can't find the network.
