### ISSUE TITLE
Improve preview speed

### ISSUE THREAD

**Issue by brunolemos** [JohnCoates/Aerial#319]
The previews are taking a long time to load.

Expectation:
1. Quickly see all available screen savers (It could be an static image for optimization, that would be more than enough)
2. Disable the ones I don't like
3. Clicking cache all should cache only the ones that I left marked

What is happening:
1. Preview is taking too long to load (it's probably loading the whole video. It stay black while it's not loaded (possibly related: #14))
2. Not sure if cache only downloads the ones I selected (because it takes so long)

[![screenshot](https://s30.postimg.org/4xawotftt/Screen_Shot_2017_02_11_at_19_11_33.png)](https://postimg.org/image/7re229hzx/)

**Comment by glouel** [comment]
Please check 1.4 if you can, you'll see pretty much what you expect. As far as it goes, when you click a video that's not in cache already, it will start streaming it (not downloading the whole thing). If the video is in cache already the preview will show up instantly.

You can also now download videos individually, or check those you want and download them with one click in the menu (click the option below the list).
