### ISSUE TITLE
Not compatible with the latest OS X

### ISSUE THREAD

**Issue by maslyankov** [JohnCoates/Aerial#320]
Not compatible with the latest OS X :(

**Comment by alistairmcmillan** [comment]
1. Select Aerial in System Preferences. You'll see that error message.
2. Close System Preferences.
3. Open System Preferences. The error message should be gone.

It's a bug in macOS. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html
