### ISSUE TITLE
System Prefs crashes everytime I select Aerial

### ISSUE THREAD

**Issue by kudigaracoder** [JohnCoates/Aerial#325]
Hello,
On the 5K iMac, when I select Aerial from 'Desktop & Screensaver', System Preferences crashes every single time. Crash report attached
[crashreport.txt](https://github.com/JohnCoates/Aerial/files/788996/crashreport.txt)

**Comment by alistairmcmillan** [comment]
@kudigaracoder Curious. The important part is the following...

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSConcreteMutableData initWithLength:]: absurd length: 18446744073709551615, maximum size: 9223372036854775808 bytes'

This says it was trying to load something that is 18446744074 GBs in size. The largest video is less than 1 GB so I'm not sure what it's doing here.

If no-one else gets to it before me, I'll send you a version of the screensaver later today with logging so we can see what it's trying to load.

**Comment by kudigaracoder** [comment]
👍

**Comment by alistairmcmillan** [comment]
@kudigaracoder Please try the version [here](https://github.com/alistairmcmillan/Aerial/releases/download/v1.2-debug/Aerial.saver.zip).

This version of the screensaver will write out to log file called `aerial_debug_YOURMACHINENAME_DATESTAMP.log` in your `/Users/YOURUSERNAME/Documents` folder.

Please try running the screensaver two or three times and then either post the output here in a comment or email it to me at alistairmcmillan75@gmail.com.

**Comment by kudigaracoder** [comment]
Thank you @alistairmcmillan. Please find the output attached.
[aerial_debug_kudigaracoder_20170222.txt](https://github.com/JohnCoates/Aerial/files/792177/aerial_debug_kudigaracoder_20170222.txt)

**Comment by alistairmcmillan** [comment]
@kudigaracoder Thanks. So it is getting the manifest okay, but then failing when it tries to download the actual videos.

What happens if you try to open http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-2.mov in a web browser?

What happens if you try http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b4-2.mov in a web browser?

**Comment by kudigaracoder** [comment]
There's the problem.. My company firewall seems to be blocking it. Will check by whitelisting the URLs

**Comment by alistairmcmillan** [comment]
@kudigaracoder I suspected it might be that. Usually though the screensaver doesn't crash when its blocked by a firewall. Usually the videos just don't appear. Strange that the firewall is convincing Aerial that it is trying to download a 18446744074 GB file.

Could you tell us which firewall it is? Or show us the error you get in the browser?

**Comment by kudigaracoder** [comment]
We use Checkpoint Firewall in the office & the error page it generates is attached.
<img width="1053" alt="screen shot 2017-02-22 at 5 52 34 pm" src="https://cloud.githubusercontent.com/assets/3305383/23211362/c8b7b7b4-f927-11e6-8867-912eb755d714.png">

**Comment by alistairmcmillan** [comment]
@kudigaracoder Thanks.

If you're unable to get those URLs whitelisted, or get the file type unblocked which seems to be what its objecting to, you could try caching the videos on another network if you're on a laptop or on another machine and transfer them over if you're on a desktop.
