### ISSUE TITLE
Blackscreen on screen saver start

### ISSUE THREAD

**Issue by elfet** [JohnCoates/Aerial#328]
When i start screen saver via active corner – black screen, then if i hit enter password fields shows up, but when i press cross (x) – video stars playing normally. 

MacOS: 10.12.3
Aerial: 1.2

**Comment by alistairmcmillan** [comment]
@elfet Are the videos cached? Maybe if you just start the screensaver and give it a little more time to start?

**Comment by elfet** [comment]
> Are the videos cached?

Yes, all of them. Everythink was working normally before some of macos updates.

**Comment by alistairmcmillan** [comment]
@elfet So if you use the hot corner to start the screensaver and leave your Mac for say 60 seconds, the screensaver never actually starts playing videos?

**Comment by elfet** [comment]
Wow, it's start about on 10 sec. Cool. thanks. 

Is is possible to make in on 1,or 2?
