### ISSUE TITLE
Prevents option for password protection

### ISSUE THREAD

**Issue by staringispolite** [JohnCoates/Aerial#33]
This is an extremely common option (available on all Mac screensavers as far as I know) but I'll make the request explicit: I'd like to make it so I put my screensaver on, and after X seconds with the screensaver on, it would require my password to regain access to the desktop.

**Comment by alistairmcmillan** [comment]
The option to "Require password [ immediately | 5 seconds | etc ] after sleep or screen saver begins" is available under the Security & Privacy preference pane in OS X. It's implemented at a system level, not within the screensavers themselves.

Try it yourself. Just tested it myself here and it works okay with this screensaver for me.

**Comment by staringispolite** [comment]
I'm familiar with how it works, and I haven't changed that setting. This screensaver just isn't behaving the same as other screensavers for me. Maybe this is just local to my machine?

**Comment by joshlewis** [comment]
It's asking for my password as expected. I have "Require password 5 seconds after sleep or screen saver begins" set, and the password dialogue comes up as expected in that case. 

Extra cool bit: the video continues playing behind the prompt's blur overlay, so the blurred colors continue to shift slowly as I type my password in. Nice.

I'm running OS X 10.11.1.

**Comment by JohnCoates** [comment]
@staringispolite what OS X version are you on? I'm on the latest El Capitan and it's been working for me.

**Comment by staringispolite** [comment]
I'm on the latest version of Yosemite.

I went in to check my password settings, and it had changed to "require password after 1 minute" instead of the previous setting "5 seconds". Even as I'm writing this, I'm aware it sounds like I'm making this up. But there is no way it was set to 1 minute for long, as I use this computer for work and made sure it locks quickly. 

It's possible a recent OS update reset this setting, and I just hadn't noticed until changing screen savers. Feel free to resolve if it's not reproducible.
