### ISSUE TITLE
Cannot View screensaver on macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by kyrian06** [JohnCoates/Aerial#330]
hi I have just downloaded Aerial and installed it. When I go into my screen savers to select it this message come up.
"You cannot use Aerial screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver"
Is there a newer version?

<img width="686" alt="screen shot 2017-03-08 at 12 00 08 pm" src="https://cloud.githubusercontent.com/assets/26263718/23685185/d1c53a14-03f6-11e7-89be-feb3aee1616e.png">

**Comment by alistairmcmillan** [comment]
It's a bug in macOS.

1) Open SystemPreferences and select Aerial.
2) Leave Aerial selected and close System Preferences.
3) Re-Open System Preferences and the error should have disappeared.
