### ISSUE TITLE
Aerial cache download only for selected items on macbook air

### ISSUE THREAD

**Issue by fpaludo** [JohnCoates/Aerial#340]
Hi. As you know, internal space in Macbooks Air are very limited. So it will be very good if download function only download the videos that are already selected, saving some space. Its a filter in code and i think it will be very well accepted by everyone.
Thanks,

Paludo
Brazil

**Comment by alistairmcmillan** [comment]
Hi @fpaludo,

The screensaver already works this way.

1) Select the videos you want downloaded. Leave the default "Cache Aerials As They Play" box ticked.
2) Let the screensaver run.
3) There is no step three.

The screensaver will only download the ones that you have selected.

I just tested this myself on a new Mac just to confirm. Ticked six videos at random, left the screensaver running over night, and it's only downloaded the six videos I ticked.

**Comment by fpaludo** [comment]
Whow! 
That's a nice new @alistairmcmillan. I have tried using the cache option, and it does not work as (I) expected... I will try this way you said about. Thanks for your help!

**Comment by ajc188** [comment]
I want to use "download now" to get all the cache video first.
But after click it, it show downloading greenland(which I didn't select) and stuck...
I already check the cache folder it have some other video downloaded(selected before but deselect didn't remove old files)

**Comment by glouel** [comment]
You can now download videos individually in 1.4, or download what you selected using the menu below the video list.
