### ISSUE TITLE
crossfade effect between video

### ISSUE THREAD

**Issue by kalafalas** [JohnCoates/Aerial#342]
This screensaver is absolutely gorgeous, and even better than the version on my apple tv (customizable, set as wallpaper etc, its amazing!) the only thing its missing from the apple tv version is it blanks out for a second and loads the next. would it be possible to add a nice cross fade or fade through black transition between videos? that would be the cherry on top! thank you!

**Comment by glouel** [comment]
Implemented in 1.4 !
