### ISSUE TITLE
Hope to support 4K video

### ISSUE THREAD

**Issue by Vxider** [JohnCoates/Aerial#343]
Hope to support 4K video

**Comment by alistairmcmillan** [comment]
@Vxider John's screensaver just displays the videos that Apple created for their Apple TV screensaver. If Apple starts to stream 4K aerial videos to the Apple TV, then John's screensaver will automatically pick them up.

**Comment by alistairmcmillan** [comment]
Closing as 4K video will be supported automatically if Apple ever released any 4K videos.
