### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by vonkas** [JohnCoates/Aerial#347]
Pictures appear MUCH sharper on Apple TV. Can this be fixed for 27" Retina screen?

**Comment by alistairmcmillan** [comment]
@vonkas The videos are produced by Apple. If you want higher resolution sharper videos you'll need to speak to them. :) But then if they are higher resolution and sharper then the file sizes will be bigger. Much bigger. :(

In the meantime, you can try swapping them out with the videos available here though.
https://github.com/JohnCoates/Aerial/issues/257

**Comment by vonkas** [comment]
Understand. Thinking about it, as Apple preps the videos for the Apple TV it would be pointless to make them higher res than what the Apple TV can show. Once that has moved on to 4K, I'm sure it will be better. The illusion of a crisper image on the Apple TV is just that.
