### ISSUE TITLE
Installing Aerial Remotely

### ISSUE THREAD

**Issue by brown921** [JohnCoates/Aerial#348]
Hi John. My bandwidth usage has sky-rocketed since using Aerial. Love the screen saver though. I'm trying to install it remotely but I'm not having much luck. I tried clicking on the link to Brew Cask but I'm coming up with dead ends. I'm not a developer so I may need some layman instructions. Any help you can provide is appreciated. 

Thanks!

Justin

**Comment by alistairmcmillan** [comment]
@brown921 Make sure you have the latest version installed. https://github.com/JohnCoates/Aerial/releases/tag/v1.2

It should automatically cache the videos. But check in the screensaver preferences to make sure caching is ticked.

Once the videos are downloaded it won't use any more of your bandwidth. Until Apple release more videos. Which they've only done once in the last two years.
