### ISSUE TITLE
ScreenSaver can be set without needing to manually enable.

### ISSUE THREAD

**Issue by MichaelDimmitt** [JohnCoates/Aerial#349]
@alistairmcmillan, works on my macOS Sierra 10.12.4, 

Avoid requiring users to manually change screensaver to Aerial.
However, if they do manually change screensaver after the command it overrides what has been done.(So no harm will be done.)

To automatically set as default screensaver add this <b>terminal command</b> after receiving credentials
### Examples:

to find out current default screen saver:
0) ```defaults -currentHost read com.apple.screensaver```

1) to set screensaver as Shell:
```defaults -currentHost write com.apple.screensaver modulePath -string "/System/Library/Screen Savers/Shell.saver"; defaults -currentHost write com.apple.screensaver moduleName -string "Shell"; defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName Shell path /System/Library/Screen\ Savers/Shell.saver/ type 0```

2) to set screensaver as Flurry:
```defaults -currentHost write com.apple.screensaver modulePath -string "/System/Library/Screen Savers/Flurry.saver"; defaults -currentHost write com.apple.screensaver moduleName -string "Flurry"; defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName Flurry path /System/Library/Screen\ Savers/Flurry.saver/ type 0```

3) to set screensaver as Aerial ... aerial is at a different path so slight difference.
```defaults -currentHost write com.apple.screensaver modulePath -string "/Library/Screen\ Savers/Aerial.saver"; defaults -currentHost write com.apple.screensaver moduleName -string "Aerial";defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName Aerial path /Library/Screen\ Savers/Aerial.saver type 0```

two links,
https://apple.stackexchange.com/questions/159992/how-to-change-the-the-screensaver-using-terminal-without-using-preference-panel/283374#283374
http://krypted.com/mac-security/mac-setting-screen-saver-from-the-cli/

Appreciate any feedback and happy to answer any questions.
It should work on older versions of mac but let me know if any issues. 
I am limited in my test capabilities. (Currently only my mac personal computer)
Also I would appreciate some feedback on if this should be a pull request for Aerial.

**Comment by alistairmcmillan** [comment]
Firstly this is John's screensaver. I just help/annoy people that log issues. :)

That aside I don't really get the benefit to users here.

You want to add something to Aerial that makes it set itself as the default screensaver whenever it runs?

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, I imagined @JohnCoates would see the issue but I just wanted to bring this potential new usability up for discussion thats why I tagged you. I suppose I could have tagged anyone 😄 .  The benefit, if someone is clicking Aerial.saver, I assume they want it as their screensaver. 

To your point users may not want it to enable by default. Aerial.saver currently brings up screensaver preferences. However, clicking Aerial manually is not in the Readme instructions.

If the default screensaver changes without manual interaction the screensaver preferences window will not even need to be brought up. 
Or the screensaver preference window could still be brought up. Users would then see Aerial already selected and be able to change to a different screensaver or back to the one they want if so inclined. 

Ultimately the main reason to bring in the change is to make it super user friendly. My understanding is that people only click Aerial.saver once. And this would enable with the click of Aerial.saver the downloading and setting screensaver so that everything works in one click instead of 2 clicks and a scroll.

**Comment by tvwillie** [comment]
Please explain to this novice the differences between:
to set screensaver as Shell:
to set screensaver as Flurry:
to set screensaver as Aerial:

**Comment by MichaelDimmitt** [comment]
@tvwillie, Each one is an individual command and doing the same thing, setting default screensaver. "Flurry" and "Shell" are other ScreenSavers. I included those as examples so people can verify default ScreenSaver is changing when those commands are run on the terminal.

The intent is not for a User to run these commands. Rather to include the "set sceensaver as Aerial" command inside the Aerial program so that at one click of "Aerial.saver" the screensaver is set up for the user. The other commands: "as Flurry" and "as Shell" are just examples. 
Hope that is clear. 😄

**Comment by alistairmcmillan** [comment]
@MichaelDimmitt I'm still not understanding the benefit. Are you saying the screensaver itself should run these commands to make itself the default, or that users should run these commands after downloading Aerial?

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, that the screensaver should run the command to make itself the default. 👍

**Comment by alistairmcmillan** [comment]
@MichaelDimmitt But when is the screensaver going to run so it can make itself the default, if it isn't already the default?

This is what I mean. Right now the situation is...

1) User downloads Aerial
2) First time they click on the downloaded Aerial.saver file, macOS launches System Preferences, installs Aerial and sets it at the default.
3) There is no step 3 :)

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, precisely! At step your <b>step 2</b>, currently the user has to manually set Aerial as default. This would automatically set Aerial as default. MacOS could still launch System Preferences or The program could change to no longer need to launch System Preferences (that is a usability decision) the default screensaver would be set regardless with this implementation. Another benefit of this enhancement, check out my comment on #4 which if incorporated into "Aerial.saver" would use this command to automatically solve #4 an open problem users have to manually fix currently.

**Comment by alistairmcmillan** [comment]
@MichaelDimmitt Are you sure making a screensaver the default is another step? Try deleting Aerial from a Mac and installing again. On my Macs the first time I open a new screensaver and macOS launches it in System Preferences, it is automatically selected as the default.

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan; I will check. 
regardless, though it could be useful to automatically solve #4.

going off memory... You are correct if I already have Aerial installed.
But I will uninstall and install Aerial and report the results 😄 .

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, I checked here is the breakdown:
1) (optional) If you remove Aerial screensaver
2) go to ScreenSaver window and click on a different ScreenSaver. 
3) click on Aerial.saver(try installing it again.)
4) Aerial is no longer my default ScreenSaver. 

@alistairmcmillan do you get the same results in your environment?

Summary: I think that if you simply uninstall and reinstall aerial it remembered that it was your old default ScreenSaver. However if you are a new user it will not put Aerial as the default.

**Comment by alistairmcmillan** [comment]
1. Delete Aerial from everywhere
2. Close System Preferences
3. Download and open Aerial which launches System Preferences and makes Aerial the default

However, if you open System Preferences and select another screensaver, and then launch Aerial while that other screensaver is running, then Aerial will get added to the list but not made the default.

But if we added these commands to Aerial to tell it to set itself as the default, you still need it to run for those commands to take effect. How do you do that? By selecting it. At which point you have already made it the default, so the commands don't make any difference.

You see what I mean? To get the thing to run the user has to take an action. That action makes Aerial the default. So there is no point to the commands.

AND about the "You cannot use..." bug. The reason people see that bug is because macOS cannot run the screensaver. If the screensaver is not running, then it can't run commands to make itself default.

I hope this makes sense, this is difficult to explain. The only way for those commands to work is for the screensaver to actually be running, and I can't see a situation where the screensaver would be running where it wasn't already the selected default.

**Comment by MichaelDimmitt** [comment]
To make the program run the user currently has to do two actions:
1) click Aerial.saver
2) click Aerial default
They would not need to click aerial. They could simply put their computer to sleep or activate their ScreenSaver through a hot corner.

@alistairmcmillan, if you want it to run terminal command:
```/System/Library/Frameworks/ScreenSaver.framework/Resources/./ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine;```

but ScreenSaver Preferences window may still want to be open in the event that a user wants to customize which aerial ScreenSavers they want to include or not include.
