### ISSUE TITLE
Progressbar seems stuck at 99, but it is just a visual thing.

### ISSUE THREAD

**Issue by iAmRenzo** [JohnCoates/Aerial#350]
I was downloading all videos and I though it was stuck at something. There is a small piece of progess missing. It's just a visual thing, but I though I'd report it anyway.

<img width="404" alt="screen shot 2017-05-14 at 18 21 11" src="https://cloud.githubusercontent.com/assets/1183790/26035794/79627920-38d2-11e7-8adb-659a43798f47.png">

**Comment by glouel** [comment]
This was actually fixed in 1.4 :)
