### ISSUE TITLE
Feature request - enable/disable keyboard controls

### ISSUE THREAD

**Issue by alyx92** [JohnCoates/Aerial#351]
Hey there,

Thanks for making this great saver! I've got it on all of my machines! Presently, (on mac at least) pressing the space bar will pause one of the screens. This could be useful, but I think an option to enable or disable spacebar and arrow keys controls in the settings would be great. Most of the time I slam my space bar to end the screen saver, then sit and wonder why nothing happened, realize it just paused a screen, and then hit a different key to return to the desktop. 

Adding that would be great! Thanks again

-Alyx

**Comment by alistairmcmillan** [comment]
@alyx92 If pressing the spacebar pauses one of the videos, then it means you are running quite an old version. This was basically a bug that John fixed back in October 2015.

Please try the latest version...
https://github.com/JohnCoates/Aerial/releases/tag/v1.2
