### ISSUE TITLE
incompatible with macOS 10.12.4

### ISSUE THREAD

**Issue by adilmajid** [JohnCoates/Aerial#352]
seeing a compatibility issue on macOS 10.12.4 on a 2015 MBP. After install, seeing a message in the Screen Saver preview that says "You cannot use the Aerial screen saver with this version of macOS."

(btw - this is an awesome idea!)

**Comment by MichaelDimmitt** [comment]
Hey @adilmajid, is this when you install for an individual user or across all users?

Also, is this similar to #4 ? 
There is a workaround I reported in that issue. I never made a pull request about it but I did put the workaround in my companion app that puts it on your desktop. https://github.com/MichaelDimmitt/Aerial_Desktop

**Comment by alistairmcmillan** [comment]
@adilmajid It's a bug in macOS. Select Aerial, close System Preferences, re-open System Preferences works. Try it and let us know how you get on.

**Comment by andyyh1214** [comment]
it can;t open

**Comment by alistairmcmillan** [comment]
@andyyh1214 Select Aerial, close System Preferences, re-open System Preferences works. Try it and let us know how you get on.
