### ISSUE TITLE
determining version of existing install

### ISSUE THREAD

**Issue by njm2112** [JohnCoates/Aerial#354]
Wondering if there's any easy way to determine whether I have the latest version (and if not, which version I have) installed. I know I installed Aerial quite  a while ago and according to my `brew list` output, I didn't install using Homebrew. Not sure if Aerial would've auto-updated since install, but if it hasn't, I want to update it. Hesitant to do so by simply downloading master.zip and replacing my existing install at `/Library/Screen Savers/` though (unless that's the recommended method).

In case there's some way to tell from what my current install looks like:
![snip20170524_1](https://cloud.githubusercontent.com/assets/10353532/26416239/29df1c92-4083-11e7-879e-6d88fd747f4d.png)

Thanks in advance!

**Comment by alistairmcmillan** [comment]
You have an old version installed.

Please download the latest version from here: https://github.com/JohnCoates/Aerial/releases/tag/v1.2

**Comment by njm2112** [comment]
@alistairmcmillan I appreciate your reply. Would you mind clarifying how you can tell I had an old version?

Strange thing is that after using `brew cask install aerial` successfully, Aerial is installed into `~/Library/Screen Savers/`(rather than `/Library/Screen Savers/`), but the files are exactly the same as what were in the screenshot I posted earlier. Here's the current state, reflecting the `brew cask` install:
![snip20170524_3](https://cloud.githubusercontent.com/assets/10353532/26429926/0486fed0-40b8-11e7-9c2c-8e2ce63fca6c.png)

I've also confirmed that the `brew cask` installation is identical to the release available at https://github.com/JohnCoates/Aerial/releases/tag/v1.2, per screenshot of file comparison:
![snip20170524_4](https://cloud.githubusercontent.com/assets/10353532/26429971/44bfade4-40b8-11e7-8930-b31f914a1435.png)

**Comment by MichaelDimmitt** [comment]
looks like the current cask version is v1.2
https://github.com/caskroom/homebrew-cask/blob/master/Casks/aerial.rb @njm2112 

Also, try this link out; it looks helpful for updating a cask:
https://stackoverflow.com/questions/31968664/upgrade-all-the-casks-installed-via-homebrew-cask

I would imagine if that link does not work you can uninstall the cask and then reinstall the cask. In that circumstance the new cask will be official published cask.

I am guessing that you would only need the most up to date cask for speed fixes or other workarounds introduced with the new commits. My understanding is that "In terms of the videos" if apple posts more videos on Apple TV they will automatically be included into Aerial. Can you confirm? Having 55 videos listed as shown in the image below.

![screen shot 2017-05-24 at 7 47 19 pm](https://cloud.githubusercontent.com/assets/11463275/26430234/d2f48dcc-40b9-11e7-8ef7-44b47fa8df31.png)

I just counted them all up. I have many of mine un-toggled.

**Comment by alistairmcmillan** [comment]
@njm2112 Actually sorry, you're right. You were already running the current release version. I was thrown off because I'm using my own custom version, and because the timestamps in the release version seem to be 2015 even though the update was released in 2016.

The two official recommended ways to install are the two listed in the [README](https://github.com/JohnCoates/Aerial/blob/master/Readme.md) file. Don't use the version in the master.zip it's in development and may or may not be complete or tested.

**Comment by alistairmcmillan** [comment]
@MichaelDimmitt Yup, John designed Aerial to automatically pick up new videos when Apple release them. Which it did a few months ago successfully for everyone when Apple released the new videos of Dubai and Greenland, etc.
