### ISSUE TITLE
Display image refresh schedule

### ISSUE THREAD

**Issue by bf140** [JohnCoates/Aerial#355]
macOS 10.12.4/10.12.5 I have been having a problem with my network being completely tied up for minutes at a time, sometimes for half an hour, several times a day. It will be tied up to the point that Safari cannot connect to the Internet and neither can Mail. I studied the log files I can find to discover that an unknown process was trying to access NIC ports one after another numbered in the 50,000-60,000 range.

It occurred to me that something is trying to refresh its data from the Internet on its own schedule which is unknown to me, but interferes with my business correspondence. 

I turned off Aerial screensaver and the network immediately cleared. I believe that the Aerial code does not work properly with the networking changes Apple must have made in macOS 10.12.4. 

I should be able to control the frequency and time of screensaver image updates in the 'Screensaver Options' section of System Preferences. This would allow me the control I need to keep Aerial out of the way during business hours.

Albert

**Comment by alistairmcmillan** [comment]
@bf140 Are you running the latest version? Do you have the videos cached?

If so, the network traffic should be effective nothing until Apple release a new video. Just downloading the JSON file when the screensaver launches. A grand total of 17 kilobytes of data.

**Comment by alistairmcmillan** [comment]
@bf140 If you should us the log files entries you mentioned, maybe I can give you a better answer about what is happening on your Mac.
