### ISSUE TITLE
New videos

### ISSUE THREAD

**Issue by brandonshough** [JohnCoates/Aerial#357]
Any plans to add the new screensavers that have been added to the AppleTV?

**Comment by alistairmcmillan** [comment]
@brandonshough You mean the new videos for places like Dubai and Hong Kong?

**Comment by brandonshough** [comment]
I haven't seen the LAX one, but I may be missing it..? Have you guys seen it yet?

**Comment by alistairmcmillan** [comment]
@brandonshough Are you running the latest release? https://github.com/JohnCoates/Aerial/releases/tag/v1.2

If you go into the preferences is "Los Angeles" listed? It should look something like this.

<img width="780" alt="screenshot 2017-06-01 09 09 50" src="https://cloud.githubusercontent.com/assets/125896/26670615/2f510834-46aa-11e7-8fe8-00b394207f30.png">
 
If you check the `/Users/YOURUSERNAME/Library/Caches/Aerial` folder on your Mac is the `comp_LA_A006_C008_t9_6M_HB_tag0.mov` file there?
