### ISSUE TITLE
Serve a Download Video URL

### ISSUE THREAD

**Issue by JayMiao** [JohnCoates/Aerial#359]
U know , for Chinese users , it's not easy to download these videos. The connection always be reset for interrupt. I look up video download url from your code, however, found nothing.  
Could U please tell the url where the Aerial download the video ? Then, I can download them in special method, and then put it in my folder.

Many thanks. 
You did a great job, and i love this project...

**Comment by alistairmcmillan** [comment]
@JayMiao This is the manifest file from Apple that lists all the videos.

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

**Comment by JayMiao** [comment]
thanks
