### ISSUE TITLE
Error: Laggy and then freezes on 10.11

### ISSUE THREAD

**Issue by agucova** [JohnCoates/Aerial#36]
I start the video, there is a very short lapse where it works (100ms or less), and then it freezes permanently, I'm in a MacBook Pro (Retina, 13-inch, Late 2013) running OSX 10.11. I really don't think is a graphic performance problem, since this mac has a Intel Iris 1536 MB...

**Comment by agucova** [comment]
This happens every time. I tried reinstalling and every normal troubleshooting step.

**Comment by hansonhu** [comment]
Have same problem
MBP (Retina, 13-inch, Early 2015)  OSX 10.11

**Comment by agucova** [comment]
I have seen 4 issues, all in El Capitan (10.11)

**Comment by agucova** [comment]
If I press space, it lasts a little longer, a pauses again (As I said, 100ms or less)

**Comment by joshnh** [comment]
I'm on a mid 2015 MacBook Pro and am not having any issues. Although occasionally it pauses for a second or two while buffering towards the start of the screensaver.

**Comment by nerdicly** [comment]
I have the same problem
`<MBP (Retina, 13-inch, Mid 2014) OSX 10.11>`

**Comment by deksden** [comment]
Same. iMAc-Late 2009: video in freeze after ~1000ms, then screensaver options are empty - can not select any video.

**Comment by EarMaster** [comment]
Same problem here on a Mac Pro (Early 2009).

**Comment by JDHatman** [comment]
I have 3 screens with OS X 10.11. I can play the same aerial shot on all three, but if I choose to use a different shot for each screen, it freezes like the others have mentioned. 2 of the 3 screens will eventually buffer, but 1 will stay frozen. Not the same one every time.

**Comment by alistairmcmillan** [comment]
Hi @agucova @sbugzu @nerdicly @deksden @EarMaster @JDHatman have you tried the betas with the caching feature? Do they work okay for you?

**Comment by deksden** [comment]
Beta 5 working for now for me - after 5 testes all is ok. Will test more

**Comment by alistairmcmillan** [comment]
Glad it's working for you @deksden .

No reply from others after months, so closing.
