### ISSUE TITLE
Download is stopped when Aerial active

### ISSUE THREAD

**Issue by livc** [JohnCoates/Aerial#360]
If I was downloading something, and then I left the Mac and the Aerial screen saver active, then I return find all my downloads were stopped.

**Comment by alistairmcmillan** [comment]
@livc The only way I can think that Aerial would affect other downloads is if you a streaming the videos and have a limited connection. Do you have the latest version of Aerial installed? Do you have the videos cached? https://github.com/JohnCoates/Aerial/releases/tag/v1.2
