### ISSUE TITLE
Slow and crashing on MacBook Pro

### ISSUE THREAD

**Issue by IBOYHK** [JohnCoates/Aerial#362]
this vision of the screensaver is slow on my MacBook Pro 13inch i5 core 8gb ram and it seem to need some time to load some time it crash

**Comment by alistairmcmillan** [comment]
Which version of macOS are you running?
Which version of Aerial are you running (are you running the [latest release](https://github.com/JohnCoates/Aerial/releases))?
Do you have the videos cached on your MacBook Pro?

**Comment by alistairmcmillan** [comment]
No reply for over a week...
