### ISSUE TITLE
You can not uset the Aerial Screen saver with this version of macOS...

### ISSUE THREAD

**Issue by teneolumen** [JohnCoates/Aerial#363]
Hello, Only my com Mac has this message.
How can I see those sunning landscape again? 

Thank you.

**Comment by alistairmcmillan** [comment]
1) Select Aerial
2) Close System Preferences
3) Re-open System Preferences

It's a bug in macOS.

**Comment by teneolumen** [comment]
Thank you! 
I can see again! : )
