### ISSUE TITLE
Aerial not running in (a) a Hackintosh and (b) in High Sierra. "Messages" screensaver pops up instead.

### ISSUE THREAD

**Issue by pjrezai** [JohnCoates/Aerial#365]
Installed and all wallpapers were cached through preview but when it should pop up after a certain amount of time the "Message" screensaver pops up instead.

**Comment by alistairmcmillan** [comment]
@pjrezai When you open the "Display & Screen Saver" preference pane in System Preferences do you have Aerial selected?

**Comment by jistark** [comment]
Same here; also, sometimes Aerials doesn't autoplay when screensaver is activated, and reverts to this. OS X 10.13 Beta (17A291m)

**Comment by alistairmcmillan** [comment]
@pjrezai Are you running a beta version of macOS as well?

**Comment by pjrezai** [comment]
@alistairmcmillan yeah I have Aerial selected. I have also selected another screensaver, rebooted, checked to see if other screensaver works, then picked aerial, rebooted, but still same issue

**Comment by alistairmcmillan** [comment]
@pjrezai And which version of macOS are you running?

**Comment by pjrezai** [comment]
10.12.5

**Comment by alistairmcmillan** [comment]
@pjrezai So the screensaver works in the preview but when it's time to launch the Message screensaver comes up instead?

**Comment by jistark** [comment]
Chiming in. Tried to replicate if it works on preview and both cases (no play, message) appeared. Still in High Sierra Beta.

**Comment by alistairmcmillan** [comment]
@jistark I'd assume Aerial will work on High Sierra once it is fully baked. I've downloaded the latest beta but haven't installed it anywhere yet. Any interesting message in Console about Aerial?

**Comment by pjrezai** [comment]
@alistairmcmillan Yeah it works perfectly in preview but not on its own with a timer.

I could have sworn I commented on how this is a hackintosh... although I don't see how such a simple software issue like a screensaver could be related (especially since all other screensavers seem to work)

**Comment by jistark** [comment]
@alistairmcmillan Will debug and report! Just did a test and it only played a second or two of movie, and it was cached.

**Comment by alistairmcmillan** [comment]
@jistark Not sure what is going on. Download the latest developer beta of High Sierra, installed it, tried Aerial and it's running okay. What kind of Mac are you running? Can you find any relevant errors in Console?

@pjrezai Similarly, can you find any relevant errors in Console? If you try to play the movies from /Users/YOURUSERNAME/Library/Cache/Aerial in QuickTime Player fullscreen do they play okay?

**Comment by BilboSwagginz** [comment]
When I record in QuickTime it suddenly works (I'm on High Sierra as well)

**Comment by BilboSwagginz** [comment]
Also for me the messages screensaver doesn't come up, the screensaver runs for a second and then it begins to stutter

**Comment by alistairmcmillan** [comment]
@BilboSwagginz Are you running the latest version of Aerial? Do you have the videos cached? Which version of High Sierra are you running? Are you running High Sierra directly on a Mac or in a VM?

**Comment by BilboSwagginz** [comment]
@alistairmcmillan Yes, some of them but all show problems, beta 5, on a Mac

**Comment by mj011** [comment]
Hi,
I have the problem as well. My MacBook is a 2017 and I use High Sierra Beta 7 (17A352a). With Sierra it works, with High Sierra I see only small Stripes on the hole Screen. The Videos direct played works without Problems.
Can you help me?
Greetings from Berlin/Germany
Markus

**Comment by alistairmcmillan** [comment]
@jistark @BilboSwagginz @mj011 High Sierra is still in beta. One of the areas they are doing a lot of work on is re-writing Quartz Compositor (the window server that draws everything on the screen) to use their new Metal2 API. So right now some people are seeing visual drawing glitches. If this is happening to you then please use Apple's Feedback app to report these issues to Apple so they can improve Quartz Compositor.

**Comment by esetnik** [comment]
I can confirm a similar issue in high sierra final. I'm also on a hackintosh. Any other screensaver I use gets triggered after the correct interval, but Aerial just does nothing for me. If I use the hot corner aerial comes up immediately and works perfectly, but if I set to 1 minute and wait for timeout no screensaver is shown. Setting screensaver to "Origami" or any other causes the 1 minute timeout to work perfectly, it's only Aerial that seems to do nothing.
