### ISSUE TITLE
Not moving

### ISSUE THREAD

**Issue by meredithmere** [JohnCoates/Aerial#367]
Hi there,
I have installed this on a new Mac Touchbar 2017 15 inch and when in screensaver mode, the picture will appear on screen, but it doesn't move when not in preview mode (only moves in preview mode).
Thank you

**Comment by alistairmcmillan** [comment]
@meredithmere Do you have the videos cached? That can help if the screensaver is having trouble streaming them.

**Comment by meredithmere** [comment]
Hi, yes I do have the cached box checked-- thanks for any other suggestions

**Comment by alistairmcmillan** [comment]
@meredithmere Sorry, I mean have you click on the

**Comment by alistairmcmillan** [comment]
@meredithmere Are the videos cached? If you check the folder `/Users/YOURUSERNAME/Library/Caches/Aerial` are there 55 videos there? If not, there is an option in the screensaver preferences to tell it to download all the videos immediately.

**Comment by meredithmere** [comment]
That worked! Thank you!

**Comment by alistairmcmillan** [comment]
Glad to hear that worked. :)
