### ISSUE TITLE
Stop 'Download Now' Caching

### ISSUE THREAD

**Issue by PJUllrich** [JohnCoates/Aerial#370]
I 'accidentally' clicked on the 'Download Now'-Button and now I can't stop the download of ALL videos. I suggest putting also a 'Stop Now'-Button next to the 'Download Now'-Button so that I don't have to wait until infinity until ALL videos are downloaded ;-)

**Comment by glouel** [comment]
Implemented in beta 3 : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta3/Aerial.saver.zip
