### ISSUE TITLE
Show Screensaver on Main Screen Only

### ISSUE THREAD

**Issue by skimgosu** [JohnCoates/Aerial#372]
Hi there,
Just a suggestion for enhancement. I liked the option to play different screensavers on different displays, but for the sake of energy conservation and not having so much happening when nothing is, making only 1 display run the screensaver in a multiple display setup would be the best, in my humble opinion!

Cheers

**Comment by glouel** [comment]
This is implemented in this build if you are willing to give it a shot : 

https://github.com/glouel/Aerial/releases/download/1.4.1test4/Aerial.saver.zip

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
