### ISSUE TITLE
Aerials 1.2 on macOS 10.13 High Sierra has some display flickering/scaling issues

### ISSUE THREAD

**Issue by eriblu** [JohnCoates/Aerial#375]
Hello,
Thanks very much for making Aerials!  I was playing around with it on a macOS 10.13 High Sierra developer beta, and I noticed Aerials seems to have a flickering scaling issue (it rapidly switches between a narrow/wider scaling), and occasionally shows some other display issues like white bars flickering at the top and bottom of the display.
Let me know if there's any additional info or logging I may be able to gather to help.
Thanks!
H

**Comment by eriblu** [comment]
Sorry, just noticed #374 already pointed out High Sierra issues, I'll close this one.

**Comment by alistairmcmillan** [comment]
Duplicate of #365
