### ISSUE TITLE
Ariel updated for Sierra 10.12.6??

### ISSUE THREAD

**Issue by jeb605** [JohnCoates/Aerial#376]
Have not been able to get it to run for a while, and I now have a new iMac 21.5 in 2017.  I used the migration method to move everything to the new iMac, and the Ariel option appears in the screen saver list in preferences. But it doesn't work  - screen just goes dark.  

This is my first time to write an issue here, so maybe it has been previously addressed.

**Comment by andrewjohnstrong** [comment]
Agreed. Doesn't work on Sierra 10.12.6 :(

**Comment by alistairmcmillan** [comment]
Aerial works fine on 10.2.6.

@andrewjohnstrong If you're getting an error saying that it needs to be updated, then that a longstanding bug in macOS. Select Aerial in System Preferences, close System Preferences and reopen it. Aerial should now be showing the preview okay.

@jeb605 Please delete Aerial from your Mac. You might have multiple copies. Check `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers`. And install the latest version from scratch from [here](https://github.com/JohnCoates/Aerial/releases). Within the preferences there are options to cache the videos. Cached the videos and then see if it works. If it doesn't please update this issue with what happens.

**Comment by andrewjohnstrong** [comment]
I see a black screen on preview sorry.

**Comment by alistairmcmillan** [comment]
@andrewjohnstrong Do you have the latest version installed? Do you have the videos cached?

**Comment by andrewjohnstrong** [comment]
Oddly it now appears to be working :)

On Mon, Sep 11, 2017 at 8:51 PM, Alistair McMillan <notifications@github.com

**Comment by alistairmcmillan** [comment]
@andrewjohnstrong If the videos aren't cached, then they'll stream from Apple's servers through their CDN partner. That can be affected in a number of ways by your network. For example some proxy servers stop people accessing the videos.

If you have the latest version installed you can cache all the videos when you have a good connection, avoiding these problems.

**Comment by andrewjohnstrong** [comment]
Thanks Alistair :) How do you cache the videos?

On Tue, Sep 12, 2017 at 6:25 AM, Alistair McMillan <notifications@github.com

**Comment by andrewjohnstrong** [comment]
Ignore that! Found the settings :)

**Comment by jeb605** [comment]
I’m also getting the blank dark screen in preview.  I checked the Cache screen- is this the way it should be?



 And in that screen above, when I click on the Download Now button, the words Loading JSON appear but nothing seems to happen - total progress and Current video progress bars do not grow.  
ALSO, I noticed in library that Apple’s own screen saver has some photos in the Folder named 2-Aerial that are named Aerial01.jpg  through Aerial09.jpg.
Could this naming method be causing a problem. 


thanks.

**Comment by alistairmcmillan** [comment]
@jeb605 It's nothing to do with the Aerial photos.

Most likely you are behind a proxy or firewall that is blocking you. If you're using a laptop, please try downloading the videos on another network.

**Comment by jeb605** [comment]
It now works.  My son showed me that in  our Xfinity ISP router protected browsing was on, and then  how to turn it off.  Then it worked.  Thanks for the help.

**Comment by alistairmcmillan** [comment]
Glad to hear that you got it working. :)
