### ISSUE TITLE
config: check all night videos

### ISSUE THREAD

**Issue by xenDE** [JohnCoates/Aerial#380]
hi,

in the config are only "uncheck all" and "check all".

I need "check all day videos" and "check all night videos".

that would be great :)

thanks for the nice prog!

**Comment by hroland** [comment]
+1 👍

**Comment by alistairmcmillan** [comment]
Duplicate of #11

**Comment by xenDE** [comment]
No, #11 is auto at local time.

I want manual select the videos!
