### ISSUE TITLE
Ariel leaks lots of URLSession/Networking objects

### ISSUE THREAD

**Issue by bnesse** [JohnCoates/Aerial#382]
Run ArielApp in Instruments (or run leaks on ScreenSaverEngine).

Simple fix attached.
[diffs.txt](https://github.com/JohnCoates/Aerial/files/1318707/diffs.txt)

**Comment by glouel** [comment]
As far as I know, should no longer happen with the new JSON downloader in 1.4. Thanks for the report (and sorry for the late answer)
