### ISSUE TITLE
Screen Saver doesn't run on macOS High Sierra 10.13.0

### ISSUE THREAD

**Issue by tempusthales** [JohnCoates/Aerial#385]
The screen saver doesn't work on my Mac Pro Late 2013 after I upgraded to macOS High Sierra 10.13.0.

The screensaver shows a black screen and the words "You cannot use the Aerial screen saver with this version of macOS.  Please contact the vendor to get a newer version of the screen saver." floating on the screen.

On my 2017 MBP Touchbar, when the screen saver plays there are graphical glitches when going full screen, while on the Intel HD video card, but when forcing the mac to discreet graphics it works.

**Comment by alistairmcmillan** [comment]
@tempusthales The screensaver does run on High Sierra. If you are getting that "cannot use the Aerial screen saver with this version of macOS" error its a bug in macOS that has been there for over a year at this point. Try selecting Aerial in System Preferences, closing System Preferences with Aerial still selected, and then opening System Preferences again. You should hopefully see Aerial running.

About the graphical glitches, there are problems on a few models where Apple need to update their drivers. There is an existing bug report for this issue. #377

**Comment by alistairmcmillan** [comment]
Closing as duplicate. Please try my suggestion above, if it doesn't work please leave a comment here.

**Comment by michael-brenner** [comment]
I found that the screen saver does run if you enable the clock

**Comment by ValentinFesenko** [comment]
It's so stupid, damn Apple ) Thx for your advice with closing **System Preference** and selected **Aerial** screensaver - it works!
