### ISSUE TITLE
Graphics Glitches in MacOS 10.13 High Sierra

### ISSUE THREAD

**Issue by irpolarbear** [JohnCoates/Aerial#388]
After upgrading to MacOS High Sierra (10.13) I have noticed the video in Aerials, on occasion, has graphical artifacts which appear at varying levels of severity. On my MacBook Pro I have seen the screen flicker and go completely blank. Hoping that the screen saver gets updated for High Sierra, it's just an awesome screen saver.

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #377
