### ISSUE TITLE
Show place name?

### ISSUE THREAD

**Issue by savraj** [JohnCoates/Aerial#389]
Everyone at my office loves aerial, but we're having trouble identifying the locations.  Is there a key / easter egg that will reveal the place name on the screen while it's running?

**Comment by MichaelDimmitt** [comment]
from pull #285 @kevinawoo made a forked release for those that can't or are too lazy to compile https://github.com/kevinawoo/Aerial/releases/download/v1.3-location-lables/Aerial.v1.3-location-labels.zip

additionally my mac desktop background program uses the aerial saver with location label enabled,
https://github.com/MichaelDimmitt/Aerial_Desktop

**Comment by byalextran** [comment]
great job @kevinawoo! just installed your fork. i'd also like to suggest including the day in the label. for those that like to only see the "good" ones, that helps better isolate which aerials to remove from the rotation.

**Comment by MichaelDimmitt** [comment]
#285 @ohayon originally created this functionality. @byalextran, consider posting that feedback in his pull request.

**Comment by glouel** [comment]
This is implemented in 1.4b9 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9
