### ISSUE TITLE
High Sierra compatibility

### ISSUE THREAD

**Issue by ppadovani** [JohnCoates/Aerial#392]
High Sierra does not think this is compatible. Additionally, I'm seeing stuttering of the screen saver on startup.

**Comment by alistairmcmillan** [comment]
About your first statement: If you get the "You cannot use the Aerial screen saver with this version of macOS." error... Select Aerial, close System Preferences with Aerial still selected, re-open System Preferences and Aerial should now work. This is a known bug with Swift screensavers in macOS/OS X reported to Apple as rdar://25569037.

About your second statement: Other people are seeing the same thing in High Sierra on certain models operating in certain modes. It's discussed here... #377

**Comment by ppadovani** [comment]
Thanks for the quick response!
