### ISSUE TITLE
Video playback problem..

### ISSUE THREAD

**Issue by jimauger** [JohnCoates/Aerial#395]
Been using, love it, but on new MacBook pro 13, once video launches I get diagonal lines
![img_0453](https://user-images.githubusercontent.com/32499237/31151357-f3a57744-a84b-11e7-82a2-80b72928e373.JPG)

![img_0453](https://user-images.githubusercontent.com/32499237/31151315-cd2810a4-a84b-11e7-8968-2a17c9f0e929.JPG)

**Comment by alistairmcmillan** [comment]
This appears to be a driver problem with the Intel chips in High Sierra. It's being discussed over here... #377
