### ISSUE TITLE
Aerial Screen saver

### ISSUE THREAD

**Issue by eddeemurfy** [JohnCoates/Aerial#396]
Hi,

Ever since upgrading my software to High Sierra when the screen savers comes up there is a distorion on my screen like its an old school tv.

I think I'm going to delete the screen saver and add it again when its compatible with High Sierra

**Comment by alistairmcmillan** [comment]
The screensaver is compatible with High Sierra. There seems to be a glitch in the High Sierra drivers for Intel chips on certain Macs.

Duplicate of #377. There is more discussion there.

**Comment by eddeemurfy** [comment]
Okay thank you for the quick reply
