### ISSUE TITLE
Strange interlacing issue

### ISSUE THREAD

**Issue by CalebKierum** [JohnCoates/Aerial#397]
For some reason the video either plays with a ton of stutter or it does this weird interlace appearing thing. Here is a video:

https://youtu.be/nJl3MXMr4Ho

I am on a MacBook Pro 2017 15" OSX High Sierra

**Comment by alistairmcmillan** [comment]
@CalebKierum There seems to be a glitch with the High Sierra drivers for Intel chips on certain models. People are discussing it here #377 .

Closing this as a duplicate.
