### ISSUE TITLE
Graphic Issues

### ISSUE THREAD

**Issue by Stevenfly** [JohnCoates/Aerial#398]
Whenevver it is supposed to show the aerial video, the graphic is not working and shows noisy lines (appears like the sitaution that graphic card is broken). Not matter auto triggerd or preview. There are couple of possibilities:
- My mac does have graphic issue (low possiblities because the condition only appears in the above case only, nothing wrong in other daily use)
- The software has graphic issue, either macOS or this library

The picture shows my mac information.

![screen shot 2017-10-06 at 16 29 57](https://user-images.githubusercontent.com/7512999/31297450-0547e5da-aab4-11e7-8e66-91e80464171b.jpg)

**Comment by alistairmcmillan** [comment]
@Stevenfly There seems to be a glitch with the High Sierra drivers for Intel chips on certain models. People are discussing it here #377 

Closing this as a duplicate.
