### ISSUE TITLE
NO Video and Menu on 10.13

### ISSUE THREAD

**Issue by UnclePluto** [JohnCoates/Aerial#399]
I install aerial by brew cask, and I had reinstall many time. I also download on GitHub to reinstall.
But it is not working on my MacBook Pro 15 2016. it was working on MacOS 10.12.
And I had downloaded all the cache.And the video is play well on VLC.
Now it just show nothing but black.
![snip20171007_2](https://user-images.githubusercontent.com/9131383/31309062-c223b9a0-abb2-11e7-9f04-26319e8d15d2.png)

![snip20171007_5](https://user-images.githubusercontent.com/9131383/31309135-ec4ed984-abb3-11e7-89ee-257f204e8a41.png)

![snip20171007_6](https://user-images.githubusercontent.com/9131383/31309157-57841e4e-abb4-11e7-8c78-d2b61307e3ed.png)

![snip20171007_4](https://user-images.githubusercontent.com/9131383/31309123-c3175744-abb3-11e7-8741-9fa5e25c06c6.png)

BTW aerial is an awesome tool.

**Comment by UnclePluto** [comment]
It's really funny,it doesn't work a few days, and I try anything I could to repair it but doesn't work... So I came here looking for help...And just when I finished commenting my issue I found areial is working...I just don't know why...I just do nothing...funny...

**Comment by alistairmcmillan** [comment]
@UnclePluto Your second screenshot where you've highlighted the box in red suggests that the JSON file didn't load from Apple's CDN partner's servers. Without that file the screensaver won't do anything (even if you already have the videos cached). Most likely reason for that not loading is a network issue.

**Comment by UnclePluto** [comment]
OK,thank you so much. I will check that.
