### ISSUE TITLE
Smooth Fade Between Scenes

### ISSUE THREAD

**Issue by austincondiff** [JohnCoates/Aerial#40]
It would be a lot more graceful if Aerial faded each scene into each other when a scene ends rather than cutting to the next scene. Given the calming nature of these video clips, a five or six second fade give or take would make it a lot less jarring.

**Comment by ckoerner** [comment]
:+1:

**Comment by jmcquillan** [comment]
+1

**Comment by glouel** [comment]
Implemented in 1.4
