### ISSUE TITLE
Night Shift Incompatibility

### ISSUE THREAD

**Issue by JTOwden** [JohnCoates/Aerial#402]
When night shift is on screensaver either distorts into bars or doesn't load. 
Disabling nightshift immediately fixes the issue.

Otherwise a beautiful screensaver, wish it came as standard on Macs 🙂

**Comment by benmarten** [comment]
Not reproducible for me, works with NightShift enabled and macOS 10.13.

**Comment by alistairmcmillan** [comment]
@JTOwden @benmarten I can reproduce on a 13" early 2015 MacBook Pro. As a workaround try enabling the "Show with clock" option.

This just seems to be more of the same Intel driver issue that Apple introduced with High Sierra. More discussion here #377

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #377
