### ISSUE TITLE
Not working on macos High Sierra

### ISSUE THREAD

**Issue by saivangie** [JohnCoates/Aerial#407]
Screensaver not working on latest macos version MACOS High Sierra

**Comment by alistairmcmillan** [comment]
@saivangie Hi, If you are getting screen corruption, that seems to be a bug in the Apple's Intel drivers for High Sierra. Hopefully they will fix it soon. In the meantime, if you tick the "Show with clock" option that will remove the screen corruption. It is being discussed here #377 .

If you are having another problem, please update this issue and we'll try to help.

**Comment by saivangie** [comment]
@alistairmcmillan I am getting the following error message "You cannot use Aerial Screen Saver with this version of macOS. Please contact the vendor to get a newer version of screen saver" even after I enable clock.

**Comment by alistairmcmillan** [comment]
@saivangie That's a long standing bug in macOS through a few versions.

Just select Aerial in System Preferences and close System Preferences.
Then open System Preferences again and (fingers crossed) Aerial should now work.

Let us know if that works.

**Comment by tengg** [comment]
@alistairmcmillan  The workaround doesn't work for me...
Any theory about the cause?

**Comment by alistairmcmillan** [comment]
@tengg Are you getting that same "You cannot use Aerial Screen Saver with this version of macOS. Please contact the vendor to get a newer version of screen saver"?

**Comment by liuliangsir** [comment]
same here: MacBook Pro (Retina, 13-inch, Early 2015) macOS High Sierra(10.13.1)

**Comment by tengg** [comment]
@alistairmcmillan  That's right.

**Comment by alistairmcmillan** [comment]
@tengg You said in another issue that you were trying to manually compile the code in the master branch and the 4K branch. John is still working on them. I'm afraid you'll have to either use a release version or wait for John to finish the code.

**Comment by tengg** [comment]
@alistairmcmillan Good to know thanks！
