### ISSUE TITLE
Downloading of all .movs

### ISSUE THREAD

**Issue by siccolein** [JohnCoates/Aerial#408]
When all screensavers are unchecked and I press 'Download now', it still downloads all of the files and I end up with a folder of roughly 8GBs of movies. Why not just download those I selected and want to have as my screen saver?

**Comment by alistairmcmillan** [comment]
@siccolein For the moment, you can check all the movies you want and just let it download them as it plays. That way you'll only end up with the ones you want.

**Comment by glouel** [comment]
You can do that now in 1.4. You can either download individual videos or what you selected (using the menu below the video list).
