### ISSUE TITLE
ScreenSaver showing 'messed up'

### ISSUE THREAD

**Issue by oeconom** [JohnCoates/Aerial#409]
Just the moment after Aerial is staring and the first pic of the movie had been shown, it ends up messed up... 
I tried downloading/caching and deleted and reinstalled Aerial (V1.2 from the main download link), bit with the same effect.

Anyone an idea?
Using the newest MBP 13'', 16GB
Aerial resides in /Library/Screen Savers

Thank you and best wishes,
Felix

![2017-10-27 17 40 07](https://user-images.githubusercontent.com/33158865/32114338-8b1f10bc-bb43-11e7-962c-1bed27f7f872.jpg)

**Comment by alistairmcmillan** [comment]
@oeconom As a workaround turn on the "Show with clock" option.

The corrupt seems to be a bug in the Intel driver in High Sierra.

Further discussion here #377

**Comment by oeconom** [comment]
How easy a solution can be... :-D

Thanks a lot!
