### ISSUE TITLE
Custom videos?

### ISSUE THREAD

**Issue by gabrielrazo** [JohnCoates/Aerial#41]
Hi, thanks for the app!

I just wanna know if there's any way to add custom videos?

Thanks for you time John!

**Comment by tobias--** [comment]
Have a look at SaveHollywood: http://s.sudre.free.fr/Software/SaveHollywood/about.html

**Comment by gabrielrazo** [comment]
It looks greet! Thanks so much.

**Comment by mateusrevoredo** [comment]
+1

**Comment by geo4orce** [comment]
+1

here's a good one
https://www.youtube.com/watch?v=NVcGGTELhX8

**Comment by NightRaider73** [comment]
@glouel Close
