### ISSUE TITLE
Bug report: Video shaking

### ISSUE THREAD

**Issue by iternety** [JohnCoates/Aerial#410]
While the Aerial is playing the video, if I adjust the brightness by pressing F1 or F2, the video starts to shake immediately.

OS Version: 10.13
Device: MacBook Pro 15, Mid 2015

**Comment by alistairmcmillan** [comment]
@iternety Can you try installing 10.13.1 and let us know if you still get the shaking?

**Comment by CupricWolf** [comment]
macOS: 10.13.1 (17B48) Also mid 2015MBP. I still get shaking.

**Comment by Cavolo** [comment]
10.13.2 Beta (17C60c) mid2017MBP, still shaking if run with intel display card

**Comment by alistairmcmillan** [comment]
Seems to be a duplicate of #377 so closing as a duplicate.

**Comment by alistairmcmillan** [comment]
@Cavolo @CupricWolf @iternety For the moment turn on the "Show with clock" option. That seems to fix the video glitches in High Sierra.
