### ISSUE TITLE
No Video in Preview

### ISSUE THREAD

**Issue by cdwilkins1** [JohnCoates/Aerial#411]
I've been having this issue with my 2011 MacBook Pro. Maybe the screen saver isn't supported on the older hardware. But when I open System Preferences and go to Aerial, no preview that ever loads. I've uninstalled and reinstalled several times. When I open the the screen saver options I see the attached. This may be a duplicate issue and I do apologize if that is the case. Just curious if anyone else has seen this happen.
![screen shot 2017-11-05 at 9 43 11 am](https://user-images.githubusercontent.com/33397004/32416387-cc6cbd0a-c20d-11e7-91a1-041765092dca.png)

**Comment by alistairmcmillan** [comment]
@cdwilkins1 Most likely if you are getting that symbol it means you are behind a firewall or corporate proxy that is blocking access to the videos. Are you able to connect your MacBook to another network and try caching the videos there?

**Comment by cdwilkins1** [comment]
I've tried multiple different networks. Current the firewall is off in System Preferences. I have a new 2016 MBP for work and it works perfectly there. Setup on the same network.

**Comment by alistairmcmillan** [comment]
The firewall in System Preferences won't cause this problem. I meant a firewall from whoever is providing your internet. Or even a third-party firewall like Little Snitch perhaps, that has caused issues for people in the past.

Another way to test is to try these links in a web browser and see if either of them are blocked...

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

**Comment by cdwilkins1** [comment]
After visiting the links you posted it is now working. Thanks for the assistance, I greatly appreciate it. I'm caching them now.

**Comment by alistairmcmillan** [comment]
@cdwilkins1 Glad to hear that's working for you now. :)
