### ISSUE TITLE
MacOS High Sierra Support

### ISSUE THREAD

**Issue by cstiles4** [JohnCoates/Aerial#412]
Would love High Sierra support! Just lost all ability to use Aerial on Macbook.

**Comment by alistairmcmillan** [comment]
@cstiles4 When reporting bugs it really helps to say exactly what is wrong.

If you are getting corrupted video then turn on the "Show with clock" option. There seem to be bugs in Apple's Intel drivers in High Sierra. Hopefully in a future release they'll fix that, but in the meantime turning on "Show with clock" will get rid of the corruption. Further discussion of this here #377 .

If you are getting a message saying the screensaver needs to be updated then that is a LONG standing bug in macOS. Just open System Preferences, select Aerial, close System Preferences, then open System Preferences. You shouldn't get that error message anymore.

If the list of locations isn't populating or the videos aren't downloading then it is likely that you are behind a firewall or corporate proxy that is blocking access. Try connecting to another network and trying to cache there.

**Comment by tengg** [comment]
brew cask install works without any issue.
But if I manually build it with the master or feature/4K branch, they won't work. Just the "with this version of macOS". And the suggested workaround in readme doesn't work.

**Comment by alistairmcmillan** [comment]
@tengg Either use a release version or the brew cask version. John is still working on the master branch and 4K branch.

**Comment by alistairmcmillan** [comment]
No reply from OP. Closing.
