### ISSUE TITLE
In macOS 10.13 most of the "time" titles are half cut off

### ISSUE THREAD

**Issue by MarcelloNicoletti** [JohnCoates/Aerial#413]
In the settings panel for what Aerials are selected to play the subtitles under most locations that say Day or Night are cut off. 

<img width="142" alt="screen shot 2017-11-05 at 12 13 35 pm" src="https://user-images.githubusercontent.com/1910383/32418269-e0cbaca0-c223-11e7-82c8-627857fd35ec.png">

**Comment by CupricWolf** [comment]
macOS 10.13.1 (17B48)
mid '15 MacBook Pro

**Comment by mikequinlan** [comment]
Same here. Same macOS 10.13.1 (17B48) but late 2016 MacBook Pro 15" with Touchbar.

**Comment by fenghebaiyang** [comment]
Me too macOS 10.13.1 mid 2014 MacBook Pro 15

**Comment by tjkohli** [comment]
I think they might be half visible instead?

**Comment by tjkohli** [comment]
I think they might be half visible instead?

**Comment by liuliangsir** [comment]
Me too macOS 10.13.1 early 2015 MacBook Pro 13

![image](https://user-images.githubusercontent.com/8049878/32590816-41ac26fe-c557-11e7-9427-21a3219270ed.png)

**Comment by mushanzi1216** [comment]
Me too,so is there any method to open it by a command?

**Comment by geniussheep** [comment]
![529300214557980483](https://user-images.githubusercontent.com/7587017/33123310-d04bfb2a-cfb4-11e7-89b2-ba2dec9604f8.jpg)
Me too,   and the screensaver doesn't play properly
![_20171122183659](https://user-images.githubusercontent.com/7587017/33123209-884c18be-cfb4-11e7-9734-0c0275c72a14.jpg)

**Comment by geniussheep** [comment]
me too ,and my screensaver doesn't play properly


![1511347498 1](https://user-images.githubusercontent.com/7587017/33123701-d781d1fc-cfb5-11e7-8c06-ca49a918511f.jpg)
![25709862255343032](https://user-images.githubusercontent.com/7587017/33123702-d7c15f98-cfb5-11e7-8339-11ad9ae8a7a5.jpg)

**Comment by alistairmcmillan** [comment]
@geniussheep Tick the "show with clock" option. It's just a workaround but it'll fix the playback until Apple fix their Intel drivrs.

**Comment by glouel** [comment]
Fixed in https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9
