### ISSUE TITLE
Weird glitchy video or plain black

### ISSUE THREAD

**Issue by ileacristian** [JohnCoates/Aerial#414]
Running macOS High Sierra 10.13 on a 2017 Macbook Pro 15" with Radeon Pro 560

The small preview looks good but when it runs it glitches like the video is 100% corrupt (or it stays black).
I also cannot unninstall the screensaver because the System Preferences app crashes when I try to delete it.

**Comment by alistairmcmillan** [comment]
@ileacristian Tick the "Show with clock" option as a workaround to get rid of the graphical glitches. It's a bug in Apple's Intel drivers in High Sierra. Tons of discussion here #377. Hopefully Apple releases a fix soon.

To uninstall the screensaver all you need to do is delete the file from either `/Library/Screen Savers` or `/Users/YOURUSERNAME/Library/Screen Savers`.
