### ISSUE TITLE
macOS High Sierra breaks Aerial

### ISSUE THREAD

**Issue by youngbill00** [JohnCoates/Aerial#415]
Upgraded to High Sierra and when Aerial runs, the whole screen turns to a bunch of lines.  I re-installed Aerial and it still does the same thing.

2017 13' MacBook Pro

**Comment by alistairmcmillan** [comment]
Duplicate of #377 

The Intel drivers that Apple include with High Sierra seem to be a wee bit buggy. Until they fix them, as a workaround, tick the "Show with clock" option. That should allow the videos to play okay.
