### ISSUE TITLE
Aerial won't let Mac sleep?

### ISSUE THREAD

**Issue by bradleyks** [JohnCoates/Aerial#419]
Beautiful, ingenious and works very well — High Sierra 10.13.1.
The only wrinkle I've run into is that when Aerial is used, the "Turn Display Off After" in the Energy Saver panel doesn't step in and put the screen to sleep after the chosen time. 
Thanks for your good work ...
bradleyks

**Comment by alistairmcmillan** [comment]
@bradleyks I think you must be running quite an old version. Try downloading the latest version and see if you have the same problem. https://github.com/JohnCoates/Aerial/releases/tag/v1.2

Let us know how you get on.

**Comment by bradleyks** [comment]
Thanks much for your reply. And, yes, I was using v1.1 — v1.2 did the trick!
