### ISSUE TITLE
Screen saver won't disengage

### ISSUE THREAD

**Issue by gjbaxter** [JohnCoates/Aerial#423]
If the screen saver engages (High Sierra), it often won't shut off when the mouse or keyboard is activated. The only method to escape it is to put the Mac laptop to sleep and wake it again.

**Comment by alistairmcmillan** [comment]
@gjbaxter That's weird. Does it happen with other screensavers?

What kind of Mac do you have? And what mouse/keyboard are you using?

Also, are you using the latest version? https://github.com/JohnCoates/Aerial/releases

**Comment by gjbaxter** [comment]
Hello John,

I, of course, don’t use any other screen savers but yours!  And yes, running 1.2.

But.. I’ll give running a different screen saver a test.

I have a macbook pro 13” running High Sierra (which was the recent change, so I chalked it up to that).

Keyboard is an apple bluetooth keyboard or the laptop keyboard itself.

The behavior is odd.  It does respond to, say, the app switch (cmd tab) and the screen ‘resizes’ for a second, but still stays locked in and running.

Thanks,
George

**Comment by gjbaxter** [comment]
Good news!  Well.. good for you.. it happened for another screen saver.  Not your problem.  Sorry about that.

Thanks,
George

**Comment by alistairmcmillan** [comment]
Good to hear. I'm not John btw. :)

**Comment by gjbaxter** [comment]
and I'm just dumb.  Sorry Alistair!
