### ISSUE TITLE
480p quality on an iMac?

### ISSUE THREAD

**Issue by S402** [JohnCoates/Aerial#426]
Just installed Aerial on my iMac mackintosh but the videos look like they're in 480p quality or something like that. I use a 1440p monitor and thought the videos would be higher quality. I have Aerial installed on my late 2016 15" MacBook Pro and they look like they are scaled correctly for that display. Is there something I need to do to make the videos HD or higher resolution on my iMac or is this just not how Aerial works? Sorry if this is a dumb question, maybe I'm just missing something here. Thanks.

**Comment by alex-mohemian** [comment]
Same for my 15" Macbook Pro (1920x1200).

**Comment by glouel** [comment]
Please give version 1.4 a try, it has improved retina support.

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
