### ISSUE TITLE
4K Videos

### ISSUE THREAD

**Issue by AVC29** [JohnCoates/Aerial#431]
Hi there, I have a 5K iMac and would love for this screensaver to play the 4K versions of the files. Is this something that is coming? Thanks so much.

**Comment by leggsimon** [comment]
https://github.com/JohnCoates/Aerial/issues/378

**Comment by ccharlton** [comment]
Close ticket due to being a dupe.

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #378.
