### ISSUE TITLE
Caching of videos fails, static image shown as screensaver

### ISSUE THREAD

**Issue by eladkatz** [JohnCoates/Aerial#432]
This is similar but not the same as the no playback known issue
I am trying to manually cache the videos but the fail after a few minutes of downloading.
Is there a way to download them independently and place them in the cache directory? 
When it fails it shows a message about NSURL failure but it's cropped and not copyable...

<img width="668" alt="screen shot 2017-12-12 at 2 16 35 pm" src="https://user-images.githubusercontent.com/1302574/33903717-44e94f40-df47-11e7-92bc-bfe7d76009c4.png">

**Comment by eladkatz** [comment]
To clarify, I've successfuly downloaded the videos in the No Playback URLs

**Comment by eladkatz** [comment]
Mac OS: High Sierra
2017 Macbook pro 13"

**Comment by alistairmcmillan** [comment]
@eladkatz If you are getting a network connection problem, it is most likely something getting between your MacBook and Apple's CDN servers, could you try caching the videos on another network?

**Comment by eladkatz** [comment]
I guess it was - it eventually got it, I guess this issue is more about the error message being unclear and the inability to resume correctly than about any real problem with the connection and download locations

**Comment by milanchokshi** [comment]
I found a solution. In MacOS High Sierra, check the box "show time" and it will get rid of the issue all together. It took a awhile to figure out a simple fix to this annoying issue.

**Comment by alistairmcmillan** [comment]
@milanchokshi That's a different issue. And discussed under #377.

**Comment by milanchokshi** [comment]
I tired that and it did not fix the issue for me. The show time trick worked
