### ISSUE TITLE
Doesn't work on 10.13.3 Beta (17D25b)

### ISSUE THREAD

**Issue by drekka** [JohnCoates/Aerial#433]
The screen looks like some sort of sync issues is occurring, but I'm not sure. The screen save flashes up for a second, then the image is cut into lots of horizontal strips of the image.

**Comment by alistairmcmillan** [comment]
@drekka Did this work okay for you in 10.13.2?

**Comment by alexeyst** [comment]
It doesn't work for me on 10.13.2 — same thing with issues. It does work on Discrete video card though.

**Comment by alexeyst** [comment]
Show with clock resolves it!

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #377
