### ISSUE TITLE
Wrong video preview shows up in main settings page

### ISSUE THREAD

**Issue by gsbernstein** [JohnCoates/Aerial#434]
Pretty sure golden gate isn't in china.
<img width="668" alt="screen shot 2018-01-06 at 5 45 01 pm" src="https://user-images.githubusercontent.com/6655924/34645716-84211cb2-f309-11e7-9a7d-803c6182aaf5.png">

**Comment by glouel** [comment]
This should no longer happen in 1.4, please give it a shot.
