### ISSUE TITLE
Unable to use the screensaver in China due to network problem

### ISSUE THREAD

**Issue by ywc1884** [JohnCoates/Aerial#436]
Hi, I actually saw this screen saver in a Chinese forum and after I downloaded and installed it in my mac I tried to review the screen saver in system preferences , but unfortunately nothing was shown. I heard someone in that forum mentioning  about the network problem and then I used the global mode for my vpn and only then I could see the videos in the screen saver. 

It will be great if you could add the network proxy setting support for this screen saver.

Regards,
Ben

**Comment by alistairmcmillan** [comment]
Best solution is to make sure you are using [the latest release](https://github.com/JohnCoates/Aerial/releases) and cache the videos though the VPN.
