### ISSUE TITLE
Aerial Video not playing

### ISSUE THREAD

**Issue by stan-man** [JohnCoates/Aerial#44]
I have a late 2008 MacBook Pro running OS X El Capitan 10.11. After downloading Aerial, this is what I have to choose from.

![screen shot 2015-10-28 at 6 41 06 am](https://cloud.githubusercontent.com/assets/15360611/10787497/52739dee-7d3f-11e5-948f-d26e082cde12.png)

**Comment by rikro** [comment]
Same here.

**Comment by katieorenstein** [comment]
+1 for the same issue

**Comment by austinfox** [comment]
+1

**Comment by pitchmak** [comment]
@stan-man did your mac has QuickTime or playable .mov extension?

**Comment by pylebecq** [comment]
:+1: 

Installed it a few days ago, was working fine, today it does not work anymore.

**Comment by alistairmcmillan** [comment]
@stan-man @rikro @katieorenstein @austinfox @pylebecq Which version are you running? Does your version have the cache options in Preferences? https://github.com/JohnCoates/Aerial/releases

**Comment by pylebecq** [comment]
@alistairmcmillan I'm running version 1.0. I did not see any cache related option in preferences, I only have an option called "Play a different video on each monitor" (sorry, might not be the accurate name, I'm translating from french)

**Comment by alistairmcmillan** [comment]
@pylebecq Try the most recent beta. John has fixed a number of bugs and added a caching feature that lets you play the video from your own machine instead of streaming from Apple's servers.

**Comment by rikro** [comment]
Alistair, I was running the original release, and have now updated to the
most recent and all is good ... really like the caching piece! I'm also now
watching the repo so I'll be aware of future updates. Thanks.

**Comment by alistairmcmillan** [comment]
@stan-man @pylebecq @katieorenstein @austinfox @rikro  Did you get the screensaver working?

**Comment by pylebecq** [comment]
Yes, sorry I didn't keep you posted. Using the latest beta did the trick.
Thank you for your help and your work.

**Comment by alistairmcmillan** [comment]
@pylebecq Not my work. @JohnCoates is the guy to thank.
