### ISSUE TITLE
Request: hosting own aerial videos

### ISSUE THREAD

**Issue by clapperman** [JohnCoates/Aerial#441]
THANK YOU SO MUCH FOR THIS APP. It is beautiful and peaceful.

I am a graduate assistant at a college and would love the option to use your app to point to a list of hosted aerial videos of our campus so that students could load your software but with our videos. Would that be an easy change to point the request to a different set of links?

**Comment by jc1arke** [comment]
If you match the JSON returned from http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json to your dataset, you should be able to change it to wherever you want via https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Models/ManifestLoader.swift#L76

**Comment by pendowski** [comment]
@clapperman I've built an app which evolved into a screen saver as well which might be helpful for that if you host your videos on YouTube, Vimeo or Wistia: https://github.com/pendowski/VSaver
Check it out and let me know if it works for you. Adding some other hosting services should be a big of a deal.

**Comment by glouel** [comment]
You can now do that by editing the JSONs if that's your thing. There are also other screensaver more apt to this so closing ;)
