### ISSUE TITLE
Minor graphical bugs on 10.13.1

### ISSUE THREAD

**Issue by Yoruiopz** [JohnCoates/Aerial#443]
On the menu, the text glitches into itself like this.
![screen shot 2018-02-28 at 9 25 48 am](https://user-images.githubusercontent.com/36910989/36771482-28c16d10-1c6a-11e8-9abe-6f2ad944f051.png)

The preview sometimes turns black like this.
![screen shot 2018-02-28 at 9 25 57 am](https://user-images.githubusercontent.com/36910989/36771474-18e1a9aa-1c6a-11e8-8e51-a14a8b9cbbf0.png)

The menu sometimes disappears and there are no check boxes.

Whenever a video ends, the screen turns black for half a second and the video resizes itself.

**Comment by BeancurdPachelbel** [comment]
i had this issues too, is there some way out?

**Comment by glouel** [comment]
This is now fixed in 1.4 !
