### ISSUE TITLE
dual screen setup macbook has bars on top and bootom and content in the middle zoomed far in

### ISSUE THREAD

**Issue by Nattinger** [JohnCoates/Aerial#444]
Hi everyone. Love aerial. but since i moved my macbook pro retina over my 1080p asus monitor  and making them fit together, aerial is having trouble previewing it. on my asus monitor everything is fine but on my macbook now there are bars on top and on the bottom and the content is totally zoomed in. and when i enter my password you can see it goes back to its normal state without bars and zoom.

video where i show the problem
https://youtu.be/eErC_Aus0tI

**Comment by wayneddgu** [comment]
I am having the same issue

**Comment by RSickenberg** [comment]
Same without double screen

**Comment by RSickenberg** [comment]
You can close this, it's a duplicated from https://github.com/JohnCoates/Aerial/issues/442

**Comment by gregorsmith** [comment]
Same problem that only begun a few days ago, external screen is fine, laptop on starts fine but quickly flashes  and the bars appear while the video seems to be bottom aligned, tried removing everything to reinstall but no fix. Only thing that has updated recently was Xcode on the 14th

**Comment by glouel** [comment]
If you are still interested, can you give this build a try : 
https://github.com/glouel/Aerial/releases/download/1.4.1test4/Aerial.saver.zip

This should fix issues in 10.13 particularly (10.14 seemed ok in 1.4), it also has a display on main monitor only option as a fallback.

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
