### ISSUE TITLE
Use Aerial not connected

### ISSUE THREAD

**Issue by joreste** [JohnCoates/Aerial#448]
I have a Mac Pro that is not connected to any network and would like to use the Aerial screen saver.

I have copied all the videos from the Cache of a machine that has Aerial installed and installed them to the Cache folder on the Mac Pro.

Is there any way to get the Mac Pro to use just the Cached videos?

Thanks,

Joe

**Comment by glouel** [comment]
This is now implemented in 1.4, see the Offline mode section in the main project readme !
