### ISSUE TITLE
[feature] Dynamic Day/Night scenes based on local time

### ISSUE THREAD

**Issue by alex-mohemian** [JohnCoates/Aerial#450]
The original Apple TV screensaver chooses scenes based on local time:

> As Apple said when it introduced the new Apple TV in September, all of these screensavers are dynamic, and day and night shots actually change depending on your local time.

Would be a nice addition (optional with checkbox)

**Comment by xenDE** [comment]
And a "select all night scenes" for manual select only night scenes.

same for day scenes.

**Comment by glouel** [comment]
Implemented in 1.4 !
