### ISSUE TITLE
[feature] Scene title/location

### ISSUE THREAD

**Issue by alex-mohemian** [JohnCoates/Aerial#451]
The Android [Aerial Dream](https://play.google.com/store/apps/details?id=com.codingbuffalo.aerialdream&hl=en) app has a feature that shows the title and (exact) location of the video (e.g. `LAX airport, Los Angeles, USA`) in the lower left corner as an overlay.

Would be a beautiful addition.

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #58
