### ISSUE TITLE
10.13.4 Macbook Pro 13' display error

### ISSUE THREAD

**Issue by guyunxiang** [JohnCoates/Aerial#452]
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) Touch Bar
MacOs 10.13.4
When using default setting display error
![image](https://user-images.githubusercontent.com/7507079/38845669-2786a992-422b-11e8-8df0-a2782082838a.png)
But using scaled display settings (Only More Space 1680 x 1050 setting) display correct.

**Comment by kaekill** [comment]
I have the same issue

**Comment by funfried** [comment]
I was able to fix that issue by turning on the clock in the screensaver settings 😂 
I have no idea why, but it really fixes the issue, but now since the last update I have a similar issue, it seems the resolution doesn't fit anymore:

![image](https://user-images.githubusercontent.com/7093028/38984140-3b5727fc-43c6-11e8-8eda-0d6df5ea1d88.png)

**Comment by guyunxiang** [comment]
@funfried you are right, fix too.😂

**Comment by kamilgregorczyk** [comment]
I have the same issue as @funfried

**Comment by MrKyhme** [comment]
Ty, @funfried! Works 😄

**Comment by YaoJuan** [comment]
@funfried  hah ,its works

**Comment by ntompson** [comment]
I have the same issue as @funfried - but I've been using the clock to deal with High Sierra issues for some time. So it is still broken for me. Sounds like 10.13.4 has broken something (again). Any plans to fix?

**Comment by MescalHeart** [comment]
Got the same issue, when using external display the main macbook pro 13" display keeps flipping continuously between fullscreen (filled/stretched) and the original aspect ratio of the video (black bars top and bottom).

**Comment by grebmeg** [comment]
I also have this issue on MacBook Pro 13" with Touch Bar. It can be fixed by turning on clock on screensaver (thank you @funfried)

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
