### ISSUE TITLE
screensaver downloading continuously overnight

### ISSUE THREAD

**Issue by dmiddlecamp** [JohnCoates/Aerial#454]
I'm seeing a network where 5-6 computers using this screensaver have downloaded about 2TB of MOV files.  Is it possible the latest version has some cache issue that is preventing cache from operating correctly, and having the same files downloaded over and over?

**Comment by dalupus** [comment]
I have run into this as well.  Downloads constantly while screensaver is showing.

**Comment by glouel** [comment]
This should be fixed in V1.4, you can now disable streaming and cache videos individually.
