### ISSUE TITLE
Can I cache the json?

### ISSUE THREAD

**Issue by UnclePluto** [JohnCoates/Aerial#456]
I am behind firewall of China, so i download all the video to cache. It worked well before.But now i alway stuck by `loading json`.

I know it should to get a json from apple's CDN by first.But it seems it blocked in China.

So may i ask the json can be cached? I have gotten 12.75G videos, I do not wanna stop by the json...If the json isn't changing all the time,Can it be a static file in the code?

I love the app so much,I don't wanna give up it.

**Comment by uuunit** [comment]
https://pan.baidu.com/s/1jIdunZK
Download it ,Put it in` /Users/***/Library/Caches` .

**Comment by UnclePluto** [comment]
thank you，but it doesn't work
<img width="676" alt="image" src="https://user-images.githubusercontent.com/9131383/39091726-f218e1ec-462d-11e8-93c6-3a309e042016.png">
I download it，and change the extension to list ,but it is still loading Json,Should I change its extensions  to Json

**Comment by uuunit** [comment]
Try this   https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5
It's not always working.
Something about Aerial :
https://sspai.com/post/39000
OR just use http://s.sudre.free.fr/Software/SaveHollywood/about.html

**Comment by UnclePluto** [comment]
Thank you，saveHollywood is working

**Comment by glouel** [comment]
This is a bit old but closing too as fixed in 1.4, we have full offline mode now (see the project readme)
