### ISSUE TITLE
Flickering at startup on OS 10.13.4

### ISSUE THREAD

**Issue by ghost** [JohnCoates/Aerial#459]
I have been using the screen saver for a while and then recently updated to High Sierra
Since then the screensaver always flickers at the start for a few seconds before it settles

I have a Macbook Pro 13 inch and the display settings are set to more space

**Comment by kruteev** [comment]
++++

**Comment by jamesyorke** [comment]
++++++++++

**Comment by rpaasch** [comment]
Im also on 10.13.4 (17E202). My screen flickers a few seconds after startup.

**Comment by jonmunson** [comment]
Also having this issue. "Show with clock" does resolve, but the clock is then shown.

**Comment by darit** [comment]
I've noticed that the flickering happens when I hover the front camera... really weird (MacBook Pro 2017 15¨)
