### ISSUE TITLE
Cache location suddenly empty

### ISSUE THREAD

**Issue by dennishelbig** [JohnCoates/Aerial#460]
I really love the aerials, great work. 

Since the few months that I use the screensaver, I recognized a dozen times that the cache location (user/library/caches/aerial) is empty and I have to download the videos again. I use a macbook pro (OS 10.13.4) and since I'm not always connected to the internet or the connection isn't always good enough to cache the videos as they play, I like to download them. 

When I see a black screen instead of the screensaver, I have to download the videos again. Unfortunately, I couldn't see any pattern of how this happens. Any help?

Thanks in advance.

**Comment by alistairmcmillan** [comment]
My guess is that your drive is running out of space. Don't let it run out of space.

Can't find documentation for this right now but I'm pretty sure if your Mac is runing out of space the operating system will automatically delete files from the ~/Library/Caches folder to make room.

**Comment by alistairmcmillan** [comment]
There's a wee note from Apple talking about this in iOS. I'm sure macOS behaves the same way.

`Note that the system may delete the Caches/ directory to free up disk space, so your app must be able to re-create or download these files as needed.`

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

**Comment by dennishelbig** [comment]
I got a 500gb disk and still 250gb available, so not exactly  "running out".
But thanks for the hint, I change the cache path to something different and will see.

thx & best
D.

**Comment by alistairmcmillan** [comment]
The only other thing that comes to mind is that there are tons of applications that do a bunch of housekeeping tasks to the operating system. For example OnyX or CleanMyMac. One of the things they usually do is delete things from the Cache folder.
