### ISSUE TITLE
Video freezes after playing normally for a variable period of time

### ISSUE THREAD

**Issue by yvesadeleharlow** [JohnCoates/Aerial#468]
Aerial exhibits frozen video playback:
On macOS 10.13.4, Aerial plays video as soon as it engages and continues to do so until the display shutoff timer triggers. Tapping the shift key breaks out of the screen saver to a login prompt as usual.
On macOS 10.13.5, Aerial plays video for a variable length of time after engaging, then freezes. Tapping the shift key breaks out of the screen saver, returning to a login prompt as usual.

**Comment by dsibilly** [comment]
I have this same issue on macOS 10.13.5. Video playback just _stops_ after a time and will not resume. Given that his puts a static image on my displays when it occurs, it limits Aerial's usefulness as a screensaver.

**Comment by Syden10** [comment]
Had this issue before under Sierra and a macOS update fixed it, now it seems to be back I believe it could be 10.13.5. Tried reinstalling aerial and re-caching vids but no luck.

**Comment by martensson** [comment]
I got the same problem in 10.13.6, seems to freeze after a short while and after just looks like a static image.

**Comment by teilor** [comment]
+1
I'm having the same issue, also with macOS version 10.13.6

**Comment by willihangga** [comment]
+1
I'm having the same issue,

**Comment by timvloon** [comment]
+1
I'm also having this issue on MacOS 10.13.6

**Comment by sebrk** [comment]
Same 10.13.6

**Comment by crts-failure** [comment]
yes, bug is still there in 10.13.6

**Comment by Syden10** [comment]
+ 1 (10.13.6)

**Comment by bcarter-cs** [comment]
+1 same here on 10.13.5 and 10.13.6

**Comment by choicelildice** [comment]
+1 same on 10.13.6

**Comment by esetnik** [comment]
Can users affected by this issue provide us with the following:

1. Full hardware profile
2. Results after testing with https://github.com/JohnCoates/Aerial/pull/501

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
