### ISSUE TITLE
Feature: tame data consumption in a better way

### ISSUE THREAD

**Issue by inadarei** [JohnCoates/Aerial#471]
If videos are not cached, this screensaver streams enormous files over network. Imagine you are traveling, getting your internet via tethering / personal hotspot and suddenly screen saver turned on your laptop - it can it up hundreds of megabytes/gigabytes of data before you realize it. That is dangerous.

There should be an option to disable streaming videos unless you are on wifi (non-hotspot one).

Yes you can cache videos, but - most people may not realize they have to. Also: the current cache feature downloads ALL videos, which now eats up gigabytes on your drive. It should be possible to only download select ones (just like you can select which ones you want to play).

**Comment by glouel** [comment]
Side note related to this issue, there is also an issue with cached videos still making network requests (as mentioned in this issue https://github.com/JohnCoates/Aerial/issues/512#issuecomment-426009013).

I do have a workaround for that one. Working on a "Never stream videos" options right now.

**Comment by esetnik** [comment]
There are third-party utilities designed to trim data consumption. A temporary workaround might be to install something like [TripMode](https://www.tripmode.ch/) which I use personally for this purpose.

**Comment by glouel** [comment]
Closing as fixed with v1.4, there are now options to block streaming and full offline mode
