### ISSUE TITLE
Doesn't fit multiple screens with different aspect ratios

### ISSUE THREAD

**Issue by theodormarcuOrbital** [JohnCoates/Aerial#472]
Just installed this great screensaver and the video looks distorted (just the edges) on my Macbook's display, but not on the monitor. Any ideas how I could fix this?

**Comment by timoa** [comment]
+1

**Comment by matttargett** [comment]
+1

**Comment by gabel** [comment]
+1 same here

**Comment by MikhailKaduchka** [comment]
+1 same with 10.13.5

**Comment by ominixamf** [comment]
this started happening my MacBook Air with 10.13.6

I noticed that it happens when the screen brightness is adjusted automatically upon light variations in the environment (or, just when I noticed, when you are coming back to your notebook and passes in front of the screen)

**Comment by jonnylangefeld** [comment]
+1 with 10.13.6

**Comment by iamsanteri** [comment]
+1 with 10.13.6

**Comment by uberux** [comment]
+1 with 10.13.6

**Comment by alistairmcmillan** [comment]
A photo of the distortion might help identify what is going on. Hard to understand what the distortion looks like for those unaffected.

**Comment by mpdifran** [comment]
MacBook Pro (13-inch, 2018)

![img_3412](https://user-images.githubusercontent.com/1365987/43462490-3a198a54-94a4-11e8-843a-a2973e9e3e79.jpg)

**Comment by alistairmcmillan** [comment]
@mpdifran What happens if you tick the "Show with clock" button?

**Comment by mpdifran** [comment]
Enabling "Show with clock" seems to fix it. I see the above screenshot whenever "Show with clock" is disabled.

**Comment by theodormarcuOrbital** [comment]
Doesn't fix it for me. @mpdifran  @alistairmcmillan 
![img_3857](https://user-images.githubusercontent.com/39921323/43466528-b7df3228-94ad-11e8-9d66-848122e42e05.JPG)

**Comment by mpdifran** [comment]
Yeah, I think I have something similar when connected to my external monitor (21:9 ratio).

**Comment by Fastjur** [comment]
I also have this issue. When an external monitor is connected, the video on my MacBook is not full screen and zoomed in, looking rather pixelated.
![img_20180926_132849](https://user-images.githubusercontent.com/1493561/46077233-6c3a1f80-c190-11e8-9435-eb2c05e0afca.jpg)

**Comment by glouel** [comment]
@Fastjur Could you check this build : 
https://github.com/glouel/Aerial/releases/download/1.4.1test4/Aerial.saver.zip

This should fix issues in 10.13 particularly (10.14 seemed ok in 1.4), it also has a display on main monitor only option as a fallback. Can you tell me what it gives you ?

**Comment by glouel** [comment]
As far as I know this is fixed in 1.4.1, reopen otherwise

**Comment by gabel** [comment]
Fixed for me with 1.4.1 on macOs Mojave 10.14

**Comment by Fastjur** [comment]
It fixed for me when updating to Mojave. Thank you!

**Comment by glouel** [comment]
Ok this really looks like a 10.13.6 bug then ! Thanks @gabel and @Fastjur for your feedback !
