### ISSUE TITLE
You cannot use the Aerial screen saver with this version of OS X - macOS Mojave - No Fix

### ISSUE THREAD

**Issue by jbis9051** [JohnCoates/Aerial#476]
The fix provided doesn't work on macOS Mojave 10.14 Beta 3.
<img width="780" alt="screen shot 2018-07-13 at 1 12 51 pm" src="https://user-images.githubusercontent.com/32957090/42704692-d9a31432-869e-11e8-9ea2-a5ab2d878b46.png">

**Comment by jbis9051** [comment]
So how are we supposed to make screen savers?

**Comment by JonoHaysom** [comment]
Beta 4 just killed it in its entirety.

**Comment by warrentheranga** [comment]
As above - updated the project to target 10.14 only, x86_64 architecture only... no joy. Builds fine though with Xcode 10.0 beta (10L176w)

**Comment by mikegazdag** [comment]
Duplicate of https://github.com/JohnCoates/Aerial/issues/464

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #464
