### ISSUE TITLE
Feature request : Set arrow keys as a way to browse aerials and toggle on/off the name of the aerial.

### ISSUE THREAD

**Issue by fashnbly-l8** [JohnCoates/Aerial#479]
On AppleTV 4K, you can swipe left or right to browse other aerials.  The name/location of the aerial is also displayed.  It would be nice to include a similar feature to this screensaver.

**Comment by twinysam** [comment]
That could be a nice feature.
Does anyone have a json for the new Aerial videos? Such as the space ones as seen here: https://www.apple.com/sa/newsroom/2018/06/apple-tv-4k-delivers-highest-quality-cinematic-experience-with-tvos-12/

**Comment by esetnik** [comment]
@fashnbly-l8 I'm not sure if it's possible to intercept keyboard events during screensaver playback. Do you have any examples of other screensavers that are interactive? It might be dangerous to intercept keyboard events since they are usually designed to interrupt screensaver playback and restore the system to a wake state. If we did implement this feature we'd want to make sure that it's configurable and disabled by default. I think most users would expect that keyboard events will terminate screensaver playback.

**Comment by ccharlton** [comment]
I remember seeing that behavior on a 3rd-party screensaver back in the 10.3 days. The arrow keys and a few other specific keys were used to cycle/modify settings. For the life of me, I can't remember the name of it.

**Comment by NightRaider73** [comment]
> On AppleTV 4K, you can swipe left or right to browse other aerials. The name/location of the aerial is also displayed. It would be nice to include a similar feature to this screensaver.

Or maybe trackpad swipe, same as Apple TV: 
Tap show description
Slide Left/ Right Switch between Aerials
Click or any key to exit screensaver.

>

**Comment by NightRaider73** [comment]
@glouel I kinda like this:
Or maybe trackpad swipe, same as Apple TV:
Tap show description
Slide Left/ Right Switch between Aerials
Click or any key to exit screensaver.

**Comment by glouel** [comment]
I like that too but I'm not sure what kind of access we have to keyboard/trackpad. I'll have a look in next-ish update.

**Comment by NightRaider73** [comment]
@glouel I know you saw this but, In #21 apparently you used to use the arrow keys to control video.
Is there anyway that you could contact JohnCoates to ask him how he did that then rewrite the functions differently?

**Comment by jhewell56** [comment]
Any progress or updates on this request? I would like it as well, if possible.

**Comment by glouel** [comment]
> Any progress or updates on this request? I would like it as well, if possible.

It's still in the todo list, I'm not sure if we can still do that on modern macOS, we'll see next year I guess ;)

**Comment by glouel** [comment]
@jhewell56 and others
You can now use the right key to skip ahead, this can be disabled in preferences : 

![Capture d’écran 2019-04-26 à 12 24 08](https://user-images.githubusercontent.com/37544189/56801678-53751380-681e-11e9-9820-8f5325fbef59.jpg)

Available starting with beta 10: https://github.com/JohnCoates/Aerial/releases/tag/v1.4.7beta10
