### ISSUE TITLE
Screensaver does not stop on arrow keys

### ISSUE THREAD

**Issue by kix** [JohnCoates/Aerial#48]
I usually use arrow keys to unlock my Mac, these are quite reachable and I'm sure I won't get any unnecessary symbols in my password field afterwards. However, Aerial seems to go to per-frame mode when I press arrow keys instead of starting the unlock procedure. 
This issue is not compatible with #21

**Comment by JohnCoates** [comment]
Try the latest version from https://github.com/JohnCoates/Aerial/releases/

**Comment by kix** [comment]
@JohnCoates, thanks!
