### ISSUE TITLE
Cannot use Aerial Screensaver with OSX 10.14 Beta 4

### ISSUE THREAD

**Issue by tpmacleod** [JohnCoates/Aerial#480]
Aerial screensaver will not work with OSX 10.14 Beta 4. I believe it stopped working with the update. I do understand these are betas but I enjoy the project so much I was just looking to get it working.

Tim

**Comment by warrentheranga** [comment]
Duplicate of https://github.com/JohnCoates/Aerial/issues/464

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #464
