### ISSUE TITLE
Compatibility with macOS Mojave

### ISSUE THREAD

**Issue by andy9man** [JohnCoates/Aerial#481]
Really appreciate the work you do, awesome screensaver.  Doesn't seem to work with Mojave, any plans on making an update?  And 4K?

**Comment by yurivangeffen** [comment]
> You cannot use the Aerial screen saver with this version of MacOS. Please contact the vendor to get a newer version of the screen saver.
- Desktop & Screen Saver

**Comment by bdnk** [comment]
Duplicate of #464

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #464
