### ISSUE TITLE
Error displaying fullscreen videos on Mac Mini

### ISSUE THREAD

**Issue by TheElectroclassics** [JohnCoates/Aerial#485]
I have problems with the Mac Mini, it's not displaying the screen saver in full resolution, it shows it scaled and the surroundings show as the border pixels.

**Comment by alistairmcmillan** [comment]
@TheElectroclassics How many monitors are you running off of your Mac mini? And are any of them in vertical orientation?

**Comment by rpairo** [comment]
I have the same problem

**Comment by rpairo** [comment]
I have the same problem.

**Comment by rpairo** [comment]
I have the same problem.

**Comment by alistairmcmillan** [comment]
Duplicate of #472
