### ISSUE TITLE
Feature request - download/ cache screensavers

### ISSUE THREAD

**Issue by nilsdecker** [JohnCoates/Aerial#489]
It would be awesome if there were some buffering or a downloading function for this. I was on a wobbly internet connection this past week and when not connected properly, the screensaver just didn't work. Perhaps just have a feature that will update/ download/ refresh every ever so often?!

Love it though, thanks for making it available!

**Comment by alistairmcmillan** [comment]
@nilsdecker Which version are you on? Caching has been a feature since 2015.

**Comment by nilsdecker** [comment]
I am on the latest version. 

I think this must have been a hiccup on my personal laptop (possibly related to black screen issue). I tested on two other machines and both work even with wifi disabled.
