### ISSUE TITLE
Caching Hangs

### ISSUE THREAD

**Issue by sclsj** [JohnCoates/Aerial#491]
Please see attachment. Cacheing hang at the process "loading JSON".
![image](https://user-images.githubusercontent.com/38654636/45618720-4bdfd600-baa9-11e8-8d1e-94ae8fd67484.png)

**Comment by alistairmcmillan** [comment]
This is most likely because you are behind a firewall or proxy that is preventing access to Apple's CDN partner's network.

Can you access http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json in a browser?

**Comment by Stephen-HWJ** [comment]
Yes, that is because of the GFW. When I tried to use my VPN, the Aerial would work well.

**Comment by esetnik** [comment]
Hi @Stephen-HWJ, it looks like this issue was solved so i'll close it out. If you still need help please open a new issue.

**Comment by sclsj** [comment]
I can access the JSON and the videos from my browser, and can download them at a pretty fast speed in FDM/Folx (downloaders). However, I must use a VPN to download the video in the Aerial, or else it will fail. I really don't know why.
