### ISSUE TITLE
Not picking up new Aerials seen in new tvOS 12

### ISSUE THREAD

**Issue by cgatesman** [JohnCoates/Aerial#492]
A whole bunch of new Aerial screensavers were introduced in tvOS 12 including NASA images.  None of these are being picked up.

**Comment by glouel** [comment]
They don't show up in the json file whether this one or the 4K one (https://sylvan.apple.com/Aerials/2x/entries.json). 

Odds are they changed the URL for tvOS12.

**Comment by cgatesman** [comment]
That's what I was thinking, also.

**Comment by glouel** [comment]
See here for a tentative fix : https://github.com/JohnCoates/Aerial/issues/463#issuecomment-423211634
