### ISSUE TITLE
https://help.github.com/articles/about-notifications/

### ISSUE THREAD

**Issue by scottws2000** [JohnCoates/Aerial#497]
_Originally posted by @esetnik in https://github.com/JohnCoates/Aerial/pull/422#issuecomment-384743092_

Are you adding the new Apple TV screen savers that just came out

**Comment by scottws2000** [comment]
Are you adding the new Apple TV screen savers that just came out

**Comment by glouel** [comment]
Fixed in 1.4b9 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9
