### ISSUE TITLE
Project Maintainer

### ISSUE THREAD

**Issue by esetnik** [JohnCoates/Aerial#499]
@JohnCoates @alistairmcmillan the project issues and PRs have gone unresolved for awhile. Are you willing to open up the project to an additional maintainer or two?

**Comment by glouel** [comment]
Would @esetnik like to volunteer ? I can give a hand but I have little experience on github :)

**Comment by esetnik** [comment]
Yes I’d be happy to help out with the project.

**Comment by glouel** [comment]
Sounds good ! I can also give a hand on handling issues, etc if needed. There are a few things that still need to be addressed so let us know @JohnCoates

**Comment by AnJellyCue** [comment]
I’d be happy to help out with the project.

**Comment by esetnik** [comment]
@johncoates where are we with this? I’d love to be able to merge in #501

**Comment by glouel** [comment]
@JohnCoates seemed to have been away according to his twitter but he twitted yesterday. 

So please come back to this thread @JohnCoates we really need to move on on this, I'm slightly tired of answering the many duplicate issues created for stuff I fixed already in builds that people don't see ;)

**Comment by JohnCoates** [comment]
@esetnik and @glouel I’m happy to add you as maintainers. I’m a fan of your contributions and you both seem dependable.

**Comment by glouel** [comment]
Sounds good to me, many thanks ! 

Thanks for the merge too, we might want to put up a new release up on this repo (and update the .md as I had tweaked it for my own fork, sorry about that !)

**Comment by esetnik** [comment]
Thanks @JohnCoates looking forward to helping out further with the project. Let me know when you've given us the maintainer permissions.

**Comment by JohnCoates** [comment]
Added both of you. I'll build a new release in a moment

**Comment by JohnCoates** [comment]
@glouel could you issue a release? My Xcode is stuck at 9 and my internet is 0.35 Mbps so it'll take about a year for me to update to the required OS and download Xcode 10 hah

**Comment by glouel** [comment]
I was going to suggest it. Should I also sign it ?

**Comment by JohnCoates** [comment]
Yeah, that would be great

**Comment by glouel** [comment]
All done, and updated the readme with the correct link to it. Other parts of the readme should probably be updated too to reflect recent changes. 

I have to go right now but I'll have a look at closing duplicate issues later today.
