### ISSUE TITLE
Update the Aerial Clips

### ISSUE THREAD

**Issue by frankhome61** [JohnCoates/Aerial#502]
tvOS 12 included more Aerial screensavers, is it able to get this macOS version up to date?

**Comment by glouel** [comment]
See here https://github.com/JohnCoates/Aerial/issues/463#issuecomment-423755801 #

**Comment by glouel** [comment]
Fixed in 1.4b9 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9
