### ISSUE TITLE
task VTDecoderXPCService high cpu load

### ISSUE THREAD

**Issue by Marx1st** [JohnCoates/Aerial#505]
Hi!

I'm using @glouel's latest build on Mojave on a late 2014 13" MacBook Pro.

I've set it to 1080p and display different videos on each of my 2 displays and it works fine, but during video playback (also in the settings app) the VTDecoderXPCService task creates a very high cpu load.

I thing playing two 1080p videos shouldn't be that taxing or am I wrong?

**Comment by glouel** [comment]
You can check this message for the long answer : https://github.com/JohnCoates/Aerial/issues/503#issuecomment-424086557

I'll try to have a H264 version soon, maybe later today, this would run much better on anything pre-Skylake (so before late 2015).

**Comment by glouel** [comment]
Please try this version and let me know, if you use 1080p H264 it should fix your load issue : https://github.com/JohnCoates/Aerial/issues/463#issuecomment-424407877

**Comment by Marx1st** [comment]
Thanks a lot! With H264 my cpu load is fine!
