### ISSUE TITLE
Updating the readme.md

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#510]
I think we need to update the project readme to reflect some of the changes. The top description mentions videos that are no longer available in the latest version. We should probably reflect that in some way (point people who want the new videos to latest versions, and those who want the old ones to the other one). 

I also think JohnCoates's twitter info is outdated.

**Comment by alock** [comment]
@glouel - is the plan to continue to support the brew cask install on the README?  I can create a PR to https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aerial.rb but wanted to know when the 1.4 versions will be out of pre-release?

**Comment by fibric** [comment]
@alock create a PR whenever Aerial drops the prerelease tag :)
Nobody owns casks.

**Comment by alock** [comment]
Yea I really just want to know why 1.4 is still in pre-release no issues for me. :)

**Comment by glouel** [comment]
I think there's still one issue I wanted to cleanup with this PR https://github.com/JohnCoates/Aerial/pull/511, apart from that I think it's probably good enough for a release although some people may be surprised that the old videos aren't there. I'll ask @esetnik and @JohnCoates their opinion on the matter.

**Comment by esetnik** [comment]
@glouel the biggest reason for holding back 1.4 from general release is the loss of previous content that people expected. Since you've solved that in #521, I'd be comfortable releasing 1.4 as soon as that gets finalized, tested, and merged.

**Comment by glouel** [comment]
Closing as fixed in release 1.4
