### ISSUE TITLE
Displaying extra descriptions on space video (international users needed !)

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#512]
One of the coolest thing about the new Space screensavers on tvOS12 is that by gently pressing the remote while they play, you can get detailed information about what the camera is flying over.

This is implemented by a set of timestamps and keys in the JSON, that are themselves referencing a localizedStrings bundle that is with the ressources.tar file that we now download in 1.4+. 

I've started implementing support to display those strings in lieu of the basic descriptions, but since those strings are localized (and will be displayed according to your MacOS locale), there are probably some text rendering issues (partially displayed, etc) in some languages that uses non latin characters.

![capture d ecran 2018-09-28 a 20 24 18](https://user-images.githubusercontent.com/37544189/46227478-a1489c80-c35f-11e8-804e-7b76eb6bf249.jpg)

So if you feel adventurous and want to help, I made a test build with that feature here : 
https://github.com/glouel/Aerial/releases/download/test1.41b1/Aerial.saver.zip

Again, this is a test build for those who want to help debug this. 

Some things of note : 
- All the descriptions show with a 2s fade in/fade out
- If you set show for 10s, the new description will pop only for 10s with fade in/fade out. If you set always, the description will stay until replaced by the new one (with a fade out/fade in again which "should" be seamless)
- Land videos have only one description for the whole duration. Space videos have multiple descriptions that can be spaced by as little as 10 seconds

Known issues : 
- The very last description will not fade out before the video gets cut
- It's possible the string disappears before the end with show always, and a land video

Those issues are linked to the fact that I'm currently not detecting the video duration. 

Please report any issue you see in your locale with a description of the issue, your mac model, and possibly a screenshot of the issue you see if it hasn't been reported already. Many thanks in advance to those who will give it a shot.

PS : Also new in this test build, I added some test to check for H.264/HEVC hardware decoding support in the popover: 

![capture d ecran 2018-09-28 a 21 01 17](https://user-images.githubusercontent.com/37544189/46228271-e1a91a00-c361-11e8-9945-b67c0f0a1b91.jpg)

(new screenshots for the 1.4 readme)
![screen shot 2018-10-11 at 14 47 09](https://user-images.githubusercontent.com/37544189/46805565-ad702900-cd65-11e8-9779-91243ee9e634.png)
![screen shot 2018-10-11 at 14 49 52](https://user-images.githubusercontent.com/37544189/46805573-b3660a00-cd65-11e8-9e40-152d170ffd8e.png)
![screen shot 2018-10-11 at 14 50 18](https://user-images.githubusercontent.com/37544189/46805577-b5c86400-cd65-11e8-8c04-252c5fa6c1eb.png)

**Comment by dVIAN13** [comment]
@glouel, everything looks good in newest beta/pull #512! Observed your known issues, however I do not use 'show always'. Great work @ starting the auto-detection of hardware decoding. Looking forward to future updates.

**Comment by glouel** [comment]
Thanks for your feedback @dVIAN13.

Latest build, some pretty nice changes :
- Add video duration detection
- Add fade in/fade out to videos
- Add a shadow around text for better readability

Also fixes the transitions so they are smoother now. I think it's pretty good so barring any bug I'll make a PR out of it, I may add a "English" default for the localization that you can override, depending on feedback from i18n users if any.
 
https://github.com/glouel/Aerial/releases/download/test1.41b2/Aerial.saver.zip

**Comment by dVIAN13** [comment]
Tested out, and it looks great! great work! some things I have observed(not necessarily related to this build).. The RAM hit I take when running the system pref pane with this open(maybe a macOS issue), and then after previewing.. I went from 8GB free RAM to about 3.5. afterwards, it climbs back up.. not sure if there is some type of memory leak? and also, I am wondering how I tell if it's streaming the video vs. playing the cached file? the video seems slightly choppy.. I am running this on a dual monitor (both 2560x1440) connected to an eGPU. here is a video showing what I am talking about. first, I direct play the cached video. next I 'preview' the screen saver. note how choppy it is.. [link](https://cvws.icloud-content.com/B/AVPwOOOA9dQJ-6muo2ochQxqGwppAejpcs3BaGeEZzUNfrZZkMELh9kl/Aerial_test_1.4b2.mov?o=AnOZ6oXJnx4nhoHScw514sV1tbUY1j3LvQEf5LfOxRZN&v=1&x=3&a=BwFDq4EtZPHo3p9Gosvh1z55jptHAxE4RgEAAAMCOEY&e=1538416349&k=AFJDquHkHzxLfgGi9VzVAw&fl=&r=a0af401c-d98f-44f1-b1f2-85b0e9e498f3-1&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=32&s=hGOlma_J0gvN3NWojxKJHSmPm9g&cd=i) I wondering if macOS is not using the eGPU to run the screensaver, instead using the built in(Intel Iris Plus Graphics 650) card? apologies if I'm introducing more complexity ;)

**Comment by glouel** [comment]
Thanks for the quick feedback, your link doesn't work though (says gone, maybe some permission issue). I'll try to have a look here, can you tell me what video format you are using ? 
About streaming vs. cache, best way to tell if you have a doubt is with "Activity monitor" (may not be an accurate translation, what you use to see cpu usage). 

About streaming, basically, it should never stream if you have the files. But you may see some small data usage (about 240 KB in I think ?) which is a bug linked to how the cache is implemented, it's actually linked to the bug I had with duration detection, if you have local files, it will still try to read the video duration that way. This one is not a new bug and something which is not an easy fix, considering how caching is implemented.  

Choppiness may be the memory thing, or too many video streams decoding simultaneously. Anyway, let me know if you can fix your video link.

**Comment by glouel** [comment]
Quick feedback, I wasn't able to reproduce your memory issue so please try to clarify it.

I did find something else that probably explains the chopinness issue for some. All of the SDR HEVC 1080p and 4K videos seem to be encoded with a Main10 profile and that's an issue at least on my machine. Skylake's Gen9's MFX doesn't fully decode HEVC Main10, so it's at best "assisted" or CPU decoded. 

![med-cap-07](https://user-images.githubusercontent.com/37544189/46312191-a4909200-c5c4-11e8-9c73-ab60f621a773.png)

I'm not sure if Apple uses the GPU assist at all for HEVC on Skylake on MacOS. 

If I use either Quicktime or Aerial to play one of the 4K files, I see for one video playing a CPU load of 20-25% (pretty much 1 core maxed) approximately on my Core i5 6600 from the decoder task (VTDecoderXPCService). 

<img width="815" alt="capture d ecran 2018-10-01 a 22 12 49" src="https://user-images.githubusercontent.com/37544189/46313078-38fbf400-c5c7-11e8-8ffb-3daf5fad4845.png">

If I have multiple streams, that goes up quite fast and things start getting choppy. Same thing for 1080p HEVC although it's much lower, maybe 7%.

In your specific case, you have a Kaby Lake, so theoretically, that iteration of Quicksync should handle HEVC Main10 decoding through the MFX. Could you try to see, using QuickTime, if you see a higher CPU load playing one of the 4K videos with the decoder task ? 

Video decoding acceleration seems to be pretty much a black box in AVPlayer, the closest thing I found is this property `preferredVideoDecoderGPURegistryID ` but Apple's documentation is... succinct : https://developer.apple.com/documentation/avfoundation/avplayer/2942616-preferredvideodecodergpuregistry

Maybe one can specify to use another GPU through that. 

In this message https://github.com/JohnCoates/Aerial/issues/463#issuecomment-424744678, I assumed that MacOS prefers QuickSync when available over dGPU acceleration, which may or may not be correct. It's hard to know, really, and the function that lets you check if hardware acceleration is available (`VTIsHardwareDecodeSupported`) only seem to allow to check for codecs without a specific profile (and answers available on my iMac for HEVC) and not for the specifics (checking if Main10 decoding is available would help).

**Comment by dVIAN13** [comment]
Hi There, I have the following video, [link](http://ewing.tech/misc/1.4b2_test2.mov) this shows the CPU hit on playing file directly.(doesn't seem to be one for me(2017 MacBook Pro 13" 4 - tb3 ports). secondly it shows what happens when I open the system prefs.

**Comment by glouel** [comment]
Thanks for your quick answer and the video !

So, the good news is that, at least on Kaby Lake+, 4K Main10 HEVC is hardware decoded, so that's a win :) I guess I should use the CPU generation to try and refine the HEVC detection. 

Regarding your issue, I think it has nothing to do with Aerial. Check this thread  : https://discussions.apple.com/thread/7589928

That service you see is the Photos/iCloud thing, it might be trying to upload/download your pictures to iCloud or maybe convert your JPEGs to HEIF. Maybe it pops because you're in the screensaver Preferences pane, and the service thinks it can then run (as I guess it does when the screensaver is running, because of the preview... that's a weird Apple bug if so).

In any case, try the pause thing suggested in that link, see if the service and choppiness disappears ?

**Comment by glouel** [comment]
Please let me know about your issue @dVIAN13 

In the meantime, last test build as I think everything is now in shape to make a PR. What's new : 
- Better messages for hardware detection (still should be improved, but the APIs aren't helping)
- Fixed cached videos generating online traffic 🎉
- Implemented "Never Stream Videos" mode
- Brought back check/uncheck all menu (in preparation for tvOS10/11 adding, not sure why I removed it in the first place...)
- Set default localized strings to english, you can still get localized strings through a checkbox

Build here : https://github.com/glouel/Aerial/releases/download/test1.41b3/Aerial.saver.zip

**Comment by esetnik** [comment]
@glouel love the hard work. The project is getting better by the day 👍

**Comment by dVIAN13** [comment]
@glouel installed latest test build and this is what I get... not working for me ;)

<img width="662" alt="screen shot 2018-10-02 at 10 12 56 am" src="https://user-images.githubusercontent.com/22992333/46364940-1223d900-c62c-11e8-9650-6a2449a5781a.png">
<img width="667" alt="screen shot 2018-10-02 at 10 13 03 am" src="https://user-images.githubusercontent.com/22992333/46364943-16e88d00-c62c-11e8-9c9c-9b35f909a008.png">
<img width="664" alt="screen shot 2018-10-02 at 10 13 40 am" src="https://user-images.githubusercontent.com/22992333/46364946-18b25080-c62c-11e8-9105-af88ab1b522c.png">

**Comment by glouel** [comment]
Oops looks like I messed up something, it doesn't load the json in your case. Just to give me a hint, is the tar/json in your Cache folder or not ?

**Comment by dVIAN13** [comment]
I believe so..

<img width="1095" alt="screen shot 2018-10-02 at 10 21 25 am" src="https://user-images.githubusercontent.com/22992333/46365291-0a186900-c62d-11e8-90a2-0ff0395214dc.png">

**Comment by glouel** [comment]
Ok thanks I'll have a look, sorry about that !

**Comment by glouel** [comment]
Just to be clear, closing and reopening System Preferences doesn't help ? Having a hard time reproducing right now.

**Comment by dVIAN13** [comment]
no, it does not. I even tried uninstalling(removing the file from my screen savers directory.) I had your last beta(1.41b2) running prior to updating.

**Comment by glouel** [comment]
Can you delete the tar file and see if it loads correctly ?

**Comment by dVIAN13** [comment]
I deleted all related files to aerial and it appears to have resolved the issue. ;) I may have inadvertently installed v1.2 over your old beta thinking it was the newest build.. and then installed your latest beta over that.. that probably explains it..

**Comment by glouel** [comment]
That's still a good cache. One change I made is that I don't redownload the JSON all the time, and use the previously saved manifest if the tar is there, but that's not a good check at all if the saved manifest is from another JSON. Thanks for the report !

**Comment by glouel** [comment]
Closing as fixed in release 1.4
