### ISSUE TITLE
Screen saver options dialog sheet won't close when clicking "Done"

### ISSUE THREAD

**Issue by lonedevel** [JohnCoates/Aerial#515]
I just upgraded to Mac OS X Mohave and was tweaking some settings including my screensaver and I noticed that I am unable to close the screen saver options sheet for Aerial by clicking on the "Done" button.   The sheet doesn't disappear.   I tried switching between the Main and Cache tab views and selecting various options but the button seems non-functional.   I also cannot close the System Preferences at this point and must force quit the System Preferences app.

A screenshot is attached.
![screenshot 2018-09-30 15 16 09](https://user-images.githubusercontent.com/16520350/46261596-c8b87a00-c4c3-11e8-847e-5efebbeb3a44.png)

**Comment by lonedevel** [comment]
Just saw another post with the same issue - sorry for the duplicate...

**Comment by glouel** [comment]
Closed as duplicate
