### ISSUE TITLE
Add tvOS12 Videos to Cache

### ISSUE THREAD

**Issue by WolverineSix** [JohnCoates/Aerial#517]
Any plans to add the new tvOS videos to the application (ISS and location information)?

**Comment by glouel** [comment]
Yes, check the latest beta : 
https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9

Extended location as the ISS flies is still work in progress, see here if interested : 
https://github.com/JohnCoates/Aerial/issues/512
