### ISSUE TITLE
Bring San Francisco back

### ISSUE THREAD

**Issue by Scuderia-Alex** [JohnCoates/Aerial#520]
Does anyone know the reason for removing San Francisco aerial screensaver in the latest build?
Any way to get it back?

**Comment by glouel** [comment]
Apple no longer uses them on tvOS, so they don't appear in the tvOS12 JSON we are loading from their servers to show the videos. We'll try to bring them back at some point, but they are only 1080p.

**Comment by fostermarke** [comment]
I second this request.
While the ISS videos are very pretty, I prefer the originals. Even if it is only playing the cached copied it would be great.

**Comment by glouel** [comment]
Please give a try to this build (you may need to close/reopen System Preferences after install) : 
https://github.com/glouel/Aerial/releases/download/1.4beta10/Aerial.saver.zip

**Comment by fostermarke** [comment]
Excellent. Thank you.


-- 
Mark Foster
fostermarke@gmail.com

**Comment by glouel** [comment]
Closing as fixed in release 1.4
