### ISSUE TITLE
At activation, build a randomized list of unique videos to cycle through before repeating

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#524]
Aerial 1.4b9

Yesterday, I saw the same Aerial video play twice in a row, out of 13 selected. More than once, I've seen the same video repeat after only one intervening video.

Would it be possible, when the screen saver activates, for Aerial to build a randomized list of selected videos for Aerial to cycle through, so that no video is repeated before all selected videos have been played?

Ideally, upon reactivation Aerial would rebuild the list with a newly randomized order.

**Comment by glouel** [comment]
Were you restricting to day/night ? If so how many videos in each bucket ?

**Comment by SeanMSmith** [comment]
This was seen with v1.4b9, which didn't offer the day/night restriction. I had all 13 space videos selected, and no others.

**Comment by glouel** [comment]
Ok thanks for the report !

**Comment by glouel** [comment]
So update on that one, twice in a row is a bug I added by fixing the caching playback and cutting extraneous network connexions 😅
 
One gaper though was always possible before. Generating a playlist is not as simple as it seems as we can have multiple monitors with different videos and with the day/night change, the playlist may become wrong. I'll see what I can do.

**Comment by glouel** [comment]
Marking as fixed in 1.4

**Comment by SeanMSmith** [comment]
So far, I haven't seen any repeats with version 1.4. Thank you!
