### ISSUE TITLE
Update the cask for version 1.4.2

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#527]
As of right now the cask still points to 1.2.

**Comment by travi** [comment]
i attempted to run the script suggested [in the cask docs](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask), but it failed. my guess is because the name of the zip file has changed. seems like someone from the team here would be better prepared than me to debug further.

**Comment by glouel** [comment]
Ok just updated the tag release, it now points to 
https://github.com/JohnCoates/Aerial/releases/download/v1.4/Aerial.saver.zip

Could you try running the script again ?

**Comment by glouel** [comment]
My bad I missed the .saver. Should be correct now : 

https://github.com/JohnCoates/Aerial/releases/download/v1.4/Aerial.zip

Thanks for your help in this and your patience :)

**Comment by travi** [comment]
looks like that did it: https://github.com/Homebrew/homebrew-cask/pull/53331

**Comment by glouel** [comment]
Awesome, thank you for this !

**Comment by travi** [comment]
it looks like it got merged, but when trying to upgrade, i get the following error:
```
==> Upgrading 1 outdated package:
aerial 1.2 -> 1.4
==> Satisfying dependencies
==> Downloading https://github.com/JohnCoates/Aerial/releases/download/v1.4/Aerial.saver.zip

curl: (22) The requested URL returned error: 404 Not Found
==> Purging files for version 1.4 of Cask aerial
Error: Download failed on Cask 'aerial' with message: Download failed: https://github.com/JohnCoates/Aerial/releases/download/v1.4/Aerial.saver.zip
```

(note the `.saver` in the name again)

the script does not reference `.saver` anywhere, so i wonder if the github release somehow introduced a redirect or something?

**Comment by glouel** [comment]
Damn ! I think it was merged twice as someone else had another PR, see here : https://github.com/Homebrew/homebrew-cask/pull/53234

But this one had the saver thing. Yours was also merged and is more recent, so one think it would override the other one...

**Comment by travi** [comment]
seems to work now, but i see you've now attached both

**Comment by travi** [comment]
either way, thanks everyone for getting this released. i've been looking forward to some of the new features 🎉

**Comment by glouel** [comment]
Well I added both a Aerial.saver.zip to the release alongside the other, so now it works :D

And if your merge gets priority it should still work !

Thanks again for taking care of this @travi !

**Comment by glouel** [comment]
@travi any chance you can run the script for "1.4.1" ? 

I have some permission error to push here, because of a messed up git config it seems.

**Comment by travi** [comment]
https://github.com/Homebrew/homebrew-cask/pull/53694

**Comment by glouel** [comment]
@travi Can I bother you again for 1.4.2 ?

**Comment by travi** [comment]
https://github.com/Homebrew/homebrew-cask/pull/54016

**Comment by glouel** [comment]
Many thanks !!

**Comment by travi** [comment]
looks like someone beat me to it: https://github.com/Homebrew/homebrew-cask/pull/54047

**Comment by glouel** [comment]
And already merged, well thank you very much for the first one !

**Comment by glouel** [comment]
@travi I really need to fix my setup but if I can bother you again for 1.4.4 ? Thanks !

**Comment by glouel** [comment]
No worries, many many thanks !
