### ISSUE TITLE
Incorrect "Your Mac does not support Night Shift" message

### ISSUE THREAD

**Issue by alex-mohemian** [JohnCoates/Aerial#528]
I get that message on a MacBook Pro (Retina, 13-inch, Late 2013) that has Night Shift enabled.

**Comment by glouel** [comment]
@alex-mohemian Can you go to terminal and type `/usr/bin/corebrightnessdiag nightshift-internal` and paste me the output ?

**Comment by alex-mohemian** [comment]
@glouel I'm on 10.14 (public release) and I did close and reopen system preferences.

The output of `corebrightnessdiag ` is:

```
Night Shift Status
{
    AutoBlueReductionEnabled = 1;
    BlueLightReductionAlgoOverride = 0;
    BlueLightReductionDisableScheduleAlertCounter = 3;
    BlueLightReductionSchedule =     {
        DayStartHour = 7;
        DayStartMinute = 0;
        NightStartHour = 22;
        NightStartMinute = 0;
    };
    BlueReductionEnabled = 0;
    BlueReductionMode = 1;
    BlueReductionSunScheduleAllowed = 1;
    Version = 1;
}
Night Shift Sunset/Sunrise
(null)
```

**Comment by alex-mohemian** [comment]
![screenshot 2018-10-12 at 11 41 48](https://user-images.githubusercontent.com/34009288/46861808-d818bb00-ce13-11e8-9ca8-f21734fd61ae.png)

**Comment by glouel** [comment]
@alex-mohemian Thanks for coming back to me on this, see your output, where it says : 

```
Night Shift Sunset/Sunrise
(null)
```

This is where I gather the Sunset and Sunrise time, this should not say null ! Here's what I get here 

```
Night Shift Sunset/Sunrise
{
    isDaylight = 1;
    nextSunrise = "2018-10-13 06:21:25 +0000";
    nextSunset = "2018-10-13 17:07:00 +0000";
    previousSunrise = "2018-10-11 06:18:18 +0000";
    previousSunset = "2018-10-11 17:11:06 +0000";
    sunrise = "2018-10-12 06:19:51 +0000";
    sunset = "2018-10-12 17:09:02 +0000";
}
```

So, in all likelihood, you may have nightshift enabled but the sunset/sunrise detection doesn't work. Can you check if you have set the timezone correctly on your mac ? Are you behind any strict firewall ? You may be blocking a service that macOS needs to determine sunset and sunrise time, although right now I'm not exactly sure which ones are necessary.

**Comment by alex-mohemian** [comment]
I manage the infrastructure here, so I can say with certainty that no services are blocked for me ;) 

Extremely weird, location services were disabled though. This must somehow happen during the Mojave upgrade because I noticed the same on my private MacBook. Very strange, because it managed to set location and timezone correctly.

After turning on location services, everything works as expected:

```
Night Shift Sunset/Sunrise
{
    isDaylight = 1;
    nextSunrise = "2018-10-14 05:34:54 +0000";
    nextSunset = "2018-10-13 16:24:48 +0000";
    previousSunrise = "2018-10-12 05:32:03 +0000";
    previousSunset = "2018-10-11 16:28:37 +0000";
    sunrise = "2018-10-13 05:33:28 +0000";
    sunset = "2018-10-12 16:26:42 +0000";
}
```

Thank you for your help with this! 👍

**Comment by glouel** [comment]
Ha, good to know, I can probably put a better error message on that specific case, thanks !
