### ISSUE TITLE
Add tooltip for "Localize for tvOS 12 videos"

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#533]
In the Main panel, you might consider adding a tooltip or suchlike for "Localize for tvOS 12 videos". One user already asked here on GitHub what that does, and I suspect many more may wonder.

**Comment by glouel** [comment]
I added tooltips to my 1.41 branch yesterday, for this one I added : "If enabled, descriptions will get translated to your macOS locale language if available"

Any suggestions for improvement ?

**Comment by SeanMSmith** [comment]
Perhaps, "Translates descriptions, if available, to your preferred language (as set in System Preferences : Language & Region)"?

**Comment by glouel** [comment]
Done ! Thanks !
