### ISSUE TITLE
Crashes with Mirroring

### ISSUE THREAD

**Issue by friedmud** [JohnCoates/Aerial#539]
Using the newest beta (1.4.1 beta 1) the screensaver still crashes for me if I try to mirror the videos to both of my monitors.  It works fine if I let it play different videos to each monitor.

I'm using 4k exclusively and have pre-cached all videos.

I'm running OSX 10.14 (Mojave) and my two external monitors are Dell U3818DW (37.5" 3840x1600) monitors.  This is on a Mac Pro with the AMD FirePro D500 graphics cards.

**Comment by friedmud** [comment]
While I've got you here... have you seen any way to set a screensaver a background in Mojave?  They seem to have removed the old way of doing that (probably because they added the new dynamic screensaver stuff).

I loved having Aerial as my desktop background!

**Comment by friedmud** [comment]
Also: thanks for continuing to work on this project!  I really appreciate it!

**Comment by glouel** [comment]
Did the Panel itself crash ? With a specific message ? Or was the UI of the panel "weird"/not working. 

If you try going into the screensaver preferences just after install, and the previous version was in memory, some of the resources won't be loaded and that might cause a crash. Seems to be a MacOS bug with swift screensavers, usually people see a wrong version number and other weird stuff. But it can definitely cause a crash when there's a change to the preferences.

Regarding desktop background, I think someone tried to do that with the old version of Aerial ? There's an issue about that but I haven't looked into it. See here, I'm not sure if it's still running : https://github.com/JohnCoates/Aerial/issues/13

**Comment by friedmud** [comment]
The panel crashed - sorry I didn't capture the message something about "Went wrong".  I think that what happened is what you described - that the old version of the screensaver was still running.

Yeah - I used to run Aerial as my background - but that command that's in #13 doesn't exist in OSX Mojave... just a bummer

**Comment by glouel** [comment]
Leaving this here for anyone else experiencing the problem : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.1beta2

I have no idea if there's a way to insert a window behind the desktop in Mojave. I'll keep this in mind for later but don't get your hopes too high ;)

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
