### ISSUE TITLE
Hitting spacebar only pauses the video, doesn't exit the screensaver

### ISSUE THREAD

**Issue by joshlewis** [JohnCoates/Aerial#54]
I'm on the latest El Capitan. My screensaver is password locked. When I hit the spacebar, assuming that it'll bring up the password box like it does on other screensavers, it instead pauses the video. 

Maybe that's a desirable thing for some reason I'm not seeing, but in that case, it would be better as a non-default option users who need it can turn on. 

The space bar, by default, should bring up the password prompt (or exit the screensaver) just as it does for almost all other screensavers.

**Comment by joshlewis** [comment]
Also worth mentioning since the issue is similar: the J, K and L keys manipulate the video too. L speeds it up, J rewinds it, and K pauses it, but doesn't unpause it. Maybe default Quicktime controls?

In any case, anyone whose password starts with any of these characters is going to get really confused.

**Comment by a9io** [comment]
:+1: this is really annoying

**Comment by JohnCoates** [comment]
This is fixed in the latest beta https://github.com/JohnCoates/Aerial/releases/

**Comment by a9io** [comment]
Thanks :D

**Comment by joshlewis** [comment]
Confirmed! Thank you so much, John. This is the best screensaver ever. Everyone who sees it is immediately like, "Whoa, where did you get that?!" I tell them, of course.

**Comment by JohnCoates** [comment]
That's awesome to hear @joshlewis!

**Comment by minhoryang** [comment]
AWESOME! +1
