### ISSUE TITLE
1.4b2 - black screen

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#540]
using 1.4b2, when I click 'preview' or let the screen saver kick in, I get a black screen(with descriptions & time though). tried uninstall/re-install and still persists.

**Comment by glouel** [comment]
@dVIAN13 Remind me, one monitor only ?

**Comment by glouel** [comment]
Oh damn. As a workaround, select mirror mode for multimonitor, I'll pull the build. Good catch and sorry about that one 😅

**Comment by dVIAN13** [comment]
haha.. no problem. just figured it out as you replied. good catch!

**Comment by dVIAN13** [comment]
@glouel also, when the 'mirror' option is chosen, the descriptions/time is only shown on main monitor.. maybe an option for which monitors to display on?

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/tag/v1.4.1beta3 😅

Yes for the mirroring, because of the way the mirroring mode works, that option would take some extra changes. Probably a "for later" improvement.

**Comment by dVIAN13** [comment]
thanks! confirmed working!

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
