### ISSUE TITLE
fast forward / rewind

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#541]
not sure if this is a 'feature' ;) but on the settings panel, you can 2-finger scroll over the video preview, and it will go forward/reverse! easter-egg/feature/bug?

**Comment by glouel** [comment]
Yeah I saw that one, also the player doesn't loop either and just stops at the end. It's just a basic video player.

I should do something about it someday.

**Comment by glouel** [comment]
No problem, I4ll keep it open to try and not forget it 😅

**Comment by dVIAN13** [comment]
nice! great work, thanks!

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
