### ISSUE TITLE
Slower description fades

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#542]
I love the support for quicker video fades in 1.4.1 beta 3, but I find that the quicker description fades that go with them are too demanding of my attention. When the description appears suddenly, my eyes are drawn to it against my will, even when I know it's coming and don't want to look at it.

When instead the description fades in gradually, I'm not distracted from focusing on the detail of the video, but I know the description is there, waiting discreetly to be read I want it.

I found the description fades in 1.4 to be ideal. I would love to able to keep that duration for description fades while selecting, say, 0.5s for the video fades.

**Comment by glouel** [comment]
What about having the same popup on the text panel for the text fade speed then ? To me having 0.5 on videos and 2s on text felt super weird so that's why I aligned their duration, but I can bring an option for that.

Side note, text fades start with a 1s delay compared to video animation, always.

**Comment by SeanMSmith** [comment]
Seems worth a try, if you don't think we're in danger of becoming too un-Mac-like by overloading the UI with choices. ;-)

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1

**Comment by SeanMSmith** [comment]
I love now being able to have two-second description fades with half-second video fades: the perfect combination for my taste. Thank you!
