### ISSUE TITLE
【Aerial 1.4】No San Francisco

### ISSUE THREAD

**Issue by LePetitPrince612** [JohnCoates/Aerial#543]
I love to use Aerial and I'm very pleased to know that Aerial contains every Aerial video, including thee old San Francisco videos. Yet after downloading, I can't find them. And I really want to know why and how to solve it.

**Comment by glouel** [comment]
Can you try the latest beta ? See here : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.1beta3/Aerial.saver.zip

As for "finding them", unsure what's the issue. Get that beta, then scroll down in the list, you'll find SF just before the "Space" videos : 

![capture d ecran 2018-10-16 a 09 05 03](https://user-images.githubusercontent.com/37544189/46998386-add04180-d122-11e8-8273-1a482925c5af.png)

**Comment by NightRaider73** [comment]
@glouel Close fixed in 1.4.1

**Comment by glouel** [comment]
@LePetitPrince612 come back to us and reopen this is you still have issues
