### ISSUE TITLE
Minor typo under Text options

### ISSUE THREAD

**Issue by bryandmlee** [JohnCoates/Aerial#546]
In v1.4.1, under the Text section of the Screen Saver Options, "Extra information:", 'diagonally' is spelt with an extra 'n'.
<img width="263" alt="screenshot 2018-10-17 at 13 22 31" src="https://user-images.githubusercontent.com/15274194/47063876-b5214900-d20f-11e8-959e-8adfe31ae743.png">

**Comment by glouel** [comment]
Oops ! Thanks, will be fixed in next builds :)
