### ISSUE TITLE
Corrections to video names and descriptions (with suggested improvements)

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#547]
I'm going to submit the following corrections and suggested improvements to video names and descriptions in batches, since compiling these takes quite a lot of time.

First up: **_San Francisco Day_**

**Movie:** b8-3.mov
**Name:** Change "Downtown" to "Alamo Square"
**Descriptions:**
_Start:_ Change "San Francisco" to "Painted Ladies across from Alamo Square in San Francisco"
_~35s:_ "St Mary’s Cathedral in the left mid-ground, with downtown SF in the background"
_~70s:_ "The dome of City Hall appearing in the right mid-ground"
_~210s:_ "The dome of City Hall clear in the right mid-ground"

**Movie:** b3-3.mov
**Name:** Change "Embarcadero/Market Street" to "Embarcadero, Market Street" (You're right, there's not enough room for " and ")
**Descriptions:**
_Start_: Change "Over San Francisco Bay moving toward the Embarcadero" to "Heading southwest over San Francisco Bay to the San Francisco Ferry Building"
_~110s:_ Add "Approaching the Port of San Francisco Ferry Building and the Embarcadero"
_160s:_ Change "Following Market Street through San Francisco" to "Heading southwest along Market Street in downtown San Francisco"

**Movie:** b4-3.mov
**Name:** Change "Golden Gate from SF" to "Presidio to Golden Gate"
**Descriptions:** Replace all descriptions with Apple's two descriptions for A013_C005:
_Start:_ "Moving along the Presidio of San Francisco toward the Golden Gate Bridge"
_190s:_ "Crossing the Golden Gate Bridge toward the Marin Headlands"

**Movie:** b10-3.mov
**Name:** Change "Presidio to Golden Gate" to "Marin to Golden Gate"
**Descriptions:** Lost in the fog, these descriptions are going the wrong way!
_Start:_ Change "Moving along the Presidio of San Francisco toward the Golden Gate Bridge" to "Moving over the Marin Headlands along Highway 101 toward the Golden Gate Bridge"
_~20s:_ Add "Horseshoe Cove appearing on the left"
_~130s:_ Add "Passing over Battery Spencer"
_~192s:_ Change "Crossing the Golden Gate Bridge toward the Marin Headlands" to "Crossing the Golden Gate Bridge toward San Francisco"

**Comment by SeanMSmith** [comment]
Second batch: **San Francisco Night**

**Movie:** b6-4.mov
**Name:** Change "Downtown/Coit Tower" to "Downtown and Coit Tower"
**Descriptions:**
_Start:_ Change "Downtown San Francisco" to "Downtown San Francisco with the Transamerica Pyramid in the center"

**Movie:** b2-4.mov
**Name:** Change "Downtown/Sutro Tower" to "Downtown and Sutro Tower"
**Descriptions:**
_50s:_ Add "Former Bank of America headquarters blotting out the sun" (Those familiar with Bank of America's role in the recent US housing crisis will appreciate the aptness of this description.)

**Movie:** b5-3.mov
**Name:** Change "Embarcadero/Market Street" to "The Embarcadero and Market Street"
**Descriptions:**
_~150s_: Add "Approaching the Port of San Francisco Ferry Building"

Movie: b7-3.mov
Name: Change "Fisherman's Wharf" to "Fisherman’s Wharf" (i.e. use proper apostrophe)
Descriptions:
_~30s:_ Add "Passing the Liberty ship SS Jeremiah O’Brien"
_~50s:_ Add "Passing over the submarine USS Pampanito"
_~80s:_ Change "Approaching Coit Tower with downtown San Francisco and the Bay Bridge in the background" to "Passing over North Beach"
_~120s:_ Add "Approaching Coit Tower on Telegraph Hill, with the Bay Bridge and downtown SF in the background"
_~150s:_ Change "Passing Coit Tower toward downtown San Francisco and the Bay Bridge" to "Passing Coit Tower on Telegraph Hill, with Sts Peter and Paul Church in the right mid-ground" (Sts Peter and Paul is the most architecturally prominent feature in this part of North Beach.)

**Comment by SeanMSmith** [comment]
Third batch: **_Los Angeles Day_**

**Movie:** comp_LA_A005_C009_PSNK_ALT_v08_SDR_PS_FINAL_20180709_SDR_4K_HEVC.mov
**Name:** Change "Interstate 110" to "Harbor Freeway (Interstate 110)"
**Description:** Change "Following Interstate 110 north through Los Angeles" to "Following the Harbor Freeway (Interstate 110) north through South Los Angeles"
_~50s:_ Add "Crossing the Century Freeway (Interstate 105)"
_~65s:_ Add "Passing over the Harbor Freeway Station on the Metro Green Line, which runs along the Century Freeway"
_~170s:_ Add "Crossing Imperial Highway"

**Movie:** LA_A006_C008_4K_SDR_HEVC.mov
**Name:** Change "LAX" to "Los Angeles Int’l Airport" (or spell out "International" if you have room; "LAX" is also used for LA's Union Station, miles from the airport)
Descriptions:
_~80s:_ Add "Passing over the Theme Building"
_~210s:_ Add "Passing over the Tom Bradley International Terminal"

**Comment by SeanMSmith** [comment]
Fourth batch: **_Los Angeles Night_**

**Movie:** LA_A011_C003_4K_SDR_HEVC.mov
**Name:** Downtown
**Descriptions:**
_Start:_ Change "Passing Downtown Los Angeles" to "Approaching Downtown Los Angeles, with the MTA Building (in yellow) and Union Station (in pink) in the left mid-ground"
_~60s:_ Add "Passing the Cathedral of Our Lady of the Angels (in the center)"
_~80s:_ Add "Passing the Los Angeles County Music Center (in the center)"
_~95s:_ Add "Crossing the Hollywood Freeway, traveling south through Downtown along the Harbor Freeway"
_~140s:_ Add "Passing Disney Hall (in the center)"
_~155s:_ Add "Passing City Hall (in pale green, in the left mid-ground)"
_~215s:_ Add "Passing the Library Tower (in the center)"
_~235s:_ Add "Passing the Bonaventure Hotel (in the center)"
_~265s:_ Add "The Los Angeles Central Library, brightly lit, appears from behind the Bonaventure Hotel"
_~310s:_ Add "Passing the Wilshire Grand Center (under construction)"
_~400s:_ Add "Passing L.A. Live"
_~435s:_ Add "Passing the Ritz-Carlton Hotel and Staples Center"
_~465s:_ Add "Passing the Los Angeles Convention Center"
_~520s:_ Add "Approaching the Santa Monica Freeway"

**Movie:** comp_LA_A006_C004_v01_SDR_FINAL_PS_20180730_SDR_4K_HEVC.mov
**Name:** Suggestion: Change "Hollywood Sign" to "Hollywood Hills" (I'm still trying to wrap my brain around a description - which is a kind of sign - for a sign. Why not just describe the "Hollywood Hills" and let the famous sign speak for itself?)
**Descriptions:**
_Start:_ Change "The Hollywood Sign in Los Angeles" to "Traveling north along Beachwood Drive through the Hollywood Hills in Los Angeles"
_~60s:_ Add "Continuing north through Beachwood Canyon"
_~252s:_ Change "Over the Hollywood Hills, approaching Burbank, California" to "Passing the Mount Lee Communications Center, heading toward Burbank, California

**Comment by SeanMSmith** [comment]
I'll try to get to London later today or tomorrow.

**Comment by glouel** [comment]
Wow thanks ! I'll have a look at these. 

The names will be an easy change (I may need to make the list larger again though).

The descriptions, those were 100% provided by apple and are translated. So might be a bit tricky to handle adding new points (replacing easy enough) for just one language but should be doable. I'll have a look in a coffee or two, thanks !

**Comment by glouel** [comment]
Side note, I can extract all the POIs if you want to see them in english for all videos ?

**Comment by SeanMSmith** [comment]
That would be most helpful!

**Comment by glouel** [comment]
There you go, hopefully readable enough (macOS 10.14.1 beta 4 just broke Sublime Text and somehow rehid file extensions here !)

[AerialPois.txt](https://github.com/JohnCoates/Aerial/files/2491123/AerialPois.txt)

**Comment by glouel** [comment]
Ok right now I'm starting to merge your new names. However about this : 

> **Movie:** b4-3.mov
> **Name:** Golden Gate from SF
> **Descriptions:** Three descriptions appear far too early.

> **Movie:** b10-3.mov
> **Name:** Change "Presidio to Golden Gate" to "Marin Headlands to Golden Gate"
> **Descriptions:** Lost in the fog, these descriptions are going the wrong way!

One problem I have is that I may not have the right video ID for these, so these may be totally wrong descriptions. There are 4 Golden Gate videos and 4 matching sets of descriptions  (the _0, _150 is the time stamp, so show at 0, show at 150...): 

A008_C007_0	: Over the Marin Headlands looking toward the Golden Gate Bridge
A008_C007_150 : Crossing the Golden Gate Bridge toward the Presidio of San Francisco

A013_C005_0 : Moving along the Presidio of San Francisco toward the Golden Gate Bridge
A013_C005_190 : Crossing the Golden Gate Bridge toward the Marin Headlands

A006_C003_0 : San Francisco Bay and the Golden Gate Bridge
A006_C003_90 : Heading over the north tower of the Golden Gate Bridge toward San Francisco

A013_C012_0 : Approaching the Golden Gate Bridge from San Francisco
A013_C012_60 : Alongside the Golden Gate Bridge heading toward the Marin Headlands
A013_C012_140 : Crossing over the Golden Gate Bridge
A013_C012_230 : Passing by the North Tower of the Golden Gate Bridge
A013_C012_240 : Over San Francisco Bay traveling alongside the Golden Gate Bridge

I matched : 
        "b8-2":"A008_C007_",                                                // San Francisco day 1
        "b10-3":"A013_C005_",                                               // San Francisco day 2
        "b9-3":"A006_C003_",                                                // San Francisco day 3
        "b4-3":"A013_C012_",                                                // San Francisco day 6
 
Maybe I got the order wrong ? Or one of these is for a yet unreleased video. SF is the only one I had a lot of issues with, I think I ended up matching A013_C012 with SF day 6 mostly because it fit on video length. There's also another Embarcadero/market street that's unlinked to any video we have : 

A013_C004_0 : Over the San Francisco Bay moving toward the Embarcadero
A013_C004_90 : Over the Embarcadero looking down Market Street in San Francisco
A013_C004_150 : Following Market Street through downtown San Francisco
A013_C004_360 : Following Market Street through San Francisco

I marked this one as an alternate of SF day 5.

(and to be clear, I tried to find those videos but I haven't found them on Apple's server. My guess is they will come back at some point since they took the time to label them, yet those aren't in the JSONs. But they are very likely to come back as 4K !)

**Comment by glouel** [comment]
Misc stuff about names mostly (I'll come back to descriptions as a second pass) : 

> _50s:_ Add "Former Bank of America headquarters blotting out the sun" (Those familiar with Bank of America's role in the recent US housing crisis will appreciate the aptness of this description.)

😅

> **Name:** Change "LAX" to "Los Angeles Int’l Airport" (or spell out "International" if you have room; "LAX" is also used for LA's Union Station, miles from the airport)

Well, regarding length I'm adding the long versions right now and will make a build. Part of the reason I went with / sometimes was so they would fit in the UI. We'll have to see how we handle the longer ones, I had already made the font smaller and the list larger, but some widgets (donwload/4K) take space too. 

> **Name:** Suggestion: Change "Hollywood Sign" to "Hollywood Hills" (I'm still trying to wrap my brain around a description - which is a kind of sign - for a sign. Why not just describe the "Hollywood Hills" and let the famous sign speak for itself?)

I like Hollywood Hills !

Again, many thanks for this, I'll put up a build with your new names later today so you can see the impact in the UI.

**Comment by NightRaider73** [comment]
Also under Downtown it just shows "San Fransisco" I don't know why but it is the only one.
I am almost certain that it was fine in 1.4.1 so maybe check that. (I am running 1.4.2test3)

**Comment by glouel** [comment]
> Also under Downtown it just shows "San Fransisco" I don't know why but it is the only one.
> I am almost certain that it was fine in 1.4.1 so maybe check that. (I am running 1.4.2test3)

Nope, it was that way too before. That video is the only one (I think out of 66) for which I didn't find "extra descriptions" in the strings file, so those are empty and it just shows the video. Maybe I missed them in the strings bundle, it's a bit of a mess !

**Comment by glouel** [comment]
I'm putting my last test build here : 
https://github.com/glouel/Aerial/releases/download/v1.4.2test4/Aerial.saver.zip

It only includes the name changes, not the descriptions. Some are cut because too long.

**Comment by NightRaider73** [comment]
I appreciate the work you put into this and so I try to help in anyway I can. (I'm no coder though)
:)

**Comment by glouel** [comment]
Everything helps ! Testing is also super helpful considering the vast variety of configurations out there. Slowly but surely it's getting there !

**Comment by dVIAN13** [comment]
@glouel Would it be a hard ask to have the cut-off names in the list display a hovering tool-tip? That way, depending on the sys pref settings for sidebar text (which are still too long for me at small), I would think that a hovering tool-tip could help complete the rest of the name.

**Comment by NightRaider73** [comment]
@glouel I can go through later and correct all of your spelling if you want me to :)

**Comment by glouel** [comment]
> @glouel Would it be a hard ask to have the cut-off names in the list display a hovering tool-tip? That way, depending on the sys pref settings for sidebar text (which are still too long for me at small), I would think that a hovering tool-tip could help complete the rest of the name.

Yeah I left them cut off so @SeanMSmith could see what we can work with. Tooltips should very much be doable if we stay with longer lines !



> @glouel I can go through later and correct all of your spelling if you want me to :)

If you see stuff either in the UI or in the readme, sure ! I think the UI should be mostly fine (maybe not the newer stuff like Text panel, etc).

The extra descriptions are Apple's though so don't spend time double checking those !

**Comment by glouel** [comment]
@dVIAN13 
https://github.com/glouel/Aerial/releases/download/v1.4.2test5/Aerial.saver.zip

with tooltips... that blink ?! That's what I got enabling tooltips. I guess they do that to not obscure the rest of the UI. That feels so unApple to me but hey...

**Comment by dVIAN13** [comment]
haha... it's better than nothing! works for me.. I like your other tooltips, but I sure that's more work!

**Comment by NightRaider73** [comment]
> If you see stuff either in the UI or in the readme, sure ! I think the UI should be mostly fine (maybe not the newer stuff like Text panel, etc).
I don't code so where would I find the UI files?

**Comment by SeanMSmith** [comment]
Sixth batch: **_London Night_**

**Movie:** b1-2.mov
**Name:** Change "Tower Bridge 1" to "River Thames near Sunset"
**Descriptions:**
_20s:_ Remove "Crossing the River Thames in London"
_25s:_ Add "Crossing the River Thames and passing over City Hall"
_35s:_ Add "Passing HMS _Belfast_ in the River Thames"
_200s:_ Change "Crossing the River Thames toward Westminster, London" to "Passing Lambeth Palace on the left and Waterloo Station on the right"
_225s:_ Add "Crossing the River Thames toward the Palace of Westminster (Houses of Parliament)"

**Movie:** b3-1.mov
**Name:** Change "Tower Bridge 2" to "River Thames at Dusk"
**Descriptions:**
(I may have gone overboard with describing all the bridges, and it may be that a more sparing set of descriptions that omits all the bridges but Tower Bridge, while retaining HMS Belfast, the buildings, and the Eye, would be more soothing.)  ;-)
_20s:_ Remove "Following the River Thames in London"
_28s:_ Add "Traveling west up the River Thames, past City Hall on the left"
_40s:_ Add "Passing HMS _Belfast_ in the River Thames, with The Shard on the left and the Walkie-Talkie on the right"
_80s:_ Add "Passing London Bridge, with Southwark Cathedral on the left"
_100s:_ Add "Passing the Cannon Street Railway Bridge"
_110s:_ Add "Passing Southwark Bridge, with St Paul’s Cathedral on the right"
_130s:_ Remove "Following the River Thames toward the London Eye"
_135s:_ Add "Following the River Thames past the Millennium Bridge"
_160s:_ Add "Passing Blackfriars Bridge"
_240s:_ Add "Following the River Thames past Waterloo Bridge"
_275s:_ Add "Passing the Hungerford and Golden Jubilee Bridges, with Whitehall on the right"
_310s:_ Change "Approaching the London Eye on the River Thames" to "Passing the London Eye on the River Thames" (Alternatively, retain "Approaching" and move to 295s, which would allow more time before the suggested description at 320s.)
_320s:_ Add "Approaching Westminster Bridge, with Big Ben, the Houses of Parliament, and Westminster Abbey on the right"
_325s:_ Remove "Passing The Houses of Parliament on the River Thames in London"

**Comment by SeanMSmith** [comment]
**_New York Night_**

**Movie:** b2-3.mov
**Name:** Change "7th avenue" to "Seventh Avenue" (or at least "7th Avenue", capitalizing the "A")
**Descriptions:**
Someone who knows New York better than I do might want to take a whack at these. :-)

**Comment by glouel** [comment]
> I didn't realize that the extended descriptions in the older videos were also written by Apple. Frankly, I think they're rather poor, so in case you should decide to undertake the work of improving them, I'll continue to suggest corrections and improvements. :-)

I think I definitely can use yours (more points, better etc), but for english only. Since you are adding timepoints I'll need to scrape theirs (you seem to have put add/change/remove so that should be an easy enough mix). 

I'm pretty sure their strings are copyrighted so to my mind, replacing is fine, keeping some of their olds and your news together, probably slightly iffy ? In order to try and not anger anyone (that project walks a fine line legally), I would suggest adding a checkbox for "supplementary/alternate english descriptions" (something that sounds better and convey those are not Apple's, a help box next to it with some disclaimer text may be needed) that would enable yours for the videos for which you have provided them. Does that sound alright to you ? 

I would highly suggest trying to keep a 10 to 15s minimum between POIs so they are not too jarring and unreadable (I think you pretty much stick to that, there's a 1s delay on your insertion point [I can probably reduce it a bit], and the fades both ways, that can cut half the time although still readable during some of the fade).

**Comment by SeanMSmith** [comment]
Yes, the alternate descriptions checkbox sounds reasonable. "Alternate English Descriptions" and "Enhanced English Descriptions" both suggest themselves to me.

My suggested descriptions above assumed keeping many of Apple's existing descriptions (anywhere I didn't explicitly suggest changing or removing them, in fact). To avoid copyright issues, I'll go through those descriptions and rewrite them.

I'll _try_ to get to that later today (Friday here in California), after I get some sleep. I'm going out of town on Saturday and will be out of touch until Thursday, if not later.

**Comment by glouel** [comment]
That's super nice of you thanks ! Take your time, no hurry 😀

**Comment by NightRaider73** [comment]
@glouel Looking good with the additions:)

**Comment by SeanMSmith** [comment]
Looking at the new **names** I proposed (not descriptions) in 1.4.1test7, I'm noticing that several are too long.  I would suggest:

**_Los Angeles_**

Change "Harbor Freeway (Interstate 110)" to "Harbor Freeway"
Change "Los Angeles International Airport" to "Los Angeles Int’l Airport"

**_San Francisco_**

Change "Marin Headlands to Golden Gate" to "Marin to Golden Gate"
Change "The Embarcadero and Market Street" to "Embarcadero, Market Street" (both day & night)

**Comment by SeanMSmith** [comment]
Regarding the two Golden Gate Bridge videos with the whacked-out descriptions:

A013_C005 should instead go with b4-3.mov, and the name should be "Presidio to Golden Gate"; Apple's two descriptions there are good.

The video b10-3.mov (which I call "Marin to Golden Gate") does not seem to have any corresponding descriptions at all in the POIs you sent me, so we should just use mine above.

(The group of descriptions labelled "San Francisco Golden Gate from SF" in the POIs doesn't seem to correspond to any video we have.)

**Comment by glouel** [comment]
> Regarding the two Golden Gate Bridge videos with the whacked-out descriptions:
> 
> A013_C005 should instead go with b4-3.mov, and the name should be "Presidio to Golden Gate"; Apple's two descriptions there are good.

Makes sense indeed !

> The video b10-3.mov (which I call "Marin to Golden Gate") does not seem to have any corresponding descriptions at all in the POIs you sent me, so we should just use mine above.
> 
> (The group of descriptions labelled "San Francisco Golden Gate from SF" in the POIs doesn't seem to correspond to any video we have.)

I guess it's for a new video they shot and we don't have yet ? We'll see I guess !

> Okay, I think that I've now rewritten all of Apple's original descriptions for those videos for which I've suggested improvements above, so that none of their copyrighted text is mixed in with my suggested descriptions

Truly awesome, thanks a lot for this !

> I've also taken the opportunity to make a few small improvements to my descriptions here and there.
> 
> I've edited the posts above to reflect all my changes. (I hope that doesn't complicate things for you, but GitHub can show the edit history, yes?)

No issue at all. 

> I'm off to San Francisco tomorrow (in about 12 hours, actually), after which I'll be out of touch most likely until Thursday.
> 
> In the meantime, thank you for all your fine work on Aerial!

Enjoy your time there ! And thanks for doing this, I should have this working when you get back

**Comment by glouel** [comment]
I'm merging your stuff but you kept some stuff like change this and that and other annotations that I'm not sure what I should do with for a couple of videos.

I don't change/add/remove, I only put your stuff in a new file and those will be used in place of Apple's description. I also need a 0 always. 

> First up: **_San Francisco Day_**
> **Movie:** b4-3.mov
> **Name:** Golden Gate from SF
> **Descriptions:** Three descriptions appear too early and should simply be removed:
> _60s:_ The description "Alongside the Golden Gate Bridge heading toward the Marin Headlands" appears two minutes too early. It also appears to be superfluous, as there's another "alongside" description, correctly timed, at 240s.
> _140s:_ The description "Crossing over the Golden Gate Bridge" likewise appears too early, as we haven't reached the bridge yet.
> _230s:_ The description "Passing by the North Tower of the Golden Gate Bridge" is far more premature, as we never do pass the north tower in this video. In fact, we have not even reached the _south_ tower yet.

I don't have a 0 and don't know what to do with that :)

> **Movie:** b10-3.mov
> **Name:** Change "Presidio to Golden Gate" to "Marin to Golden Gate"
> **Descriptions:** Lost in the fog, these descriptions are going the wrong way!
> _Start:_ Change "Moving along the Presidio of San Francisco toward the Golden Gate Bridge" to "Moving over the Marin Headlands along Highway 101 toward the Golden Gate Bridge"
> _~20s:_ Add "Horseshoe Cove appearing on the left"
> _~130s:_ Add "Passing over Battery Spencer"
> _~192s:_ Change "Crossing the Golden Gate Bridge toward the Marin Headlands" to "Crossing the Golden Gate Bridge toward San Francisco"

I'll add those 4 as is.

**Comment by glouel** [comment]
Haha no problem thanks ! 

I'll add those to the json for next version. It looks pretty good with your new strings you'll see ;)

**Comment by SeanMSmith** [comment]
I'm off to SF now and will have to wait until I get back to check out the new Aerial--by which time, at the rate you're going, there'll be so many improvements I'll barely recognize it!  :D

**Comment by glouel** [comment]
Haha :) Enjoy your trip !

**Comment by SeanMSmith** [comment]
I would much rather look at a flyby of the Eiffel Tower, or just about anything else, than a close-up flyover of a Los Angeles freeway!

Guillaume, I would still suggest changing the name "Harbor Freeway (Interstate 110)" to "Harbor Freeway". (The former is too long, "Harbor Freeway" is more descriptive than only "Interstate 110", and it's identified as "Interstate 110" in both Apple's descriptions and our community descriptions.)

**Comment by SeanMSmith** [comment]
Would it be possible to italicize the names of the ships in the community descriptions for Fisherman's Wharf and the three River Thames videos? That is the usual style in English.

So HMS _Belfast_, SS _Jeremiah O’Brien_, and USS _Pampanito_. (Note that the "HMS", "SS", and "USS" are _not_ italicized.)

**Comment by glouel** [comment]
> Guillaume, I would still suggest changing the name "Harbor Freeway (Interstate 110)" to "Harbor Freeway". The former is too long, "Harbor Freeway" is more descriptive than only "Interstate 110", and viewers will learn that it's also called "Interstate 110" from either Apple's descriptions or our community descriptions.

Ok !

> I would also suggest changing the name "Marin to Golden Gate" to "Marin Headlands in Fog", which would be more descriptive and would contrast nicely with the "Marin Headlands" video, which follows a similar route.

Ok. Are you familiar with JSON by any chance ? I've put all your text in this file that you can edit if you want. I'll modify those but if you are confortable enough to do it, you can then modify it yourself easily. Let me know if you want help figuring how to.

https://github.com/glouel/Aerial/blob/feature/v1.4.2/Aerial/Resources/Community/en.json

> Would it be possible to italicize the names of the ships in the community descriptions for Fisherman's Wharf and the three River Thames videos? That is the usual style in English.
> 
> So HMS _Belfast_, SS _Jeremiah O’Brien_, and USS _Pampanito_. (Note that the "HMS", "SS", and "USS" are _not_ italicized.)

Definitely possible, but will need a bit of extra work. I'll think about it and get back to you.

**Comment by SeanMSmith** [comment]
Looks straightforward enough, but how do I actually edit the file? Do I need to fork it first?

**Comment by glouel** [comment]
Yep ! Go to this page : https://github.com/JohnCoates/Aerial/

Press fork (top right) to create your own fork (copy) of the repository. Then inside that repository (should probably be something like https://github.com/SeanMSmith/Aerial/) browse to Aerial/Resources/Community/en.json

Then you can edit the file. When your changes are done, it will probably suggest you to make a pull request in yellow. If not, there's a button for that (New pull request), it should autofill source (your fork) and destination (JohnCoates/Aerial). Submit the thing and it will appear here so I can merge the changes.

Let me know if you want any more help with that ! Hopefully we can extend the method for other languages too.

**Comment by SeanMSmith** [comment]
With "Use community information when available" unchecked, the two San Francisco videos with confused descriptions are still confused.

"Presidio to Golden Gate" is still using the wrong set of Apple descriptions, and "Marin to Golden Gate" (or "Marin Headlands in Fog") is still using northbound descriptions for a southbound video.

(When using community information, both videos now have correct descriptions.)

See https://github.com/JohnCoates/Aerial/issues/547#issuecomment-431557719.

**Comment by glouel** [comment]
Oops probably forgot those sorry, I have to edit those in code so will take care of that tomorrow.

**Comment by SeanMSmith** [comment]
Thanks for the tip; this should should be much efficient!

**Comment by glouel** [comment]
Awesome ! So as you've probably seen, it makes a pull request here : https://github.com/JohnCoates/Aerial/pull/591

I just merge it, so now your changes appear directly here : https://github.com/JohnCoates/Aerial/blob/master/Aerial/Resources/Community/en.json 

They will be picked up automatically in next release this way, makes it easier for me too :) Thanks !

**Comment by glouel** [comment]
beta 3 has your changes : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta3/Aerial.saver.zip

**Comment by SeanMSmith** [comment]
Could you change the name of the space video "Southern California to Baja" to "Northern California to Baja" (or let me know its ID so I can add it to the Community JSON)?

This video actually starts north of the California border (out to sea, west of the Oregon coast), and its current name is just plain wrong. (You'd think the folks at Apple would know better.)

**Comment by glouel** [comment]
Done :) 

https://github.com/JohnCoates/Aerial/pull/594

**Comment by glouel** [comment]
in the future, if you're looking for video ids, you can have a look here : 

https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Models/AerialVideo.swift
(look for TimeInformation at the beginning)

and here : https://github.com/JohnCoates/Aerial/blob/master/Aerial/Source/Models/ManifestLoader.swift

(mergePOI)

**Comment by SeanMSmith** [comment]
As of 1.4.5 beta 4, when **not** using community information, those two confused Golden Gate Bridge videos still have incorrect descriptions. (See https://github.com/JohnCoates/Aerial/issues/547#issuecomment-433568837 and https://github.com/JohnCoates/Aerial/issues/547#issuecomment-431557719.)

To recap:

The Apple descriptions currently attached to b4-3.mov (Presidio to Golden Gate) are not the right ones; in fact, they do not correspond to any video we have.

The correct descriptions for b4-3.mov got mistakenly attached to b10-3.mov (Marin Headlands in Fog), so the Apple descriptions currently attached to b10-3.mov should instead be attached to b4-3.mov.

The video b10-3.mov (Marin Headlands in Fog) does not have any Apple-authored descriptions in the AerialPois.txt file you sent me. When "Use community information…" is unchecked, we should either use the community descriptions for this one video regardless, or omit descriptions in this video entirely.

**Comment by glouel** [comment]
Bah, sorry about that one, fixed in next. 

Proof that I really did it this time 😱

https://github.com/glouel/Aerial/commit/c8187e004a718979ddbfa76ff5808452e3ac17d3

**Comment by aitor** [comment]
@SeanMSmith A quick ping to let you know that we've setup a translation process based on [lokalise.co](lokalise.co) and that it's now super easy to contribute to the project by directly translating the video descriptions to any language.

@glouel We can close this ticket right?

**Comment by glouel** [comment]
Indeed thanks ! @SeanMSmith feel free to ping me/aitor so we can add you to the group, this should make it much simpler next time a new video comes around !

**Comment by SeanMSmith** [comment]
@glouel @aitor Ping!

**Comment by aitor** [comment]
@SeanMSmith Send me your email (hello AT aitor DOT is or by DM in Twitter @_aitor)
