### ISSUE TITLE
Aerial doesn't work

### ISSUE THREAD

**Issue by polywebb** [JohnCoates/Aerial#55]
I have 2011 MacBook Pro with 27 inch Apple monitor attached via lighting cable
Installed Aerial and it installs but doesn't load any pictures/videos

Running OS X 10.11.1

I have a 2008 Mac Pro at home using dual generic monitors and Aerial runs like a champ
Can't figure out why it won't run on this setup 
This is what it looks like in screensaver settings

![screen shot 2015-10-28 at 2 04 44 pm](https://cloud.githubusercontent.com/assets/15367905/10799827/e459c084-7d7c-11e5-9a7d-45c25bba5545.png)

**Comment by austinfox** [comment]
I can confirm that I am also experiencing this issue. (Running OS X 10.10.5)

**Comment by periodicdesign** [comment]
Same issue as @austinfox and @polywebb running OS X 10.10.5 as well.

**Comment by alistairmcmillan** [comment]
@periodicdesign @austinfox Which hardware are you running the screensaver on? Are you running it behind a firewall or proxy, for example LittleSnitch?

**Comment by polywebb** [comment]
I believe it has to do with network and firewall. Last night the machine 
that was working lost internet connection and I got the same screen Soon 
as internet came back on it started working again'

So it must be our corporate network preventing it from working on this 
machine

> Jason Wishard <mailto:notifications@github.com>
> November 3, 2015 at 10:17 AM
>
> Same issue as @austinfox <https://github.com/austinfox> and @polywebb 
> <https://github.com/polywebb> running OS X 10.10.5 as well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153402440>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by periodicdesign** [comment]
Just got it to work. I copied the entire master folder in ~/Library/Screen Savers/ then double-clicked the Aerial.saver file. BOOM!

**Comment by polywebb** [comment]
Tried that and it still doesn't work for me
Tried copying the folder didn't work
Opened master folder and copied contents, still doesn't work


> Jason Wishard <mailto:notifications@github.com>
> November 3, 2015 at 12:03 PM
>
> Just got it to work. I copied the entire master folder in 
> ~/Library/Screen Savers/ then double-clicked the Aerial.saver file. BOOM!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153437329>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by polywebb** [comment]
deleted all aerial files as I had downloaded numerous times.
Downloaded latest beta and installed and it still doesn't work

Is there a way to download the files from apple so as to circumvent our 
corporate network blocking connection?


> Jason Wishard <mailto:notifications@github.com>
> November 3, 2015 at 12:03 PM
>
> Just got it to work. I copied the entire master folder in 
> ~/Library/Screen Savers/ then double-clicked the Aerial.saver file. BOOM!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153437329>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by alistairmcmillan** [comment]
This file lists the movie files.

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

If you download them and drop them in a folder called /Users/YOURUSERNAME/Library/Caches/Aerial the screensaver should pick them up from there.

Alternatively if the screensaver is working on one machine like your Mac Pro (and it is a current version that includes the caching feature), that folder should already be populated with the movie files, so you could copy them from the working machine to the non-working one.

**Comment by polywebb** [comment]
The machine that works is a 2008 Mac Pro and on my home network straight 
to internet
The machine that doesn't work is a 2011 Mac Book Pro on our company 
network that is probably causing the issues

I cannot find the folder you referenced n the working machine and I did 
upgrade that to the latest beta

> Alistair McMillan <mailto:notifications@github.com>
> November 3, 2015 at 10:21 AM
>
> @periodicdesign <https://github.com/periodicdesign> @austinfox 
> <https://github.com/austinfox> Which hardware are you running the 
> screensaver on? Are you running it behind a firewall or proxy, for 
> example LittleSnitch?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153403700>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by polywebb** [comment]
Hooked up work machine to a direct internet line and now it works. 
Hopefully it will cache the files so I can get back on company network 
and still have it working

> Alistair McMillan <mailto:notifications@github.com>
> November 3, 2015 at 10:21 AM
>
> @periodicdesign <https://github.com/periodicdesign> @austinfox 
> <https://github.com/austinfox> Which hardware are you running the 
> screensaver on? Are you running it behind a firewall or proxy, for 
> example LittleSnitch?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153403700>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by polywebb** [comment]
Nice try but as soon as I went back to company network aerial stopped 
working
Either I didn't stay on internet line long enough for it to download 
everything or else it is not cacheing the way it should.

I may switch the lines and run it all night to see what happens.


> Alistair McMillan <mailto:notifications@github.com>
> November 3, 2015 at 10:21 AM
>
> @periodicdesign <https://github.com/periodicdesign> @austinfox 
> <https://github.com/austinfox> Which hardware are you running the 
> screensaver on? Are you running it behind a firewall or proxy, for 
> example LittleSnitch?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153403700>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by periodicdesign** [comment]
I pulled all the files from the JSON file and it has worked beautifully since. I didn't realize how large the MOV files were. I think that is the culprit. That's a lot of data to stream and cache on the fly.

**Comment by polywebb** [comment]
Jason,

How did you do that and what is the JSON file?
I nee dot do the same thing but not sure how to do it.


> Jason Wishard <mailto:notifications@github.com>
> November 4, 2015 at 1:37 PM
>
> I pulled all the files from the JSON file and it has worked 
> beautifully since. I didn't realize how large the MOV files were. I 
> think that is the culprit. That's a lot of data to stream and cache on 
> the fly.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153840820>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by periodicdesign** [comment]
Check this comment further up the stack: https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153530969

**Comment by periodicdesign** [comment]
You just need to copy and paste each link in your browser and it will download each video. When all done, move them to the cache folder as outlined. Keep in mind you can only have I think 8 sockets (downloads running) connected simultaneously. At least that was the limit I hit, so I had to wait for some to clear before proceeding with others. I'm not fancy enough to queue them all up via terminal and pull them that way.

**Comment by polywebb** [comment]
Finally it works at work!

Downloaded all the .mov files and put them in cache location
Deleted aerial saver and downloaded and installed latest beta

It works now with no problems

Thanks for all the help

> Jason Wishard <mailto:notifications@github.com>
> November 4, 2015 at 1:53 PM
>
> You just need to copy and paste each link in your browser and it will 
> download each video. When all done, move them to the cache folder as 
> outlined. Keep in mind you can only have I think 8 sockets (downloads 
> running) connected simultaneously. At least that was the limit I hit, 
> so I had to wait for some to clear before proceeding with others. I'm 
> not fancy enough to queue them all up via terminal and pull them that way.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnCoates/Aerial/issues/55#issuecomment-153844931>.
>

-- 
Jim Boughton
Polywebb Enterprise
jim@polywebb.com
817.366.6298

**Comment by alistairmcmillan** [comment]
Closing as issue is fixed for @polywebb
