### ISSUE TITLE
(Fix Inside) Aerial not Displaying full title for Dubai Night two (Sheikh Zayed Road) 

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#553]
![screen shot 2018-10-18 at 2 19 06 pm](https://user-images.githubusercontent.com/44180668/47185011-1f55ee80-d2e1-11e8-9193-78d7dbebbd73.png)
@glouel This is another bug I found that should be easy to fix:)

**Comment by glouel** [comment]
Indeed I should display the secondary name there ! Will fix tomorrow thx (this one also doesn't have extended descriptions).

**Comment by glouel** [comment]
(Fixed in next build)

**Comment by glouel** [comment]
Fixed here : 
https://github.com/glouel/Aerial/releases/download/v1.4.2test7/Aerial.saver.zip

**Comment by NightRaider73** [comment]
Thank you!

**Comment by NightRaider73** [comment]
I will keep this open until 1.4.2 is stable.

**Comment by glouel** [comment]
Closing as fixed in 1.4.2beta1 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.2beta1
