### ISSUE TITLE
Ability to Change Speed of the Aerial, like: .25X, 1X, 1.25X, 2X.

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#555]
Is there a way where @glouel could make a test build with this feature because I'm not sure how it would look.

**Comment by glouel** [comment]
Video yes, but if I do it as a test build you won't have descriptions synced.

**Comment by NightRaider73** [comment]
Ok maybe not this build maybe 1.4.3, once you have all the descriptions:)

**Comment by NightRaider73** [comment]
@glouel Is learning his spelling and Grammar!!!!!! 🎉🎉🎉🎉🎉
You get a 5/5!

**Comment by NightRaider73** [comment]
Oh and also turn 1.4.2test9 into beta 1.
You don't need to change anything though.

**Comment by glouel** [comment]
> @glouel Is learning his spelling and Grammar!!!!!! 🎉🎉🎉🎉🎉
> You get a 5/5!

🤣

> Oh and also turn 1.4.2test9 into beta 1.
> You don't need to change anything though.

Yeah I think I'll just release it as beta 1. It's good enough and fixes a few things :) Thanks for checking the readme !

**Comment by NightRaider73** [comment]
And don't forget to sign it

**Comment by glouel** [comment]
I did :) Updating the readme now.

https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta1/Aerial.saver.zip

**Comment by NightRaider73** [comment]
I didn't mean to close this sorry:\

**Comment by NightRaider73** [comment]
@glouel Do you think you could get this feature to work?
Maybe by making a different `.json` for each speed

**Comment by glouel** [comment]
Possibly, that's very low priority though, I don't really see the need for it.

**Comment by LvanProosdij** [comment]
Videos are slow motion, it can be cool to see them accelerated to normal motion or fun at faster speed.
But low priority indeed.

**Comment by ccharlton** [comment]
+1

**Comment by diimdeep** [comment]
Hey, I have been using [this](https://github.com/VFUC/Aerial/tree/playback-speed) branch for almost a year ! 
At 2x speed these videos even more amazing.

<img width="209" alt="screenshot 2018-11-16 at 15 11 53" src="https://user-images.githubusercontent.com/485713/48620677-fdb85780-e9b1-11e8-8d03-182f3ba08a0d.png">

**Comment by NightRaider73** [comment]
Thank you
