### ISSUE TITLE
Making the clock sticky

### ISSUE THREAD

**Issue by bennokress** [JohnCoates/Aerial#556]
It would be nice to have a setting to make the clock sticky while the location information is fading in and out.

**Comment by dVIAN13** [comment]
to build on that, an option to have it on it's own fade-in/out schedule around the screen... however, I still just use the sys-pref show with clock option to accomplish that... I don't mind the design of it's overlay(personally)..

**Comment by glouel** [comment]
Sticky... Well, people keep complaining that they don't want stuff to stay at the same place to avoid burn-in 😅

Having the clock on a longer schedule, that's definitely doable though, it can definitely be jarring when you have 10s in a transition. 

Reason why it moves this way right now is that I linked it to the position of the extra information. (same, h-opposed, d-opposed), I'll try to think about that one.

**Comment by SeanMSmith** [comment]
By the way, I should have thought that "horizontally opposed" meant "across, on the other side of the screen, on the same level horizontally" not "above or below".

**Comment by glouel** [comment]
> By the way, I should have thought that "horizontally opposed" meant "across, on the other side of the screen, on the same level horizontally" not "above or below".

I tried to take the mathematical approach but maybe that doesn't translate well !

**Comment by glouel** [comment]
So back to main subject, what if it sticks to the corner you asked IF you set a static corner in the text pane for descriptions, and pick one of the opposed thing ? Having it stick on "same" will be an issue, I can "animate it" to it's new position which depends on the text description below it (the line height may differ based on letters, and if you pick a truly large font, it may split to multiple lines ?

And if you pick random, animate as it is right now ? 

Does that sound like a good compromise ?

**Comment by bennokress** [comment]
I think we don't talk about the same improvement: what I would like (if possible) is - when you look at my screenshot - that the clock stays visible at all time in the same position and only the description below fades in and out just as it can be done right now.
<img width="960" alt="bildschirmfoto 2018-10-20 um 13 13 35" src="https://user-images.githubusercontent.com/6912918/47255018-5dcae500-d46a-11e8-94f6-6b85b9947039.png">

**Comment by bennokress** [comment]
Ah yes, that makes sense. I have to ask though: Font size and Screen size are constant for each session at least and only text length is variable, correct? So normally the clock doesn't have to be dependent on text length of the info text except when it exceeds one line. So will the clock also be moving by a few pixels if the info text always stays on one line (because the display is wide enough)? And would it make sense to look at other possibilities like:
* making the info text denser, if it would exceed one line
* clipping the info text, if it would exceed one line
* always reserving space for two lines of info text (okay, this may cause problems on really small displays or large font settings)

Those are just some thoughts and I would be most happy if the clock doesn't move as long as the info text stays on one line, but every solution would be an improvement in my opinion.

**Comment by glouel** [comment]
@bennokress check this version : 
https://github.com/glouel/Aerial/releases/download/v1.4.2test8/Aerial.saver.zip

With helvetica neue it shouldn't move by a pixel ;)

**Comment by bennokress** [comment]
Wow, that was fast. With IBM Plex Sans it also doesn't move. This is exactly what I thought of when opening the issue. Should I test some other scenarios for you?

**Comment by glouel** [comment]
Yeah that was a quick fix ;)

You can try a large font and see how it moves if it multi lines split to see the move effect. And random mode for corner (in that case you should see the old fades). 

I think those are decent defaults, we'll see what people think.

**Comment by bennokress** [comment]
Everything you wrote in the last post works as intended. I have just one thing you might want to consider: When using the option "Show location: 10 seconds" and a fixed corner, then the clock stays all the time and doesn't disappear with the info text which some people might want (and others might want exactly this behavior). I will personally use "Show location: always" with the fixed corner and that's perfectly solved now ;)

**Comment by glouel** [comment]
Oh that's a good catch, forgot that case. Agreed, in that case it should fade ! Will fix in next build thanks !

**Comment by glouel** [comment]
Closing as fixed in 1.4.2beta1 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.2beta1
