### ISSUE TITLE
Does not work (Blackscreen) on High Sierra

### ISSUE THREAD

**Issue by MeboGit** [JohnCoates/Aerial#559]
## Known Issues

Before logging an issue please check if one of the problems you are experiencing is mentioned here. If the issue you are experiencing isn't covered here, then please delete this content and tell us about the problem you are experiencing or the feature you'd like to request.

### "You cannot use the Aerial screen saver with this version of OS X." message

If you get a message saying `You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` that is a known bug with macOS that was reported to Apple in April 2016 as [rdar://25569037](http://openradar.appspot.com/25569037). As of November 2017 the bug is still not fixed. To work around the bug:
* Select the Aerial screensaver in System Preferences
* Close System Preferences with Aerial selected
* Reopen System Preferences and the preview should work now

### Mac won't sleep with Aerial as screensaver

If your Mac won't sleep while Aerial is the selected screensaver, then you probably have an older version of Aerial installed. Download the latest verson of Aerial here: https://github.com/JohnCoates/Aerial/releases/ Make sure to check both locations for the old version, it can be installed to `/Library/Screen Savers` and `/User/YOURUSERNAME/Library/Screen Savers`.

### Corrupted playback

If you are getting corrupted playback when the screensaver starts then that is a new bug in macOS High Sierra. It appears to be a problem with the Intel drivers in High Sierra. As a workaround tick the "Show with clock" option as that seems to eliminate the corruption for the moment. Discussed extensively here: https://github.com/JohnCoates/Aerial/issues/377

### No playback

If you are getting a crossed out play icon instead of the preview or the videos just never seem to load, please check that a firewall or proxy isn't blocking the screensavers access to the videos. Trying the following two URLs in a web browser might show if they are blocked. If you are on a Macbook you can also try caching the videos on another network to test whether it is your network provider that is blocking access.
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov
http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

**Comment by MeboGit** [comment]
Also tried reinstall and restart options, no go!
Well, maybe takes another 2 years to get a working mac scrennsaver?!

**Comment by MeboGit** [comment]
Also suprising, how complicated a screensaver can be?!
Much easier on Windows!!

**Comment by glouel** [comment]
Well, if you'd like some help, maybe try to be nice and elaborate a bit about your issue ? 

- What happens if you close and reopen System Preferences, go to Screensaver and select Aerial on the left, do you see a mini preview streaming ? 
- If you open Aerial preferences and click a video on the list on the left, does it start playing or not ? 
- Have you tried downloading a video (clicking the + button next to a video) to cache it ? Does that work ?

**Comment by MeboGit** [comment]
Sorry but tried over 30 minutes and just wanted to install a screensaver not a new operating system.

Thanks for your quick response.

I closed/reopened System Preferences many times with Aerial selected/unselected but Click on Preview was Black Screen. The mini preview screen was shown though.
When I click a video on the list it starts playing.

I finally found out that the screensaver itself seems to work, only the preview is (still) not working ( black screen)?!

Maybe a Message when click on Preview: "Even if you see a black screen the screen saver still may work"?!

Thank you for your help.

**Comment by glouel** [comment]
Yes, the "preview button" is broken on 1.4.1...

There's an issue posted about exactly this here with the explanation and fix : https://github.com/JohnCoates/Aerial/issues/548

**Comment by glouel** [comment]
Closing as fixed in 1.4.2 beta 1 https://github.com/JohnCoates/Aerial/releases/tag/v1.4.2beta1

**Comment by MeboGit** [comment]
Hi,

thanks for distributing this fast fix. The screen saver itself looks very cool.

Anyhow I encountered two other issues now:

1. In 1.4.1 I could say only show on main monitor, now it automatically shows on all monitors (vertical and horizontal) but not in the wright way (see picture)
2. Before I saw caption on the pictures, now there are none and also no options for labels.

Also there are a lot less options now (see other picture)?!

Best regards

Michael (Mebo)

**Comment by glouel** [comment]
I don't see your pictures. Have you restarted System Preferences after upgrading ? This is a macOS bug that we can't fix, it messes the UI.

**Comment by MeboGit** [comment]
Here the pictures...and yes I restarted preferences at least 5 times, also I deleted the old version before installing new version.

![pastedgraphic-1](https://user-images.githubusercontent.com/15740317/47260844-0c027900-d4c3-11e8-91ed-16718e69439a.png)
![20181020_212133135_ios](https://user-images.githubusercontent.com/15740317/47260845-115fc380-d4c3-11e8-8fa8-cb3de6e5abd5.jpg)

**Comment by glouel** [comment]
That's definitely not 1.4.2 ! This looks like the old 1.2 version from years ago. Are you sure you downloaded the right one ? 

Try this link : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta1/Aerial.saver.zip

**Comment by MeboGit** [comment]
I took Aerial.saver out of the following archive:
![grafik](https://user-images.githubusercontent.com/15740317/47260878-00fc1880-d4c4-11e8-8369-7076e76d9e8f.png)

**Comment by glouel** [comment]
You have to use the zip I linked, this is no good, I'll see to remove it.

**Comment by MeboGit** [comment]
Ok, tried the other zip file now, that seems to be the newer version.

But the picture still shows in the same layout on vertical screen.

**Comment by glouel** [comment]
Make sure you have removed the old one and restarted syspref. If that's still an issue, feel free to reopen with more information about your setup : 
- Mac model
- mac OS version
- Screen resolution (and retina)

There's also a new debug mode in Advanced, you can enable it and enable log to disk, and run the screensaver once (don't use preview, run the screensaver normally) and post the file there so I can have a look at it tomorrow.

**Comment by MeboGit** [comment]
Ok, thank you. 

I think I will only use it on main screen for now.

**Comment by glouel** [comment]
More bugs were fixed specifically in multi monitor setups + mirrored mode in b2 : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta2/Aerial.saver.zip
