### ISSUE TITLE
Feature: prevent shifting AM/PM indicator with non-default font

### ISSUE THREAD

**Issue by fcpwiz** [JohnCoates/Aerial#562]
I noticed that since the seconds of the digital clock are constantly changing, the "AM"/"PM" are always shifting left and right to compensate for the added/lost pixels needed for the different numbers that make up the seconds.

To address this distracting shifting of the "AM"/"PM" indicator, either:

(1) make the "AM"/"PM" fixed, disconnecting it from the seconds that precede it, and/or;
(2) give the option to disable the seconds on the clock

ps: I am using the font San Fransisco Pro Text.

**Comment by glouel** [comment]
1) is messy, especially taking into account right aligned options where it just shift the issue to minutes:hours
2) it is then

You can also use a monospaced font if that really bothers you and you want seconds.

**Comment by glouel** [comment]
@fcpwiz This is fixed in beta2 per above : 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta2/Aerial.saver.zip

**Comment by fcpwiz** [comment]
Great, thank you @glouel !

**Comment by glouel** [comment]
@fcpwiz 
Note that this is actually bugged in public beta, this build here: 

https://github.com/glouel/Aerial/releases/download/v1.4.2beta5/Aerial.saver.zip

fixes the issue that was reported here: 

https://github.com/JohnCoates/Aerial/issues/568

If all goes well I'll push stable 1.4.2 later today which will have the fix too.
