### ISSUE TITLE
Can't use Nightshift to control timed display option

### ISSUE THREAD

**Issue by Rossh51** [JohnCoates/Aerial#563]
I have late 2015 27" iMac with Mohave OS and latest version of Aerial. Although Mac supports Nightshift this option is greyed out in the Time tab under preferences. New to Aerial not sure if a problem or my lack of knowledge!

**Comment by glouel** [comment]
What's the error message ? Something that can happen on recent Macs is that in order for night shift to detect sunset/sunrise time, you need to have location services enabled. It should tell you so in the grey area. 

Can you check for that ? 

Another way to check is to go to terminal and run `/usr/bin/corebrightnessdiag nightshift-internal`

More information about this here https://github.com/JohnCoates/Aerial/issues/528

**Comment by Rossh51** [comment]
No error message but I had a similar problem to user in post #528 ie (null) in Night Shift / Sunrise section of Terminal output. Turning Location Services off and on seems to have fixed it. Thanks for the help.

**Comment by glouel** [comment]
It should have appeared in the UI in the grey line where you see the sunset/sunrise times right now, are you sure it wasn't there ? Good anyway that this is fixed !

**Comment by Rossh51** [comment]
Ah. I did not notice the times are there until you pointed them out. I don't think they were there before and the complete option was not available.

**Comment by glouel** [comment]
I may add a warning icon to point to them in case of error. Thanks !
