### ISSUE TITLE
1.4.2 beta 3 - black screen / no video

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#565]
Been running Aerial for years on the same Mac Mini late-2012 with 2 1920x1080 monitors in a vertical stack layout. Up until today I was running fine with 1.4.1.

I decided to try 1.4.2beta3 and I can't get it to play any videos.

The small mini-preview window plays video fine - I can see that when I open it via the pref pane. However, when the screensaver kicks in, all I see are 2 black screens. Triggering via the "Preview" button within the CP or via "hot corner" gives the same result.

OS is Mojave 10.14.1 beta4 (18B67a)

I have no problem loading or caching videos directly, nothing blocking in my firewall etc. I also tried enabling the "Never stream videos / Never stream previews" options, just to see if it made any difference (it didn't).

Reverting back to 1.4.1 got everything working again.

I enabled Debug Logging and here's the output:

```
5:07:54 PM : UI logToDisk: true
5:08:02 PM : <AerialView: 0x7faae1c161a0> stopAnimation
5:08:02 PM : avInit1
5:08:02 PM : <AerialView: 0x7f8069200110> AerialView setup init
5:08:02 PM : <AerialView: 0x7f8069200110> isPreview : false
5:08:02 PM : <AerialView: 0x7f8069200110> singlePlayerAlreadySetup false
5:08:02 PM : <AerialView: 0x7f8069200110> nbPlayers 0 previewPlayerExists false
5:08:02 PM : <AerialView: 0x7f8069200110> no local player
5:08:02 PM : <AerialView: 0x7f8069200110> setupPlayerLayer
5:08:02 PM : <AerialView: 0x7f8069200110> setting up player layer with frame: (0.0, 0.0, 1920.0, 1080.0) / (0.0, 0.0, 1920.0, 1080.0)
5:08:02 PM : Manifest init
5:08:02 PM : isManifestCached 10 true
5:08:02 PM : isManifestCached 11 true
5:08:02 PM : isManifestCached 12 true
5:08:02 PM : Manifests files were not loaded in class
5:08:02 PM : Files were not already loaded
5:08:02 PM : Manifests are cached on disk, loading
5:08:02 PM : Poi Strings Provider initialized
5:08:02 PM : path : /Users/luke/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
5:08:02 PM : Community JSON : 54
5:08:02 PM : Could not determine duration, video is not cached in any format
5:08:02 PM : <AerialView: 0x7f8069200110> Setting player for all player layers in []
5:08:02 PM : Time Management initialized
5:08:02 PM : initvideocache
5:08:03 PM : cached video file with length: 287804109
5:08:03 PM : <AerialView: 0x7f8069200110> playing video (OFFLINE MODE) : file:///Users/luke/Library/Caches/Aerial/b2-2.mov
5:08:03 PM : <AerialView: 0x7f8069200110> observing current item <AVPlayerItem: 0x600001852a30, asset = <AVURLAsset: 0x600001a1ed00, URL = file:///Users/luke/Library/Caches/Aerial/b2-2.mov>>
5:08:03 PM : <AerialView: 0x7f8069200110> observeValue Optional("readyForDisplay")
5:08:03 PM : AssetLoaderDelegate deinit
5:08:03 PM : <AerialView: 0x7f8069200110> backing change 1.0 isDisabled: false
5:08:03 PM : avInit1
5:08:03 PM : <AerialView: 0x7f8066e0a1e0> AerialView setup init
5:08:18 PM : <AerialView: 0x7faae1c161a0> startAnimation
```

**Comment by luckman212** [comment]
No, I was not using mirroring mode—Unique video on each display.

**Comment by glouel** [comment]
That makes sense in a way, I may have broken that mode while fixing mirrored. Again, sorry I'll fix tomorrow !

**Comment by glouel** [comment]
@luckman212 So in my haste to squash that nasty mirroring mode I did mess everything else up 😅 I did recheck every cases (previews, non previews) on two multimonitor setups (one Mojave, one 10.13.6).

This time (...) it should really be fine, I'll post beta4 as soon as GitHub let me do so (maybe a couple hours according to their status...)

**Comment by glouel** [comment]
@luckman212 : Fixed everything in beta 4, again sorry about that one ! 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta4/Aerial.saver.zip

**Comment by luckman212** [comment]
@glouel Thanks for such a quick fix! Yes, I confirm that [1.4.2beta4](https://github.com/JohnCoates/Aerial/releases) works just fine.

**Comment by glouel** [comment]
@luckman212 Thanks again for your report, and checking the fix so quickly too 👍

**Comment by glouel** [comment]
Marking as fixed in https://github.com/JohnCoates/Aerial/releases/download/v1.4.2/Aerial.saver.zip
