### ISSUE TITLE
1.4.2 b4 show with seconds.

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#568]
@glouel, When show with seconds is not checked, I get the following preview:

<img width="591" alt="screen shot 2018-10-22 at 7 41 34 am" src="https://user-images.githubusercontent.com/22992333/47298965-f168f680-d5cd-11e8-864f-407c8fd9869e.png">

if I turn it on(checked), I get:

<img width="503" alt="screen shot 2018-10-22 at 7 41 41 am" src="https://user-images.githubusercontent.com/22992333/47298984-fcbc2200-d5cd-11e8-9c02-784682bdc578.png">

Settings Panel:

<img width="626" alt="screen shot 2018-10-22 at 7 39 32 am" src="https://user-images.githubusercontent.com/22992333/47299000-080f4d80-d5ce-11e8-86de-41fbd3b8bb26.png">

**Comment by glouel** [comment]
@dVIAN13 My bad, I think I had a bug that didn't show on locales without the AM/PM thing. 

Any chance you can check this build when you have a sec ? 

https://github.com/glouel/Aerial/releases/download/v1.4.2beta5/Aerial.saver.zip

**Comment by dVIAN13** [comment]
@glouel, That resolved the bug, and it's good to go! Thanks!

**Comment by dVIAN13** [comment]
thanks!, not that it's a bug necessarily, however, if you're on the main panel(videos), and it's displaying a preview, if you then go to cache and click 'download now', it jumps back to main screen, but the display is then black. This is the case whether of not there are downloads available.

**Comment by glouel** [comment]
Ha yes, I removed the old "Download now" to put in the stop button and thus I send back to the video panel. 

I guess something happens when the list refresh itself to add the queue/download indicators. Maybe there's the same thing when you use the menu below, I'll try to have a look thanks !

**Comment by glouel** [comment]
> thanks!, not that it's a bug necessarily, however, if you're on the main panel(videos), and it's displaying a preview, if you then go to cache and click 'download now', it jumps back to main screen, but the display is then black. This is the case whether of not there are downloads available. I can open up a new issue if you'd like..

I'm pretty sure I reproduced the issue yesterday but I can't this morning, hmm ! Whether from the menu or from the Download now button, it keeps playing, whether I have a 4K or a 1080p video selected. I'm pretty sure I didn't fix it though. Will keep an eye on it.

**Comment by glouel** [comment]
Marking as fixed in 1.4.2.

https://github.com/JohnCoates/Aerial/releases/download/v1.4.2/Aerial.saver.zip
