### ISSUE TITLE
Update Aerial Thumbnail

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#569]
@glouel I think that the thumbnail is a little blurry you can see below:
![screen shot 2018-10-22 at 10 23 10 am](https://user-images.githubusercontent.com/44180668/47307749-ac03f380-d5e4-11e8-878a-0c7ea71e4133.png)

**Comment by glouel** [comment]
I think that's just the 1080p video getting downscaled that artifacts like that, although it does look particularly bad. Is that on a retina screen ?

On 4K videos I noticed the opposite, where the previews are extra sharp and small details tend to blink. I'll have a look tomorrow, I'm not sure if we can pick any resizing method (usually you can) for previews.

**Comment by NightRaider73** [comment]
No I have a Late 15 MacBook Air

**Comment by NightRaider73** [comment]
Not the Preview the thing in the bottom left corner

**Comment by glouel** [comment]
Fixed in 1.4.2 !

https://github.com/JohnCoates/Aerial/releases/download/v1.4.2/Aerial.saver.zip

**Comment by max1mvs** [comment]
That is so bloody cool! The best screensaver ever. And that goes beyond the videos themselves as well. Great job guys!

**Comment by dVIAN13** [comment]
@glouel noticed that the image is actually outside of the border... see screenshot. 

<img width="244" alt="screen shot 2018-10-23 at 8 07 47 am" src="https://user-images.githubusercontent.com/22992333/47370711-2d1dc200-d69b-11e8-83af-e18b0600de9d.png">

and possibly still slightly blurry on a new 5k iMac I'm setting up for a client.. ;)

**Comment by glouel** [comment]
> @glouel noticed that the image is actually outside of the border... see screenshot.
> 
> <img alt="screen shot 2018-10-23 at 8 07 47 am" width="244" src="https://user-images.githubusercontent.com/22992333/47370711-2d1dc200-d69b-11e8-83af-e18b0600de9d.png">

Apparently we had the same issue before, see this screenshot here : 

![](https://user-images.githubusercontent.com/37544189/46805565-ad702900-cd65-11e8-9779-91243ee9e634.png)

Guess I need to cut the corner of the image !

> and possibly still slightly blurry on a new 5k iMac 

I'll try to see what images are used by the bundled screensavers, that may have changed and the info I found was outdated 90x58 and 180x116@2x for retina.

>I'm setting up for a client.. ;)

What a nice thing to do for your client 👍

**Comment by glouel** [comment]
FYI found this : https://stackoverflow.com/questions/34030980/os-x-screensaver-retina-thumbnail-image

Regarding corner faking, I can do it, no issue. But the retina thing looks like a bug, I used the same method as the guy did and it's indeed blurry looking closely. 

And as the guy said, indeed the effect/corners are baked in default savers ! Very weird : 

![capture d ecran 2018-10-23 a 17 41 30](https://user-images.githubusercontent.com/37544189/47372912-08e9d180-d6eb-11e8-9b57-2d3eb0c37e11.png)

**Comment by dVIAN13** [comment]
no worries.. I think the obvious thing was the corner, imo... the retina thing just may be slightly more of an issue at higher(bigger) resolutions?

**Comment by glouel** [comment]
@dVIAN13 here's the build with the new icon with rounded corners, I tried to align myself to word of the day although the other ones are slightly different. 

https://github.com/glouel/Aerial/releases/download/v1.4.4test2/Aerial.saver.zip

Also couple of new featuer, manual sunset/sunrise calculation from latitude/longitude, and brightness reduction !

**Comment by dVIAN13** [comment]
corners look great! and it doesn't stick out anymore form the other savers... ;) thank you!

**Comment by glouel** [comment]
Closing this with https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta1/Aerial.saver.zip

**Comment by NightRaider73** [comment]
I am still getting a blurry picture on my 2015 MacBook Air:
![screen shot 2018-10-25 at 3 18 56 pm](https://user-images.githubusercontent.com/44180668/47533630-5429ee80-d869-11e8-811b-e977530a182b.png)
