### ISSUE TITLE
Ariel does not install--unregistered developer

### ISSUE THREAD

**Issue by duanes712** [JohnCoates/Aerial#57]
Cannot install the developer unregistered error message is given. Latest Safari and system from Apple.

**Comment by trustypelletgun** [comment]
You have to manually allow the installation. Go to the Security & Privacy section in System Preferences and click the "Open Anyway" button and provide admin credentials.

A faster (but less explicit and informative) way avoid this warning is to contol+click on the Aerial.saver file and click "Open" in the context menu. See this support document https://support.apple.com/kb/PH21769?locale=en_US for more information.

**Comment by duanes712** [comment]
Excellent answer. It works as advertised using the methods suggested trustypelletgun.

**Comment by fwartner** [comment]
I have signed a release: https://github.com/fwartner/Aerial/releases/tag/v1.1%40signed

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #10
