### ISSUE TITLE
Memory leak ? (downloading videos from Control Panel)

### ISSUE THREAD

**Issue by LvanProosdij** [JohnCoates/Aerial#573]
Aerial 1.4.2, macOS 10.14, iMac 16 GB.

Reproductible : 
- For testing I removed Aerial cache folder.
- Open Control Panel, Screen Saver, Aerial, Screen Saver Options…, Videos, Check All, Download All. Keep panel open.
- Process `Desktop Picture (System Preferences)` memory usage keeps growing and growing while downloading file after file.
- The more files are loaded the more memory is used, GB adds to GB, computer starts to swap, everything gets slower and slower. An 8 GB Mac will completely freeze.
- Quitting the Control Panel frees memory.
![screenshot 2018-10-23 at 17 37 01](https://user-images.githubusercontent.com/6991846/47372539-47cb5780-d6ea-11e8-9d57-275b0a4decfa.png)
![screenshot 2018-10-23 at 17 59 40](https://user-images.githubusercontent.com/6991846/47374406-25d3d400-d6ee-11e8-8b77-d94f3a50d8a4.png)

**Comment by glouel** [comment]
Reproduced, thanks for your report, will look into it !

**Comment by glouel** [comment]
Fixed in 1.4.3, there was also a retain cycle when streaming videos. Those were some pretty old bugs but now that we have many more videos it made things much worse !

https://github.com/JohnCoates/Aerial/releases/download/v1.4.3/Aerial.saver.zip

**Comment by LvanProosdij** [comment]
Great news!
That may also explain reports of slowed down Mac (and sometimes freezes), high CPU usage, etc.

**Comment by glouel** [comment]
Quite possible on streaming yep !
