### ISSUE TITLE
Feature request: Being able to put the text anywhere

### ISSUE THREAD

**Issue by StrangePC** [JohnCoates/Aerial#583]
can we please be able to move the text around instead of only being able to put it in a corner.

**Comment by NightRaider73** [comment]
@glouel Might be able to help you

**Comment by glouel** [comment]
@StrangePC Define anywhere ? As of right now you can use random corner if you don't want it to stick always at the same place.

**Comment by StrangePC** [comment]
I mean like say in the middle or anywhere. I want to make it look as much as the Apple TV as possible and currently the text is too far in the corner

**Comment by NightRaider73** [comment]
Maybe an option where it lets you drag "text" any where on a little box. Maybe?

**Comment by glouel** [comment]
@StrangePC As far as I know it's in the left bottom corner on Apple TV ?

**Comment by StrangePC** [comment]
yes, but not that far down @glouel

**Comment by NightRaider73** [comment]
And the text is a tad bit smaller.  I think

**Comment by StrangePC** [comment]
<img width="1440" alt="screen shot 2018-10-26 at 9 37 29 am" src="https://user-images.githubusercontent.com/44482890/47534370-d2869f00-d902-11e8-8bd2-711a232a485a.png">

**Comment by StrangePC** [comment]
<img width="1440" alt="screen shot 2018-10-26 at 9 38 39 am" src="https://user-images.githubusercontent.com/44482890/47534403-f518b800-d902-11e8-9de9-9338ac92ba56.png">

**Comment by StrangePC** [comment]
<img width="1440" alt="screen shot 2018-10-26 at 9 39 33 am" src="https://user-images.githubusercontent.com/44482890/47534433-14174a00-d903-11e8-8806-73b0810ac795.png">

**Comment by StrangePC** [comment]
see the difference @glouel

**Comment by glouel** [comment]
I do, but we don't aim to copy *exactly* everything Apple does. They may, and rightly so, take offense to it. We're quite happy that they haven't so far.

Adding a custom fixed position could be done, I'll put it in the list of future features to be looked at.

**Comment by StrangePC** [comment]
ok thanks

**Comment by NightRaider73** [comment]
@StrangePC Apple could easily just block all the links to devices not running a piece of hardware that is only found in Apple TVs

**Comment by LvanProosdij** [comment]
We have fewer risks of Apple blocking Aerial if it is beautifully executed, respecting Apple look and feel, contributing to "create value", which is what Aerial does.

**Comment by glouel** [comment]
Trying not to break everything, one "easy" option would be to allow to change the margin relative to the corner, this way it doesn't break the rest of the features. I'll keep thinking about it.

**Comment by glouel** [comment]
@StrangePC 

Added the option to change the margin in beta2. Also change the default to 50/50px instead of 10/10. 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta2/Aerial.saver.zip

**Comment by NightRaider73** [comment]
Lets give a cheer for @glouel

**Comment by glouel** [comment]
Closing as fixed.
