### ISSUE TITLE
Super Blurry Thumb Nail

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#584]
@gIouel I am still getting a blurry picture on my 2015 MacBook Air:
![screen shot 2018-10-25 at 3 24 59 pm](https://user-images.githubusercontent.com/44180668/47533854-2e511980-d86a-11e8-85c2-73fa9ab58a7a.png)

Is there any way you could sharpen the picture or compress it differently?

**Comment by glouel** [comment]
There's no need to reopen a new issue, I get notifications for messages on closed issues and reply there. And no I can't do better than that, I suggest you read the other thread.
