### ISSUE TITLE
Focus issue on version prior to Mojave ?

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#586]
I've seen a weird bug on my old Macbook Air that's stuck on 10.13.6. When you open Aerial preferences, the preferences sheet doesn't have focus. The biggest hint is that the tab bar is grey instead of blue (in focus) : 

![bug](https://user-images.githubusercontent.com/37544189/47573866-a0932e00-d93e-11e8-959a-a70bc25ec4e4.png)

This used to be of little impact in older versions, but with more recent ones, apart from the color thing, you simply can't type in any text field, which is an issue for custom messages, brightness duration and longitude/latitude.

Does anyone else experience this on any version of macOS prior to Mojave or is it just on my system ? I've rolled back to 1.2 and the issue was already there, I tried a few things to fix it but no luck.

**Comment by glouel** [comment]
Interesting, hopefully we'll get more data on this !

**Comment by NightRaider73** [comment]
Yes I don't know why it works that way🤨

**Comment by SeanMSmith** [comment]
I too am seeing this problem on my iMac17,1 (Retina 5K, 27-inch, Late 2015) in macOS 10.13.6.

**Comment by glouel** [comment]
Thanks for confirmation. Been trying to look onto that one all day with no success so far.

**Comment by glouel** [comment]
Please see here for the workaround : https://github.com/JohnCoates/Aerial/issues/606#issuecomment-434813082
