### ISSUE TITLE
Gray out the Brightness options when the Master setting is not chosen

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#589]
![screen shot 2018-10-26 at 10 26 09 am](https://user-images.githubusercontent.com/44180668/47582575-9145bd80-d909-11e8-922d-39663ac862af.png)
As you can see up above I can still click all the options that you don't really need access to like down below:
![screen shot 2018-10-26 at 10 27 08 am](https://user-images.githubusercontent.com/44180668/47582618-b4706d00-d909-11e8-9415-41a1fa2d0e7b.png)
Not selected so you shouldn't be able to type ect.

**Comment by NightRaider73** [comment]
@glouel See what I mean?

**Comment by NightRaider73** [comment]
Oh and by the way @glouel You are doing amazing, amazing, amazing, amazing, work

**Comment by glouel** [comment]
Yep, I do, will put that in next thanks !

**Comment by NightRaider73** [comment]
Also when you delete your coordinates it doesn't recalculate them for you, maybe add a recalculate  coordinates option.

**Comment by NightRaider73** [comment]
@glouel With the v.1.4.4 release maybe update the screenshots because there is SO much more options now

**Comment by glouel** [comment]
The master thing is done for brightness and text. I'll look into the coordinate stuff at some point. 

(and yes for screenshot @ 1.4.4 finale)

**Comment by glouel** [comment]
> Also when you delete your coordinates it doesn't recalculate them for you, maybe add a recalculate coordinates option.

It does as soon as you validate the field (enter, leave, etc), I don't see the problem. If one field is empty it will prompt you to fix it.

**Comment by glouel** [comment]
Fixed in beta 3 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta3/Aerial.saver.zip
