### ISSUE TITLE
Seconds digits are truncated

### ISSUE THREAD

**Issue by heldausberlin** [JohnCoates/Aerial#592]
If you use your own font for the time on both Mojave and High Sierra , the seconds digits on the edge of some videos are truncated. Completely independent of the margins to corner.

It's just the wide digits like 06, 28, 39 etc.

It is on both the MacBook Pro (2016) 13" display and the external 24" display.

<img width="228" alt="bildschirmfoto 2018-10-27 um 16 25 54" src="https://user-images.githubusercontent.com/843542/47605327-34c7c880-da05-11e8-847a-391f7aca2a48.png">

<img width="207" alt="bildschirmfoto 2018-10-27 um 16 18 17" src="https://user-images.githubusercontent.com/843542/47605228-43fa4680-da04-11e8-90f8-87873f99fc80.png">

**Comment by glouel** [comment]
Ha yes ! Need to resize the rectangle, will see if I can fix that thanks for the report !

**Comment by glouel** [comment]
Side bug, clock was also not showing if you deactivated community descriptions and picked a video where there were no apple provided descriptions. 

Fixed in beta 3 : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta3/Aerial.saver.zip
