### ISSUE TITLE
Feature Request: Keep clock but hide descriptions

### ISSUE THREAD

**Issue by oddharsh** [JohnCoates/Aerial#595]
An option to always have the clock be displayed but have the descriptions hide (basically separating the two in terms of when they show up) would be super cool.

**Comment by LvanProosdij** [comment]
You can check the clock option in macOS Screensaver to get a clock all time

**Comment by dVIAN13** [comment]
I believe this idea has been proposed before, and the decision was made to not include it because of ‘burn-in’ potential.

**Comment by glouel** [comment]
Yeah sorry @oddharsh, if you only want the clock there's one built in with macOS that you can enable in the main pane. 

Aerial's clock was implemented to have a clock that doesn't interfere with the descriptions (as MacOS's clock did). Clock and descriptions are tied down in the way they appear and it would be pretty hard to decouple them.
