### ISSUE TITLE
Brightness settings only work on primary display

### ISSUE THREAD

**Issue by jakecovert** [JohnCoates/Aerial#598]
Hello. I have two external monitors connected.  One via Thunderbolt 2, and one via HDMI.  (2015-era MacBook Pro running latest Mojave).

When I use the dimming, fade to black option, it only works on the main display.

LOVE the work.  Great job!

**Comment by jakecovert** [comment]
Correct. Only the physical laptop screen dims.  :-)

**Comment by glouel** [comment]
Ok thanks, just to confirm too, if you use the brightness keys on your Macbook, do all of the screens dim ? 

Here with DVI over DP, external screens don't change brightness either for example. I'm not sure every monitor can have it's brightness control over every interface, will look more into it.

**Comment by jakecovert** [comment]
Ah.. this makes sense.  Using the brightness button on my laptop does only change the actual laptop display.  So, if you're using that methodology, I'd understand why that doesn't work.

**Comment by glouel** [comment]
Yeah we use macOS' system brightness controls, so if they don't work with your monitors, Aerial won't be able to do more. 

As far as I know, you could control external Apple monitors too, but probably not other brands through those system settings. It may depend on the interface used too (maybe the LG 5K monitor supports this ?)

**Comment by glouel** [comment]
@jakecovert , I have added a description of how the brightness dimming works in the readme. I'll keep in mind if I can do something else about this at some point, but macOS doesn't seem to help a lot on this. Thanks !
