### ISSUE TITLE
Featured on 9to5mac!!

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#599]
@glouel, again, Great work on this!!! 

https://9to5mac.com/2018/10/29/apple-tv-screensavers-to-mac/

**Comment by glouel** [comment]
I did send them an email earlier today, and they were kind enough to write about the project, pretty cool feature too ;)

**Comment by jay-hankins** [comment]
Great work on all the improvements with this @glouel. Seeing the new 4K screensavers always brightens my day! 😄🌻

**Comment by ccharlton** [comment]
Saw this too! Mad props!!!!!!!!!
