### ISSUE TITLE
Don't see any screen saver in pref

### ISSUE THREAD

**Issue by Cataklix** [JohnCoates/Aerial#6]
I cannot enable one of all the screen saver : 
![screen 1 - copie](https://cloud.githubusercontent.com/assets/14280044/10755225/9fcfd574-7c9c-11e5-903f-f10a237d7dca.jpg)
Any solutions ?
![sans titre - copie](https://cloud.githubusercontent.com/assets/14280044/10755262/d6c2677c-7c9c-11e5-9aa6-b61171015e21.jpg)

**Comment by JohnCoates** [comment]
If you open up the Console app, do you see any logs that pertain to this?

**Comment by Cataklix** [comment]
No

**Comment by JohnCoates** [comment]
What happens when you visit the following link: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

**Comment by Cataklix** [comment]
![sans titre - copie](https://cloud.githubusercontent.com/assets/14280044/10755422/099478ce-7c9e-11e5-9c27-ce886fe413b8.jpg)
that

**Comment by JohnCoates** [comment]
I think it's because it's not able to load the JSON list for some reason. Maybe try restarting?

**Comment by Cataklix** [comment]
Not working after restarting

**Comment by JohnCoates** [comment]
You don't happen to have Xcode and are able to compile the testing target?

**Comment by Cataklix** [comment]
It's working now, thanks you

**Comment by JohnCoates** [comment]
Oddly enough a lot of people report the same thing. It wasn't working, and now it is.
