### ISSUE TITLE
Not working on my MacBook Air

### ISSUE THREAD

**Issue by askming** [JohnCoates/Aerial#60]
Hi John,

Thanks for your work. I've tried to download and installed the screen saver, the installation was successful, however, when I try to switch to it, it seems not working. As you can see in the attachment. Could you help to advise what is wrong with it?

Thanks!
Ming
![screen shot 2015-10-28 at 19 44 19](https://cloud.githubusercontent.com/assets/5671771/10807315/5124174e-7dac-11e5-8c4c-d99d93e8d4a4.png)

**Comment by fwartner** [comment]
Try this signed one: https://github.com/fwartner/Aerial/releases/tag/v1.1%40signed

**Comment by devSC** [comment]
@fwartner it's still can't use in my macbook pro 15.

**Comment by askming** [comment]
@fwartner Same for me. Still not working.

**Comment by alistairmcmillan** [comment]
@askming Did you get the screensaver working?

**Comment by askming** [comment]
No. Not working.

**Comment by alistairmcmillan** [comment]
@askming Have you tried the recent betas? https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

**Comment by alistairmcmillan** [comment]
@askming If they still don't work try the following URLs. If you're unable to view the movie at the following URLs then that most likely means a firewall or proxy is preventing you from accessing the movies on Akamai's servers.

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

**Comment by askming** [comment]
When I click or copy the link to browser it just starts to download it to my computer.

**Comment by alistairmcmillan** [comment]
@askming Cool, that means the videos aren't being blocked. :)

Try 1.2b5 and see if it works for you.

**Comment by askming** [comment]
Oh, it's working now! Great！

**Comment by alistairmcmillan** [comment]
@askming Cool. Glad to hear it. :)

@devSC Did you get it working?

**Comment by askming** [comment]
@alistairmcmillan Thanks for the great work!

**Comment by alistairmcmillan** [comment]
@askming Not me. :) The screensaver is all @JohnCoates's work.

**Comment by askming** [comment]
I see. Thank you both then :).
