### ISSUE TITLE
Cannot select Done from the Screen Saver Options for Aerial in System Preferences

### ISSUE THREAD

**Issue by pws442** [JohnCoates/Aerial#608]
MacBook Pro (15-inch, Late 2016)
Mojave 10.14.1
Local display

Cannot select Done from the Screen Saver Options for Aerial. This was before the 10.14.1 Mojave update. Must Force Quite System Preferences.

I have the savers cached.

**Comment by glouel** [comment]
@pws442 was it just after install ? Did you restart the System Preferences panel after install (as suggested) ? 

Which version of Aerial are you using ? Pretty sure I fixed this in 1.4 on Mojave.

**Comment by pws442** [comment]
Nah, I am an idiot. I downloaded all that Bask stuff, and tried to upgrade my older version, I guess (don’t know how to show the version), and it still had only the two buttons on the Options in Screen Saver. Finally, I renamed/deleted everything, and clicked the download link for the Mac, and LIFE IS GOOD AGAIN!

Wonderful screen saver. Looking forward to the other options that this has.

Paul W Schluter
paul@paulschluter.com
Sent from my MacbookPro

On Oct 30, 2018, at 16:09, Guillaume Louel <notifications@github.com> wrote:

@pws442 <https://github.com/pws442> was it just after install ? Did you restart the System Preferences panel after install (as suggested) ?

Which version of Aerial are you using ? Pretty sure I fixed this in 1.4 on Mojave.

**Comment by glouel** [comment]
No problem, enjoy !

**Comment by pws442** [comment]
I just LOVE this version. I only had 2 buttons in the options, but now a veritable plethora of nice options?

My wife has a MacBook Pro that cannot be upgraded to Mojave, even though it has 16GB RAM and a 2TB SSD. Can she use the same download as I did? I did read the release info on the beta version. Her only issue is that it stops moving after a fashion and then does not change.

Thanks a lot!

Paul W Schluter
paul@paulschluter.com
Sent from my MacbookPro

On Oct 30, 2018, at 18:03, Guillaume Louel <notifications@github.com> wrote:

Closed #608 <https://github.com/JohnCoates/Aerial/issues/608>.

**Comment by glouel** [comment]
Hey Paul

Thanks for your kind words. I'll have a much better beta specifically for High Sierra later today. I'll reply to this message when it's posted to let you know, it will be much less cumbersome than the currently posted beta. 

You mentioned it stops moving on your wife laptop, I guess that's with 1.4.4 right ? Just wait a bit for next beta, the 1.4.5 betas have a fix for some video driver issues on 10.13.6.

**Comment by pws442** [comment]
Hi,

It was not 1.4.4, as I just downloaded it yesterday, thank you very much. In fact, I have NO CLUE as to how to check the version! I just know hers has, and mine had, only 2 buttons in the options of the screen saver preferences (and I had to force quit out of System Preferences when I went into the options. Don’t know about hers).

Thanks again!


Paul W Schluter
paul@paulschluter.com
Sent from my MacbookPro

On Nov 1, 2018, at 10:03, Guillaume Louel <notifications@github.com> wrote:

Hey Paul

Thanks for your kind words. I'll have a much better beta specifically for High Sierra later today. I'll reply to this message when it's posted to let you know, it will be much less cumbersome than the currently posted beta.

You mentioned it stops moving on your wife laptop, I guess that's with 1.4.4 right ? Just wait a bit for next beta, the 1.4.5 betas have a fix for some video driver issues on 10.13.6.

**Comment by glouel** [comment]
Hey Paul

No worries, that was an old version indeed with plenty of known issues. Please uninstall the old version on your wife's Mac, see the instructions here : https://github.com/JohnCoates/Aerial#uninstallation 

The first method should do the trick. Then close System Preferences, and install the new beta : 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta3/Aerial.saver.zip

Double click the Aerial.saver to install. 

This version has proper support for High Sierra and fixes the outstanding bugs we had there !

**Comment by pws442** [comment]
Thank you Sir,

I will do this Saturday during the wee hours of the morning. My version was installed in June 2016, and I believe the file date was November 2015. Still curious as to how to check the version.


Paul W Schluter
paul@paulschluter.com
Sent from my MacbookPro

On Nov 1, 2018, at 12:50, Guillaume Louel <notifications@github.com> wrote:

Hey Paul

No worries, that was an old version indeed with plenty of known issues. Please uninstall the old version on your wife's Mac, see the instructions here : https://github.com/JohnCoates/Aerial#uninstallation <https://github.com/JohnCoates/Aerial#uninstallation>
The first method should do the trick. Then close System Preferences, and install the new beta :

https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta3/Aerial.saver.zip <https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta3/Aerial.saver.zip>
Double click the Aerial.saver to install.

This version has proper support for High Sierra and fixes the outstanding bugs we had there !

**Comment by glouel** [comment]
No worries, regarding versions, only the most recent ones (starting with 1.4) have the version in the corner, so that's why you missed it probably. 

Nov 2015 is 1.2, which was indeed the last version released until we got the project back up again this september.

**Comment by glouel** [comment]
Yep 1.4.5b4 is good, 1.4.5 finale is also out but there are nearly no changes that you should care about ! Enjoy !
