### ISSUE TITLE
Aerial does not support my software

### ISSUE THREAD

**Issue by babalak** [JohnCoates/Aerial#61]
I am running a OS X El capitan 10.11 and the aerial screensaver does not work for me.

**Comment by JohnCoates** [comment]
Could you try the latest beta? https://github.com/JohnCoates/Aerial/releases/

**Comment by alistairmcmillan** [comment]
@babalak Did you get the screensaver working?

**Comment by babalak** [comment]
Yeah did work and now all works fine.

**Comment by alistairmcmillan** [comment]
Glad to hear it. :)
