### ISSUE TITLE
Feature Request: Mojave live desktop support

### ISSUE THREAD

**Issue by ccharlton** [JohnCoates/Aerial#610]
Can these videos be used for Mojave's new live desktop (day/night) feature?

**Comment by glouel** [comment]
Hi @ccharlton 

Live desktop is just a series of still pictures, maybe a dozen but can be more, that change throughout the day. So there's not much in common in practice. We do support showing day/night videos based on time (see the Time tab) but we can't force Aerial on the desktop for now. 

In previous versions of macOS, you could actually run your screensaver as a desktop picture, (see here https://github.com/JohnCoates/Aerial/issues/37) but this is no longer possible on Mojave. We don't know of a workaround to this yet.

**Comment by glouel** [comment]
So I looked a bit more into it, it looks like in recent versions of macOS, you can no longer put a window at wallpaper level (behind the desktop icons) but you can still have somthing that's "on top" of the wallpaper/desktop icons but behind everything else (dock, menus, all windows)

I'm considering looking at this further, but would probably release this as a separate app if there's interest.

**Comment by LvanProosdij** [comment]
@glouel there is something interesting here : [How to replace Dynamic Desktop with video wallpaper in macOS Mojave](https://appleinsider.com/articles/18/11/13/how-to-replace-dynamic-desktop-with-video-wallpaper-in-macos-mojave)
We could have a look at how VLC does this. Can also ask them, lead developers are friends.

**Comment by glouel** [comment]
Gave it a shot, their version does indeed keep the icons unlike my quick prototype. Might be a swift thing or I missed something. 

I'd suggest referring people who want this feature to using VLC with a playlist of their videos, since it does pretty much what those users want ?

**Comment by LvanProosdij** [comment]
The solution with VLC is a "hack", using a feature of VLC, but the user experience isn't smooth and it also impacts VLC use while desktop mode is active.

People ask : how can I have Aerial as a desktop wallpaper ?
We can answer Aerial is a screensaver not a wallpaper, sorry.
But as 99% of what is required to create an Aerial wallpaper is what Aerial screensaver does (maintaining a list of videos, caching them, playing them, etc.), maybe we can make Aerial both a screensaver and a wallpaper, the wallpaper being an App ?

**Comment by glouel** [comment]
I agree it's a hack. 

As of right now that's the better option for those who want that. Looking at this for a proper implementation is still on my to do list and if I do, I'll check how VLC does it but it's pretty low priority as it's going to take some amount of work and there are other things that I need to address first.

**Comment by ccharlton** [comment]
Something came to mind: Technically, individual frames could be extracted from the video. Say, a day video that's 12-minutes long would offer 12 hourly images, or more if you want to update every 15-30 minutes.

**Comment by glouel** [comment]
> Something came to mind: Technically, individual frames could be extracted from the video. Say, a day video that's 12-minutes long would offer 12 hourly images, or more if you want to update every 15-30 minutes.

I'm not sure that would look good since it would make a bit of a weird motion, but if you want to give it a shot, you can extract said frames with ffmpeg, then use this tool to make the wallpaper : https://github.com/mczachurski/wallpapper

This is very much outside of the scope of Aerial though.

**Comment by ccharlton** [comment]
Agreed about scope. Love 'Aerial' screensaver! Thank you.

**Comment by Valpertui** [comment]
I would be very interested of using Aerial as a desktop wallpaper.  
I find Aerial very soothing and calming and so would love to be able to set is as the background of a secondary or third screen while i'm working on the other(s) ones
