### ISSUE TITLE
'Screen Saver Options' in Preferences won't close while running Mojave

### ISSUE THREAD

**Issue by 28grahams** [JohnCoates/Aerial#614]
Macbook Pro Retina 15in, Mid 2015 running Mojave

The 'Done' button is broken in 'Screen Saver Options' in System Preferences and I perpetually can't close the options or system preferences.

**Comment by glouel** [comment]
@28grahams 
Please make sure you have installed the latest version, this bug has been fixed in 1.4. 

Here's version 1.4.4 : https://github.com/JohnCoates/Aerial/releases/download/v1.4.4/Aerial.saver.zip

**Comment by 28grahams** [comment]
Oops sorry!
