### ISSUE TITLE
Install & Preview work. Otherwise shows a black screen on start

### ISSUE THREAD

**Issue by skiddyrow** [JohnCoates/Aerial#62]
I'm able to install the screen saver and click on preview to view it. However when I start the screensaver, either manually using a hot corner, or wait for it to start, the screen just goes black. I'm on 10.11.1

**Comment by sdecaux** [comment]
I had the same problem. Due to LittleSnitch (network filter). I just had to allow outgoing connections to domain akamai.net for ScreenSaverEngine...

**Comment by dayaki** [comment]
Same problem here. @sdecaux solution fixed it. It was due to LittleSnitch.

**Comment by skiddyrow** [comment]
Thanks! that solved the problem!
