### ISSUE TITLE
Precision of coordinates

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#620]
Aerial 1.4.5
macOS 10.13.6

It occurs to me that the pretended precision of the coordinates returned by Location Services is utterly absurd.

Latitude, for example, is reported to a precision of _eight_ decimal places, or one hundred-millionth of a degree. In other words, about _one millimeter!_

My reported latitude and longitude can each vary by tens of meters or more just by clicking the "Use macOS Location Service to find your location" button at different times, without ever moving my iMac (and even these vastly greater differences make no discernible difference whatsoever in the calculated time of sunrise and sunset).

I realize this is not a bug in Aerial's functionality, and I've no doubt that Aerial is simply displaying the value returned by Apple's Location Services, but now that I've noticed this, it annoys me. **Apple's engineers were clearly not paying attention when they were taught the importance of [significant digits](https://en.wikipedia.org/wiki/Significant_figures) in middle school!**

Could we please round off the display of these coordinates to something credible? Three decimal places of precision _at the most_, I should think: .001 degree is about 110 meters, or about a quarter of a seconds' difference in the time of sunrise and sunset. Reporting any greater precision is meaningless.  :)

**Comment by glouel** [comment]
Haha yeah as far as I remember location services on Mac mostly uses WiFi (through a database of known access points) to get your location. So depending on where you live the precision can vary greatly and you may get different results consecutively.

I’m uneasy about shaving digits though as things may improve (future Mac with cellular, or grabbing location from iPhone etc). I know you can ask for various kinds of precision I’ll have a look if I can find a good way to deal with this.

But nice to have at best 😅

**Comment by SeanMSmith** [comment]
But the point is that even if the _accuracy_ of Location Services improves, pretending anything greater than three decimal places of _precision_, or one-quarter second's difference in the time of sunrise and sunset, is meaningless for our purposes. No one is _ever_ going to notice a difference of two or three _hundredths_ of a second in the time of sunrise or sunset (let alone dawn or dusk), which is the accuracy implied by displaying just _four_ decimal places of precision.

By asserting _seven_ decimal places of precision in longitude, as we are now, we are implying that, even if we only _display_ the times of sunset and sunrise rounded to the nearest second, we can actually _calculate_ sunrise and sunset to an accuracy of 0.00002 second, or two hundred-thousandths of a second, which is quite simply false.

Spurious digits like this irk me because they can easily mislead the careless or uneducated into believing that a much greater degree of accuracy is involved than is actually the case. With the Aerial screen saver, it doesn't really matter, but in other contexts, spurious digits can be dangerously misleading.

Imagine, for example, that a pollster questions seven Americans at random on whether they think the immigrant caravan approaching the southern border of the United States poses a grave danger to our national security, and that three out of those seven random Americans answer that it does.

Now imagine that some news outlets, dividing three by seven, report that "42.857% OF AMERICANS BELIEVE IMMIGRANT CARAVAN POSES GRAVE THREAT TO NATIONAL SECURITY." Now imagine further that some United States Congressmen read those headlines and think "42.857%! Wow, this survey must be really accurate to be so precise! I'd better take this strong current of public opinion into account."

This, of course, is a hypothetical example, but it is precisely the sort of thing that happens all the time, and it is why we should always be alert, and encourage _others_ to be alert, to the pretended precision of spurious digits.

**Comment by glouel** [comment]
Don't get me wrong, I completely agree on principle. I'm simply displaying what the APIs give me at the moment.

I still believe that one should be able to input whatever he wants, so if you have checked your precise position with Apple Maps, you should be able to enter whatever you want and Aerial should not truncate it. I had 3 digits rounding on an earlier version and it was a bad experience. 

As for what Location Services returns that's another story. As of right now I'm getting them raw and don't take into account accuracy. It looks like Apple has some extra parameters for Accuracy here : https://developer.apple.com/documentation/corelocation/cllocation/1423599-horizontalaccuracy

I'll try to see what I can do with that and reduce the digits accordingly to what is returned. But if Core Location says accuracy = 10cm, I completely disagree to rounding to 3 digits in that case, on the principle that it makes no difference for Aerial. That's a step too far in my book independently of the impact on calculations.

Do we agree on this ?

**Comment by SeanMSmith** [comment]
Now that Aerial is using kCLLocationAccuracyThreeKilometers (#663), does it make any sense to continue displaying a pretended accuracy on the order of one millimeter? (One tenth of a degree (0.1°) is 1.7 km.)

**Comment by glouel** [comment]
To be clear, there's a difference between what you ask and what you get, it's merely a suggestion (and on MacOS it has 0 impact). 

I'll move to 3 decimals (110m) as a compromise.
