### ISSUE TITLE
Supporting: I created the list of the videos with thumbnail.

### ISSUE THREAD

**Issue by hidehiro98** [JohnCoates/Aerial#623]
I'm creating this list because loading the movie in settings is really slow (I'm not offensive, I really appreciate guys!).

https://paper.dropbox.com/doc/Aerial-macOS-screen-saver-list--ARLYUjAa1UrRyjC8HPKJv4DBAQ-HvOeL0gNhLpqpIFgmLHaS

**Comment by NightRaider73** [comment]
@hidehiro98 Can you specify what these pictures are suppose to be? Are they suppose here:
![screen shot 2018-11-06 at 10 11 42 am](https://user-images.githubusercontent.com/44180668/48084384-6c283900-e1ac-11e8-80fd-b460592dfd89.png)
Or here:
![screen shot 2018-11-06 at 10 11 52 am](https://user-images.githubusercontent.com/44180668/48084399-721e1a00-e1ac-11e8-95f9-e70ded9905fe.png)

Thank you

**Comment by glouel** [comment]
Hi @hidehiro98 !

Really cool guide ! Because the videos are the property of apple, I'm not sure if taking screenshots is fair use or not, if it is we should definitely link to it as this could help people. Maybe someone knows about fair use around this ? 

Thanks for doing this in any case !

**Comment by hidehiro98** [comment]
Hello @glouel !
Thank you for your reaction! Yes, fair use or not does matter.
If this is in fair use, please link to this!

**Comment by glouel** [comment]
@hidehiro98, version 1.4.6beta1 has 4 new videos : 
- Space, Italy to Asia
- Space, New York night
- Liwa, Liwa Oasis 2
- San Francisco, Golden Gate from SF

You can find that beta here : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta1/Aerial.saver.zip

And more info about the other changes here, I suggest you read before install (you will have to redownload some files) : https://github.com/JohnCoates/Aerial/issues/630

**Comment by NightRaider73** [comment]
@hidehiro98 Could you please update your download 1.4.6 and update your guide please?
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6/Aerial.saver.zip

**Comment by hidehiro98** [comment]
@glouel I updated the list!! Would you update the link URL because URL is changed while the title of the document changing.
https://paper.dropbox.com/doc/Aerial-macOS-screen-saver-list-with-version-1.4.6--AT8JYSGrIHiMF4g2IcZq30lmAg-HvOeL0gNhLpqpIFgmLHaS#:h2=California-to-Vegas

**Comment by glouel** [comment]
@hidehiro98 awesome, updating right now ! Thanks a lot !

**Comment by glouel** [comment]
Closing, @hidehiro98 if you plan to update it just reopen this thread. Thanks !
