### ISSUE TITLE
Missing many new videos

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#624]
1 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#AFA22C08-A486-4CE8-9A13-E355B6C38559
 
2 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#E5DB138A-F04E-4619-B896-DE5CB538C534
3 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#B1B5DDC5-73C8-4920-8133-BACCE38A08DE
4 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#63C042F0-90EF-4A95-B7CC-CC9A64BF8421
5 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#F0236EC5-EE72-4058-A6CE-1F7D2E8253BF
6 http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#72B4390D-DF1D-4D51-B179-229BBAEFFF2C
If you go and watch the videos on the sites you will notice that Apple has provided NEW descriptions for San Fransisco

**Comment by NightRaider73** [comment]
@glouel You have something new to work on:)

**Comment by glouel** [comment]
Great find on the videos thanks, I'll have a look asap to add them :)

and lol about the city, believe it or not I actually don't live far from there, I know that place ;))

**Comment by NightRaider73** [comment]
All you have to do is right click the video (not the links) then select copy video link

**Comment by NightRaider73** [comment]
Also @glouel I only put the other videos that I was 100% sure about you might want to go over every one yourself here: http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#AFA22C08-A486-4CE8-9A13-E355B6C38559
Thank you for all the work!!!

**Comment by glouel** [comment]
Yeah I'll try to have a look and get in touch with Benjamin Mayo when I get back home to see where he found the links in the first place. Thanks !

**Comment by NightRaider73** [comment]
Yeah the fact that it auto picks up the links is amazing, if we could get Aerial to do that..... that would be awesome

**Comment by NightRaider73** [comment]
@glouel What where you planing to do with the new links? Where you planing on creating a new `.Json`, or just add to the existing one.  I think it might be better to make a new `tvOS12.1.Json` Just in case.

**Comment by glouel** [comment]
It depends how they did it. As I said, I'll have a look tomorrow.

**Comment by NightRaider73** [comment]
I know now I did more research on it:) Get some rest so that you can work on it tomorrow.

**Comment by glouel** [comment]
I don’t particularly like being ordered around so I would appreciate that you stop doing that please.

**Comment by NightRaider73** [comment]
Sorry😰😰😰😰😰

**Comment by NightRaider73** [comment]
@glouel I just stubbed upon something weird and good at the same time!!!!!!! It will be a long article but I will explain

**Comment by NightRaider73** [comment]
I decided to try and delete my cache folder including the .json and when I reloaded them there were a TON of extra videos that weren't there before as you can see below compare with yours and try it yourself:
[Screen Recording 2018-11-08 at 10.49.14 AM.zip](https://github.com/JohnCoates/Aerial/files/2564074/Screen.Recording.2018-11-08.at.10.49.14.AM.zip)'

I is a real big mess right now for anybody who downloads Aerial that doesn't already have the files

**Comment by glouel** [comment]
(I'm fairly sure I asked you nicely to start using the Edit button and stop replying to yourself, please consider how MANY notifications you are generating. It's incredibly disturbing, to me and others trying to follow. This will be the last time I'm saying this.)

The json was updated which didn't seem to happen much in the past. 

I'll post an update shortly on how I'll handle this in next versions depending on the difference of content.

**Comment by NightRaider73** [comment]
For the people that might panic put something on the readme for them with the old not updated `.json` so that they don't have to mess with all the duplicates.

**Comment by glouel** [comment]
> Take your time I'm not trying to boss you around:)

I do not know if you are a native english speaker. If not that's ok, but this:

>  put something on the readme

I will not accept. I've been fairly patient with you but I'm done asking nicely. Feel free to ask for something or suggest something. Do not tell me to do something again or I'll either ignore or block you outright. Clear?

**Comment by NightRaider73** [comment]
@glouel Sorry I have offended you and I will just not help anymore.

**Comment by NightRaider73** [comment]
I see why you don't want a code of conduct:

> Our Standards
Examples of behavior that contributes to creating a positive environment include:
Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members
