### ISSUE TITLE
"Screen Saver Options" "Done" button does not work

### ISSUE THREAD

**Issue by NtwkEngineer** [JohnCoates/Aerial#627]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:  Retina MacBook Air 13", 2018
- [ ] macOS version: Mojave 10.14.1
- [ ] Monitor setup:  Built-in display

After installing the screen saver, I navigated to the "Screen Saver Options" button, clicked on the check-box to enable different scenes when on multiple displays, but the "Done" button doesn't return me to system preferences.  I have to force quit system preferences to get out of it.  My changes to the options are saved though.

**Comment by glouel** [comment]
Did you install latest version ? 1.4.5 ? If so make sure you uninstalled the old ones too and are using the correct one (the thumbnail on the left in the screensaver pane should look like earth, not the Golden Gate.

**Comment by NtwkEngineer** [comment]
That fixes it :) Thanks!
