### ISSUE TITLE
Version 1.4.6 and new videos

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#630]
So as pointed, Apple has updated it's tvOS12 json. It mostly replaces the old one and is much larger, going to 44 videos from 33, and brings completely new videos, upgrade a few old ones to 4K (as I predicted they would from TVIdleScreenStrings.bundle) and sadly removes one video (!). While the json is new, TVIdleScreenStrings.bundle is unchanged. And so are the older jsons.

It's however not as simple as just adding new/upgrading videos, there are also "new versions" of the old ones, and misc changes that are sometimes just weird (and messed up some of Aerial's UI, but not core functionality), so I'll try to sum up the changes here and what I'm doing about it: 

New (to Aerial): 
- Space, Italy to Asia : This is new ! It shares similarities with Space, China in the naming convention, might be from the same batch of data. I actually thought at first it replaced China but it does not (more about that one below)
- Space, New York night : This is new too, pretty long video, 5m30, good quality. Way more than just NY but, hey. 
- Liwa, Liwa Oasis 2 : New (has more sky than the other one)
- San Francisco, Golden Gate from SF (@SeanMSmith you'll recognize the descriptions that didn't match with any of our videos here, feel free to suggest a new title as I was massively uninspired, despite just coming back from a work trip to SF)

Upgraded to 4K (yay):
- China, Great wall 2 
- Dubai, Downtown (massively touched up colors)
- Greenland, Ilulissat Icefjord night (massively touched up colors, recroped)
- Honk Kong Victoria Harbour 1 (touched up colors)
- SF, Marin Headlands in Fog
- SF, Bay and Golden Gate
- SF, Bay Bridge
- SF, Fisherman's Wharf

Upgraded to 4K (but):
- China, Great wall 1 : This is a longer version of the 1080p great wall 1 (b6-1), it's 5:36 (instead of 4:00), starts a bit earlier and ends a tiny bit later. I've treated it as a pure upgrade, so it replaces the old one. 

Other changes (a lot of these have color correction, denoising, etc):
- Space, California to Vegas : The videos are bumped to v8 (from v7), same length, maybe slightly denoised, or a very minor tweak to contrast. My eyes are a bit tired but I didn't see a major difference. Changed id.
- Space, China : For some reason, Apple changed the ID of the video, but kept the same files...
- Space Ireland to Asia  : Same thing, Apple changed the ID of the video, same files
- Space, Korean and Japan Night : They didn't fix the name, sorry @SeanMSmith (the files are named correctly though !), but they fixed some macroblocks that stayed fixed on bottom right of screen at the beginning of the video, so yay ! Video files from v17 to v18, changed id.
- Dubai night, Approaching Burj Khalifa : v19, marked as denoised, it's also soooo much sharper (and they tweaked the colors). Much improved version imho. 
- Dubai, Marina 1 : New version, touched up colors
- Dubai, Marina 2 : New version, touched up colors
- Greenland, Nuunsuaq Peninsula : New version, touched up colors
- Hong Kong, Victoria Harbour Night: New version, touched up brightness
- Hong Kong, Victoria Harbour 2 : They actually start the video cropped to the right and pan to the left (!), touched up colors
- Liwa, Liwa Oasis 1 : Touched up colors
- LA, LAX : Touched up colors
- LA, Santa Monica Beach : Touched up colors
- LA, Harbor Freeway : Touched up colors

What I'm doing about it:
- With the new JSON, some of the stuff we built on top of the JSONs on previous versions failed because of the new video IDs (but it didn't crash at least 😅). This is mostly benign as it showed videos without the extra "community" name that we added, and showed a few duplicates, but it picked up the new videos as it should have. All of this is fixed in 1.4.6beta1 which adds the new ids to the community stuff and deduplicate the new videos correctly. Hopefully Apple will not redenoise/color touch all of it's videos every month.

- The **new versions** of the videos are the new default. You may not like the color changes, but the only sustainable way forward for Aerial is to roll with the new versions of the videos when Apple pushes them. I will maintain a list **of videos that gets removed** from rotation so you can still watch and download them (hopefully on the last one), but I will not track all the **old individual versions** of each videos. This will mean that you have to redownload some new videos if you want to have everything (sorry). You can still rename the old videos to the new names if you absolutely hate something but I will not give individual choices on this.

- As I've stated above, because of the removing of "Sahara and Italy", Aerial 1.4.6 will now bundle an extra "missingvideos.json" just for that one. Should Apple move other videos out of rotation, it may become handy and I'll add other missing videos there (as long as they don't outright remove the files, which they didn't do yet for this one)
 
- Because we thought that JSONs rarely if ever changed, I did remove the auto download of the JSON that Aerial 1.2 used to do every time it started with 1.4. Considering that the tvOS 12 JSON is much larger (because of the tar/bundle), this was a pretty good decision but it removed the ability to pick up the new videos should they come (and they did this time !). It's still unclear at which frequency Apple will update the JSON and that may not be tied to a tvOS version (the new json is dated October 30). So I'm introducing a new preference "Check for new Aerial Videos" with "Weekly, Monthly and Never" as options (currently in Cache panel because of space issues, but considering making the panel larger to make it in main panel ?). Also, I'm considering Weekly or Monthly as default (I'll probably have a hidden daily option just for me, or maybe in betas to make sure we know when the next JSON update comes through, will think about that one so we're not caught unprepared). I don't think Never is a good default, even if it may break some stuff in the UI (extra names and dupes), it will not break main functionality and people should expect new videos to be picked up automatically when possible, I think. 

- 1.4.6 will force check for new JSONs the very first time you run it (if it doesn't find the backup folder, see below).

- A backup folder in Aerial's cache will keep a copy of the old files just in case when a new one is picked up. I will checksum the files to look for changes. This will help me track new versions  

Right now I'm still working on this (finishing the backup/redownload) and will post beta1 either tonight or tomorrow.

**Comment by glouel** [comment]
70

**Comment by NightRaider73** [comment]
Thank you

**Comment by glouel** [comment]
Version 1.4.6beta1 : https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta1/Aerial.saver.zip

This version WILL redownload the new tvOS12 manifest so make sure you read 1st post before installing.

**Comment by NightRaider73** [comment]
Is it suggested to clear cache?

**Comment by glouel** [comment]
Nope, no need. It will move your entries.json to backups/

**Comment by NightRaider73** [comment]
As I had in my edit how did you figure out how to get the location services without signing it?

**Comment by glouel** [comment]
It should be signed.

**Comment by NightRaider73** [comment]
I wasn't for me unless it was an error on MacOS

**Comment by glouel** [comment]
Nice catch, I signed the wrong file. New build is at the same place : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta1/Aerial.saver.zip

My understanding is that if you authorized it once on a previous version, new builds will work, signed or not.

**Comment by NightRaider73** [comment]
Okay I didn't really care because I don't use that but in one of your previous articles I think you may have said that so I was just making sure:)

**Comment by owellsjr** [comment]
Not sure about you guys but I’m up to 45 new videos on the ATV4K. I presume I’ll see the second Great Wall of China screensaver on the Mac soon?

**Comment by qwertimus** [comment]
> The new versions of the videos are the new default. You may not like the color changes, but the only sustainable way forward for Aerial is to roll with the new versions of the videos when Apple pushes them. [...] You can still rename the old videos to the new names if you absolutely hate something but I will not give individual choices on this.

This is somewhat disappointing, as many of the new versions are noticeably less sharp than the older versions (@ 1080p H264). For example, the Liwa and China videos show a pronounced difference in visual quality, separate from the compositional changes—which I generally dislike (SF Bay Bridge awkwardly cropped down, for instance).

I understand not wanting to provide direct choices; however, please consider at least moving old versions of videos into a separate folder. Separating old and current videos would make management (swapping, deleting videos) much easier & significantly less frustrating.

**Comment by glouel** [comment]
Yeah video management is something I'll try to add in the next build, I can't reliably track old versions sadly, but I can at least point unused files and move them to a directory.

**Comment by glouel** [comment]
So as pointed, new version of the tvOS12 JSON, again : 

Updated to 4K (yay again):
- Great Wall 3 : Looks about the same visually, but longer, the video lasts 4 minutes now, the added bit is at the end 
- Ilulissat Icefjord (day) : Cropped differently (much less sky), more dramatic colors, same length
- Pu‘u O ‘Umi (night) : Bumped to 4 minutes too, from 2:24, slightly more dramatic colors
- Pu‘u O ‘Umi (day) : Bumped to 4 minutes (!), video starts earlier, tiny color changes
- "Waimanu Valley" : Do I even need to say it ? from 3:12, extra bits at the end, tiny saturation change, and recropped (less sky too)
-  "Laupāhoehoe Nui" : Same length (?!), just a saturation bump on this one

Side note, in previous versions, I swapped Waimanu Valley and  Laupāhoehoe Nui, the names are now  aligned to the descriptions.

- Kohala Coastline : This is getting ridiculous... 4 minutes, extra bits at the beginning, sky/sun severely cropped out, makes it more dramatic
- Victoria Peak : Same length, but someone fell asleep on the saturation slider. It's a bit ridiculous to be honest when you look at both side by side but, oh well...
- River Thames : Bumped FROM 4 minutes to 5:36 (!), extra bits before and at the end, **this will mess with our community descriptions timings**
- River Thames near sunset : Bumped FROM 4 minutes to 4:48, extra bits at the end, should be ok with community descriptions
- River Thames at dusk : Same length, looks about the same too !
- Buckingham Palace : Bumped from 5:36 to 6 minutes, extra bits at the beginning, ** this will mess community descriptions**
- Downtown (LA) : This one is actually shorter, downsized to 8:37, ** this will mess community descriptions**, otherwise they fixed the light balance, it looks arguably much better in my very partial opinion
- Upper East Side : Same same
- Seventh Avenue : Cut to 2:54, removed bits at the beginning (good choice) **this will mess community descriptions**
- Central Park : Maaaaaassively longer, from 4:49 to 8:01 (!), looks like 1:35 extra at the end, and the rest at the beginning  **this will mess community descriptions**

**/New York City is now known as New York**

So that's 16 videos upgraded to 4k which is great. Nearly all the old videos have been upgraded, there's still a few though that I guess will be updated soonish : 
- Hawaii : Honopu Valley
- New York : Lower Manhattan (day)
- 7 San Francisco videos

We've also lost one video in the JSON : 
- Hong Kong : Victoria Harbour 2

I've added it to the missingvideos.json so we're still at 70 videos. 

Files are dated december 5 but they were updated more recently than this. Note that TVIdleScreenStrings.bundle was updated but remain the same size. Possibly some typos or tweaked timings, haven't looked that far yet. 

All of this in beta7 : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta7/Aerial.saver.zip

To force the redownload, delete entries.json and TVIdleScreenStrings.bundle.

**Comment by NightRaider73** [comment]
Thank you again!!

**Comment by glouel** [comment]
Since it was long overdue, I released 1.4.6 finale with those changes.

**Comment by SeanMSmith** [comment]
I updated the community descriptions (#691) for those London and Los Angeles videos that have been re-cropped or re-edited.

The new Victoria Peak video is simply ghastly, but then so was the new Victoria Harbour 2 video from the last round of Apple changes. Is it possible that the HDR versions of these two videos actually look good on an Apple TV? (If they look anything like these SDR versions, then I want to keep _well clear_ of whatever noxious substance the folks at Apple are smoking.)

As for the new Downtown Los Angeles night video, while it may look better to you, I can tell you, as someone who lives only five minutes away, that it looks a lot less like Downtown L.A. I barely recognize these new colors.

I fully understand that it would simply not be feasible to offer version management for individual videos. (Just the thought of trying to track and match different versions of the community descriptions to their corresponding video versions is enough to make one shudder in horror.) But honestly, some of these new versions are downright _ugly!_

**Comment by glouel** [comment]
@SeanMSmith that's awesome, thanks, will be in next build.

I haven't seen the videos on a HDR TV yet, but usually (modern) movie and TV content is massively saturated, so maybe they wanted to align with those expectations ? The color expectations are certainly different on a "calibrated" computer screen though over the years, the color spaces are slowly converging. 

By experience, downconverting HDR content to SDR is hard and something that looks good in 10-12bit, if you linearily scale it down to 8 will look horrible in most cases unless you spend a lot of time working on it. I think it's clear that they either shot in HDR and downconvert it, or mapped to HDR and downconvert that to make the SDR versions with more or less success.   

Version management is a mess because we may not always have the previous JSON and it's a big can of worms. But with the new "move old videos" feature in Advanced tab, at least you can track the changes and move back/rename the files. Since it creates a new folder each day you run that feature, the next time they update the JSON you'll only have the few changed videos in that oldvideos/ folder, so it should be much easier to manage manually if you want.

**Comment by SeanMSmith** [comment]
The new "Move old videos" feature will indeed be a great help (even if only for archiving old videos), as has been the recently-added ability to right-click on videos in the Aerial UI and open them in QuickTime Player, which is tremendously useful when editing community descriptions. These two new features will save a lot of time, so thank you very much!

Of course, with all the edits and re-crops that Apple is doing, if we rename old versions of videos that we like better so that they play instead of the new versions, the updated community descriptions for some of them will be thrown completely out of sync.

Again, I'm not asking you to do anything about that, especially with Apple constantly re-editing these videos (which _for the most part_ has made for welcome improvements). Perhaps some clever and relatively painless way of associating previous community descriptions with renamed videos will occur to you, but I certainly don't expect expect it, and I should hate for you to lose any sleep over it. :)

I strongly suspect that this project is taking far more of your time than you originally anticipated, what with all the lovely new features you've introduced!

**Comment by glouel** [comment]
So a new JSON with new videos, the strings bundle was also updated. 

- Space, Antartica, night : Aurora Australis over Antartica, wiiiilld colors, looks really nice !

![capture d ecran 2019-01-25 a 18 21 16](https://user-images.githubusercontent.com/37544189/51764025-4f790e80-20d4-11e9-9c4f-39fae38a8ec0.jpg)

- Space, North America, night : Moving towards Canada and Aurora Borealis, definitely a new personal favorite, awesome colors: 

![capture d ecran 2019-01-25 a 18 20 12](https://user-images.githubusercontent.com/37544189/51764179-c6160c00-20d4-11e9-89b9-af2a4c7f37d9.jpg)

- San Francisco, Bay and Embarcadero : This looks a lot like Embarcadero, Market street but not the same (check the sea reflections and see below) 

![capture d ecran 2019-01-25 a 18 37 14](https://user-images.githubusercontent.com/37544189/51764209-e2b24400-20d4-11e9-8b3e-cca54460572e.jpg)

Updated : 
- Dubai, Sheikh Zayed Road, Day : colors shifted to red, no comment
- SF, Embarcadero, Market Street : so that one is upgraded to 4K, yay, slightly shorter

Misc stuff : 
- Space, Sahara and Italy : This video was previously removed in november, it's back. Same files but new ids so slightly messed things up, but at least no new redownload.

So as of January 25th 2019, that's 73 videos in Aerial. 

So, in order to get the new videos handled correctly, I'm pushing 1.4.7beta1 today. This build includes Sparkle for auto update. The auto update mechanism is still very early, so things may fail in the future. 

In order to force the download of the new JSON, you can now use the Updates tab : 

<img width="677" alt="capture d ecran 2019-01-25 a 18 49 54" src="https://user-images.githubusercontent.com/37544189/51764675-0924af00-20d6-11e9-899a-2c233c4685d1.png">

Press "Check Now" on top, you may need to restart Aerial afterwards. Let me know how things go for you. 

Version 1.4.7beta1 :

**Comment by lkingjr** [comment]
Installed 1.4.7 Beta on a Mojave 10.14.4 beta install. For some reason the AerialLog.txt file is created to the Desktop instead of in the Cache folder.

**Comment by glouel** [comment]
@lkingjr beta2 fixes this : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta2/Aerial.saver.zip

**Comment by lkingjr** [comment]
Thank you.

**Comment by lkingjr** [comment]
I forgot to mention, Clicking the "Check Now" update button generates an
error.
[image: Screen Shot 2019-01-26 at 10.35.20 AM.png]

**Comment by glouel** [comment]
Can you repost your screenshot through github ? It doesn't work by email. Thanks.

**Comment by lkingjr** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/2839164/51789472-264d9200-2157-11e9-91df-3d2f61e0dc9f.png)

**Comment by lkingjr** [comment]
FWIW, I restarted my Mac and no longer get the error.

**Comment by glouel** [comment]
I think I had an issue with the XML, tried various fixes. Did you actually auto update ?

**Comment by glouel** [comment]
Looks like I fixed it and it seems to work. The update process isn't super nice, it doesn't restart the system preferences panel (I don't think it can) but it's better than not having an auto update at all I think !

**Comment by lkingjr** [comment]
I agree. :o)
