### ISSUE TITLE
Suggestion: Manually check for new .json

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#636]
![screen shot 2018-11-10 at 7 49 29 am](https://user-images.githubusercontent.com/44180668/48303274-2ecdef00-e4bd-11e8-8d38-0821c134cbf3.png)
I have always like to check manually for updates. Is it possible to add a Botton next to the "Check for new videos"?

**Comment by glouel** [comment]
Yep I'll add one, probably not next beta but the one after.

**Comment by NightRaider73** [comment]
Okay, Thanks @glouel

**Comment by glouel** [comment]
It's be based on distance from last check, so it will vary for anyone.

**Comment by NightRaider73** [comment]
Okay thanks for the clarification:)

Subscribe to me on Twitch:
Twitch.tv/NightRaider73

**Comment by glouel** [comment]
Implemented in 1.4.6
