### ISSUE TITLE
Manifest Not Loading

### ISSUE THREAD

**Issue by steken89** [JohnCoates/Aerial#64]
Hi! Bug. Details on the screenshot. I have a Hackintosh. 4600 and HD i3 4370. OS X 10.10.5
![2015-10-29 15 09 02](https://cloud.githubusercontent.com/assets/11692905/10815664/53a47d9e-7e4f-11e5-922d-8a729f5d0aff.png)

**Comment by JohnCoates** [comment]
Do you have Little Snitch installed or are you using a proxy at all?

**Comment by alistairmcmillan** [comment]
No answer after over a year, closing.
