### ISSUE TITLE
Feature request: Disable Night Shift for Aerial

### ISSUE THREAD

**Issue by jackxujh** [JohnCoates/Aerial#644]
With Night Shift, beautiful aerials are shown with a warm yellow hue, which does not work very well with blue sky and many scenery or objects in aerials. It would be great that Aerial allows the user to choose if they would love Aerial to disable Night Shift when aerials are played.

**Comment by glouel** [comment]
Hi @jackxujh I had a quick look but apparently there's no API that lets us temporarily disable night shift, sorry :(
