### ISSUE TITLE
'Screen saver options...' dialog won't open properly

### ISSUE THREAD

**Issue by peterstnsz** [JohnCoates/Aerial#65]
iMac (27-inch, Late 2013), OS X Yosemite 10.10.5 (14F1021)

![screen shot 2015-10-29 at 10 32 09](https://cloud.githubusercontent.com/assets/15378130/10816133/7f2d9e36-7e28-11e5-8f2a-6bc00b426588.png)

**Comment by alistairmcmillan** [comment]
@peterstnsz Did you get the preference window to open correctly?

**Comment by alistairmcmillan** [comment]
Waited a few months, no reply, so closing.
