### ISSUE TITLE
Non-functional gear icon in Videos pane

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#656]
Aerial 1.4.6 beta 3
iMac (Retina 5K, 27-inch, Late 2015) 
macOS 10.13.6

Clicking the gear icon in the Videos pane does nothing.

(This problem was not present in version 1.4.6 beta 2.)

**Comment by SeanMSmith** [comment]
Yes, I did indeed close and reopen System Preferences.

This is 100% reproducible here.

What further information can I give you?

**Comment by dVIAN13** [comment]
hmm... I'm on beta3 and I have access to the button..

<img width="667" alt="screen shot 2018-11-16 at 11 34 48 am" src="https://user-images.githubusercontent.com/22992333/48643100-ac00d480-e993-11e8-8889-7d1f72090322.png">

1.4.6beta3
MacOS 10.14.1

**Comment by glouel** [comment]
> Yes, I did indeed close and reopen System Preferences.
> 
> This is 100% reproducible here.
> 
> What further information can I give you?

That's the thing, I have no idea, this is so weird. 100% sure this is 1.4.6beta3 and not an older version ? I know I sometimes have 2 versions of Aerial in syspref, that can happen when Safari unpacks the zip if you didn't purge your download folder, it might rename and rename the file to Aerial-10.saver, etc

Apart from that, no idea. Will think about it.

**Comment by SeanMSmith** [comment]
Yes, I'm 100% sure this is 1.4.6beta3. 

(I closed System Preferences, deleted Aerial.saver from /Library/Screen Savers, verified that there's nothing in ~/Library/Screen Savers, re-downloaded v1.4.6beta3, reinstalled it, closed System Preferences and then reopened it. Aerial's Screen Saver Options and the Finder both show "1.4.6beta3".)

I even tried deleting Aerial's preferences file, to no avail.

To be precise, when I click on the gear icon in the Videos pane, the gear icon darkens (so it's registering the mouse down event), but no menu pops up (either on mouse down or on mouse up).

(The gear icons in the Text pane both work as expected.)

**Comment by glouel** [comment]
This is super weird, I can't reproduce on either macs. I'll try something for next beta will let you know.

**Comment by glouel** [comment]
@SeanMSmith longshot but give beta4 a try, I reverted a change to the menu although it doesn't make much sense : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta4/Aerial.saver.zip

**Comment by SeanMSmith** [comment]
Sure enough, whatever change you reverted in v1.4.6beta4 corrected the problem. The menu now pops up as expected.

(To confirm, if I reinstall 1.4.6beta3, the problem returns; upon then reinstalling 1.4.6beta4, the problem goes away again.)

**Comment by glouel** [comment]
Ok thanks again for double checking, I really don't get it but hey. As long as it works...
