### ISSUE TITLE
aerials not moving

### ISSUE THREAD

**Issue by samuelgustave** [JohnCoates/Aerial#66]
Hi! The aerials are not moving. Why?

**Comment by abhiklodh** [comment]
true... same here

**Comment by JacquesPienaar** [comment]
same

**Comment by abhiklodh** [comment]
I think instead of streaming the videos from apple, u should provide the downloaded inside the package cos apple's servers are giving us a slow stream....it's due to apple guys

**Comment by abhiklodh** [comment]
U can manually download the vids from the links given in the son file here : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

and then link ur own modified json file to in the code which probably says : 
 
[
   {
      "id" : "b1",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b1-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "London",
            "type" : "video",
            "id" : "b1-2",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b1-3",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b1-4",
            "timeOfDay" : "night"
         }
      ]
   },
   {
      "id" : "b2",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "China",
            "type" : "video",
            "id" : "b2-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b2-2",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b2-3",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b2-4",
            "timeOfDay" : "night"
         }
      ]
   },
   {
      "id" : "b3",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "London",
            "type" : "video",
            "id" : "b3-1",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b3-2",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b3-3",
            "timeOfDay" : "day"
         }
      ]
   },
   {
      "id" : "b4",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b4-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b4-2",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b4-3",
            "timeOfDay" : "day"
         }
      ]
   },
   {
      "id" : "b5",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "China",
            "type" : "video",
            "id" : "b5-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "London",
            "type" : "video",
            "id" : "b5-2",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b5-3",
            "timeOfDay" : "night"
         }
      ]
   },
   {
      "id" : "b6",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "China",
            "type" : "video",
            "id" : "b6-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b6-2",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "London",
            "type" : "video",
            "id" : "b6-3",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b6-4",
            "timeOfDay" : "night"
         }
      ]
   },
   {
      "id" : "b7",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b7-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b7-2",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b7-3",
            "timeOfDay" : "night"
         }
      ]
   },
   {
      "id" : "b8",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b10-4",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b8-2",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b8-3",
            "timeOfDay" : "day"
         }
      ]
   },
   {
      "id" : "b9",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b9-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "London",
            "type" : "video",
            "id" : "b9-2",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b9-3",
            "timeOfDay" : "day"
         }
      ]
   },
   {
      "id" : "b10",
      "assets" : [
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b10-1",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "New York City",
            "type" : "video",
            "id" : "b10-2",
            "timeOfDay" : "night"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "San Francisco",
            "type" : "video",
            "id" : "b10-3",
            "timeOfDay" : "day"
         },
         {
            "url" : "modified link to other vid or local storage",
            "accessibilityLabel" : "Hawaii",
            "type" : "video",
            "id" : "b8-1",
            "timeOfDay" : "night"
         }
      ]
   }
]

BUT the downside will be that u won't automatically get new videos which apple may add after this point of time and to add them u will have to manually edit the son again...

perhaps let apple provide a faster stream which maybe not possible...lol...
 perhaps apple changed their primary place for storing vids...lots of possibilities frnds !

**Comment by dayaki** [comment]
Same here but it seems hitting the spacebar makes it to start moving

**Comment by pitchmak** [comment]
@dayaki Try to run this command in Terminal. It might help.

```
# Auto-play videos when opened with QuickTime Player
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen 1
```

**Comment by alistairmcmillan** [comment]
@pitchmak @dayaki @abhiklodh @JacquesPienaar @samuelgustave 

Try downloading the latest release and caching all the videos.
https://github.com/JohnCoates/Aerial/releases
