### ISSUE TITLE
Video only playing on single monitor

### ISSUE THREAD

**Issue by mr100percent** [JohnCoates/Aerial#661]
#### Description of issue / Feature request

When using the 1.4.6beta3 release, the Screensaver will only play on the main monitor and not the external attached monitor. Other Apple screensavers play on the multiple displays, but using either the **Play Aerials** setting "Mirrored on All Displays" or "Different on Each Display," the second display is blank while the main display shows the Aerial videos. The problem persists on unplugging and plugging in different displays. The only solution is to switch the display to mirror only.

MacBook Pro Late 2013
MacOS 10.14.1
External HDMI monitor

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/2591464/AerialLog.txt)

**Comment by glouel** [comment]
@mr100percent thanks for your report, did you previously use Aerial or was this the first version you installed ? 

I'll have a look if we had a regression.

**Comment by glouel** [comment]
@mr100percent was that the full log ? 

Can you try this maybe to help me check your issue:
- Launch Aerial configuration panel in syspref
- enable mirrored mode (in app, and leave your screens individual in macos)
- only enable cached video (you can do that with the menu below the list, click the gear then "Check only cached")
- enable debugMode (advanced pane, feel free to delete/trim the log)
- close system preference
- launch your screensaver (from a hot corner if you have one set, but please launch from hot corner and not the "preview" button from system preferences)

and attach that log ?

I know it's bothersome but would help. Thanks !

**Comment by nicolevella** [comment]
I'm also experiencing this.
os 10.14.1
MBA Retina 2018

I did the steps above, and heres the log

7:33:01 PM : Location services may be disabled, Night Shift can't detect Sunrise and Sunset times without them
7:33:53 PM : UI debugMode: true
7:34:07 PM : UI logToDisk: true
7:34:25 PM : <AerialView: 0x7f8851c0c070> startAnimation
7:34:28 PM : <AerialView: 0x7f8851c0c070> stopAnimation
7:34:30 PM : <AerialView: 0x7f8851c0c070> startAnimation
7:34:33 PM : <AerialView: 0x7f8851c0c070> stopAnimation

**Comment by glouel** [comment]
That log is awfully short can you post the full one ?

**Comment by glouel** [comment]
@nicolevella @mr100percent 
Sorry, found the bug, the preferences weren't saved correctly because of this PR : https://github.com/JohnCoates/Aerial/pull/649

I'll have a new beta up later today, sorry again.

**Comment by glouel** [comment]
@nicolevella @mr100percent 

Please try this new version, again apologies about the issue : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta4/Aerial.saver.zip

**Comment by nicolevella** [comment]
Works perfectly now for me, thank you!!! no apologies needed, thanks for the amazing work!!!
