### ISSUE TITLE
Amazing work, thank you!

### ISSUE THREAD

**Issue by jarrah31** [JohnCoates/Aerial#672]
I would just like to say thank you very much for the continued development of this amazing screensaver for the Mac. 

I've had this screensaver installed for many years despite it going stagnant, and was keeping an eye on the original "[New Aerial Screensavers](https://github.com/JohnCoates/Aerial/issues/463)" thread for a hopeful update when Mojave was release. I've now had 1.4b8 installed since late Sep as I didn't think any more development would occur, but what a pleasant surprise it was to discover continued active work on this project and a truly fantastic feature set compared to the early version! 

Work Colleagues continue to be drawn to the dual videos I have running over both monitors during the day, so now that you have all the extra videos on here again there'll be even less work being done! :)

Love the detailed location information on the videos, much better than just a single location name.

Thanks!!

**Comment by glouel** [comment]
Thanks for your kind words, it's a big effort to maintain this and keep it going so it's appreciated. If you haven't, the latest beta includes the newest videos, updated october 30th. See more here : 
https://github.com/JohnCoates/Aerial/issues/630

**Comment by jarrah31** [comment]
I've just been reading through your very useful and informative analysis of the latest videos (https://github.com/JohnCoates/Aerial/issues/630), and really appreciate you highlighting the differences. Can't wait to watch these tomorrow! (yep, installed the latest beta)

Just on that, is there an easy way to launch and watch videos from the screensaver options menu, such as double-clicking on a video to open it full screen? If not, perhaps hovering over the video name tells you the cached name so you can easily find it, or a clickable link in the options somewhere? I wanted to watch the videos after reading your analysis on them, but it's not easy to find the equivalent cached file.

b.t.w, I would be happy to buy you a few coffee's via a donation link if you have one!

Thanks!

**Comment by glouel** [comment]
> Just on that, is there an easy way to launch and watch videos from the screensaver options menu, such as double-clicking on a video to open it full screen? If not, perhaps hovering over the video name tells you the cached name so you can easily find it, or a clickable link in the options somewhere? I wanted to watch the videos after reading your analysis on them, but it's not easy to find the equivalent cached file.

Easy, nope, but you can find the video names/path as they play in the AerialLog.txt if you enable logs and debug mode. Definitely cumbersome. But that's a pretty good feature idea. Option clicking a video could show a menu to show in finder or open in quicktime maybe. I'll see what I can do about that. 

> b.t.w, I would be happy to buy you a few coffee's via a donation link if you have one!

Because someone also asked previously, I do have a link in my github profile for this. Don't feel obligated to though.

**Comment by jarrah31** [comment]
Option clicking a video with a menu item to launch it in quicktime would be fab! 👍 

Heading to your profile now, thanks again for your work on this project!

**Comment by glouel** [comment]
Thanks @jarrah31 !

I've added a right click/ctrl click menu on cached videos with a "Open in QuickTime" option. I may add other options there at a later point.  

https://github.com/JohnCoates/Aerial/releases/download/v1.4.6beta5/Aerial.saver.zip

**Comment by jarrah31** [comment]
Thank you very much, it works a treat!! ;)

**Comment by TheMoonDawg** [comment]
I also wanted to chime in and comment on how phenomenal the new updates are. I LOVE the Homebrew support (much easier to keep up to date)!

I've been running the old version for the past year and seeing all the new videos and config options make this app a must have for any Mac owner. I've already swayed a few coworkers to install it.

Awesome work @glouel !!
