### ISSUE TITLE
Feature request : default cache folder to /Library/Cache

### ISSUE THREAD

**Issue by LvanProosdij** [JohnCoates/Aerial#673]
Cache folder should default to `/Library/Caches` instead of `~/Library/Caches` to avoid multiple copies of videos being stores in each user's folder.

**Comment by glouel** [comment]
Yeah that's a good idea. Right now I implemented it as a test build here : 
https://github.com/glouel/Aerial/releases/download/v1.4.6test6a/Aerial.saver.zip

Here's how it works in this build: 
- Look for Aerial in local cache (should be /Library/Caches), if there, use that
- Look for Aerial in user cache (should be ~/Library/Caches), if there, use that
- Create Aerial in local cache, then use that

So new users will default to /Library/Caches. 

You can either move the Aerial dir from ~/Library/Caches to /Library/Caches yourself, or rename the Aerial cache in the first folder to test that the new one is created and used in the right place (you can then move your videos). 

Please try and test this before I release this if you can ;)

**Comment by LvanProosdij** [comment]
Tested since a couple weeks, works perfectly.
This will save precious GB on multi-users Macs.

**Comment by glouel** [comment]
Good. Beta6 has this change now too (was sure it was in beta5 but apparently not, been a while).
