### ISSUE TITLE
Moving Cache Doesn't Delete Existing Files

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#674]
Similar to Issue #532, but not exactly... It appears that if you manually change the location of the Video Cache in 1.4.4 or 1.4.5 the files in the previous location remain and are not either deleted or moved. As a result a folder of ~5GB is left and then duplicated elsewhere on the drive. 

A better option would be to prompt the user to delete the existing cache or to move it when the cache location is changed.

**Comment by glouel** [comment]
That option is now available, you can dedulplicate old videos, see here : https://github.com/JohnCoates/Aerial/issues/532#issuecomment-446655252
