### ISSUE TITLE
Suggestion: Making Backups look cleaner

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#676]
I changed it to this:
![screen shot 2018-11-21 at 9 03 36 am](https://user-images.githubusercontent.com/44180668/48857017-c8728780-ed6c-11e8-9f9b-44f715f7c83f.png)
![screen shot 2018-11-21 at 9 03 59 am](https://user-images.githubusercontent.com/44180668/48857018-c8728780-ed6c-11e8-9ec8-22af7c835026.png)
As you can see the current is the 2018-11-9

I also know that the feature is not out yet but this is just a suggestion.

**Comment by dVIAN13** [comment]
@NightRaider73 I can understand coming from a readability perspective, however I believe the current way of naming folders makes sorting incredibly more useful... without having to sort by modified date/etc...? and if in the future, the need to programmatically manipulate any of the folders arises, the current ones are much easier to handle vs dealing with spaces and commas, etc... just my $0.02..

**Comment by NightRaider73** [comment]
Understood:)
