### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error 99999.)

### ISSUE THREAD

**Issue by stephenhersee** [JohnCoates/Aerial#680]
macOS version: 10.14.2 Beta (18C52a)
Mac Version: MacBook Pro (Retina, 15-inch, Late 2013)
Ariel Version: 1.45 and 1.4.6beta5

After downloading the app, extracting the zip, and then right clicking to open, and accepting the unidentified developer warning, I'm greeted with the following warning: 
The operation couldn’t be completed. (OSStatus error 99999.)
the only option is ok, and then the installer quits. 

Tried downloading with Chrome, Safari and Firefox, and extracting with both Archive Utility and TheUnarchiver and all combinations have the same issue.

**Comment by glouel** [comment]
Hi

This is weird for many reasons, the first one being that after unzipping you are seeing an unidentified developer warning, while the builds are signed (the zips are not which can cause some issues but not this one I'd expect). 

One thing you can try, although I'm not sure that's your issue, to make sure it's not the unsigned zip issue, you can download with Safari, **but**, before make sure that in Safari's Preferences, you have checked "Open safe files automatically" (unsure about the translation, it's the last checkbox in the "General" panel). This way Safari will unzip for you and do it correctly (preserving whatever GateKeeper needs). 

Please try this, make sure that Safari was the one unzipping the file, and let me know if it helps. 

The error you get afterward "The operation couldn’t be completed. (OSStatus error 99999.)" is certainly different too, although some people had it too here a while back : https://github.com/JohnCoates/Aerial/issues/469 

This may also be an issue with SystemPolicy on your machine, please check this link https://discussions.apple.com/message/33636882#33636882 and this one http://hints.macworld.com/article.php?story=20130803041717457

**Comment by glouel** [comment]
Closing this as no answer, feel free to reopen if you still need help
