### ISSUE TITLE
They updated the .json again

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#685]

**Comment by NightRaider73** [comment]
@glouel Yesterday was update day and I guess they updated Hawaii again and New York👎🏻

**Comment by glouel** [comment]
Thanks for the heads up, I'll have a look.

**Comment by NightRaider73** [comment]
It really is just annoying

**Comment by glouel** [comment]
Updated here : https://github.com/JohnCoates/Aerial/issues/630#issuecomment-446372861
