### ISSUE TITLE
Bug with default location

### ISSUE THREAD

**Issue by NightRaider73** [JohnCoates/Aerial#688]
@glouel When clicking the "reset to default" it still resets it to

Users/Library/Caches/Aerial
Hope this helps you👍🏻
![screen shot 2018-12-12 at 8 36 03 am](https://user-images.githubusercontent.com/44180668/49884142-0a7d6f00-fde9-11e8-84c1-b7f85255bae8.png)

**Comment by glouel** [comment]
Thanks for the report, this is as intended though. 

"Default" gets computed as startup, and if your folder is in the old location (user directory), it will consider that as default. Same if global directory.

**Comment by NightRaider73** [comment]
I deleted my Cache and changed it to the new default the clicked the "reset" and it reset it to that.

**Comment by glouel** [comment]
Actually, unless I'm wrong, what's on the left and that you maked is the name of your Mac/Hard drive, and not your user folder. So it's working as intended for you.

**Comment by NightRaider73** [comment]
![screen shot 2018-12-12 at 8 54 20 am](https://user-images.githubusercontent.com/44180668/49885257-96909600-fdeb-11e8-8747-c3d02cf10261.png)

**Comment by glouel** [comment]
What does it show BEFORE you click ?

**Comment by NightRaider73** [comment]
I re-tested and it is fine now.  Thank you again👍🏻
