### ISSUE TITLE
Aerial not working with El Capitan?

### ISSUE THREAD

**Issue by anthonyvandeveen** [JohnCoates/Aerial#69]
![screen shot 2015-10-29 at 14 11 29](https://cloud.githubusercontent.com/assets/13529549/10826156/1a6229ee-7e47-11e5-854b-3d8d71c3c0f3.png)

**Comment by M4Rv** [comment]
For me it's working on 10.11.1

**Comment by JakeBilbrey** [comment]
Same issue.

**Comment by aenaon** [comment]
10.11.1 iMac 2009, black sceen

**Comment by arosenb2** [comment]
Working for me on 10.11.1 MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by rickghome** [comment]
same issue on iMac 27" -

**Comment by rickghome** [comment]
worked for me on imac 27", but only after I updated little snitch to allow a network connection

**Comment by aenaon** [comment]
Second. Little Snitch rule needed disabling.

**Comment by stevechen** [comment]
Not working for me on 10.11.1 MacBook Pro (Retina, 15-inch, Mid 2014). No little snitch installed.

**Comment by ciudilo** [comment]
Disabling Little Snitch fixes black screen but Aerial does not work even in with Little Snitch in silent mode with all connections allowed.

**Comment by ciudilo** [comment]
Little Snitch rule was the source of black screen problem for me as well.

**Comment by JohnCoates** [comment]
I'm trying to track down why that error message shows up, but I haven't been able to get much info from the console logs

**Comment by Qeria** [comment]
The same is happening in my laptop (Macbook Pro Retina, 15inch - Mid 2014) with El Capitan 10.11.1.

**Comment by dave5623** [comment]
I wasn't able to run it because it's not a trusted program. I had to go into my security preferences and there was a button to allow the execution of Aerial.saver. Then it appeared as a screensaver option.

**Comment by JakeBilbrey** [comment]
I was able to make this work for me by installing it manually and right clicking and selecting Opening with System Prefs.

**Comment by alistairmcmillan** [comment]
Closing. OP's problem is caused by Swift bug in OS X.

Workaround is to select Aerial, close System Preferences, re-open System Preferences. Preview should then work.
