### ISSUE TITLE
Screensaver black

### ISSUE THREAD

**Issue by ios11iphone6s** [JohnCoates/Aerial#690]
macOS HighSierra 10.13.3
Hackintosh iMac (27-inch, Late 2013)
FullHD 1920x1080

Installed through brew cask.

![duq0fcmuwaiu5fd jpg large](https://user-images.githubusercontent.com/36934886/49999280-6c420280-ffbc-11e8-9320-ee5ef72c9084.jpg)

**Comment by glouel** [comment]
Hi @ios11iphone6s 

There are bugs with 10.13.3, there's a couple of workarounds but it doesn't work for most people (restarting Syspref with aerial selected and enabling screensaver clock). 

I would highly recommend you upgrade to at least .4 or .6 as this is a MacOS issue. Check this threads for more:

https://github.com/JohnCoates/Aerial/issues/567
https://github.com/JohnCoates/Aerial/issues/433
https://github.com/JohnCoates/Aerial/issues/377
