### ISSUE TITLE
External Monitor

### ISSUE THREAD

**Issue by jimmeh1988** [JohnCoates/Aerial#7]
When using on my MBP 13" 2015 model, with an external monitor, a different video is shown on each of the screens, but only one plays, the other seems to freeze. OSX 10.11.1.

**Comment by derekbjohnson** [comment]
Additional information:  I'm running MBP 13" 2015 with OSX 10.11.1 with 3 monitors.  This issue occurs sporadically and typically only affects 1 of the 3 monitors.  It is not limited to external monitors and has happened on my built-in screen.  It seems to affect some videos more than others and occasionally, the videos will resume after a 10-15 second delay.  When the screensaver begins, all videos play for 1-3 seconds and then one of them will hang.

**Comment by glouel** [comment]
This is old but this should be fixed now.
