### ISSUE TITLE
Stalled Image

### ISSUE THREAD

**Issue by AnderCrafter** [JohnCoates/Aerial#701]
- [iMac (Retina 4K, 21.5-inch, 2017) ] Mac model:
- [ 10.14.2] macOS version: 
- [ Internal] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

> 20:07:21 : <AerialView: 0x7fc9b5726620> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x60000351be40, asset = <AVURLAsset: 0x60000351bdc0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/DB_D011_C009_4K_SDR_HEVC.mov>>), userInfo = nil
20:07:57 : <AerialView: 0x7fc9b544dd00> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x60000352b2a0, asset = <AVURLAsset: 0x60000352b2e0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A011_C003_DGRN_LNFIX_STAB_v57_SDR_PS_20181002_SDR_4K_HEVC.mov>>), userInfo = nil
20:47:13 : <AerialView: 0x7fc9b544dd00> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x60000352b2a0, asset = <AVURLAsset: 0x60000352b2e0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A011_C003_DGRN_LNFIX_STAB_v57_SDR_PS_20181002_SDR_4K_HEVC.mov>>), userInfo = nil
20:49:19 : <AerialView: 0x7fc9b544dd00> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x60000352b2a0, asset = <AVURLAsset: 0x60000352b2e0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A011_C003_DGRN_LNFIX_STAB_v57_SDR_PS_20181002_SDR_4K_HEVC.mov>>), userInfo = nil

Error, when playing there is always a stalled screen,
files are downloaded
{{Replace this}}

**Comment by glouel** [comment]
Hi, sorry about that issue.

Reading the log, it looks like files may not be available offline, see this : 

```
<AVURLAsset: 0x60000352b2e0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A011_C003_DGRN_LNFIX_STAB_v57_SDR_PS_20181002_SDR_4K_HEVC.mov>>
```

If you are really loading files from disk, you should see something like this : 

```
16:29:07 : <AerialView: 0x10140b3c0> observing current item <AVPlayerItem: 0x60000000caa0, asset = <AVURLAsset: 0x60000024a9c0, URL = file:///Library/Caches/Aerial/comp_HK_H004_C001_PSNK_DENOISE_v14_SDR_PS_FINAL_20180731_SDR_4K_HEVC.mov>>
```

I'd suggest you double check that you have downloaded the file in the correct format (4K HEVC). In the main UI, you can change the "Preferred video format" from 4K HEVC to another, you should see the UI updates itself on the left showing whether you have the files cached or not (there are many). 

If for some reason you have the files (about 70 HEVC files off the top of my head) and still see streaming, I'd need to see the log further up.

**Comment by AnderCrafter** [comment]
Ok, i will check if i am back from School, said it to download everything, it should be finished by now

**Comment by AnderCrafter** [comment]
Ok it works, thank you

**Comment by AnderCrafter** [comment]
ok it works
