### ISSUE TITLE
2018 MacBook Air Issue

### ISSUE THREAD

**Issue by murdockrb** [JohnCoates/Aerial#703]
I looked through current and closed issues with no success. I have a new 2018 MacBook Air with Mojave up-to-date. Install latest 1.4.6 trying both current user and all users. Can initially see the Aerial in list of screensavers but soon all screensavers are blanked out. Deleting the Aerial restores the other screensavers. I have quit System Preferences when installing, tried rebooting, deleted any caches, etc. This screensaver works successfully on other MacBook pros and MacBook Airs (albeit earlier versions of the Mac OS).

Suggestions?

<img width="626" alt="screen shot 2019-01-23 at 2 11 02 pm" src="https://user-images.githubusercontent.com/46973470/51640650-f3b65600-1f18-11e9-863e-a027162388b4.png">
<img width="640" alt="screen shot 2019-01-23 at 2 11 20 pm" src="https://user-images.githubusercontent.com/46973470/51640663-fa44cd80-1f18-11e9-9d33-167d7413a745.png">

**Comment by glouel** [comment]
Hey @murdockrb 

Sorry about that, can you look at this post https://github.com/JohnCoates/Aerial/issues/681#issuecomment-443729062 and paste the crash log so I can have a look at it ? Thanks !

**Comment by murdockrb** [comment]
[Crash Log.txt](https://github.com/JohnCoates/Aerial/files/2793807/Crash.Log.txt)
Thanks here is the log

**Comment by murdockrb** [comment]
Thanks for the reply. I've uploaded the Crash Log to the issue. Hopefully there is no personal information. I'm not that knowledgeable about them.

Thank you!!

________________________________

**Comment by glouel** [comment]
Thanks for this, I'll have a look later today and get back to you. To answer your question, yes, crash logs are anonymized. More information here on Privacy section if you want to know more : https://developer.apple.com/documentation/os/logging#overview

**Comment by glouel** [comment]
The log isn't straightforward but it does look like some path issue (did you change cache location at some point ?), sounds similar to this one : https://github.com/JohnCoates/Aerial/issues/696

Could you remove Aerial.saver (in both locations, see readme for more info on removing them) and install this test build : 
https://github.com/glouel/Aerial/releases/download/v1.4.7test5/Aerial.saver.zip

It may work outright, but most importantly it will generate an AerialLog.txt on your Desktop. If this version fails, please attach that file which should help me diagnose your issue.

Also, can you let me know if you aren't behind a firewall/proxy, or have some kind of antivirus installed ?

Thanks !

**Comment by murdockrb** [comment]
And yes, initially I tried to make the cache location an external thumbdrive.

________________________________

**Comment by glouel** [comment]
I see. If you configured a path that didn't exist (removed thumbdrive), old versions would have had an issue. You didn't comment on whether the test build fix the bug for you ?

**Comment by murdockrb** [comment]
No it did not. I've removed all old versions based on the read me.

Sent from my iPhone

On Jan 30, 2019, at 9:33 AM, Guillaume Louel <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. If you configured a path that didn't exist (removed thumbdrive), old versions would have had an issue. You didn't comment on whether the test build fix the bug for you ?

**Comment by glouel** [comment]
Sorry but I'm not sure I understand, or you didn't paste the correct log as everything works there. Please delete the AerialLog.txt on your desktop, and launch Aerial from the System Preferences until it crashes, and paste that AerialLog.txt from your desktop (please also try to use Github UI, attachements by mails doesn't always work). 

Thanks

**Comment by murdockrb** [comment]
Good news. When I tried again today, it now appears to be working successfully! Not sure how or why but the System Preferences screensaver screen is no longer blank. Thank you for your help!

**Comment by glouel** [comment]
Good to know. It's quite possible that the first time it still failed but recovered afterwards. FYI, the fix is also in the public 1.4.7 betas should you wish to install them, see latest version here : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta3/Aerial.saver.zip
