### ISSUE TITLE
1.4.7beta1 json update issue

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#704]
Hello @glouel! great work at keeping this updated!

I think I may have found an issue... I went to the updates tab and clicked to check for json update button.. the button never came back to clickable and I didn't have any new videos available to download in my main list... log says total processed 69 videos.. also, the button doesn't become usable again until I close out Aerial and got back into the updates tab.

let me know if you need anything else

<img width="658" alt="screen shot 2019-01-25 at 10 33 08 am" src="https://user-images.githubusercontent.com/22992333/51765490-c5f21e00-208c-11e9-8481-71b798709f67.png">

[AerialLog.txt.zip](https://github.com/JohnCoates/Aerial/files/2797361/AerialLog.txt.zip)

**Comment by glouel** [comment]
Hey @dVIAN13 

The button thing is normal in this beta, I had to rush it because of the new videos. Did you close and reopen the control panel ? The list should update then as far as I remember.

**Comment by dVIAN13** [comment]
@glouel Yes, I have opened/closed a few times to see if I could get it to update... 

here's is how my folder looks as far as recently updated files..
<img width="629" alt="screen shot 2019-01-25 at 10 42 11 am" src="https://user-images.githubusercontent.com/22992333/51765887-f1c1d380-208d-11e9-8cd6-82d596fd8dd5.png">

**Comment by glouel** [comment]
@dVIAN13, can you look at the size/date of your entries.json ? This is the new one : 

![capture d ecran 2019-01-25 a 19 44 19](https://user-images.githubusercontent.com/37544189/51766004-b6e58d00-20d9-11e9-9d9e-6551103f1409.jpg)

**Comment by dVIAN13** [comment]
here you go.. :)

looks like it did not update... 

<img width="265" alt="screen shot 2019-01-25 at 10 46 47 am" src="https://user-images.githubusercontent.com/22992333/51766104-8c221700-208e-11e9-8846-e63df6f4ae6f.png">

**Comment by glouel** [comment]
Did you fully close and restart System Preferences ? In any case, just delete entries.json, it should redownload it and you'll get the new file. Please let me know how it goes !

**Comment by dVIAN13** [comment]
I had closed completely.. a few times. deleting/moving it out of the folder worked...

**Comment by glouel** [comment]
Ok I'll check the button code, maybe something didn't work. I'll update the 1.4.7beta1 release info thanks !

**Comment by dVIAN13** [comment]
also, my system was hung for a few seconds initially after opening the preference pane. It then popped the enable auto update window.. Not sure if my system is just maxed out of RAM right now, or if it was doing something...

**Comment by glouel** [comment]
The sparkle initial check should not hang things, could be specific to your system. I'll keep an eye open if other people complain about it ! If you manually click the second button, it should tell you you are up to date. 

I've updated the release note to add the mention to delete entries.json.

**Comment by glouel** [comment]
This is fixed in beta 3 now 👍
