### ISSUE TITLE
Graphics don't load on 2012 MacBook Pro

### ISSUE THREAD

**Issue by VictorGav** [JohnCoates/Aerial#71]
Hi, are there specific graphics hardware requirements for Aerial?

I've downloaded and installed it on my:

MacBook Pro (Retina, 13-inch, Late 2012)
with
Processor: 2.9 GHz Intel Core i7
Memory: 8 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB
OS X El Capitan 10.11.1 (15B42)

It shows up in my Screen Saver Preferences pane, and the preview works there as expected.

But when I try to invoke the screen saver by using a hot corner, the screen just goes black and the video never loads. Makes me wonder if my video hardware is insufficiently study.

Thanks, Victor

**Comment by brianpattison** [comment]
I'm not using a hot corner, but I'm having the same issue with the exact same setup. The preview works, but when the screen saver kicks in, I just get a black screen. It **works** on my Mac Mini, which has the same graphics.

Doesn't work on my MacBook Pro:

<img width="263" alt="screen shot 2015-10-29 at 9 44 24 pm" src="https://cloud.githubusercontent.com/assets/124570/10837356/93588822-7e86-11e5-94ae-febab5aeadcf.png">

Works on my Mac Mini:

![screen shot 2015-10-29 at 9 50 26 pm](https://cloud.githubusercontent.com/assets/124570/10837422/4cefeeba-7e87-11e5-8058-7a97e6b4a2f3.png)

**Comment by JohnCoates** [comment]
Looking into it, thanks for the heads up

**Comment by JohnCoates** [comment]
Could you try the latest beta? Also, if you have little snitch installed try disabling it https://github.com/JohnCoates/Aerial/releases/

**Comment by brianpattison** [comment]
@JohnCoates Good call. Worked for me after disabling Little Snitch without installing the latest beta. Thanks!

**Comment by VictorGav** [comment]
Yay! Worked for me too. Then I went into Little Snitch and allowed incoming and outgoing connections to edgesuite.net and Aerial worked with LS turned back on.
Thanks!

**Comment by JohnCoates** [comment]
Okay awesome! I'll add a troubleshooting section to the readme that covers this.
