### ISSUE TITLE
Feature Request: Only play on external displays

### ISSUE THREAD

**Issue by alekplay** [JohnCoates/Aerial#718]
It'd be nice if I could specify the areal to _only_ be displayed on external displays. Currently the options are:

- Only on Main Display
- Mirrored on All Displays
- Different on Each Display

However many, myself included, have our desks set up in a way that the external displays are the main feature-point. Given the size difference between the external displays and the main display, the entire setup looks odd when you have the video playing on all of them. It'd be nice if I could specify it to only play on the external displays, keeping the main display black.

I realize I could adjust my laptop's settings to switch the _main display_ to the external one, but for practical purposes I use the built-in screen as the main display. The only time I want this to switch is during the screen saver.

**Comment by glouel** [comment]
Hey @alekplay 

So, I think that right now we can only distinguish "main" and "secondaries" as defined by which one you set as main in Sys Pref. I could probably add "Only on Secondary Displays" as an option though. Will get back to you on this.

**Comment by glouel** [comment]
@alekplay can you give this build a shot and let me know if that works for you : 
https://github.com/glouel/Aerial/releases/download/v1.4.7test9/Aerial.saver.zip

**Comment by ccharlton** [comment]
This is gonna be nice. :)
