### ISSUE TITLE
Request: Ability to check/uncheck all.

### ISSUE THREAD

**Issue by fl0gic** [JohnCoates/Aerial#722]
It'd be nice to be able to check and uncheck all videos in one click, as well as having this for each specific category.

For instance, I was trying to show off a new Antarctica screensaver, and I went through and unchecked each video by hand until I only had that one to guarantee I would get it (I later found out that I can right click to open in QuickTime, but this would still be useful).

**Comment by glouel** [comment]
Hi @fl0gic 

There's a button at the bottom at the list that pops an action menu, exactly for this purpose.
