### ISSUE TITLE
System Preferences crash

### ISSUE THREAD

**Issue by kaedys** [JohnCoates/Aerial#725]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- **Mac model:** MacbookProc14,3 (15-inch, 2017, the one with the new touch strip)
- **macOS version:** 10.13.4
- **Monitor setup:** Laptop plus two 4k external monitors connected via USB-C -> HDMI adaptors

**If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).**
Cannot access the application to adjust these settings

#### Description of issue / Feature request
Clicking on Aerial in the Screensaver section of System Preferences instantly crashes System Preferences.  Things I've tried:

- Ensuring the file is not being blocked by the file shield.
- Ensuring the URLs cited in [this related issue](https://github.com/JohnCoates/Aerial/issues/325#issuecomment-281629286) are not being blocked by my corporate firewall.
- Installing via Homebrew and via direct download (with uninstall in between, issue present in both)

These two installs are the only times Aerial has ever been on my system.

[aerial crash report.txt](https://github.com/JohnCoates/Aerial/files/2876890/aerial.crash.report.txt)

**Comment by glouel** [comment]
@kaedys very sorry about that. 

Some random things to try and fix your issue : 

- Just so I know, did you also try the beta or not ? The betas are not available through homebrew, here's the latest version (it does contain some important crash fix, although maybe not for your issue) : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta5/Aerial.saver.zip 

- Can you look into /Library/Caches to see if there's an Aerial folder ? If so can you list it's content ? If not, can you check ~/Library/Caches for the Aerial folder too ? If you can find the folder in either place, can you try creating that folder in one place or the other ? 

That should narrow it down a bit if you can answer these. Thanks !

**Comment by kaedys** [comment]
Did both, I had not tried the beta, and there was no cache directory.  Probably should have done them separately, but _one_ of the two appears to have worked.  Much appreciated.

**Comment by glouel** [comment]
Ok, in theory 1.4.7 will try to recreate that directory if it's missing, so could have been that. Thanks for following up !
