### ISSUE TITLE
ScreenSaverEngine spawns multiply and lockscreen login do not work

### ISSUE THREAD

**Issue by kaloprominat** [JohnCoates/Aerial#726]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini Server (Late 2012)
- [ ] macOS version: 10.12.6 (16G1618)
- [ ] Monitor setup: DELL U2414H

If appropriate, please enable `Debug mode` a
nd `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/2884139/AerialLog.txt)

#### Description of issue / Feature request

If i leave my mac for a day or more, when i try to login to lock screen, locksceen by itself disappears, but Aerial video continue playing. If i try to check screensaver processes from ssh, i see multiple ScreenSaverEngine instances. And count of them grows with time, like this:

`ps aux | grep -i screensaverengine"

user-osx:
    user           27909   4.4  1.1  2740828 176972   ??  S    Tue03AM  77:51.52 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           57142   4.0  0.5  2644072  91652   ??  S     4:17PM  45:25.81 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user            5189   3.7  1.1  2783996 181856   ??  S    Mon05PM 105:04.92 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           84507   3.6  0.6  2695824 100716   ??  S     5:04AM  19:37.44 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           54755   3.6  0.5  2657952  90000   ??  S     3:36PM  46:53.89 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           56911   2.7  0.5  2646056  89120   ??  S     4:10PM  46:17.15 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           60549   2.7  0.5  2638928  90052   ??  S     5:34PM  42:20.02 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user            3421   1.8  0.5  2634472  90276   ??  S    Mon04PM 103:09.52 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user            3736   1.6  0.5  2624796  89840   ??  S    Mon04PM 102:01.44 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           46134   1.6  0.5  2629204  88240   ??  S    Tue12PM  53:54.97 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           62057   1.3  1.0  2717576 172732   ??  S     6:13PM  40:09.65 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user            2495   1.1  0.5  2631732  91956   ??  S    Mon04PM 102:59.59 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user            3359   0.8  0.6  2629036  94748   ??  S    Mon04PM 102:34.52 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine
    user           56277   0.7  0.5  2630468  88864   ??  S     4:00PM  45:58.79 /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine`

**Comment by glouel** [comment]
Hi @kaloprominat 

This is indeed pretty bad, sorry about that. This is the first report of something like this so there might  be something specific to your system (OS version/video driver or something). 

In the AerialLog.txt, I can see new instances popping up too, which is super weird. It's about once an hour, but can be happening more frequently. Can you answer these questions so we can see if we can resolve that issue : 

- Can you tell me exactly how you setup your energy saving, are you allowing the screen to shut down or not (I would assume not) ?
- Do you power off your screen while the screensaver is on or before launching it ?
- Can you look for crash logs in Console.app (see here for more details : https://github.com/JohnCoates/Aerial/issues/681#issuecomment-443729062 )
- What kind of background tasks are you running (dont need precise details), but are any using the GPU ? Are you running Photos with iCloud backup enabled ?
- Can you check what the video acceleration tooltip reports (click the ? button next to the video mode selection on main panel) ? 

My first guess was some crash with the video driver/acceleration that breaks, but it might be more on the system side.  Here's an example from your logs : 

```
2:19:58 PM : <AerialView: 0x7fb05658f160> playing video (OFFLINE MODE) : file:///Users/pkond/Library/Caches/Aerial/comp_A105_C003_0212CT_FLARE_v10_SDR_PS_FINAL_20180711_SDR_2K_AVC.mov
...
2:20:18 PM : avInit1
2:20:18 PM : <AerialView: 0x7fdc16c00380> AerialView setup init
```

So at 2:19:58 old instance (0x7fb05658f160) starts a video for 3:30 length, but at 2:20:18 a new instance starts and starts running (0x7fdc16c00380).

Yet your old instance will keep going : 

```
2:23:29 PM : <AerialView: 0x7fb05658f160> played did reach end
```

So the old instance played the video till the end. So in a sense that instance is still running correctly, but they are stacking up as you saw. 

In a system sense, Aerial is just a plugin to ScreenSaverEngine, we have 0 control on how many instances are running (there can be multiple if multiple screens), when they are started/stopped, nothing on lifecycle, it's out of our control. Baring the questions I ask above, I think digging more in Console.app would be the best bet to find your issue. 

Thanks !

**Comment by kaloprominat** [comment]
I'm sorry for late answer. I've figured out that this behaviour occurs with any screensaver on my machine. So i would make a conclusion, that this issue is not relevant to Aerial screensaver. Sorry for disturbing.

**Comment by glouel** [comment]
> I'm sorry for late answer. I've figured out that this behaviour occurs with any screensaver on my machine. So i would make a conclusion, that this issue is not relevant to Aerial screensaver. Sorry for disturbing.

No worries, thanks for following up on this. This might just be a 12.6 issue, you should probably look if there's not a newer point update.
