### ISSUE TITLE
Not compatible with Google+ Featured Photos screensaver

### ISSUE THREAD

**Issue by BigChickenInc** [JohnCoates/Aerial#730]
### System Info
Mac model: MacBook Pro 13-inch, 2018
macOS version: 10.14.4 Beta 
Monitor setup: None (no plug or casting used)

#### Description of issue / Feature request
I cannot have both the Google+ Featured photos screensaver and the aerial screensaver installed at the same time, I can switch between them by reinstalling the one that breaks, which breaks the other. (They are both up to date)

**Comment by glouel** [comment]
Hi @BigChickenInc 

Never heard of "Google+ Featured photos screensaver", can you provide me a link (wasn't Google+ killed by Google ?) ? 

Also can you give me more details about what "breaks" ? What do you see with Aerial when that happens, what kind of breakage are we talking about ? Also, crash logs ?

Thanks !

**Comment by BigChickenInc** [comment]
https://plus.google.com/featuredphotos

this is not necessarily something that needs to be fixed, I just figured that you would want to be made aware of the issue because it might lead to your screen saver being incompatible with a number other screen savers too, this is just the one I found. Thank you for the help 😄

**Comment by glouel** [comment]
@BigChickenInc thanks !

However let me reiterate : "Also can you give me more details about what "breaks" ? What do you see with Aerial when that happens, what kind of breakage are we talking about ? Also, crash logs ?"

That would be helpful to have an idea of what the "incompatibility" is. Thanks a lot.

**Comment by baldgzr** [comment]
In system preferences, screen savers with Aerial selected a message appears 'the screen saver cannot be used with this version of macOS'. Deleting the Google+ screen saver removes the error and all works OK. Very odd!?

**Comment by glouel** [comment]
@baldgzr, can you please try this workaround and let me know ? It might be because it's 2 swift screensavers:

"You cannot use the Aerial screen saver with this version of macOS." error: Select Aerial, close System Preferences with Aerial still selected, re-open System Preferences and Aerial should now work.

Let me know if that works or not ?

**Comment by baldgzr** [comment]
That works, the error moves to the Google+ screen saver. repeating the process will enable the screen saver selected when System Preferences is closed.

Cheers

**Comment by glouel** [comment]
@baldgzr thanks a lot for checking ! I know it's not the most convenient workaround but that's the best we can do. Things will get better possibly with Swift 5 and ABI stability, should everyone update their screensavers. 

@BigChickenInc please see the last 2 comments about the workaround for your issue. Thanks again to both !
