### ISSUE TITLE
Feature request: specify which displays show screensaver

### ISSUE THREAD

**Issue by ryan-madrona** [JohnCoates/Aerial#732]
Hello, in the options you have Play Aerials: 
- different on each display
- mirrored on all displays
- only on main display

Would it be possible to specify which monitors it plays on?

Reason being, in my case I have a 2012 Mac mini that only supports 2 video outputs, but I have a 3rd display connected via a USB to HDMI converter. It's laggy/low frame rate and doesn't look good with a video playing. It's nice having different aerials across all multiple displays but is ruined by the choppy 3rd one. Would be great to just have it on 2 of the 3.

Great software, thanks!

**Comment by glouel** [comment]
Hi @ryan-madrona 

So right now, we don't detect individual monitors, I'm not sure we can do that within the boundaries of the screensaver, I'll have to check. 

What we can do right now is differentiate the first one vs "all the others" which is what we implement (there's also a new everything but main display in latest beta).

**Comment by JayHoltslander** [comment]
I thought I'd submitted the same request but can't find it so... +1

**Comment by glouel** [comment]
Just a quick heads up, after a lot of fighting with the APIs, it looks like this is doable, although quite convoluted. So tentatively put for next big release, 1.5.0.

**Comment by ryan-madrona** [comment]
That is great to hear, thank you!

**Comment by glouel** [comment]
This is what it looks like now, will hopefully put a beta out today and update here. You'll have to reconfigure your displays settings as the old ones will be lost in the process :

![Capture d’écran 2019-05-10 à 16 58 40](https://user-images.githubusercontent.com/37544189/57536761-260f8600-7345-11e9-9233-fae3e788a502.jpg)

Display selection (all, main only, sec. only, manual selection) is now independent from viewing mode (independent, mirrorred, and maybe a new one) which makes a lot more sense.

**Comment by glouel** [comment]
Beta is up, I would very much appreciate reports. Please check the release note too, you may experience issues. I'm very much interested in reports also about the new "spanned" viewing mode which allows you to span an Aerial on your displays. This *should* theoretically work with a disabled screen too, although I wasn't able to test it here so feedback welcome. 

![Capture d’écran 2019-05-10 à 18 20 39](https://user-images.githubusercontent.com/37544189/57542048-d040db00-7350-11e9-9aa3-ac191d4e1434.jpg)

https://github.com/JohnCoates/Aerial/releases/tag/v1.4.99beta1

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0

**Comment by ryan-madrona** [comment]
Been testing this for a bit and it seems to work quite well, thanks!
