### ISSUE TITLE
Feature request: 24h hour format

### ISSUE THREAD

**Issue by jahirfiquitiva** [JohnCoates/Aerial#734]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 2017
- [x] macOS version: 10.14.4
- [x] Monitor setup: Just laptop screen

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Can you please add support for 24h hour format? So instead of showing something like `10:00 pm` it shows the hour like `22:00`

Thanks in advance!

**Comment by glouel** [comment]
> Can you please add support for 24h hour format? So instead of showing something like `10:00 pm` it shows the hour like `22:00`
> 
> Thanks in advance!

We already do that, the time format depends on whatever you set in your MacOS regional settings. You can enable 24h mode there and Aerial will comply.

**Comment by jahirfiquitiva** [comment]
You're right. Sorry, I didn't know this.
