### ISSUE TITLE
Downloads keep disappearing

### ISSUE THREAD

**Issue by jahirfiquitiva** [JohnCoates/Aerial#736]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 2017
- [x] macOS version: 10.14.4
- [x] Monitor setup: Display only

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Hello

I recently downloaded all videos I wanted the screensaver to use, because I didn't want them to be streamed/cached every time as they looked really slow and ugly.

After downloading them, they worked fine enough for a day.

Then when I started using it again, noticed a huge lag in the videos, and so I went and checked the screensaver settings, just to notice all the selected videos appeared as if they were not downloaded already.

This is annoying tbh. What is the "Download" feature for if not to use the downloaded videos and instead making me download them every time I want to use the screen saver? :confused:

**Comment by glouel** [comment]
Hi

Aerial never deletes anything. Depending on your installation, videos are downloaded either to /Library/Caches/Aerial or ~/Library/Caches/Aerial. You can see the current path in the Cache tab of the preference panel. 

I suggest you check both, and make sure you didn't manually change the cache storage path. Changing the path doesn't move the videos. 

If you haven't, I'd check if you have some app that cleans MacOS's caches periodically. Maybe if you were low on disk space (the whole set of videos is huge, in tens of GB), MacOS may have prompted you to wipe caches to reclaim space (I'm not sure it does it if not prompted). If so, that's your explanation. 

You can manually set another path, outside of the caches folders, if you wish in the aforementioned tab if you'd rather keep cleaning your cache.

**Comment by jahirfiquitiva** [comment]
Yep. You're right. I didn't realize that. Thanks for the information
