### ISSUE TITLE
Aerial causes immediate logout in latest macOS 10.14.5 Beta

### ISSUE THREAD

**Issue by owellsjr** [JohnCoates/Aerial#738]
### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 2017 MacBook
- [ ] macOS version: 10.14.5 Beta (18F108f)
- [ ] Monitor setup: LG 27UD88 external and bull-in Retina display

Since updating to the latest macOS 10.4.5 beta I've noticed that every time the Aerial screensaver launches it immediately shuts down all running apps and returns me to the login window. Not a kernel panic. Not a reboot. Just an immediate logout. I went into System Preferences and switched to a built-in screen saver and invoked it and it worked as expected. So it appears something about Aerial isn't playing nicely with the latest beta version of macOS .

**Comment by glouel** [comment]
Ouch, that's not good. I'm also on the beta but haven't seen that. Can you confirm which version of Aerial you are using ?

**Comment by owellsjr** [comment]
I was on Aerial 1.4.7 beta 3 when I first noticed it but I figured I should update to the latest Aerial 1.4.7 beta 6 to see if that would fix it but no dice.

**Comment by glouel** [comment]
Thanks I'll try to reproduce. Does it also happen if you start Aerial with hot corners ? 

If you are willing, do you think you could look into Console.app to see if there's a crash log ? I mentionned how to do that in this post (around the end, ignore the uninstall stuff) https://github.com/JohnCoates/Aerial/issues/737#issuecomment-480835738

**Comment by owellsjr** [comment]
It definitely happens when I use hot corners since I routinely do that to lock my machine when I leave my desk. I'm not sure if it happens when the screensaver invokes itself after the set time of inactivity. And there's nothing in Console in the User Reports folder with "com.apple.preference.desktopscreeneffect.screeneffects.remoteservice" in the middle column.

**Comment by glouel** [comment]
Ok thanks for confirming all this ! This definitely does not happen here on my iMac 2015 with the same macOS, so I'm wondering if this could be a video driver issue with video decoding hardware acceleration ? 

If you feel like it, could you go to Aerial's cache folder (/Library/Aerial/Caches or ~/Library/Aerial/Caches unless you changed it) and try playing those videos with quicktime ? 

I'll try to think of what could be happening, but it's likely that it's more on system's side than on ours. Again, thanks for reporting this.

**Comment by owellsjr** [comment]
I tried about 10 random videos in ~/Library/Caches/Aerial and they all played in QuickTime without incident.

**Comment by glouel** [comment]
Ok that was worth a shot, thanks I'll keep monitoring this and keep you posted.

**Comment by owellsjr** [comment]
So remember when macOS Mojave 10.4 Beta 4 was released and things went off the rails with Aerial? #464 Distorted display followed by a kernel panic?

And the workaround was to check the **Show with clock** option to get it to function? At least until Beta 6 was released which resolved that issue. Well I decided to try that workaround and lo and behold ... Aerial runs as expected and doesn't immediately log me out. Go figure. See my system specs below. Hope this helps!
<img width="250" alt="Screen Shot 2019-04-10 at 7 19 07 PM" src="https://user-images.githubusercontent.com/20402469/55922836-98673c00-5bc8-11e9-820e-4e5b1ed9ac07.png">

**Comment by glouel** [comment]
Oh wow, well first thanks for trying to find a solution @owellsjr, this will be helpful to others who will undoubtedly face the same situation.

This must indeed be a new iteration of this bug that happened a lot with Macs with Intel graphics. I actually added a while back a very faint dot on top of the video in a corner, it seemed to serve the same purpose as the show clock, and was a succesful workaround for those systems so far (pre mojave). Guess that bug just keeps coming back but the workaround no longer works. 

I'm slightly curious if it's because you have 2 screens, maybe my workaround only worked with one, or not with all the modes (mirroring, diff videos, etc).

In any case, I'll add a warning to the troubleshooting section in the readme, thanks a lot !

**Comment by owellsjr** [comment]
I unplugged my external monitor and in that setup Aerial works as expected with **Show with clock** checked or unchecked. When the external monitor is plugged in (not mirrored, Aerial only on the external monitor) it only works with **Show with clock** checked. Unchecked results in the immediate logout.

**Comment by glouel** [comment]
@owellsjr thanks for checking !! I'll have a look at the code and see if I can improve that.

**Comment by glouel** [comment]
@owellsjr I just checked and the workaround code was disabled for Mojave ! I'll add it back for everyone, I'll ping you with a fresh beta, hopefully that will fix it for you.

**Comment by owellsjr** [comment]
@glouel That fixed it. You are the man! Thanks so much. :)

**Comment by glouel** [comment]
Glad we fixed it 🎉
