### ISSUE TITLE
Set screensaver from terminal

### ISSUE THREAD

**Issue by zored** [JohnCoates/Aerial#742]
## Problem
Screensaver resets after being set from CLI defaults script. But it worked before.

## How to reproduce
I have a script to set Aerial screensaver as default:
```bash
defaults \
    -currentHost \
    write \
    com.apple.screensaver \
	moduleDict -dict \
		path -string "$SAVER/Aerial.saver" \
		moduleName -string "Aerial" \
		type -integer 0
```

And we have a nice config after running this code:
```
    moduleDict =     {
        moduleName = Aerial;
        path = "/path/to/Aerial.saver";
        type = 0;
    };
```

It worked great before macOS 10.12. Now when screensaver starts - it turns into regular hostname screensaver. And config resets too:
```
    moduleDict =     {
        moduleName = "Computer Name";
        path = "/System/Library/Frameworks/ScreenSaver.framework/Resources/Computer Name.saver";
        type = 0;
    };
```

Does anyone have solution for it?

## Why?
Relates to #349.  I like auto-configuration a lot, because I have many scripts in one file and they all run silently without pop-ups 😃

**Comment by glouel** [comment]
Hi @zored 

Have you tried this with another 3rd party screensaver ? I'm not sure this is specific to Aerial, this may be a macOS bug more than ours. 

In general, a screensaver is just a plugin that gets executed by the system when he wants, we have no control about our lifecycle, nor about the install process or setting ourselves as default. So unless our screensaver gets rejected for some reason (I'm still struggling with some signing issue, could be that, requirements are getting tough and slightly unclear for non-app), not sure about what we can do. 

Please try to confirm with another screensaver!

Thanks
