### ISSUE TITLE
Clicking done in the preferences in settings doesn't do anything

### ISSUE THREAD

**Issue by aaronedell** [JohnCoates/Aerial#749]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac (Retina 5K, 27-inch, 2019)
- [x] macOS version: 10.14.4 (18E2034)
- [x] Monitor setup: Built in

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

In the Systems Preferences, after you open Aerial and select preferences where one can select or deselect the videos to play, one cannot click done. Clicking done doesn't do anything. One must force quit system preferences. 

<img width="780" alt="Screen Shot 2019-04-21 at 2 38 25 PM" src="https://user-images.githubusercontent.com/11819814/56475887-7b8dfc80-6443-11e9-956b-4688f2de4269.png">

**Comment by glouel** [comment]
Hi @aaronedell !

You are running a very outdated version of Aerial that had this bug. We've fixed it since and improved many other things.

Please download the latest version here, it will fix your issue : https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta9/Aerial.saver.zip

**Comment by aaronedell** [comment]
This is great - thank you
