### ISSUE TITLE
Doesn't move

### ISSUE THREAD

**Issue by austonib** [JohnCoates/Aerial#75]
I can see the starting image but there is no movement. It just isn't loading I guess. Please help if there's anything that I can do! This seems really cool!

**Comment by beornlake** [comment]
@austonib If you’re using an older build, try hitting the spacebar once. Pressing spacebar, J, K, L, or the arrow keys appears to send keyboard input directly to the QuickTime player which can cause Aerial to sit at a still frame. I had this happen accidentally on my own machine. (See issues #21 and #67).

The newest 1.2b4 release appears to intercept keyboard input, so the above shouldn’t be a problem with the newer versions.

**Comment by austonib** [comment]
Awesome thank you! It works now and this is awesome!

On Oct 31, 2015, at 10:26 PM, Michael Lake <notifications@github.com<mailto:notifications@github.com>> wrote:


@austonib<https://github.com/austonib> If you're using an older build, try hitting the spacebar once. Pressing spacebar, J, K, L, or the arrow keys appears to send keyboard input directly to the QuickTime player which can cause Aerial to sit at a still frame. I had this happen accidentally on my own machine. (See issues #21<https://github.com/JohnCoates/Aerial/issues/21> and #67<https://github.com/JohnCoates/Aerial/issues/67>).

The newest 1.2b4 release appears to intercept keyboard input, so the above shouldn't be a problem with the newer versions.

-

**Comment by alistairmcmillan** [comment]
Closing as resolved for @austonib
