### ISSUE TITLE
New Apple TV videos April 2019

### ISSUE THREAD

**Issue by johnnyblair** [JohnCoates/Aerial#755]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by johnnyblair** [comment]
I just noticed that some really nice new videos started streaming on my Apple TV this week.  Any chance anyone has some information on these new videos?  Seems like some tropical stuff, possibly Antarctica, and some others.

**Comment by glouel** [comment]
Hi @johnnyblair, which version of Aerial are you using ? You can find the version in the bottom right corner of the preference panel. 

I had a quick look and the file hasn't changed since the january update. I'd suggest you install the latest beta to get the latest videos, if you haven't already.

**Comment by johnnyblair** [comment]
What I am saying is that my Apple TV is showing new screensaver videos this week.  Ones that I do not see in the last update.  I am running the newest version with the January updated videos.  I will take some screenshots of the new videos I have noticed on my Apple TV later tonight.

**Comment by glouel** [comment]
@johnnyblair ok please do ! Could be there's a new url that we don't know about, although that would be surprising. Are you running a tvOS beta maybe ?

I'm still seeing the same videos here on my Apple TV but what you get is so random on there, there could be new videos that I don't see.

**Comment by johnnyblair** [comment]
ok after a reboot I think Aerial Saver is now seeing them.  just ignore this thread :)

**Comment by glouel** [comment]
Ok feel free to reopen if you see something new, thanks !
