### ISSUE TITLE
Feature request: Display information setting on multiple monitors

### ISSUE THREAD

**Issue by papin97** [JohnCoates/Aerial#756]
On the current version, there is a setting to handle Aerial playback on multiple display. Can we have the same setting for information text?
Like, currently the information only displays to main display. I want the setting so I can configure the information to display, just like Aerial playback setting.

**Comment by glouel** [comment]
Hi @papin97 

Right now the multi monitor code is really messy, but I'll put this for a future update. Thanks !

**Comment by glouel** [comment]
Hi @papin97 

I know it's been a long while, but I finally implemented this in latest beta : https://github.com/JohnCoates/Aerial/releases/download/v1.6.5beta1/Aerial.saver.zip

**Comment by glouel** [comment]
Closing this with the release of 1.7.0 : https://github.com/JohnCoates/Aerial/releases/tag/v1.7.0
