### ISSUE TITLE
Feature Request: Include Option to load Personal Videos from local directory

### ISSUE THREAD

**Issue by LiquidDev** [JohnCoates/Aerial#757]
#### Description of issue / Feature request

Please include a local directory option where personal action camera movies can be uploaded from. 
- Create local directory   -   ~/Library/Cache/Aerial  
- Poll this directory for entries.json to pull correctly formatted screensaver descriptions
- Really Nice to have:  Include ability to add the JSON entry via the screensaver dialog.

Hoping you can support this.
Thanks,    Paul

**Comment by glouel** [comment]
> #### Description of issue / Feature request
> Please include a local directory option where personal action camera movies can be uploaded from.
> 
> 
> Hoping you can support this.
> Thanks, Paul

Hi @LiquidDev 

This has been asked a few times but it's a pretty big task. 

> * Create local directory   -   ~/Library/Cache/Aerial

I'll consider this one for a future update, but no promise !

> * Poll this directory for entries.json to pull correctly formatted screensaver descriptions

That's a mayyyybe, it's not easy to correctly generate that json.

> * Really Nice to have:  Include ability to add the JSON entry via the screensaver dialog.

That's a hard nope sorry, way too complex :)

G.

**Comment by glouel** [comment]
This is implemented in beta6, see this issue : https://github.com/JohnCoates/Aerial/issues/786

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0
