### ISSUE TITLE
Fill screen option for portrait orientation displays

### ISSUE THREAD

**Issue by serriere** [JohnCoates/Aerial#76]
Not sure if this is possible, but on portrait orientation displays (screen width is less than screen height) or even any display that doesn't have an aspect ratio that matches the source content it would be nice to have a "fill screen" option that scales and crops the video to fit the screen. Current behavior letterboxes (black bars top and bottom) the content and this effect is particularly pronounced on portrait orientation displays.

**Comment by serriere** [comment]
Turns out this is just a Mavericks bug. Upgraded to El Cap and everything works as expected.

**Comment by JohnCoates** [comment]
Good to hear that fixed it. I just found the cause of that and have patched it for the next release.
