### ISSUE TITLE
Brew installed v1.4.8 if "Auto install updates while the screen saver runs" with default enabled status only.

### ISSUE THREAD

**Issue by billstanden** [JohnCoates/Aerial#760]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Various MacBook Pros and iMacs
- [ ] macOS version:  10.14.4
- [ ] Monitor setup: Single and multiple

#### Description of issue

I'm installing Aerial via Brew and with the latest update discovered the screensaver would fail to start, falling back to the default after some seconds when instantiated.

From the System Preferences the small preview ran fine but testing it full screen had the same results.

In debugging I noticed the new Automatic updates section and that the "Auto install updates while the screen saver runs" is enabled by default.

Toggling this off resolves the issue and the screensaver runs normally after that, including if you toggle the setting back on.

**Comment by glouel** [comment]
hi @billstanden and oops, sorry about that !

I think I know what happened, unlike regular install methods (manual or Sparkle), Aerial's control panel will never get launched with homebrew post update. So just going there I think fixes it. 

I think I know what to do but it would be super nice to have confirmation, any chance you can paste me the crash log ? You can find more info on how to get it here (https://github.com/JohnCoates/Aerial/issues/737#issuecomment-480835738 ignore the begginning about uninstall, it starts at Console.app), that would be most helpful !

Thanks for reporting and really sorry about that crash

**Comment by glouel** [comment]
I managed to reproduce the crash, trying to test the fix ASAP but VirtualBox isn't really quick for this. Will update asap.

**Comment by glouel** [comment]
@billstanden v1.4.9 is on its way, I submitted the PR for the new cask https://github.com/Homebrew/homebrew-cask/pull/62643 

Again sorry about the issue and thanks for the report !

**Comment by glouel** [comment]
1.4.9 is now up on homebrew.

**Comment by billstanden** [comment]
Installed and confirmed fixed.  Cheers.
