### ISSUE TITLE
Location issues

### ISSUE THREAD

**Issue by heutger** [JohnCoates/Aerial#761]
Hi,

first thanks for introducing an update mechanism. Second just a question, what does community information mean, which I can choose? Is the control panel also available in other languages and/or how can I help to localize?

Now the primary question:

I tried to change to day and night themes based on location, but can't choose this option. I'm on MacOS 10.14 and I also now activated Night Shift (just to be sure, that location services are enabled). However the control panel of Aerial still states, that location is unavailable and it seems, that location services are disabled, but they aren't. Are there any other topics, I need to check? e.g. Double-Click to install did not work as the code is not signed, I then copied the saver to my screensavers folder of my user account.

Regards,
Christian

**Comment by glouel** [comment]
> Hi,
> 
> first thanks for introducing an update mechanism. Second just a question, what does community information mean, which I can choose?

Community descriptions are extra video descriptions. When Aerial plays, you can see location information about what you are watching on the bottom left corner by default. Some of these come from Apple, some videos however lack those information (only the newest tvOS12 videos have them, Aerial supports all the videos from previous tvOS versions). For those, we have Community Descriptions, written by our community of users and translated in multiple languages. If you enable, then that's what you can pick.  

> Is the control panel also available in other languages and/or how can I help to localize?

Nope, the control panel is english only for now, it's on my todo list. You can find more about the localization process here FYI : https://github.com/JohnCoates/Aerial/blob/master/Resources/Community/Readme.md

> Now the primary question:
> 
> I tried to change to day and night themes based on location, but can't choose this option.

Just so we are clear, we're talking about option 2 in this screenshot right ? 

![Capture d’écran 2019-05-01 à 14 16 03](https://user-images.githubusercontent.com/37544189/57016688-c239de80-6c1b-11e9-8782-e59bcd289d09.jpg)

> I'm on MacOS 10.14 and I also now activated Night Shift (just to be sure, that location services are enabled). However the control panel of Aerial still states, that location is unavailable and it seems, that location services are disabled, but they aren't. 

So, for the second option, Aerial uses a terminal command to grab sunset/sunrise times. Can you open terminal and type this : 

```
/usr/bin/corebrightnessdiag nightshift-internal
```

there should be a section like this : 

```
Night Shift Sunset/Sunrise
{
    isDaylight = 1;
    nextSunrise = "2019-05-03 04:39:06 +0000";
    nextSunset = "2019-05-02 19:10:56 +0000";
    previousSunrise = "2019-05-01 04:42:31 +0000";
    previousSunset = "2019-04-30 19:07:58 +0000";
    sunrise = "2019-05-02 04:40:48 +0000";
    sunset = "2019-05-01 19:09:27 +0000";
}
```

Can you paste yours ? 

As a fallback, you should be able to use the first option, this one uses Core Location to get your position and will calculate your sunset/sunrise times. Click the compass, it will prompt you to allow Aerial to use location services (so you'll see this later on in Sys Pref, sorry for the French screenshot) :

![Capture d’écran 2019-05-01 à 14 16 03](https://user-images.githubusercontent.com/37544189/57016812-6facf200-6c1c-11e9-82f9-8902ff536878.jpg)

Also useful if all else fails:
- going into advanced, enable debug log & log to disk.
- Close Aerial preferences
- Close System Preferences
- Reopen System Preferences and Aerial panel. Grab the log and paste it here. 

>e.g. Double-Click to install did not work as the code is not signed, I then copied the saver to my screensavers folder of my user account.

It's signed, but macOS still complains and I haven't fully figured out why yet. In any case, not related to your issue.

**Comment by heutger** [comment]
Hi,

 

thanks for the additional information.

 

Regarding my primary problem, I was able to solve. I just looked into Preferences Security and because of the signing failure I wasn’t able to use option 2, as after accepting Aerial to be loaded although not signed (or signing failure), the option was able to be selected.

 

Grüße,

Christian

 

Von: Guillaume Louel <notifications@github.com>
Antworten an: JohnCoates/Aerial <reply@reply.github.com>
Datum: Mittwoch, 1. Mai 2019 um 14:32
An: JohnCoates/Aerial <Aerial@noreply.github.com>
Cc: Christian Heutger <christian@heutger.net>, Author <author@noreply.github.com>
Betreff: Re: [JohnCoates/Aerial] Location issues (#761)

 

Hi,

first thanks for introducing an update mechanism. Second just a question, what does community information mean, which I can choose?

Community descriptions are extra video descriptions. When Aerial plays, you can see location information about what you are watching on the bottom left corner by default. Some of these come from Apple, some videos however lack those information (only the newest tvOS12 videos have them, Aerial supports all the videos from previous tvOS versions). For those, we have Community Descriptions, written by our community of users and translated in multiple languages. If you enable, then that's what you can pick.

Is the control panel also available in other languages and/or how can I help to localize?

Nope, the control panel is english only for now, it's on my todo list. You can find more about the localization process here FYI : https://github.com/JohnCoates/Aerial/blob/master/Resources/Community/Readme.md

Now the primary question:

I tried to change to day and night themes based on location, but can't choose this option.

Just so we are clear, we're talking about option 2 in this screenshot right ?

I'm on MacOS 10.14 and I also now activated Night Shift (just to be sure, that location services are enabled). However the control panel of Aerial still states, that location is unavailable and it seems, that location services are disabled, but they aren't.

So, for the second option, Aerial uses a terminal command to grab sunset/sunrise times. Can you open terminal and type this :
/usr/bin/corebrightnessdiag nightshift-internal
 
there should be a section like this :
Night Shift Sunset/Sunrise
 
{
 
    isDaylight = 1;
 
    nextSunrise = "2019-05-03 04:39:06 +0000";
 
    nextSunset = "2019-05-02 19:10:56 +0000";
 
    previousSunrise = "2019-05-01 04:42:31 +0000";
 
    previousSunset = "2019-04-30 19:07:58 +0000";
 
    sunrise = "2019-05-02 04:40:48 +0000";
 
    sunset = "2019-05-01 19:09:27 +0000";
 
}
 
Can you paste yours ?

As a fallback, you should be able to use the first option, this one uses Core Location to get your position and will calculate your sunset/sunrise times. Click the compass, it will prompt you to allow Aerial to use location services (so you'll see this later on in Sys Pref, sorry for the French screenshot) :

Also useful if all else fails:
going into advanced, enable debug log & log to disk. 
Close Aerial preferences 
Close System Preferences 
Reopen System Preferences and Aerial panel. Grab the log and paste it here. 
e.g. Double-Click to install did not work as the code is not signed, I then copied the saver to my screensavers folder of my user account.

It's signed, but macOS still complains and I haven't fully figured out why yet. In any case, not related to your issue.
