### ISSUE TITLE
[1.4.10b1] Aerial skips low battery check

### ISSUE THREAD

**Issue by papin97** [JohnCoates/Aerial#764]
*Log file attached*
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3137670/AerialLog.txt)
#### Description of issue / Feature request

Aerial keeps playing the video on lower than 20% battery level even though the power saving option is enabled on low battery.

**Comment by glouel** [comment]
Hi @papin97 

Can you clarify exactly what you see ? 

As of right now, the battery check only happens when Aerial starts playing (when the screensaver is first called by the system). If you cross the threshold while the screensaver plays, it won't stop. Is this what you saw ?

**Comment by papin97** [comment]
Hi @glouel 
No. I set the screensaver to play after 1 minute. I was working on my laptop until it reaches 13% then I left it for a bit. When I came back the screensaver plays Aerial video (no black screen as expected). The threshold already crossed before the screensaver plays.

**Comment by glouel** [comment]
@papin97 
Ok then sorry about that, I'll have a look, might require a new beta with extra logging, I'll let you know!

**Comment by glouel** [comment]
@papin97 sorry for the delay but my old macbook air's battery is shot so it was pretty hard to reproduce. 

Looks like the low battery detection didn't work as intended, I've replace the code with a new battery percentage detection. If you are below 20% now it will engage power saving as expected. 

Let me know how it goes for you, this is fixed on beta2.

**Comment by papin97** [comment]
@glouel Can confirm that this issue is fixed in beta2. Thanks so much!
I'll close this issue.
