### ISSUE TITLE
Feature Request: Allow deletion of videos from cache

### ISSUE THREAD

**Issue by fok** [JohnCoates/Aerial#766]
#### Description of issue / Feature request

An option to delete specific videos from cache would be nice.

**Comment by glouel** [comment]
Good idea, marking for future enhancement for 1.5.0

**Comment by ArtemBernatskyy** [comment]
But we can manually remove videos from cache folder, aren't we ?

**Comment by fok** [comment]
When you manually remove them Aerial doesn't pick up on that. Tried it twice. I had to remove the whole cache directory to have it sync again.

**Comment by glouel** [comment]
You can, but you need to restart aerial for it to rescan your video folder.

**Comment by glouel** [comment]
@fok you can now right click to move a video to trash with the latest beta

https://github.com/JohnCoates/Aerial/releases/tag/v1.4.99beta3

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0

**Comment by ArtemBernatskyy** [comment]
Thx, waiting for homebrew version :)

**Comment by glouel** [comment]
> Thx, waiting for homebrew version :)

Wooops, I knew I forgot something this morning ! I just pushed the pull request, should be merged soonish ! https://github.com/Homebrew/homebrew-cask/pull/64204

**Comment by glouel** [comment]
@ArtemBernatskyy it's up !

**Comment by ArtemBernatskyy** [comment]
@glouel thx
Already tried `remove from cache` feature, works perfect :)
