### ISSUE TITLE
Skip to next video only affects monitor 1 in a multi-display setup

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#769]
- [x] Mac model: **mac mini 2018**
- [x] macOS version: **10.14.4**
- [x] Monitor setup: **2 external 23" displays**

#### Description of issue

On my multi-monitor system, tapping the Right-arrow key to skip to the next video only causes the video on "monitor 1" to skip (it should skip on both screens I think).

**Comment by glouel** [comment]
Ok that's an embarrassing one I'll fix asap 🙈

**Comment by glouel** [comment]
Should be fixed in beta3

**Comment by luckman212** [comment]
Thank you! I will test & confirm asap

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0
