### ISSUE TITLE
Debug logs only include a time (no date)

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#771]
It would be helpful when debugging long-running issues (e.g. #768) if the logs were written using a full timestamp that included the date and time in 24H format. Currently only a 12h time is output (no date).

The timestamp format should be similar to what `date '+%Y-%m-%d %H:%M:%S'` outputs.

e.g. instead of
```
1:03:48 PM : AssetLoaderDelegate deinit
1:03:48 PM : <AerialView: 0x7f9c90c435c0> playing next video for player Optional(<AVPlayer: 0x600001d86190>)
1:03:48 PM : <AerialView: 0x7f9c90c435c0> observeValue Optional("readyForDisplay")
1:03:48 PM : locale.languageCode en
```

it should be
```
2019-05-09 13:03:48 : AssetLoaderDelegate deinit
2019-05-09 13:03:48 : <AerialView: 0x7f9c90c435c0> playing next video for player Optional(<AVPlayer: 0x600001d86190>)
2019-05-09 13:03:48 : <AerialView: 0x7f9c90c435c0> observeValue Optional("readyForDisplay")
2019-05-09 13:03:48 : locale.languageCode en
```

**Comment by glouel** [comment]
I'll change the timestamp format, good idea. Will be in next beta.

**Comment by glouel** [comment]
That's fixed in betas so closing this :)
