### ISSUE TITLE
Feature Request: Ability to disable streaming on certain Access Points and/or Personal Hotspot connection

### ISSUE THREAD

**Issue by czo** [JohnCoates/Aerial#772]
I am using my Mac frequently from a Huawei mobile hotspot via my metered cellular connection. If i can disable streaming (to play only locally cached videos) when connected over a metered connection, then it's can save ton's of bytes from my monthly bundle. So, i think, a list where i can store the list of the metered connections is the best option for this. Maybe, to made this ever better in the future, create an option to limit the count of the cached videos. I think, it's enough for me to play only the last one (keep only one video in the cache) video every time, when i on the go.

Thanks.

**Comment by glouel** [comment]
Hi @czo 

I specifically implemented the never stream videos for people with metered connection. I would suggest with current version to cache a few videos (you can manually select the ones you wish) and check never stream videos. Then Aerial will only play from what's on your cache, period, and generate 0 traffic (apart from a periodic update check which you can disable).

I have a feeling you'd be better served by a system wide tool though if you want to keep streaming, there are tools like Trip Mode and Little Snitch that can do the apply restrictions in a broader manner. See here for some suggestions : https://apple.stackexchange.com/questions/215454/managing-metered-connections-on-osx#215509 

I don't think implementing this in every app is a good idea. 

About having a cache size limit and periodically refreshing it (the way Apple TV does it), it's pretty complex but on the mayyyybe future update list. In general streaming videos is bad, not everyone can stream them fast enough and it generates unneeded strain on servers (which we have to be very considerate of) so I would not implement it with streaming in any case. 

G.

**Comment by czo** [comment]
I think, caching more than one video is wasting space on the pricey SSD (i have very fast internet everywhere, or maybe limit it in 0.5 or 1GB and/or reencode it to 720p), so that's why i thinking streaming is the best option when i am home (i have all of the videos are enabled because i don't wan't to limit which can i see or not, but i don't wan't to cache them all). 

If i remember correctly, little snitch "Trip Mode" is something that i need to turn on manually and that's feature is limit the complete app not only one function of the app. (example: when i use Photos.app with enabled iCloud Photo Library, i would like to limit photo/video uploads but i don't wan't to limit original downloads from the library when i open one or more photo). 

i have an open ticket about "metered connection" flag in Apple's Radar since 2012, i don't think Apple will implement this (or similar thing) in the near future.

**Comment by glouel** [comment]
Aerial piggybacks on tvOS server ressources which are currently open. Something we are grateful for and hope will remain so in the future. Continuously streaming goes counter to that and is not something I will encourage in Aerial.  

With that said, please check the link I provided, Trip mode is a separate app from Little Snitch. There are many options listed to block certain apps/processes when on a particular connexion which would work with how you want to use Aerial.
