### ISSUE TITLE
Just wanted to say

### ISSUE THREAD

**Issue by schroef** [JohnCoates/Aerial#773]
Just wanted to say thank you! 

I was checking this old mac pro we bought couple months back on disk space, when i noticed this huge folder in the cache folder. After some quick checking i found this wonderful project and see i this is already installed. 

Wow does this look great, thanks for the effort in creating this!!!!

**Comment by glouel** [comment]
Thanks @schroef ! Glad you discovered Aerial this way, I've been maintaining this project for a few months now and it's always nice to hear good things :)

Make sure you update your version as we always add some new features !

**Comment by schroef** [comment]
Thanks just did, but the tcomputer is on slow internet. So im gonna download everything at home.

Perhaps one thing could be added. A better download for the videos. Now it seems to stop when the screensaver is stopped. However i did get one new video somehow. Perhaps some sort of setting to download them from the settings, it think this will make it easier for some users.

**Comment by schroef** [comment]
PS i did an update and noticed 2 files tvOS10 and tvOS11, but on the main page i read about downloading them all at once and than i noticed tvOS12? That doesnt come with the auto update though?

**Comment by glouel** [comment]
> Perhaps one thing could be added. A better download for the videos. Now it seems to stop when the screensaver is stopped. However i did get one new video somehow. Perhaps some sort of setting to download them from the settings, it think this will make it easier for some users.
> PS i did an update and noticed 2 files tvOS10 and tvOS11, but on the main page i read about downloading them all at once and than i noticed tvOS12? That doesnt come with the auto update though?

So when you update Aerial (to 1.4+), it will look for the tvOS12 videos. That means it will update the list on the left in it's settings, where you can download the ones you want. By default, Aerial will pick them up one by one when the screensaver is running as it can stream new videos and will cache them for later use (you can disable that in Cache tab). 

However, the fast way to get the videos is to get them from the System Preferences settings panel. Missing videos will show a little + on the list: 

![Capture d’écran 2019-05-11 à 10 39 29](https://user-images.githubusercontent.com/37544189/57567438-6e788380-73d9-11e9-9432-67f22432fe2e.jpg)

You can either click the ones you want or if you want everything, press the cog button below the list and pick Download all, they'll get queued:

![Capture d’écran 2019-05-11 à 10 40 08](https://user-images.githubusercontent.com/37544189/57567439-6e788380-73d9-11e9-8d8e-de720a521acd.jpg)

You need to keep that panel open for the downloads to proceed (I need to add a warning before you close the panel if you have downloads still going). 

> PS
> why not make the main page more compact with compact info and than work on a wiki page. Now its endless scrolling. The wiki page still shows some kind TOC on the right. Thats much easier to read

Yep I really need to work on that 😅

**Comment by schroef** [comment]
Great and super fast help! Thanks a lot!

Ill check if i can get it working now.
