### ISSUE TITLE
Small typo! independant→independent

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#774]
https://github.com/JohnCoates/Aerial/blob/4255a5a190186781cd7272b59e30eef0eccad497/Aerial/Source/Controllers/Preferences.swift#L109

Should be "independ**e**nt"

![image](https://user-images.githubusercontent.com/1992842/57546211-467e1700-732a-11e9-81f9-c8117e96d290.png)

**Comment by glouel** [comment]
Oops... I actually had a doubt typing it, wrote it the french way.
Fixed for next beta thanks !

**Comment by glouel** [comment]
forgot to close this one since fixed :)
