### ISSUE TITLE
Text overlay on video

### ISSUE THREAD

**Issue by cassidoo** [JohnCoates/Aerial#78]
Some workplaces require some text on screensavers so that people can see whose computer it is if they leave it sitting somewhere or something.  It'd be great to have a small bit of customized text as an overlay somewhere on the screen.

**Comment by JohnCoates** [comment]
Good feature request @cassidoo 
Related to Issue #58 and can be implemented at the same time

**Comment by Jonathan-Rosewood** [comment]
John, do u have a roadmap?

**Comment by JohnCoates** [comment]
Not yet @Jonathan-Rosewood! I hadn't thought about it, I'll make one asap

**Comment by mgguinne** [comment]
+1

**Comment by glouel** [comment]
https://github.com/JohnCoates/Aerial/releases/tag/v1.4.1beta2 bit late but this feature is in this build FYI

**Comment by cassidoo** [comment]
Wow! Better late than never! 😄
