### ISSUE TITLE
No video update

### ISSUE THREAD

**Issue by axelv73** [JohnCoates/Aerial#782]
Hi, I've installed Aeriel many months ago with all updates but the video are ever the same!
Any solution?

Aerial 1.4.9

**Comment by glouel** [comment]
Hi @axelv73 

The frequency of updates depends of Apple. While they were many updates in the last months of 2018, the last one was on january 21, this is why you don't see new ones.

I expect we'll see new videos at WWDC in a couple of weeks though, so stay tuned !

**Comment by axelv73** [comment]
I wrote because it seemed to me that I had seen a new video on AppleTV that I had never seen on Aerial...

**Comment by glouel** [comment]
If you do, please take a picture of it.

FYI I do use an Apple TV too and so far have not spotted a new one, but with the randomness you never know !

**Comment by glouel** [comment]
Closing this, please reopen with a screenshot if you see something new thanks !
