### ISSUE TITLE
How to set 24-hour clock?

### ISSUE THREAD

**Issue by peterzheng98** [JohnCoates/Aerial#789]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- [x] macOS version: macOS Mojave 10.14.4 (18E226)
- [x] Monitor setup: Built-in Retina Screen

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

How to set clock in 24 hour mode?

**Comment by glouel** [comment]
Hi @peterzheng98 !

Aerial uses your system's settings for clock. You can enable 24 hour clock in macOS in System Preferences > Language & Region, see below : 

![Screen Shot 2019-05-30 at 13 21 41](https://user-images.githubusercontent.com/37544189/58630065-91160200-82de-11e9-8b59-8fcaa712e779.jpg)
