### ISSUE TITLE
Request: Easy Access to Change Log

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#790]
As a user with Automatically Check For Updates turned on and currently enabled Beta Builds as well, I would love to have an easier access to the most recent change logs. 

A simple way of doing this would be to allow a user to click on the build number and have this lead to the most recent change log. This would be a great help for the beta builds, but I also think would end up being useful for many other users as well. 

![Screen Shot 2019-05-30 at 12 23 15 PM](https://user-images.githubusercontent.com/18543749/58647627-f6192a00-82d5-11e9-890d-f59842f16877.jpg)

An alternative choice would also be to just have a button implemented into the Updates panel that allows for this.

**Comment by glouel** [comment]
Hey !

So yeah, using the version number to point to the release notes (so in that case : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.99beta7 ) seems like a good idea for betas. 

I'm currently rewriting the documentation and as a part of this, I have a more easy to read ChangeLog as part of this, you can see here the WIP : https://github.com/glouel/Aerial/blob/master/Documentation/ChangeLog.md

Maybe linking to that for non beta versions would be better (easier to read) ? Thoughts ?

**Comment by ZV00** [comment]
I would say that those of us using beta builds the ease of reading is not as necessary... So I would think that beta builds should go to the "less easy" version, while the official releases go to the "easier" version if that makes sense?

**Comment by glouel** [comment]
yep for beta, the tag link.

**Comment by ZV00** [comment]
Yeah that would do it!

**Comment by glouel** [comment]
So this is implemented for tommorrow's 1.5.0 release. There's also a few bugfixes compared to beta7 but not enough to warrant a new beta. 

![Capture d’écran 2019-05-30 à 21 22 21](https://user-images.githubusercontent.com/37544189/58658668-47024000-8321-11e9-993a-48498a30016c.jpg)

On stable releases, clicking the version number will go to https://github.com/glouel/Aerial/blob/master/Documentation/ChangeLog.md (but in this repository, it's not up yet so linking that one instead just in this issue)

On beta releases, it will go to the release notes directly : https://github.com/JohnCoates/Aerial/releases/tag/v1.4.99beta7

Those are usually more terse but should be good enough for everyone. I keep them aligned to what you see in the Sparkle update if you don't use the silent update thing.

**Comment by ZV00** [comment]
Awesome great!

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0
