### ISSUE TITLE
PlaybackStalled errors since 1.5.0

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#793]
Hey all!

Since the 1.5.0 (weirdly not in the beta build before) I have been throwing `AVPlayerItemPlaybackStalledNotification` errors on many launches: 

```
12:29:20 : <AerialView: 0x7ff80f01fdc0> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x60000376bf40, asset = <AVURLAsset: 0x60000376fe60, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_HK_H004_C001_PSNK_DENOISE_v14_SDR_PS_FINAL_20180731_SDR_4K_HEVC.mov>>), userInfo = nil

12:33:14 : <AerialView: 0x7fbcede1ec60> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000cca020, asset = <AVURLAsset: 0x600000cca120, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G004_C010_PSNK_v04_SDR_PS_FINAL_20180709_SDR_4K_HEVC.mov>>), userInfo = nil
```

Wanted to report it in case that can be fixed in the future.

**Comment by glouel** [comment]
Hey ! So stalled notification happen when the streaming is too slow (slow connexion to server), and the playback stalls. Nothing I can do about that. 

I would suggest you cache the videos to get rid of those slowdowns 😉

**Comment by ZV00** [comment]
Copy that!

**Comment by glouel** [comment]
I guess I should make that error easier to understand too it’s pretty obscure !

**Comment by ZV00** [comment]
Lol, could be made easier. The warnings are all sort of nondescript which makes them a little hard to decipher or determine if action is actually needed.
