### ISSUE TITLE
v1.5.0, Custom videos just stop instead of advancing to next one

### ISSUE THREAD

**Issue by hub-c** [JohnCoates/Aerial#799]
Aerial v1.5.0

2015 Retina Macbook Pro w/AMD RadeonR9 M370X
macOS High Sierra 10.13.4 (17E199)
Monitor setup: built-in screen is main, with secondary 1080p screen rotated to portrait mode to the right

Aerial set to display on main screen only, 0.5sec fade in/out (happens when set to 0 fade in/out, too)

I am using a folder of 11 custom videos, downloaded from youtube, length ranging from roughly 30s to 1m30s. All videos are .mp4 and play fine in Aerial preview box.

When I activate screen saver one plays at random, but after it's done it screen saver just stops on last frame and does not advance to the next video.

Pressing right arrow will load next video as expected.

Attaching debug log.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3248698/AerialLog.txt)

**Comment by glouel** [comment]
I'll have a look tommorrow and let you know ! Thanks for the report !

**Comment by glouel** [comment]
Can you tell me how/with which tool you downloaded you videos ? Could be some issue with detection the correct video length, will need to have a better look.

**Comment by hub-c** [comment]
https://en.savefrom.net/1-how-to-download-youtube-video/

Copied and pasted URL of Youtube video, then rather than download the MP4 720 I clicked the popup menu to select the MP4 1080 (no audio) format option.

When I check the Duration value in the Manage Custom Videos window, it is the same as what Quicktime Player and VLC say, but your assessment was correct: the video length detection is wrong, in fact it's roughly double what the actual lengths are. It seems to be a problem with downloading the 1080 (no audio) format specifically, the default MP4 720 has the correct duration.

**Comment by glouel** [comment]
Ha, makes sense then ! I would suggest you try remuxing the videos to fix them.

**Comment by hub-c** [comment]
Remuxing videos with Handbrake fixed the video length detection, and videos advance as expected. I'll close this issue since it's not an Aerial bug, nor should Aerial be expected to compensate for a problem with the source video.

**Comment by glouel** [comment]
Great ! I've added a section in troubleshooting here with an answer so other people can find it : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md#about-custom-videos
