### ISSUE TITLE
Screensaver movie stops after 1 sec

### ISSUE THREAD

**Issue by reglmk** [JohnCoates/Aerial#8]
Hi!

I am using a Late 2013 MacBook Pro Retina, with Yosemite 10.10.5.
Aerial installed without a problem, but the video stops after 1 sec, no matter if I click the preview in the Sys Pref/Screensavers or I let it start, it is the same.
I was wondering if the wifi has anything to do with it. I am on a WPA2-Enterprise wifi network, with quite a few blocked ports.
Or it might have nothing to do with it (sorry, I am not familiar with it...).
Thank you for the help in advance.
Cheers

**Comment by danielgolden** [comment]
I'm experiencing the same issue:

- MacBook Pro (Retina, Mid 2012)
- El Capitan 10.11.1 (15B42)
- 2.6 GHz Intel Core i7 (in case it matters)

**Comment by BenGale** [comment]
+1

**Comment by computeus** [comment]
+1
* MacBook Air (13-inch, Mid 2012)
* OS X El Capitan 10.11 Beta (15A278b)
* 1,8 GHz Intel Core i5
* 4 GB 1600 MHz DDR3

**Comment by tepRuslan** [comment]
+1

* Mac Mini (Late 2012)
* OS X El Capitan 10.11.1
* 2,6 GHz Intel Core i7
* 4 GB 1600 MHz DDR3
* Intel HD Graphics 4000 1536 MB
* Internet: 4G Mobile from iPhone

**Comment by echezbro** [comment]
+1

**Comment by ValentinCreative** [comment]
+ 1 

* MacBook Pro (Retina, 15-inch, Late 2013)
* OS X El Capitan 10.11.1
* 2,3 GHz Intel Core i7
* 16 Go 1600 MHz DDR3
* NVIDIA GeForce GT 750M
* Internet ADSL (wifi)

**Comment by ValentinCreative** [comment]
It's definitely an internet speed issue. 
I just tried with my iPhone 4G connexion and it works pretty well !

**Comment by reglmk** [comment]
Think it is a proxy or firewall issue. What ports does it use???

**Comment by ValentinCreative** [comment]
@reglmk if it was proxy or firewall you should not be able to see the first second at all. 

I just tried today at the office (fiber-optic) and it works well.

**Comment by reglmk** [comment]
Ok, just tried it, and now it works fine on all screens, even with airplay.
Cheers
