### ISSUE TITLE
Option to Fit video onto (rotated) second screen

### ISSUE THREAD

**Issue by hub-c** [JohnCoates/Aerial#800]
2015 Retina Macbook Pro w/AMD RadeonR9 M370X
macOS High Sierra 10.13.4 (17E199)
Monitor setup: built-in screen is main, with secondary 1080p screen rotated to portrait mode to the right

When second screen is used, video is cropped to fill entire screen, i.e. no black borders. This is great for spanning videos.

When video Viewing Mode is set to Independent though, would like option to instead Fit entire video on screen when in portrait mode, e.g. there's large black bars above and below video.

Thank you and loving your great work!

**Comment by glouel** [comment]
That's doable, your video would look fairly small though with huge black bars on top and below ! I'm marking this for a future update.

**Comment by hub-c** [comment]
With my 24" screen rotated 90°, the width is about 1" less than the width of the 15" MBPro's screen, so the difference won't be that great in my setup.

On a rotated 1080p screen, the black bars take up enough space to stack 3 different 16:9 videos, like 3 screens stacked atop each other (top, middle, bottom)... Perhaps a further enhancement for this Fit-to-window option is choosing which pseudo-screen(s) to play up to three different videos?

**Comment by glouel** [comment]
I'm willing to add black bars (so instead of filling screen, fit video to screen with bars) but multiple videos on a same screen is a big no no, sorry :)

**Comment by hub-c** [comment]
Just black bars are fine, I had a feeling the additional stuff was a rather big ask :)

On reflection, I used the wrong term for this... I think "**Scale video to screen**" is closest to what I'm describing, since that preserves the aspect ratio while still showing the entire video, and can result in black bars. Fill or fit implies stretching the video so there are no black bars, and that would look terrible on a rotated screen!

**Comment by glouel** [comment]
Agreed we're thinking of the same thing ! I'm looking at Apple's documentation, they have that exact mode and they are calling it `resizeAspect`. I'll probably have a beta with it tommorrow, will let you know (I'm trying to download the beta/xcode to try and find the new undersea videos shown in the keynote).

**Comment by gregarios** [comment]
> Agreed we're thinking of the same thing ! I'm looking at Apple's documentation, they have that exact mode and they are calling it `resizeAspect` (and the current mode is `resizeAspectFill` hardly good names !).

Just a note: Speaking from personal experience fitting video to odd screen sizes, it is often a good thing to "scale to screen" then add a certain percentage of zoom to crop off the left and right sides of the video just a little (not too noticeable usually) to add the benefit of reducing the height of the black bars by quite a bit.

**Comment by glouel** [comment]
> Just a note: Speaking from personal experience fitting video to odd screen sizes, it is often a good thing to "scale to screen" then add a certain percentage of zoom to crop off the left and right sides of the video just a little (not too noticeable usually) to add the benefit of reducing the height of the black bars by quite a bit. You could even make the zoom part adjustable by the user.

Indeed ! With knowledge from the "Spanned" mode, I think I can do this. It might take me a bit to figure out though but keeping that in mind, thanks !

**Comment by glouel** [comment]
@hub-c 
Ok I've implemented a quick & dirty fill/fit selection in displays in this build : https://github.com/glouel/Aerial/releases/download/v1.5.1test1/Aerial.saver.zip

Let me know if it works at least :) I'm thinking that you'd probably rather have a checkbox that says "Fit on rotated screens" instead ? 😅

**Comment by hub-c** [comment]
Haven't forgotten, but have been away from my second screen the last two days. Will get back to it next week and let you know :)

**Comment by hub-c** [comment]
Tested the "Fit to Screen" option and it works perfectly. I think the wording is fine as-is, no need to mention rotated screen in the popup menu, though that use case could be mentioned in help popup text (via a (?) button like next to Videos > Preferred Video Format) as the reason the option exists

**Comment by glouel** [comment]
Great ! Thanks for the feedback. I mentioned rotated screens because as is, it fits all screens, so you likely have black horizontal bars on your main display (unless it's the exact ratio of the videos which it might be, in the case of an iMac, you get black bars on your display).
