### ISSUE TITLE
Bringhtness control

### ISSUE THREAD

**Issue by ChristofMS** [JohnCoates/Aerial#803]
Hey everyone, 

Frist of all, thank you very much for this program and your continuing efforts regrading it! It's wonderful to have these screensavers on the Mac.

From my point of view, it would be nice to have an option, where the dimming starts at the current brightness of the display and not artificially jumps to the point defined in the settings. Otherwise the display gets sometimes (with low current brightness setting) much brighter and/or sometimes much darker depending on the setting in Aerial.

**Comment by glouel** [comment]
> From my point of view, it would be nice to have an option, where the dimming starts at the current brightness of the display and not artificially jumps to the point defined in the settings. Otherwise the display gets sometimes (with low current brightness setting) much brighter and/or sometimes much darker depending on the setting in Aerial.

That makes sense, I'll have to look at the code to see what I did, I don't really remember. Should be an easy fix.

**Comment by glouel** [comment]
Hey @ChristofMS 

So after thinking about this, I think I found a nice compromise, I keep the settings as is, but Aerial will use the min value between what you set as a start point and the current brightness. 

I think it solves the issue, keep some versatility and makes it more intuitive than adding more settings again.

**Comment by glouel** [comment]
@ChristofMS 
Please give this version a shot and let me know if it works for you : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta2/Aerial.saver.zip

**Comment by ChristofMS** [comment]
Hey @glouel 

That compromise indeed works perfectly well! It definitely makes sense not to overcrowd the settings there. 

Thanks

**Comment by kikiwora** [comment]
It would be nice to have brightness controll (dimming) for external displays.
I use an application called Lunar, which allows me to controll brightness of an external monitor using native brightness keys and displays native brightness controll HUD (or at leas it appears to be native).

Is there any change Aerial will be able to integrate with Lunar to controll brightness of external monitors?
Or maybe, at least, control it directly using DDC/CI? (though in this case it might conflict with Lunar).

Not sure if I should create a new issue or not.
This idea seems to be realted to this issue.

**Comment by glouel** [comment]
Hey @kikiwora 

I haven't checked recently but the last time I looked at this, DDC/CI didn't work with Apple Silicon. This may have changed though and may be worth me rechecking ? What mac are you using right now ?

**Comment by kikiwora** [comment]
@glouel I am using an Apple Silicone Mac, in fact, a few of them — Mac Mini with M1 and Mac Pro 14" with M1 Pro.
And I can confirm that the DDC/CI works on both of them. Not a software gamut correction, but a real brightness/contrast/volume control.
I can read values from my displays too.

**Comment by glouel** [comment]
That's great, I4ll have to double check the status on that, there was a promising library I could use I think, but at the time the support was limited, I'll put a note on my list to have a look when I have a sec (lots of Sonoma stuff to fix first though)
