### ISSUE TITLE
HVEC shows black screen on 10.12

### ISSUE THREAD

**Issue by Joshfindit** [JohnCoates/Aerial#808]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac (27-inch, Late 2013)
- [x] macOS version: 10.12.6 (16G1114)
- [x] Monitor setup: Single Dell S2716DG Display connected to GTX 1070

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3269782/AerialLog.txt)

#### Description of issue / Feature request

H264 videos work properly, but 1080p HVEC and 4k HVEC do not display (just show a black screen, even if videos are fully cached)

Granted, h265 support was officially added to OSX in 10.13, so this may be a matter of simply showing an error.
IINA and other video players do, of course, play the 4k h265 without issue.

**Comment by glouel** [comment]
> H264 videos work properly, but 1080p HVEC and 4k HVEC do not display (just show a black screen, even if videos are fully cached)
> 
> Granted, h265 support was officially added to OSX in 10.13, so this may be a matter of simply showing an error.
> IINA and other video players do, of course, play the 4k h265 without issue.

Hi @Joshfindit 

Aerial uses AVFoundation to playback video, so basically if it doesn't play on QuickTime Player X on your MacOS version, it won't play in Aerial. We don't get a playback error according to the log so Aerial still tries to play it. 

Best I can do is restrict HEVC to 10.13+ in the UI (and unless you are unable, I'd highly suggest at least upgrading to 10.13 or 10.14), can't do much more than that.

**Comment by glouel** [comment]
@Joshfindit I disabled the format choice for < macOS 10.13, will be in next release. Sorry I can't do more but it's hard enough making Aerial work with each new version of macOS, and while I try to support older versions as best as I can, I can't just change the whole video playback system.

**Comment by Joshfindit** [comment]
No need to apologize. Your point is valid and I’m perfectly good with that as the solution.
Cheers
