### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by iraise** [JohnCoates/Aerial#81]
struck's a lot and does not play most of the time..image is only displayed 
unresponsive in settings panel

**Comment by JohnCoates** [comment]
I'm working on adding a button to download all the videos, that should fix that. Please bear with me, as offline mode and caching have just been added in the last couple of days. This shouldn't take much longer.

**Comment by resist888** [comment]
I'm having the same problem... the videos play if I manually activate the screensaver. If I let it activate automatically, the videos don't play. A still image is displayed instead.

I'm running Aerial 1.1 on El Capitan 10.11.1 on a MacBook Pro (Retina, 15-inch, Mid 2015) with a second monitor (Samsung) connected by HDMI

Thanks for listening, it's such a great screensaver.!

**Comment by maxinfos** [comment]
Hi there. The same problem happens with my computer, and my low speed internet connexion (2 Mbits/s). A pre-load button could be effectively fine for me. On screensaver start, only fixed image is displayed, like if the video couldn't be downloaded. So, i'm waiting for the next beta release.

**Comment by testzugang** [comment]
See https://github.com/JohnCoates/Aerial/issues/115 for a possible solution.

**Comment by resist888** [comment]
Thanks Meinhard

I’m not running Beta 4 - it doesn’t seem to support the different Aerial on a second display option.

**Comment by alistairmcmillan** [comment]
@resist888 John hasn't removed that feature. It's still there through all the betas including 4 and the latest beta 5.

**Comment by sharifmohammad** [comment]
Amar Arek Nam.
