### ISSUE TITLE
Beta 1.5.1 beta4 works perfectly under charger / black screen if on battery

### ISSUE THREAD

**Issue by ajalbawab** [JohnCoates/Aerial#813]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [MBP 2019 13" ] Mac model:
- [10.14.5 ] macOS version: 
- [ No monitor] Monitor setup:

#### Description of issue / Feature request

When Macbook is plugged in, everything works perfectly. If I unplug the MBP from charger, then screen goes black (even when videos being used are cached). I have replicated the issue and it is specific to when machine is connected to power vs. on battery.

**Comment by glouel** [comment]
Hi @ajalbawab 

Can you check the main Videos tab ? On the right you'll see an option called "Override on battery". My guess is you checked this, and selected "Power Saving" as the mode. 

If that's the case, uncheck the checkbox in front of this. Power saving mode is exactly what you are describing, not playing videos (so black screen) on battery. You can activate this on battery, or just on low battery. 

Let me know if that fixes your issue.

**Comment by glouel** [comment]
Closing this, please reopen if instructions above didn't fix your issue.
