### ISSUE TITLE
No Videos

### ISSUE THREAD

**Issue by Amclp** [JohnCoates/Aerial#816]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 2016 13" TB
- [ ] macOS version: 10.14.5
- [ ] Monitor setup: Only MacBook Display

#### Description of issue / Feature request

No Videos. If i start the screensaver  its just black, I see the clock and can exit the screensaver mode but there are now videos playing. Even in the preview it's just black. In the Videos folder its just empty. What can I do?

Thanks in Advance

**Comment by glouel** [comment]
Hi @Amclp 

Did you just install Aerial ? Or did you upgrade and nothing is working ?

Please confirm so I can help you through this.

**Comment by Amclp** [comment]
@glouel Thanks for the answer!
I just downloaded it. I tried the normal version first, but that didn't work so i tried the newest beta, still the same problem.

**Comment by glouel** [comment]
Ok thanks a lot ! 

Aerial needs to download videos online in order to work, so just to be clear, you'll need network connection. Here's my suggestion:

Go to System Preferences > Screen Savers, make sure Aerial is slicked on the left in your screensaver list. If you wait a tiny bit, on the right there's a black screen, can you tell me if it does change to a video playing ? 

Then open Aerial settings. 

Pick your "Preferred video format" on the right if you want (you can change it later and keep default for now). Then try to download a video of your choice (click the + button next to one). This may take some time depending on your connexion. You'll see a progress thing next to it. When done, that video will be cached. 

Now close this and launch your screensaver (if you have a hot corner) and wait a couple of seconds, your video should start playing ? If it does not (this may be related to another bug), can you try pressing "space bar" ? 

Let me know how all that goes !

**Comment by Amclp** [comment]
So I'm waiting but nothing changes.
And by settings you mean in the Screensaver Settings of Aerial right?
When I try to click on the + button next to the text: "Download Video" it is just blank.

**Comment by glouel** [comment]
> So I'm waiting but nothing changes.

Ok that's weird. 

> And by settings you mean in the Screensaver Settings of Aerial right?

Yep

> When I try to click on the + button next to the text: "Download Video" it is just blank.

No I mean next to a video, see here in red : 
![Capture d’écran 2019-06-19 à 11 24 47](https://user-images.githubusercontent.com/37544189/59753918-6c7dcc00-9285-11e9-9a43-fda2ed8f4fc4.png)

Pick one, click the + next to it. And let me know if it downloads.

**Comment by Amclp** [comment]
Problem is there is nothing xD
<img width="765" alt="Bildschirmfoto 2019-06-19 um 11 31 20" src="https://user-images.githubusercontent.com/51651479/59754152-d7c79e00-9285-11e9-8723-2785437a65da.png">

**Comment by glouel** [comment]
Ha ! Please press the "Show error" at the bottom left of the screen, you'll see a new window pop, can you try and make a screenshot of its content (you may need to resize it to show all). This is the error log that should help me tell you what's wrong. 

But it looks like Aerial has no network connection (are you running a firewall like Little Snitch ? You'll need to authorize Aerial to download). The list is also downloaded online so with no network connection, Aerial can't do much.

**Comment by Amclp** [comment]
Can' resize the window but I can copy it:

11:19:18 : avInit1 (537.0, 497.0, 296.0, 184.0)
11:19:18 : <AerialView: 0x7feac4f08420> AerialView setup init (V1.5.1beta4)
11:19:18 : Time Management initialized
11:19:18 : Display Detection initialized
11:19:18 : ***Display Detection***
11:19:18 : 1 display(s) detected
11:19:18 : 1cm = 50.393701544239036 points
11:19:18 : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1440, 900}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69733632, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8]
11:19:18 :        bottomLeftFrame (0.0, 0.0, 1440.0, 900.0)
11:19:18 : src orig : (0.0, 0.0)
11:19:18 : left 0.0 below 0.0
11:19:18 : [id=69733632, width=1440, height=900, bottomLeftFrame=(0.0, 0.0, 1440.0, 900.0), topRightCorner=(1440.0, 900.0), isMain=true, backingScaleFactor=2.0]
11:19:18 : (0.0, 0.0, 1440.0, 900.0)
11:19:18 : ***Display Detection Done***
11:19:18 : <AerialView: 0x7feac4f08420> isPreview : true
11:19:18 : Using : nil
11:19:18 : <AerialView: 0x7feac4f08420> no local player
11:19:18 : <AerialView: 0x7feac4f08420> setupPlayerLayer
11:19:18 : <AerialView: 0x7feac4f08420> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
11:19:18 : Using dot workaround for video driver corruption
11:19:18 : Manifest init
11:19:18 : cache to be used : Optional("/Users/aaron/Library/Caches/Aerial")
11:19:18 : custom file : file:///Users/aaron/Library/Caches/Aerial/customvideos.json
11:19:18 : No customvideos.json Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „customvideos.json“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSFilePath=/Users/aaron/Library/Caches/Aerial/customvideos.json, NSUnderlyingError=0x600002a34630 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
11:19:18 : isManifestCached 10 false
11:19:18 : isManifestCached 11 false
11:19:18 : isManifestCached 12 false
11:19:18 : 2019-06-19
11:19:18 : move
11:19:18 : Manifests files were not loaded in class
11:19:18 : Files were not already loaded in memory
11:19:18 : Fetching missing manifests online
11:19:18 : <AerialView: 0x7feac4f08420> backing change 2.0 isDisabled: false
11:19:18 : <AerialView: 0x7feac4f08420> startAnimation
11:19:18 : Error Domain=NSURLErrorDomain Code=-1005 "Die Netzwerkverbindung wurde unterbrochen." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x600002a10990 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x6000007ba990 [0x7fff978ed8e0]>{length = 16, capacity = 16, bytes = 0x100204567f0000010000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <1991C597-E018-4329-9E64-0738A1F0315D>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <1991C597-E018-4329-9E64-0738A1F0315D>.<3>"
), NSLocalizedDescription=Die Netzwerkverbindung wurde unterbrochen., NSErrorFailingURLStringKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, NSErrorFailingURLKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, _kCFStreamErrorDomainKey=4}
11:19:18 : Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSErrorFailingURLStringKey=https://sylvan.apple.com/Aerials/2x/entries.json, NSLocalizedRecoverySuggestion=Möchtest du die Verbindung zu dem Server trotzdem herstellen?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <7BCD9A63-0242-468B-B7B6-F9824157B524>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <7BCD9A63-0242-468B-B7B6-F9824157B524>.<2>"
), NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden., NSErrorFailingURLKey=https://sylvan.apple.com/Aerials/2x/entries.json, NSUnderlyingError=0x600002a04150 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
11:19:18 : Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSErrorFailingURLStringKey=https://sylvan.apple.com/Aerials/resources.tar, NSLocalizedRecoverySuggestion=Möchtest du die Verbindung zu dem Server trotzdem herstellen?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <AB4A13B2-39E4-4B27-9CA5-9B10C8EEA1C8>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <AB4A13B2-39E4-4B27-9CA5-9B10C8EEA1C8>.<1>"
), NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden., NSErrorFailingURLKey=https://sylvan.apple.com/Aerials/resources.tar, NSUnderlyingError=0x600002a10060 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
11:19:18 : Fetching manifests all done
11:19:18 : Can't load entries.json from cached directory (tvOS12)
11:19:18 : Can't load tvos11.json from cached directory
11:19:18 : Can't load tvos10.json from cached directory
11:19:18 : No video to load, no internet connexion ?
11:20:16 : <AerialView: 0x7feac4f08420> stopAnimation
11:20:16 : pwc init2
11:20:16 : Aerial control panel V1.5.1beta4
11:20:16 : Cache size : 0 GB
11:20:16 : Poi Strings Provider initialized
11:20:16 : TVIdleScreenStrings.bundle is missing, please remove entries.json in Cache folder to fix the issue
11:20:16 : Defaulting to bundle
11:20:16 : path : /Users/aaron/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
11:20:16 : Community JSON : 73 entries
11:20:17 : Location services may be disabled, Night Shift can't detect Sunrise and Sunset times without them
11:20:17 : cvcinit2
11:20:17 : cvcawake
11:20:17 : wdl
11:21:14 : UI popupVideoFormat: 2
11:23:11 : <AerialView: 0x7feac4f08420> startAnimation
11:30:58 : <AerialView: 0x7feac4f08420> stopAnimation

**Comment by glouel** [comment]
Awesome, thanks a lot ! So, according to google translate "Die Netzwerkverbindung wurde unterbrochen" means your network connection was interrupted. The other one talks about not being able to establish a SSL connexion. 

Can you tell me if you are running your computer on a home network or some corporate environment ? Maybe you are behind a proxy ? Can you tell me more about your network situation so I can narrow it down ?

Something is blocking Aerial to download in any case. Can you try this link in Safari, see if it works ? https://sylvan.apple.com/Aerials/2x/entries.json

That's what Aerial can't download (one of the list of videos). If it works in Safari and not in Aerial, could be either a local firewall (Little Snitch ?) or maybe a proxy bug. 

Please let me know so we can fix it!

**Comment by Amclp** [comment]
Okey Thanks!
Im running my Mac on my Home Network, I don't know what Little Snitch is sorry, and this comes up when I press the link:
<img width="1440" alt="Bildschirmfoto 2019-06-19 um 11 49 04" src="https://user-images.githubusercontent.com/51651479/59755577-748b3b00-9288-11e9-9202-8a2cfafdbfe8.png">

**Comment by glouel** [comment]
> Okey Thanks!
> Im running my Mac on my Home Network, I don't know what Little Snitch is sorry

No worries. Little Snitch is a firewall that let's you block certain applications to use your network connection (it's usually used for privacy control) : https://www.obdev.at/products/littlesnitch/index.html

Do you know if you are running any sort of tool that could block some application to use your internet connection on your Mac ? It looks like something is blocking Aerial here on your mac. 

> and this comes up when I press the link:
> <img alt="Bildschirmfoto 2019-06-19 um 11 49 04" width="1440" src="https://user-images.githubusercontent.com/51651479/59755577-748b3b00-9288-11e9-9202-8a2cfafdbfe8.png">

Ok that's good in a sense, so it's not a general network issue, it's more of an application issue. It really looks like you have something blocking Aerial network access. Can you think of some tool you may have installed for privacy or something, or maybe a friend/relative installed for you ?

**Comment by Amclp** [comment]
I have Kaspersky Internet Security as my Anti Virus maybe thats the problem. I try to turn it off and reinstall it. Thanks

**Comment by glouel** [comment]
This is probably it ! No need to reinstall Aerial, just disable Kaspersky or tell him to allow Aerial to use Internet (I don't use it so not sure how to do that, but usually there's some menu for this). Then relaunch the screen saver settings, you should see the list filled up and Aerial will now work ;)

**Comment by Amclp** [comment]
Tried it, still not working, these are the new Errors:
12:06:35 : avInit1 (537.0, 497.0, 296.0, 184.0)
12:06:35 : <AerialView: 0x7fa13044e320> AerialView setup init (V1.5.1beta4)
12:06:35 : Time Management initialized
12:06:35 : Display Detection initialized
12:06:35 : ***Display Detection***
12:06:35 : 1 display(s) detected
12:06:35 : 1cm = 50.393701544239036 points
12:06:35 : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1440, 900}, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69733632, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}]
12:06:35 :        bottomLeftFrame (0.0, 0.0, 1440.0, 900.0)
12:06:35 : src orig : (0.0, 0.0)
12:06:35 : left 0.0 below 0.0
12:06:35 : [id=69733632, width=1440, height=900, bottomLeftFrame=(0.0, 0.0, 1440.0, 900.0), topRightCorner=(1440.0, 900.0), isMain=true, backingScaleFactor=2.0]
12:06:35 : (0.0, 0.0, 1440.0, 900.0)
12:06:35 : ***Display Detection Done***
12:06:35 : <AerialView: 0x7fa13044e320> isPreview : true
12:06:35 : Using : nil
12:06:35 : <AerialView: 0x7fa13044e320> no local player
12:06:35 : <AerialView: 0x7fa13044e320> setupPlayerLayer
12:06:35 : <AerialView: 0x7fa13044e320> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
12:06:35 : Using dot workaround for video driver corruption
12:06:35 : Manifest init
12:06:35 : cache to be used : Optional("/Users/aaron/Library/Caches/Aerial")
12:06:35 : custom file : file:///Users/aaron/Library/Caches/Aerial/customvideos.json
12:06:35 : No customvideos.json Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „customvideos.json“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSFilePath=/Users/aaron/Library/Caches/Aerial/customvideos.json, NSUnderlyingError=0x600002c494d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
12:06:35 : isManifestCached 10 false
12:06:35 : isManifestCached 11 false
12:06:35 : isManifestCached 12 false
12:06:35 : 2019-06-19
12:06:35 : move
12:06:35 : Manifests files were not loaded in class
12:06:35 : Files were not already loaded in memory
12:06:35 : Fetching missing manifests online
12:06:35 : <AerialView: 0x7fa13044e320> backing change 2.0 isDisabled: false
12:06:35 : <AerialView: 0x7fa13044e320> startAnimation
12:06:35 : Error Domain=NSURLErrorDomain Code=-1005 "Die Netzwerkverbindung wurde unterbrochen." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x600002c42be0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x60000018ee40 [0x7fff978ed8e0]>{length = 16, capacity = 16, bytes = 0x100204567f0000010000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <4CEA5077-FC8B-4017-8B66-530B3D077277>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <4CEA5077-FC8B-4017-8B66-530B3D077277>.<3>"
), NSLocalizedDescription=Die Netzwerkverbindung wurde unterbrochen., NSErrorFailingURLStringKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, NSErrorFailingURLKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, _kCFStreamErrorDomainKey=4}
12:06:35 : Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSErrorFailingURLStringKey=https://sylvan.apple.com/Aerials/resources.tar, NSLocalizedRecoverySuggestion=Möchtest du die Verbindung zu dem Server trotzdem herstellen?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <6BEAB140-FF91-49DD-8247-DFF50B8CFEB3>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <6BEAB140-FF91-49DD-8247-DFF50B8CFEB3>.<1>"
), NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden., NSErrorFailingURLKey=https://sylvan.apple.com/Aerials/resources.tar, NSUnderlyingError=0x600002c60870 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
12:06:35 : avInit1 (537.0, 497.0, 296.0, 184.0)
12:06:35 : <AerialView: 0x7fa130653e30> AerialView setup init (V1.5.1beta4)
12:06:35 : <AerialView: 0x7fa130653e30> isPreview : true
12:06:35 : Using : nil
12:06:35 : <AerialView: 0x7fa130653e30> no local player
12:06:35 : <AerialView: 0x7fa130653e30> setupPlayerLayer
12:06:35 : <AerialView: 0x7fa130653e30> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
12:06:35 : Using dot workaround for video driver corruption
12:06:35 : <AerialView: 0x7fa13044e320> stopAnimation
12:06:35 : <AerialView: 0x7fa130653e30> backing change 2.0 isDisabled: false
12:06:35 : <AerialView: 0x7fa130653e30> startAnimation
12:06:35 : Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSErrorFailingURLStringKey=https://sylvan.apple.com/Aerials/2x/entries.json, NSLocalizedRecoverySuggestion=Möchtest du die Verbindung zu dem Server trotzdem herstellen?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <9395B59D-0C75-41AC-8E80-6098244D04A9>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <9395B59D-0C75-41AC-8E80-6098244D04A9>.<2>"
), NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden., NSErrorFailingURLKey=https://sylvan.apple.com/Aerials/2x/entries.json, NSUnderlyingError=0x600002c42d00 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
12:06:35 : Fetching manifests all done
12:06:35 : Can't load entries.json from cached directory (tvOS12)
12:06:36 : Can't load tvos11.json from cached directory
12:06:36 : Can't load tvos10.json from cached directory
12:06:36 : No video to load, no internet connexion ?
12:06:39 : <AerialView: 0x7fa130653e30> stopAnimation
12:06:39 : pwc init2
12:06:40 : Aerial control panel V1.5.1beta4
12:06:40 : Cache size : 0 GB
12:06:40 : Poi Strings Provider initialized
12:06:40 : TVIdleScreenStrings.bundle is missing, please remove entries.json in Cache folder to fix the issue
12:06:40 : Defaulting to bundle
12:06:40 : path : /Users/aaron/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
12:06:40 : Community JSON : 73 entries
12:06:40 : Location services may be disabled, Night Shift can't detect Sunrise and Sunset times without them
12:06:40 : cvcinit2
12:06:40 : cvcawake
12:06:40 : wdl

**Comment by glouel** [comment]
Looks like the same exact errors. So it looks like you maybe didn't completely disable it ?

**Comment by glouel** [comment]
This link may be helpful : 

https://smallbusiness.chron.com/disable-kaspersky-firewall-53591.html

What you want to disable is the firewall component (what blocks internet traffic). That or tell it to allow Aerial access.

**Comment by Amclp** [comment]
Thanks for the Support, unfortunately the Mac Version of Kaspersky does not have a firewall plugin, but I disabled the firewall on my mac, nothing happened, after i activated it and set a exception for the system preferences it worked!

 Thank you sooo much for helping me!!! :D

Have a good day!

**Comment by glouel** [comment]
Awesome ! Glad to hear you made it work !

And no worries, happy to help, have a good day too :)
