### ISSUE TITLE
prevents display sleep 

### ISSUE THREAD

**Issue by octothorpe8** [JohnCoates/Aerial#82]
When Aerial is running, screen never sleeps, ignoring preference set in Energy Saver control panel.

2011 Mac Mini, running 10.11.1 (15B42)

**Comment by Tuinslak** [comment]
Same here, seems to happen when magsafe is connected.

**Comment by octothorpe8** [comment]
(I'm closing this since there are already other issues opened with this same bug)

**Comment by Markyt1977** [comment]
mark tegeda
On Oct 31, 2015 2:20 PM, "octothorpe8" <notifications@github.com> wrote:
>
> Closed #82.
>
> —
> Reply to this email directly or view it on GitHub.

mark tegeda
