### ISSUE TITLE
Catalina External Drive Use for Cache

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#823]
So I took the plunge into Catalina since #815 

The big issue for me is that it seems not to recognize my location already has cached files. 

So, the cache location reset (that's due to my own error this time, however, of launching the Screen Saver Settings without the external drive connected) however, from there trouble ensued: 

1. Cache Tab
2. Change Cache Location to a folder that currently has ALL screen savers previously downloaded in Mojave (28+GB)
3. Enter: /Volumes/DRIVENAME/Screen Savers
4. Change takes effect
5. Quit System Preferences
6. Re-open
7. Note that videos are "waiting" to be downloaded in home tab
8. Note under Cache: 
![Screen Shot 2019-06-28 at 22 36 38](https://user-images.githubusercontent.com/18543749/60378739-3236cc00-99f5-11e9-9bcf-3482b21319c2.jpg)

I also tested just to be sure that it would in fact re-download videos are sure enough it does.

**Comment by glouel** [comment]
I assume you are running 1.5.1beta7 right ? I didn't have a chance to test if we had access to external volumes yet, with sandboxing that was a bit unclear to me. 

I'll have a look but we may no longer have access with current permissions.

(New downloads always go in the container in any case in Catalina)

**Comment by glouel** [comment]
@ZV00 I just tested using a cache on a network drive, and indeed, that no longer works, I get this error. So mounted volumes are out for now, too...

`NSData failed to load cache file /Volumes/downloads-1/AerialCache/4KSDR/comp_HK_H004_C008_PSNK_v19_SDR_PS_20180914_SDR_4K_HEVC.mov`

I'm filling another radar to hopefully get some guidance on where they expect 3rd party screensavers to go, we'll see what they say if anything.

**Comment by ZV00** [comment]
> I assume you are running 1.5.1beta7 right ? I didn't have a chance to test if we had access to external volumes yet, with sandboxing that was a bit unclear to me.
Yes

> I'm filling another radar to hopefully get some guidance on where they expect 3rd party screensavers to go, we'll see what they say if anything.
Very well! Will have to just continue to stream then in the mean time!

**Comment by ZV00** [comment]
Whoops just saw the edit!

`12:11:27 : Community JSON : 73 entries
12:11:27 : Using exiting customCacheDirectory : /Volumes/SSDStorage/Screen Savers
12:11:27 : cache to be used : Optional("/Volumes/SSDStorage/Screen Savers")
12:11:28 : Total videos processed : 73 callbacks : 0`

However it then errors:

`12:11:27 : No customvideos.json Error Domain=NSCocoaErrorDomain Code=260 "The file “customvideos.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/minime/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json, NSUnderlyingError=0x600003948990 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

Weirdly enough, during this test, it failed to display any screensaver on either of my two monitors. However, a second test did work so I assume that was just a connection/large file issue.

**Comment by glouel** [comment]
That error (custom videos.json) is not the one you’re looking for. My guess is you will have the same one I had (nsdata failed).

**Comment by ZV00** [comment]
> That error (custom videos.json) is not the one you’re looking for. My guess is you will have the same one I had (nsdata failed).

Yes, that error does exist. If you want the full log I can supply it. But sounds like you've already figured out what's going on.

**Comment by glouel** [comment]
Yep, no need, thanks ! I filled the radar and will let you know how it goes.

**Comment by amy1499** [comment]
Don't know whether this has been mentioned anywhere else, but I created a symlink Alias within 

/Users/user/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial

and the screensaver works just fine with videos stored on an external drive. Had to restart though. 10.15 19A487m and Aerial 1.5.7b

**Comment by glouel** [comment]
> Don't know whether this has been mentioned anywhere else, but I created a symlink Alias within
> 
> /Users/user/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial
> 
> and the screensaver works just fine with videos stored on an external drive. Had to restart though. 10.15 19A487m and Aerial 1.5.1 beta7

@amy1499 that's interesting, we had conflicting reports about that in early betas, but maybe things have improved a bit. I'm a bit puzzled though about exactly what you are symlinking to, are you symlinking your whole cache to the `Application Support/Aerial`, not having a real directory there ? 

FYI this may cause some issues in the long run with downloading new videos. It may be safer to create a `External Cache` folder in there, and use that as a symlink destination, then set the cache to that `External Cache` folder. 

This is still confusing for me I really need to have a better look at this ! Thanks in any case, that's really helpful info.

**Comment by amy1499** [comment]
Using Symbolic Linker by Nick Zitzmann Ver 2.11 and created an Alias like that. I have learned there is a difference between this approach and simply creating an Alias using Finder.
All videos are/were cached and stored on an external HD. The only thing I did was pretty much copying that symlink into the location mentioned above.

If you need me to test other settings let me know.

**Comment by glouel** [comment]
Thanks for the info, I'll try to do some more testing tomorrow to see if we have read/write access. 

If you have a sec in the meantime, if you could enable debug logging and log to disk in Aerial's control panel, then close System Preferences, then launch Aerial once, then paste that log, that might give me some info too ! Thanks !

**Comment by amy1499** [comment]
There you go. I tested the setting while being offline.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3342956/AerialLog.txt)

**Comment by glouel** [comment]
Ok so, looks like your workaround fully works ! Since you actually saw the AerialLog.txt being created there, that means we have write access to your external drive this way ! I'll have a more thorough look tomorrow but that's great news indeed.

**Comment by glouel** [comment]
@amy1499 

So, I had a try here and I can't get it to work for write access on a local directory, or even on read access on a read only directory. 

I'm wondering, is there any chance you disabled SIP on your system, or something akin to that? Anything particular about your system you could share (Hackintosh maybe which would have SIP disabled ?) ?

**Comment by amy1499** [comment]
Nice catch, it is indeed. SIP disabled. Cant turn it on though in 10.15 beta 3. Ill keep you posted.

**Comment by glouel** [comment]
Ha no worries ! Thanks for the confirmation it clears things up ! SIP should disable sandboxing so it makes 100% sense that you can do it while others can't.

**Comment by glouel** [comment]
I put a mention of the workaround to disable SIP as it's the only known way to use a mounted volume that we know of in the Catalina topic, so closing this one.
