### ISSUE TITLE
[Catalina] Reset to Default and Show In Finder buttons under Cache fail to work

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#824]
In addition to #823 I went to reset the Cache back to default and found out that the **Reset to Default** and **Show in Finder** buttons under the **Cache** tab fail to work when reverting back from the external drive. 

Clicking them simply has no action taken. 

Wanted to make this a separate issue as it seems unrelated to the other one.

**Comment by glouel** [comment]
Yeah reset to default doesn't work anymore with the path split, will fix. As for "Show in finder", it does work if we are allowed to touch the files. But since you couldn't reset, we probably were denied opening finder there ;) Will fix in next beta thanks.

**Comment by glouel** [comment]
This should be fixed in beta8 btw, this was a beta bug so closing this one ! Reopen if you see it misbehaving.
