### ISSUE TITLE
No Aerial.Saver file

### ISSUE THREAD

**Issue by nzlittleman** [JohnCoates/Aerial#833]
Hi guys, I've tried downloading this several times directly and via GitHub Desktop.

Each time the aerial.saver file which is referred to for installation is missing.

I've checked my anti-virus and it hasn't blocked or quarantined any files.

**Comment by glouel** [comment]
Hi @nzlittleman !

The Aerial.saver file is not in the git repository. You have to download them from the release page :  https://github.com/JohnCoates/Aerial/releases

The repository will only give you the source code.
