### ISSUE TITLE
Feature request - allow alternative video sources 

### ISSUE THREAD

**Issue by homiak** [JohnCoates/Aerial#834]
Currently there is only a limited list of videos available in Aerial and there is no easy way to add other videos to the list (apart from you own local videos). 

It's great that now I can add my own drone footage, however, there is no way I can play my friend's drone footage from youtube or vimeo or any other place. 
I understand that it may be difficult or outright illegal to download videos from youtube. 
However,  many creators would only be happy (at least I would be) to make their video available to the Aerial audience in other ways. 

Could you guys define what this other way could be (e.g. make a file downloadable via http, have a text file next to it describing what the video is about, maybe someone would be happy to host those files? Maybe add a feature "allow sharing" for local videos and use P2P to share those footage between the users?) And then make those alternative videos available to other users? 

Drone footage is abandon nowadays and I think letting the users share their footage with others inside Aerial would let you build the community around this project and ensure it long term survival.

**Comment by glouel** [comment]
> It's great that now I can add my own drone footage, however, there is no way I can play my friend's drone footage from youtube or vimeo or any other place.
> I understand that it may be difficult or outright illegal to download videos from youtube.

I have no idea whether it's against their terms of services as I rarely use those sites, but my understanding is that tools like youtube-dl exist and should let you locally download content (or they may have some download option too there ?) which you then can play through Aerial's existing local feature (you may need to convert it with ffmpeg).  One should read their TOS before going this route though and check that's ok. 

> However, many creators would only be happy (at least I would be) to make their video available to the Aerial audience in other ways.

I don't think those hosting sites are appropriate for what you'd want if it's against their TOS. 

> Could you guys define what this other way could be (e.g. make a file downloadable via http, have a text file next to it describing what the video is about, maybe someone would be happy to host those files? Maybe add a feature "allow sharing" for local videos and use P2P to share those footage between the users?) And then make those alternative videos available to other users?

While the UI doesn't allow it for custom videos, you can already add your own http videos to be streamed/cached, by manually editing the entries.json file. You'll have to add an entry into the `assets` array and provide at least one URL.  

Adding it to the UI should be easy enough. But hosting/sharing, quite frankly, that's very much out of the scope of the project. If there are free ressources that host and allow pure http streaming/downloading/caching of mp4 videos, I'd consider adding the http url option on top of local files. But does that even exist ? I did look for some good quality footage to download and didn't see much (didn't spend much time on it to be fair). This is probably not a good business model, so I'm doubtful. If you know some, let me know ? 

P2P, then handling some sort of repository/sharing has many implications in case of misuse, so I don't see myself adding that then be liable in some jurisdiction. 

> Drone footage is abandon nowadays and I think letting the users share their footage with others inside Aerial would let you build the community around this project and ensure it long term survival.

I'm not convinced that free of rights, not behind a monetizing platform like youtube, quality drone footage is that abundant online ? 

Don't get me wrong, I understand the spirit of what you want, I'm not just convinced that kind of hosting exists.

**Comment by tkisme** [comment]
Note: if convert from other video 
```
ffmpeg -i input.mp4 -c:v hevc_videotoolbox -b:v 0  -tag:v hvc1 out1.mp4
```
