### ISSUE TITLE
Second display still displays screensaver sometimes when the option for the screensaver to be only shown on the main display.

### ISSUE THREAD

**Issue by Monkiey** [JohnCoates/Aerial#837]
The screensaver is still displaying on my second display(Monitor)when I enable the option for the screensaver to be only on my main display

**Comment by glouel** [comment]
> The screensaver is still displaying on my second display(Monitor)when I enable the option for the screensaver to be only on my main display

Hi @Monkiey 

That's... weird. Gonna need some more info:
- When you say it shows in your second display, do you mean instead of your main display, or do you mean it shows in both ? 
- Can you tell me which version of Aerial and macOS you are using ? 
- Also, some more context about your screens. Is your second display always connected or are you unplugging/plugging it often ?

And also, as always, a log would be helpful.

**Comment by owellsjr** [comment]
Same deal for me. I'm running Aerial 1.5 beta 10 on macOS Catalina public beta 4. I have a 2017 MacBook connected via USB-C to an external monitor. I have Aerial configured to play on the "Main Display" which is the external monitor. In macOS Catalina public beta 3 it would always display on the MacBook display. But now in macOS Catalina public beta 4 it always displays on both displays.

**Comment by glouel** [comment]
Hi @owellsjr !

So, if you are running Catalina, that's part of the large list of things that don't work quite yet. Apple has completely changed the way 3rd party screensavers work and there's still a lot of issues that needs to be resolved on Apple's end. 

If you have a second, I would suggest you have a look at the top and last couple of posts in this thread, they sum up the changes made in Catalina and what people are seeing so far : https://github.com/JohnCoates/Aerial/issues/801

FYI I do have radars filled with Apple regarding all those issues, the one about the multi monitor setup says that a fix is coming in next beta (which didn't drop yesterday with the iOS ones, sadly), so there's hope !

I suggest you keep an eye on the thread I linked for updates on fixes/new betas for Catalina.

**Comment by glouel** [comment]
@Monkiey & @owellsjr 

Please try latest beta with a workaround for Catalina's bug : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta11/Aerial.saver.zip 

It should fix multi monitor bugs.

**Comment by owellsjr** [comment]
It's playing on the main display as expected now. The playback is quite "choppy" in macOS Catalina compared to macOS Mojave ... but I'm not sure if that's a screensaver or OS issue.

**Comment by glouel** [comment]
@owellsjr good!

Regarding your issue, is it just choppy at the start or all throughout ? I do see a small choppiness at the start when using HDR videos on my 2015 iMac here, I don't think I have the choppiness in SDR. This is a system thing in any case

**Comment by owellsjr** [comment]
It's throughout. But I have a 2017 12-inch MacBook with 8 GB of RAM. Trying to push 4K HDR video over USB-C to an external monitor. It's altogether likely that I'm just taxing the capabilities of my machine!

**Comment by glouel** [comment]
If I'm not mistaken, 2017 Macbook 12" has a Kaby Lake generation CPU, which, I think, doesn't have full HEVC GPU acceleration. So you might be decoding on the CPU which is quite taxing. I would suggest you give a shot to H.264 1080p mode instead on that machine. Or if you are very patient, you could transcode the 4K HDR videos to H.264.

In any case, you can also try to go to Aerial's folder where the videos are stored, and open one in Quicktime (we use the same playback API). Using Activity Monitor you should pretty quickly if your CPU is pegged or not.

**Comment by owellsjr** [comment]
1080p HEVC was better. But 1080p H264 was smooth as butter. Thanks!

**Comment by Monkiey** [comment]
The screensaver shows up on both of the displays. I am using Aireal version
1.50 and mac os 10.14.6.

**Comment by glouel** [comment]
@Monkiey please install latest beta and let me know if it fixes things. Download here : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta11/Aerial.saver.zip

**Comment by glouel** [comment]
Closing with the release of 1.6.0 finale.

**Comment by aroraakshit** [comment]
Still unable to have Aerial screensaver on second display. 
Aerial Saver 1.6.4
MacOS Catalina 10.15 Beta (19A487m)
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4051888/AerialLog.txt)

**Comment by glouel** [comment]
> Still unable to have Aerial screensaver on second display.
> Aerial Saver 1.6.4
> MacOS Catalina 10.15 Beta (19A487m)
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4051888/AerialLog.txt)

Hi @aroraakshit 

That's 10.15 public beta1, or beta2, right ? There was a bug in those early Catalina beta where 3rd party screen savers would only work on the main screen. I did check, it got fixed only in dev beta5 of Catalina. I would strongly advise you upgrade from that build if you can, nothing I can do on that one sorry.
