### ISSUE TITLE
Couldn't download video

### ISSUE THREAD

**Issue by cnBruceHong** [JohnCoates/Aerial#840]
because of GFW，I can't download video by clicking the download button in this plugin.

**Comment by glouel** [comment]
Hi @cnBruceHong !

I know there are a few users in the same situation as you that had to manually download the videos from another non firewalled machine. We do have instructions of the files you need here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/OfflineMode.md

I also have some instructions about automating the process here (you may need to change the destination cache if you are not using macOS 10.15) : https://github.com/JohnCoates/Aerial/issues/801#issuecomment-500205534 

Side question, do you happen to know if Apple TV is sold in China directly by Apple ? There may be a mirror on the other side of the firewall if so, but not being there, I don't know.

**Comment by cnBruceHong** [comment]
Thanks!

 Apple TV is not currently available in China. 😭

**Comment by glouel** [comment]
> Thanks!
> 
> Apple TV is not currently available in China. 😭

Thanks for the confirmation. Good luck grabbing the videos!
