### ISSUE TITLE
Suggestion: suspend rendering if the screen is off.

### ISSUE THREAD

**Issue by nsayer** [JohnCoates/Aerial#841]
Sometimes when my mac is sitting with the screen off you can hear the fans going because Aerial is still rendering the video(s).

It'd be nice if there was a checkbox to say that if the physical screen is in power-save that Aerial should just not bother.

**Comment by glouel** [comment]
> Sometimes when my mac is sitting with the screen off you can hear the fans going because Aerial is still rendering the video(s).
> 
> It'd be nice if there was a checkbox to say that if the physical screen is in power-save that Aerial should just not bother.

Hi @nsayer 

Can you clarify what you mean by screen off ? Are you manually doing this ? If you go into "power saving" (the lightbulb icon) in System Preferences, what did you set here for Shutdown screen after... ? 

As far as I know, when macOS shutdowns your screen, it also closes Aerial. To give you an idea, here's my setup, in Desktop & Screen savers, bottom left of the screen I have "start after 20 mins", then in "power saving" I have 30. Aerial will only run for 10 mins. Logs tell me this work pretty well at least on my system. 

I would suggest you use those system settings to fix an upper limit for macOS to shutdown your screen if you don't. 

Let me know if you need more info, and if so, I'll need more info on which macOS version you are running and which Aerial version too.
