### ISSUE TITLE
Feature request - send in key combination when saver starts and finishes

### ISSUE THREAD

**Issue by k00d1** [JohnCoates/Aerial#844]
#### Description of issue / Feature request

Like requested in the topic, I would like to be able to send combination of key presses when the screensaver starts, to dim my external display. And vice versa, when screensaver stops, it would brighten up.

Can't get the dimming working as I've got Mac mini with non-apple display.

**Comment by glouel** [comment]
Hi @k00d1 

I'm not sure that's possible for a couple of reasons. 

First, and that's a big one, starting with Catalina we no longer are allowed to control the keyboard it seems. We can no longer intercept keypress, and while I haven't checked, we probably can't create them either. Features such a pressing a key to skip to next video no longer work with no clear way to get them back.

But more importantly, I don't think that could work at all. If we send a keypress when the screensaver starts, I'm fairly sure that it will be intercepted by macOS (if we don't intercept it ourselves, which we wouldn't want) and just kill us right there, completely defeating the purpose.

**Comment by k00d1** [comment]
Hi glouel!

Thanks for the clear reply. Yeah I kind of figured that would need somekind of internal timer to setup the first combination send, but didn't know about the restrictions.

Thanks for clearing this out fast and swiftly. Have a great week!

**Comment by glouel** [comment]
No worries! The big problem is that macOS is the one starting the screensaver and stopping it by looking at keypresses, we are just a plugin to the system with little control in all this (and less and less in Catalina, sadly !). 

Have a great week too!
