### ISSUE TITLE
Feature Request - Display music details if music is playing

### ISSUE THREAD

**Issue by aidenmitchell** [JohnCoates/Aerial#846]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac 21.5" Late 2012
- [x] macOS version: MacOS Mojave 10.14.6
- [x] Monitor setup: 1 monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

It'd be cool if on the screensaver, above the video description, the name and artist of the current song playing on my Mac could show up. I use Spotify, but iTunes would be good to add too.

**Comment by ilovecats516** [comment]
That's too bad it won't work come Catalina. Hopefully, there will be a workaround, or Apple will loosen their security a tad.

**Comment by glouel** [comment]
Time passed a bit, but 2.3.4beta3 includes both Apple Music and Spotify integration ;)
 
![Capture d’écran 2021-07-02 à 18 27 53](https://user-images.githubusercontent.com/37544189/124310405-6a38f280-db6c-11eb-907f-5eff140f5a84.jpg)

**Comment by Pcar17** [comment]
@glouel,

This is a great idea! However, I'm not seeing the Apple Music track that's playing showing up on an M1 MBA running macOS 11.4 (20F71) running the latest build, 2.3.4beta3.

Is there anything that I have to do in order to activate it besides "enabling" it?  Or anything I should do to diagnose?

Thanks!

**Comment by glouel** [comment]
@Pcar17 
The track that plays when Aerial starts will not show up, but if you press next on your keyboard (that doesn't interrupt the screensaver) the track change should be detected. If it's not let met know I'll try to investigate, thanks !

**Comment by Pcar17** [comment]
@glouel,

Wow....what too you so long to respond! Maybe 15 seconds? 

lol!

But, yes, that was it.  It works perfectly.  What a nice feature!

**Comment by glouel** [comment]
Haha I just had the notification and was around ;) 

Check here for more info on the current limitations and what will change : https://ko-fi.com/post/Apple-Music-and-Spotify-integration-W7W056GL2
