### ISSUE TITLE
Login revealed on click only

### ISSUE THREAD

**Issue by sirschuyler** [JohnCoates/Aerial#847]
When auto-update is enabled, click on trackpad is only way to reveal login details (user/password field).

When auto-update is disabled, any trackpad movement, click or key press reveals login details—this is the expected behavior.

Love the screensaver. Thanks for your excellent work!

---
MacBook Pro (Retina, 15-inch, Early 2013)
macOS Mojave v10.14.6
Built-in Retina Display

**Comment by glouel** [comment]
Hi @sirschuyler !

I guess you only see this bug once a day if auto update is enabled (Auto update only runs once a day) ? 

A common culprit is firewall application Little Snitch, if by any chance you are running that one, you may need to add a rule to it so it doesn't steal focus from Aerial. You can read more about that in this issue: https://github.com/JohnCoates/Aerial/issues/814#issuecomment-511051452

What happen most of the time is some application pops up and steal focus if Aerial does an auto update check. Some other tools may cause this interaction too (some keyboard app, some reminder apps etc). 

Let me know if you happen to run one of these tools.

**Comment by sirschuyler** [comment]
Hey @glouel !

Bug is actually persistent, if auto update checked, then trackpad click is the only option to reveal login details whenever screen saver is "running". 

Not using Little Snitch, nor a keyboard app, only possible reminder app (outside of Apple Reminders) is Fantastical 2, but maybe it's some other app stealing focus…  I'll keep an eye on it and mess with auto update enabled/disabled some more in the meantime.

Thanks.

**Comment by glouel** [comment]
@sirschuyler thanks for your answer. Interesting that it persist, hmm. Apple's reminder is fine and I doubt Fantastical is behind it either. 

Another user wrote a nice script that shows which application has focus here : https://gist.github.com/luckman212/91cdd9a08e98a9f01214bdfde3057e85

If you have a second, do you think you could try running it and see if it tells you anything ? 

Thanks !

**Comment by glouel** [comment]
@sirschuyler if you're still looking at this, i remembered another issue related to what you may be experiencing, please check this : https://github.com/JohnCoates/Aerial/issues/768#issuecomment-491473659

Freel free to reopen if you want more help on this.
