### ISSUE TITLE
Can't remove custom videos

### ISSUE THREAD

**Issue by RidgeSTD** [JohnCoates/Aerial#848]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: MBP 13inch 2016
- [X] macOS version: Mojave 10.14.6
- [X] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I succeeded adding custom screen saver video but after accidentally renamed the file name and found that Aerial isn't able to detect the change file. After rescanning the folder there are two video files existing in custom file list, one valid the other not.

Then it appears that there is no way(or at least not easy to find, light right click, delete key, fn+delete etc.) to remove a (invalid) video. My current solution is to edit the `customvideos.json` file. But maybe a GUI solution would be better?

**Comment by glouel** [comment]
Hi @RidgeSTD 

Can confirm, editing the JSON is the only way right now and it's clearly not intuitive. I'll add that soonish, thanks for raising the issue !

**Comment by wtrdk** [comment]
Hi, I also experience this issue. Where can I find the JSON so I can edit it? Thanks!

**Comment by glouel** [comment]
> Hi, I also experience this issue. Where can I find the JSON so I can edit it? Thanks!

Hi @wtrdk, the JSON by going to Aerial's preference pane, then Advanced tab and Show in Finder. The file is called `customvideos.json`

In Catalina, that's : `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json`

**Comment by wtrdk** [comment]
Thanks!

Verstuurd vanaf mijn iPhone

**Comment by glouel** [comment]
You can now right click videos and groups to remove them from the JSON, I can't remember when I added this but this is definitely in 1.8.0 : https://github.com/JohnCoates/Aerial/releases/download/v1.8.0/Aerial.saver.zip
