### ISSUE TITLE
New underwater scenes

### ISSUE THREAD

**Issue by jhewell56** [JohnCoates/Aerial#849]
Any plans to add the new tvOS 13 underwater screens to the Aerials repertoire?

**Comment by glouel** [comment]
Hi @jhewell56 

Yes, but as far as I know they are not released yet. See this post for more info : https://github.com/JohnCoates/Aerial/issues/801#issuecomment-534675994

**Comment by jhewell56** [comment]
Oh, ok. I saw them described on the tvOS13 page (software was released yesterday); didn't know if the screensavers were in that release.  Looking forward to them....

**Comment by glouel** [comment]
@jhewell56 beta13 is up with the new videos : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta13/Aerial.saver.zip :)

**Comment by jhewell56** [comment]
Thanks!

J Hewell

**Comment by glouel** [comment]
Closing with the release of 1.6.0 finale.
