### ISSUE TITLE
Migrate setteings to new os installation

### ISSUE THREAD

**Issue by aloysiu3** [JohnCoates/Aerial#854]
I'm fairly new to all of this.
I'm trying to migrate _com.JohnCoates.Aerial.{UUID}.plist_ to a new installation of mac os so i don't have go through all the settings again. Isn't the UUID different for each installation? Will Aerial on a new mac installation pic up the .plist with the UUID from the old installation?

**Comment by glouel** [comment]
Hi @aloysiu3 !

I admit I don't know, but if you look in the `ByHost` folder on your mac, all the plist share the same UUID. So I'd suggest copying the UUID from another app and rename the plist that way. Let me know if that works.

**Comment by glouel** [comment]
Closing, feel free to reopen if needed
