### ISSUE TITLE
Windows Version ?

### ISSUE THREAD

**Issue by Tiino-X83** [JohnCoates/Aerial#858]
hello to you, would you be able to update the version for Windows? (https://github.com/cDima/Aerial/releases) Thanks :)

Sorry for my English, I use google translate

**Comment by glouel** [comment]
Hi @Tiino-X83 

Sorry, the Windows version is a completely separate project, we only link to it as a courtesy. It looks like the project hasn't been updated in a while though. 

But we only take care of the Mac version here, you have to ask for help on their own repository.
