### ISSUE TITLE
Intermittently unable to bring login interface from screensaver

### ISSUE THREAD

**Issue by Oclair** [JohnCoates/Aerial#861]
Screensaver can go into a state where it is not possible to bring up the login menu and instead will at best have a pointer with a black background.

#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
> Screensaver can go into a state where it is not possible to bring up the login menu and instead will at best have a pointer with a black background.

Hi @Oclair 

I'm going to need a bit more info:
- Aerial version:
- macOS version:
- Monitor setup:

Also, this is important, are you using a firewall or not (Little Snitch being a popular one) ?

Can you try going into Aerial settings, then Updates tab, then at the bottom, uncheck "Auto updates while the screensaver runs". 

Intermittent issues are usually caused by something interfering with auto updates (like Little Snitch).

**Comment by Oclair** [comment]
Aerial Version 1.6.1, on Mojave 10.14.6, Hackintosh GA-Z87N-WIFI i5 4670k ASrock AMD Radeon Vega 56 8GB 16DDR3, Acer S273HL Monitor.

This problem has been consistent for quite a while from several previous versions of Aerial and on the previous OS High Sierra.

Yes I do have little snitch 4.4.3 Nightly, Settings for "System Preferences via Screen Saver" is set to Allow All.

**Comment by glouel** [comment]
Very likely it's Little Snitch then. Please disable the auto-update setting I mentioned in my previous post. 

Reason behind is in the main project page with more info if you want to fix your Little Snitch settings : 

> **Are you using Little Snitch ?* You may need to configure your firewall to allow Aerial to connect to the internet. Also Little Snitch may include a rule that forbids connexions to `raw.githubusercontent.com`. This will block Aerial's automatic updates and can cause the screensaver to misbehave. We highly recommend you either remove that rule or disable Aerial's automatic updates. You can find more information in our [FAQ](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

**Comment by Oclair** [comment]
Sounds good thank you, great setting work around btw!
