### ISSUE TITLE
Screensaver running but unresponsive to input (keyboard, mouse, trackpad, sacrificial chicken, etc.)

### ISSUE THREAD

**Issue by jlocca** [JohnCoates/Aerial#863]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: iMac 27-inch, Late 2013
- [x] macOS version: 10.15 (stable version)
- [x] Monitor setup: no external monitors connected right now

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I love the screensavers. As mentioned in the title, though, I returned to my iMac & tried every bit of input I could think of to stop the screensaver -- mouse clicks, keyboard clicks (spacebar, ESC key, ENTER key). I even sacrificed a chicken in hopes of pleasing the screensaver gods. None of these inputs worked; so, I hung out and watched about 6 different screensavers (awesome!) before forcing the system to shut down. I noticed the clock (overlay when the screensaver is running) was stuck on 12:08 -- the time was actually 12:32 when I shut down.

**Comment by glouel** [comment]
Hi @jlocca may I guess that you are using Little Snitch (or another firewall) ? 

Please go to Aerial Settings and disable the auto update settings I circled : 

![Capture d’écran 2019-10-04 à 21 23 03](https://user-images.githubusercontent.com/37544189/66234167-41f93700-e6ed-11e9-843b-009ac6ea0f39.jpg)

This usually solve this issue. If you are using Little Snitch I put this mention on the front page that explains it a bit : 

> **Are you using Little Snitch ?** You may need to configure your firewall to allow Aerial to connect to the internet. Also Little Snitch may include a rule that forbids connexions to `raw.githubusercontent.com`. This will block Aerial's automatic updates and can cause the screensaver to misbehave. We highly recommend you either remove that rule or disable Aerial's automatic updates. You can find more information in our FAQ.

> I noticed the clock (overlay when the screensaver is running) was stuck on 12:08 -- the time was actually 12:32 when I shut down.

Someone else reported that one too once, I wonder if that's linked to the same issue you had or if it's something else, hmm. Please try the thing I circled above and let me know.

**Comment by cameleonhelp** [comment]
Hi

indeed this seems to work around the problem.
When the screen-saver is activated there is no problem to wake the Mac
This problem did not exist on Mojave in the same configuration, it's appear with Catalina update.
- Mac model: MacBook Pro 15 -inch, Late 2013
- MacOS version: 10.15 (stable version)
- Monitor setup: no external monitors connected right now

I'm not using Little Snitch

**Comment by glouel** [comment]
@cameleonhelp interesting, thanks for the feedback. Since that feature no longer work in Catalina anyway, I'll disable it in the next point update for 10.15+ until this gets resolved. 

Glad it's fixed for you in any case.

**Comment by jlocca** [comment]
Thank you for the quick response.
I do not use Little Snitch. The only firewall I see is the firewall built into macOS (Systems Preferences > Security & Privacy > Firewall).
![Screen Shot 2019-10-08 at 7 35 39 AM](https://user-images.githubusercontent.com/16841852/66405009-531c9f00-e99e-11e9-8307-53d0133fbf8d.png)


Okay, I unchecked both auto-update options ... **how will we know when a manual update is available?**

The first quick test showed I could stop the screensaver, as desired. I'll try several times throughout the week to see if the issue re-occurs & will report back if it does.
Thank you!

**Comment by glouel** [comment]
> Thank you for the quick response.
> I do not use Little Snitch. The only firewall I see is the firewall built into macOS (Systems Preferences > Security & Privacy > Firewall).

Ok thanks for confirming that !

> The first quick test showed I could stop the screensaver, as desired. I'll try several times throughout the week to see if the issue re-occurs & will report back if it does.

Awesome, thanks! 

> Okay, I unchecked both auto-update options ... **how will we know when a manual update is available?**

So now that we know it's ok, you can recheck the very first option (but DON'T recheck the second one, the auto install) ? This means Aerial will only check when you launch it's settings panel (you can also click the Check Now button to know if a new version is available). 

The entire update process sadly does not work at all in Catalina, that's part of a slew of bugs/limitations introduced with Catalina, you can read more in that top post here : https://github.com/JohnCoates/Aerial/issues/801 So clicking check now, you'll see update available, but if you say install the install will fail. You can use that in the meantime to know when an update is available and grab it from here. I know it's not a great experience but that's all I can do right now. The bug in question is pretty messy if you are interested : https://github.com/sparkle-project/Sparkle/issues/1476

I'm hopeful it will get fixed soon(ish). I'll release a 1.6.2 today or tomorrow that disable the auto install under catalina considering both your and @cameleonhelp 's experiences.

**Comment by jlocca** [comment]
Thank you!
