### ISSUE TITLE
Ability to center text on screen along with the current corner options.

### ISSUE THREAD

**Issue by fosbrader** [JohnCoates/Aerial#866]
I've always used the text in the left corners, but today I was looking at it and thought it might be interesting to see what it would look like centered on the top and bottom (time on top, description on bottom, or vice versa)

**Comment by glouel** [comment]
Hi @fosbrader 

Marking this as a "why not" !

**Comment by glouel** [comment]
Hi @fosbrader !

Took some time but I have that feature in beta, this is part of a large rewrite of the text feature, you can configure that in the new Info tab. 

![Capture d’écran 2019-12-18 à 19 15 24](https://user-images.githubusercontent.com/37544189/71111975-d5111b80-21ca-11ea-8911-a0ac8c0e0926.jpg)

Check out the beta here : https://github.com/JohnCoates/Aerial/releases/download/v1.6.5beta2/Aerial.saver.zip

**Comment by fosbrader** [comment]
This is incredible, great work, it’s exactly what I had in mind.

On Dec 18, 2019, at 12:16 PM, Guillaume Louel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @fosbrader<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffosbrader&data=02%7C01%7C%7Cd2811d70d2ac46422e7808d783e6626b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637122897820369318&sdata=H5qxAxbXnT%2BCSmSHS%2BwcBUrQlf5zqZWMZ%2F6fXWFke90%3D&reserved=0> !

Took some time but I have that feature in beta, this is part of a large rewrite of the text feature, you can configure that in the new Info tab.

[Capture d’écran 2019-12-18 à 19 15 24]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F37544189%2F71111975-d5111b80-21ca-11ea-8911-a0ac8c0e0926.jpg&data=02%7C01%7C%7Cd2811d70d2ac46422e7808d783e6626b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637122897820379329&sdata=d2aIVmiNkfi%2BFIVrhWR7BsuC35aH6BliPV2w141y4TA%3D&reserved=0>

Check out the beta here : https://github.com/JohnCoates/Aerial/releases/download/v1.6.5beta2/Aerial.saver.zip<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJohnCoates%2FAerial%2Freleases%2Fdownload%2Fv1.6.5beta2%2FAerial.saver.zip&data=02%7C01%7C%7Cd2811d70d2ac46422e7808d783e6626b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637122897820389334&sdata=HFjwM0zneZdhWsafx26rSr5IGKzYALf9f%2F8LY9jKlkc%3D&reserved=0>

**Comment by glouel** [comment]
Closing this with the release of 1.7.0 : https://github.com/JohnCoates/Aerial/releases/tag/v1.7.0
