### ISSUE TITLE
Problem with video download

### ISSUE THREAD

**Issue by hansw1204** [JohnCoates/Aerial#868]
[Arial_log.txt](https://github.com/JohnCoates/Aerial/files/3713364/Arial_log.txt)

iMac 4K
Catalina 
Just main monitor

Got an error while downloading videos. Hope the log helps!
Cheers,
Hans

**Comment by glouel** [comment]
Hi @hansw1204 

Can you clarify what happened exactly I'm trying to parse the log bug it's a bit hard to tell. 

Looks like you queued a lot of videos, some seem to download (suspiciously fast, did they actually download ?). 

Then you get one timeout and a bunch of errors indeed afterwards. 

So did it download anything at all, just failed some ?

**Comment by hansw1204** [comment]
Thanks for the fast reply!I believe it did download some and then got stuck.  I have a Gigabit connection so they do come fast. Might just be a server problem.
    	
    	

    	
    
  




On Thu, Oct 10, 2019 at 11:46 AM -0400, "Guillaume Louel" <notifications@github.com> wrote:












Hi @hansw1204


Can you clarify what happened exactly I'm trying to parse the log bug it's a bit hard to tell.


Looks like you queued a lot of videos, some seem to download (suspiciously fast, did they actually download ?).


Then you get one timeout and a bunch of errors indeed afterwards.


So did it download anything at all, just failed some ?

**Comment by glouel** [comment]
After restarting Aerial (please close system preferences and restart it), if you try to download just one, does it download (click the + sign next to one) ? 

If it doesn't download anymore, can you try this in Safari : https://sylvan.apple.com/Videos/SE_A016_C009_SDR_20190717_SDR_2K_AVC.mov

See if it downloads at all (I did recheck here, this one does) ?

Looks like an issue with you reaching the server, maybe they didn't like that you pulled the videos too fast ? Never heard of that issue but maybe they added some throttling to their servers ? (each video is downloaded with 4 threads which never was an issue here either, with a gigabit connexion too). 

Let me know what happens.

**Comment by hansw1204** [comment]
Thanks Guillaume!

 

It seems to be working fine, actually. I think the reason it stopped downloading was that I reset the preferences from 4K to 1080HVECand thus the 4K videos stopped downloading. The screensaver runs well. I do get a warning that location service may not be set on and that it cannot determine the sunset/sunrise time. I checked, Location Service is on, however. Not a big deal.

 

Cheers,

Hans

**Comment by glouel** [comment]
> Thanks Guillaume! It seems to be working fine, actually. I think the reason it stopped downloading was that I reset the preferences from 4K to 1080HVECand thus the 4K videos stopped downloading. 

That's definitely it ;) Those are different files so it probably pruned the cancelled the queued downloads. 

> The screensaver runs well. I do get a warning that location service may not be set on and that it cannot determine the sunset/sunrise time. I checked, Location Service is on, however. Not a big deal. 

So under Catalina, we don't have access to location services for now because of the whole new sandboxing thing. I'll remove that warning in a next build since there's not much we can do about it. 

Thanks for following up on this!
