### ISSUE TITLE
Allow Right arrow key to skip not working

### ISSUE THREAD

**Issue by stickmanx** [JohnCoates/Aerial#869]
Aerial 1.6.2
 
- [ ] Mac model: MacBook Pro 15 2017
- [ ] macOS version: macOS Catalina 10.15
- [ ] Monitor setup:

The "Allow Right arrow key to skip" does not work, clicking on the right arrow triggers the user login prompt.

**Comment by glouel** [comment]
Hi @stickmanx 

Yep, this no longer works in Catalina (it still works in older macOS versions). This is a sandbox restriction that we can't override, you can find more information here about all the various limitations imposed by Catalina in the first post : https://github.com/JohnCoates/Aerial/issues/801
