### ISSUE TITLE
No Screensaver options

### ISSUE THREAD

**Issue by TheAwesomeGuy11** [JohnCoates/Aerial#878]
MacBook Pro (Retina, 15 inch, Mid 2015)
Macos Catalina (10.15)

I can't access any screensaver options.

<img width="662" alt="Screen Shot 2019-10-18 at 4 59 33 pm" src="https://user-images.githubusercontent.com/56467465/67070857-ac6ba600-f1c8-11e9-9e6a-a6afc4061a92.png">

**Comment by glouel** [comment]
Hi @TheAwesomeGuy11 

Please try this build : https://github.com/glouel/Aerial/releases/download/v1.6.3test2/Aerial.saver.zip

There's a crash happening if you happened to have added custom videos to Aerial, this build fixes it.

**Comment by TheAwesomeGuy11** [comment]
Thank you. That fixed the problem
