### ISSUE TITLE
macOS version is Catalina,the location path use external disk, the aerial can't work.

### ISSUE THREAD

**Issue by coldice945** [JohnCoates/Aerial#879]
macOS version: Catalina 10.15 (19A602)
Aerial version: 1.6.3

 When I change cache location to external disk the aerial is not work. The path like '/Volumes/ColdiceSD/Aerial'. When I change cache location to Mac Internal disk, the aerial screensaver can work.

2019-10-27 00:03:22 : Error while enumerating files /Volumes/ColdiceSD/Aerial: The file “Aerial” couldn’t be opened because you don’t have permission to view it.

When I change the path to my Mac disk, the Screensaver was worked. But the video tab bar still can't preview the video. Like the pic.
<img width="628" alt="截屏2019-10-2701 01 53" src="https://user-images.githubusercontent.com/18394852/67623274-c99e1580-f855-11e9-864e-96e3ac35066d.png">

**Comment by glouel** [comment]
Hi @coldice945 

This is no longer possible sadly, this is a restriction imposed by Catalina for the moment and there's no workaround (besides disabling SIP which is not a good idea for many reasons). You can only set a cache on your primary disk right now.

You can read more about Catalina limitations in this issue : https://github.com/JohnCoates/Aerial/issues/801

**Comment by NewsGuyTor** [comment]
> Hi @coldice945
> 
> This is no longer possible sadly, this is a restriction imposed by Catalina for the moment and there's no workaround (besides disabling SIP which is not a good idea for many reasons). You can only set a cache on your primary disk right now.
> 
> You can read more about Catalina limitations in this issue : #801
> 
> Edit: About the preview, please System preferences (close and reopen), this will fix it.

SIP is disabled on my end. How do I enabled cache folder on a different partition?

**Comment by glouel** [comment]
Hi @NewsGuyTor !

Go to Caches tab, then click "Change cache location". You'll have to type the path to your volume (so something like "/Volumes/Some volume/Some path"). Then quit syspref and restart it. You need to create your folder before you set it.

**Comment by NewsGuyTor** [comment]
That didn't work for me. I got it working like this though:

1. Create a new cache folder whereever you want
2. You move the contents of "/Users/username/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application\ Support/Aerial" to your new cache folder. 
3. Then you delete the old Arial folder
4. Then you run "ln -s /Volumes/Newlocation/Aerial /Users/username/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application\ Support/Aerial" in iTerm

**Comment by glouel** [comment]
Right, my apologies. I gave you the instructions in case you had previously downloaded all the videos and wanted to move the cache folder. By default it only downloads in the container so your symbolic link solution is the correct one. Sorry again for sending you on the wrong path!
