### ISSUE TITLE
Catalina: You can’t open the application “ScreenSaverEngine” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by HimalayanSage** [JohnCoates/Aerial#883]
Looks like this might be something new.   Catalina. 10.15.1 on a MBP 13" 2017. Internal monitor.

When the screensaver is active (full page, black background, floating text):
"**You cannot use the Aerial screen saver with this version of MacOs. Please contact the vendor to get a newer version of the screen saver.**"

When I click on the "preview button" with Aerial selected in the System Preference:

"**You can’t open the application “ScreenSaverEngine” because it may be damaged or incomplete.**"

#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by HimalayanSage** [comment]
Followed directions to manually delete and re-install latest version for all users.  Same results.

**Comment by glouel** [comment]
Hi @HimalayanSage 

That one is strange. `ScreenSaverEngine` is the container for all 3rd party screensavers. Do you happen to have other 3rd party screensavers installed ?

Also, are you using latest version (1.6.4 ?). Earlier version would fail. 

Here's what I would suggest : 
- Close System Preferences
- Open console.app
- Top right corner, type ScreenSaver
- Open System Preferences again and try to launch the preview of Aerial
- Paste whatever comes in console

That might tell me more about what's happening here for you. Thanks !

**Comment by HimalayanSage** [comment]
Hi,  I assume it’s 1.6.4 but can’t v edify the version once installed since I can’t open.  I got it from:
https://github.com/JohnCoates/Aerial/releases/download/v1.6.4/Aerial.saver.zip

No other screensavers installed, never had.

Here’s the console when I select preview:

default 17:18:38.622355-0500 lsd Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///System/Library/CoreServices/ScreenSaverEngine.app/Contents/, NSFilePath=/System/Library/CoreServices/ScreenSaverEngine.app/Contents/PlugIns, NSUnderlyingError=0x7fca8f595a90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory”}}
default 17:18:38.622539-0500 lsd - 45683955: Checking whether application is managed at file:///System/Library/CoreServices/ScreenSaverEngine.app//com.apple.ScreenSaver.Engine
default 17:18:38.647228-0500 lsd Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///System/Library/CoreServices/ScreenSaverEngine.app/Contents/, NSFilePath=/System/Library/CoreServices/ScreenSaverEngine.app/Contents/PlugIns, NSUnderlyingError=0x7fca8f1f2960 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory”}}
default 17:18:38.647341-0500 lsd - 45683955: Checking whether application is managed at file:///System/Library/CoreServices/ScreenSaverEngine.app//com.apple.ScreenSaver.Engine
default 17:18:38.683641-0500 lsd Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///System/Library/CoreServices/ScreenSaverEngine.app/Contents/, NSFilePath=/System/Library/CoreServices/ScreenSaverEngine.app/Contents/PlugIns, NSUnderlyingError=0x7fca8f503a80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory”}}
default 17:18:38.683706-0500 lsd - 45683955: Checking whether application is managed at file:///System/Library/CoreServices/ScreenSaverEngine.app//com.apple.ScreenSaver.Engine
default 17:18:38.693104-0500 lsd Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///System/Library/CoreServices/ScreenSaverEngine.app/Contents/, NSFilePath=/System/Library/CoreServices/ScreenSaverEngine.app/Contents/PlugIns, NSUnderlyingError=0x7fca8eebed20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory”}}
default 17:18:38.693281-0500 lsd - 45683955: Checking whether application is managed at file:///System/Library/CoreServices/ScreenSaverEngine.app//com.apple.ScreenSaver.Engine
error 17:18:38.715063-0500 com.apple.preference.desktopscreeneffect.screeneffects.remoteservice -[ScreenSaverPref beginSaverPreview]_block_invoke -- Failed to launch ScreenSaverEngine.app. Error: Error Domain=NSCocoaErrorDomain Code=259 "The application “ScreenSaverEngine” could not be launched because it is corrupt." UserInfo={NSURL=file:///System/Library/CoreServices/ScreenSaverEngine.app/, NSLocalizedDescription=The application “ScreenSaverEngine” could not be launched because it is corrupt., NSUnderlyingError=0x600003647c30 {Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3590, _LSFunction=_LSOpenStuffCallLocal}}}
default 17:18:38.752430-0500 dmd Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs = (
        “com.apple.ScreenSaver.Engine”
    );
    isPlaceholder = 0;
}
default 17:18:38.809668-0500 dmd Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs = (
        “com.apple.ScreenSaver.Engine”
    );
    isPlaceholder = 0;
}
default 17:18:38.850847-0500 dmd Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs = (
        “com.apple.ScreenSaver.Engine”
    );
    isPlaceholder = 0;
}
default 17:18:38.853405-0500 dmd Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs = (
        “com.apple.ScreenSaver.Engine”
    );
    isPlaceholder = 0;
}



Cheers,

Don

**Comment by HimalayanSage** [comment]
No ScreenSaverEngine.app in /System/Library/CoreServices/

Wonder how the heck that happened during upgrade from 10.14?

Cheers,

Don

**Comment by glouel** [comment]
> Hi,  I assume it’s 1.6.4 but can’t v edify the version once installed since I can’t open.  I got it from: https://github.com/JohnCoates/Aerial/releases/download/v1.6.4/Aerial.saver.zip 

So yeah, that's 1.6.4, good !

> No ScreenSaverEngine.app in /System/Library/CoreServices/ Wonder how the heck that happened during upgrade from 10.14? Cheers, Don

I was going to ask... That's... not good at all. 

That's a part of macOS so I have no idea how come it's missing for you. First time I've seen that too. Quite frankly I have no idea on this one. This may break some default screensavers too (maybe not all, unsure).

**Comment by glouel** [comment]
Just throwing an idea here, maybe try Disk Utility, and launch First Aid ? Maybe some disk corruption makes it inaccessible ? 

System volume is locked down in Catalina so there's no chance you (or some app) deleted it even by accident. Sorry about that one, wish I could help more.

**Comment by HimalayanSage** [comment]
About 10 minutes ahead of you ;-). Rebooted into recovery and ran First Aid as you suggested.  Rebooted, ScreenSaverEngine.app was back and Aerial is working!   Thanks for the hint!  Still have no idea how it went missing.

Cheers,

Don

**Comment by glouel** [comment]
Hehe, glad to hear you got it back 👍 Super weird in any case !
