### ISSUE TITLE
Feature Request: Different Font for Extra Message and Clock

### ISSUE THREAD

**Issue by admiral-ackbar** [JohnCoates/Aerial#885]
I would like to set the clock to a monospaced font but not the extra message under it.

**Comment by glouel** [comment]
hi @admiral-ackbar 

Bit late of a response but this is something that should come with the rework on text displaying at some point.

**Comment by glouel** [comment]
Hi @admiral-ackbar 

I have that feature now in beta2, you can now set a different font for every different "Info" : 

![Capture d’écran 2019-12-18 à 19 15 24](https://user-images.githubusercontent.com/37544189/71111975-d5111b80-21ca-11ea-8911-a0ac8c0e0926.jpg)

Check the beta here : https://github.com/JohnCoates/Aerial/releases/tag/v1.6.5beta2

**Comment by admiral-ackbar** [comment]
I've installed the beta and it works really well. I did find an issue however, the order of the message, clock, and location is the reverse of what is set in the settings. I'm sorry to send this to you directly instead of putting it on Github, but I don't normally work with Github so I don't know where to post an issue for a beta.

**Comment by glouel** [comment]
No worries, if you reply to the email it gets posted on the website too. Thanks for the feedback!

So the order thing, here's how it works right now, the order you put them in the column (you can reorder) is the order they are drawn, from the corner then outwards of it. 

So if you put location, message, then clock in the top left corner, they will appear in that order.

If you put the same thing in the bottom left corner, the order you see them is reversed (location is drawn first so it's closer to the corner, then the next one, etc). 

That's not super intuitive, I'll see if I can make it reverse the order for the bottom positions. 

Hope that makes sense ;)

**Comment by glouel** [comment]
@admiral-ackbar that bug is fixed in beta3, it also includes the battery thing (text only, no icons for now) : https://github.com/JohnCoates/Aerial/releases/tag/v1.6.5beta3

**Comment by glouel** [comment]
Closing with 1.7.0
