### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by richardplas** [JohnCoates/Aerial#886]
18:35:08 : avInit1 (0.0, 0.0, 296.0, 184.0)
18:35:08 : <AerialView: 0x7fd824813560> AerialView setup init (V1.6.4)
18:35:08 : Time Management initialized
18:35:08 : Display Detection initialized
18:35:08 : ***Display Detection***
18:35:08 : 1 display(s) detected
18:35:08 : 1cm = 50.7874023375534 points
18:35:08 : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1680, 1050}, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 2077750201, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}]
18:35:08 :        bottomLeftFrame (0.0, 0.0, 1680.0, 1050.0)
18:35:08 : src orig : (0.0, 0.0)
18:35:08 : left 0.0 below 0.0
18:35:08 : [id=2077750201, width=1680, height=1050, bottomLeftFrame=(0.0, 0.0, 1680.0, 1050.0), topRightCorner=(1680.0, 1050.0), isMain=true, backingScaleFactor=2.0]
18:35:08 : (0.0, 0.0, 1680.0, 1050.0)
18:35:08 : ***Display Detection Done***
18:35:08 : <AerialView: 0x7fd824813560> isPreview : true
18:35:08 : Using : nil
18:35:08 : <AerialView: 0x7fd824813560> no local player
18:35:08 : <AerialView: 0x7fd824813560> setupPlayerLayer
18:35:08 : <AerialView: 0x7fd824813560> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
18:35:08 : Using dot workaround for video driver corruption
18:35:08 : Manifest init
18:35:08 : app support exists
18:35:08 : loading custom file : file:///Users/xxx/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/customvideos.json
18:35:08 : isManifestCached 10 false
18:35:08 : isManifestCached 11 true
18:35:08 : isManifestCached 12 true
18:35:08 : isManifestCached 13 true
18:35:08 : 2019-11-14
18:35:08 : Interval : Optional(-66908.14339995384)
18:35:08 : No need to check for new videos
18:35:08 : Manifests files were not loaded in class
18:35:08 : Files were not already loaded in memory
18:35:08 : Fetching missing manifests online
18:35:08 : <AerialView: 0x7fd824813560> backing change 2.0 isDisabled: false
18:35:08 : <AerialView: 0x7fd824813560> startAnimation
18:35:25 : <AerialView: 0x7fd824813560> stopAnimation
18:35:25 : pwc init2
18:35:26 : Aerial control panel V1.6.4
18:35:26 : Cache size : 0.83 GB
18:35:26 : Poi Strings Provider initialized
18:35:26 : Community Language overriden to : zh_CN
18:35:26 : path : /Users/xxx/Library/Screen Savers/Aerial.saver/Contents/Resources/zh_CN.json
18:35:26 : Community JSON : 73 entries
18:35:26 : No local or user cache exists, using ~/Library/Application Support/Aerial
18:35:26 : cache to be used : Optional("/Users/xxx/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
18:35:26 : cvcinit2
18:35:26 : cvcawake
18:35:26 : wdl
18:36:08 : Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600001846df0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <99909253-F196-4FC3-8EED-29DB3FFBCD55>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <99909253-F196-4FC3-8EED-29DB3FFBCD55>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, NSErrorFailingURLKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, _kCFStreamErrorDomainKey=4}
18:36:08 : Fetching manifests all done
18:36:08 : Can't load tvos10.json from cached directory
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : Could not determine duration, video is not cached in any format
18:36:08 : tvOS10 manifest is absent
18:36:08 : Total videos processed : 79 callbacks : 2
18:36:08 : <AerialView: 0x7fd824813560> Setting player for all player layers in []
18:36:08 : initvideocache
18:36:08 : cached video file with length: 347334071
18:36:08 : <AerialView: 0x7fd824813560> playing video (OFFLINE MODE) : file:///Users/xxx/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%xx/Aerial/comp_C001_C005_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov
18:36:08 : <AerialView: 0x7fd824813560> observing current item <AVPlayerItem: 0x600001495060, asset = <AVURLAsset: 0x600001603ec0, URL = file:///Users/xxx/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/comp_C001_C005_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov>>
18:36:08 : <AerialView: 0x7fd824813560> observeValue Optional("readyForDisplay")
18:36:08 : AssetLoaderDelegate deinit
18:36:08 : Callback after manifest loading
18:36:08 : Looking for outdated files
18:36:08 : No old files found
18:36:08 : <AerialView: 0x7fd824813560> observeValue Optional("readyForDisplay")
18:38:32 : Playing this preview id=7825C73A-658F-48EE-B14C-EC56673094AC,
name=Space,
type=video,
timeofDay=night,
url1080pH264=https://sylvan.apple.com/Videos/comp_GMT329_113NC_396B_1105_CHINA_v04_SDR_FINAL_20180706_F900F2700_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_113NC_396B_1105_CHINA_v04_SDR_FINAL_20180706_F900F2700_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_113NC_396B_1105_CHINA_v04_HDR_FINAL_20180706_F900F2700_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_113NC_396B_1105_CHINA_v04_SDR_FINAL_20180706_F900F2700_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_113NC_396B_1105_CHINA_v04_HDR_FINAL_20180706_F900F2700_HDR_4K_HEVC.mov"
18:38:40 : <AerialView: 0x7fd824813560> startAnimation
18:38:58 : <AerialView: 0x7fd824813560> stopAnimation
18:39:01 : Playing this preview id=22162A9B-DB90-4517-867C-C676BC3E8E95,
name=China,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov"
18:39:01 : initvideocache
18:39:02 : Playing this preview id=044AD56C-A107-41B2-90CC-E60CCACFBCF5,
name=China,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/comp_C003_C003_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_C003_C003_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_C003_C003_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_C003_C003_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_C003_C003_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov"
18:39:02 : initvideocache
18:39:02 : Playing this preview id=B876B645-3955-420E-99DF-60139E451CF3,
name=China,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/comp_CH_C007_C011_PSNK_v02_SDR_PS_FINAL_20180709_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_SDR_PS_FINAL_20180709_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_HDR_FINAL_20180709_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_SDR_PS_FINAL_20180709_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_HDR_FINAL_20180709_HDR_4K_HEVC.mov"
18:39:02 : initvideocache
18:39:03 : Playing this preview id=D5E76230-81A3-4F65-A1BA-51B8CADED625,
name=China,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/comp_CH_C007_C004_PSNK_v02_SDR_PS_FINAL_20180709_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C004_PSNK_v02_SDR_PS_FINAL_20180709_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C004_PSNK_v02_HDR_FINAL_20180709_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C004_PSNK_v02_SDR_PS_FINAL_20180709_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C004_PSNK_v02_HDR_FINAL_20180709_HDR_4K_HEVC.mov"
18:39:03 : initvideocache
18:39:03 : Processsing contentInformationRequest
18:39:03 : expected content length: 295151621 type:com.apple.quicktime-movie
18:39:03 : Processsing contentInformationRequest
18:39:03 : expected content length: 295151621 type:com.apple.quicktime-movie
18:39:03 : Playing this preview id=9CCB8297-E9F5-4699-AE1F-890CFBD5E29C,
name=China,
type=video,
timeofDay=day,
url1080pH264=https://sylvan.apple.com/Videos/comp_CH_C002_C005_PSNK_v05_SDR_PS_FINAL_20180709_SDR_2K_AVC.mov,
url1080pHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C002_C005_PSNK_v05_SDR_PS_FINAL_20180709_SDR_2K_HEVC.mov,
url1080pHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C002_C005_PSNK_v05_HDR_FINAL_20180709_HDR_2K_HEVC.mov,
url4KHEVC=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C002_C005_PSNK_v05_SDR_PS_FINAL_20180709_SDR_4K_HEVC.mov"
url4KHDR=https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C002_C005_PSNK_v05_HDR_FINAL_20180709_HDR_4K_HEVC.mov"
18:39:03 : initvideocache
18:39:04 : Processsing contentInformationRequest
18:39:04 : expected content length: 244424872 type:com.apple.quicktime-movie
18:39:04 : Processsing contentInformationRequest
18:39:04 : expected content length: 244424872 type:com.apple.quicktime-movie
18:39:05 : Processsing contentInformationRequest
18:39:05 : expected content length: 501989080 type:com.apple.quicktime-movie
18:39:06 : Processsing contentInformationRequest
18:39:06 : expected content length: 500992397 type:com.apple.quicktime-movie
18:39:06 : Processsing contentInformationRequest
18:39:06 : expected content length: 501989080 type:com.apple.quicktime-movie
18:39:06 : Processsing contentInformationRequest
18:39:06 : expected content length: 213156616 type:com.apple.quicktime-movie
18:39:06 : Processsing contentInformationRequest
18:39:06 : expected content length: 500992397 type:com.apple.quicktime-movie
18:39:06 : Processsing contentInformationRequest
18:39:06 : expected content length: 213156616 type:com.apple.quicktime-movie
18:39:07 : AssetLoaderDelegate deinit
18:39:08 : connectionDidFinishLoading
18:39:08 : AssetLoaderDelegate deinit
18:39:08 : connectionDidFinishLoading
18:39:08 : AssetLoaderDelegate deinit
18:39:09 : AssetLoaderDelegate deinit
18:39:09 : connectionDidFinishLoading
18:39:09 : connectionDidFinishLoading
18:39:09 : connectionDidFinishLoading
18:39:18 : Closing cvc
18:39:18 : customvideos.json saved successfully!
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : Could not determine duration, video is not cached in any format
18:39:18 : tvOS10 manifest is absent
18:39:18 : Total videos processed : 79 callbacks : 1
18:39:18 : Callback after manifest loading
18:39:18 : Looking for outdated files
18:39:18 : No old files found
18:39:21 : <AerialView: 0x7fd824813560> startAnimation
18:39:30 : <AerialView: 0x7fd824813560> stopAnimation

**Comment by glouel** [comment]
Hi @richardplas 

It looks like you are unable to connect to one of Apple's servers to grab the tvOS 10 manifest, the link may be blocked in your country. 

> 18:36:08 : Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600001846df0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <99909253-F196-4FC3-8EED-29DB3FFBCD55>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDownloadTask <99909253-F196-4FC3-8EED-29DB3FFBCD55>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, NSErrorFailingURLKey=http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json, _kCFStreamErrorDomainKey=4}

This is not super important as those are fairly old videos. 

You can try downloading the file manually following this link : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

Save the json as tvos10.json in your cache folder, and you won't see the error anymore. Or you can just ignore it and keep using as is.

**Comment by glouel** [comment]
Please reopen the issue if you need more help with this.
