### ISSUE TITLE
Show Battery

### ISSUE THREAD

**Issue by admiral-ackbar** [JohnCoates/Aerial#887]
It would be nice if there was a setting to show the current battery level or to hide it if the battery was fully charged

**Comment by glouel** [comment]
Adding this as a maybe

**Comment by glouel** [comment]
This is now in beta3 : https://github.com/JohnCoates/Aerial/releases/tag/v1.6.5beta3

Beware after installing, you will need to set again your video format (1080p, 4K, HDR) as I changed some more internal stuff.

**Comment by nriley** [comment]
The "show" menu (icons vs text) doesn't seem to do anything; I always see text.

I would agree that it would be nice if the charged state would just hide the battery level as in the first case. "Plugged-in" is not great wording in any case.

**Comment by glouel** [comment]
Hi @nriley 

> The "show" menu (icons vs text) doesn't seem to do anything; I always see text.

Yep I thought I had mentioned it somewhere, it's still a work in progress and only text works for now as the icon code doesn't work yet. I hope to have that one fixed soon. 
 
> I would agree that it would be nice if the charged state would just hide the battery level as in the first case. 

That's a good idea for an option, I'm not a big fan of the text/icon thing overall, in many ways, it was a placeholder until I got the icon drawing working, I'll keep it in mind. 

> "Plugged-in" is not great wording in any case. If you do want to display text, "Charging" or "Charged" (100%) would be more consistent with other places in macOS.

Agreed !

**Comment by glouel** [comment]
@nriley since there were new videos, I released 1.7.0 with the text changes you mentionned (Charging/Charged) ! Closing this though I'll keep working on the icon stuff for next version !

**Comment by nriley** [comment]
Looks good, thanks!
