### ISSUE TITLE
Mac OS pref DESKTOP and ScreenSAver panel ( not Catalina) can't be closed once opened 10.14.6 thanks - LOVE this one 4 monitors works beauty a nd has for the last few years....

### ISSUE THREAD

**Issue by walkermurch** [JohnCoates/Aerial#888]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
HI @walkermurch 

Can you tell me which version you are using of Aerial ? Because this sounds like a veeery old bug. You can see the version in the bottom right corner, like here : 

<img width="892" alt="Capture d’écran 2019-11-19 à 15 04 52" src="https://user-images.githubusercontent.com/37544189/70184848-feb94580-16e8-11ea-98c4-3777bdd63e6e.png">

If you don't see a version number or your Aerial doesn't look like this, you're likely using a super old version. Please install latest from here : https://github.com/JohnCoates/Aerial/releases/download/v1.6.4/Aerial.saver.zip

**Comment by walkermurch** [comment]
Hey thanks. I just left but am going back to check a render in a few hours. 

Thanks! 



D R E A M L I K E   P I C T U R E S 
                Moving Stories 

   https://dreamlikepictures.com




> On Dec 4, 2019, at 4:55 PM, Guillaume Louel <notifications@github.com> wrote:
> 

﻿
HI @walkermurch

Can you tell me which version you are using of Aerial ? Because this sounds like a veeery old bug. You can see the version in the bottom right corner, like here :



If you don't see a version number or your Aerial doesn't look like this, you're likely using a super old version. Please install latest from here : https://github.com/JohnCoates/Aerial/releases/download/v1.6.4/Aerial.saver.zip

**Comment by walkermurch** [comment]
On Dec 4, 2019, at 4:55 PM, Guillaume Louel <notifications@github.com> wrote:

HI @walkermurch <https://github.com/walkermurch>
Can you tell me which version you are using of Aerial ? Because this sounds like a veeery old bug. You can see the version in the bottom right corner, like here :







Wow  - that was it…i didn’t distinguish between the Visuals updating and the app…you added  TON of new functionality!


Thanks!


Walker






       
        D R E A M L I K E    P I C T U R E S 
                        Moving Stories



https://dreamlikepictures.com <http://dreamlikepictures.com/>

instagram.com/dreamlikepictures <http://instagram.com/dreamlikepictures>

linkedin.com/in/arthur-bell/

917•769•5096

**Comment by glouel** [comment]
Hehe yep, I changed a loooot of things since then ;) That and you'll find many new videos too. Take care !
