### ISSUE TITLE
[Feature request] Quotes via Jason centered stage

### ISSUE THREAD

**Issue by dutchdodo** [JohnCoates/Aerial#892]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
Hi @dutchdodo 

Would you mind elaborating on what you're asking ? I literally have no idea on what your title mean. Thanks !

**Comment by dutchdodo** [comment]
I would like to show my daily quotes (from 'https://www.interaction-design.org/quote') on top of the video. Much like the Extra Information 'Extra Message', but then in the middle of the screen. The quote(s) data could be a feed in JSON.

**Comment by glouel** [comment]
I see, your title autocompleted to Jason, so I was a bit puzzled ! I'm currently reworking the whole text display thing right now to add more features, so something of the sort is possible. 

I'll keep it in mind, no schedule on that though.

**Comment by glouel** [comment]
Been a looooong time @dutchdodo but this is finally possible in the latest betas where you can have the output of a shell script shown as a message : https://github.com/JohnCoates/Aerial/issues/1157 

Middle of the screen is also available since 2.0 ;)
