### ISSUE TITLE
Multi User Support

### ISSUE THREAD

**Issue by RamblinWreck77** [JohnCoates/Aerial#893]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- Mac model: 2012 15" retina
- macOS version: 10.15.2
- Monitor setup: 2x external

#### Description of issue / Feature request

Hello! I have multiple users on my machine, and while aerial is installed on one account (brew cask install aerial) no other users see aerial as an option in their screen saver list. Is this not supported?

Thanks!

**Comment by glouel** [comment]
Hi @RamblinWreck77 

I think the homebrew script only installs for your user. If you install manually though, you'll get to pick if you want it to run for your user, or all users.

**Comment by glouel** [comment]
I'll be closing this, please reopen if you need more help on this.
