### ISSUE TITLE
Does not work with proxy

### ISSUE THREAD

**Issue by Curtisjk** [JohnCoates/Aerial#9]
I am attempting to use this screensaver at work, where we use a proxy. I have installed but the images do not load. After a period of time, a play button with a line through it appears - indicating the content could not be played.

Proxy has been set in network settings and inside terminal profile.

**Comment by Gatewayy** [comment]
I have the same issue as well, the screensaver does work fine at my home though.  Our proxy is network based and does not have any settings on our computers that I can find.

**Comment by Stephanvs** [comment]
I have the same issue as @Gatewayy and cannot influence the settings

**Comment by alistairmcmillan** [comment]
Duplicate of #5
