### ISSUE TITLE
Screen is black upon initialization. Pressing enter initializes video.

### ISSUE THREAD

**Issue by jonfoxnj** [JohnCoates/Aerial#900]
As said in subject

**Comment by glouel** [comment]
Hi @jonfoxnj 

I'm gonna need a little more details, which Mac you have, which macos version, etc ? 

Assuming you are **NOT** running Catalina, you may want to try disabling auto updates as that could be a likely culprit.

**Comment by jonfoxnj** [comment]
I’m an idiot! lol thanks man

**Comment by glouel** [comment]
No worries, take care !
