### ISSUE TITLE
Ability to add custom video files

### ISSUE THREAD

**Issue by alexstolzbergua** [JohnCoates/Aerial#901]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Is there a way that you could add a feature to allow users to add their own videos to the screen saver?

**Comment by glouel** [comment]
Hi @alexstolzbergua 

It's already here ;) It's a bit hidden, press the button below the list and then Custom videos in the popup. It will pop a new window where you can drag video folders. 

![Capture d’écran 2020-01-10 à 18 20 56](https://user-images.githubusercontent.com/37544189/72172718-267d8680-33d6-11ea-82cb-e22ae593b01f.jpg)
