### ISSUE TITLE
Allow Right arrow key to skip

### ISSUE THREAD

**Issue by TheFavaLava** [JohnCoates/Aerial#902]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 13 inch with Touch Bar (2016)
- [ ] macOS version: 10.15.2
- [ ] Monitor setup: n/a

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I just downloaded the newest version on Aerial today, and I have lost the ability to click the right arrow key to cycle through the scenes. I was hopping this could be looked into, or if this is a 10.15.2 issue I would just like to be aware of that. Thank you.

**Comment by glouel** [comment]
Hi @TheFavaLava 

Sadly, screensavers are no longer allowed to control the keyboard in macOS 10.15, so this feature won't come back for the time being (it still works in Mojave and older OSes).

It may come back if/when Apple release SDK for their new .appex screensaver model, maybe with 10.16.

**Comment by TheFavaLava** [comment]
Hello Guillaume,

Thank you for the heads up. Glad to know it's not something I was doing
wrong.

Have a good rest of your day.
