### ISSUE TITLE
Videos transition enhancement for looping

### ISSUE THREAD

**Issue by Pingren** [JohnCoates/Aerial#910]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [x] macOS version: 10.15
- [x] Monitor setup: Built-in

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I am using a 4k custom video (around 45s) as a screen saver. The video was made 
for looping (video starting frame and ending frame are same)

When the video ended, I could notice around 0.3s black screen before it starts play again. Looping transition doesn't look good because of this flash.

P.S.: 
1. I tried 1080p video, this effect is same except the shorter flash time.
2. Fade in/out doesn't help in this case. It only interrupts the looping effect. 

I suggest to improve transition effect: maybe a new setting for keeping the video's last frame until the next video starts playing. So the transition will become unnoticeable to human eyes and video looping smoothly.

**Comment by glouel** [comment]
@Pingren so the way Aerial works usually is that you always try not to play the same video twice unless you really have to. Technically I use 2 AVPlayer instances and swap from one to the next, that's why you see the black flashing. Changing that whole logic would take some time though.

In your case, you only have one (custom) video in your playlist, correct ? I guess there's maybe something I can do in that case, if there's only one video, play it continuously on loop. This should remove the flash (there might be issues with animations), I'll try to think about it and get back to you.

**Comment by glouel** [comment]
@Pingren give this build a shot, if you have only one video in your playlist it will rewind it in the same player and keep playing : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1beta1/Aerial.saver.zip

Looks seamless here on a classic Aerial.

**Comment by Pingren** [comment]
@glouel the tested build works great on this case. The video rewinds without flash. I noticed a cross-fade effect though but it is much better than a flash!

**Comment by glouel** [comment]
Awesome !

**Comment by Pingren** [comment]
@glouel Thank you for your work! I really appreciate you giving such a quick fix.

**Comment by glouel** [comment]
> **UPDATE**: I realized that the cross-fade effect is from the video itself; looping works great.
> @glouel Thank you! I really appreciate you giving a fix in such a short time.

@Pingren just saw your update this morning, even better then ! And no problem, always happy to help if I can !

**Comment by glouel** [comment]
Closing with 1.7.1 which includes the fix : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1/Aerial.saver.zip
