### ISSUE TITLE
Right key to skip quits the screensaver on Mojave

### ISSUE THREAD

**Issue by ZeppelinCaptain** [JohnCoates/Aerial#914]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- [ ] macOS version: Mojave 10.14.6
- [ ] Monitor setup: One screen

#### Description of issue / Feature request

When I press right key, it has recently started quitting the screensaver instead of skipping to the next one. I have tried enabling and disabling the option for skipping. 
I can read that this has broken on newer OS'es, but has it also broken on Mojave?

**Comment by glouel** [comment]
> #### Required information
> In order to help us sort your issue, we ask that you provide the following information:
> 
> * [ ]  Mac model: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
> * [ ]  macOS version: Mojave 10.14.6
> * [ ]  Monitor setup: One screen
> 
> #### Description of issue / Feature request
> When I press right key, it has recently started quitting the screensaver instead of skipping to the next one. I have tried enabling and disabling the option for skipping.
> I can read that this has broken on newer OS'es, but has it also broken on Mojave?

Hi @ZeppelinCaptain 

Yes, it's supposed to work in older OSes but 1.7.0 had a bug, I fixed that in the latest beta that you can download here : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1beta1/Aerial.saver.zip 

Sorry about the confusion !

**Comment by glouel** [comment]
Closing with 1.7.1 : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1/Aerial.saver.zip
