### ISSUE TITLE
Videos play even if they are unchecked

### ISSUE THREAD

**Issue by alexstolzbergsysco** [JohnCoates/Aerial#915]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I added custom videos to the Aerial screen saver and unchecked all of the Apple TV ones but when I start the screensaver I still see a lot of the unchecked videos appear in the screensaver.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4157136/AerialLog.txt)

**Comment by glouel** [comment]
Hi @alexstolzbergsysco !

In your log, I can see these at first launch every time: 

```
2020-02-04 20:24:06.083 : Empty playlist, not good !
2020-02-04 20:24:06.083 : returning random video after condition change not met !
```

Empty playlist can mean 2 things, either you have no video selected at all, or you have no video checked that satisfy the current conditions that need to be met. 

First one is self explanatory, please double check that your custom videos are actually checked : 

![Capture d’écran 2020-02-05 à 12 05 05](https://user-images.githubusercontent.com/37544189/73836583-e6ac9200-480f-11ea-8732-b62f548c03d4.jpg)

This could explain the issue. They are automatically checked after you add them, but if you used, for example, the Uncheck all button in the menu, it would have unselected them too. 

The other one is a bit more tricky, you may have put a day/night restriction in the Aerial's Time tab (something else than "Do not adapt videos based on time" is checked there). Each Aerial (or custom video) can be categorized as a "day" or "night" video. If you have added all your custom videos as "day", but restrict by day/night some way, you could get an empty playlist at night.

Please let me know if that makes sense and fix your issue, if not we'll try to have another look.

**Comment by glouel** [comment]
Please reopen if you need more assistance.
