### ISSUE TITLE
Fonts and sizes for Info don't stick

### ISSUE THREAD

**Issue by tomwolsky** [JohnCoates/Aerial#918]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
- [x] macOS version: 
- [x] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by tomwolsky** [comment]
2019 MacBook Pro 10.15.4 Single monitor.

The Fonts stick for location and battery, but not the sizes. Neither font nor size changes seem to work on the clock.

**Comment by glouel** [comment]
> 2019 MacBook Pro 10.15.4 Single monitor.
> 
> The Fonts stick for location and battery, but not the sizes. Neither font nor size changes seem to work on the clock.

Hi @tomwolsky 

Oops, I'll have a look today. I did rush the release of 1.7.0 a bit with the arrival of the new videos, so I didn't put as much testing as I liked. I'll get back to you, sorry about the bug in any case !

**Comment by glouel** [comment]
Hi again, so, I did double check and this seems to work here. Please tell me, after you change the font/size, do you try to immediately launch the screensaver without pressing the "Done" button ? It's a bit weird, but some settings only gets saved when you press that button. All settings (clock, battery, location) work with size and font changes here, as long as I press the "Done" button. 

This is probably your issue, and I probably should save settings more often than that, so please let me know if this is it.

**Comment by tomwolsky** [comment]
Thanks Guillaume. I think I was just trying the hot corner without closing out the options pane.

**Comment by glouel** [comment]
Technically speaking, when you launch a hot corner, you are launching a separate instance of Aerial that will reload preferences, that's why you experienced that issue. 

It's still very not user friendly, I'll have a look at making sure that every change gets saved instantly (instead of waiting for macOS's API to periodically to it on its own), this should be a good improvement. 

Thanks for the report !

**Comment by glouel** [comment]
@tomwolsky it was a really quick fix, I've added it last minute to 1.7.1 here : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1/Aerial.saver.zip

You will now see the settings reflected immediately on hot corner launches, which is a whole lot better ! Take care.
