### ISSUE TITLE
Display never goes to sleep

### ISSUE THREAD

**Issue by epheterson** [JohnCoates/Aerial#92]
It may be my computer settings, but it looks like since I started using this screensaver, my screen never turns off. I'll sleep all night and wake up to a bright screen with the screensaver up. Can we look into this for saving energy?

**Comment by jaygoldman** [comment]
I was just going to report the same! My displays don't sleep anymore either. I've verified that the displays are set to sleep in Energy Saver and they do sleep if I go back to my old screensaver. Thanks!

**Comment by JohnCoates** [comment]
Anyone having this issue, it's fixed in the latest beta release found here https://github.com/JohnCoates/Aerial/releases

More about this in issue #23
