### ISSUE TITLE
Info is incomplete on a video

### ISSUE THREAD

**Issue by tomwolsky** [JohnCoates/Aerial#922]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 2019 MBP
- [ ] macOS version: 10.15.4
- [ ] Monitor setup: Single
1,7,2b1

Info for one of the videos says "Spinner dolphins off the coast of..." 

I think it's supposed to say Costa Rica, but I'm not sure.

**Comment by glouel** [comment]
Hi @tomwolsky !

Normally, when a line of text is long, it gets split up in two. It should look something like this (with the dolphins) :

![Capture d’écran 2020-02-14 à 16 04 44](https://user-images.githubusercontent.com/37544189/74542633-41e33080-4f44-11ea-8e4c-7358afbbd451.jpg)

Is it possible you missed the line below ? If not, I'd love more details like if you changed font settings, and if you remember which corner it appeared ? Or if you could make a picture maybe ?

Thanks !

**Comment by tomwolsky** [comment]
Should have taken a picture when I first noticed it. My apologies. THE video info is in the upper left. The font is Arial Black 28. Clock and battery are in the upper right. Mine looked like yours except the last two words were missing. This was the first time this video loaded for me.

**Comment by glouel** [comment]
> Should have taken a picture when I first noticed it. My apologies. The video info is in the upper left. The font is Arial Black 28. Clock and battery are in the upper right. Mine looked like yours except the last two words were missing. This was the first time this video loaded for me.

No worries ! I'll try to reproduce your settings, there was nothing else upper left than the info ? Upper left also has the Updates message by default in 1.7.2b1, it's possible that it's linked, although it's probably more a weird clipping bug (I had a few of those earlier on).  

Got to go right now but I'll have a look in an hour or so and get back to you.

**Comment by tomwolsky** [comment]
Only the video info in the upper left.

**Comment by glouel** [comment]
Yes, guess I'm mixing my left and right now too 🙈

I did kinda reproduce the bug with Arial Black 28, I do get some clipping and somehow 3 lines of text. I'll double check that code, I probably miscalculate the height of that box for it to get clipped. Will let you know !

![Capture d’écran 2020-02-14 à 17 04 50](https://user-images.githubusercontent.com/37544189/74547515-85da3380-4f4c-11ea-9431-d8e8b9a333e7.jpg)

**Comment by glouel** [comment]
@tomwolsky so I think I found the issue, for some reason there's a discrepency between the bounding rect that the string is supposed to occupy, and how it's actually appearing. It's like there's a hidden margin somewhere. I had accounted for that vertically, but not horizontally, which caused the strings to split weirdly and the 3rd line to get cut. I think it should be much better now.

I'm still trying to finish some UI work before I push beta2, probably in a couple hours or so, I'll let you know. Thanks for noticing this and reporting it !

**Comment by tomwolsky** [comment]
Thanks Guillaume.

**Comment by glouel** [comment]
@tomwolsky give that beta a shot and let me know if you still experience an issue : https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta2/Aerial.saver.zip

**Comment by tomwolsky** [comment]
Thanks for this. I see a related problem. Some of the location info breaks about half way across the screen. Other go all the way across the screen before they break. A number of the city titles a quite long and run all the way across the screen without breaking. 

![IMG_9108](https://user-images.githubusercontent.com/18217685/74558435-4f8ebb00-4f30-11ea-9725-726a31d96bb3.jpg)

![IMG_9109](https://user-images.githubusercontent.com/18217685/74558441-5289ab80-4f30-11ea-83f5-f314a71fa3c3.jpg)

![IMG_9105](https://user-images.githubusercontent.com/18217685/74558607-98df0a80-4f30-11ea-987f-7df09c2dc1c2.jpg)

**Comment by glouel** [comment]
Indeed, I was pretty sure I had fixed those overlaps by adding a margin to force the line break earlier, but looking at the code, I can't seem to find it... Will fix for the next update !

**Comment by glouel** [comment]
I was a bit weirded out by your first screenshot, because it should clearly fit the screen in width compared to your 3rd screenshot. So I took a look at the string in the bundle: 
```
A school of Chevron Barracuda
in the waters near Borneo
```

Same goes for the first one that you spotted:

```
Spinner Dolphins in the waters off
of Costa Rica
```

So I guess that explains why some are split weirdly (and the 3 line split I saw that didn't make complete sense to me before). I'm not 100% sure, but I believe that those line breaks may be new from the latest video update, that or I missed them when tvOS13 came. There's not much consistency in any case, those were by far not the longest strings in the bundle !

Assuming I fix the overlap issue, I'm not sure if I should remove those line breaks, and rebreak them when needed based on screen size/font size. In any case, thanks a lot again for the screenshots !

**Comment by tomwolsky** [comment]
Thanks for working on this wonderful screensaver.

**Comment by r8ders2k** [comment]
Ditto, thanks for ALL your work on Aerial!

**Comment by glouel** [comment]
@tomwolsky & all,
I finally fixed the font overlap issue/splitting, please give this beta a try : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta4/Aerial.saver.zip

Here's how it look with large fonts : 

![Capture d’écran 2020-03-23 à 17 09 36](https://user-images.githubusercontent.com/37544189/77339568-431a3100-6d2c-11ea-9002-60dfc990f219.jpg)

**Comment by tomwolsky** [comment]
Thank you Guillaume.


All the best,

Tom
