### ISSUE TITLE
Could not install (null) screen saver

### ISSUE THREAD

**Issue by purplespud** [JohnCoates/Aerial#926]
Howdy,

Attempting install "Aerial.saver" (v1.7.1) and preference pane is opened and I am met with "Could not install (null) screen saver" OK.

MacBook Pro (Retina, 13-inch, Late 2013)
10.15.2

**Comment by glouel** [comment]
Hi @purplespud 

Did you have a previous version installed before ? You must close System Preferences and not keep it open before double clicking the .saver file.

**Comment by purplespud** [comment]
I read that somewhere and System Preferences was indeed closed. On double clicking the install it opens the preferences pane and a slide down sheet arrives with that message "Could not install (null) screen saver" OK.

**Comment by glouel** [comment]
Is this the first time you tried to install Aerial ? 

I'm wondering if you file might be corrupted. Can you please try redownloading from this link and try again : https://github.com/JohnCoates/Aerial/releases/download/v1.7.1/Aerial.saver.zip 

?

**Comment by purplespud** [comment]
Thanks for help. Just tried that for you but same issue.  Yes, I did have previous version installed.
Q: do you get a prompt that asks to install for your user or all users before that error or not ?  NO
Q: if you option click the Aerial.saver before and ask for info... 
YES file size is 16,457,217

Restarted computer and also have deleted previous version and restarted to no avail. Same issue

**Comment by glouel** [comment]
Ok, sorry about that. I just tried installing 1.7.1 here on my main machine to double check, and in a VM and it works correctly just in case something with notarization was amiss. 

So, here's my suggestion, please launch `Console.app`, this is Apple's logging thing. Top right, there's a filter field, type `screensaver` and validate.

Now, try to install, it will probably fail, but you'll see a bunch of stuff being added in the console window. Can you copy paste this info ? This might tell me more about your issue. 

Thanks !

**Comment by purplespud** [comment]
is this it?

Feb 17 13:56:36 Jamess-MacBook-Pro AccountProfileRemoteViewService[1929]: objc[1929]: Class AOSUISpyglassAccountChangeHelper is implemented in both /System/Library/PrivateFrameworks/AOSUI.framework/Versions/A/AOSUI and /System/Library/PrivateFrameworks/AOSUI.framework/Versions/A/XPCServices/AccountProfileRemoteViewService.xpc/Contents/MacOS/AccountProfileRemoteViewService. One of the two will be used. Which one is undefined.
Feb 17 13:57:01 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.AccountProfileRemoteViewService[1929]): Service exited due to SIGKILL | sent by AccountProfileRemoteViewService[1929]

**Comment by glouel** [comment]
@purplespud thanks for doing this ! 

So, this line may be it " __dirhelper_create_relative_with_error: error Operation not permitted"

I have to ask, are you running some company management tool (MDM) on your mac ? Here's a suggestion, can you select a Finder window, then pick "Go to folder". Looks like that here in french, the one in blue:

![Capture d’écran 2020-02-17 à 21 06 17](https://user-images.githubusercontent.com/37544189/74683567-ab27a580-51c9-11ea-878f-c75e570695e5.jpg)

Then paste `~/Library/Screen Savers` in the finder window. 

This should show you your user's screensaver folder. Now, take the Aerial.saver file and copy it there. Then launch System Preferences, Aerial should be there. If you see an error when copying the file, there might be something denying you access to the folder or something, if you do let me know.

Sorry about all that in any case !

**Comment by purplespud** [comment]
No, company management or mdm.

That got it to show up in preferences but my new friend I am afraid the preview is just a black screen and screen saver options is greyed out.

**Comment by glouel** [comment]
That's wild. 

Sorry to ask a few more questions/suggest more things, as I'm trying to think this through.
- First, can you close system preferences (leave the file where it is). The open Console.app again, do the filter thing with `screensaver`, it should be blank now (and you can clear previous messages if it's not). Then launch System Preferences and select Aerial in the control panel. Now paste all that has appeared in Console.app  

- Second, how did you download Aerial, did you use Safari or another browser ? If so which. And after download, did you have a zip file that you had to unzip, or did you have a .saver file directly ? 

- Third, you may want to give another build of Aerial a shot, although I'm doubtful this is the issue. Here's the latest build I made earlier today : https://github.com/glouel/Aerial/releases/download/v1.7.2beta4/Aerial.saver.zip

Catalina sandboxing is weird, but I haven't had many install issues of the sort you are having right now...

**Comment by purplespud** [comment]
Was Safari and it was a zip on arrival.
Did try other build before posting original issue.
Console output in a second

**Comment by purplespud** [comment]
Feb 17 14:26:33 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Engine.legacyScreenSaver[2537]): Service exited due to SIGKILL | sent by legacyScreenSaver[2537]
Feb 17 14:26:36 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ScreenSaver.iLife-Slideshow-Extension[2527]): Service exited due to SIGKILL | sent by iLifeSlideshows[2527]
Feb 17 14:26:36 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Computer-Name[2525]): Service exited due to SIGKILL | sent by Computer Name[2525]
Feb 17 14:26:36 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Engine.legacyScreenSaver[2526]): Service exited due to SIGKILL | sent by legacyScreenSaver[2526]

**Comment by purplespud** [comment]
your beta link same problem.  tried another browser to download, same issue. 
Can I shout "tabarnouche" without offending!

**Comment by glouel** [comment]
> Console output in a second

Ok, that's not as helpful as I would have hoped. 

`Feb 17 14:26:36 Jamess-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.ScreenSaver.iLife-Slideshow-Extension[2527]): Service exited due to SIGKILL | sent by iLifeSlideshows[2527]`this is one of Apple's screensavers misbehaving but I've seen that elsewhere and shouldn't be linked to your issue. 

> Did try other build before posting original issue.

Ok :( 

> Was Safari and it was a zip on arrival.

Ok, this might sound weird, but it might be your issue depending on what tool you used to unzip. With gatekeeper and sandboxing, some metadata may not get preserved. May I suggest you try this, go to Safari's menu, Preferences, then enable that setting I circled in red. Safari will unzip for you (you can revert afterwards, but this may be it).

![Capture d’écran 2020-02-17 à 21 31 51](https://user-images.githubusercontent.com/37544189/74684797-132bbb00-51cd-11ea-9986-ddad067dc158.jpg)

Now download again (delete whaterver .saver/zip file is remaining from your previous tries first), make sure you get a .saver file, then double click that.

> Can I shout "tabarnouche" without offending!

Yes you can ! 

If you still have an issue, the last thing I'd recommend is doing the Console.app thing, but without filtering with screensaver. Instead, on the left, you'll see something like "All messages" and "Errors and failures" (or something roughly like that). Click the errors and failures thing.

Your list should now only show stuff with yellow/red dots. Clear again the output, then launch again System Preferences and click Aerial in the screensaver panel. The error might show up here. 

Again sorry to ask so many various things !

**Comment by purplespud** [comment]
!vous êtes un héros!

The safari trick worked!

Thanks you so much for your time and effort.

No idea what is going on with the unzipping.  mind blown.

**Comment by glouel** [comment]
Yes !! Thanks for sticking with me through it !

I'm pretty sure it's an issue with whatever tool you are using to unzip. It's probably older than Catalina and probably wipes some extended attributes or puts the unzipped files in a weird state. 

With gatekeeper, when you download a program from the internet, the file normally gets quarantined. Gatekeeper will check if the file is notarized (I have to register every build of Aerial with Apple so they sign it) before allowing it to be launched. 

So my suggestion, keep the safari thing, and update your unzip thing ! Take care !
