### ISSUE TITLE
Unable to get Gitmodules/Sparkle to work post-1.8

### ISSUE THREAD

**Issue by zeromhz** [JohnCoates/Aerial#929]
Hello - After the 1.8 update I am not able to get Aerial/git to pull in Sparkle using the new submodule method. Following the instructions in Contribute.md:

1. git clone https://github.com/JohnCoates/Aerial.git
2. cd Aerial
3. git submodule update --init --recursive

This does not result in Sparkle being pulled in and the project will not compile because it is unable to find Sparkle. I had (and still have) a fully working setup from 1.7.1 that I was tinkering with prior to this. 

- I also attempted starting with the existing 1.7.1 project, deintegrating the pod, and running the submodule command with no luck.
- I have also attempted the following to clone the repository with the modules included:
git clone --recurse-submodules https://github.com/JohnCoates/Aerial.git

Building on macOS Catalina 10.15.3 with Xcode 11.3.1 (11C504)

**Comment by glouel** [comment]
Hi @zeromhz 

I'm not incredibly familiar with submodules myself, but from my understanding you should probably do `cd Extern` first, you may need to mkdir that directory too if it's not committed. 

From the 1.7.1, after deintegrate, this is what does it:
```
cd Extern
git submodule add https://github.com/sparkle-project/Sparkle.git
```

Hope this help, let me know if you figure it out, if not I'll give it a shot tomorrow to try and see how to fix this. 

Apologies for this

**Comment by zeromhz** [comment]
Is it possible you checked in the .gitmodules file but not the rest of the files from the module? I would have expected checking in just .gitmodules to work, but according to this it does not...

https://stackoverflow.com/questions/39765663/git-submodule-init-does-absolutely-nothing/39766926

**Comment by glouel** [comment]
I think you are right, the Extern folder isn't committed nor the submodule, damn. I'll try to fix this quickly hold on

**Comment by zeromhz** [comment]
Yeah, it appears I can fix this by creating the Extern directory as you describe, but I believe checking in your copy of it is the right step. Thanks for your time.

**Comment by glouel** [comment]
Yeah I think the problem is that Xcode ignored it and even adding manually doesn't help, I'll try from command line.

**Comment by glouel** [comment]
Just merged it : https://github.com/JohnCoates/Aerial/tree/master/Extern

So now a recurse clone should work too, I'll test tomorrow, that's probably a better way to pull everything at once ;) Sorry about that and thanks for the heads up !

**Comment by zeromhz** [comment]
Confirmed fixed. Doing...

git clone --recurse-submodules https://github.com/JohnCoates/Aerial.git

.. now properly pulls in Sparkle and everything builds and executes as expected. May be worth adding this as an instruction in Contribute.md.

Thank you for the instant turnaround time. Much respect.

**Comment by glouel** [comment]
Awesome, I’ll fix the instructions tomorrow as it’s getting late now !

**Comment by zeromhz** [comment]
After about two hours of trying I am unable to get notarization to work after this change. This could be very specific to my setup. In the previous process the pod forced code signing of Sparkle which the correct certificate, and I am unable to find an equivalent step now. I'm interested to know if you are able to get it to code sign using your methods.

**Comment by zeromhz** [comment]
One thing to triple check as well is that notarization is working. I had to tinker around for quite a bit to get it to notarize after this change, but that could be entirely specific to how I'm doing it.

**Comment by glouel** [comment]
@zeromhz I think this should be better now : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Contribute.md 

Thanks for the heads up!

**Comment by glouel** [comment]
> One thing to triple check as well is that notarization is working. I had to tinker around for quite a bit to get it to notarize after this change, but that could be entirely specific to how I'm doing it.

Do you redistribute a notarized version ? What's the use case, I'm curious ? 

I don't provide instructions to do so, but the signing part should be OK. There's a Run Script phase for the .saver target, the last one, that takes care of properly signing Sparkle (which is what makes notarization fails). There's no extra signing step.

**Comment by zeromhz** [comment]
The issue that I was having related to the code signing of Sparkle. As configured, on my machine, Sparkle was being code signed with a different cert than the rest of the app. You are correct that this should all just work, and it's likely in my case it didn't because I have multiple certificates. I was able to resolve this by manually setting the team and certificate in the Sparkle project (as opposed to "Sign to run locally" as it comes by default.)

I am new to this project and have been experimenting with adding custom videos server side. This is entirely experimental at this point. I always notarize everything I build to ensure I'm not missing issues or edges that would not otherwise appear on a self-signed build. If I get anywhere with the experiments I will send you an e-mail to share the work. Thanks again for your help.

**Comment by glouel** [comment]
> The issue that I was having related to the code signing of Sparkle. As configured, on my machine, Sparkle was being code signed with a different cert than the rest of the app. You are correct that this should all just work, and it's likely in my case it didn't because I have multiple certificates. I was able to resolve this by manually setting the team and certificate in the Sparkle project (as opposed to "Sign to run locally" as it comes by default.)

Ok, codesign is always a bit mystical to me and screensavers make everything complicated. But here's my understanding:
- I do **not** sign sparkle at build time (it says Sign to run locally, as it should). 
- My understanding is that when you embed the framework, it will strip the code signing anyway
- The run script that I mentionned (the last step) sign the executable files inside the framework (and also put the timestamp which is required on top of signing)

The issue might be with the last step, maybe it doesn't correctly detect your signing identity as it should. 

> I am new to this project and have been experimenting with adding custom videos server side. This is entirely experimental at this point. I always notarize everything I build to ensure I'm not missing issues or edges that would not otherwise appear on a self-signed build. If I get anywhere with the experiments I will send you an e-mail to share the work. Thanks again for your help.

No worries, I was wondering if you had a specific use case for Sparkle or not. I think that I should probably make a build target that doesn't require Sparkle, as it's useless for everyone but me, and puts a barrier to getting into the project. Take care !

**Comment by zeromhz** [comment]
Funny you mention that, I was just looking at removing Sparkle in favor of the simpler Catalina compatible system you built. It does the job for my purposes as anything I might distribute wouldn't need frequent updates.
