### ISSUE TITLE
iMac no unlocking via aapl

### ISSUE THREAD

**Issue by r8ders2k** [JohnCoates/Aerial#931]
#### General troubleshooting tips

Before logging an issue please check that:
- [X] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: 2017 iMac 5K (18,3)
- [X] macOS version: 10.15.3 (19D76)
- [X] Monitor setup: 27" iMac
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4226472/AerialLog.txt)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

My iMac does not unlock via my Watch Series.  Wanted to check to see if others are having seeming issue(s)/behavior.

**Comment by glouel** [comment]
Hi

It definitely works here for me, I use it everyday. You need to have BT enabled on your Mac and make sure you check that box : 

![Capture d’écran 2020-02-19 à 18 55 00](https://user-images.githubusercontent.com/37544189/74860760-77738980-5349-11ea-9ee9-b5a5a8a1d300.jpg)

You may still get the password prompt from time to time in my experience, like if you are a bit too far, it will try to unlock but fail and put the password prompt. 

But in general this is completely independent of what screensaver you use.
