### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by zhihan526** [JohnCoates/Aerial#932]
Hi.  My Aerial doesn't work when I'm not charing my computer. I usually use the active conner to inactive the screen saver, and it worked yesterday when I was charing it. However, it didn't work now. It only shows up black screen whether I preview it or activate the screen saver.

<img width="653" alt="截屏2020-02-1911 52 22" src="https://user-images.githubusercontent.com/61249030/74866650-73774580-5310-11ea-9170-bec04b2ecc0e.png">
<img width="664" alt="截屏2020-02-1911 52 32" src="https://user-images.githubusercontent.com/61249030/74866654-740fdc00-5310-11ea-8f78-ccefceb966f1.png">

**Comment by zhihan526** [comment]
12:11:58 : avInit .saver (0.0, 0.0, 296.0, 184.0) p: true o: true
12:11:58 : <AerialView: 0x7fd543c15120> AerialView setup init (V1.8.0) preview: true
12:11:58 : Time Management initialized
12:11:58 : Display Detection initialized
12:11:58 : ***Display Detection***
12:11:58 : 1 display(s) detected
12:11:58 : 1cm = 50.393701544239036 points
12:11:58 : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1440, 900}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69733568, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8]
12:11:58 :        bottomLeftFrame (0.0, 0.0, 1440.0, 900.0)
12:11:58 : src orig : (0.0, 0.0)
12:11:58 : left 0.0 below 0.0
12:11:58 : [id=69733568, width=1440, height=900, bottomLeftFrame=(0.0, 0.0, 1440.0, 900.0), topRightCorner=(1440.0, 900.0), isMain=true, backingScaleFactor=2.0]
12:11:58 : (0.0, 0.0, 1440.0, 900.0)
12:11:58 : ***Display Detection Done***
12:11:58 : Using : nil
12:11:58 : <AerialView: 0x7fd543c15120> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
12:11:58 : Using dot workaround for video driver corruption
12:11:58 : Manifest init
12:11:58 : app support exists
12:11:58 : loading custom file : file:///Users/harry/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/customvideos.json
12:11:58 : isManifestCached 10 true
12:11:58 : isManifestCached 11 true
12:11:58 : isManifestCached 12 true
12:11:58 : isManifestCached 13 true
12:11:58 : 2020-02-19
12:11:58 : Interval : Optional(-43918.26370501518)
12:11:58 : No need to check for new videos
12:11:58 : Manifests files were not loaded in class
12:11:58 : Files were not already loaded in memory
12:11:58 : Manifests are cached on disk, loading
12:11:58 : Poi Strings Provider initialized
12:11:58 : Preferred languages : ["zh-Hans-CN"]
12:11:58 : Best matched language : zh_CN
12:11:58 : Defaulting to bundle
12:11:58 : path : /Users/harry/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
12:11:58 : Community JSON : 99 entries
12:11:58 : Using exiting customCacheDirectory : /Users/harry/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial
12:11:58 : cache to be used : Optional("/Users/harry/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
12:11:58 : Total videos processed : 99 callbacks : 0
12:11:58 : <AerialView: 0x7fd543c15120> Setting player for all player layers in []
12:11:58 : initvideocache
12:11:58 : cached video file with length: 249055089
12:11:58 : <AerialView: 0x7fd543c15120> playing video (OFFLINE MODE) : file:///Users/harry/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/DB_D011_C009_4K_SDR_HEVC.mov
12:11:58 : <AerialView: 0x7fd543c15120> observing current item <AVPlayerItem: 0x600003a45b10, asset = <AVURLAsset: 0x60000380a6c0, URL = file:///Users/harry/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/DB_D011_C009_4K_SDR_HEVC.mov>>
12:11:58 : <AerialView: 0x7fd543c15120> observeValue Optional("readyForDisplay") false (0.0, 0.0, 296.0, 184.0)
12:11:58 : AssetLoaderDelegate deinit
12:11:58 : <AerialView: 0x7fd543c15120> backing change 2.0 isDisabled: false frame: (0.0, 0.0, 296.0, 184.0) preview: true
12:11:59 : <AerialView: 0x7fd543c15120> observeValue Optional("readyForDisplay") true (0.0, 0.0, 296.0, 184.0)
12:11:59 : start playback: (0.0, 0.0, 296.0, 184.0) (0.0, 0.0, 296.0, 184.0)
12:11:59 : <AerialView: 0x7fd543c15120> startAnimation frame (0.0, 0.0, 296.0, 184.0) bounds (0.0, 0.0, 296.0, 184.0)
12:11:59 : restarting playback
12:12:00 : <AerialView: 0x7fd543c15120> stopAnimation
12:12:00 : pwc init2
12:12:00 : Callback after manifest loading
12:12:00 : Looking for outdated files
12:12:00 : b5-1.mov NOT FOUND in manifest
12:12:00 : 1 old files found
12:12:01 : Aerial control panel V1.8.0
12:12:01 : Cache size : 44.78 GB
12:12:01 : cvcinit2
12:12:01 : cvcawake
12:12:01 : wdl
12:12:03 : Playing this preview id=3FFA2A97-7D28-49EA-AA39-5BC9051B2745,
name=Dubai,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_HDR_PS_20180912_HDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_HDR_PS_20180912_HDR_2K_HEVC.mov"]
12:12:03 : Playing this preview id=00BA71CD-2C54-415A-A68A-8358E677D750,
name=Dubai,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_DB_D002_C003_PSNK_v04_SDR_PS_20180914_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D002_C003_PSNK_v04_SDR_PS_20180914_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D002_C003_PSNK_v04_HDR_PS_20180914_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D002_C003_PSNK_v04_HDR_PS_20180914_HDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D002_C003_PSNK_v04_SDR_PS_20180914_SDR_4K_HEVC.mov"]
12:12:04 : Playing this preview id=E991AC0C-F272-44D8-88F3-05F44EDFE3AE,
name=Dubai,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_DB_D001_C001_PSNK_v06_SDR_PS_20180824_SDR_2K_AVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C001_PSNK_v06_HDR_PS_20180824_HDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C001_PSNK_v06_HDR_PS_20180824_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C001_PSNK_v06_SDR_PS_20180824_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C001_PSNK_v06_SDR_PS_20180824_SDR_2K_HEVC.mov"]
12:12:07 : <AerialView: 0x7fd543c15120> startAnimation frame (0.0, 0.0, 296.0, 184.0) bounds (0.0, 0.0, 296.0, 184.0)
12:12:07 : restarting playback
12:12:21 : <AerialView: 0x7fd543c15120> stopAnimation

**Comment by glouel** [comment]
Hi @zhihan526 

Check your 2nd screenshot, you have disabled Aerial when running on battery. See this : 

![Capture d’écran 2020-02-19 à 20 11 51](https://user-images.githubusercontent.com/37544189/74867081-55cbcf80-5354-11ea-973b-2bce748d3f4b.png)

Change from "Always disabled" to "Keep enabled". This will fix your issue !

**Comment by zhihan526** [comment]
Thx. That did slove my problem
