### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by salimcansatici** [JohnCoates/Aerial#933]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Macbook Pro 2017 Late
- [ ] macOS version: 10.15.3 (19D76)
- [ ] Monitor setup: 1440x900

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

11:36:53 : avInit .saver (0.0, 0.0, 296.0, 184.0) p: true o: true
11:36:53 : <AerialView: 0x7f9cdc509930> AerialView setup init (V1.8.0) preview: true
11:36:53 : Time Management initialized
11:36:53 : Display Detection initialized
11:36:53 : ***Display Detection***
11:36:53 : 1 display(s) detected
11:36:53 : 1cm = 50.393701544239036 points
11:36:53 : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 69733568, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1440, 900}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8]
11:36:53 :        bottomLeftFrame (0.0, 0.0, 1440.0, 900.0)
11:36:53 : src orig : (0.0, 0.0)
11:36:53 : left 0.0 below 0.0
11:36:53 : [id=69733568, width=1440, height=900, bottomLeftFrame=(0.0, 0.0, 1440.0, 900.0), topRightCorner=(1440.0, 900.0), isMain=true, backingScaleFactor=2.0]
11:36:53 : (0.0, 0.0, 1440.0, 900.0)
11:36:53 : ***Display Detection Done***
11:36:53 : Using : nil
11:36:53 : <AerialView: 0x7f9cdc509930> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
11:36:53 : Using dot workaround for video driver corruption
11:36:53 : Manifest init
11:36:53 : app support exists
11:36:53 : No customvideos.json at : /Users/username/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json
11:36:53 : isManifestCached 10 true
11:36:53 : isManifestCached 11 true
11:36:53 : isManifestCached 12 true
11:36:53 : isManifestCached 13 false
11:36:53 : 2020-02-20
11:36:53 : Interval : Optional(-41813.59520494938)
11:36:53 : No need to check for new videos
11:36:53 : Manifests files were not loaded in class
11:36:53 : Files were not already loaded in memory
11:36:53 : Fetching missing manifests online
11:36:53 : <AerialView: 0x7f9cdc509930> backing change 2.0 isDisabled: false frame: (0.0, 0.0, 296.0, 184.0) preview: true
11:36:54 : <AerialView: 0x7f9cdc509930> startAnimation frame (0.0, 0.0, 296.0, 184.0) bounds (0.0, 0.0, 296.0, 184.0)
11:36:54 : restarting playback
11:36:55 : <AerialView: 0x7f9cdc509930> stopAnimation
11:36:55 : pwc init2
11:36:55 : Aerial control panel V1.8.0
11:36:56 : Cache size : 0,31 GB
11:36:56 : No local or user cache exists, using ~/Library/Application Support/Aerial
11:36:56 : cache to be used : Optional("/Users/username/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
11:36:56 : Poi Strings Provider initialized
11:36:56 : Preferred languages : ["tr-TR"]
11:36:56 : Best matched language : tr
11:36:56 : TVIdleScreenStrings13.bundle is missing, please remove entries.json in Cache folder to fix the issue
11:36:56 : Defaulting to bundle
11:36:56 : path : /Users/username/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
11:36:56 : Community JSON : 99 entries
11:36:56 : cvcinit2
11:36:56 : cvcawake
11:36:56 : wdl

**Comment by glouel** [comment]
Hi @salimcansatici 

Can you clarify what is not downloading exactly ? It looks like you don't have the tvOS 13 bundle at the very least.

Can you try downloading this link to see if you don't have an issue with some sort of firewall ? This is where the file is : https://sylvan.apple.com/Aerials/resources-13.tar

Thanks

**Comment by Andy0570** [comment]
I can download videos, but the download speed is too slow, only 43 kB/s. Is there any other way to download videos?

**Comment by glouel** [comment]
> I can download videos, but the download speed is too slow, only 43 kB/s. Is there any other way to download videos?

Hi @Andy0570 

The videos are hosted by Apple on their servers, but I've been told they are blocked in China, so there's not much I can do. If you want to try to use other tools to download the files manually, you can check the instructions here (but know that Aerial uses 4 threads per file to download already) :  https://github.com/JohnCoates/Aerial/blob/master/Documentation/OfflineMode.md

Your best bet might be to try an alternate connexion (some form of VPN?). Sorry I can't help you more.

**Comment by salimcansatici** [comment]
> > I can download videos, but the download speed is too slow, only 43 kB/s. Is there any other way to download videos?
> 
> Hi @Andy0570
> 
> The videos are hosted by Apple on their servers, but I've been told they are blocked in China, so there's not much I can do. If you want to try to use other tools to download the files manually, you can check the instructions here (but know that Aerial uses 4 threads per file to download already) : https://github.com/JohnCoates/Aerial/blob/master/Documentation/OfflineMode.md
> 
> Your best bet might be to try an alternate connexion (some form of VPN?). Sorry I can't help you more.

Hi,

Thank you very much this answer, my problem is solved.
