### ISSUE TITLE
Versions newer than 1.7.0 not compatible with El Capitan 10.11.6

### ISSUE THREAD

**Issue by briantully** [JohnCoates/Aerial#936]
#### General troubleshooting tips

Before logging an issue please check that:
- [ x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

```When upgrading to a version newer than 1.7.0, Aerial crashes immediately on selection. I've deleted all Aerial preferences/cache, to no avail. I've had this issue with 1.7.1 up to 1.8.0.```

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ x] Mac model: Mac Pro (Early 2008)
- [ x] macOS version:  El Capitan 10.11.6  
- [ x] Monitor setup: Single monitor Apple Cinema Display, 1920 x 1200

**If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).**

#### Description of issue / Feature request

Exception:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY
```

Aerial Crash Log:

[Aerial-crash.log](https://github.com/JohnCoates/Aerial/files/4252511/Aerial-crash.log)

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4252553/AerialLog.txt)

**Comment by glouel** [comment]
Hi @briantully 

Sorry about that, but I did drop support in 1.8.0 for anything below 10.12. Many things were already broken on those OSes and it's incredibly hard to keep supporting old versions and new versions of macOS at the same time without making a lot of concessions. Catalina made everything harder and if there's a new screensaver API at WWDC, it will probably make things even worse.

If there's truly a large amount of demand, I could see about having a separate build for those, although that's probably a fair amount of work. 

Right now, 1.7.2beta3 is the last <10.12  compatible version, you can get it here : https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta3/Aerial.saver.zip

**Comment by briantully** [comment]
Hi @glouel 

Thanks for the explanation. Understood. Unfortunately I get the same error with the v1.7.2beta3. It seems to have occurred at v1.7.1. I'll revert back to 1.7.0, which seems to be the latest version working with <10.12. 

Is there anything in the docs or release notes that could be added to specify which releases support which versions of OSX? MIght save a lot of heartache if we specify a "requires Mac OS 12 HIgh Sierra or greater" to each new release going forward :)

**Comment by glouel** [comment]
Ha, sorry, I read your message too quickly. As far as I remember, 1.7.1 and the 1.7.2 betas should have worked. Could you send me the full crash log maybe ? I'm pretty sure I only moved the build target with 1.8.0...

There's already the info on the main page, though it's on the bottom so easy to skip:

`Aerial is written in Swift, which requires OS X Sierra (10.12) or above. Aerial 1.7.1 is the last version that supports macOS 10.9.` I should definitely add the message on the release note of 1.8.0 too, I'll do that right now !

Not that you asked, but there are "unnofficial" options to run more modern macOS versions on your Mac Pro. I personally use that to run Catalina on an old 2011 Macbook Air (although I would recommend against Catalina !).

**Comment by glouel** [comment]
@briantully I see you have edited your first post to add the full crash log, but:

```
PlugIn Version:          1.8.0 (1.8.0)
```

If you want me to look at it, could you give me a crash log with 1.7.1 maybe ? Thanks

**Comment by briantully** [comment]
Hi @glouel 
Thanks for the response :)

I would love to hear about the "unofficial" options to run newer versions of OSX on this old and trusty box. Indeed I've been avoiding Catalina even on my main laptop (Mid-2018 MacBook Pro).

Here's the crash log for v1.7.1. Thanks for taking a look at it :)

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY
```

[Aerial-1.7.1-crash.log](https://github.com/JohnCoates/Aerial/files/4256431/Aerial-1.7.1-crash.log)

**Comment by glouel** [comment]
About the options, check these : 
http://dosdude1.com/catalina/
http://dosdude1.com/mojave/
http://dosdude1.com/highsierra/

Basically it patches the installer to allow it to work on older macs, and includes community patches too for various hardware (with semi frequent updates). I would probably recommend mojave, or high sierra. But I would **highly** recommend you install on a separate partition/disk though, this way you can keep your old system around if needed. 

And thanks for the log, a quick look suggest it crashes around the animation system, the thing is, I don't recall changing much in 1.7.1 around that. I'll have a further look when I get a sec ! 

What's crazy is that the crash happens at the same place as 1.8.0, which I would have thought would not run at all on those systems considering I move the minimum compile target. But somehow macOS don't care (I'm pretty sure it does for apps, but apparently not for plugins !). One more oddity I'm learning today I guess !

**Comment by glouel** [comment]
Just wanted to let you know that I haven't forgotten you, however I'm having issues finding a El Capitan full installer for vmware from Apple (or a somewhat reputable source). I do have Sierra to Catalina though, so I'll give Sierra a shot to see if it happens there too in the meantime :)
