### ISSUE TITLE
Crashing when trying to access the options

### ISSUE THREAD

**Issue by beerbaron23** [JohnCoates/Aerial#939]
Since upgrading to 1.8.0 the screensaver will crash when you go to open up the "Screen Saver Options" before the options screens are shown. The problem can be fixed temporarily by deleting the .plist file, but after trying to go into the options a 2nd or 3rd time it will start to crash again and deleting the .plist file is required again to get it to work. The screensaver itself still works, but no access to the options...

Running OSX High Sierra 10.13.6 with latest updates.

**Comment by glouel** [comment]
Hi @beerbaron23 

Any chance you can give me the crash log ? Go into Console.app and you should find it. Let me know if you need more directions. 

This might be the same issue that seems to happen on 10.11 on this issue : https://github.com/JohnCoates/Aerial/issues/936 , I'll try to get a High Sierra machine running to double check.  

In the meantime you should probably revert to 1.7.0. Sorry about that, I'll keep you updated next week.

**Comment by beerbaron23** [comment]
There is a bunch of stuff listed in the Console.app, which parts do you need? (I'm not well versed with Console logs)

Another bug i've noticed, is that if you try and change the Cache directory it will not see any of my existing videos, I had to move all my videos to the default cache directory and only then will the screensaver recognize them.

Note that the issue might be different then #936 as in my issue you can indeed select the screensaver and it will function, it's just the options crash/accessible. I included the Aerial log if that might help.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4270917/AerialLog.txt)
.

**Comment by glouel** [comment]
> There is a bunch of stuff listed in the Console.app, which parts do you need? (I'm not well versed with Console logs)

I'm not 100% sure it's the same in High Sierra (I think it was), but this is how it was in Mojave : https://github.com/JohnCoates/Aerial/issues/681#issuecomment-443729062

Let me know if you find something there !

> Another bug i've noticed, is that if you try and change the Cache directory it will not see any of my existing videos, I had to move all my videos to the default cache directory and only then will the screensaver recognize them.

This is a bit weird, one thing though, after changing the path, you need to close system preferences (fully, the whole thing), and reopen it and reopen Aerial's settings for it to reload your videos from the new location.
 
> Note that the issue might be different then #936 as in my issue you can indeed select the screensaver and it will function, it's just that the option screen crash/unaccessible. I included the Aerial log if that might help.
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4270917/AerialLog.txt)
> .

Indeed. I had a quick look, I found this instance of an incomplete start : 

```
2020-02-29 14:39:49.889 : pwc init2
2020-02-29 14:39:49.891 : Callback after manifest loading
2020-02-29 14:39:49.966 : Looking for outdated files
2020-02-29 14:39:49.967 : No old files found
2020-02-29 14:39:49.968 : Aerial control panel V1.8.0
2020-02-29 14:39:49.969 : Cache size : 15.07 GB
2020-02-29 14:39:50.686 : cvcinit2
2020-02-29 14:39:50.687 : cvcawake
2020-02-29 14:39:50.690 : wdl
```

So it crashed fairly early on in the process, but I can't tell a lot more from there. The crash log will tell me more.

**Comment by beerbaron23** [comment]
I believe these are the ones you are requesting.


[Crashlogs.zip](https://github.com/JohnCoates/Aerial/files/4271190/Crashlogs.zip)

**Comment by glouel** [comment]
> I believe these are the ones you are requesting.
> 
> [Crashlogs.zip](https://github.com/JohnCoates/Aerial/files/4271190/Crashlogs.zip)

Perfect, thanks for looking for them !

As you suspected the issue is different, for some reason it fails to load one of the UI files... which is about the weirdest thing I've seen so far ! I'll have to install a version of 10.13 and see what I can gather, as this doesn't make much sense to me I'm afraid. 

Again, sorry about the bug, I'll get back to you asap !

**Comment by glouel** [comment]
@beerbaron23 

I managed to install 10.13.6 but I can't reproduce the bug yet. Could you tell me about which changes you usually make in settings, to see if that helps me trigger the bug ?

**Comment by beerbaron23** [comment]
No need to apologize, I really dig this screensaver and all the work put into it to have all these options.

I reverted back to a previous release and it works fine, installed the newest beta and issue is back, here is the plist used that causes a crash on the newest beta.


[com.JohnCoates.Aerial.71CA71CC-E057-526E-957D-81D79DE6E7D6.plist.zip](https://github.com/JohnCoates/Aerial/files/4282470/com.JohnCoates.Aerial.71CA71CC-E057-526E-957D-81D79DE6E7D6.plist.zip)

**Comment by glouel** [comment]
Great, thanks a lot, I'll have a look and let you know !

**Comment by glouel** [comment]
Damn, the bug wasn't linked at all to High Sierra. There was a bug if you disabled automatic update checks which crashed the panel. I'll double check it and make a new release :)

**Comment by glouel** [comment]
There you go : https://github.com/JohnCoates/Aerial/releases/tag/v1.8.1

Let me know, but I'm 99% sure I got it ;)

**Comment by beerbaron23** [comment]
Took it for a test drive and it's fully stable now. Interesting that it was a bug that could affect everyone, I was assuming it was High Sierra/older version related as well.

Awesome work man with a quick resolution, I'm impressed!

**Comment by glouel** [comment]
Yeah, I usually test all options, but I made a last minute change to make the code more readable/look better, which is *always* a bad idea :)

Funny thing is, the crash log was completely unhelpful (and to be clear, it generated the same crash log here !), it actually crashed in another thread but macOS seems to get confused if something crashes while it loads a nib (the ui file) and misreport the crash. That's the second time that I see that oddity. At least it didn't take me a couple of months to track it this time !

Anyway, glad to hear it's fixed, enjoy !
