### ISSUE TITLE
How to intall?

### ISSUE THREAD

**Issue by thte5thbeatle** [JohnCoates/Aerial#941]
I'm running Aerial 1.8.0, and there was a message on my Aerial Screensaver saying an update was available. So I downloaded Aerial 1.8.1, but it once I opened the downloaded Aerial.saver.zip. there was not an Aerial.saver to click on to automatically install it onto my Mac.

How do I go about installing the update?

Thanks in advance for your help.

**Comment by glouel** [comment]
Hi @thte5thbeatle 

Can you try again with this link ? https://github.com/JohnCoates/Aerial/releases/download/v1.8.1/Aerial.saver.zip

I just double checked, the file is inside the zip, maybe your download got interrupted or something, it can happen sometimes. 

Let me know if you still have an issue !

**Comment by thte5thbeatle** [comment]
Thank you for getting back to me so quickly!

I was able to download from the link you provided, and it installed itself.
Is it Aerial 1.8.1?
My system said I had already installed it on my computer, so I had it
reinstall this new download. I don't know if I reinstalled the older
version or if it's the update.

-Patti

**Comment by glouel** [comment]
> Thank you for getting back to me so quickly! I was able to download from the link you provided, and it installed itself.

Great !

> Is it Aerial 1.8.1? My system said I had already installed it on my computer, so I had it reinstall this new download. I don't know if I reinstalled the older version or if it's the update.

So, each time you update, System Preferences will ask you if you want to override the existing version. That's pretty normal. Before installing, I always recommend you close System Preferences (make sure the window is closed). This helps a bit.

To double check, if it's installed correctly, make sure you have closed System Preferences, then open it again and to into the screen saver settings, and open Aerial's panel :

![Capture d’écran 2020-03-03 à 23 09 25](https://user-images.githubusercontent.com/37544189/75824652-2ed5ba80-5da4-11ea-8d80-38944bd4812e.jpg)

You can see which version is installed circled in red ! Make sure you have closed System Preferences before or after installing, to make sure it reloads correctly (if you don't, it will still show 1.8.0).

**Comment by thte5thbeatle** [comment]
Many thanks again for taking the time to get back to me!
I'm Aerial running 1.8.1  and loving it!

-Patti

**Comment by glouel** [comment]
Happy to help and always love to hear that people enjoy it ! Take care !
