### ISSUE TITLE
Custom Videos play within options view but not preview and ultimately not as a screensaver

### ISSUE THREAD

**Issue by mckennedy** [JohnCoates/Aerial#944]
I've followed the documentation to include custom videos. I add the folder and I have 2 videos (MP4 H264). One for day and one for night. I've unchecked all other videos that come with the screen saver. The videos play fine within the Screen Saver Options view. I click Close and the screen saver preview is black. If I click Preview, the screen saver maintains being solid black. If I click Screen Saver Options again the videos are still there and play fine. If I close the Desktop & Screen Saver preferences completely and return, click Screen Saver Options, scroll to my videos and select either of my videos, the preview is now a play icon crossed out as if the video is invalid. Would appreciate help!

**Comment by glouel** [comment]
Hi @mckennedy 

I assume you are using Catalina ? There's a bug in Catalina where the screen saver Preferences Sheet can access files that are stored in your documents or desktop once when you add them, but not afterwards. 

I really need to add a warning or something, here's what I would recommend, create a folder in `/Users/Shared/` and put your custom videos there. Then add to Aerial from there, then it should work. Please let me know if that works !

**Comment by mckennedy** [comment]
That was absolutely the issue. Many thanks!

**Comment by glouel** [comment]
Awesome ! Sorry about that, it's one of those weird restrictions that Apple introduced in Catalina with sandboxing screen savers (all of them undocumented) and that particular one was reported not long ago, I really need to put a message somewhere about that. I'll do that in the documentation right now and will see to add a warning in the UI too at some point. 

Take care.
