### ISSUE TITLE
Secondary Monitors display incorrect Location information when skipping

### ISSUE THREAD

**Issue by bluestarstudios** [JohnCoates/Aerial#945]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: iMac (27-inch, Late 2013)
- [ ] macOS version: 10.13.6
- [ ] Monitor setup: 3 monitors
- [ ] Aerial Version: 1.8.1

#### Description of issue / Feature request

If you use the right arrow to skip to the next video, the primary monitor updates the location text accordingly. The secondary monitors, however, do switch to the new text, but then they start displaying the location text for the previous video(s) when those would have been displayed within the original video. I was able to replicate this behavior multiple times.

Example: Triggered the screensaver, the first video was a flyover over London. Hit "next" (right arrow). Videos updated to a space flyover over the Pacific Ocean. All location texts updated accordingly on all three monitors.
After a few seconds the main display was still showing correct information:
![IMG_0768](https://user-images.githubusercontent.com/7295261/76060066-4abc9600-5f35-11ea-82a1-e5e025cc08b2.JPG)

On the other hand, the secondary displays were now showing location info from the London flyover.
![IMG_0767](https://user-images.githubusercontent.com/7295261/76060289-c6b6de00-5f35-11ea-9bc1-5a9c14b93ef1.JPG)

**Comment by glouel** [comment]
Oops ! I have a pretty good idea of what's going wrong here, I'll have a look and get back to you. Since skipping no longer works in Catalina I'll be unable to test the fix so you'll have to do that for me. I'll get back to you later today thanks !

**Comment by glouel** [comment]
@bluestarstudios sorry for the lag, I looked in the wrong place the other day when I thought it was an easy fix. Please give a try to this beta, I'm 94% sure I got it : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta1/Aerial.saver.zip

**Comment by bluestarstudios** [comment]
Hi Guillaume. That did the trick! Thanks.
On a side note, in this new beta version, hitting the Preview button in System Preferences blacks out the screens but the screensaver never actually starts.
David

**Comment by glouel** [comment]
> Hi Guillaume. That did the trick! 

Awesome !

> Thanks. On a side note, in this new beta version, hitting the Preview button in System Preferences blacks out the screens but the screensaver never actually starts. David

That's weird. Could you send me a log ? Enable it in Advanced, and launch preview once then attach the log here. Thanks !

**Comment by glouel** [comment]
Closing with 1.8.2 finale release, please reopen if you still have a bug
