### ISSUE TITLE
[Feature Request]: Randomise video order

### ISSUE THREAD

**Issue by lengland** [JohnCoates/Aerial#946]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Macbook Pro 2018
- [x] macOS version: Catalina 10.15.3
- [x] Monitor setup: Switch between laptop only and laptop + external 1080p

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Hi, 

This is a fantastic tool, but I would like to see an option for randomising the order of the videos. When I lock my mac the videos always follow the same order. I would like to see a random video from the list I have checked in the options. 

Thanks

**Comment by glouel** [comment]
Hi @lengland 

That's a bit weird, I was pretty sure I fixed that a long time ago... Can you tell me which version of Aerial you are running ? 

Just to make sure I understand, if you launch/exit the screensaver several times in a row (with a hot corner), you're always getting the same first video ? (again, just double checked here, it's definitely random !)

The only thing that touches that is the Time Synchronization in the Advanced tab. Can you check if you have that you have that option below, in blue, unchecked ? 

![Capture d’écran 2020-03-06 à 14 04 14](https://user-images.githubusercontent.com/37544189/76085988-767e6100-5fb3-11ea-819b-6e86d2bf0fd6.jpg)

With Time Sync check, you'll get the same playlist for one minute. 

The way the randomizer works is that when Aerial starts, it generates a random playlist with your selected videos. It plays/plucks from the list and when it's empty, it generates a new random one (based on possibly new conditions, say you want day videos by day and night at night, and start Aerial before dusk, the first playlist will be day videos, and the next playlist will be night videos), and so on.

Let me know which version you are running and if you have that option unchecked.

**Comment by lengland** [comment]
Hi @glouel 

I am running v1.8.1 and have checked the config - I had Sync computers checked. 
When I launch screensaver on my mac the same video would always start no matter the time of day - I can't remember if the following videos are the same also, I can have a check if you want to know more.

Unchecking this has allowed random order to resume. Thanks for your solution.

**Comment by glouel** [comment]
> Hi @glouel
> 
> I am running v1.8.1 and have checked the config - I had Sync computers checked.
> When I launch screensaver on my mac the same video would always start no matter the time of day - I can't remember if the following videos are the same also, I can have a check if you want to know more.
> 
> Unchecking this has allowed random order to resume. Thanks for your solution.

Good to hear. It's still weird that this caused it. This option is going away soon, to be replaced by a better sync method so that shouldn't be an issue for much longer. Thanks for confirming this worked !
