### ISSUE TITLE
Countdown suggestion

### ISSUE THREAD

**Issue by cxy5014** [JohnCoates/Aerial#947]
Hi,
Could you please add a day countdown instead of month?

**Comment by glouel** [comment]
Hi @cxy5014 

Yep, I really need to add more time formatting options. I'll get back to you soonish.

**Comment by glouel** [comment]
@cxy5014 I reworked it a bit, and removed month/year, it will only show days/hours/minutes and optionnally seconds (which you can now really disable). 

Beta here, let me know : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta2/Aerial.saver.zip

**Comment by cxy5014** [comment]
@JohnCoates Thanks, you are so kind.
