### ISSUE TITLE
Overlapping info text for longer strings

### ISSUE THREAD

**Issue by oxxie** [JohnCoates/Aerial#949]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro (15-inch, Late 2016)
- [ ] macOS version: 10.15.3 (19D76)
- [ ] Monitor setup: Built-in Display 15,4-inch (2880 x 1800)

#### Description of issue / Feature request
I have Aerial set up so that the lower left corner contains the Location info, while the lower right corner contains the Clock and Battery info. Generally this works very well, however some Location info strings are quite long (e.g. the start of Los Angeles Downtown Night) and therefore may overlap the other info. I would like to suggest to have the Location info wrap onto a new line in these cases, balancing out the width of both lines for aesthetic reasons. Thanks!

**Comment by glouel** [comment]
Hi @oxxie 

Yep, that's one the next few things I have to take care of, I should have a beta up this week with that change, will let you know.

**Comment by oxxie** [comment]
Great @glouel! Let me know if you need any more information.

**Comment by glouel** [comment]
No prob, I know where the bug is, it's just that the last few weeks have been a tad hectic, but I should have a fix soonish ;)

**Comment by glouel** [comment]
@oxxie sorry took me a while but I finally managed to get to it, please try beta4 here : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta4/Aerial.saver.zip

Here's an example with very large fonts, it will multi line split as needed :

![Capture d’écran 2020-03-23 à 17 09 36](https://user-images.githubusercontent.com/37544189/77339340-e7e83e80-6d2b-11ea-90ac-a9347dd3391e.jpg)

**Comment by oxxie** [comment]
Hi, I'm afraid beta4 didn't solve the issue for me...

<img width="1680" alt="Screen Shot 2020-03-24 at 07 05 00" src="https://user-images.githubusercontent.com/25564375/77393864-44844180-6d9e-11ea-8731-ee3d64eb2371.png">

Can I provide you with any information for your debugging?

**Comment by glouel** [comment]
Hi @oxxie 

Did that happen on the very first message ?

**Comment by oxxie** [comment]
Hi, just did some tests with larger font sizes. For me, it seems that the issue is still there regardless of whether it is the first displayed info or a later one... So sadly, I can't confirm.

**Comment by glouel** [comment]
I just had a thought, you probably have your location set on the left corner and not random ? 

I was so obsessed with fixing the random case (which is so much harder) that I forgot the simple ones 🙈

**Comment by glouel** [comment]
@oxxie I can confirm, I reproduced the bug when picking a fixed position for Location, and fixed it ;) I'm trying to fix a couple more bugs but I'll release this later today : 

![Capture d’écran 2020-03-24 à 14 19 48](https://user-images.githubusercontent.com/37544189/77430299-3bfe2c00-6ddb-11ea-96d6-5bc75e3895ac.jpg)

Thanks for following up with me on this !

**Comment by glouel** [comment]
@oxxie I'm pretty sure I got it this time, including the very first message, it should work ok now : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2/Aerial.saver.zip

**Comment by oxxie** [comment]
Yes, I can confirm the issue has been resolved. Great work @glouel!
