### ISSUE TITLE
[Feature request] Add the function of loop playback

### ISSUE THREAD

**Issue by ruochem** [JohnCoates/Aerial#952]
- [x] Mac model: MacBook Pro (15-inch, 2019)
- [x] macOS version: 10.15.3
- [x] Monitor setup : 3

**Feature request**

After playing one video, continue to shuffle other videos. And add a fade in effect during this period.

**Comment by glouel** [comment]
Hi @ruochem 

I'm not sure I understand, could you expand a little bit ? What do you mean by loop playback ?

Your description is how Aerial work, after playing one video, it will fade out/in and play another random one. I don't get the loop part ?

**Comment by ruochem** [comment]
Yes, as you said. I hope that Aerial can continue to play other videos after playing one video, instead of keeping the last frame of the picture.

**Comment by glouel** [comment]
@ruochem could you enable the logs in Advanced and send one to me ? Looks like you're hitting a bug. Thanks.

**Comment by glouel** [comment]
Just in case this is fixed in 1.8.3beta1
