### ISSUE TITLE
Issue with display of screensavers in system preferences

### ISSUE THREAD

**Issue by mbellis18** [JohnCoates/Aerial#956]
This is driving me nuts, in the screensaver preferences pane all my screensavers are suddenly listed in a single row rather then side by side, screenshot attached.  I have erased my Mac to try and resolve and it returns each time.  Anyone else seeing similar behavior or have a suggestion for resolution.  

Thanks in advance!

macOS:  10.15.4 (19E266)
Model:  MacBook Pro (15-inch, 2016), MacBookPro13,3
Display:  Built-In Retina LCD, Resolution:  2880 x 1800 Retina
Aerial Version:  1.8.2

<img width="780" alt="Screen Shot 2020-03-26 at 8 32 58 PM" src="https://user-images.githubusercontent.com/44421177/77812492-06c23a00-7078-11ea-8336-645448ca9c55.png">
<img width="780" alt="Screen Shot 2020-03-26 at 11 05 48 AM" src="https://user-images.githubusercontent.com/44421177/77812494-0a55c100-7078-11ea-85e2-50190b9dfd96.png">

**Comment by glouel** [comment]
Hi @mbellis18 

This may not help but I have that same issue on my non retina Macbook Air, it seems to be a long standing bug. 

My rough guess is that the bug may depend on your scaling settings in MacOS, as the column might be one pixel too short and depending on rounding it fits two or one. So not much to say apart that it seems to be a UI bug on Apple's end. So I would suggest playing with the scaling options and see if you see stuff changing, but that's probably about it !

**Comment by mbellis18** [comment]
I have formatted my Mac about 6 or 7 times in the past few days trying to figure out what causes it, what's interesting is each time on initial startup there are 2 rows like I expect, except 1 time it was a single row which lead me to believe it is a macOS bug...  But within a few minutes it randomly switch back to a single row, even before adding any 3rd party savers.  However I have also figured out that if I skip adding my Apple ID during the setup process after clean install then it sticks with 2 rows even after adding the 3rd party savers.  That led me to think maybe it was something in my iCloud settings or iCloud Drive files... deleted almost all the files in my iCloud Drive and did another erase and it doesn't seem to be that.  In iCloud settings it does show that System Preferences stores data in iCloud but I can't seem to find anything on the web about what it stores, nor does it seem that any system preferences carry over and sync to different devices...

Also tried all the scaling settings available and that doesn't have any effect.  

Thanks for the reply, any ideas if there are any disadvantages to not adding my Apple ID during the initial setup?  I may erase it one more time lol!

Be well and stay safe!

**Comment by glouel** [comment]
> I have formatted my Mac about 6 or 7 times in the past few days trying to figure out what causes it, what's interesting is each time on initial startup there are 2 rows like I expect, except 1 time it was a single row which lead me to believe it is a macOS bug... But within a few minutes it randomly switch back to a single row, even before adding any 3rd party savers. 

That's super intriguing...

> However I have also figured out that if I skip adding my Apple ID during the setup process after clean install then it sticks with 2 rows even after adding the 3rd party savers. That led me to think maybe it was something in my iCloud settings or iCloud Drive files... deleted almost all the files in my iCloud Drive and did another erase and it doesn't seem to be that. In iCloud settings it does show that System Preferences stores data in iCloud but I can't seem to find anything on the web about what it stores, nor does it seem that any system preferences carry over and sync to different devices...

I don't think that's documented nope, so just to be clear, you *never* hit the bug just if you never sync iCloud settings ? Or you don't hit the bug just if you don't sync at install, but add your account later ?

> Also tried all the scaling settings available and that doesn't have any effect.

There goes my theory !

> Thanks for the reply, any ideas if there are any disadvantages to not adding my Apple ID during the initial setup? I may erase it one more time lol!

As far as I know, none, you can always add later. If that works for you then stick with that I'd say !

> Be well and stay safe!
You too !

**Comment by glouel** [comment]
Had one more thought while pouring a coffee :

> what's interesting is each time on initial startup there are 2 rows like I expect [...] But within a few minutes it randomly switch back to a single row, even before adding any 3rd party savers. 

The fact that it changes after a few mins could be consistent with some plist settings getting synced from the cloud and being applied. It's possible though that if you don't have your account setup at install, and go to this panel (and close it), you'll get some settings saved that may not get erased later on when your account is added.  In any case, stick with that and you could consider filing a radar with Apple through Feedback Assistant, it's an interesting one !

**Comment by josroling** [comment]
I can not use the screensaver any more. I get the error message:
![error](https://user-images.githubusercontent.com/16956677/78028450-58f8a900-735f-11ea-90d1-c6b97288c8ca.png)

**Comment by glouel** [comment]
> I can not use the screensaver any more. I get the error message:
> ![error](https://user-images.githubusercontent.com/16956677/78028450-58f8a900-735f-11ea-90d1-c6b97288c8ca.png)

Hi @josroling 

Which version did you get ?

**Comment by josroling** [comment]
I had two versions installed, it defaulted to the old version. After deinstalling the old version and a reboot, it works. Thank you for the support.

**Comment by josroling** [comment]
I had two version installed, it defaulted to the old version, hence the error. After deinstall and a reboot, it works again.

thank you!


\jos

**Comment by 1aurabrown** [comment]
hello, I am trying to create a screensaver of my own and I ran into this issue of "notarization." If you're willing to share, I'd be interested to know how you fixed this issue.

Thanks!

**Comment by glouel** [comment]
@1aurabrown I documented it a while back in this message, have a look : https://github.com/JohnCoates/Aerial/issues/801#issuecomment-530439586

It should be fairly straightforward if you follow the steps I describe in there. Be aware all of this may change around WWDC if Apple finally introduces a new screensaver API.
