### ISSUE TITLE
屏保出现2分钟后就不动了

### ISSUE THREAD

**Issue by JayChou007** [JohnCoates/Aerial#957]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
- [x] macOS version: 
- [x] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by cxy5014** [comment]
Have you ever downloaded a video in system preferences or manually? Downloading video from Apple's official servers can be slow in China.

**Comment by JayChou007** [comment]
Have you ever downloaded it? Is that the reason why it is slow to download in China?

**Comment by JayChou007** [comment]
Resolved, network download issue

**Comment by glouel** [comment]
@JayChou007 this may not be helpful but I've heard multiple times that those specific Apple servers are slowed down/blocked in China and that the solution is using another connexion (VPN, etc). 

If you have access to such a connexion on another machine, there are some instructions here to download the video and transfer them : https://github.com/JohnCoates/Aerial/blob/master/Documentation/OfflineMode.md

If it's a unix machine, check this post for instructions on how to automatically grab them : https://github.com/JohnCoates/Aerial/issues/801#issuecomment-500205534

Take care
