### ISSUE TITLE
Video no longer looping

### ISSUE THREAD

**Issue by sirschuyler** [JohnCoates/Aerial#959]
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (Retina, 15-inch, Early 2013)
- [x] macOS version: 10.14.6
- [x] Monitor setup: Built-in Display - 15.4-inch (2880 x 1800)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Video no longer looping. Only one video selected in my case. Screen stays black after single play… display still on and login option available on mouse move or key click.

Fade in/out: 0.5 second
Video format: 1080p H264
No other features enabled (i.e. Info / Time / Brightness)
Single video selected appears to be downloaded and cached

Thanks for looking into it.

**Comment by glouel** [comment]
Hi ! Can you give me a debuglog that catches the hang ? Does it happen 100% of the time ? And please confirm which version you are using thanks !

**Comment by sirschuyler** [comment]
Hey there! Debug log attached.
Yes happens 100% of the time. FYI been using Aerial Saver for a while, not sure when the black screen, no loop issue occurred.
v1.8.2
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4441482/AerialLog.txt)

**Comment by glouel** [comment]
Thanks a lot ! I had a quick look, according to the log, Aerial actually rewinded the video, that's weird : 

```
2020-04-06 19:51:55.722 : start playback: (0.0, 0.0, 1440.0, 900.0) (0.0, 0.0, 1440.0, 900.0)
2020-04-06 19:54:50.069 : <AerialView: 0x7f994ba00000> played did reach end
2020-04-06 19:54:50.070 : <AerialView: 0x7f994ba00000> notification: name = AVPlayerItemDidPlayToEndTimeNotification, object = Optional(<AVPlayerItem: 0x600003201b60, asset = <AVURLAsset: 0x600003035680, URL = file:///Users/schuyler/Library/Application%20Support/Aerial/comp_N013_C004_PS_v01_SDR_PS_20180925_F1970F7193_SDR_2K_AVC.mov>>), userInfo = nil
2020-04-06 19:54:50.074 : Rewinding video!
```

If it's not too much trouble, could I ask you to delete that log and make another one, but after it goes black, let it run 5 more minutes with the black screen, that might give me a better clue of what's happening. I'll try to reproduce here tomorrow with that specific video, it's possible that the rewinding (which is a new thing, I added it so you get seamless looping but enabling it by default maybe was a wrong idea) causes issues on specific videos. 

I'll get back to you tomorrow with hopefully a fix !

**Comment by sirschuyler** [comment]
Cool. I'll create a new debug log and post here…
The display will probably sleep before 5 minutes is up. That okay? Or would you prefer I set display not to sleep for X minutes?

**Comment by glouel** [comment]
If you could make it not sleep that would be best ! Thanks !

**Comment by glouel** [comment]
@sirschuyler I reproduced the bug, will get you a new build soonish thanks for the report and sorry about that !

**Comment by sirschuyler** [comment]
@glouel Yay! Thanks for getting it figured out. I'll keep an eye out for new build.
Thanks again for your work and a great screen saver.

**Comment by glouel** [comment]
@sirschuyler here you go, this is a quick fix but this should work : 

https://github.com/glouel/Aerial/releases/download/v1.8.3test3/Aerial.saver.zip

**Comment by glouel** [comment]
Closing with 1.8.3beta1
