### ISSUE TITLE
Uninstallation documentation not complete

### ISSUE THREAD

**Issue by jkreller** [JohnCoates/Aerial#961]
#### Required information
- Mac model: MacBook Pro 2017
- macOS version: 10.15.3

#### Description of issue / Feature request
I found out that when I follow the [uninstallation documentation](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md#uninstallation), the following directory (which has for me 8GB of size) is not removed:
`/Users/USERNAME/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial`
It stores videos, a log and backups.

**Comment by glouel** [comment]
Hi @jkreller !

Sorry for the late reply, yes, with Catalina the paths changed to this sandboxed location and the doc hadn't caught up. I'll update the documentation right now, thanks for the heads up!

**Comment by glouel** [comment]
Changes here with more details : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md 

Thanks again!
