### ISSUE TITLE
Unable to turn off time display

### ISSUE THREAD

**Issue by KarmaLlama** [JohnCoates/Aerial#962]
Mac model: Mac mini mid 2012
macOS version: High Sierra
Monitor setup: External 1080p Monitor via HDMI

#### Description of issue / Feature request

The screensaver always displays the time in the bottom left corner irrespective of the corresponding setting in the screensaver options

**Comment by glouel** [comment]
Hi @KarmaLlama 

That's weird.

Just in case, are you unchecking that box circled in red here ? 

![Capture d’écran 2020-04-17 à 17 47 19](https://user-images.githubusercontent.com/37544189/79588052-aef57c80-80d3-11ea-9ed1-ec2575d40a4d.jpg)

When you disable it, the dot goes red in the left column.

If so, can you confirm which version you are using ?

**Comment by KarmaLlama** [comment]
So sorry, wasted your time. I was unchecking show with clock. Getting old LOL, thanks so much glouel

**Comment by glouel** [comment]
No worries take care !
