### ISSUE TITLE
Can't Select Done or Exit System Preferences

### ISSUE THREAD

**Issue by Herlordship** [JohnCoates/Aerial#963]
After downloading and installing Arial Saver and it installing it (apparently an old version, found here https://youtu.be/lbj9kihTwcc), once in System Preferences, I selected Arial and it opened a new window to choose which cities and days, etc. and if I want to have a different display on each screen.  It will not allow me to select "done."  I cannot quit System Preferences.  I tried uninstalling and reinstalling, which has made no difference.  

I have downloaded the latest from this page:  https://github.com/JohnCoates/Aerial/releases/tag/v1.8.2

Double clicking to install does nothing, just takes me back to System Preferences with the non-functional Done button.

I'm running Mojave 10.14.6 

Macbook Pro

**Comment by glouel** [comment]
Hi @Herlordship 

This sounds like you are actually running an old version of Aerial which is stuck (I renamed the "Done" button to "Close" a while back).

So first, before installing 1.8.2, you have to force quit System Preferences. Right click on System Preferences in your dock, press Alt (the option key), then pick force quit.

Now, you can safely install 1.8.2 and you'll be able to use it correctly.

**Comment by Herlordship** [comment]
HI!  Force Quit is not an option, sadly.

**Comment by Herlordship** [comment]
<img width="273" alt="Screen Shot 2020-04-17 at 3 48 59 PM" src="https://user-images.githubusercontent.com/63876214/79608425-fa535f00-80c2-11ea-8d5e-e5c1cd274377.png">

**Comment by Herlordship** [comment]
I did command + opt + esc and was able to force quit.  It works, thank you SO much!

**Comment by glouel** [comment]
Yep, when you are there, press Alt at the left of your space bar (the one that looks like a Fork with 2 prongs), and Quit will switch to Force Quit.

**Comment by glouel** [comment]
Good to hear and happy to help. Remove the old version, install the new one and you're good to go.

**Comment by Herlordship** [comment]
Yup! It's all good! Thanks!
