### ISSUE TITLE
Would it possible to have the Greece ? The Acropolis? The Parthenon?

### ISSUE THREAD

**Issue by stamatgeorge** [JohnCoates/Aerial#964]
https://www.youtube.com/watch?v=FxRyNuaSeCg
https://www.youtube.com/watch?v=J-nnkD5Ep4Y

https://www.youtube.com/watch?v=_2oFV2Myq88

**Comment by buddhaCode** [comment]
I guess it's a bit out of scope for this project. You can try [VSaver](https://github.com/pendowski/VSaver) to play random online video.

**Comment by glouel** [comment]
Hi @stamatgeorge 

As @buddhaCode said, the video Aerial uses are coming from Apple, so it's not our choice. 

You can however add your own videos to Aerial, so you can consider saving the ones you like on Youtube or whereever, and add them yourself to your rotation. Instructions here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/CustomVideos.md

**Comment by stamatgeorge** [comment]
I understand. Thanks so much ❤️
