### ISSUE TITLE
[REQUEST] Download Only...

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#966]
Good afternoon!

I am writing in with a request to optimize the Videos section tab. Under the options tab located at the bottom of the videos tab:

<img width="259" alt="Screen Shot 2020-04-19 at 1 11 43 PM" src="https://user-images.githubusercontent.com/18543749/79694598-5216d500-823f-11ea-8a8f-a4b563207cfd.png">

I would like to see the following options added:

- Check only "Day" Videos
- Check only "Night" Videos
- Check only specific location videos > And have a subsequent menu or option to select which specific location. 

I realized this option would be a huge help after deciding that I wanted to check and download only nighttime videos but that there was no easy way to select just a given subset of them. 

Thanks so much!

**Comment by glouel** [comment]
That's a good idea. I planned to rework the whole video selection/enabling process as part of adding a cache size limit but that's a quick stop gap in the meantime. I'll keep you posted !

**Comment by ZV00** [comment]
> That's a good idea. I planned to rework the whole video selection/enabling process as part of adding a cache size limit but that's a quick stop gap in the meantime. I'll keep you posted !

I saw that idea mentioned and I totally support that change as well, I think a cache limit will be a huge help as well! Thanks for your time and consideration!

**Comment by glouel** [comment]
So I added Check only day and night. I'll also add the submenu but didn't get it to work today, so it will be for a next beta ;)

https://github.com/JohnCoates/Aerial/releases/download/v.1.8.3beta3/Aerial.saver.zip

**Comment by ZV00** [comment]
Just tested it out and it's great! Thanks so much, that was super fast! Using it right now!!
