### ISSUE TITLE
No Sound?

### ISSUE THREAD

**Issue by cptwalker1** [JohnCoates/Aerial#971]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: IMac Retina 5K, 27 inch, 2019
- [ ] macOS version: Catalina 10.15.4
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I get no sound with my videos. They are .mov and they have sound, but not when used for screen saver. What am I missing? Is there no sound with this app? Thanks.

**Comment by glouel** [comment]
Hi @cptwalker1 

Do you mean with Custom Videos you've added yourself ? 

The Apple TV videos have no sound, and by request from others I do mute the sound on custom videos (the general feeling was that it was distracting for a screensaver). Is that your issue ?

**Comment by cptwalker1** [comment]
Yes. Thank you for the quick response. A function to turn on or off the sound would be nice. That way ASMR videos would be nice as a screensaver.

**Comment by glouel** [comment]
> Yes. Thank you for the quick response. A function to turn on or off the sound would be nice. That way ASMR videos would be nice as a screensaver.

Ha I see. Yep that would definitely make sense for those videos. I'll get back to you tomorrow, should be an easy fix.

**Comment by glouel** [comment]
@cptwalker1 give a shot to beta5 : https://github.com/JohnCoates/Aerial/releases/download/v1.8.3beta5/Aerial.saver.zip

There's a new checkbox in advanced tab, uncheck to unmute sound.

**Comment by cptwalker1** [comment]
Perfect! You are a genius!
