### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#983]
MacMini, 10.15.4, HP 4K 27" monitor

Description of issue / Feature request
I've been running Aerial for three days, and had it freeze twice (on a new Mac with plenty of memory). I have my Mac set to never sleep (and to never sleep the monitor, because it's hard to un-sleep), so Aerial runs all night, making problems more likely to appear.

This time, when I stopped the screensaver, there was a notice that Apple wanted me to sign in again to my iCloud account. I have no idea if that's coincidental or not. 

Would a log file be helpful?

**Comment by glouel** [comment]
> I've been running Aerial for three days, and had it freeze twice (on a new Mac with plenty of memory). I have my Mac set to never sleep (and to never sleep the monitor, because it's hard to un-sleep), so Aerial runs all night, making problems more likely to appear.

Can you clarify freezing ? Like, the image is frozen, but what happens when you wake it up usually ? Do you get the prompt instantly ? 
 
> This time, when I stopped the screensaver, there was a notice that Apple wanted me to sign in again to my iCloud account. I have no idea if that's coincidental or not.

I would say 99.9% coincidental. 
 
> Would a log file be helpful?

If you have it sure. From what I read though, I would guess maybe you haven't cached the videos and were streaming at the time ? Streaming is notoriously unreliable (Apple servers are not setup for it) and it can cause Aerial to get stuck. I would suggest downloading the videos you want, so they are cached, (uncheck what's not cached in the main panel) and you should not experience freezes again. 

If everything was cached already then yep, a log would help. Thanks

**Comment by Jimmbo** [comment]
Sorry for being vague. The image freezes, not the app. I can exit easily back to Finder without anything like a force quit.

[Here's a screenshot of my caching prefs](http://i.imgur.com/a5fhJtq.png)

Let me know which log you'd like.

**Comment by glouel** [comment]
> Sorry for being vague. The image freezes, not the app. I can exit easily back to Finder without anything like a force quit.
> 
> [Here's a screenshot of my caching prefs](http://i.imgur.com/a5fhJtq.png)
> 
> Let me know which log you'd like.

Looking at the size of your cache, you probably haven't cached all the videos yet. Please check the main panel : 

![Capture d’écran 2020-05-05 à 18 15 19](https://user-images.githubusercontent.com/37544189/81089420-a2a75700-8efc-11ea-839d-2352aa525d88.jpg)

Videos that aren't cache will have a little + next to them (cicled in red). To quickly disable the videos that currently aren't cached, you can use the button I circled in yellow, then "Check only cached". This will make sure you won't stream new videos.

**Comment by Jimmbo** [comment]
I would rather download/cache all of them rather than limit the variety! 

Perhaps I should make this a separate issue, but I'd propose a single button to do this (and, if appropriate, a way to change default location to an external drive for disk space reasons). And include an explanation of why this helps the app run more smoothly (I can help with copywriting if you ever need it, btw; I'm a professional writer/author).

**Comment by glouel** [comment]
> I would rather download/cache all of them rather than limit the variety!
> 
> Perhaps I should make this a separate issue, but I'd propose a single button to do this (and, if appropriate, a way to change default location to an external drive for disk space reasons). And include an explanation of why this helps the app run more smoothly (I can help with copywriting if you ever need it, btw; I'm a professional writer/author).

There is ! Click the Yellow button I circled above, download all, the missing videos will download one by one (with 4 threads). You'll see a progress bar for each video and a global bar at the bottom (left of the show debug button). 

Keep the panel open, it can take a while depending on your connection (you'll get a warning if you try closing it if not finished).

**Comment by Jimmbo** [comment]
One more comment: If the app needs to download all videos first to work right, it would be great if that could be fixed. Caching should work (I'm not complaining, I love your implementation).

**Comment by Jimmbo** [comment]
I followed your directions, but there was an error: Couldn't download video: A server with the specified hostname could not be found.


12:19:36 PM : avInit .saver (0.0, 0.0, 296.0, 184.0) p: true o: true
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> AerialView setup init (V1.8.2) preview: true
12:19:36 PM : Time Management initialized
12:19:36 PM : Display Detection initialized
12:19:36 PM : ***Display Detection***
12:19:36 PM : 1 display(s) detected
12:19:36 PM : 1cm = 32.086614655120954 points
12:19:36 PM : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {144, 144}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1920, 1080}, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 59592000, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace]
12:19:36 PM :        bottomLeftFrame (0.0, 0.0, 1920.0, 1080.0)
12:19:36 PM : src orig : (0.0, 0.0)
12:19:36 PM : left 0.0 below 0.0
12:19:36 PM : [id=59592000, width=1920, height=1080, bottomLeftFrame=(0.0, 0.0, 1920.0, 1080.0), topRightCorner=(1920.0, 1080.0), isMain=true, backingScaleFactor=2.0]
12:19:36 PM : (0.0, 0.0, 1920.0, 1080.0)
12:19:36 PM : ***Display Detection Done***
12:19:36 PM : Using : nil
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
12:19:36 PM : Using dot workaround for video driver corruption
12:19:36 PM : Manifest init
12:19:36 PM : app support exists
12:19:36 PM : No customvideos.json at : /Users/Jimleff/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json
12:19:36 PM : isManifestCached 10 true
12:19:36 PM : isManifestCached 11 true
12:19:36 PM : isManifestCached 12 true
12:19:36 PM : isManifestCached 13 true
12:19:36 PM : 2020-05-03
12:19:36 PM : Interval : Optional(-217176.0771330595)
12:19:36 PM : No need to check for new videos
12:19:36 PM : Manifests files were not loaded in class
12:19:36 PM : Files were not already loaded in memory
12:19:36 PM : Manifests are cached on disk, loading
12:19:36 PM : Poi Strings Provider initialized
12:19:36 PM : Preferred languages : ["en-US"]
12:19:36 PM : Best matched language : en
12:19:36 PM : Defaulting to bundle
12:19:36 PM : path : /Users/Jimleff/Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
12:19:36 PM : Community JSON : 99 entries
12:19:36 PM : No local or user cache exists, using ~/Library/Application Support/Aerial
12:19:36 PM : cache to be used : Optional("/Users/Jimleff/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
12:19:36 PM : Total videos processed : 99 callbacks : 0
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> Setting player for all player layers in []
12:19:36 PM : initvideocache
12:19:36 PM : cached video file with length: 333364462
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> playing video (OFFLINE MODE) : file:///Users/Jimleff/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/SE_A016_C009_SDR_20190717_3m30s_SDR_4K_HEVC.mov
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> observing current item <AVPlayerItem: 0x600001688e80, asset = <AVURLAsset: 0x6000014cfc60, URL = file:///Users/Jimleff/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application%20Support/Aerial/SE_A016_C009_SDR_20190717_3m30s_SDR_4K_HEVC.mov>>
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> observeValue Optional("readyForDisplay") false (0.0, 0.0, 296.0, 184.0)
12:19:36 PM : AssetLoaderDelegate deinit
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> backing change 2.0 isDisabled: false frame: (0.0, 0.0, 296.0, 184.0) preview: true
12:19:36 PM : <AerialView: 0x7fc5c8f0be80> observeValue Optional("readyForDisplay") true (0.0, 0.0, 296.0, 184.0)
12:19:36 PM : start playback: (0.0, 0.0, 296.0, 184.0) (0.0, 0.0, 296.0, 184.0)
12:19:37 PM : <AerialView: 0x7fc5c8f0be80> startAnimation frame (0.0, 0.0, 296.0, 184.0) bounds (0.0, 0.0, 296.0, 184.0)
12:19:37 PM : restarting playback
12:19:38 PM : <AerialView: 0x7fc5c8f0be80> stopAnimation
12:19:38 PM : pwc init2
12:19:38 PM : Callback after manifest loading
12:19:38 PM : Looking for outdated files
12:19:38 PM : No old files found
12:19:39 PM : Aerial control panel V1.8.2
12:19:39 PM : Cache size : 26.49 GB
12:19:39 PM : cvcinit2
12:19:39 PM : cvcawake
12:19:39 PM : wdl
12:28:00 PM : Video queued New York
12:28:00 PM : Starting download for New York
12:28:00 PM : Queued id=3BA0CFC7-E460-4B59-A817-B97F9EBB9B89,
name=New York,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov"]
12:28:00 PM : Video queued Sea
12:28:00 PM : Queued id=58C75C62-3290-47B8-849C-56A583173570,
name=Sea,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/MEX_A006_C008_SDR_20190923_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/MEX_A006_C008_SDR_20190923_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/MEX_A006_C008_HDR_20190923_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/MEX_A006_C008_HDR_20190923_HDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/MEX_A006_C008_SDR_20190923_SDR_4K_HEVC.mov"]
12:28:00 PM : Video queued China
12:28:00 PM : Queued id=F0236EC5-EE72-4058-A6CE-1F7D2E8253BF,
name=China,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C001_C005_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_C001_C005_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C001_C005_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C001_C005_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C001_C005_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov"]
12:28:00 PM : Video queued China
12:28:00 PM : Queued id=22162A9B-DB90-4517-867C-C676BC3E8E95,
name=China,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_C004_C003_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov"]
12:28:00 PM : Video queued Greenland
12:28:00 PM : Queued id=2F52E34C-39D4-4AB1-9025-8F7141FAA720,
name=Greenland,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G002_C002_PSNK_v03_HDR_PS_20180925_HDR_2K_tuned.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G002_C002_PSNK_v03_SDR_PS_20180925_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G002_C002_PSNK_v03_SDR_PS_20180925_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G002_C002_PSNK_v03_HDR_PS_20180925_HDR_4K_tuned.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_GL_G002_C002_PSNK_v03_SDR_PS_20180925_SDR_2K_AVC.mov"]
12:28:00 PM : Video queued Dubai
12:28:00 PM : Queued id=3FFA2A97-7D28-49EA-AA39-5BC9051B2745,
name=Dubai,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_DB_D001_C005_COMP_PSNK_v12_SDR_PS_20180912_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_HDR_PS_20180912_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D001_C005_COMP_PSNK_v12_HDR_PS_20180912_HDR_4K_HEVC.mov"]
12:28:00 PM : Video queued Sea
12:28:00 PM : Queued id=BA4ECA11-592F-4727-9221-D2A32A16EB28,
name=Sea,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A001_C007_SDR_20190717_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A001_C007_HDR_20190719_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A001_C007_SDR_20190717_SDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A001_C007_HDR_20190719_HDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/PA_A001_C007_SDR_20190717_SDR_2K_AVC.mov"]
12:28:00 PM : Video queued Sea
12:28:00 PM : Queued id=E580E5A5-0888-4BE8-A4CA-F74A18A643C3,
name=Sea,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A002_C009_SDR_20190730_ALT01_SDR_4K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A002_C009_HDR_20190730_ALT02_HDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A002_C009_SDR_20190730_ALT01_SDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/PA_A002_C009_SDR_20190730_ALT01_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/PA_A002_C009_HDR_20190730_ALT02_HDR_2K_HEVC.mov"]
12:28:00 PM : Video queued Sea
12:28:00 PM : Queued id=6143116D-03BB-485E-864E-A8CF58ACF6F1,
name=Sea,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/KP_A010_C002_HDR_20190717_HDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/KP_A010_C002_HDR_20190717_HDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/KP_A010_C002_SDR_20190717_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/KP_A010_C002_SDR_20190717_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/KP_A010_C002_SDR_20190717_SDR_2K_AVC.mov"]
12:28:00 PM : Video queued Sea
12:28:00 PM : Queued id=8C31B06F-91A4-4F7C-93ED-56146D7F48B9,
name=Sea,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/g201_TH_804_A001_8_SDR_20191031_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/g201_TH_804_A001_8_SDR_20191031_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/g201_TH_804_A001_8_HDR_20191031_HDR_2K_HEVC.mov", Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/g201_TH_804_A001_8_SDR_20191031_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/g201_TH_804_A001_8_HDR_20191031_HDR_4K_HEVC.mov"]
12:28:00 PM : Video queued Hawaii
12:28:00 PM : Queued id=499995FA-E51A-4ACE-8DFD-BDF8AFF6C943,
name=Hawaii,
type=video,
timeofDay=day,
urls=[Aerial.VideoFormat.v1080pHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_H005_C012_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHEVC: "https://sylvan.apple.com/Aerials/2x/Videos/comp_H005_C012_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov", Aerial.VideoFormat.v1080pH264: "https://sylvan.apple.com/Videos/comp_H005_C012_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov", Aerial.VideoFormat.v1080pHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_H005_C012_PS_v01_HDR_PS_20180925_HDR_2K_HEVC.mov", Aerial.VideoFormat.v4KHDR: "https://sylvan.apple.com/Aerials/2x/Videos/comp_H005_C012_PS_v01_HDR_PS_20180925_HDR_4K_HEVC.mov"]
12:28:00 PM : Starting download for content information
12:28:00 PM : Starting 4 streams with 123381465 each, for content length of 493525860
12:28:00 PM : last stream range: {370144395, 123381465}
12:28:00 PM : Starting download for range bytes=0-123381465
12:28:00 PM : Starting download for range bytes=123381465-246762930
12:28:00 PM : Starting download for range bytes=246762930-370144395
12:28:00 PM : Starting download for range bytes=370144395-493525860
12:28:25 PM : connectionDidFinishLoading
12:28:33 PM : connectionDidFinishLoading
12:28:34 PM : connectionDidFinishLoading
12:28:39 PM : connectionDidFinishLoading
12:28:39 PM : Finished downloading!
12:28:39 PM : Finished
12:28:39 PM : Video download finished
12:28:39 PM : Starting download for Sea
12:28:39 PM : Starting download for content information
12:28:39 PM : Starting 4 streams with 92716525 each, for content length of 370866100
12:28:39 PM : last stream range: {278149575, 92716525}
12:28:39 PM : Starting download for range bytes=0-92716525
12:28:40 PM : Starting download for range bytes=92716525-185433050
12:28:40 PM : Starting download for range bytes=185433050-278149575
12:28:40 PM : Starting download for range bytes=278149575-370866100
12:29:01 PM : connectionDidFinishLoading
12:29:04 PM : connectionDidFinishLoading
12:29:06 PM : connectionDidFinishLoading
12:29:09 PM : connectionDidFinishLoading
12:29:09 PM : Finished downloading!
12:29:09 PM : Finished
12:29:09 PM : Video download finished
12:29:09 PM : Starting download for China
12:29:09 PM : Starting download for content information
12:29:09 PM : Starting 4 streams with 85703486 each, for content length of 342813944
12:29:09 PM : last stream range: {257110458, 85703486}
12:29:09 PM : Starting download for range bytes=0-85703486
12:29:09 PM : Starting download for range bytes=85703486-171406972
12:29:10 PM : Starting download for range bytes=171406972-257110458
12:29:10 PM : Starting download for range bytes=257110458-342813944
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for China
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Greenland
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Dubai
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Sea
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Sea
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Sea
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Sea
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:10 PM : Starting download for Hawaii
12:29:10 PM : Starting download for content information
12:29:10 PM : Couldn't download video: A server with the specified hostname could not be found.
12:29:10 PM : Finished
12:29:10 PM : Connection fail: A server with the specified hostname could not be found.
12:29:10 PM : Video download finished with error/cancel
12:29:28 PM : connectionDidFinishLoading
12:29:30 PM : connectionDidFinishLoading
12:29:30 PM : connectionDidFinishLoading

**Comment by glouel** [comment]
That's weird. It looks like it downloaded a couple correctly but then failed, are you behind some sort of firewall ? Hostname is a very weird failure (dns) so that's pretty weird.  

I'd suggest trying again, you can try downloading one individually by clicking the little + just to check.

**Comment by Jimmbo** [comment]
No firewall. 

I started again and it worked. OTOH, the "show error" button never went away (even if I close and reopen Sys Prefs).

**Comment by glouel** [comment]
> No firewall.
> I started again and it worked.

Maybe your ISP had a hiccup or something ? Good thing it worked, this is pretty battle tested and I pretty much never get issues about downloads. 

> OTOH, the "show error" button never went away (even if I close and reopen Sys Prefs).

This may seem weird but when you close and come back, you haven't restarted Aerial, so the panel is still in the same state you left it. If you close system preferences and reopen it, the button will disappear. It's an oddity of how screensaver panels work with macOS ;)

**Comment by Jimmbo** [comment]
> Hostname is a very weird failure (dns) so that's pretty weird.

FWIW....

I just had tried to install an app update from App Store, and got a popup that "A server with the specified hostname could not be found". 

I found [a tip on apple.stackexchange](https://apple.stackexchange.com/questions/354197/macos-mojave-software-update-error-a-server-with-the-specified-hostname-could/371591#371591) that MacOS' Content Caching (in System Settings ➡︎ Sharing) may cause host name issues. I shut off Content Caching and App Store no longer reported host name issues. This may apply to my problems with Aerial, too, so I'm throwing this in here in case it's helpful to anyone in future.

**Comment by glouel** [comment]
Wow, that's... It's very likely that was your issue as the hostname lookup is done through macOS libraries in Swift for Aerial (browsers tend to have different rules though).

I'm not sure if they have a bug in their DNS cache resolution system or something, but that makes me wonder what exactly that "content caching" does ! 

Many thanks for providing me with an update though, I will add something to the FAQ when I get a sec !
