### ISSUE TITLE
Touchpad and Keyboard Unresponsive after Wake

### ISSUE THREAD

**Issue by nagyj2** [JohnCoates/Aerial#984]
I have just installed Aerial and have set up a custom .mov file as the only enabled screensaver. The screen goes to sleep as expected and upon wake, the lock screen functions like normal. However when I log in, the mouse _click_ and keyboard are unresponsive. The cursor moves with the trackpad. If I bring up Mission Control, the mouse and keyboard go back to normal. I have tried with 1.8.2 and 1.8.3beta11.

-  Mac model: MacBook Pro 16"
-  macOS version: Catalina 10.15.4
-  Monitor setup: Internal Laptop Screen

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4583446/AerialLog.txt)

**Comment by glouel** [comment]
Hi @nagyj2 

Let me try to clarify a bit:
- first, what you are experiencing, does it happen some of the time, all the time ?
- you mention that you do log in, so I assume that you can click/press a key to quit Aerial and bring the login prompt, correct ? Do you have a password prompt where you actually type your password ? And if so, can you type at that time and the issue happens afterwards ?

I don't think your custom mov is a concern, your log doesn't exhibit anything weird either. 

In general in Catalina, Aerial no longer has raw access to the keyboard/mouse at all, so it really doesn't do anything with it. So what you are experiencing sounds more like a macOS bug with certain specific conditions, I'll have to try and think back as there were some odd reports of some weird interactions in those issues, I'll try to find them again so you can have a look. 

There has been some focus issues with loginwindow and that's the first thing that comes to mind. Please try and clarify the two things above and I'll try and get back to  you. Thanks

**Comment by glouel** [comment]
@nagyj2 this is the post I was thinking about, specifically about mission control and some set of settings that caused issues previously, this may be an interesting read : https://github.com/JohnCoates/Aerial/issues/768#issuecomment-491473659

**Comment by nagyj2** [comment]
The problem is that the touchpad click and keyboard input does not respond after waking from sleep. To log in, I used the fingerprint reader. The prompt appears and I can type into it. Entering my password has the same problem with the touchpad and keyboard. This happens any time the laptop goes to sleep, even when using the default screensavers. Because it occurs with the default screensavers, it seems I may have an issue with another part of the laptop; I only just noticed it when using this software. I did disable the 3 checkboxes and they did not fix the problem. I do not run little snitch or any other firewall programs.

**Comment by glouel** [comment]
@nagyj2 thanks for clarifying ! And sorry about that bug, while this particular variant seems new to me (I'll have to try and think a bit if someone else didn't report something like that), there's been a lot of changes around screensavers in Catalina that sometimes just throws things off. 

My rough guess is some app is stealing the focus, capturing the inputs and making it look like they don't respond. And launching mission control just gives it back to you by removing focus from them. Login time is a bit special usually, so just clicking on the login field tend to not do anything that you would expect. 

As to which app does that, hard to know. I would focus on any "resident" app that you always run in the background and could maybe pop a window, this could be a likely culprit. There's also a script written by a user here : https://gist.github.com/luckman212/91cdd9a08e98a9f01214bdfde3057e85

It might tell you who took the input, although I'm afraid most of the times people tried that it's been more miss than hit. It's possible it's just loginwindow just misbehaving...

**Comment by glouel** [comment]
Closing this, please reopen if you want to investigate this further.
