### ISSUE TITLE
Where are the files stored that Aerial.saver downloads and displays?

### ISSUE THREAD

**Issue by jfrench11** [JohnCoates/Aerial#986]
Dear reader,

*** iMac (Retina 5K, 27-inch, 2017), macOS Mojave 10.14.6, Aerial.saver 1.8.1 ***

Can someone please tell me where Aerial.saver's downloaded screen saver files are located? If this is not the correct forum for asking such a question, please tell me how to reach the proper person.

Thanks,
John French
jfrench1@flash.net

**Comment by glouel** [comment]
Hi @jfrench11  !

Please check the "Removing the cache" section here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md#removing-the-cache

As you'll see, depending on when you installed Aerial, and how you installed it (for your user/for multiple users), there are multiple possible locations, but the `Caches` tab will point you to the correct one. 

Let me know if you don't find what you need.

**Comment by jfrench11** [comment]
Hi, Guillaume!

> On May 11, 2020, at 11:17 AM, Guillaume Louel <notifications@github.com> wrote:
> 
> 
> Hi @jfrench11 !
> 
> Please check the "Removing the cache" section here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md#removing-the-cache
> 
> As you'll see, depending on when you installed Aerial, and how you installed it (for your user/for multiple users), there are multiple possible locations, but the Caches tab will point you to the correct one.
> 
> Let me know if you don't find what you need.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

That was exactly what I was looking for. Thank you for the quick response.

Aerial is a magnificent and elegant app. Is there a way for me to contribute to your programming effort? I'm retired and by no means wealthy, but I like to reward in some small way those whose work I find useful.

Regards,
john

**Comment by glouel** [comment]
Glad you enjoy it thanks ! 

Answering your question, I did add a paypal link on the main page some time ago, but please don't feel obligated by any means. Link here : https://www.paypal.me/glouel/

**Comment by jfrench11** [comment]
Hi, Guillaume!

> Glad you enjoy it thanks !
> 
> Answering your question, I did add a paypal link on the main page some time ago, but please don't feel obligated by any means. Link here : https://www.paypal.me/glouel/

What is the URL of the "main page"?

No feeling of obligation whatsoever; purely gratitude and admiration. I deposited a small amount with PayPal; wish it could have been more.

Onward,
john

**Comment by glouel** [comment]
> Hi, Guillaume!
> Glad you enjoy it thanks ! Answering your question, I did add a paypal link on the main page some time ago, but please don't feel obligated by any means. Link here : https://www.paypal.me/glouel/
> What is the URL of the "main page"? 

Sorry that wasn't clear, the main project page is here : https://github.com/JohnCoates/Aerial

>No feeling of obligation whatsoever; purely gratitude and admiration. I deposited a small amount with PayPal; wish it could have been more. Onward, john

👍

**Comment by eternalstorms** [comment]
@jfrench11 Hi John. I'm sorry to hijack this thread for something completely unrelated, but John, you just wrote me a support mail (regarding my app ScreenFloat), and when I tried to reply to your mail, it came back to me with an "_is_blocked" error. My apologies to everyone here to write this here, but I have no other way of reaching John at this time.
John, if possible, please mail me from a different email address, or write me on twitter (@eternalstorms) or facebook (via the Eternal Storms Software facebook page). Thank you all for bearing with me.

**Comment by glouel** [comment]
@eternalstorms I'm not sure he follows here, as he's not really involved with Aerial much (despite the repo name). You should try to reach him at https://twitter.com/JohnCoatesDev instead.

**Comment by eternalstorms** [comment]
> @eternalstorms I'm not sure he follows here, as he's not really involved with Aerial much (despite the repo name). You should try to reach him at https://twitter.com/JohnCoatesDev instead.
Thank you for your help, @glouel! Is John Coates = @jfrench11, though? Thank you.

**Comment by glouel** [comment]
No he's @JohnCoates ...
