### ISSUE TITLE
Minor Check For New Videos Gripe

### ISSUE THREAD

**Issue by Jimmbo** [JohnCoates/Aerial#989]
Minor thing, but if I hit the  "Check Now" button to look for new videos, there should probably be a pop-up saying like "Nothing New This Time!" Dead-end processes increase anxiety! :)

Also, question: if I have the app set to download all HD videos, then when the weekly check-for-new happens, new ones will download automatically, correct?

**Comment by glouel** [comment]
@Jimmbo regarding "Check now", hmm, there is : 

![Capture d’écran 2020-05-25 à 18 22 17](https://user-images.githubusercontent.com/37544189/82830051-fd592080-9eb4-11ea-9814-68beb00a04b8.png)

One thing I noticed though, I didn't seem to give the window a focus, so it might be hidden somewhere, you should try exposé and see if you can find the window. If it's there then I need to change that to make it more obvious. 

Regarding your question yep, that's exactly how it works. Note though that this "season", there hasn't been a lot of changes on the feed, I think there was one in january (after the original september release with the sea videos) and that's it. But if new videos happen, they'll get downloaded automatically and added as enabled by default in your playlist.

**Comment by Jimmbo** [comment]
There are two "check now" boxes, one for new videos (per title of this thread), one for app updates of Aerial. 

The latter works as you say, but the former is unresponsive (unless, presumably, there are new videos).

**Comment by glouel** [comment]
Ha, sorry, got confused there. So yep when you click that it just look for new videos and updates the small line that says "Last checked on ..." . I should definitely improve that so that it's consistent on both checks ! Because if you click it twice the same day, you won't see any change in that line (as I just use the date there).
