### ISSUE TITLE
MAC won't come out of screen saver once starts

### ISSUE THREAD

**Issue by FlyinLimey** [JohnCoates/Aerial#991]
MAC OS 10.15.4
MacMini Late 2014
Screensaver v1.9 (was doing it on previous version too) 
Bluetooth Apple keyboard / wired USB mouse
2 Monitors, HDMI VS278 Display & VX2240w Display rotated 270deg (1050 x 1680)

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

** Screen saver starts and I couldn't get back to the regular desktop screens.  Mouse wouldn't wake it up, just kept scrolling to the next video.  KB wasn't able to do it either.  Was trying force quit 3 key combo, Apple+Q, was hearing error sound like 'unable to do what you're asking' noise when using KB.  So it was taking input but not waking up.  
First time I had no choice but to 4 second power button the MAC. 
Then I removed v1.8x and got the latest 1.9version.  confirmed old removed and set to trash.  
Started the screensaver using lower left hot corner.. wouldn't wake up again.  Started down the 4sec power button move and after about 2 seconds on that button it woke up and broke out of the screensaver.  I let go, didn't reset the MAC and entered this ticket before I have to likely remove Aerials :-(

**Comment by glouel** [comment]
Hi @FlyinLimey 

Sorry about that, there seems to be a variety of bugs when it comes to screensavers to Catalina and quitting the screensaver. Some if not most seem to be outside of my control sadly.

In general, some tips that may help : 
- go into updates tab in Aerial and uncheck the three checkboxes at the bottom
- make sure you don't have your iphone or ipad charging on your mac (for someone that was the cause of the hang)
- make sure that if you are using a firewall like little snitch, it's configured to allow Aerial
- make sure you don't have some app that tries to bring a window to the foreground and steal the focus from the screensaver

Some people have reported this kind of issue with Aerial and also 1st party screensavers like Flurry. Not everyone has exactly the same symptoms and it's pretty hard to track. You can find some of the reports people gave me so far here : https://github.com/JohnCoates/Aerial/issues/828

**Comment by FlyinLimey** [comment]
Looks like it was a really random MAC thing.. OR.. my apple watch unlock feature is helping it wake up.  So far over the last 24 hours this hasn't been an issue and I didn't change anything.  Thanks for the tips and I will reference this should it occur again.
