### ISSUE TITLE
[Feature Request] Don't show Battery Indicator if plugged in AND battery percentage is 100

### ISSUE THREAD

**Issue by daletman** [JohnCoates/Aerial#995]
I would like to have an option to say "Don't show Battery Indicator if plugged in AND battery percentage is 100". I use my MacBook a lot in desktop mode and don't need the battery information if this is the case and it does look cleaner without it. But when I'm not plugged in or my MacBook is charging it's very useful to see the battery percentage.

**Comment by glouel** [comment]
Hi @daletman 

That's a good idea. There's a bug I need to fix to make that work though, will let you know.

**Comment by glouel** [comment]
@daletman please give this version a shot : https://github.com/JohnCoates/Aerial/releases/download/v1.9.1beta1/Aerial.saver.zip

My very old macbook air battery is shot so I couldn't test it as much as I wanted. I'd be interested of a couple of things if you have a minute to report:
- launch Aerial with battery at 100%, unplug your power cord and wait a minute or five. Does the indicator show up again ?
- quit Aerial, launch Aerial with battery below 100% and plugged in, wait until it's charged, does it disappear ? 

Right now there's a 10s lag in this build between battery information updates, I may shorten that in a later build.

Thanks

**Comment by dVIAN13** [comment]
> * launch Aerial with battery at 100%, unplug your power cord and wait a minute or five. Does the indicator show up again ?

yes, it came back after about 3 minutes for me...

> * quit Aerial, launch Aerial with battery below 100% and plugged in, wait until it's charged, does it disappear ?

didn't have to quit, once the indicator showed up, I plugged power back in. Once it reached 100%, it disappeared.

**Comment by daletman** [comment]
> * launch Aerial with battery at 100%, unplug your power cord and wait a minute or five. Does the indicator show up again ?
I charged my MacBook to 100%, unplugged it, started Screen Saver. The Battery Indicator showed up for 1 second showing 100% and disappeared until the battery hit 99%

> * quit Aerial, launch Aerial with battery below 100% and plugged in, wait until it's charged, does it disappear ?
Yes, it does.

**Comment by glouel** [comment]
Thanks to both @dVIAN13 and @daletman for confirming it works ! Closing this.
