### ISSUE TITLE
[Feature Request] Info Box for Miscellaneous Section

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#997]
Good Afternoon, 

While viewing the settings today I went over the to Advanced tab and noticed something I hadn't before, the **Misc** section with the **Mute sound** setting. I realized I had no clue what this was for. 

Simple enhancement request: 

Can we add a _? button_ overlay that explains what this is? I cannot imagine I am the only one who is curious 😜 
<img width="780" alt="Screen Shot 2020-05-27 at 1 32 29 PM" src="https://user-images.githubusercontent.com/18543749/83053499-cc94fa80-a01e-11ea-8adf-ed207dabb6b3.png">

**Comment by glouel** [comment]
Ha, I've added that one during the betas and completely forgot about it, it's pretty inscrutable as is, you're right 🙈

So to explain, this is enabled by default and will not play sound with videos. It has 0 impact on regular Aerials. However, custom videos may have sound, so I muted sound, but someone requested the ability to unmute so here it is. A longer description is definitely warranted, maybe something like "Mute sound (applies to custom videos)" or something. I'm open to suggestions !

**Comment by ZV00** [comment]
Aha! That makes effect sense. I assumed it would mute sound but wasn’t clear on what that would mean. For example, does it affect notification sounds? If yes, that’s actually handy to me to be honest!! 

So depending on the answer to that I would say something like:

Mute custom video sound and/or notification sounds when Aerial is playing.

**Comment by glouel** [comment]
Just to clarify, it doesn't mute the sound globally, so I guess "Mute custom videos sound" or "Mute sound for custom videos" is the way to go ! I'll fix that in next beta thanks !

**Comment by ZV00** [comment]
Aww too bad. I’d actually love a global mute option... but that may not be possible. But yes, for this easy fix that should do great. Thanks!

**Comment by glouel** [comment]
That's been fixed for a while hmm :D
