### ISSUE TITLE
[Feature Request] Show weather temp in C or F

### ISSUE THREAD

**Issue by toxicatomicdog** [JohnCoates/Aerial#998]
I don't see an option to show celsius or fahrenheit. Can this be added or I'm missing the setting?

**Comment by glouel** [comment]
HI @toxicatomicdog 

It's there, but I admit it can look a bit hidden, I circled it below:

![Capture d’écran 2020-05-27 à 20 29 43](https://user-images.githubusercontent.com/37544189/83058638-f9660380-a058-11ea-9b89-cccfcc68f6ca.jpg)

**Comment by toxicatomicdog** [comment]
Thank you for pointing that out. I missed it completely.

Best regards,
Steve Poirier
