### ISSUE TITLE
Stuttering/Fan spinning on MBP 2018

### ISSUE THREAD

**Issue by glouel** [JohnCoates/Aerial#999]
Happens 100% of the time. Yea sounds good thanks for the time!

_Originally posted by @jonfoxnj in https://github.com/JohnCoates/Aerial/issues/940#issuecomment-634861199_

**Comment by glouel** [comment]
Ok so, considering it's happening 100% of the time, it's probably not the photo library thing.

Let me try and unpack a bit. You mentioned that you had no issue with SDR. Did you mean 4K HEVC ? Or 1080pH264 ?

Also, does it stutter or plays fine with the fan spinning ? 

What I'd like you to try is open a 4K HDR video from Aerial in Quicktime. Go to Aerial and right click a video that you have cached and select open in quicktime. Does it also stutter/fan spin or not ? We'll try to go from here. Thanks

**Comment by jonfoxnj** [comment]
4K HVEC, it has stuttered in the past after running for a while. Testing the video playback now.

**Comment by jonfoxnj** [comment]
Yea fan seems to spin up during playback thru Quicktime as well. Plays smooth.

**Comment by glouel** [comment]
Ok about 4K HEVC.

But you're saying this : 
> it has stuttered in the past after running for a while

Are you talking about HDR or 4K HEVC ? You said it happened 100% of the time so I'm not sure I follow. Please tell me what is happening exactly...

Regarding Quicktime, I suggest you launch "activity monitor", can you tell me the name of the CPU task eating your CPU and spinning up the fan ? 

If it spins in quicktime, it's likely that for some reason macOS is using CPU decoding instead of GPU accelerated decoding. If it's an issue in Quicktime, there's not much Aerial can do. As to why that happens, it's hard to know considering I'm not sure I actually understand what you are experiencing right now.

**Comment by jonfoxnj** [comment]
Ok so when I was on Mojave, I ran Aerial in 4K HVEC, never had the fans spin up. Since upgrading the Catalina and 4K HDR, the fans spin up every time Aerial runs. I retested Aerial on Catalina with 4K HVEC and the fans don’t spin up. When I play the 4K HDR video via quicktime or via Aerial the fans spin up ~2-3min in and i'll notice stuttering a few minutes later as well. 

I definitely think now its directly correlated with playing 4K HDR, Activity monitor is showing "WindowServer" as the main culprit using ~$%% CPU and 25% GPU, Quicktime is using no GPU during playback and only ~6% of CPU.

**Comment by glouel** [comment]
> Ok so when I was on Mojave, I ran Aerial in 4K HVEC, never had the fans spin up.

Ha ok, thanks for clarifying, this makes more sense.

> Since upgrading the Catalina and 4K HDR, the fans spin up every time Aerial runs. 

Ok !

> I retested Aerial on Catalina with 4K HVEC and the fans don’t spin up. When I play the 4K HDR video via quicktime or via Aerial the fans spin up ~2-3min in and i'll notice stuttering a few minutes later as well.
> 
> I definitely think now its directly correlated with playing 4K HDR, Activity monitor is showing "WindowServer" as the main culprit using ~40% CPU and 25% GPU, Quicktime is using no GPU during playback and only ~6% of CPU.

Window server, hmm. I'm not 100% sure but I think that could be the conversion from HDR to something displayable on your Mac that accounts for this. 

I had a quick look here and I also have highish CPU from windowserver when HDR content runs, have a look : 

![Capture d’écran 2020-05-27 à 22 05 59](https://user-images.githubusercontent.com/37544189/83067261-a7c47580-a066-11ea-8e73-e0942a7e0da2.jpg)

This is on a late 2015 iMac, the top line is the video decoding, that's what eats most of the CPU here as my iMac doesn't handle GPU acceleration for HEVC. But windowserver is pretty high and that's probably because of the tone mapping that's done to display HDR on a non HDR screen. 

That's my best guess here as to what makes it spin for you. There's probably not much to do except hope for some better implementation of that tone mapping in macOS.

**Comment by jonfoxnj** [comment]
Ok that actually makes so much sense. That's it though, I'm not outputting HDR to either my MBP display or TV (need to look into a bit more). Oddly enough even though their support site says my MBP display supports HDR, its really only content at 1080p. https://support.apple.com/en-hk/HT210980 I was under the impression Catalina brought native HDR to the system but its really only support of content right and really only up to 1080p. Definitely digging into it a bit more but you're 100% right its tone mapping the content to display properly on the nonHDR screens (Even though both support HDR). I'll let you know if anything else comes to light but I have to think this is the same for essentially anyone trying to run the 4k HDR videos. Prob switching back to 4k HEVC for now, the fan drives me nuts.

**Comment by glouel** [comment]
Oh, nice find with that support page. 

I have to say I'm a bit puzzled by what they mean by "1080p only", as to whether they picked that arbitrarily (because in practice it produced fan spinning and thus a bad experience) or for a real technical reason.

Since you don't see any high VTDecoderXPCService CPU usage on your end when quicktime is playing, it's not because of pure video decoding, so tone mapping is likely.

"HDR" is a bit of an umbrella term, so there's a lot of processing involved depending on the output. In the case of my iMac (and I assume your MBP), the screen is 10bit per component (instead of traditional 8bit). So are the videos (and interestingly, the 4K HEVC SDR are also encoded in 10bit). 

Apple HDR videos are encoded with "Dolby Vision" which does 10 bit and very high luminosity output. There seems to be some form of transform, the description on wikipedia (https://en.wikipedia.org/wiki/High-dynamic-range_video#Dolby_Vision) is pretty succinct, and that's probably what I called tone mapping earlier, the dolby vision process that ends up bringing it to something displayable on our displays.

Interestingly, when you play HDR on a Mac Pro, macOS does also some compositing, for example the small preview before you go into Aerial settings will have full brightness while the window looks dimmed in comparison. My understanding so far is that this is done by WindowServer and Apple doesn't exactly say what they do. I suppose that there are specific conversions path based on how bright your display can output and that has some non trivial cost. 

In any case thanks for the link, it's good knowledge to have as I think every MBP will hit the fan issue with Aerial, I'll try to put something about that in the FAQ tomorrow.

**Comment by glouel** [comment]
Ha, but I missed that part of your original message : TV via HDMI in clamshell

Soooo. My first suggestion would be, try on your internal display. I would love to know if you have massive spinning or not.

Second, I'd be interested to know if your TV (is it 4K ?) does 10bit/HDR/Dolby vision. That may be part of the equation.

**Comment by jonfoxnj** [comment]
Yes its 4k and HDR10 compatible. I'm outputting 4k @60hz via TB3, Catalina's not giving me an option to enable HDR natively and when I force HDR via the TV it's super saturated. VTDecoderXPCService CPU usage is actually around ~15% during HDR playback and ~9% during HEVC playback.

I screenshotted some iterations with activity monitor:

MBP HEVC
<img width="1512" alt="MBP SDR" src="https://user-images.githubusercontent.com/21955911/83074648-85b7fc80-a040-11ea-958c-3dd9a4763377.png">

MBP HDR
<img width="1511" alt="MBP HDR" src="https://user-images.githubusercontent.com/21955911/83074642-82247580-a040-11ea-8f21-6141b14876d9.png">

TV HEVC
<img width="1940" alt="TV SDR" src="https://user-images.githubusercontent.com/21955911/83074816-cf084c00-a040-11ea-8cff-89930b715021.png">
 
TV HDR
<img width="1522" alt="TV HDR" src="https://user-images.githubusercontent.com/21955911/83074841-d62f5a00-a040-11ea-92e9-10d5e4a1b383.png">

It seems like in terms of load on the GPU it's [MBP HEVC < TV HEVC < MBP HDR < TV HDR]

I'm noticing only significant fan spin up on TV HDR. I gave MBP HDR only ~5 minutes so I'm going to revert back to HDR in aerial and test for 15 minutes just on my MBP again. Figured I’d share the above for now.

**Comment by glouel** [comment]
> Yes its 4k and HDR10 compatible. I'm outputting 4k @60Hz via TB3

Thanks for the info, so you are using a TB3 -> HDMI adapter ? Apple says this on the page: 

> If you're using HDMI, make sure that the HDMI cable and adapter support HDR10. Apple recommends HDMI cables that have been tested with Apple TV 4K and a wide range of televisions, such as the Belkin UltraHD HDMI Cable. Compatible adapters include the Apple USB-C Digital AV Multiport Adapter and Belkin USB-C to HDMI Adapter.

They list only two specific adapters as compatible, what are you using on your end ? It's possible that some adapters may not do HDMI 2.1 (which I think is required for HDR?), the "classic" USB-C -> HDMI dongle may not be enough here, they especially mention this one from Apple which is not cheap : https://www.apple.com/shop/product/MUF82AM/A/usb-c-digital-av-multiport-adapter

> Catalina's not giving me an option to enable HDR natively and when I force HDR via the TV it's super saturated. 

Ok so it could be your dongle maybe, that would make sense as to why you can't enable HDR. 

> VTDecoderXPCService CPU usage is actually around ~15% during HDR playback and ~9% during HEVC playback.

Ok so that's low, and consistent with GPU decoding working correctly, so that door is closed for good ;)

> I screenshotted some iterations with activity monitor:
> It seems like in terms of load on the GPU it's [MBP HEVC < TV HEVC < MBP HDR < TV HDR]

Thanks for those. You had a time machine backup running while doing the TV testing, so that could add to the fan spinning a bit.

> I'm noticing only significant fan spin up on TV HDR. I gave MBP HDR only ~5 minutes so I'm going to revert back to HDR in aerial and test for 15 minutes just on my MBP again. Figured I’d share the above for now.

Sounds good, thanks a lot ! Please let me know about your dongle, I'm curious. Since you couldn't enable HDR, macOS does have to tonemap the video down to 8bit per component and that could be a slightly more expensive path in the windowserver code, could explain why you get some fan spinning on your TV.

**Comment by jonfoxnj** [comment]
HDR on MBP seems fine in terms of fan speed in the 10 minute test I did. I just noticed above too you can visibly see the difference of Catalina downgrading the HDR video to SDR in the screenshots above. If i play the same videos in HDR and SDR on my TV the HDR looks way better but the screenshots above say otherwise. I'll keep playing around with things and let you know if anything sticks out. Yea let me look into the dongle too.

**Comment by amy1499** [comment]
Hi there, I also got the stuttering video issue on a MBP 2013. It seems to be related to 4K HEVC files and not to the screensaver since the issue can be reproduced when opening this file type with Quicktime player directly. Both in 15.5.5 and 15.6.1 (pb 1) Thats HDR_4K_HEVC files only.

**Comment by glouel** [comment]
> Hi there, I also got the stuttering video issue on a MBP 2013. It seems to be related to 4K HEVC files and not to the screensaver since the issue can be reproduced when opening this file type with Quicktime player directly. Both in 15.5.5 and 15.6.1 (pb 1) Thats HDR_4K_HEVC files only.

Hi @amy1499 

Just to confirm, the CPU inside the 2013 MBP does not support hardware accelerated decoding of HEVC videos, so it's done on the CPU which cause stuttering and spinning. You can get more info with the little help bubble next to the format picker in Aerial, it should tell you what your mac supports.

So not surprising you get the same issue with Quicktime. "1080p H.264" is hardware decoded (so no CPU load/stuttering/fan spinning) and is the "safe" choice for that generation (unless you want to manually convert the 4K videos to H.264 which can take some time but if you really want 4K, that's an option).

**Comment by amy1499** [comment]
Thanks for the heads up. Switched it to H264. Removed 2k and 4k HEVC from downloaded items ApplicationSupport/Aerial. No issues. 
2k HEVC clips also showed the stuttering issue on MBP 13” 2012.

Thanks again for the quick answer.
